### ISSUE TITLE
Two projects with the same name cannot be referenced

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1020]
From here: http://stackoverflow.com/questions/27704235/moving-solution-to-asp-net-vnext-unable-to-reference-assembly

It might be by design but if that's the case we need to provide better diagnostics.

Long story short: the project in `src` and the one in `test` have the same name. You cannot reference the project in `src` from `test`

**Comment by davidfowl** [comment]
@ChengTian fixed this by reporting the ambiguous projects.

**Comment by davidfowl** [comment]
What work is left here?

**Comment by ChengTian** [comment]
I guess there is no further work needs to be done
