### ISSUE TITLE
Print feed does not exist warning with a different color (like yellow)

### ISSUE THREAD

**Issue by Praburaj** [aspnet/DNX#1051]
This is filed after a comment in this PR https://github.com/aspnet/KRuntime/pull/1032#issuecomment-69368698

![image](https://cloud.githubusercontent.com/assets/2294732/5686387/461aeb16-97f7-11e4-9acd-13b085e5e164.png)

When `kpm` finds it cannot resolve a feed (local or remote) it will be good to print a warning with a different color. Today we print it like plain logs which makes it difficult to see something is failing. 

/CC @ChengTian

**Comment by BrennanConroy** [comment]
![warningcolor](https://cloud.githubusercontent.com/assets/7574801/6311000/89ef277c-b911-11e4-8de9-9e30ed7d052d.PNG)

![remotewarning](https://cloud.githubusercontent.com/assets/7574801/6311059/24534f1e-b912-11e4-87c5-1e51cad4c4ce.PNG)

**Comment by Praburaj** [comment]
@BrennanConroy is there a PR for this? 

And it would be good to make the word `Warning:` in yellow.

**Comment by BrennanConroy** [comment]
No PR yet. Was wanting your feedback first

Sent from my HTC

----- Reply message -----

**Comment by BrennanConroy** [comment]
If we made ```Warning:``` yellow we would probably need to do that across all repos to be consistent.
