### ISSUE TITLE
Parallelize package download in "kpm restore"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1062]
Optimization can be done here:
https://github.com/aspnet/KRuntime/blob/dev/src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs#L387

**Comment by muratg** [comment]
This assumes you're using a feed format where the nuspec and the nupkg are available independently.

**Comment by muratg** [comment]
@pranavkm is this partially implemented already?

**Comment by pranavkm** [comment]
Yup, this was addressed as part of https://github.com/aspnet/XRE/commit/7144ddcb0b43da44b6d18f0ed76244387b512f14

**Comment by muratg** [comment]
Closing this one.  If there's still work to be done, feel free to reopen.

**Comment by muratg** [comment]
Actually closing now :)
