### ISSUE TITLE
`source` is a bashism

### ISSUE THREAD

**Issue by georgesimms** [aspnet/dnx#1064]
`build.sh` doesn't specify it's meant to be run with bash but it uses `source`. This could be changed to `.`

**Comment by muratg** [comment]
Can you give a specific example?

**Comment by georgesimms** [comment]
line 31 of build.sh

**Comment by davidfowl** [comment]
The build script requires bash

**Comment by georgesimms** [comment]
Ok. It now  has a proper shebang
