### ISSUE TITLE
Project.json Include and Exclude File patterns 

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1067]
/cc: @loudej @davidfowl

**Comment by davidfowl** [comment]
Email dump 
```
We will have following project json elements:
 
Compile (+ includes files to be compiled)
<- compileExclude (- globbing rules excluding files or folders from compilation, overrides “compile”)
<- compileFiles ( + individual files included to compilation, overrides “compileExclude”)
Content (+ includes content files)
<- contentExclude (- globbing rules excluding files or folders from packing, overrides “content”)
        <- contentFiles (+  individually included content files, overrides “contentExclude”)
Exclude (- has highest priority, overrides everything in “compile”and “content”. If file/folder is in “exclude” globbing, it is treated s excluded from project completely and should not be displayed in Solution Explorer)
<- projectFiles (+includes individual files to the project and overrides “exclude”)
So if user, right clicks in the file in Solution Explorer and excludes file, it is added as globbing rule to “exclude” (and removed from “projectFiles” if it is there) and removed from Solution Explorer.
Then if user wants to include file back, click on Show All Files in Solution Explorer, right click and “Include file”. This will add a file to “projectFiles” list.
Now if file is a .cs file, it will be treated as compilable only if it survives the “compile”/”compileExclude”/”compileFiles” filter (Question: if it appears excluded by old compile rules should we automatically add cs files to “compileFiles” list? Or do nothing and let user to change cs file “Excluded from compile” setting again?
Same for content file
```

**Comment by troydai** [comment]
Is this the project will suppose to look like?
```JSON
{
    "Compile":
    {
        "pattern": "**/*.cs;../sdk/**/*.cs",
        "exclude": "compile/preprocess/**/*.cs;samples/**/*.cs",
        "include": "../lib/shared/tool.cs"
    },
    "Content":
    {
        "pattern": "**/*.cs;../sdk/**/*.cs",
        "exclude": "compile/preprocess/**/*.cs;samples/**/*.cs",
        "include": "../lib/shared/tool.cs"
    }
    "Exclude":
    {
        "pattern": "bin/**;obj/**;*.config",
        "projectFiles": "web.config"
    }
}
```

Questions (and answer I assumed):
1. Non-exist single file path in include, report error? Yes
2. Support wild card in "includeFiles"? No
3. Non-exist single file path in includeFiles, report error? Yes 
4. Do `BundleExclude`, `Preprocess`, `Resources`, and `Shared` adopt the same pattern? Yes
5. Can the `pattern` section for each group be omitted? Yes
6. What will happen if `pattern` is missing? Use the default patterns.
7. Prevously `Exclude` doesn't participate in content files globbing. Do we start to do so? I assume yes?
8. Does `Exclude` impact `BundleExclude`, `Preprocess`, `Resources`, `Shared`? No

**Comment by abpiskunov** [comment]
Looks good to me. One question: could folders be added to "include" elements along with individual files?

**Comment by davidfowl** [comment]
That doesn't look good to me. The sections are just expressed in the json file, they were just supposed to be titles.

**Comment by davidfowl** [comment]
@abpiskunov no, they can't.

**Comment by abpiskunov** [comment]
Ah yes, if so then thingFiles explicitly has only files and my question is irrelevant. One exclusion from pattern will be the exclude section:
  "exclude":[],
  "projectFiles":[]

It does not follow the pattern.

**Comment by troydai** [comment]
Need better pattern for exclude, of course. So how about
```
exclude
excludeExempt
```

Also, the compile files using name `codes` now, are we going to retired it?

**Comment by lodejard** [comment]
I think it was something like this...

### project.json properties, and their defaults
```
"compile": [ "**/*.cs" ],
"compileExclude": [],
"compileFiles": [],

"content": [ "**/*" ],
"contentExclude": [],
"contentFiles": [],

"preprocess": [ "compiler/preprocess/**/*.cs" ]
"preprocessExclude": []
"preprocessFiles": []

"resources": [ "compiler/resources/**/*" ]
"resourcesExclude": []
"resourcesFiles": []

"shared": [ "shared/**/*.cs" ],
"sharedExclude": [],
"sharedFiles": [],

"exclude": [], /* template adds "wwwroot" and other allways-excluded knock-outs here */
"excludeBuiltIn": [ "bin/**", "obj/**", "**/.*/**", "*.kproj", etc ]
```
### actual files lists, and how they're calculated
```
CompileList =
  +Glob( +compile -compileExclude -exclude -excludeBuiltIn) 
  -SharedList
  -PreprocessList
  +Literal( +compileFiles )

PreprocessList =
  +Glob( +preprocess -preprocessExclude -exclude -excludeBuiltIn) 
  +Literal( +preprocessFiles )

SharedList =
  +Glob( +shared -sharedExclude -exclude -excludeBuiltIn) 
  +Literal( +sharedFiles )

ResourcesList=
  +Glob( +resource -resourceExclude -exclude -excludeBuiltIn) 
  +Literal( +resourceFiles )

ContentList =
  +Glob( +content -contentExclude -exclude -excludeBuiltIn) 
  -CompileList
  -PreprocessList
  -SharedList
  -ResourcesList
  +Literal( +contentFiles )
```
### Usage and example of file lists
```
PreprocessList becomes syntax trees for preprocess temp assembly (like PrecompiledViews.cs)
CompileList becomes syntax trees for main assembly (like Program.cs)
ResourcesList becomes embedded resources for main assembly (like Resources.resx)
SharedList are included in the nupkg during pack  (like internal class MyHelper.cs)
ContentList are included in the approot during bundle (like config.json)
'wwwroot' is copied entirely to webroot during bundle (like web.config)
```
@ChengTian can you take a look at this to see if it breaks any of the things we do today?

**Comment by ChengTian** [comment]
Looks safe to use :+1:

**Comment by camMCC** [comment]
Chiming in because I was just dealing with this today in my project.

Since I have done quite a bit of work in the past with grunt.js my first instinct was to use the globbing patterns that are typical in a simple gruntfile.  It would be nice to see the ability to use the negation globbing pattern in the project.json file rather than being forced to have a separate property.

something like:

```
{
    "resources": [
        "**/*.js",
        "!node_modules"
    ]
}
```

While I do like the option to have a more generic exclude pattern that can be applied, sometimes it is rather nice to apply step by step globbing and exclude filtering so that you can include everything in a directory and then exclude just 1 known file without having to jump around to a different property with a different context feel.  It just helps keep everything that matters about 1 specific subject in 1 place.

**Comment by davidfowl** [comment]
If we choose to do excludes via `!foo` that's actually separate from this feature. We're still going to add the extra properties because it can be used by tools to easily edit the json file via UI gestures without having to do set logic on globbing patterns.

**Comment by troydai** [comment]
@abpiskunov this change is merged. will appear in next KRE build. you can get it from volatile feed now.

**Comment by abpiskunov** [comment]
Great! thanks

**Comment by DamianEdwards** [comment]
This is reproing again. See repro project at https://github.com/DamianEdwards/BundleExcludeLongPaths
Clone that and try to `dnu publish` it from the command line.

**Comment by troydai** [comment]
Looks like a regression. I'll look into it and add tests to guard this scenario.

**Comment by troydai** [comment]
In both scenarios the errors are caused by the long path under `node_modules` folder.

**Comment by muratg** [comment]
@troydai is it a regression?

**Comment by troydai** [comment]
I'm not sure, the scenario is not covered in the automation case. Base on @DamianEdwards 's experience, it sounds like a regression.

**Comment by davidfowl** [comment]
Yes it looks like a regression:

**Comment by troydai** [comment]
I'm replacing all the `DirectoryInfo` and `FileInfo` instances with `Directory` and `File` static methods calling.

**Comment by troydai** [comment]
I'll close this issue. Bug is being tracked by https://github.com/aspnet/dnx/issues/1500

**Comment by back5576** [comment]
What is the formal definition of the pattern syntax?
And specifically, what would be a pattern to exclude files which begin with a # character?

**Comment by MelbourneDeveloper** [comment]
Is there actually a way to exclude files using the project.json file now?

**Comment by smbecker** [comment]
https://github.com/aspnet/Announcements/issues/175

**Comment by MelbourneDeveloper** [comment]
It doesn't work.
