### ISSUE TITLE
Add support for packages containing ICompileModule

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#1072]
* Scan dependencies for Preprocess flag
* Load 'em up
* Give them to RoslynCompiler somehow
* :sparkles: Run them :sparkles:

**Comment by anurse** [comment]
This will likely be part of dev-dependencies work in the New Runtime.

**Comment by muratg** [comment]
Moved to beta6 as per the discussions around pending runtime work.

**Comment by per-samuelsson** [comment]
Whats the status of this one? It says "Ready", but it's in the backlog milestone. Any info on your thinking regarding this?

**Comment by muratg** [comment]
This issue was moved to dotnet/roslyn#7467
