### ISSUE TITLE
Support for iconUrl and owners in project.json

### ISSUE THREAD

**Issue by djanosik** [aspnet/dnx#1089]
Hi there,

I was thinking I could convert my projects to vNext class libraries. Unfortunately, I've found it is not possible to specify *iconUrl* and *owners* of the generated *.nupkg package. I can't publish packages without my icons ;) Please make it supported.

Is it possible to specify "global" package metadata (authors, etc.) in `global.json`? I don't want to repeat everything in every `project.json`.

Thank you!

**Comment by Eilon** [comment]
Just to confirm, does it work if you *do* specify the metadata in `project.json`? I thought that was supposed to work. But yeah `global.json` support would be convenient for some of these super common properties.

**Comment by djanosik** [comment]
Yes... authors, tags, projectUrl and other metadata work as expected.

**Comment by Eilon** [comment]
OK cool. So is the bug about `project.json` at all or just about `global.json`?

**Comment by djanosik** [comment]
It is about *owners* and *iconUrl* in *project.json* and other metadata in *global.json*.

**Comment by davidfowl** [comment]
Let's separate the 2 features. One is about nuspec parity. The other is a new feature inheriting some properties from global.json. Open another issue for that.

**Comment by davidfowl** [comment]
@djanosik do you want to code this up and send a pull request?

**Comment by djanosik** [comment]
No I don't ;)
