### ISSUE TITLE
Serviceable package marker

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1097]
We need a way to specify that a package is serviceable. The feature is needed because we only leave breadcrumbs for the marked packages

PR for breadcrumbs: https://github.com/aspnet/KRuntime/pull/1078

**Comment by victorhurdugaci** [comment]
@davidfowl I'm assigning this to you since you mentioned that you are going to talk to the NuGet team

**Comment by glennc** [comment]
I think we are going to pivot on how we do breadcrumbs. Come talk to me about it.

**Comment by muratg** [comment]
@victorhurdugaci let's get this prioritized. Fundamentals team has started testing these things already. :)

**Comment by victorhurdugaci** [comment]
@ChengTian please resolve this when you merge the serviceable changes
