### ISSUE TITLE
Servicing: KRuntime should listen for changes to the servicing index file

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/dnx#1101]
Currently we have no way for servicing patches to detect which processes have the KRE loaded, so any servicing patch we release is going to have to be pessimistic and reboot the machine.  If the KRE were instead to hook up a file change monitor to the servicing index file, the patch might be able to rely on this "applications reset themselves" behavior and not have to reset the machine.

**Comment by victorhurdugaci** [comment]
A few questions:

1. Should the current process react to *any* change in the servicing index or only if there is an entry that affects what it has loaded?
2. How should the process react when the servicing index notification comes? Does it just kill itself?

**Comment by victorhurdugaci** [comment]
@lodejard @GrabYourPitchforks ?

**Comment by victorhurdugaci** [comment]
@blowdart, Levi suggested to run this by you. He thinks that we might not need this for v1 because we do not have a safe way of stopping a running app that we know nothing about. What do you think?

**Comment by davidfowl** [comment]
We shouldn't need this for v1.

**Comment by blowdart** [comment]
If the patches trigger a reboot we have parity with the existing poor behaviour. Improvements can come later.

**Comment by davidfowl** [comment]
We decided not do do this

/cc @muratg @moozzyk
