### ISSUE TITLE
ScriptExecutor should set an encoding when it starts a process

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#1103]
In VS when we create a new web application, the package manager log shows these lines at the end:

[4mRunning "bower:install" (bower) task[24m
[31mFatal error: Failed to execute "git ls-remote --tags --heads git://github.com/twbs/bootstrap.git", exit code of #-532462766[39m

There are some spurious chanracters like '[4m', this is because ScriptExecutor starts bower process without setting an encoding.

**Comment by barrytang** [comment]
@glennc, so this is not a bug level fix and that's why it got moved to the backlog? I am pretty you have seen the experience and it is quite ugly. Ideally, we should fix this for VS RC but probably too late?

**Comment by barrytang** [comment]
Adding @Eilon and @DamianEdwards. Can we fix this?

**Comment by Eilon** [comment]
@muratg

**Comment by troydai** [comment]
Can't repo. Need to confirm with @PradeepKadubandi if this is still an issue.

**Comment by glennc** [comment]
@troydai Did you confirm with @PradeepKadubandi?

**Comment by troydai** [comment]
Confirmed. Won't repo.
