### ISSUE TITLE
Move ILoggerFactory down the stack so it can be used in DNX

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1118]
See the comments here https://github.com/aspnet/XRE/pull/1078

And log servicing messages

**Comment by blowdart** [comment]
I have to consider not raising serviceability problems front and centre a bug, rather than an enhancement,

**Comment by victorhurdugaci** [comment]
Marked as bug :beetle:

**Comment by blowdart** [comment]
Thanks

**Comment by davidfowl** [comment]
How is this a bug?

**Comment by blowdart** [comment]
Hiding a huge gaping security problem in such a way that a user won't discover it unless it's a full moon, they're standing on one leg and have mistletoe tucked behind their left ear is, to my mind, not an enhancement but a gaping bug.

**Comment by davidfowl** [comment]
This bug has nothing to do with security. Look at the title.

**Comment by blowdart** [comment]
Then move the bug component to a bug, rather than rewriting history ya muppet.

**Comment by blowdart** [comment]
There. #1122. Are we a happy camper now @davidfowl ?

**Comment by davidfowl** [comment]
@blowdart :grin:

**Comment by victorhurdugaci** [comment]
@glennc @davidfowl  can we talk about this in the next design meeting?

**Comment by davidfowl** [comment]
Closing this issue as we cannot do this.
