### ISSUE TITLE
DNX needs to inform users when servicing is not possible

### ISSUE THREAD

**Issue by blowdart** [aspnet/dnx#1122]
Currently nothing happens if the breadcrumb directory does not exist. This is a problem.

When XRE on Windows starts and cannot find the breadcrumb directory it needs to inform the user of this problem in a discoverable way.

And by discoverable I don't mean sending something to an ilogger (once it's moved downwards by #1118) in the vain hope that a listener has been configured, I'm meaning write to the console and the event log by default, with a way to disable in case it's on purpose.

**Comment by victorhurdugaci** [comment]
Moving this to `1.0.0` because by then we should have logging in XRE.

**Comment by muratg** [comment]
We plan to make servicing and security related work a "theme" in beta6.

**Comment by victorhurdugaci** [comment]
Design meeting result: ETW is complicated and it doesn't work cross platform. The solution is to have en environment variable that one can set. If that variable is set, `dnx` will not start if servicing is not possible.

**Comment by blowdart** [comment]
Then, obviously, as you expected, on OSes where we support servicing startup should stop by default.

Then environment variable should be an indication the machine administrator is opting out of caring about updates.

**Comment by BrennanConroy** [comment]
@victorhurdugaci Looks like this should be closed?

**Comment by victorhurdugaci** [comment]
Yup, it was fixed
