### ISSUE TITLE
'kpm --version' does not return the installed version on Mono

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnx#1132]
With the command `k` being renamed to `dotnet` running `dotnet --version` returns `0.0.0.0` instead of the version. Although `k --version` still returns the correct value

**Comment by ChengTian** [comment]
What's the runtime version and OS used? Cannot reproduce with `dotnet-clr-win-x86-1.0.0-beta4-10991`.

![capture](https://cloud.githubusercontent.com/assets/1383883/5909705/cac1dbb8-a567-11e4-88b3-caf756d485c2.PNG)

BTW, just a small clarification, k wasn't renamed, klr was renamed to dotnet.

**Comment by suhasj** [comment]
Sorry I did not check if for windows. This is happening on Mono with the latest version. I'll update the title

**Comment by ChengTian** [comment]
Checked `dotnet.mono.managed.dll` with reflector. Seems we forget to specify version info when building this dll:
![capture](https://cloud.githubusercontent.com/assets/1383883/5912071/17dcb7fe-a583-11e4-927d-530041b184e2.PNG)

**Comment by davidfowl** [comment]
It's been that way for a while. We need to change the build process to add an AssemblyInfo file.

**Comment by Praburaj** [comment]
Currently `k --version` does return the right version on mono. Will revisit this when we rename it to something other than `k`.
