### ISSUE TITLE
HelloMetaProgramming/ICompileModule needs better documentation

### ISSUE THREAD

**Issue by m0sa** [aspnet/dnx#1134]
At least on of HelloMetaProgramming.cs or ICompileModule.cs should contain information about the XRE only invoking ICompileModule implementations from paths matching the [preprocess pattern](https://github.com/aspnet/XRE/blob/07fd900f492cea1b285cdbbd5408dbc1d4aab422/src/Microsoft.Framework.Runtime/Project.cs#L29). I just spent way to much time figuring that trivial fact out by browsing through the source code.

**Comment by mgravell** [comment]
Is this still as represented here? https://github.com/aspnet/dnx/issues/39

(waits patiently for documentation...)

**Comment by muratg** [comment]
This issue was moved to dotnet/roslyn#7466
