### ISSUE TITLE
KRE should support loading assemblies for TFMs "net40-client" and "net40-full"

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1138]
As per http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package, the .NET Framework 4.0 shipped in two versions: Client & Full profile. Per that, NuGet supports TFM folders called `net40-client` and `net40-full`. The KRE should be able to load from either of these folders safely when running on .NET Framework.

This is blocking the creating of the SignalR Service Bus scale-out package as the Service Bus client NuGet package uses the `net40-full` folder name.

**Comment by davidfowl** [comment]
We shouldn't create any packages with those monikers. They are deprecated. Conceptions should work fine but producing them makes no sense.

**Comment by DamianEdwards** [comment]
Agreed, just need to support consuming them

-----Original Message-----

**Comment by muratg** [comment]
@victorhurdugaci please sync up with Justin from nuget team on this one.

**Comment by davidfowl** [comment]
Turns out this has nothing to do with the TFM but instead has to do with how service bus declares its dependencies. I've contacted them and there's a workaround you can apply in project.json to make this work. I'm going to close this for now.
