### ISSUE TITLE
DTH leaks a thread when clients disconnect

### ISSUE THREAD

**Issue by jrieken** [aspnet/dnx#1148]
@davidfowl - as discussed and exposed by Omnisharp

**Comment by muratg** [comment]
@troydai please sync-up on @davidfowl if you're not up to date on the leak. We can move this to beta 7 as well.

**Comment by troydai** [comment]
@muratg talked to @davidfowl just now, let's move this out of beta8 for now.

**Comment by troydai** [comment]
Hi @jrieken , it has been 9 months since this this issue was filed. Do you still repo this issue? If you haven't tried out this issue recently, can you let me know how you repo and detected this issue?

**Comment by jrieken** [comment]
You can reproduce this when using OmniSharp and DTH. There is code in OmniSharp that tries to connect to DTH in short intervals such that this message (https://github.com/aspnet/dnx/blob/6e6d83951a8d80dc43c82140e3cace69b0bc399d/src/Microsoft.Dnx.DesignTimeHost/Program.cs#L84) is printed twice.

<img width="421" alt="screen shot 2015-10-07 at 09 44 27" src="https://cloud.githubusercontent.com/assets/1794099/10331744/0658807c-6cd8-11e5-97a4-115e0cacfc16.png">

**Comment by troydai** [comment]
Thanks @jrieken. I'll look into this.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#598
