### ISSUE TITLE
Change IApplicaitonEnvironment to return appbase as directoryinfo

### ISSUE THREAD

**Issue by glennc** [aspnet/DNX#1160]
Instead of a string.

**Comment by davidfowl** [comment]
Why?

**Comment by glennc** [comment]
why not? I don't remember why I filed this, but if it's directory info then I can do things like GetFiles as well as get FullName to use the string if that's what I want. Is there a strong reason that it should be a string?

**Comment by davidfowl** [comment]
I don't see a reason to do it.
