### ISSUE TITLE
Support kpm bundle copying all output to a single folder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1182]
This will make it possible to run on app models that don't support loading from anywhere but the location where the runtime resides.

/cc @ChengTian

**Comment by davidfowl** [comment]
https://github.com/aspnet/XRE/tree/bundle-one-folder I started a prototype here. A few things that we need to consider:
- It should probably fail when you pass multiple frameworks or runtimes
- Copying the minimal runtime required based on what other dependencies were used in the application itself and what is minimally required by the runtime.
- Multiple runtimes should fail as well. Basically anything that would cause it to overwrite files in the same folder should fail.

**Comment by ChengTian** [comment]
@davidfowl 

`Assembly.GetReferencedAssemblies()` is not available in CoreCLR. So we are unable to calculate the minimal runtime assembly closure on CoreCLR.

As a temporary workaround, I am copying all runtime assemblies if current `kpm bundle --one-folder` is running on CoreCLR.

**Comment by davidfowl** [comment]
@ChengTian we actually can do that without `Assembly.GetReferencedAssemblies()` (we shouldn't be loading anything anyways). Look at what `kpm list` does to get the assembly closure

**Comment by ChengTian** [comment]
@davidfowl , `dnu publish --one-folder`. Who needs this feature? Should this be beta5 issue?

**Comment by ChengTian** [comment]
Talked to @davidfowl , this is for some folks from CoreCLR team. It's not urgent issue and can be put to backlog.
