### ISSUE TITLE
Use flat list as DSL describing folder structure in functional tests

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1184]
Replace current JSON-based DSL with the following approach:
```c#
var dirTree = DirTree.CreateFromList(
  "bin/",  // Empty folder
  "src/HelloWorld.cs",
  "src/utils/Utils.cs"
)
```

See discussion at: https://github.com/aspnet/XRE/pull/1175/files#r24285922

**Comment by troydai** [comment]
:+1:

**Comment by ChengTian** [comment]
@davidfowl , it's better to finish this before adding new tests. Tests for `kpm bundle --no-source` will come after this today.

**Comment by ChengTian** [comment]
We chose another way to represent dir structures. Closing this.
