### ISSUE TITLE
Ensure “COM+_Entry_Point” symbol is added to modules to support F10/F11

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#1192]
There was a pretty long email thread about F10/F11 in console apps don't start debugging on the first line in Program.cs/Main. Debugger team applied a partial fix, but from runtime side we need to make sure that “COM+_Entry_Point” symbol is added to our modules for debugger to find entry point to a module. See TFS bug for more details: 1114153

**Comment by davidfowl** [comment]
Not required
