### ISSUE TITLE
Create a custom HostExecutionContextManager for .NET 4.5.1 host that flows current culture across threads

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1211]

**Comment by muratg** [comment]
@DamianEdwards if you're planning to do this at the same time as the CoreCLR one, please feel free to self-assign.

**Comment by davidfowl** [comment]
@troydai Test out this PR first,https://github.com/aspnet/XRE/pull/953

**Comment by troydai** [comment]
#953 works.

**Comment by troydai** [comment]
Update: quirk won't work on Desktop when the app domain info's target framework name is set to .net framework 4.5.1. It only fixes culture flow issue on 4.6.

**Comment by troydai** [comment]
Update: change target framework name to 4.6 won't fix the async culture flow issue on Desktop.

**Comment by troydai** [comment]
3a62febd2923fa556a31c80bc574feccdb32c061
https://github.com/aspnet/Helios/commit/7078090f7fc0f8288db4b1e2a881da19f2d525bd
