### ISSUE TITLE
Use Matcher to exclude files during bundling

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1212]
https://github.com/aspnet/XRE/blob/94add15fefff3484f2204bc977bd7373af5dd022/src/Microsoft.Framework.PackageManager/Bundle/BundleProject.cs#L264

There is logic in bundle to exclude specified files from final output. It looks like a proper candidate or matcher consumer.

**Comment by troydai** [comment]
@glennc @muratg need triage. I think we need this.

**Comment by muratg** [comment]
@ChengTian Would Matcher be applicable for this case?

**Comment by muratg** [comment]
Backlogging for now.  We can bring it back if there's interest and we can get resources to work on it.

**Comment by davidfowl** [comment]
@troydai Do we need this?

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#597
