### ISSUE TITLE
Lock entries should be sorted in a consistent manner to avoid conflicts

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1221]
To avoid potential merge conflicts, the lock file should have sorted:

- Dependencies
- File list
- Framework assemblies

**Comment by muratg** [comment]
@anurse Is the lock file format finalized?  And is sorting as part of that?

**Comment by BrennanConroy** [comment]
39a75d9a2afa92a159b381f500d51ff82c9e109f
