### ISSUE TITLE
remove overwrite from kpm

### ISSUE THREAD

**Issue by glennc** [aspnet/DNX#1227]
Overwrite was created for the scenario of packing two applications into the same output directory. In that scenario you would want to copy the output into the folder, but not try and duplicate all the packages.

Given that people aren't trying to do this, and the overwrite command is constantly misunderstood and mislabeled we will remove it.

**Comment by muratg** [comment]
@BrennanConroy Make sure you check with tooling team, MVC and @troydai to ensure this doesn't break them.  They might need to remove this switch from their scripts.  Also check stress CI as well.

**Comment by troydai** [comment]
It is used for once instance in perf infrastructure, The parameter is actually quite handy when we auto-deploy a performance tool, save a delete command. It is not critical though, so I'm ok with removing it. 

Reference 
https://github.com/aspnet/Perf/blob/751fa4aafc42fc1c03018de49dcee40966cc97d3/tools/KPerf.TestManager/deploy.ps1#L36

**Comment by muratg** [comment]
@barrytang is Tooling team OK with this?

**Comment by barrytang** [comment]
@vijayrkn?

**Comment by BrennanConroy** [comment]
ping

**Comment by BrennanConroy** [comment]
Tooling team has made a fix on their side.
What do we want to do in bundle now as far as overwriting files, never overwrite, or always overwrite?

**Comment by vijayrkn** [comment]
Bundle should always overwrite files.
