### ISSUE TITLE
Can't reference two shared source packages that depend on same shared source package. (shared sources should be transitive)

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/dnx#1237]
Right now if I have the following project structure were all projects are shared source projects:
```
   / -- B
A 
   \ -- C
```
I'm unable to utilize both package `B` & `C` in the same application like so:
```
         / -- B -- \
TestApp             A
         \ -- C -- /
```
This is due to the sources of `A` being embedded into both `B` and `C`: 
```
B: B.cs, A.cs
C: C.cs, A.cs
```
Which results in duplicate types for the `A.cs` in a test app. Talked with @loudej and @ChengTian about potential fixes for this issue and @loudej suggested we make shared sources transitive where the nupkg for `B` would contain a dependency on shared source `A`. This way package resolution can only bring in one copy of `A.cs` and essentially only ever do 1 copy of all sources from shared sources.

@loudej / @ChengTian feel free to add additional details.

**Comment by dougbu** [comment]
> unable to utilize

@NTaylorMullen what are the symptoms when C has a build-time dependency on B and B shares *.cs (i.e. the B package contains only empty assemblies) and describes a dependency on A in its .nuspec?

**Comment by NTaylorMullen** [comment]
@dougbu C will then have the shared sources from both B & A. Therefore everything will seem to function fine. The problem occurs when C also depends on a separate library in the system that also depends on A.

**Comment by borgdylan** [comment]
An issue will also occur if B or C are not shared projects themselves and depend on A's sources being compiled into them.

**Comment by davidfowl** [comment]
> Talked with @loudej and @ChengTian about potential fixes for this issue and @loudej suggested we make shared sources transitive where the nupkg for B would contain a dependency on shared source A. This way package resolution can only bring in one copy of A.cs and essentially only ever do 1 copy of all sources from shared sources.

```
         / -- B -- \
TestApp             A
         \ -- C -- /
```

Does it mean that sources from A don't end up in B and C? What it does mean to bring in one copy of A.cs? Does it just dedupe based on path?

**Comment by NTaylorMullen** [comment]
Right now it ends up A.cs ends up in both B and C which cause a conflict. The idea @loudej suggested is not necessarily to dedup the dependencies but to rather utilize the dependency chain (what nuget does) to pick only one of them.

**Comment by muratg** [comment]
@davidfowl @loudej are we going with Louis' suggestion?

**Comment by davidfowl** [comment]
Yep, but this isn't a fix we can make right now. We need to get our dependency type support up to scratch.

**Comment by davidfowl** [comment]
irrelevant with nuget3 immutable content support
