### ISSUE TITLE
Support globbing in global.json

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1248]
It's convenient to have
```json
{
    "sources": [
        "src",
        "submodules/*/src"
    ]
}
```
instead of
```json
{
    "sources": [
        "src",
        "submodules/FileSystem/src",
        "submodules/NuGet.Packaging/src",
        "submodules/NuGet.Versioning/src"
    ]
}
```

**Comment by ChengTian** [comment]
WARNING from @davidfowl : if not implemented properly, this globbing can hurt performance. Please remember to expand the pattern at most once in `ProjectResolver`.

**Comment by ChengTian** [comment]
Our `FileSystemGlobbing` package doesn't support globbing directories. Although we can implicitly append ·/*/project.json·, this workaround leads to suboptimal performance that we want to avoid.

I filed an issue for adding directory globbing: https://github.com/aspnet/FileSystem/issues/118

**Comment by Eilon** [comment]
Moving this to the Backlog. We decided not to support this for the initial release. Will revisit in the future.
