### ISSUE TITLE
XRE app base change can break .NET APIs that are documented as supporting app-relative paths

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1253]
The recent change to change the base path of XRE apps to the XRE folder itself (rather than the application's folder) (#1152) causes some API's in the .NET Framework that are documented as supporting app-relative paths to break, as they now start searching from the wrong location.

e.g. [ResourceManager.CreateFileBasedResourceManager(string baseName, string resourceDir, Type usingResourceSet)](https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager.createfilebasedresourcemanager(v=vs.110).aspx)

We should do an investigation of .NET Framework APIs that reference `AppDomain.CurrentDomain.BaseDirectory` to determine how much might be affected by this.

**Comment by davidfowl** [comment]
We need to keep an eye out for the number of things that break because of this appbase change

/cc @shhsu @jhawk42

**Comment by shhsu** [comment]
this actually sound like a possible deal breaker. Any client uses any BCL library that takes a file path could break due to this

**Comment by bricelam** [comment]
This caught me off guard. I was calling `AppContext.BaseDirectory` expecting it to be the value of `IApplicationEnvironment.ApplicationBasePath`, but it was the runtime directory instead since it just uses the value of `AppDomain.CurrentDomain.BaseDirectory` internally.

**Comment by muratg** [comment]
@moozzyk

**Comment by bricelam** [comment]
@davidfowl per the discussion in dotnet/corefx#2670 can `AppContext.BaseDirectory` point to the right location on `dnx46` now?

**Comment by davidfowl** [comment]
46? That's a 461 change

**Comment by bricelam** [comment]
Ah, "6 days ago" :smile: definitely not on 46 then.

**Comment by davidfowl** [comment]
Irrelevant with CLI work
