### ISSUE TITLE
cleanup kre.coreclr.cpp

### ISSUE THREAD

**Issue by glennc** [aspnet/dnx#1258]
AMD64 check needs to be removed: https://github.com/aspnet/XRE/blob/dev/src/kre.coreclr/kre.coreclr.cpp#L232

Always pass full path to coreclr don't try and use relative paths or search around.

/@blowdart

**Comment by davidfowl** [comment]
@muratg I think @moozzyk would be better suited to do this :smile:

**Comment by moozzyk** [comment]
The AMD64 check has already been removed - it was pointless.  We **always** tried reading from disk even though the dll was never in this location - even on dev boxes (even though the logic was supposed to help debug things).
