### ISSUE TITLE
Localization: Loading of loc resources

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1263]
- [ ] Satellite assemblies
- [ ] Satellite assembly packages
- [ ] Satellite assemblies in main package
- [ ] Packages

**Comment by muratg** [comment]
Is @lodejard doing this?

**Comment by davidfowl** [comment]
Moving this out. I'll pull in some major pieces from @lodejard 's work in beta5

**Comment by muratg** [comment]
@davidfowl Move further?

**Comment by DamianEdwards** [comment]
Put in beta 7

**Comment by kirthik** [comment]
merged bfc4776207bc08c3b2787fd04ae5c66960c7ed6a
