### ISSUE TITLE
Drop project.lock.json in AppData or some other location

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnx#1265]
Can the new project.lock.json be stored in the AppData rather than in the project itself ? AFAIK this should not be tampered by the users right or is there a scope to customize this by the users. If it is auto generated and not supposed to be manually edited, it can be dropped in some other location.

**Comment by davidfowl** [comment]
I don't see how appdata makes any sense for something that is per project.

**Comment by suhasj** [comment]
on the contrary why in the project unless it is supposed to be customized ? It is one more config file in the project displayed in VS and sometimes users might edit it by mistake.

**Comment by glennc** [comment]
Users can edit the file, to set locked to true if nothing else. I'm not against some tooling support to special case the file in VS, but moving it away from the project doesn't seem to add anything and it splits up my view of the world too much. So I don't think we should move it out of the project.

@davidfowl have we had any discussions about tooling features for lock files?

**Comment by davidfowl** [comment]
We're not going to move this file. In some cases it can be checked into source control.
