### ISSUE TITLE
project.lock.json must be loaded before resolving package path

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#1267]
I installed a package globally using `kpm commands install` and I am getting this when I run the installed command:

![image](https://cloud.githubusercontent.com/assets/328122/6353764/30f2d5d0-bc43-11e4-8357-17685c92bf3e.png)

I am on v1.0.0-beta4-11134.

**Comment by victorhurdugaci** [comment]
@davidfowl and I already talked about this. It seems that the lock file broke the global install :disappointed:

**Comment by davidfowl** [comment]
@victorhurdugaci Restore for the commands needs to write a lock file.
