### ISSUE TITLE
DTH null ref in project with Tag Helpers & Razor pre-compilation

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1275]
Using latest bits. When building the MVC repo, the TagHelperSample.Web project fails to build due to a null ref in the DTH. Builds fine from the CLI.

**Comment by DamianEdwards** [comment]
@davidfowl FYI the issue we were looking at on my machine

**Comment by DamianEdwards** [comment]
I was able to reproduce on a simple Starter Web project. As soon as you reference tag helpers and you have Razor pre compilation configured, it fails.

**Comment by troydai** [comment]
@DamianEdwards can this issue be reproduced by this sample https://github.com/aspnet/Mvc/tree/dev/samples/TagHelperSample.Web?

**Comment by davidfowl** [comment]
This isn't a bug in the runtime. It was a bug in MVC
