### ISSUE TITLE
Need mechanism for including loose files with other binaries 

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1283]
It seems unlikely that ASP.NET VNext's build mechanism will support build for targets like .NET 3.X, Silverlight, etc any time soon or at all.  Thus, if I want to make a package that works for ASP.NET VNext and these targets, I need to create entries like this:

        "net35": {
            "bin": {
                "assembly": "../../../build/bin/Release/.NET Framework 3.5/NLog.dll",
                "pdb": "../../../build/bin/Release/.NET Framework 3.5/NLog.pdb"
            }
        },

While trying to make an identical (for .NET 3.5 users) package to what I got from NLog, I realized I could not figure out how to automatically include the Intellisense XML files that are in the normal feed here.  
It seems likely that there will be other scenarios with loose adjacent files for this.  I'd like some kind of "content" tag to go along with the bin tag to support this.

**Comment by anurse** [comment]
Dupe on #848
