### ISSUE TITLE
Print warning when deprecated properties are used.

### ISSUE THREAD

**Issue by troydai** [aspnet/DNX#1292]
We keep supporting `code` and `resources` in project.json for the sake of compatibility. They should be gradually retired so as to simplify the parsing logic.

**Comment by davidfowl** [comment]
Awesome! We need something for design time host

**Comment by troydai** [comment]
Developing on this branch. Feature scope:

1. Returns warnings on Build and Bundle command;
2. Shows warnings in VS.

**Comment by troydai** [comment]
Change of scope: item 2 will be traced on https://github.com/aspnet/XRE/issues/1330
PR related to this issue will only impact _build_ and _bundle_ command.

**Comment by troydai** [comment]
Fixed in 41ae546c87337413138ee5c75bd32255a7bf0f1d
Moving on to #1330
