### ISSUE TITLE
Possible parsing bug?

### ISSUE THREAD

**Issue by jods4** [aspnet/dnx#1296]
I was trying to answer a few questions by reading the sources today and noticed:
https://github.com/aspnet/XRE/blob/069dfb964a86ab505dd6df5e5495434072346b6c/src/Microsoft.Framework.Runtime/NuGet/SemanticVersion.cs#L186

`SemanticVersion.TryParseInternal`
It seems that the intent of line 186 is to remove the `"-*"` suffix, by dropping the last 2 chars of `version`. But this is inconsistent with the `if` above. It checks if the last two chars _after trimming_ are `"-*"`, whereas the code tries to remove the last two chars _before trimming_.

It is my understanding that with a version such as `"1.0.0-* "` (notice the space at the end), this method would fail.

**Comment by glennc** [comment]
@anurse Is this code we temporarily borrowed from NuGet?

**Comment by muratg** [comment]
Seems fixed.
