### ISSUE TITLE
Expose the AppRoot - physical and virtual paths - via an API

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#13]
It would be useful to have the equivalent of HttpRuntime.AppDomainAppPath and AppDomainAppVirtualPath exposed as an API.

**Comment by roydukkey** [comment]
@davidfowl Can you please rephrase your last sentence? I don't understand how virtual paths are a concept from Helios.

Are virtual paths obsolete in the coming release?

**Comment by davidfowl** [comment]
No the dnx is the layer below web starts. Virtual Paths are an IIS concept and this belongs in a much higher layer than the DNX.
