### ISSUE TITLE
'kpm restore' needs to report errors more clearly

### ISSUE THREAD

**Issue by jodavis** [aspnet/dnx#1308]
When a package can't be found during 'kpm restore', it is reported in the middle of the output, in the same dark gray color as all the other standard messages. It is then unclear why the restore command returned a failed error code.

There should be a summary of errors at the end of the command output, so the important messages are easy to find. Error messages should be reported on stderr as well, so they are detected as errors by build systems that look for them there (e.g. MSBuild).

**Comment by muratg** [comment]
This is fixed in either Beta 4 or 5.  Assigning to @BrennanConroy to close.
