### ISSUE TITLE
kpm wrap to wrap a custom assemblies in the same way as csproj to allow referencing them 

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#1316]
To allow reference custom (loose) assemblies in project.json we decided to use kpm wrap in the same way it works for project dependencies. This issue is to track that work item. As soon as it is done , we will enable Browse button/tab in Add Reference dialog.

**Comment by abpiskunov** [comment]
@ChengTian fyi

**Comment by muratg** [comment]
@ChengTian Do you have time to look into this? It's blocking a tooling scenario as described above.

**Comment by ChengTian** [comment]
I'll start to work on this item today.

**Comment by ChengTian** [comment]
@abpiskunov  @sayedihashimi  @BillHiebert  @muratg 

This feature is checked in. Tooling team can integrate it with VS based on next build of DNX. Usage:

`kpm wrap <path_to_assembly> --framework <target_framework_name>`

This command assumes its work dir is in the solution, in which we want to reference the wrapped assembly.

The command also automatically wraps dependency assemblies of the wrapped assembly if they are in the same dir.
