### ISSUE TITLE
Framework Assemblies and Packages are treated the same

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1322]
PackageA -> FrameworkAssemblyB -> PackageB is seen as a cycle

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/997

**Comment by davidfowl** [comment]
This is worse than I thought. Since we unify by name you can end up potentially compiling and running against the wrong thing.

**Comment by muratg** [comment]
Ugh. Move to beta5?

**Comment by muratg** [comment]
@davidfowl is prepending "fx/" to the reference assemblies something we'll keep or do we need to find a better solution. IOW, is this one good to close?

**Comment by davidfowl** [comment]
That's the best it's going to be for a while. Closing this out.
