### ISSUE TITLE
kpm install should provide an option to specify what version of KRE to use

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1326]
Today, the commands run in the context of the current active framework. If the app doesn't support the active framework, it fails. 

There should be an option to "lock" the app on a particular framework version.

Disadvantage: if you remove that framework, the app will fail.

**Comment by davidfowl** [comment]
Talk to Louis about this before doing anything. We had a discussion about this a while back.

**Comment by tugberkugurlu** [comment]
:+1: for the issue.

> Disadvantage: if you remove that framework, the app will fail.

Is it possible to distribute the framework stuff along with the command installation? E.g. when you install commands of the **foo** package, install the framework 1.0.0 in a place where only this app knows. Sounds like a bad idea but what do you guys think?

Also, what does nodejs do with global installs?

**Comment by muratg** [comment]
Putting to 1.0 milestone for now. We can update later once Victor syncs up with Louis

**Comment by tugberkugurlu** [comment]
Is there a specific release date determined for this? I am looking into doing a few spikes on our command line tools to see how we would ship this way but I am pretty sure we don't want users to manage runtime dependency stuff (e.g. figure out which version do I have, do I need to switch runtime, etc.). 

What we would want to have:

As long as the user has dnvm, the command-line tool should be installed happily. Afterwards it should run even if the user has no runtime installed under ~/.dnx/runtimes, which piratically means to be able to ship the runtime along with the command-line app and scope that runtime just for this app usage, don't make it available to anyone else.

**Comment by muratg** [comment]
@tugberkugurlu: @victorhurdugaci and @lodejard will talk about this and potential designs. If it turns out to be simple to implement it could potentially be beta 7.

**Comment by tugberkugurlu** [comment]
@muratg awesome, thanks for the update :smile:

**Comment by davidfowl** [comment]
Closing as nuget suppors this and we're moving it tonuget

**Comment by tugberkugurlu** [comment]
@davidfowl how will global installs work in dotnet CLI world as the commands will be removed?

**Comment by muratg** [comment]
@tugberkugurlu That's under discussion currently :)
