### ISSUE TITLE
Add support for new TFMs

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#1342]
* dnx46 - DNX on Desktop .NET Framework 4.6
* core50 - Assemblies targeting the broader ".NET Core 5.0" platform

Support needs to be added for:
* Pulling the right framework reference assemblies (dnx46 only)
* Framework Compatibility Matrix (i.e. dnxcore50 and dnx46 projects can reference core50, etc.)
* Project Target Frameworks
* Parsing of new framework names (FrameworkNameUtility, VersionUtility, NuGet.Core, NuGet.Frameworks, etc.)
* and probably more I'm forgetting

**Comment by muratg** [comment]
@anurse let me know if you are not able to spend time on this one.

**Comment by anurse** [comment]
This will be in the new runtime. I assume @davidfowl will be too busy to implement it now :)

**Comment by davidfowl** [comment]
@anurse assigned this to you and marked it as working.

**Comment by muratg** [comment]
Is there other work remaining on this?  Or is this good to close?
