### ISSUE TITLE
Fix use of TargetFramework property in dnx.vcxproj

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#1348]
We shouldn't use the TargetFramework property any more. The split is actually by runtime, not framework. Instead of building the dnx.exe bootstrapper in "dnx451" and "dnxcore50" flavors, we should use "clr" and "coreclr_[platform]" as the names.

**Comment by anurse** [comment]
Actually this is useful for keeping the `makefile.shade` clean because it just scans all folders under `src` for `bin\*\dnx451\**` and `bin\*\dnxcore50\**` (excluding some files). There's no problem here really, especially since we only ever build the Windows CoreCLR variant on Windows.

Propose **wontfix** /cc @muratg @moozzyk

**Comment by muratg** [comment]
:+1:
