### ISSUE TITLE
Long coreclr home and application base path cause errors in CoreCLR

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1358]
https://github.com/aspnet/XRE/blob/dev/src/dnx.coreclr/dnx.coreclr.cpp#L463

The size of the buffer to store coreclr path and app path is set to `MAX_PATH`, which can be easily exceeded when both paths are long. It happens in the case of IBC build on CI.

Which makes it worse is that the error is swallowed. Not trace or exception to be captured.

**Comment by BrennanConroy** [comment]
Should be [(MAX_PATH + 1) * 2] unless CreateAppDomainWithManager expects a certain sized string.

We should also print the value of errno in the CHECK_RETURN_VALUE_FAIL_EXIT_VIA_FINISHED macro and possibly include the line number __LINE__ and file just in case __FILE__

**Comment by davidfowl** [comment]
Closing this as it should be part of @moozzyk's general native code clean up.
