### ISSUE TITLE
Add advanced authentication for kpm restore proxy

### ISSUE THREAD

**Issue by ChengTian** [aspnet/DNX#1364]
Reported by @sleemer in https://github.com/aspnet/DNX/pull/324

For example, `kpm restore --proxy` cannot handle credentials with domain usernames like:
`company.com\username:password` or `username@company.com:password` because you cannot construct an URI like `http://company.com\username:password@proxyaddress.com` with `UriBuilder`.

**Comment by davidfowl** [comment]
We shouldn't out any more effort into making kpm work with proxies. We're just going to merge with nuget and use the code that's in there (which pretty much handles all/most cases)

/cc @emgarten
