### ISSUE TITLE
Fix sporadic exception thrown during "kpm restore"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1366]
Directory.Move() sporadically throws exceptions.

**Comment by ChengTian** [comment]
Found a problem after pushing to CI.

The fix #1324 doesn't work because when `kpm restore` to a remote folder, `Directory.Move()` the temp folder from current machine to the remote machine throws exception:
```
System.IO.IOException: Source and destination path must have identical roots. Move will not work acr
oss volumes.
```

**Comment by davidfowl** [comment]
Nice

**Comment by ChengTian** [comment]
This can be frequently reproduced with a VM with following configuration:
OS: Windows 7 Enterprise (EN-US)
Hardware: CPU=2, RAM=3584, Arch=AMD64

**Comment by muratg** [comment]
Looks like we're still looking for the right fix. Moving to Beta 5.

**Comment by davidfowl** [comment]
Nooooooo

**Comment by victorhurdugaci** [comment]
We should fix this as soon as possible. The cross plat CI machines are affected by this all the time. The runs are very unstable.

**Comment by muratg** [comment]
adding @pranavkm in case he has some ideas..

**Comment by pranavkm** [comment]
I'll spend some time looking at this - if we can't find a reasonable solution for this we can consider reverting the parallel restore behavior until we have something more reliable.

**Comment by davidfowl** [comment]
Whats the state of this issue?

**Comment by pranavkm** [comment]
I'll close this one and use https://github.com/aspnet/dnx/issues/1190 to track the issue.
