### ISSUE TITLE
`kpm build` executes `postBuild` scripts even if the build failed.

### ISSUE THREAD

**Issue by lefb766** [aspnet/dnx#1372]
This behaviour is not intuitive and may cause unexpected side-effect.

Here's simplest steps to repro:
1. Create project.json described below and a .cs file with random content (which doesn't compile).
2. Run `kpm build`.

project.json:
 ```json
{
    "scripts" : {
        "postBuild" : [
            "echo postBuild executed"
        ]
    }
}
```

Dnx version: 1.0.0-beta4-11244

**Comment by davidfowl** [comment]
Agreed that's unexpected. Do you want to send a PR to fix it?

**Comment by lefb766** [comment]
Yes, I'd love to. I'm not familiar with the code base however, so it might take long to find where to fix.

**Comment by davidfowl** [comment]
Here's the line of code:

https://github.com/aspnet/DNX/blob/dev/src/Microsoft.Framework.PackageManager/Building/BuildManager.cs#L195

There's a variable called success that you can check before executing the scripts

**Comment by lefb766** [comment]
Thanks.

**Comment by muratg** [comment]
@ChengTian can you look at the PR to see if we can get this in?
