### ISSUE TITLE
Print summary of restore errors when kpm restore runs on multiple projects

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1376]
This hits *everyone*. Run kpm restore at the solution root, if one of the projects fail to restore something you need to search the restore log (which can be huge) to figure out what the package is.

**Comment by BrennanConroy** [comment]
Thoughts?
![restoreerror](https://cloud.githubusercontent.com/assets/7574801/6644008/0a759108-c96e-11e4-9e93-79b3a8cfe0ce.PNG)

**Comment by muratg** [comment]
Looks much better to me.
