### ISSUE TITLE
kpm restore fails with recent versions of kestrel - Can not add property Microsoft.AspNet.Hosting to Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by dbreshears** [aspnet/DNX#1383]
<pre>

Trying to run kpm restore on a web project I get an error with any recent Kestrel package that I add to the project.json file.

Seems to happen with all versions of Kestrel > 1.0.0-beta4-11222.  

Installing Kestrel 1.0.0-beta4-11252
Writing lock file <projectPath>\bin\output\approot\src\WebApplication4\project.lock.json
----------
System.ArgumentException: Can not add property Microsoft.AspNet.Hosting to Newto
nsoft.Json.Linq.JObject. Property with the same name already exists on object. </pre>

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Home/issues/368
