### ISSUE TITLE
The pdb file info in DLL is not full path

### ISSUE THREAD

**Issue by feiling** [aspnet/dnx#1391]
You can run `dumpbin /headers <the dll>` to get the path to the pdb file associated with an assembly, under section "Debug Directories".

For an assembly generated by csc, the path of the pdb file is the full path. This is why I can move the file to another place on the same machine and the debugger can still locate the source files.

For an assembly generated by k, the path of the pdb file is not the full path. If I move the assembly to another place, then the debugger will not be able to locate the source files since it can't find the pdb file. I have to copy the pdb file to the same directory as the assembly. This makes debugging quite painful when using nuget packages generated by k.

**Comment by muratg** [comment]
@lodejard, re: discussion this morning in the nuget standup.

**Comment by muratg** [comment]
@lodejard are we doing this for RC?   /cc @davidfowl

**Comment by anurse** [comment]
I've done some initial investigation. We are definitely passing the full path for the desired PDB to Roslyn. However, the generated DLL has a relative path in the Debug Directory. I verified that using Roslyn's `csc.exe`, the absolute path to the PDB **is** embedded in the Debug Directory, but I can't figure out where we're going wrong in passing the right data to Roslyn.

That's about all the investigation I've been able to do so far, I have to go back to some other higher-pri things right now.

**Comment by muratg** [comment]
@davidfowl Recent work on Portable PDBs changed this?

**Comment by davidfowl** [comment]
Nope

**Comment by davidfowl** [comment]
CLI uses CSC so this should be fixed.
