### ISSUE TITLE
DTH performance issues for large solution load

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#1394]
_Updated_

- [ ] `JsonDeserializer.Deserialize` is invoked 155 times and count for 40% of the time.
- [ ] Serializing the payload on the way out takes over 2.49% of the time.

_Expired_
- [ ] - TryGetProject called over and over
- [x] -  Microsoft.Framework.Runtime.NuGetDependencyResolver.GetSharedSources() should never touch the disk
- [ ] -  Microsoft.Framework.Runtime.Hosting.PatternGroup.SearchFiles() - takes 10 seconds for 41 projects

[This is the notes out of combined session with Fowler, he should have all the context about these issues]

**Comment by troydai** [comment]
DTH is going away. I'll close this issue for now. Moving forward, performance on large solution will always be a test pivot.

/cc @muratg @Eilon @davidfowl
