### ISSUE TITLE
Add a summary of errors/warnings when restore is completed

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnx#1399]
Today if there is an error during ```kpm restore``` (```dnx restore```) you have to search through the log to find the error. It would be nice if the command had a summary like msbuild at the end clearly showing errors/warnings.

**Comment by glennc** [comment]
Dup? https://github.com/aspnet/DNX/issues/1376

**Comment by sayedihashimi** [comment]
@glennc #1376 is specifically for multiple projects. I'd like this for a single project as well.

**Comment by muratg** [comment]
@BrennanConroy this will work for a single project too, right?

**Comment by BrennanConroy** [comment]
Pretty sure I tested that.

**Comment by muratg** [comment]
@sayedihashimi have a look at latest builds as #1376 is checked in. Closing this one.
