### ISSUE TITLE
Add a "DNX_ANY" compilation constant when the target framework is any DNX

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/dnx#1400]
I've found that I have `#if DNX451 || DNXCORE50` in a few places in my code base. Unfortunately this pattern is fragile, as if a DNX452 target is added then this #ifdef will evaluate to false and the code that it surrounds won't be compiled.

Spoke with @Eilon about this, and we think that it might be good to define a handful of meta compilation constants like DNX (any DNX version on desktop CLR), DNX_CORE (any DNX version on core CLR), DNX_ANY (any DNX version on any CLR), and so on.

**Comment by anurse** [comment]
What about splitting up a bit:

DNX - "'dnx' TFM, regardless of CLR"
CORECLR - "CoreCLR is present, regardless of DNX (i.e. core50)"

Then you can compose the necessary conditions yourself:

```
DNX && CORECLR ==> 'dnxcore50'
DNX && !CORECLR ==> 'dnx4x'
!DNX && CORECLR ==> 'core50' but NOT 'dnxcore50'
CORECLR ==> 'dnxcore50' OR 'core50'
etc...
```

**Comment by GrabYourPitchforks** [comment]
@anurse I like the composability offered by your proposal.

**Comment by aggieben** [comment]
Is there such a thing as `!DNX && CORECLR`?

**Comment by Eilon** [comment]
Not at this time. Just wishful thinking :smile:

**Comment by muratg** [comment]
Moving to backlog

**Comment by davidfowl** [comment]
Irrelevant now with the CLI move

**Comment by aggieben** [comment]
There's still an app-hosting model that differs from .NET 4.6 and before, right?  Wouldn't the move to CLI just mean that instead of `DNX_ANY`, it would need to be `DOTNET_ANY` or something?

**Comment by davidfowl** [comment]
Not really. DOTNET_ANY IMO isn't that valuable to have.
