### ISSUE TITLE
Problem with dynamic assembly loading

### ISSUE THREAD

**Issue by justkao** [aspnet/dnx#1412]
I am trying to write little code generation tool as ASP .NET 5 console app

Problem:
AssemblyA
AssemblyB that depends on AssemblyA

Using IAssemblyLoadContext.LoadFile I load both assemblies into memory, but upon accessing AssemblyB.ExportedTypes the FileNotFoundException is thrown (complaining about AssemblyA not found). 

ActualCode:
https://github.com/justkao/Bolt/blob/Bolt_ASPNET5/src/Bolt.Console/AssemblyCache.cs

Should I use other API to dynamically load assemblies ? The AppDomain.AssemblyResolve is not available in dnxcore profile.

**Comment by davidfowl** [comment]
Dependent assemblies aren't loaded by default from the side by side location.

You can add a custom IAssemblyLoader that handles that.

**Comment by davidfowl** [comment]
See thus sample https://github.com/aspnet/Entropy/tree/dev/samples/Runtime.CustomLoader

**Comment by davidfowl** [comment]
I took a look at your code and you can totally implement that alot more efficiently by using a custom loader implementation.

**Comment by justkao** [comment]
Thanks for pointing me into the right direction. I basically used the code from your example and it's working fine. I will deal with performance later, currently I am just experimenting with the new runtime ... i like it quite a lot, good job ;)
