### ISSUE TITLE
'dnvm setup' results in 'Cannot overwrite the item ... with itself' error

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/dnx#1424]
When running 'dnvm setup' (v1.0.0-beta4-10346) from PowerShell console (on Win 10 9926), the following error is returned:

> Cannot overwrite the item C:\Users\Rich\.dnx\bin\dnvm.ps1 with itself

```
D:\dev> dnvm
You must specify a command!
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-beta4-10346
By Microsoft Open Technologies, Inc.

usage: dnvm <command> [<arguments...>]

commands:
    alias      Lists and manages aliases
    help       Displays a list of commands, and help for specific commands
    install    Installs a version of the runtime
    list       Lists available runtimes
    name       Gets the full name of a runtime
    setup      Installs the version manager into your User profile directory
    upgrade    Installs the latest version of the runtime and reassigns the specified alias to point at it
    use        Adds a runtime to the PATH environment variable for your current shell
D:\dev> dnvm setup
Installing .NET Version Manager to C:\Users\Rich\.dnx\bin
Installing 'dnvm.ps1' to 'C:\Users\Rich\.dnx\bin' ...
Copy-Item : Cannot overwrite the item C:\Users\Rich\.dnx\bin\dnvm.ps1 with itself.
At C:\Users\Rich\.dnx\bin\dnvm.ps1:1150 char:9
+         Copy-Item $ps1Command $Destination -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Rich\.dnx\bin\dnvm.ps1:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand

Installing 'dnvm.cmd' to 'C:\Users\Rich\.dnx\bin' ...
Copy-Item : Cannot overwrite the item C:\Users\Rich\.dnx\bin\dnvm.cmd with itself.
At C:\Users\Rich\.dnx\bin\dnvm.ps1:1157 char:9
+         Copy-Item $cmdCommand $Destination -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Rich\.dnx\bin\dnvm.cmd:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand

Adding C:\Users\Rich\.dnx\bin to Process PATH
Adding C:\Users\Rich\.dnx\bin to User PATH
Adding C:\Users\Rich\.dnx to Process DNX_HOME
Adding C:\Users\Rich\.dnx to User DNX_HOME
```

**Comment by glennc** [comment]
Did you expect it to work or is this just for us to add a check so that it doesn't crash?

**Comment by davidfowl** [comment]
I want self update!

**Comment by anurse** [comment]
This is separate from self-update, but we should add a catch and just do nothing. Self-update is also a good idea, but a separate feature :).

**Comment by davidfowl** [comment]
Move this to aspnet/dnvm

**Comment by bitcrazed** [comment]
Thanks for moving @davidfowl - didn't realize DNVM was in its own repo! :flushed:

**Comment by bitcrazed** [comment]
@glennc 

> "Did you expect it to work or is this just for us to add a check so that it doesn't crash?"

Erm ... well, I kinda expected that if I ran `dnvm setup` that it'd do so without :rage: shouting :rage: at me in big red, unhelpful text that make me wonder whether something went wrong in the setup and maybe I should expect the setup to have failed in some way.

A gentle, polite message saying *"DNVM is already installed and ready for use. Setting up your paths..."* would have more than sufficed :grinning:

**Comment by glennc** [comment]
@bitcrazed Yeah, that's what I thought. Which is fine, and something we should do. Are you interested enough to send a pull request for the dnvm repo? It's just a powershell script. If not that's fine and we will probably fix it in one of the polish pushes we do where we cleanup issues like this.

**Comment by bitcrazed** [comment]
Yep, happy to do so 😉 Will send tonight.

Sent from my Windows Phone
________________________________

**Comment by bitcrazed** [comment]
Hey Glenn. 


Just submitted DNVM PR #187 for your review: https://github.com/aspnet/dnvm/pull/187


Let me know if you need additional changes.






Rich.





From: Glenn Condron
Sent: ‎Thursday‎, ‎March‎ ‎19‎, ‎2015 ‎17‎:‎02
To: aspnet/dnx
Cc: Richard Turner





@bitcrazed Yeah, that's what I thought. Which is fine, and something we should do. Are you interested enough to send a pull request for the dnvm repo? It's just a powershell script. If not that's fine and we will probably fix it in one of the polish pushes we do where we cleanup issues like this.
