### ISSUE TITLE
Active XRE version does not persist across console windows

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1435]
I have a bleeding edge setup with the following output from dnvm list:

C:\>dnvm list

Active Version           Runtime Architecture Location                       Alias
       1.0.0-beta4-11257 clr     x64          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11257 clr     x86          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11257 coreclr x64          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11257 coreclr x86          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11271 clr     x64          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11271 clr     x86          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11271 coreclr x64          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11271 coreclr x86          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11308 clr     x64          C:\Users\mattgal\.dnx\runtimes
  *    1.0.0-beta4-11308 clr     x86          C:\Users\mattgal\.dnx\runtimes default
       1.0.0-beta4-11308 coreclr x64          C:\Users\mattgal\.dnx\runtimes
       1.0.0-beta4-11308 coreclr x86          C:\Users\mattgal\.dnx\runtimes

Note that the x86 4.5.1 1.0.0-beta4-11308 is active here.
... however, if I start a new command prompt, I get the same output from dnvm list except no active version.  Since this isn't persisted, I have to then dnvm use a version every time I new up a command prompt.

This might be a bug, might be a feature request.  I expect (which is why default is set there) that later command-prompt instances will have some version active, ideally the default one if I have not selected otherwise.

**Comment by davidfowl** [comment]
Wrong repository, file this on aspnet/dnvm.

**Comment by davidfowl** [comment]
Also this is fixed now
