### ISSUE TITLE
`kpm restore` not using other packageSources on Ubuntu

### ISSUE THREAD

**Issue by conniey** [aspnet/dnx#1437]
I have a project that uses a feed from MyGet.org.  This project works on Windows.  When I try to restore packages on Ubuntu 14.04, it can't resolve my dependency `Microsoft.Fx.Portability`.

I looked at the output from `kpm restore` and it doesn't seem to be querying feeds other than the official one: https://www.nuget.org/api/v2/FindPackagesById()

[Script Output](https://gist.github.com/conniey/1128c985e72f9dbc7de8#file-scriptoutput)
[NuGet.config](https://gist.github.com/conniey/1128c985e72f9dbc7de8#file-nuget-config)
[project.json](https://gist.github.com/conniey/1128c985e72f9dbc7de8#file-gistfile1-txt)

**Comment by davidfowl** [comment]
Can you push this to a repository somewhere so I can see the layout in the project.

**Comment by conniey** [comment]
Here is a minimal repro: https://github.com/conniey/webrepo

**Comment by conniey** [comment]
Any updates on this? Were you able to reproduce it?

**Comment by davidfowl** [comment]
What version of mono?

**Comment by conniey** [comment]
Mono JIT compiler version 3.12.1 (tarball Fri Mar  6 19:12:47 UTC 2015)

**Comment by conniey** [comment]
@davidfowl: This issue still persists, even with the latest dnx (1.0.0-beta5-11624).

I followed the instructions from [Getting Started Debian](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md).

Is it by design to __only__ use the NuGet.config from `~/.config/NuGet`?

**Comment by davidfowl** [comment]
The latest unstable version of the dnx prints out a summary of what things were considered during restore. That includes package sources and nuget.config files. 

If this issues still persists, look at that log and reopen the issue with those details.
