### ISSUE TITLE
Reduce Allocations in the runtime startup path

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1446]
![image](https://cloud.githubusercontent.com/assets/95136/6727612/837089ac-cde0-11e4-9828-407bdb8c3331.png)

Pivots:

## Lock file memory consumption
- [ ] Cache strings
- [ ] Parsing lock file lazily

## Cache common metadata
- [ ] Versions strings, SematicVersion
- [ ] Path strings
- [ ] Library names

## File globbing
- [ ] Dispose the matchers
- [ ] Cache strings

**Comment by davidfowl** [comment]
Another thing we can do is reduce the amount of duplicate strings:

![image](https://cloud.githubusercontent.com/assets/95136/6727803/2627eb30-cde2-11e4-9800-f394981ef3df.png)

**Comment by davidfowl** [comment]
I'd like @anurse to also help out on this as it involves refactoring pieces of the runtime.

**Comment by troydai** [comment]
![image](https://cloud.githubusercontent.com/assets/1329240/9391144/0333d3a2-472a-11e5-82da-54aac4cb0557.png)

**Comment by anurse** [comment]
:+1: totally on board here :)

**Comment by davidfowl** [comment]
I'll take this one
