### ISSUE TITLE
Offer more information in dnx --version

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1447]
This is what we have today:
```
$ dnx --version
1.0.0-beta4-11309
```

It would be nice to print the full name so as to know what platform, arch and target framework the current dnx is for.

**Comment by davidfowl** [comment]
@troydai or @BrennanConroy can you work on this? It would be great since we have all flavors working in some form.

**Comment by troydai** [comment]
I'll take a look at it today.

**Comment by troydai** [comment]
I'll try to put the full build version in the `AssemblyInformationVersionAttribute`

**Comment by troydai** [comment]
Fixed in 4afed2c694fa9bff7734ca9985697b1db3bb3afc
