### ISSUE TITLE
'System.Reflection.TargetInvocationException' being thrown on app initalization through IIS Express

### ISSUE THREAD

**Issue by 0xdeafcafe** [aspnet/dnx#1452]
I did a fresh install of Windows 10 Technical Preview - the one that came out yesterday - and now none of my ASP vNext applications are debugging when I run them in visual studio using IIS Express.

The exact exception is
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in AspNet.Loader.dll

Additional information: Exception has been thrown by the target of an invocation.
```

My call stack is:
![](http://i.imgur.com/YkzG1VH.png)

Is there anything else I should provide?

**Comment by 0xdeafcafe** [comment]
Upon further investigation, this is only thrown on CLR, if I use CoreCLR, it executes perfectly. Could this be to do with corrupted runtimes? My .k folder looks like this:
![](http://i.imgur.com/GwkiLBs.png)

**Comment by davidfowl** [comment]
File this on aspnet/Home.

**Comment by 0xdeafcafe** [comment]
Good idea. Re-posted in Home.
