### ISSUE TITLE
Missing NUPKG metadata: iconUrl

### ISSUE THREAD

**Issue by bradwilson** [aspnet/dnx#1460]
There is no way to set the `iconUrl` value for your package. (https://github.com/xunit/aspnet.xunit/issues/19)

**Comment by davidfowl** [comment]
These were all added in the latest builds

**Comment by davidfowl** [comment]
https://github.com/aspnet/dnx/commit/dd88a6ee46c98e1276270e887dd2eaf6ea42458d
https://github.com/aspnet/dnx/commit/cdad86f30495d970ab6fb61682892662195b1c3d
