### ISSUE TITLE
Revisit ICompilationProject after new runtime merge

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#1464]
An upcoming refactoring of Compilation will be introducing an `ICompilationProject` interface to abstract between the old and new versions of the `Project` class. We should revisit this after we get rid of the old runtime and have just a simple `Project` poco we can share around.

**Comment by anurse** [comment]
Ditto `IProjectFilesCollection`

**Comment by muratg** [comment]
@anurse is this still valid? 

@cc @davidfowl

**Comment by anurse** [comment]
This is covered in #2225
