### ISSUE TITLE
Remove k.cmd and only use dnx

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1473]
parent https://github.com/aspnet/Coherence-Signed/issues/19

@muratg , @davidfowl thinks we should do this in beta4. Working on it.

**Comment by ChengTian** [comment]
Cannot get this in before beta4 release branching. Will ask for check-in approval later after release branching.

**Comment by hishamco** [comment]
@ChengTian you can apply the fix into Security repo

**Comment by hishamco** [comment]
@ChengTian can we apply the fix into Diagnostics repo

**Comment by hishamco** [comment]
@ChengTian can we add the fix into SignalR-ServiceBus repo

**Comment by ChengTian** [comment]
@hishamco , thanks for the reminder, I'll add fix to them with my automation script

**Comment by hishamco** [comment]
@ChengTian all the best

**Comment by anurse** [comment]
Something I noticed: If you happen to have two DNXes on your path "New;Old", where _Old_ is one with `k.cmd` and _New_ is one without it and you accidentally run `k`, you will get the old runtime (whereas running `dnx` gives you the newer one). Not a bug or something technical to correct, just something to put in release notes or other docs.
