### ISSUE TITLE
Improve experience of debugging into source code

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#1484]
My scenario: I wanted to debug into source code which is across repos (`routing` references `logging`). I had both these repos cloned on my machine and updated the `routing` repo's global.json to have the src path of `logging`. When I open routing solution in VS, all the projects load fine but when I debug I see errors like below:
- `The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)`
- `The type or namespace name 'NotNull' could not be found (are you missing a using directive or an assembly reference?)`

The reason for these is probably due to `NotNullAttribute` being moved to the `Common` repo. So now I have to even add the `Common` repo's src path to my global.json folder, which as you can imagine is not discover-able (as its used internally by a package) for an external user trying to debug into our code.

The weird thing is that after I do the above i get the debug experience working correctly but i get back the same exception messages earlier when i try the second time and on.

/cc: @victorhurdugaci @NTaylorMullen

**Comment by regisbsb** [comment]
The problem is that the projects added via global.json do not load their Nuget.config
Add the https://www.myget.org/F/aspnetmaster/api/v2 that is on the Nuget.config of the dnx project to your nuget.config or to the visual studio package sources.
It's a bit bad that visualstudio does not use the nuget package configuration for the project's you add via source.

**Comment by regisbsb** [comment]
@shanselman was showing how to add MVC as a source in a video but MVC uses only the public nuget feed. It would be nice to feedback to visual studio the team that you cannot add for example the Options project to your source without getting the @kichalla described error.
