### ISSUE TITLE
Running dnu commands on mono null refs

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1492]
```
Davids-MacBook-Pro:helloworld dfowler$ dnu commands
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.ShowHelp (System.String commandName) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program+<>c__DisplayClass3_13.<Main>b__26 () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Davids-MacBook-Pro:helloworld dfowler$ 
```

/cc @victorhurdugaci

**Comment by victorhurdugaci** [comment]
It happens both on mono and windows and it caused by [this fix](https://github.com/aspnet/dnx/commit/5d8ab2b1eb5c0a702a73a27034b0f19cda8a96ca).

Particular, [this line](https://github.com/aspnet/dnx/commit/5d8ab2b1eb5c0a702a73a27034b0f19cda8a96ca) because `VersionGetter` is null.

@BrennanConroy can you please take a look?

**Comment by davidfowl** [comment]
@victorhurdugaci I can't repro on windows

**Comment by BrennanConroy** [comment]
I can, using dnx v11360

**Comment by victorhurdugaci** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5921642/6832417/8bc46698-d2e3-11e4-8916-29d0cc9adae9.png)

**Comment by davidfowl** [comment]
Ah hah, I was using 51

**Comment by davidfowl** [comment]
So these kinds of regressions are bad. We need to beef up our testing. Manual and automated.

**Comment by victorhurdugaci** [comment]
I agree, we should have more tests for scenarios that are not hit everyday

**Comment by davidfowl** [comment]
Possibly unit testing more?

**Comment by BrennanConroy** [comment]
I will write unit tests for dnu and dnx commands after fixing this issue.

**Comment by Praburaj** [comment]
`user-secret` feature is also affected by this issue.

**Comment by Praburaj** [comment]
@rustd

**Comment by dougajmcdonald** [comment]
I'm seeing this on user-secret too. 

>user-secret -h
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

**Comment by victorhurdugaci** [comment]
@BrennanConroy is this related to the change that you made yesterday?

**Comment by BrennanConroy** [comment]
@dougajmcdonald
What dnx version are you using? I'm guessing it is older than beta5-11702

**Comment by dougajmcdonald** [comment]
I'm on beta4-11566 I can't seem to find a newer one, if I dnvm upgrade from the vnext myget feed that's all I get. Do I need to download something manually?

**Comment by BrennanConroy** [comment]
Get the latest dnvm, either download manually or run dnvm update-self, then run dnvm upgrade -u for the unstable (myget) feed. That's all that should be needed to get the latest

**Comment by dougajmcdonald** [comment]
@BrennanConroy I think I must be doing something wrong! dnvm update-self tells me:
 'Unknown command: 'update-self''.

dnvm upgrade tells me I already have the latest:
Determining latest version
'dnx-clr-win-x86.1.0.0-beta4-11566' is already installed.
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta4-11566'

'dnvm install latest' tells me the same.

I can't see a release on github for dnvm > beta 4 : https://github.com/aspnet/dnvm/releases

Will I need to build it myself? was hoping to avoid that if possible.

**Comment by BrennanConroy** [comment]
Ok, are you wanting to use beta4 or beta5 because you can't mix them. You are using beta4 dnx with a beta5 SecretManager. If you want to get the latest dnvm follow the instructions here: https://github.com/aspnet/Home
Then use dnvm upgrade -u to get beta5 dnx. Otherwise uninstall the SecretManager app you have and reinstall using your beta4 dnx pointing at the beta4 feed

**Comment by dougajmcdonald** [comment]
I'm happy to use either, but not 100% clear on how best to ensure they are both in sync!

I've just run the PS script from the link you sent and confirm I'm now on beta5-11722.

Now trying to install SecretManager I get:

>dnu commands install SecretManager
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='SecretManager'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?id='Secret
Manager'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Secre
tManager'
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Framework.PackageManager.InstallGlobalCommand.CreateTemporaryPro
ject(String installFolder, String packageName, String packageVersion)
   at Microsoft.Framework.PackageManager.InstallGlobalCommand.<Execute>d__17.Mov
eNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass4_12.<<Main>b_
_24>d.MoveNext()

Any thoughts?

**Comment by BrennanConroy** [comment]
Its a regression: https://github.com/aspnet/dnx/issues/1808
