### ISSUE TITLE
Kpm bundle with configuration as 'release' is not honored when built from source.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#1501]
Runtime does not honor the configuration passed to kpm bundle when built from the source.

Repro:
kpm.cmd bundle "C:\WebApplication2" --out "C:\Temp\AspNetPublish\WebApplication2-89" --configuration Release --runtime dnx-clr-win-x86.1.0.0-beta4-11296 --wwwroot-out "wwwroot" --quiet

**Comment by troydai** [comment]
To keep up with the progress check out branch https://github.com/aspnet/dnx/tree/trdai/1501

**Comment by troydai** [comment]
Fixed in 33eccd43e5fa250c2650744b6d28140cd42096a7
