### ISSUE TITLE
Consider moving the .dnx directory on Windows to a subdirectory of %AppData%

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#1507]
On Windows, everything under the `Users` directory with the exception of the `AppData` sub directory is indexed. Consequently restoring packages kicks off the search indexer. It doesn't look like it's actually indexing package contents, but it does index the file names. Moving it would avoid all the extra work.

**Comment by IRLeif** [comment]
I'm not sure if this is related, or if it's a separate issue.

My company limits the Windows profile storage space to 30 MB, and my `.dnx` directory currently takes up 120 MB in my user directory.

It would be very nice if it were possible to somehow move this folder to another location. Is there a config option to change the location of this folder?

**Comment by Suchiman** [comment]
This also bugs me, but not only for the reasons already mentioned.

DNX behaves like a badly ported unix application on windows:
* being cmd focused (ok, it's still far away from release, expecting more complete tooling later)
* prefixing folders with `.` which is totally useless on windows, cheats on alphabetical sorting and is ugly
* being in the `%USERPROFILE%` folder where programs don't belong into

So i strongly agree on moving it into one of the `%AppData%` folders and having the `.` removed, e.g. `%AppData%\dnx`

**Comment by ghuntley** [comment]
https://twitter.com/davkean/status/628456517205823492

**Comment by bitcrazed** [comment]
If only GitHub issues had a voting mechanism. I'd give this 100 thumbs up.

**Comment by Suchiman** [comment]
I asked this in a ASP.NET Community Standup and this is unlikely to happen http://blogs.msdn.com/b/webdev/archive/2015/07/07/asp-net-community-standup-july-7-2015.aspx see Q&A or the video

**Comment by shiftkey** [comment]
:thumbsup: to this change. Here's the [MSDN reference](https://technet.microsoft.com/en-us/library/cc749104(v=ws.10).aspx) about %USERPROFILE% (well, it's alias %CSIDL_PROFILE%)

<img width="835" alt="screen shot 2015-08-05 at 5 08 25 pm" src="https://cloud.githubusercontent.com/assets/359239/9080170/aabe3686-3b94-11e5-9dab-26cb4b71ccfb.png">

**Comment by RichiCoder1** [comment]
Agree with all the above. I'm all for cross uniformity, but this is explicitly AppData.

**Comment by luisrudge** [comment]
:+1:

**Comment by onovotny** [comment]
This also applies to NuGet v3. Has anyone filed a bug there?

**Comment by vbfox** [comment]
:+1: If it is a cache it should be in local-appdata and if it is settings it should in in roaming-appdata.

If the same things was done the other way (Applying windows folder conventions on unix) it would have been patched by the person doing the port / package.
They often maintain patches to adapt software to their OS/Distribution when the maintainer doesn't want to conform to their platform conventions.

**Comment by DamianEdwards** [comment]
Appreciate the feedback on this item. We'll take another look at this.

**Comment by shiftkey** [comment]
Thanks @DamianEdwards!

**Comment by akoeplinger** [comment]
Setting DNX_HOME like [shown here](https://github.com/aspnet/Announcements/issues/5#issuecomment-125660908) works for the command line, but seems to break VS. @DamianEdwards is that env var supposed to work for VS?

**Comment by Suchiman** [comment]
So what's the status on this?
Community clearly expressed their idea in the same direction.
3 months looking at this is some serious work :smile:
