### ISSUE TITLE
The git submodules are pointing to the aspnetvnext feed

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1519]
The git submodules in `dnx` release branch are pointing to the `aspnetvnext` myget feed. Things will start breaking...

cc @anurse

**Comment by anurse** [comment]
We'll need to create a `dnx-release` branch in the NuGet submodules and make the change there. The `release` branch on the NuGet repos are completely different from the code we're trying to build.

Ideally, we should try to remove the new runtime from beta4 entirely...

**Comment by anurse** [comment]
The NuGet ones actually aren't interfering so I won't change them in this fix. I will request a separate beta4 fix to remove the new runtime build from the release branch
