### ISSUE TITLE
Installation on MacOSX has problems/doesn't work

### ISSUE THREAD

**Issue by TheDarkTrumpet** [aspnet/dnx#1528]
Hello all,

I'm not sure if this is an issue with how I did things, but it seems like most things should be in place.

Steps To Reproduce:
1) Installed Mono through brew: (brew install Caskroom/cask/mono-mdk)
2) Installed dnx/dnvm (curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh from https://github.com/aspnet/Home)
3) Upgraded the runtimes (dnvm upgrade)
4) Check out the sample, cd into the samples/HelloMvc
5) Restore packages: (dnu restore)
6) Try and run the setup (dnx . kestrel)

At the end of this message, I have a post on the error I'm getting

I found a similar report of this being a problem for someone
https://github.com/aspnet/DNX/issues/762

I'm currently trying to build everything from source and see if placing the resulting dll (guessing) in this place would work.  This could all be a documentation issue, but after spending about 5 hours trying to get this working, I thought  it worth reporting as maybe an issue, or a documentation need.

The error I'm getting is:
MacBookPro:HelloMvc dthole$ dnx . kestrel
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Kestrel 1.0.0-beta3
   Microsoft.AspNet.Diagnostics 1.0.0-beta3
   Microsoft.AspNet.Hosting 1.0.0-beta3
   Microsoft.AspNet.Mvc 6.0.0-beta3
   Microsoft.AspNet.Server.WebListener 1.0.0-beta3

Searched Locations:
  /Users/dthole/Programming/Home/samples/{name}/project.json
  /Users/dthole/.dnx/packages/{name}/{version}/{name}.nuspec
  /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5/{name}.dll
  /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by davidfowl** [comment]
Use the dev branch

**Comment by TheDarkTrumpet** [comment]
I actually checked out the source code for dnx, and am on the dev branch.  I followed the directions on https://github.com/aspnet/dnx, including the command to create the symlinks, and switched the environment to the dev environment.  I verified the same problem occurs.  I went into the build directory (where the symlinking was done to) and verified dnx was in there.  

MacBookPro:HelloMvc dthole$ dnvm list

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
       1.0.0-beta5-11400    mono    ~/.dnx/runtimes      default
  *    1.0.0-dev            mono    ~/.dnx/runtimes      mono-dev

MacBookPro:HelloMvc dthole$ dnx . kestrel
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Kestrel 1.0.0-beta3
   Microsoft.AspNet.Diagnostics 1.0.0-beta3
   Microsoft.AspNet.Hosting 1.0.0-beta3
   Microsoft.AspNet.Mvc 6.0.0-beta3
   Microsoft.AspNet.Server.WebListener 1.0.0-beta3

Searched Locations:
  /Users/dthole/Programming/Home/samples/{name}/project.json
  /Users/dthole/.dnx/packages/{name}/{version}/{name}.nuspec
  /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5/{name}.dll
  /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
MacBookPro:HelloMvc dthole$


On a side note, can you please not close the issue until it's resolved?  At the very least this is a documentation problem, and that needs to be fixed.  I wouldn't mind helping with that, but getting it working is a first step.

**Comment by davidfowl** [comment]
dev branch of the Home repository for samples

**Comment by davidfowl** [comment]
You never really have to build your own dnx ever, unless you want to work on it.

**Comment by BrennanConroy** [comment]
:+1: and even then you can usually get away with just building parts of it and replacing those parts in the version you have installed.

**Comment by TheDarkTrumpet** [comment]
Yeah, I've been at this for something like 7 hours now, so that's why I started building my own dnx.  At least I got back to the original difficulty I was at (server starts, but no connections, and little information posted) is was the same as I was having with k, so it looks like switching to dev worked.  I think I'll fork the Home documentation, and try to add something to the beginning that if using the dnx version, you should probably use the dev branch.

Thanks for the help, I'll continue banging my head on why it's not working on connecting, but that's better than I was at.

**Comment by davidfowl** [comment]
http://davidfowl.com/diagnosing-dependency-issues-with-asp-net-5/ Check out this awesome blog post (that I wrote) :smile:

**Comment by TheDarkTrumpet** [comment]
That is a useful post.  I think it was one of your posts, I came across, that originally got me setup some months ago using this.  I recall being to your website a few times so far.  I'll definitely read through this post to see if I can get "dnx . web" actually working

**Comment by TheDarkTrumpet** [comment]
and I got it working.  I really hope I can document this in a way that others won't have to battle quite as much as I did for getting this to work.

**Comment by rene-poulsen** [comment]
Did you ever get to that documentation part? :-)
I'm having the same problems as you mention - so before I start using hours on it I hope that you might be able to point me in the right direction.
