### ISSUE TITLE
Coreclr bad argument not same as Desktop

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#1543]
On coreclr if you do something like ```dnx . glhf```` it gives the "Try running 'dnu restore'." error message with the failed dependencies list.

Same command on desktop clr has the "Unable to load application or execute command 'glhf'." error.

**Comment by muratg** [comment]
Ugh

**Comment by BrennanConroy** [comment]
This error only occurs when using a dnx framework that isn't supported in the application. i.e. dnx-coreclr with a project.json that only has dnx451 as a target framework.
