### ISSUE TITLE
Set NuGet minClientVersion to 2.8.5 when using dnx* TFMs

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#1544]
Older versions of NuGet will be unhappy with these TFMs :). Our packages should require this minimum version of NuGet.

/cc @yishaigalatzer

**Comment by glennc** [comment]
@anurse Does this still need to happen?

**Comment by anurse** [comment]
I think it should. We should ensure we set the minClientVersion appropriately. We'll need similar code to what NuGet has to determine the appropriate version. This can happen in RC though.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#590
