### ISSUE TITLE
Need a more descriptive message when an incorrect file globbing pattern is entered

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#1548]
For example if I accidentally put a `*` in a globbing pattern that does not allow `*` e.g:
```
"compileFiles": [ "*.cs" ],
```

All we show in the error is this without any line number information, or pointers on what's wrong etc. We should print out a more descriptive error with some information on what exactly is wrong. 

![image](https://cloud.githubusercontent.com/assets/2294732/6908138/2215bcae-d6f0-11e4-9d0e-a8488583aa19.png)

Expected: `compileFile` cannot contain wildcard patterns. 

@troydai

**Comment by troydai** [comment]
We may exam the 'literal' patterns more carefully while parsing project.json.

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Hosting/PatternGroup.cs#L80

**Comment by troydai** [comment]
No, we didn't take action. The error is expected. We can have a better error message through.

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/dnx/commit/a486da1669280f1f46ea3e11cf5e6f42c9a00133
