### ISSUE TITLE
dnx . [command] Cannot resolve packages

### ISSUE THREAD

**Issue by jskulavik** [aspnet/dnx#1551]
Run dnu restore as suggested, "Installed *" successfully, then dnx . [command] to receive missing packages:  
![dnx_dependencies](https://cloud.githubusercontent.com/assets/2044176/6912292/b45adb22-d72b-11e4-85b1-61a384c275ac.png)

project.json: 
```{
    "webroot": "wwwroot",
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta3",
        "Microsoft.AspNet.Mvc": "6.0.0-beta3",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta3",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta3",
        "Microsoft.Net.Http": "2.2.29"
    },
    "frameworks": {
        "aspnet50": { },
        "aspnetcore50": { }
    },
    "commands": {
        "winhost": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5102",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5104"
    },
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ],
    "bundleExclude": [
        "node_modules",
        "bower_components",
        "**.kproj",
        "**.user",
        "**.vspscc"
    ]
}
```

**Comment by davidfowl** [comment]
Beta3 packars aren incompatible with the DNX. If you're using the Home samples, use the dev branch with the dnx.

**Comment by jskulavik** [comment]
Thanks @davidfowl.  I'm not using the Home samples though.  My process:  Latest VS2015->build simple ASPNET5 app->deploy local file system->xcopy to 2012 server->run *.cmd to activate WebListener->error: kre.host cannot be added due to security (loadFromRemoteSources)->execute dnvm/dnu upgrade, kpm restore->dnx . [command]->your answer.  So, what's the deployment story for dnvm & beta3 following VS2015 instructions from /Home? Please forgive my confusion, still catching up with the dnvm/dnx/dnu renames and shuffling.

**Comment by davidfowl** [comment]
beta3 is incompatible with dnx (which is >= beta4). Read this http://davidfowl.com/diagnosing-dependency-issues-with-asp-net-5/. 

The first tip is the one to be most aware of.

**Comment by jskulavik** [comment]
Thank you sir!  "Learnt" huh?  You've been hanging out with @DamianEdwards a bit too much it seems ;-).  Thanks again.
