### ISSUE TITLE
Publish Regression

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#1556]
When publishing a package, dependencies still list all their requirements even for the non needed frameworks yet not all of these requirements are deployed with the bundle. This is leading to an inconsistent deployment bundle.

**Comment by davidfowl** [comment]
Can you be more specific about what used to work, and what is failing now?

**Comment by borgdylan** [comment]
Before the packages for the unused framework were not copied yet still required by the dnx to let you run. Before you could copy the packages manually and manage to run. The latter is no longer the case.

**Comment by davidfowl** [comment]
I don't understand

**Comment by borgdylan** [comment]
I have a site that depends on a library. This library has a net40 only dependency. This dep is not being copied in the packages folder on a publish. However the runtime still expects that dependency to be present. Before I used to fix this issue by copying the dependency myself, but now that does not work.

**Comment by borgdylan** [comment]
I will try to patch the project.json in the published image and see if I can fool the runtime since I am targeting dnx451 with the site.

**Comment by davidfowl** [comment]
net40 is compatible with dnx451 so I don't quite understand why it isn't copied. If you can make a repro site that would be great. We can add it as a test case.

**Comment by borgdylan** [comment]
Also, why does the runtime ask for the presence of dependencies not meant for the current target framework when I run? I would expect that the runtime checks for what is needed for the chosen TFM only.

**Comment by borgdylan** [comment]
This library is rather special in that it provides async support for my language. It only needs this package i.e. Microsoft.Bcl.Async on net40. It supports later versions using built in types.

**Comment by davidfowl** [comment]
We'll make progress when you provide a sample.

**Comment by borgdylan** [comment]
The library source code is here: https://github.com/borgdylan/dylandotnet/tree/master/vnext-stuff/dylan.NET.Tasks

**Comment by davidfowl** [comment]
Can you provide a minimal repro with steps on how to reproduce the problem. The goal is to put this as a test case so we don't regress it again.

**Comment by borgdylan** [comment]
Would a c# project that does a simple app.Run using the library for async be ok? It should make the runtime behave in the same way.

**Comment by davidfowl** [comment]
Whatever you want, the less dependencies the better.

**Comment by atrauzzi** [comment]
@davidfowl 

I've been trying to get going with postgresql and EF7, so I've been using their unstable feed here: https://www.myget.org/F/npgsql-unstable

I think this issue is related to what I'm experiencing?  Here's my `project.json` for you:

```
{
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
    "EntityFramework": "7.0.0-beta4",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
    "Npgsql.EntityFramework7": "3.0.0-unstable1836"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
    }
  }
}
```

What I'm experiencing is that there's some kind of issue with the `Microsoft.Bcl.Async` that npgsql's library is either bundling or requesting.  It only occurs for dnx451.  Gives me a little yellow warning in my references.  Hopefully this is helpful.
