### ISSUE TITLE
Setting project name in project.json

### ISSUE THREAD

**Issue by andyalm** [aspnet/dnx#1559]
Forgive me if someone has already asked about this. I tried searching through the issue history and couldn't find mention of it. Are there plans to provide a way to set a projects name/id in the project.json file? Right now, it seems to be a requirement that the name come from the parent directory name. While I think that is a fine default, I find the inability to override that to be very limiting. For example, at my company, we have many projects that compile to assemblies with 4 or 5 part names (not unlike many assemblies provided by Microsoft). For example "CompanyName.HighLevelArea.Component.SubcomponentA". Within a given git repo, the first couple parts of the assembly name are usually all the same, so including that in the folder structure is redundant, and in fact adds friction to doing simple things at the command line. So, our folder structure typically will only mirror the last part of the assembly name. For example (src/SubcomponentA, src/SubcomponentB, or sometimes src/Component.SubcomponentA, etc) Furthermore, we run the risk of running into PathTooLongExceptions when we use the fully qualified name for both the directory and filenames. This has especially bitten us on our CI servers where they tend to have working directories that are already somewhat deep.

We would love to start using the project.json project system as it has a number of advantages over the current .csproj system. However, requiring us to rename all of our directories will make this very difficult to do.

Thoughts?

**Comment by davidfowl** [comment]
We had it in earlier versions and removed it. The reasoning was that forcing the folder name to be the project name was to make things more DRY. The other reason was that project references were found via project name on disk. This makes it very quick to check for `/folder/{project}/project.json` without having to crack open any JSON files upfront. Moving the name into the `project.json` means that we have to parse all potential `project.json` files upfront, to figure out what the actual project name is. That lookup had a significant performance impact.

This obviously can be very limiting in certain scenarios (like the ones you mention). We may revisit this in the future if tons of people complain. 

Another solution I can think of would be to allow mapping project names to paths in `global.json`:

`global.json`

```JSON
{
  "projects": { 
     "MyProject": "/some/path/here"
  },
}
```

**Comment by andyalm** [comment]
@davidfowl Thanks for the quick response. I definitely understand the performance benefit here. Putting it in the global.json feels a little weird to me, because something as important as the identity of a project feels like it belongs with the project's own manifest.

I'm very excited about this new project system as it addresses so many of the frictions of the current csproj system. However, this issue is going to make it a painful transition.

**Comment by davidfowl** [comment]
Lets brain storm some more then. Let's talk about all of the names:

- Name to use for a project reference
- Name to use for the generated package
- Name to use for the assembly name within the package

I assume you want all of them to be in sync right?

**Comment by andyalm** [comment]
I think it makes sense for them to be in sync. That said, the two that are most important are the name of the generated package and assembly. We have to preserve them for backwards compatibility for downstream consumers.

**Comment by davidfowl** [comment]
Ok I'm leaning towards the `global.json` solution. If you override the project name in `project.json` you have to go to global.json and specify the mapping from name to location (relative to the global.json of course).


`root/src/ComponentA/project.json`

```JSON
{
    "name": "CompanyName.HighLevelArea.Component.SubcomponentA",
    "dependencies": {
        "CompanyName.HighLevelArea.Component.SubcomponentB"
     }
}
```

`/root/src/ComponentB/project.json`

```JSON
{
    "name": "CompanyName.HighLevelArea.Component.SubcomponentB"
}
```

`root/global.json`

```JSON
{
   "projects": [ "src", "test" ],
   "projectReferences": {
        "CompanyName.HighLevelArea.Component.SubcomponentA" : "src/ComponentA",
        "CompanyName.HighLevelArea.Component.SubcomponentB" : "src/ComponentB"
   }
}
```

I'm torn between reusing projects (formerly sources) or creating another node.

Maybe it's also possible to directly specify a project location in `project.json` but that makes things less DRY so lets stay away from that for now.

/cc @glennc @lodejard @muratg

**Comment by david-driscoll** [comment]
I think the global.json solution makes sense, it places the responsibility in a single file.

I think the question comes in, what happens when I as a library consumer try to reference this as source code.  I believe referencing the global.json is how things currently work today in beta3.

Something like... `projects: ["src", "test", "../path/to/source"]` which I references the global.json in the folder which would have the mapping.

**Comment by glennc** [comment]
@BillHiebert  if we did this can we make it so that if I ever rename a project in VS it automatically adds the right entries to global.json and project.json?

I'm not sure I like having to change two files. Will think about it more though.

**Comment by davidfowl** [comment]
@glennc YES we can!! Just discussed that with @DamianEdwards

**Comment by davidfowl** [comment]
### Option 1

```JSON
{
    "projects": [ "src”, "test" ],

    "projectMapping”: {
         "Foo" : "src/SomethingElse"
    }
}
```

### Option 2

```JSON
{
    "projectSearchPaths": [ "src”, "test" ],

    "projects: {
         "Foo": "src/SomethingElse"
    }
}
```

### Option 3

```JSON
{
    "projects": [ 
        "src”, 
        "test", 
        { "Foo" : "src/SomethingElse" } 
    ]
}
```

**Comment by davidfowl** [comment]
I'm leaning towards 3. In general explicit name mappings override search locations.

**Comment by davidfowl** [comment]
### Option 4

```JSON
{
    "projects" : {
        "*": "src",
        "*": "test",
        "Foo" : "src/SomethingElse",
        "Microsoft.AspNet.Mvc.Core" : "../../../Mvc/src/Microsoft.AspNet.Mvc.Core"
    }
}
```

**Comment by david-driscoll** [comment]
Will 4 still allow the array syntax by default?

**Comment by davidfowl** [comment]
The idea is to change the array syntax to key value pairs instead.

**Comment by glennc** [comment]
I like 4

**Comment by glennc** [comment]
I like 4

**Comment by kijanawoodard** [comment]
4 seems like it could be a problem with standard json libraries because of the relevant RFCs.

http://stackoverflow.com/a/23195243/214073

**Comment by bradwilson** [comment]
4 isn't, strictly speaking, legal JSON, because keys must be unique in objects.

**Comment by bradwilson** [comment]
I like a slightly modified version of 3 to make it clearer that the strings are patterns, not project names:

```json
{
    "projects": [ 
        "src/*", 
        "test/*", 
        { "Foo" : "src/SomethingElse" }
    ]
}
```

**Comment by david-driscoll** [comment]
Then 3 might make more sense if the idea is to use the same property.

**Comment by bradwilson** [comment]
Or, an alternative 4 that is legal JSON (let's call this `4a`):

```json
{
    "projects" : {
        "*": ["src", "test"],
        "Foo" : "src/SomethingElse",
        "Microsoft.AspNet.Mvc.Core" : "../../../Mvc/src/Microsoft.AspNet.Mvc.Core"
    }
}
```

**Comment by davidfowl** [comment]
I like that one @bradwilson

**Comment by DamianEdwards** [comment]
I vote for `4a` so far

**Comment by davidfowl** [comment]
Yah +1

**Comment by Bartmax** [comment]
4a is pretty clever!

**Comment by Tragetaschen** [comment]
`4a`, because it's easy to describe how the ordering/overriding works.

(and it extends nicely with upstream `global.json`-include)

**Comment by davidfowl** [comment]
Names will *always* override * as a rule

**Comment by bradwilson** [comment]
If ordering is an issue, you should be drawn and quartered. :stuck_out_tongue_winking_eye:

**Comment by david-driscoll** [comment]
What we had a common prefix such as `Microsoft.Framework`?

    {
        "projects" : {
            "*": ["src", "test"],
            "Microsoft.AspNet.Framework.*" : "src/*",
            "Microsoft.AspNet.Framework.*.Tests" : "test/*"
        }
    }

**Comment by davidfowl** [comment]
Feature creep. That's not a bad suggestion but I'm going to say maybe in v5 :smile:

**Comment by congiuluc** [comment]
Me too 1vote for 4a

**Comment by akoeplinger** [comment]
+1 to 4a, although I think it'd be clearer if the pattern was explicit like in @bradwilson modified version 3 (which also makes a future extensions like @david-driscoll proposed more consistent):

```
{
    "projects" : {
        "*": ["src/*", "test/*"],
        "Foo" : "src/SomethingElse",
        "Microsoft.AspNet.Mvc.Core" : "../../../Mvc/src/Microsoft.AspNet.Mvc.Core"
    }
}
```

**Comment by Bartmax** [comment]
On references (dependencies), should/can use foo or somethingelse or both?

This would also work as an alias for External nugets? Like "mvc" : "Microsoft.AspNet...." ??

Are there any difference when dealing with local projects or Nuget ?

**Comment by MattGal** [comment]
I'd vote for #1 or #3, as I am skeptical that the * naming system will add much value to users, and doesn't exactly match the "wildcard" interpretation that asterisk has carried for some years.   #1 makes it slightly more obvious that it's a mapping, but may be confusing because it's a mapping and not a project name-wise... so it might not be obvious whether one puts the project name in both places AND the mapping if they want a different name, or only the mapping.

This feature is definitely needed.  However, since users will be making the transition from  the traditional SLN / proj way of doing things, we need to think about how users will react.  There needs to be some kind of assurance that if I build a particular project.json that VS or the command line tools will show the assembly / package name when I do. Imagine someone not super familiar with the project system trying to contribute.  With any of these approaches, if they were in a subfolder building various projects from the solution as they touched them, they'd see some projects that just matched their folder names, others that didnt

**Comment by ErikSchierboom** [comment]
+1 for 4a. Seems easy to grasp.

**Comment by davidfowl** [comment]
I coded this up and I don't like it. We're working on a way to make project parsing 0 cost at runtime by putting project information inside of the `project.lock.json` file

**Comment by aggieben** [comment]
I like option 3 better, and I agree with @MattGal: the additional syntax introduced by option 4 seems confusing and inconsistent to me.

**Comment by davidfowl** [comment]
We're discussing this issue here https://github.com/aspnet/dnx/issues/2312
