### ISSUE TITLE
Restore failed: TODO: Circular dependency references not supported. Package 'EntityFramework.Commands'. on opening a project

### ISSUE THREAD

**Issue by alexgav** [aspnet/dnx#1563]
Getting the error in the title on open of a test project that was previously working. The project sources are checked in into WebToolsExtensions at src\editors\json\package\test\webs\websites.sln. There is a corresponding TFS bug 1143923. This is blocking some of the JSON nightly tests.

**Comment by davidfowl** [comment]
Can you make a simplified repro? Or at least show the error message?
