### ISSUE TITLE
The code that injects the version information should not be part of the runtime

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1567]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Roslyn/RoslynCompiler.cs#L226-L282 <- this should be part of the build script and only added to the projects that need it

**Comment by davidfowl** [comment]
What?

**Comment by victorhurdugaci** [comment]
Synced offline with @davidfowl . Closing for now
