### ISSUE TITLE
Why is CommandLineApplication internal & shared instead of public?

### ISSUE THREAD

**Issue by cherrydev** [aspnet/dnx#1569]
I haven't been able to find any discussion upon why CommandLineApplication is internal and source-shared with dependent projects instead of public.  Is this just as an insurance policy against breaking changes?

**Comment by muratg** [comment]
This is an internal implementation detail.

**Comment by cherrydev** [comment]
That doesn't answer the question.  Are you saying that the API is internal and shouldn't be used publicly by developers?  Are you saying that the choice of "internal and source-shared" or "public" is an implementation detail and therefore therefore not relevant to developers?

**Comment by muratg** [comment]
Yes, the API is for use internally and not something we would like to officially support at this point, at least for our V1. 

That being said, the repo is OSS with Apache license, so if you'd like to use it, you can of course do that. :)
