### ISSUE TITLE
Main method with multiple args does nothing

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1570]
```
    public class Program
    {
        public static void Main(string[] x, int k)
        {
            Console.WriteLine("Works");
        }
    }
```

1. Create a console app with the code above. 
2. Run
3. Notice the app exits without any error message and nothing gets written to the console.

**Comment by davidfowl** [comment]
Should show an error

**Comment by Eilon** [comment]
The codes are in here: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Common/Impl/EntryPointExecutor.cs
