### ISSUE TITLE
Rename k-crossgen tool

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1572]
Reported by @moozzyk 

This is the last k-*.cmd we have. It's mainly an internally used tool, so the renaming is not urgent.

@muratg @davidfowl  Do we want to rename it to `dnx-crossgen`? Or you have some better names for it

**Comment by davidfowl** [comment]
merge it into dnu or make it another global command /cc @loudej

**Comment by ChengTian** [comment]
I guess merging it into dnu is better.

`dnvm` is using `k-crossgen` and assumes `k-corssgen` comes with dnx. Making `k-crossgen` a global command means `dnvm` will need to install this global command first. It's very different from the current approach.

**Comment by davidfowl** [comment]
Ah hah! Yes lets merge it in

**Comment by ChengTian** [comment]
So we all agree on the new name `dnx-crossgen`?

**Comment by muratg** [comment]
dnx-crossgen sounds fine to me.  Unless @davidfowl has any objections, let's go with that name.

**Comment by anurse** [comment]
`dnu optimize` ? Eventually, it could even take parameters such as allowing me to "optimize" specific packages/apps/runtimes/whatever.

I, as a user, have no idea what a `crossgen` is... but regardless, people don't generally run this command manually so I'm not very worried either way.

**Comment by ChengTian** [comment]
I guess `optimize` is a too general term and users may imagine they can do something like
```
dnu optimize MyApp
```
to make their app run faster...

If we don't expect people to use this in most cases, `crossgen` can be a better choice, which means "keep away if you don't know what it is"

**Comment by troydai** [comment]
In CLR we use Ngen.exe as well. I think `crossgen` is a more accurate name.

**Comment by ChengTian** [comment]
Moving forward with `dnx-crossgen` if there is no objection

**Comment by muratg** [comment]
:+1:

**Comment by ChengTian** [comment]
Talked to @joeloff and confirmed that, as long as the command name is in the form of `<any_prefix>-crossgen.cmd`, our installer can always find it. So there is no change needed in installer part.
