### ISSUE TITLE
Chagne DNU usage text for help

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#1577]
This works: `dnu help publish`
but the following do not
`dnu --help publish`
`dnu -h publish`
`dnu -? publish`

![image](https://cloud.githubusercontent.com/assets/6559784/6972570/83ae7ba4-d939-11e4-89d6-8f6dad2d0560.png)

**Comment by BrennanConroy** [comment]
If we want to support this what should the behavior be for:
```dnu --help . <some dll>```
The current behavior is that we just display the help and ignored all other arguments, but if we want --help and friends to take ```[command]``` that won't work

**Comment by BrennanConroy** [comment]
@kichalla 
Are you just wanting us to change the -?|-h|--help text? Something like "Show this help page"

**Comment by kichalla** [comment]
@BrennanConroy yes, currently its misleading...something like `-?|-h|--help` becomes `help Show help information about a command` and remove the last statement that I highlighted as it feels redundant?...also not sure if we again need to specify `help` in the `Commands` list...

**Comment by muratg** [comment]
cc: @glennc

**Comment by BrennanConroy** [comment]
@kichalla 
Does this resolve the issue? https://github.com/aspnet/dnx/commit/b084dadba551fc1cb0bafb8782f215d455fbbfb4

**Comment by kichalla** [comment]
@BrennanConroy No, it does not...following is the current behavior...we should remove `--help` from options completely as it currently does nothing(the 2nd section here)

```
C:\> dnu commands


Usage: dnu commands [options] [command]

Options:
  -?|-h|--help  Show help information

Commands:
  install    Installs application commands
  uninstall  Uninstalls application commands

Use "commands [command] --help" for more information about a command.
```
---------------
```
C:\> dnu commands --help install


Usage: dnu commands [options] [command]

Options:
  -?|-h|--help  Show help information

Commands:
  install    Installs application commands
  uninstall  Uninstalls application commands

Use "commands [command] --help" for more information about a command.
```
-----
```
C:\> dnu commands install --help


Usage: dnu commands install [arguments] [options]

Arguments:
  [package]  The name of the application package
  [version]  The version of the application package

Options:
  -o|--overwrite              Overwrites conflicting commands
  -s|--source <FEED>          A list of packages sources to use for this command
  -f|--fallbacksource <FEED>  A list of packages sources to use as a fallback
  -p|--proxy <ADDRESS>        The HTTP proxy to use when retrieving packages
  --no-cache                  Do not use local cache
  --packages                  Path to restore packages
  --ignore-failed-sources     Ignore failed remote sources if there are local packages meeting version requirements
  --quiet                     Do not show output such as HTTP request/cache information
  --parallel                  Restores in parallel when more than one project.json is discovered.
  -?|-h|--help                Show help information
```

**Comment by BrennanConroy** [comment]
This is expected behavior, other command line tools follow this convention.
Talked with @ChengTian @Eilon
