### ISSUE TITLE
Bootstrapper tests are failing on appveyor

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1586]
https://ci.appveyor.com/project/aspnetci/dnx/build/1.0.47

@ChengTian can you take a look at this?

**Comment by ChengTian** [comment]
Looking at it

**Comment by ChengTian** [comment]
This commit (https://github.com/aspnet/dnx/commit/a3729ddb5eb85f7f5c63ba0ca37971b7b50c573f) fixes bootstrapper tests but more tests are failing because of the line ending issue.

Looks like AppVeyor is using improper git line ending configuration on Windows. Working on a workaround.

**Comment by ChengTian** [comment]
Fixed: https://github.com/aspnet/dnx/commit/bd29db2bdbe8481fa5e75eb8a860d0e06dcb8732
Also fix the same problem in all other repos.
