### ISSUE TITLE
Can run an app but cannot build it (assemblies used for internal purposes leak to the user's code)

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1587]
A stock "Hello World" app can be executed successfully but cannot be built if it contains types pre-loaded by bootstrapping. 

Consider this app:
```
    public class Program
    {
        private IServiceProvider _sp;

        public void Main(string[] args)
        {
            Console.WriteLine("Hello World");
            Console.ReadLine();
        }
    }

```
with the following dependencies:
```
    "dependencies": {
    },
```

You can run this app with `dnx . run` without any problem 
Trying building it with VS (or from command line: `dnu build --out c:\temp\`) results in: 

C:\Users\pawelka\Documents\Visual Studio 2015\Projects\DNXTest\src\DNXTest\Program.cs(7,17): error CS0246: The type or namespace name 'IServiceProvider' could not be found (are you missing a using directive or an assembly reference?) 

As per @ChengTian this is because bootstrapping uses the `IServiceProvider` type and even though we are missing the dependency the type is already loaded when the code is being compiled. 

Adding `System.ComponentModel` to dependencies fixes build errors.

**Comment by davidfowl** [comment]
Thinking about this some more it actually makes sense and the only reason it's running is because we also have default CLR (dnx451) compilation references. Otherwise it would fail the same way as `dnu build`.

**Comment by davidfowl** [comment]
Won't happen with the CLI
