### ISSUE TITLE
Shutdown behavior with Thread that has IsBackground=false is different on DNX/Windows than DNX/Mono and Desktop .NET

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/dnx#1589]
Take this code snippet:

``` csharp
using System;
using System.Threading;

namespace ConsoleApplication1
{
    internal class Program
    {
        public static void Main()
        {
            var t = new Thread(() => { while (true); });
            t.IsBackground = false;
            t.Start();
            Console.WriteLine("finished");
        }
    }
}
```

On Desktop .NET and DNX/Mono, this will not exit until the thread is finished (i.e. never).
On DNX on Windows (both CoreCLR and CLR) however, this just exits after printing "finished", which seems like a bug.

/cc @davidfowl

**Comment by jkotas** [comment]
The shutdown sequence for standalone desktop apps is different from shutdown sequence of hosted apps. DNX on Windows is always hosted that explains the behavior you are seeing. Once main method exits, the DNX hosts tells CoreCLR to shutdown the appdomain and then exits the process.

I do not think that the current desktop or CoreCLR hosting APIs expose an easy way to make the shutdown work like standalone desktop apps today.

cc @janvorli

**Comment by muratg** [comment]
@davidfowl file a bug on CoreCLR to expose this functionality?

**Comment by muratg** [comment]
@danroth27

**Comment by muratg** [comment]
This is horrible, but not sure if there's anything we can do about it at the moment. Putting it into Backlog for now.

**Comment by muratg** [comment]
> I do not think that the current desktop or CoreCLR hosting APIs expose an easy way to make the shutdown work like standalone desktop apps today.

@jkotas Any plans to add this support in CoreCLR?

**Comment by jkotas** [comment]
Not on https://github.com/dotnet/coreclr/issues -> no plans

**Comment by muratg** [comment]
Cool, filed: https://github.com/dotnet/coreclr/issues/1648 

Tracking as External (https://github.com/aspnet/External/issues/46) and closing this one.

Thanks for the report @akoeplinger
