### ISSUE TITLE
Add System.Private.ServiceModel to DNX

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#1598]
If you reference types in any of the following packages from a DNX-coreclr app you’ll get a load exception:
- System.ServiceModel.Duplex.4.0.0-beta-22802.nupkg
- System.ServiceModel.Http.4.0.10-beta-22802.nupkg
- System.ServiceModel.NetTcp.4.0.0-beta-22802.nupkg
- System.ServiceModel.Primitives.4.0.0-beta-22802.nupkg
- System.ServiceModel.Security.4.0.0-beta-22802.nupkg

**Comment by muratg** [comment]
Approved for Beta4.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/1601
