### ISSUE TITLE
When dnu is run from solution directory, post restore scripts will not work

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#1602]
This is logged from investigating TFS bug 1152758. (http://bung/#/DevDiv/search/table?q=CID%3DDevDiv.1152758) 

When VS opens a project, we do a solution level restore by setting the working directory to solution directory. The gulp and npm tools set the path gulp/npm exes relative to project.json but since dnu interprets the paths from relative to solution level directory, restore fails saying gulp is not found.

Me and Joe talked to Victor and he asked us to log a bug on dnx.

**Comment by muratg** [comment]
Is this still an issue? @PradeepKadubandi @victorhurdugaci

**Comment by victorhurdugaci** [comment]
@moozzyk

**Comment by muratg** [comment]
:watch:

**Comment by moozzyk** [comment]
@victorhurdugaci #887 has not changed how we run scripts but only when we run scripts so I assume it is not fixed.
