### ISSUE TITLE
Rationalize type and function usage in native parts of DNX

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1603]
Currently we mix different aliases of types across the code e.g. `WCHAR*`, `LPWSTR`, `LPTSTR` are used all over the place (e.g. bool GetTrustedPlatformAssembliesList(WCHAR* szDirectory, bool bNative, LPWSTR pszTrustedPlatformAssemblies, size_t cchTrustedPlatformAssemblies))
even though they are basically the same type. 

Similarly we mix usage of `_T` and `L` macros and also mix string functions like `_tcs*` and `wcs*`  and 
`_tprintf_s` vs. `wprintf_s`

We should just use one alias or ideally - switch to STL and not use them at all. 

We could consider creating our own alias for `std::string` and `std::wstring` (like dnx::string_t) type that would be used across the codebase regardless of what platform we are using.

**Comment by anurse** [comment]
> We should just use one alias or ideally - switch to STL and not use them at all. 

:+1: :+1: :+1:

**Comment by BrennanConroy** [comment]
Biggest concern with STL is if we are concerned about speed. Otherwise I'm all for it
@davidfowl

**Comment by davidfowl** [comment]
@moozzyk is this still relevant with all of your refactorings?

**Comment by moozzyk** [comment]
@davidfowl - yes. Most of the occurrences are being fixed in https://github.com/aspnet/dnx/pull/2263 which has not been merged yet. I will need to do a final sweep after #2263 is merged since fixing this was not the main goal there.
