### ISSUE TITLE
dnx cannot run on Win7 Enterprise

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1616]
OS: Windows 7 Enterprise (EN-US) RTM
Hardware: CPU=2, RAM=3584, Arch=AMD64

Repro:
(1) Grab `dnx-clr-win-x64.1.0.0-beta4-11492.nupkg` from artifacts of `Coherence-Signed/release`
(2) Unzip the nupkg and run `dnx.exe` inside. `DNX_TRACE` shows `Failed to load: dnx.clr.dll`
(3) Can reproduce with CoreCLR version of dnx as well (shows `Failed to load: dnx.coreclr.dll`)

**Comment by victorhurdugaci** [comment]
Is it just on Enterprise or does it happen on other versions?

**Comment by pranavkm** [comment]
Are you using release builds?

**Comment by ChengTian** [comment]
@victorhurdugaci , I didn't test on other versions. But surprisingly it works on the Win7 used by Azure CI.

**Comment by ChengTian** [comment]
@pranavkm , yes, I grabbed the dnx build from `Coherence-Signed/release`

**Comment by ChengTian** [comment]
BTW, I have .NET Framework 4.5.2 installed on my Win7 VM.

**Comment by victorhurdugaci** [comment]
Yeah, seems to work there. I just kicked off a new build now.

**Comment by victorhurdugaci** [comment]
Do you have the latest updates and services packs?

**Comment by ChengTian** [comment]
After upgrading to Win7 SP1 and installing several important updates after upgrade, dnx works on my WIn7 VM. Closing this because users are supposed to have latest updates installed. It's not a bug.

**Comment by victorhurdugaci** [comment]
We should add this info in the release notes
