### ISSUE TITLE
Refactor dnu to use new NuGet libraries

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1623]

**Comment by ChengTian** [comment]
Talked to @davidfowl and we are going to use the new dnu written by @anurse (https://github.com/NuGet/NuGet3/commits?author=anurse). I should make sure all bugs I found in NuGet core libs during my refactoring are all fixed.

Assigning this to @anurse

**Comment by anurse** [comment]
I don't think this is going to happen fully for 1.0. @davidfowl is doing some refactoring to reduce (or even remove?) the dependency on forked NuGet code in the runtime though, making it much easier for us to unify the actual code post 1.0.

Thoughts on closure @davidfowl @Eilon @DamianEdwards ?

**Comment by davidfowl** [comment]
Punt to backlog. I'm working on moving stuff out of the runtime so this split will be easier.
