### ISSUE TITLE
LoadContext support for reflection only?

### ISSUE THREAD

**Issue by cherrydev** [aspnet/dnx#1626]
With LibraryManager now being the way of discovering dependencies and LoadContext being the way of explicitly loading them into the AppDomain, there does not seem to be any way of loading assemblies into the reflection only context.  Is this still going to be a supported "thing" in DNX?

An example:

I have a core (PCore) project that needs to search its dependencies on startup for classes that match a certain predicate in order to bootstrap my dependency injection container.  I have a project (PService) that contains the implementation of a service that's used by PCore.  PCore only references the services by their interfaces, which are in a separate project from the implementations (PInterface).  Therefore, PCore never DIRECTLY references PService, when you read all of the loaded assemblies from the AppDomain, PService is not in there.
I believe in the past, GetReferencedAssemblies() took care of this, but it doesn't actually appear to do anything anymore.  If you want a list of dependent libraries, you can now get them from LibraryManager, but it only gives you simple names of assemblies, which means you can't load them from the static Assembly.Load* methods (Note: this was confusing because ILibraryInformation provides AssemblyName structs which are bogus).
Currently, I can discover PService from LibraryManager and load it using LoadContextAccessor/LoadContext, but this does not provide me a way to load anything into the reflection only context, which would be ideal for determining if I REALLY want to load an assembly into the execution context after examining the classes in it.
Is there a way to do this that I haven't figured out?
Is the reflection only AppDomain context a thing of the past?

**Comment by davidfowl** [comment]
You should consider using a combination of `ILibraryManager` and `System.Reflection.Metadata` to read metadata.

**Comment by cherrydev** [comment]
`System.Reflection.Metadata`, the package whose documentation appears to consist entirely of a title and a short list of release notes on an MSDN blog page?  http://blogs.msdn.com/b/bclteam/p/metadata.aspx

Yes, since it appears that I can, for example, call GetCustomAttributes() on a TypeDefinition, it seems exactly what I'm looking for, but while LibraryManager provides ILibraryExport objects which have a "MetadataReferences" property on them, that metadata doesn't appear related to `System.Reflection.Metadata`.
How would I go about, for example, getting `System.Reflection.Metadata` objects out of ILibraryManager?  From a source code search, nothing in the DNX project references System.Reflection.Metadata (except LogFileUtils).
The only examples I've seen of `System.Reflection.Metadata` need to read a PE file (or bytes of) and nothing I can see related to LibraryManager exposes that.
Please let me know if you think I've missed anything obvious, thanks.

**Comment by muratg** [comment]
@cherrydev Thanks... adding discussion label to this and closing as there doesn't seem to be a need for a code change on dnx.  Feel free to continue discussing this here, or on Jabbr.

**Comment by cherrydev** [comment]
A discussion sort of needs more than one participant and I feel like my questions have been pretty clear (or at least no clarification has been asked of me).  I'd be happy to continue the conversation if someone will step up and participate in it, thanks!

**Comment by davidfowl** [comment]
We don't expose the assemblt paths in the library manager but we could. It would allow you to use the API to open a file stream to get the metadata

**Comment by cherrydev** [comment]
I think that was exactly what I was originally trying to accomplish and is cleaner than the solution that I ultimately came up with.
