### ISSUE TITLE
UI for Errors stemming from Project.Lock.json files are confusing and do not lead to the real source of the problem

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#1629]
From @MattGal from a TFS bug.

## Steps to reproduce:

I had a project that depends on 4.0.20-beta-22516 of System.RUntime.dll.  This was removed from the feed and is no longer available.  This had left some cruft in the project.lock.json file

You'd expect one of two behaviors from this.

Roll forward, to next available version ( 4.0.20-beta-22605 ) and hope they're compatible.  Bonus points if you show me a warning in the build window or some other surfacing of this in the UI.

or (probably best choice)

An error saying it failed to restore this package... after all it does not exist.

## Actual behavior:

An error does show up... but double clicking it takes me to an MSBuild target in `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets`.

![image](https://cloud.githubusercontent.com/assets/202643/7078435/d71be6d4-decd-11e4-907f-b3e1c8e1f4b1.png)

In this case, the error also seems to be in a generated file, NOT something the user is expected to craft (nasty!)  since it is visible to the user, it'd be nice for the tooling to point them to the new project.lock.json file.

**Comment by davidfowl** [comment]
@MattGal This experience is improved in later builds.

**Comment by davidfowl** [comment]
This is fixed now. If the package isn't on disk it will show up as unresolved.
