### ISSUE TITLE
Trim the nupkg generated by "dnu publish --no-source"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1631]
Today `dnu publish --no-source` builds dependencies projects for all frameworks specified in `project.json`.

When `--runtime` is specified, we can trim generated nupkg by only building for given runtimes

**Comment by borgdylan** [comment]
Can it be trimmed for given frameworks? Like dnx451 only which would trim net40 specific stuff together with dncxore50 etc?

**Comment by muratg** [comment]
@borgdylan Yup.  See https://github.com/aspnet/dnx/issues/2428 where this was fixed.
