### ISSUE TITLE
dnu commands install doesn't respect NuGet.Config

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1635]
```
Davids-MacBook-Pro:aspnet-buzz dfowler$ dnu commands install SecretManager --no-cache   GET https://nuget.org/api/v2/FindPackagesById()?Id='SecretManager'.   OK https://nuget.org/api/v2/FindPackagesById()?Id='SecretManager' 1516ms Unable to locate the package SecretManager The name of the package to be installed was not specified.
```
/cc @victorhurdugaci

**Comment by atheken** [comment]
I think this is related and may help people getting going with dnx:

On OS X, I need to call `dnu restore` with the following sources in order to get the nightly bits, YMMV.

`dnu restore -s https://www.myget.org/F/aspnetvnext/ -f https://www.nuget.org/api/v2/`

**Comment by davidfowl** [comment]
This has nothing to do with restore, that fine

**Comment by atheken** [comment]
@davidfowl Is it possible to set default feeds for dnu?

**Comment by aggieben** [comment]
You can do this in %AppData%\NuGet\NuGet.config.  Here's mine:

```
<packageSources>
    <add key="ASP.NET 5 Dev" value="https://www.myget.org/F/aspnetvnext" />
    <add key="xunit-dnvm" value="https://www.myget.org/F/xunit-dnvm/api/v2/" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
```

**Comment by atheken** [comment]
@aggieben Hmm, on OS X here, do you happen to know the default location for OS X?

**Comment by aggieben** [comment]
`~/.config/NuGet/NuGet.Config`, I think.

**Comment by victorhurdugaci** [comment]
Global install uses only the global `NuGet.config` file. Otherwise, could get different results based on where you run it from.

**Comment by aggieben** [comment]
@victorhurdugaci "global install" isn't a thing anymore, is it?  I'm running into this right now: when I run `dnu restore` (installed in `%USERPROFILE%\.dnx`), it uses my `%AppData%\NuGet\NuGet.config` instead of the `NuGet.config` I have in my solution directory, tracked in source control.
