### ISSUE TITLE
Support for background services

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/dnx#1638]
I'd like to ask whether there will be supoort for background services, meaning an application that doesn't have to run within web server and runs on background without anyone logging into the computer while utilizing the .net core and libraries written as "asp.net vnext class library"?

If there won't be explicit support, what is the recommended approach to run continuous tasks in background?

Thanks

(please redirect me if this is not appropriate place for this discussion)

**Comment by davidfowl** [comment]
@Kukkimonsuta Can you open this on aspnet/Home?
