### ISSUE TITLE
[Test] Unzip the dnx runtime in a persist location during functional test to improve test performance

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1651]
https://github.com/aspnet/dnx/blob/dev/test/Microsoft.Framework.FunctionalTestUtils/TestUtils.cs#L109

/cc @davidfowl @ChengTian @muratg

**Comment by BrennanConroy** [comment]
?

**Comment by troydai** [comment]
we unzip to a temp folder and delete after every tests. unzipping and file copy is time consuming and tax the hard disk heavily.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/dnx/blob/dev/test/Microsoft.Framework.FunctionalTestUtils/TestUtils.cs#L91

**Comment by troydai** [comment]
good catch. but it doesn't work if you're not running test in batch. for example `dnx . test -method <name>` will still trigger a unzip. plus the logic you pointed out relies on makefile to establish the cache.

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/dnx/commit/19779308553bb18acaeeed86075595365dba9f82
