### ISSUE TITLE
Changing default templated ASP Web project over to CoreClr produces totally bogus build error

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1671]
Repro: 
1. New aspnet web Application
2. Build, all is good
3. Remove dnx451
4. Build. You get an error in RazorPrecompilation.cs 
5. To make sure it is not a DTH|VS thing, change the build option to produce outputs
6. Build. Get the same errors from the command line build.

There's a corresponding bug on WTE issue tracker for the Tooling side of the fix.

**Comment by muratg** [comment]
Brennan, can you see if this repros?  This was reported by the tooling team.

**Comment by BrennanConroy** [comment]
Version 14.0.22823.1 D14REL doesn't seem to have this issue.

**Comment by BrennanConroy** [comment]
Close as dupe: #1777
