### ISSUE TITLE
Can't compile against MonoTouch/MonoAndroid

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#1680]
Similar to #1679, but it get's a bit further:

    Building Microsoft.Data.Sqlite for MonoTouch,Version=v0.0
      Using Project dependency Microsoft.Data.Sqlite 1.0.0
        Source: C:\Projects\DataCommon.SQLite\src\Microsoft.Data.Sqlite\project.json

      Unable to resolve dependency framework/mscorlib

**Comment by davidfowl** [comment]
I assume you have those frameworks installed?

**Comment by bricelam** [comment]
Yes, they're installed.

**Comment by muratg** [comment]
@anurse.

Are we supporting this (and #1679) in V1?

**Comment by anurse** [comment]
It shouldn't be too hard, but to do it right we'll want a CI that has the frameworks installed so we can test it

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#588
