### ISSUE TITLE
Installing Xamarin disrupts portable package resolution

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#1681]
Given the following `project.json`...
```JSON
{
    "dependencies": {
        "System.Collections.Immutable": "1.1.34-rc"
    },
    "frameworks": {
        ".NETPortable,Version=v4.5,Profile=Profile7": {
            "frameworkAssemblies": {
                "System.Runtime": "4.0.0.0"
            }
        }
    }
}
```
...and the following code...
```C#
using System.Collections.Immutable;
```
...it builds fine without Xamarin installed.

But, when I install Xamarin, it fails:

    Loaded Module: dnx.clr.dll
    Found DLL Export: CallApplicationMain
    Information: [LoaderContainer]: Load name=Microsoft.Framework.PackageManager
    Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Framework.PackageManager in 57ms

    Building Test for .NETPortable,Version=v4.5,Profile=Profile7
    Information: [DependencyWalker]: Walking dependency graph for 'Test DNX,Version=v4.5.1'.
    Information: [WalkContext]: Graph walk stage 1 took in 53ms
    Information: [DependencyWalker]: Graph walk took 60ms.
    Information: [WalkContext]: Populate took 15ms
    Information: [DependencyWalker]: Resolved dependencies for Test in 78ms
    Information: [DependencyWalker]: Walking dependency graph for 'Test .NETPortable,Version=v4.5,Profile=Profile7'.
    Information: [WalkContext]: Graph walk stage 1 took in 5ms
    Information: [DependencyWalker]: Graph walk took 5ms.
    Information: [WalkContext]: Populate took 0ms
    Information: [DependencyWalker]: Resolved dependencies for Test in 6ms
    Information: [ProjectExportProviderHelper]: Resolving references for 'Test'
    Information: [ProjectLibraryExportProvider]: GetLibraryExport(Test, .NETPortable,Version=v4.5,Profile=Profile7, Debug, )
    Information: [Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler]: GetProjectReference(Test, .NETPortable,Version=v4.5,Profile=Profile7, Debug, )
    Information: [ProjectExportProviderHelper]: Resolving references for 'Test'
    Information: [ProjectExportProviderHelper]: Resolved 1 references for 'Test' in 4ms
    Information: [RoslynCompiler]: Compiling 'Test'
    Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing
    Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing
    Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing.Algorithms
    Information: [LoaderContainer]: Load name=System.Security.Cryptography.Hashing.Algorithms
    Information: [LoaderContainer]: Load name=System.IO.FileSystem
    Information: [LoaderContainer]: Load name=System.IO.FileSystem
    Information: [RoslynCompiler]: Compiled 'Test' in 614ms
    Information: [ProjectExportProviderHelper]: Resolved 2 references for 'Test' in 687ms
      Using Project dependency Test 1.0.0
        Source: C:\Users\bricelam\Desktop\Test\project.json

      Using Package dependency System.Collections.Immutable 1.1.34-rc
        Source: C:\Users\bricelam\.dnx\packages\System.Collections.Immutable\1.1.34-rc

      Using Assembly dependency framework/System.Runtime 4.0.0.0
        Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Runtime.dll

    Information: [ProjectLibraryExportProvider]: GetLibraryExport(Test, .NETPortable,Version=v4.5,Profile=Profile7, Debug, )
    Information: [CompilationContext]: Generating resources for Test
    Information: [CompilationContext]: Generated resources for Test in 6ms
    Information: [RoslynProjectReference]: Emitting assembly for Test
    Information: [RoslynProjectReference]: Emitted Test in 216ms
    C:\Users\bricelam\Desktop\Test\Class1.cs(1,26): error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?)

    Build failed.
        0 Warnings(s)
        1 Error(s)

    Time elapsed 00:00:01.7242071

If I remove the following files from the `.NETPortable\v4.5\Profile\Profile7\SupportedFrameworks` directory, it builds again.
- Xamarin.Android.xml
- Xamarin.iOS.Unified.xml
- Xamarin.iOS.xml

**Comment by davidfowl** [comment]
I wonder if it has anything to do with those platforms not being understood

**Comment by bricelam** [comment]
My suspicion was that it's failing because now it's trying to see if net45+win+monotouch+monoandroid+xamarinios is a subset of net45+win.

Xamarin? | Project | Package | Compatible?
---- | ------ | --------- | ------
No | net45+win | net45+win | Yes
Yes | net45+win+monotouch+monoandroid+xamarinios | net45+win | No

**Comment by davidfowl** [comment]
installed xamarin and I can reproduce this now.

**Comment by muratg** [comment]
@davidfowl What was the outcome of your investigation?

**Comment by davidfowl** [comment]
Should be fixed now
