### ISSUE TITLE
Run both CLR and CoreCLR version of dnx in tests to get better coverage

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1685]
In some tests, we need to invoke the newly built dnx to do some tasks like `dnu pack` or `dnu restore`. Currently we just pick an arbitrary flavor of dnx to run and it doesn't have good coverage.

An example is: https://github.com/aspnet/dnx/blob/dev/test/Microsoft.Framework.PackageManager.Tests/LockFileUtilsFacts.cs#L25

`TestUtils.GetRuntimeComponentsCombinations().Last()` returns a CLR version of dnx, so we don't have coverage for CoreCLR version of dnx in this test case.

**Comment by BrennanConroy** [comment]
The functional tests test all the CLR versions of dnx, and they should have coverage of things like dnu pack and dnu restore, so the non-functional tests just need to grab any dnx and use it.

**Comment by ChengTian** [comment]
Great. @pranavkm , then we can pick an arbitrary flavor of dnx in LockFileUtilsFacts
