### ISSUE TITLE
How to load specific version assembly from GAC in ASP Net vNext

### ISSUE THREAD

**Issue by gurunathancs1991** [aspnet/dnx#1688]
I can load the assembly from GAC in ASP.Net 5 application. but i couldn't load the specific version. please have a look on my codes.

[project.json]

    "frameworks": {
    "aspnet50": { },
    "aspnetcore50": { },
    "net45": {
        "frameworkAssemblies": {
            "System.Web.Mvc": "5.0.0.0"
        }

    }
}
In above code in project.json file, i have tried to load MVC 5.but it doesn't load in reference instead of that, it will show like with corrupted symbol. Even these assemblies are available in GAC. i have tried with some other assemblies. Am getting the same error only.

In case if i load without version details. it will automatically load the lowest version of MVC. i.e., MVC 3 is the lowest version in my machine. that was loaded in reference.

this is not with MVC assembly alone. we can reproduce it any assembly by following the below scenario. 

Am having an assembly named as 'EssentialASP" which was available in GAC in two version like 1.0.0.0 , 2.0.0.0. If i refer without assembly version it will automatically load the lowest version. but if i try to refer some other version other than lower i.e., 2.0.0.0 then it couldn't load in the project (showing with corrupted symbol) in the reference section.

**Comment by muratg** [comment]
@gurunathancs1991 I believe ```frameworkAssemblies``` section is for specifying .NET Framework assemblies.  Instead of using GAC, I recommend using ```dnu wrap``` to wrap the particular assembly you'd like with your project.  This would give you the option to use CoreCLR in the future, and also potentially go cross platform.

That being said @davidfowl do we support version info for frameworkAssemblies?  Should we just throw if there's anything specified there?

**Comment by GuardRex** [comment]
@muratg 
> option to use CoreCLR in the future
Does this mean that `dnu wrap` could be used to roll `System.Net.Mail` into a `dnxcore50

**Comment by davidfowl** [comment]
@GuardRex nope

**Comment by troydai** [comment]
I can repo this issue. Investigating ...

**Comment by troydai** [comment]
It's a bug in `GacDependencyResolver`, it takes the first gac assembly which matches the reference name but doesn't compare the version.
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime/DependencyManagement/GacDependencyResolver.cs#L61

I'm working on the fix.

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/dnx/commit/ce597a99c5af8f8069d4a99499f77fbe2f730d24
