### ISSUE TITLE
Verify Kudu support 

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1704]
- [x] Find out how Kudu figures out SDK version for their build scripts.
- [ ] Ensure we can deploy ASP.NET 5 apps with different DNX versions to Antares

**Comment by troydai** [comment]
@mikaelm12 has tested the scenario on beta5.

**Comment by troydai** [comment]
We will proceed to a beta6 test later.

**Comment by muratg** [comment]
Load balancing to @BrennanConroy

**Comment by BrennanConroy** [comment]
https://github.com/projectkudu/kudu/issues/1623 (Read architecture and runtime from global.json) [fixed]

**Comment by Jabe** [comment]
Successfully deployed beta6 app to Azure after adding a global.json.

**Comment by muratg** [comment]
Thanks @Jabe!
