### ISSUE TITLE
VB support

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1706]

**Comment by ErikSchierboom** [comment]
Any chance for F# support too?

**Comment by Eilon** [comment]
@ErikSchierboom not currently planned but that would be a good project for the community to start up.

**Comment by davidfowl** [comment]
VB, F#, dylan.NET (yes this is a real language) support will all be via the same mechanism. This is a generic extensibility point. The real problems come when tooling support is added (intellisense support in Visual Studio etc.)

**Comment by ErikSchierboom** [comment]
@davidfowl So the VB support will be like a template for how to do F# integration?

**Comment by davidfowl** [comment]
Yes and just FYI this isn't new https://github.com/YoloDev/YoloDev.FSharp.AspNet. https://github.com/davidfowl/vNextLanguageSupport. Language support was refactored a while ago so that we can add more languages. That's not really the big problem, though it still needs to be cleaned up.

**Comment by ErikSchierboom** [comment]
That looks promising! Will there be any kind of documentation on how new languages can be added, or will we be able to infer that from the added VB support?

**Comment by davidfowl** [comment]
There'll be something documented once the churn ends. Talk to @Alxandr, he's spent a considerable amount of time experimenting with F# and the dnx compilation system (even got it working with in memory assemblies).

**Comment by Alxandr** [comment]
Yes, and then, when I started looking at it again like 5 hrs ago, everything has blown up xD.

Well, unstable APIs and all that. I'll try to get F# support working again against beta5 soon~ish.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#587
