### ISSUE TITLE
Deduplicate error messages shared by different frameworks

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1710]
Today, an error message is duplicated if it happens to multiple frameworks.

![capture](https://cloud.githubusercontent.com/assets/1383883/7329323/b0cca27c-ea92-11e4-8943-68262e1259a8.PNG)

We should merge identical error messages if they only differ in the aspect of framework and have something like

```
----------------------------------------------------------------------
|    Description     |                        Project                |
----------------------------------------------------------------------
| error message 1    |    ProjectA (framework1, framework2)          |
| error message 2    |    ProjectA (framework1)                      |
| error message 3    |    ProjectA (framework2)                      |
----------------------------------------------------------------------
```

**Comment by ChengTian** [comment]
I think the easiest way to do it is asking Tooling team to do a `GroupBy()` on error messages. Then we can have
```
--------------------------------------------------------------------------------
|       Description      |                        Project                           |
--------------------------------------------------------------------------------
| error message 1    |    ProjectA (framework1, framework2) |
| error message 2    |    ProjectA (framework1)                      |
| error message 3    |    ProjectA (framework2)                      |
--------------------------------------------------------------------------------
```

@davidfowl , do you like this approach?

**Comment by davidfowl** [comment]
We want the errors to look the same across DTH and command line. Talk to @BillHiebert and come up with a consistent scheme for showing errors like that. I like what you have there (grouping by error location). We need to see if the error list in VS supports this.
