### ISSUE TITLE
Need a setting in project.json to enable xml doc comments

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/dnx#1717]
This option is needed to allow generation of xml doc comments. It would also be picked up by tooling to provide diagnostics for broken or missing comments.

**Comment by barrytang** [comment]
Happening in beta5?

**Comment by barrytang** [comment]
@Eilon, @davidfowl ?

**Comment by muratg** [comment]
When we internalized the JSON parser (and moved away from json.net, we decided not to add comment support on json files, as they are not valid per the RFC.

**Comment by GuardRex** [comment]
@BillHiebert If you mean comments in the project.json file, it was discussed here ...
https://github.com/aspnet/Announcements/issues/24
https://github.com/aspnet/dnx/issues/1816

**Comment by muratg** [comment]
Or do you guys mean a switch which would enable/disable XML comment generation on source code?

**Comment by Eilon** [comment]
This is about generating the doc XML file. Nothing to do with comments in JSON :smile:

**Comment by Eilon** [comment]
And BTW I thought we always generate it now, don't we? At most I think we'd have an option to turn it off (though, do we even need that?).

**Comment by BillHiebert** [comment]
@davidfowl  
Looks like that is the case. So I should just enable it by default instead of having it disabled by default.

**Comment by barrytang** [comment]
Moved to U1.

@BillHiebert's comment:

I put in a small change to enable document comments in the language service since the runtime is generating the xml file anyway. However, Roslyn does a lot of validation (kind of like fxcop) when doc comments are enabled and I see 260 warnings in the error list for a new Web Application.

**Comment by barrytang** [comment]
![foo](https://cloud.githubusercontent.com/assets/1648865/8075595/05d8ba8e-0ef7-11e5-94ad-05b426422cd2.png)

**Comment by davidfowl** [comment]
Uhhhh this cannot be on by default.

**Comment by BillHiebert** [comment]
Nope. I punted the bug to update1 until there is a way to enable\disable the feature in project.json

**Comment by davidfowl** [comment]
Sweet

**Comment by barrytang** [comment]
@davidfowl, where are we at with the runtime change?

**Comment by davidfowl** [comment]
@barrytang This bug isn't in a milestone and so it doesn't exist :smile:

**Comment by barrytang** [comment]
@BillHiebert, can you update it? I don't seem to have permission to.

**Comment by BillHiebert** [comment]
How do I do that?

**Comment by BillHiebert** [comment]
Looks like I don't have permission either. I assume it is because this is in the Dnx project

**Comment by barrytang** [comment]
@davidfowl, what kind of tool is this? :)

Can you set the milestone?

**Comment by Anderman** [comment]
@muratg  I found a incorrect xml documetation. Is this something that will be fixed later or do like I make a new issue of this
```
/// <summary>
        /// Initalizes a new instance of the <see cref="RoslynCompilationService"/> class.
        /// </summary>
        /// <param name="environment">The environment for the executing application.</param>
        /// <param name="loaderAccessor">
        /// The accessor for the <see cref="IAssemblyLoadContext"/> used to load compiled assemblies.
        /// </param>
        /// <param name="libraryManager">The library manager that provides export and reference information.</param>
        /// <param name="compilerOptionsProvider">
        /// The <see cref="ICompilerOptionsProvider"/> that provides Roslyn compilation settings.
        /// </param>
        /// <param name="host">The <see cref="IMvcRazorHost"/> that was used to generate the code.</param>
        public RoslynCompilationService(
            IApplicationEnvironment environment,
            IAssemblyLoadContextAccessor loaderAccessor,
            ILibraryExporter libraryExporter,
            ICompilerOptionsProvider compilerOptionsProvider,
            IMvcRazorHost host,
            IOptions<RazorViewEngineOptions> optionsAccessor)
```

**Comment by muratg** [comment]
@Anderman That class is in MVC repo, please file a bug in that repo.  This bug in particular tracks ability to generate XML doc comments file for your libraries and apps.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#585
