### ISSUE TITLE
Inconsistent DNX install behaviour on Windows and Ubuntu

### ISSUE THREAD

**Issue by conniey** [aspnet/dnx#1718]
I followed the instructions to get started using this: [Getting Started Debian](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md)

When I execute `dnvm upgrade`, it cannot find DNX to install.

```
conniey@conniey-ubuntu:~/git/dotnet-apiweb$ cat ~/.config/NuGet/NuGet.config 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources />
</configuration>
conniey@conniey-ubuntu:~/git/dotnet-apiweb$ dnvm upgrade
Determining latest version
Error: Could not find latest version from feed https://nuget.org/api/v2
conniey@conniey-ubuntu:~/git/dotnet-apiweb$ 
```

However, the same command works on Windows and it will install the "unstable" version 1.0.0-beta5-11624 from `https://www.myget.org/F/aspnetvnext/api/v2` even though I did not pass the `-unstable` flag.

**Comment by davidfowl** [comment]
This works now. You have 2 differenet versions of dnvm
