### ISSUE TITLE
dnu publish breaks the build

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1719]
On a project that is correct and compiles (I tried with MusicStore) do:

```
dnu build
dnu publish --runtime dnx-coreclr-win-x64.1.0.0-beta5-11624 --no-source
dnu build
```

Publish fails. Then the second build should work. It actually fails and you are no longer able to build the project until you delete the `bin` folder

cc @davidfowl

**Comment by davidfowl** [comment]
@victorhurdugaci does this only repro with music store?

**Comment by davidfowl** [comment]
I can't reproduce this with a simple application. Showing me the errors you got would be great.

**Comment by muratg** [comment]
@victorhurdugaci is this still a problem?  If not, let's close.

**Comment by victorhurdugaci** [comment]
No more repro
