### ISSUE TITLE
dnu publish should fail if xproj has a dependency to csproj and csproj binaries are not available

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#1720]
dnu publish should fail if xproj has a dependency to csproj and csproj binaries are not available

Repro steps:
1. Create an xproj.
2. Add reference to a csproj.
3. delete all the csproj outputs (bin , obj, from wrap etc)
4. Run dnu publish for the xproj project.

expected:
dnu publish fails because csproj output is not available.

actual:
dnu publish succeeds. The output folder does not contains the csproj output, so it fails at runtime.

**Comment by vijayrkn** [comment]
@ChengTian

**Comment by muratg** [comment]
@vijayrkn Is this still a problem?

**Comment by davidfowl** [comment]
I think this is by design
