### ISSUE TITLE
dnu packages add doesn't overwrite destination if it already exists

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#1726]
**Repro:**
1. Create a NuGet package (doesn't matter what's in it)
2. Run `dnu packages add MyPackage.1.0.0.nupkg c:\pkgs`
3. Modify the original NuGet package in some verifiable way (e.g. change something in the nuspec, add a file, etc.)
4. Run `dnu packages add MyPackage.1.0.0.nupkg c:\pkgs` *again*

**Result:**
Step (4) does nothing, though there's no warning of any sort. That is, the original "exploded" package remains in `c:\pkgs`, untouched.

**Expected:**
Step (4) should overwrite the destination.

----------

This in fact causes issues in our own build system where we publish packages to the volatile feed on the CI. For example with a lot of internal packages that we consume (e.g. Roslyn), their package id's and version numbers don't change on each build, so our build system thinks it's updating Roslyn builds in the volatile feed with `dnu packages add ...` when in fact it's no-op'ing.

**Comment by Eilon** [comment]
@danroth27 @davidfowl

**Comment by davidfowl** [comment]
Ugh, we should fix that.

**Comment by Eilon** [comment]
@muratg can we get someone to take a look at this this week? This is a must-fix to ship even the next preview because we use this command on the CI and it doesn't work as we want it to.

**Comment by davidfowl** [comment]
@ChengTian a simple change would be to compare the sha's. If they differ then overwrite. Also we should print out a message that shows what action was taken (overwrite, vs already exists).
