### ISSUE TITLE
Set the global regex timeout to a suitable value (and allow for easy dev changes)

### ISSUE THREAD

**Issue by blowdart** [aspnet/dnx#1730]
Default regex timeout is infinite. For web apps this is a bad idea.

Set it to a more sensible value (https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.matchtimeout%28v=vs.110%29.aspx)

```
   AppDomain domain = AppDomain.CurrentDomain;
  // Set a timeout interval of 2 seconds.
  domain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", TimeSpan.FromSeconds(2));
```

Expose a setting to allow devs easier access that the monstrous code above.

**Comment by glennc** [comment]
How is this different to https://github.com/aspnet/dnx/issues/1752?

**Comment by blowdart** [comment]
1752 was about specific instances of regexs in the framework. This is about choosing a default timeout for all regexs, framework or otherwise. Doesn't work in coreclr though, or didn't when I proposed this.

**Comment by davidfowl** [comment]
@blowdart I'm not sure I understand what this is suggesting. Is `REGEX_DEFAULT_MATCH_TIMEOUT` a special key that is respected on full CLR? Didn't we do this work already?

**Comment by blowdart** [comment]
I have no idea what work you have done sometimes. And yes, it's a special CLR key that is respected on desktop, as you can see by following the MSDN link above.

**Comment by brentschmaltz** [comment]
Is this key respected on fxCore?
