### ISSUE TITLE
dnu publish prints a lot of log messages even when quiet flag is passed.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#1734]
C:\Users\vramak\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11624\bin\dnu.cmd publish "C:\Users\vramak\Documents\Visual Studio Next\Projects\WebApplication412\src\WebApplication412" --out "C:\Users\vramak\AppData\Local\Temp\PublishTemp" --configuration Release --runtime dnx-clr-win-x86.1.0.0-beta5-11624 --wwwroot-out "wwwroot" --quiet

Expected: minimal output

Actual:
Installing Microsoft.AspNet.Server.IIS 1.0.0-beta5-11599
Add complete, 28ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Server.WebListener\1.0.0-beta5-12015\Microsoft.AspNet.Server.WebListener.1.0.0-beta5-12015.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Server.WebListener 1.0.0-beta5-12015
Add complete, 34ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.runner.aspnet\2.0.0-aspnet-beta5-10311\xunit.runner.aspnet.2.0.0-aspnet-beta5-10311.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.runner.aspnet 2.0.0-aspnet-beta5-10311
Add complete, 30ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Loader.IIS.Interop\1.0.0-beta5-11599\Microsoft.AspNet.Loader.IIS.Interop.1.0.0-beta5-11599.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Loader.IIS.Interop 1.0.0-beta5-11599
Add complete, 70ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Loader.IIS\1.0.0-beta5-11599\Microsoft.AspNet.Loader.IIS.1.0.0-beta5-11599.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Loader.IIS 1.0.0-beta5-11599
Add complete, 50ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Http.Interfaces\1.0.0-beta5-11382\Microsoft.AspNet.Http.Interfaces.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Http.Interfaces 1.0.0-beta5-11382
Add complete, 29ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Hosting.Server.Interfaces\1.0.0-beta5-11653\Microsoft.AspNet.Hosting.Server.Interfaces.1.0.0-beta5-11653.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Hosting.Server.Interfaces 1.0.0-beta5-11653
Add complete, 31ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Logging.Interfaces\1.0.0-beta5-11275\Microsoft.Framework.Logging.Interfaces.1.0.0-beta5-11275.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Logging.Interfaces 1.0.0-beta5-11275
Add complete, 65ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Net.Http.Server\1.0.0-beta5-12015\Microsoft.Net.Http.Server.1.0.0-beta5-12015.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Net.Http.Server 1.0.0-beta5-12015
Add complete, 65ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Runtime.Interfaces\1.0.0-beta5-11624\Microsoft.Framework.Runtime.Interfaces.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Runtime.Interfaces 1.0.0-beta5-11624
Add complete, 33ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.TestHost\1.0.0-beta5-11363\Microsoft.Framework.TestHost.1.0.0-beta5-11363.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.TestHost 1.0.0-beta5-11363
Add complete, 38ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.assert\2.0.0-rc3-build2880\xunit.assert.2.0.0-rc3-build2880.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.assert 2.0.0-rc3-build2880
Add complete, 23ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.execution.AspNet\2.0.0-aspnet-beta5-10274\xunit.execution.AspNet.2.0.0-aspnet-beta5-10274.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.execution.AspNet 2.0.0-aspnet-beta5-10274
Add complete, 51ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.runner.utility.AspNet\2.0.0-aspnet-beta5-10274\xunit.runner.utility.AspNet.2.0.0-aspnet-beta5-10274.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.runner.utility.AspNet 2.0.0-aspnet-beta5-10274
Add complete, 36ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.DataProtection.Interfaces\1.0.0-beta5-11277\Microsoft.AspNet.DataProtection.Interfaces.1.0.0-beta5-11277.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.DataProtection.Interfaces 1.0.0-beta5-11277
Add complete, 49ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Hosting\1.0.0-beta5-11653\Microsoft.AspNet.Hosting.1.0.0-beta5-11653.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Hosting 1.0.0-beta5-11653
Add complete, 30ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.WebEncoders.Core\1.0.0-beta5-11382\Microsoft.Framework.WebEncoders.Core.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.WebEncoders.Core 1.0.0-beta5-11382
Add complete, 57ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.FeatureModel\1.0.0-beta5-11382\Microsoft.AspNet.FeatureModel.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.FeatureModel 1.0.0-beta5-11382
Add complete, 29ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.ConfigurationModel.Interfaces\1.0.0-beta5-11230\Microsoft.Framework.ConfigurationModel.Interfaces.1.0.0-beta5-11230.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.ConfigurationModel.Interfaces 1.0.0-beta5-11230
Add complete, 59ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Net.WebSockets\1.0.0-beta5-12015\Microsoft.Net.WebSockets.1.0.0-beta5-12015.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Net.WebSockets 1.0.0-beta5-12015
Add complete, 34ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.TestAdapter\1.0.0-beta5-11363\Microsoft.Framework.TestAdapter.1.0.0-beta5-11363.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.TestAdapter 1.0.0-beta5-11363
Add complete, 29ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.ApplicationHost\1.0.0-beta5-11624\Microsoft.Framework.ApplicationHost.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.ApplicationHost 1.0.0-beta5-11624
Add complete, 33ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.CommandLineUtils\1.0.0-beta5-11624\Microsoft.Framework.CommandLineUtils.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.CommandLineUtils 1.0.0-beta5-11624
Add complete, 39ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Logging\1.0.0-beta5-11275\Microsoft.Framework.Logging.1.0.0-beta5-11275.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Logging 1.0.0-beta5-11275
Add complete, 52ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Runtime\1.0.0-beta5-11624\Microsoft.Framework.Runtime.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Runtime 1.0.0-beta5-11624
Add complete, 65ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Newtonsoft.Json\6.0.6\Newtonsoft.Json.6.0.6.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Newtonsoft.Json 6.0.6
Add complete, 293ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.abstractions\2.0.0-rc3-build2880\xunit.abstractions.2.0.0-rc3-build2880.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.abstractions 2.0.0-rc3-build2880
Add complete, 35ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\xunit.extensibility.core\2.0.0-rc3-build2880\xunit.extensibility.core.2.0.0-rc3-build2880.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing xunit.extensibility.core 2.0.0-rc3-build2880
Add complete, 49ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.FileProviders\1.0.0-beta5-11272\Microsoft.AspNet.FileProviders.1.0.0-beta5-11272.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.FileProviders 1.0.0-beta5-11272
Add complete, 41ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Hosting.Interfaces\1.0.0-beta5-11653\Microsoft.AspNet.Hosting.Interfaces.1.0.0-beta5-11653.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Hosting.Interfaces 1.0.0-beta5-11653
Add complete, 29ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Http\1.0.0-beta5-11382\Microsoft.AspNet.Http.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Http 1.0.0-beta5-11382
Add complete, 38ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Http.Extensions\1.0.0-beta5-11382\Microsoft.AspNet.Http.Extensions.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Http.Extensions 1.0.0-beta5-11382
Add complete, 38ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.ConfigurationModel\1.0.0-beta5-11230\Microsoft.Framework.ConfigurationModel.1.0.0-beta5-11230.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.ConfigurationModel 1.0.0-beta5-11230
Add complete, 83ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.DependencyInjection\1.0.0-beta5-11259\Microsoft.Framework.DependencyInjection.1.0.0-beta5-11259.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.DependencyInjection 1.0.0-beta5-11259
Add complete, 60ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.DependencyInjection.Interfaces\1.0.0-beta5-11277\Microsoft.Framework.DependencyInjection.Interfaces.1.0.0-beta5-11277.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.DependencyInjection.Interfaces 1.0.0-beta5-11277
Add complete, 79ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Runtime.Loader\1.0.0-beta5-11624\Microsoft.Framework.Runtime.Loader.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Runtime.Loader 1.0.0-beta5-11624
Add complete, 32ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Runtime.Caching\1.0.0-beta5-11624\Microsoft.Framework.Runtime.Caching.1.0.0-beta5-11624.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Runtime.Caching 1.0.0-beta5-11624
Add complete, 33ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.FileProviders.Interfaces\1.0.0-beta5-11272\Microsoft.AspNet.FileProviders.Interfaces.1.0.0-beta5-11272.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.FileProviders.Interfaces 1.0.0-beta5-11272
Add complete, 47ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.Http.Core\1.0.0-beta5-11382\Microsoft.AspNet.Http.Core.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.Http.Core 1.0.0-beta5-11382
Add complete, 37ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.AspNet.WebUtilities\1.0.0-beta5-11382\Microsoft.AspNet.WebUtilities.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.AspNet.WebUtilities 1.0.0-beta5-11382
Add complete, 33ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Net.Http.Headers\1.0.0-beta5-11382\Microsoft.Net.Http.Headers.1.0.0-beta5-11382.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Net.Http.Headers 1.0.0-beta5-11382
Add complete, 47ms elapsed
Adding NuGet package C:\Users\vramak\.dnx\packages\Microsoft.Framework.Caching.Interfaces\1.0.0-beta5-11251\Microsoft.Framework.Caching.Interfaces.1.0.0-beta5-11251.nupkg to C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\packages
Installing Microsoft.Framework.Caching.Interfaces 1.0.0-beta5-11251
Add complete, 60ms elapsed
Restoring packages for C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\src\WebApplication412\project.json
Writing lock file C:\Users\vramak\AppData\Local\Temp\PublishTemp\approot\src\WebApplication412\project.lock.json

**Comment by vijayrkn** [comment]
@ChengTian

**Comment by ChengTian** [comment]
Should be regression introduced in recent dnu publish changes.

**Comment by muratg** [comment]
Didn't repro with my basic smoke level testing.  Closing.  Please reopen if you still hit this @vijayrkn
