### ISSUE TITLE
DNU on OSX fails with space in home directory

### ISSUE THREAD

**Issue by salerth** [aspnet/dnx#1735]
On my work macbook, the user home directories are symlink to a seperate volume, which has a space in the name.

i.e. /Users/bob -> /Volumes/User Data/Users/bob

dnu wont run at all, with the following error : 

/Users/bob/.dnx/runtimes/dnx-mono.1.0.0-beta5-11649/bin/dnu: line 12: /Volumes/User: No such file or directory

**Comment by muratg** [comment]
@salerth Thanks for the contribution!

@ChengTian can we get this in by tomorrow?

**Comment by ChengTian** [comment]
Travis and Appveyor failed with non-relevant failure. I'll test @salerth 's PR and merge it today.

**Comment by ChengTian** [comment]
Merged: https://github.com/aspnet/dnx/commit/c076b0417dd998c2252d6ae88bc82a2dbf4777d8
