### ISSUE TITLE
dnx-coreclr-linux's DNX complains about libcoreclrpal.so

### ISSUE THREAD

**Issue by colemickens** [aspnet/dnx#1744]
```
[mono-20150421154735]root@649644f8e8a9:/opt/polykube/dotnet/src/Polykube.Api# dnvm install latest -r coreclr -u
Determining latest version
Latest version is 1.0.0-beta5-11657 
Downloading dnx-coreclr-linux-x64.1.0.0-beta5-11657 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-linux-x64/1.0.0-beta5-11657
######################################################################## 100.0%
Installing to /root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-11657
Adding /root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-11657/bin to process PATH

[mono-20150421154735]root@649644f8e8a9:/opt/polykube/dotnet/src/Polykube.Api# dnx
failed to locate libcoreclr with error libcoreclrpal.so: cannot open shared object file: No such file or directory
```

**Comment by colemickens** [comment]
I had the same behavior running in a docker container under Arch, as well as a standard Ubuntu server image in Azure.

**Comment by glennc** [comment]
Don't think I've seen this before. @ellismg have you?

**Comment by colemickens** [comment]
@davidfowl is right. `sudo apt-get update; sudo apt-get install libunwind8` resolved this issue for me.

**Comment by glennc** [comment]
Oh yeah, forgot about libunwind. I don't remember hitting that when I was testing out this stuff on clean Ubuntu though. I will have to add a note to the Linux instructions.

**Comment by ellismg** [comment]
Please also make sure to install libssl-dev, which you will need to compile stuff

**Comment by colemickens** [comment]
I created this VM this morning, just tried it again.
Azure > New > Compute > "Ubuntu Server 14.04 LTS"

Just now, on this "clean" ubuntu install:

```
colemickens@cm-vnext-test:~$ dnvm update-self
Downloading dnvm.sh from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.sh 
######################################################################## 100.0%

colemickens@cm-vnext-test:~$ dnvm install latest -r coreclr -u
Determining latest version
Latest version is 1.0.0-beta5-11657 
Downloading dnx-coreclr-linux-x64.1.0.0-beta5-11657 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-linux-x64/1.0.0-beta5-11657
######################################################################## 100.0%
Installing to /home/colemickens/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-11657
Adding /home/colemickens/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-11657/bin to process PATH

colemickens@cm-vnext-test:~$ dnx
failed to locate libcoreclr with error libcoreclrpal.so: cannot open shared object file: No such file or directory

colemickens@cm-vnext-test:~$ uname -a
Linux cm-vnext-test 3.16.0-36-generic #48~14.04.1-Ubuntu SMP Wed Apr 15 13:11:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
colemickens@cm-vnext-test:~$ hostname
cm-vnext-test
```

**Comment by ellismg** [comment]
This clean image includes libunwind8 and libssl-dev?

**Comment by glennc** [comment]
Apparently :). Actually. You know what. It is probably  I had built something else and pulled them down, like building kestrel and possibly Mono when I was doing the test. I don't think I actually created a new VM just to test coreclr.

**Comment by davidfowl** [comment]
We need to beef up our instructions

**Comment by glennc** [comment]
I don't disagree. But I also don't think it will significantly cut-down people having problems. People don't generally read the manual very well before trying things. A better way of installing that either checks and gives you better errors for missing dependencies, or prompts to install them for you, would be better.

**Comment by davidfowl** [comment]
can we check for those components?

**Comment by glennc** [comment]
`apt-cache policy libssl-dev`
will tell you if a package is installed. 
`whereis libuv.so.1`
will tell me if libuv is available. But IIRC there are some problems with whereis in certain circumstances.

So basically, yes we should be able to but some research into the best ways would be required.

**Comment by colemickens** [comment]
dpkg can help here too.

**Comment by glennc** [comment]
@colemickens Yeah :).
