### ISSUE TITLE
Need the OS flavor

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1745]
We need to know the flavor of the OS from `IRuntimeEnvironment` for test runs. 
Example of flavors: "Nano Server" or "Ubuntu".

**Comment by davidfowl** [comment]
What is OS flavor and how can you figure it out?

**Comment by victorhurdugaci** [comment]
Not sure if "flavor" is the right terminology. It is basically the type of OS in the same family. For example, the "Home" or "Professional" part in Windows 7 Home/Windows 7 Professional. It is not something that you can extract from the OS name or version.

On Windows you figure it out with [GetProductInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724358(v=vs.85).aspx) and on Linux/Darwin using [uname](http://www.gnu.org/software/libc/manual/html_mono/libc.html#Host-Identification).

Stay tuned for a PR

**Comment by anurse** [comment]
Is it not possible to detect what we need from Nano Server via feature detection? If not, then fair enough, this makes some sense to have, but I'm extremely wary of trying to do SKU detection :).

**Comment by victorhurdugaci** [comment]
We're not going to do this. Too many SKUs to make a generic solution. We'll implement code to do the SKU check only where we need it.
