### ISSUE TITLE
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1'

### ISSUE THREAD

**Issue by sgentile** [aspnet/dnx#1750]
Receiving following errors :
```
dnx . kestrel
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0-beta3
   EntityFramework.InMemory 7.0.0-beta3
   EntityFramework.SqlServer 7.0.0-beta3
   Kestrel 1.0.0-beta3
   Microsoft.AspNet.Diagnostics 1.0.0-beta3
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta3
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta3
   Microsoft.AspNet.Mvc 6.0.0-beta3
   Microsoft.AspNet.Security.Cookies 1.0.0-beta3
   Microsoft.AspNet.Server.IIS 1.0.0-beta3
   Microsoft.AspNet.Server.WebListener 1.0.0-beta3
   Microsoft.AspNet.StaticFiles 1.0.0-beta3
   Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta3
   Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta3
   Microsoft.Framework.Logging 1.0.0-beta3
   Microsoft.Framework.Logging.Console 1.0.0-beta3
   Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta3

Searched Locations:
  /Users/stevegentile/Documents/Workspace/net/{name}/project.json
  /Users/stevegentile/.dnx/packages/{name}/{version}/{name}.nuspec
  /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/{name}.dll
  /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

I ran dnu restore prior

```
dnx --version
1.0.0-beta4-11566
```

```
.NET Version Manager - Version 1.0.0-beta5-10372
```

```
dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
```

**Comment by davidfowl** [comment]
Change your frameworks to dnx451 and dnxcore50 instead of aspnet50 and aspnetcore50.  See http://blogs.msdn.com/b/webdev/archive/2015/04/29/new-asp-net-features-and-fixes-in-visual-studio-2015-rc.aspx for the changes made in the latest release.

**Comment by sgentile** [comment]
David: How do I go about doing that ?   I'm not using Visual Studio 2015, I'm on a Mac - I followed the instructions on asp.net 5 for OSX

**Comment by sgentile** [comment]
ok, I see now, my project.json has this

```
 "frameworks": {
        "aspnet50": {},
        "aspnetcore50": {}
    },
```

so I need to make it

```
 "frameworks": {
        "aspnet50": {},
        "aspnetcore50": {}
    },
```
this was from a yeoman generator, it must be out of data already.

so then I ran dnu restore again, and then 

dnx . kestrel

and I get this:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Framework.ConfigurationModel.IConfiguration'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) [0x00000] in <filename unknown>:0 
  at System.AppDomain.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)
  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Loader.LoadContext.Load (System.String name) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly (System.Object sender, System.ResolveEventArgs args) [0x00000] in <filename unknown>:0 
  at System.AppDomain.DoAssemblyResolve (System.String name, System.Reflection.Assembly requestingAssembly, Boolean refonly) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Shutting down finalizer thread timed out.
```

**Comment by npehrsson** [comment]
I am getting the exact same error on Azure, it works fine locally but in azure I get this error.
Only one thing is the difference and it is not searching for the packages in the packages directory, and I cannot set it to do so either. Any clues?

**Comment by SPEmoorthy** [comment]
I  am also getting the same error.


D:\Easwar_DotNetWorkspace\GSalesWeb\GSalesWeb>dnx . web
System.InvalidOperationException: Failed to resolve the following dependencies f
or target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0
   EntityFramework.SqlServer 7.0.0
   Microsoft.AspNet.Authentication.Cookies 1.0.0
   Microsoft.AspNet.Authentication.Facebook 1.0.0
   Microsoft.AspNet.Authentication.Google 1.0.0
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0
   Microsoft.AspNet.Authentication.Twitter 1.0.0
   Microsoft.AspNet.Diagnostics 1.0.0
   Microsoft.AspNet.Diagnostics.Entity 7.0.0
   Microsoft.AspNet.Identity.EntityFramework 3.0.0
   Microsoft.AspNet.Mvc 6.0.0
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0
   Microsoft.AspNet.Server.IIS 1.0.0
   Microsoft.AspNet.Server.WebListener 1.0.0
   Microsoft.AspNet.StaticFiles 1.0.0
   Microsoft.AspNet.Tooling.Razor 1.0.0
   Microsoft.Framework.CodeGenerators.Mvc 1.0.0
   Microsoft.Framework.ConfigurationModel.Json 1.0.0
   Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0
   Microsoft.Framework.Logging 1.0.0
   Microsoft.Framework.Logging.Console 1.0.0
   Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0

Searched Locations:
  D:\Easwar_DotNetWorkspace\GSalesWeb\{name}\project.json
  D:\Easwar_DotNetWorkspace\GSalesWeb\GSalesWeb\src\{name}\project.json
  D:\Easwar_DotNetWorkspace\GSalesWeb\GSalesWeb\test\{name}\project.json
  C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1
\{name}.dll
  C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1
\Facades\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

D:\Easwar_DotNetWorkspace\GSalesWeb\GSalesWeb>

**Comment by davidfowl** [comment]
And you read the resolution right?

**Comment by npehrsson** [comment]
We realised the the way we deployed to azure before just referencing the console app that would be a web job does not work anymore. We need to publish them separatly.
It makes it much more complex to publish a web site with a job to azure but that is how it is.

**Comment by urigolani** [comment]
Having the same issue only when wrapping a csproj: Getting the same error for System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1'  
(full error below)


##Setup:  
1. VS 2015 RC, freshly installed.
2. new solution with ASP vnext project under src and another classLibrary(old fashion)
3. asp references classLibrary (project json files for both, below)
4. a. publish to local folder succeeds but getting the above exception on run on web.cmd
4. b. if adding a nuget dependecy to classLibrary, which is reflected in the wrap project.json under the dependencies key, the publish itself from VS doesn't succeed due to an error of not being able to publish 

###Notes: 
1. Upon successful publish (for 4.a) the classLibrary.dll along with nuget wrapper for v.1.0.0 is positioned correctly under approot/packages 

##project.json 's:
###asp project.json:
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-WebApplication4-8f619bc3-7e8b-4860-a684-c2d229502b5a",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta4",
    "EntityFramework.Commands": "7.0.0-beta4",
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
    "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
    "Microsoft.Framework.Logging": "1.0.0-beta4",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta4",
    "Newtonsoft.Json": "6.0.8",
    "Microsoft.Azure.DocumentDB": "1.1.0"

  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
    "gen": "Microsoft.Framework.CodeGeneration",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "ClassLibrary2": "1.0.0-*"

      }
    },
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }
}

###classLibrary wrap project.json:
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "wrappedProject": "../../ClassLibrary2/ClassLibrary2.csproj",
      "bin": {
        "assembly": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.dll",
        "pdb": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.pdb"
      }
    },
    "net45": {
      "wrappedProject": "../../ClassLibrary2/ClassLibrary2.csproj",
      "bin": {
        "assembly": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.dll",
        "pdb": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.pdb"
      }
    }
  }
}

###Full error
I've marked the nuspec line in bold because that is what should be used to find the dlls.
.nuspec can be found below

C:\Microsoft\mAppStore>web.cmd
System.InvalidOperationException: Failed to resolve the following dependencies f
or target framework 'DNX,Version=v4.5.1':
   ClassLibrary1 1.0.0

Searched Locations:
  C:\Microsoft\mAppStore\approot\src\{name}\project.json
  C:\Microsoft\mAppStore\approot\test\{name}\project.json
  C:\Microsoft\mAppStore\approot\wrap\{name}\project.json
 * C:\Microsoft\mAppStore\approot\packages\{name}\{version}\{name}.nuspec*
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\
v4.5.1\{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\
v4.5.1\Facades\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

C:\Microsoft\mAppStore>

###ClassLibrary.nuspec  (after publish, from approot/packages/.../)
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ClassLibrary1</id>
    <version>1.0.0</version>
    <authors>ClassLibrary1</authors>
    <owners>ClassLibrary1</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>ClassLibrary1</description>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
  </metadata>
</package>

**Comment by jj09** [comment]
I have the same error like https://github.com/SPEmoorthy.
Tried `dnu restore` and upgrading dnx, but it didn't help.

Everything works with Visual Studio, but I wanted to try VSCode+console.

**Comment by lcostea** [comment]
If you run from Visual Studio with IISExpress there are no binaries created in the bin/dnx451 folder.
And the same happened when I Build/Rebuild from Visual Studio.
But then I ran dnu rebuild where the project.json is located and the binaries are created.
And at that moment I was able to run dnx . web and the server started.

**Comment by sgentile** [comment]
sorry, should have specified further - this is on OSX
