### ISSUE TITLE
Failed to initalize runtime (80070002)

### ISSUE THREAD

**Issue by fals** [aspnet/dnx#1753]
When I try to restore using any sample from https://github.com/aspnet/Home using Windows:

Command:

```
dnx restore
```

Output: 

**Failed to initalize runtime (80070002)**

The Upgrade:

**Determining latest version
'dnx-clr-win-x86.1.0.0-beta4' is already installed.
Adding C:\Users\FilipeAugusto\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin to process PATH
Adding C:\Users\FilipeAugusto\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta4'**

**Comment by moozzyk** [comment]
I believe it should be `dnu restore` and not `**dnx** restore`

**Comment by fals** [comment]
I got as output when ```dnu restor```:

***ObjectNotFound: (dnu:String) [], CommandNotFoundException***

**Comment by muratg** [comment]
@fals Can you paste the output of `dnvm list`?

**Comment by fals** [comment]
Active Version     Runtime Architecture Location                             Alias
------ -------     ------- ------------ --------                             -----
  *    1.0.0-beta4 clr     x86          C:\Users\FilipeAugusto\.dnx\runtimes default

**Comment by muratg** [comment]
The exception you shared seems like a PowerShell exception which is weird. 

Can you try `%userprofile%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin\dnu.cmd restore`

**Comment by fals** [comment]
There's no dnu.cmd at directory.

**Comment by muratg** [comment]
What's the output of `where dnu`?

**Comment by ChengTian** [comment]
@fals , looks like your have an incomplete runtime installed for some reasons. Please delete `%userprofile%\.dnx\runtimes` folder and run `dnvm upgrade` again.

**Comment by ChengTian** [comment]
For the `Failed to initalize runtime (80070002)` error, you should install `Microsoft .NET Framework 4.5.2`  before using CLR version of `dnx`

**Comment by davidfowl** [comment]
I thought @troydai made the error message less sucky.

**Comment by ChengTian** [comment]
@fals , did installation of .NET Framework fix this issue for you?

**Comment by fals** [comment]
@ChengTian I deleted the folder and did the full reinstall for the dnvm. I already have the most recent version of the .NET Framework, given that this machine has the Visual Studio 2013 Update 4 and the last version of Visual Studio 2015 RC.

1. ConsoleApp demo working
2. HelloWeb demo working
3. HelloMV not working yet due:
  *System.TypeLoadException: Método get_BasePath no tipo Microsoft.Framework.ConfigurationModel.Configuration do assembly M
icrosoft.Framework.ConfigurationModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null nao tem uma implementaçao.*

**Comment by troydai** [comment]
@fals You latest description of the issue seems to be different from the original one. Hopefully I read the Portuguese right that it indicates the `BasePath` property is not found. The property is added lately https://github.com/aspnet/Configuration/commit/7efb7b232fb1c20c4aaad2764cbf98d457429231. Could it be your application is out of date? It's not in the beta4 release.

**Comment by muratg** [comment]
@fals Let us know if you're still hitting this issue with beta7/beta8 bits.
