### ISSUE TITLE
VS Package restore includes too many projects

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#1757]
From @rynowak in defunct 'dnu' repo:

Package restore in VS will restore packages for all projects that exist in the repo (includes projects not in the solution, and projects which are unloaded).

You can test this by opening Mvc.NoFun.sln from the MVC repo. You'll see a bunch of restore message in the log like:

Writing lock file C:\k\Mvc\test\WebSites\ViewComponentWebSite\project.lock.json
This project isn't part of the solution, and it's not a dependency of anything that's included.

**Comment by davidfowl** [comment]
This is actually a VS bug.

**Comment by Eilon** [comment]
Eh, it was moved from Tooling to dnu, now to dnx... should we re-open the Tooling one?

**Comment by Eilon** [comment]
BTW you're the one who said it was a dnu bug to begin with :smile:

**Comment by rynowak** [comment]
Regardless of whose bug this is exactly this qualifies as a top-pain point for working with the MVC solution. It effectively doubles the package restore time of our solution.

**Comment by muratg** [comment]
@davidfowl DNU or Tooling? :)

**Comment by ChengTian** [comment]
This can be partially fixed in DNU: https://github.com/aspnet/dnx/issues/1862
However, DNU doesn't have knowledge of unloaded projects. So it is still a Tooling bug and VS should do restore for each individual loaded project.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/1494

**Comment by muratg** [comment]
Closing this one as #1494 tracks the work needed.
