### ISSUE TITLE
Make RuntimeEnvironment lazy

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1758]
Because performance:

![image](https://cloud.githubusercontent.com/assets/95136/7427617/4f966cca-ef94-11e4-8974-dd46e58f676e.png)

**Comment by victorhurdugaci** [comment]
Can you dig a little deeper in the call stack? Is it the call to `uname` that's slow?

**Comment by davidfowl** [comment]
Yes

**Comment by davidfowl** [comment]
Yes

**Comment by davidfowl** [comment]
![image](https://cloud.githubusercontent.com/assets/95136/7428578/d7d1ea7a-efa7-11e4-83a3-9a65c29484c3.png)
