### ISSUE TITLE
Output window should de-dupe errors coming from multiple frameworks

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#1760]
1. Have a simple ClassLibraryA with an error
![image](https://cloud.githubusercontent.com/assets/8246794/7431313/6bd41250-efd2-11e4-8c49-162878a93dfe.png)

2. Build ClassLibraryA

ACTUAL
Output window shows 2 errors

![image](https://cloud.githubusercontent.com/assets/8246794/7431334/9cb645aa-efd2-11e4-993f-7c8b20e62749.png)

EXPECTED
Output window shows only 1 error

**Comment by davidfowl** [comment]
This is actually nothing to do with the runtime. This is a tooling issue
