### ISSUE TITLE
CompileModule Diagnostics not showing completely in "Error List"

### ISSUE THREAD

**Issue by dtkujawski** [aspnet/dnx#1769]
In a CompilerModule, I can diagnostics error message that VS will add to the "Error List window".  However, even when I specify an id, the "Error List window" never shows anything in the "Code" column except blank.

```C#
DiagnosticDescriptor descriptor = new DiagnosticDescriptor("XX1000", "TITLE", "Sample Message", "DESCRIPTION", DiagnosticSeverity.Error, true);
Location location = Location.Create(@"c:\test.txt", 
                                    new Microsoft.CodeAnalysis.Text.TextSpan(0, 0), 
                                    new Microsoft.CodeAnalysis.Text.LinePositionSpan(new Microsoft.CodeAnalysis.Text.LinePosition(0, 0), 
                                                                                     new Microsoft.CodeAnalysis.Text.LinePosition(0, 0)));
context.Diagnostics.Add(Diagnostic.Create(descriptor, location));
```

ADDITIONALLY: If I specify a severity of "DiagnosticSeverity.Info" the message will never appear in the "Error List window".  It only populates in the "Error List" when the severity is ERROR or WARNING.

**Comment by muratg** [comment]
@troydai any guidance?

**Comment by troydai** [comment]
I'll take a look.

**Comment by troydai** [comment]
Hi @dtkujawski, sorry for the latest reply. I tried your scenario on latest code. I can't repo your issue. Would you let me know the DNX you tested and can you try your scenario on latest DNX. 

Here's my result:
![image](https://cloud.githubusercontent.com/assets/1329240/8317585/8d7a7150-19b3-11e5-852d-983a3a43e307.png)

**Comment by troydai** [comment]
Hi @dtkujawski,

I'm closing this bug since I can't repo this on the latest DNX. Please give the newer build a try. If you can still observe the problem, please feel free to reopen this issue.

Regards,
Troy
