### ISSUE TITLE
CompilerModule : any way to output custom message to the "Output window"

### ISSUE THREAD

**Issue by dtkujawski** [aspnet/dnx#1770]
During execution of a custom CompilerModule, I've tried using "Debug.WriteLine" and "Trace.WriteLine" but neither seem to send custom messages to the "Output window".  Is there anyway to send custom messages (diagnostics and whatnot) to that window in Visual Studio?

**Comment by muratg** [comment]
@troydai Does something like this exist currently?

**Comment by pranavkm** [comment]
It's not the same thing but any `DiagnosticMessages` added to the compile context should show up in VS.

**Comment by troydai** [comment]
@pranavkm is correct.
