### ISSUE TITLE
Gitter Room

### ISSUE THREAD

**Issue by dbettin** [aspnet/dnx#1772]
Please create a Gitter room for DNX.  This is consistent w/ CoreCLR, CoreFX, and Roslyn.

**Comment by davidfowl** [comment]
We jabbr over here

**Comment by dbettin** [comment]
Great discussion.. Great way to build a community.

**Comment by davidfowl** [comment]
OK ok

**Comment by davidfowl** [comment]
I'll make one.

**Comment by Romoku** [comment]
Maybe there is a way to have both?

**Comment by goblinfactory** [comment]
+1 for gitter

**Comment by davidfowl** [comment]
Closing this out.

**Comment by davidfowl** [comment]
+1 for gitter as well.
