### ISSUE TITLE
Affect on profiler API?

### ISSUE THREAD

**Issue by sawilde** [aspnet/dnx#1774]
I have the following issue raised against OpenCover - [Lines showing as not covered](https://github.com/OpenCover/opencover/issues/285) - OpenCover is an open-source code coverage tool for .NET (similar to PartCover).

What I am seeing is that the IL begin sent to the profiler is different to that on the disk. e.g. for release assemblies (I am not sure why only release assemblies are affected)

    IL_0007: bge.s IL_0019

is being changed to

    IL_0008 clt
    IL_000A stloc.1
    IL_000B ldloc.1
    IL_000C brfalse.s IL_001E

This is functionally the same but seems to be wanting to store (intermediate) values (or perhaps it is some sort of optimisation)

Is the sort of thing the new JIT stuff (I have recently read about) would do for optimisations in release builds vs debug builds before the IL is sent to the runtime for actual compilation? If so are the sequence oints preserved for debugging purposes?

**Comment by muratg** [comment]
Seems like a Roslyn issue.  Do you get this only with DNX based projects?

**Comment by muratg** [comment]
Ah, I see you filed a Roslyn bug as well: https://github.com/dotnet/roslyn/issues/2477

**Comment by sawilde** [comment]
> Seems like a Roslyn issue. Do you get this only with DNX based projects?

From my current sample of 1 - yes. It's not actually my code but a user of OpenCover

> Ah, I see you filed a Roslyn bug as well: dotnet/roslyn#2477

@muratg - I did as I don't know the cause

**Comment by muratg** [comment]
@sawilde Looks like Roslyn folks require some more info from your side to proceed. I'm closing the bug on the DNX side since it does look like a Roslyn problem. If it turns out DNX needs investigation as well, please feel free to file a bug here. Thanks.

**Comment by sawilde** [comment]
It seems that some people got it working by using the `--lib` option from dnx (https://github.com/OpenCover/opencover/issues/327)

e.g.

    OpenCover.Console.exe 
      -target:C:\users\jbruun.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\dnx.exe 
      -targetargs:"--lib c:\projects\cpip\src\website\bin\debug\dnx451 c:\projects\cpip\test\Website.Tests test" 
      -output:coverage.xml 
      -filter:+[Website]*

**Comment by davidfowl** [comment]
Ohhhh hacky. We might be able to run in a compatibility mode that drops the dll and pdb on disk. This would be for existing tools to consume

**Comment by sawilde** [comment]
@davidfowl perhaps you could expand - I haven't really had the time recently to get up to date with dnx et al (I work with fat clients mainly) - why would this be consider hacky?

**Comment by davidfowl** [comment]
It circumvents dependency resolution

**Comment by sawilde** [comment]
Okay - so is there another way this can be done currently or would something else have to be done - have other profiler tools experienced the same/similar issues?

**Comment by davidfowl** [comment]
Do you know what the requirements are? Is it the pdb files and dlls Beinf on disk?

**Comment by sawilde** [comment]
what we found was that the dll being loaded had been modified from the original dll supplied and no longer aligned with the PDB as such the instrumentation that was using the PDB to align IL with source code no longer worked.
