### ISSUE TITLE
RazorPreCompilation.cs error on dnx core 5.0 

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#1777]
From https://github.com/aspnet/Home/issues/533 by @dopare
Created started web application for beta4. Removed dnx451 from frameworks and got compilation error.

` RazorPreCompilation.cs(5,17,5,23): DNX Core 5.0 error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) `

**Comment by troydai** [comment]
It only reproduces on _beta4_.

**Comment by troydai** [comment]
On another look. This issue actually repos on __beta5__. The difference is we swallow the build exception. I'm investigating the source.

**Comment by troydai** [comment]
The root cause of this issue is because the created load context for preprocess module contains a library manager of runtime target framework instead of application target framework. https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Roslyn/RoslynCompiler.cs#L234

**Comment by davidfowl** [comment]
@troydai this bug is fixed right?

**Comment by troydai** [comment]
Fixed!
