### ISSUE TITLE
Potentially incompatible version of a package installed when using specific version of the package

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1797]
Referencing a specific beta version may in project json may result in installing beta+1 version of the package.

Repro steps:

Drop this file to a folder:
```
{
    "dependencies": {
        "EntityFramework": "7.0.0-beta4-12943"
    },
    "dnx451": { },
    "dnxcore50": {
        "dependencies": {
        }
    }
}
```
Using a matching dnx version 

`  *    1.0.0-beta4       clr     x86          C:\Users\pawelka\.dnx\runtimes`

run `dnu restore`
run `dnu list`

You see:
`*EntityFramework 7.0.0-beta5-12754`
so beta5 was installed even though I am on a "beta4 train"

Expected:
a correct beta4 version of the package is installed or an error if a greater or equal beta4 version of the package does not exist. Installing beta5 may cause hard to resolve issues (dll hell x 2) if there are breaking changes between beta4 and beta5. Also note that using `...beta4-*` will install the `...beta4` version.

**Comment by davidfowl** [comment]
This behavior is by design. Versions specified are a minimum and it looks like your feeds are broken?

**Comment by moozzyk** [comment]
@davidfowl - in what sense are my feeds broken?

**Comment by davidfowl** [comment]
Specifying a version that doesn't exist in any of your feeds means you will get the lowest version greater than the specified version.

`1.0.0-beta4` is smaller than `1.0.0-beta4-somebuildnumber`

**Comment by moozzyk** [comment]
Thanks. Will look into it. The specific version I have was returned by VS Code Intellisense...
