### ISSUE TITLE
Pkg rename: Build only packages should have .Sources in the package name

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1800]
- Microsoft.Framework.Runtime.Common:  Common -> Sources
- Microsoft.Framework.Runtime.Compilation:  Common -> Sources
- Microsoft.Framework.CommanlineUtils:  Append Sources

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/dnx/commit/3d20719b0a985b6960a3f87d9f5f9b6c3f71b7bc
