### ISSUE TITLE
Visual Studio 2015 RC and dnx 1.0.0-beta4 : ProduceOutputsOnBuild does not create artifacts

### ISSUE THREAD

**Issue by StefH** [aspnet/dnx#1801]
*I'm not sure if this is the right place to post this issue.*

**Issue**
When building a dnx 1.0.0-beta4 dll, the ProduceOutputsOnBuild  is not saved/updated in the VS2015 UI and it seems that this setting is not used/not working because no artifacts are created after the build.

![2015-05-06_21h11_07](https://cloud.githubusercontent.com/assets/249938/7501514/be67c794-f434-11e4-98c0-3bda4e49b6cf.png)

Note that the xproj file looks fine:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
</PropertyGroup>
```

Is this bug, or I'm missing something?

**Comment by davidfowl** [comment]
Can you file this issue on aspnet/Tooling?
