### ISSUE TITLE
DNU does not stamp TFM into assembly

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/dnx#1802]
I'm using beta4 of `dnx`, and found that when I run `dnu pack` the resulting assemblies do not have the TFM stamped into the assemblies.  I have a library that targets `dnx45`, `dnxcore50`, and `net45` and none of them get the stamp.

**Comment by davidfowl** [comment]
The stamp really only mater for non dnx targets but we should do this

**Comment by davidfowl** [comment]
See https://github.com/dotnet/cli/issues/398
