### ISSUE TITLE
Package name: Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1805]

**Comment by muratg** [comment]
@davidfowl `Microsoft.Framework.Runtime.Compiler.*`?

**Comment by Eilon** [comment]
`.Extensions` :smile:

**Comment by muratg** [comment]
How about the "Roslyn" name? This bug was tracking that in particular as Roslyn team itself is not using this name in any of their packages.

**Comment by muratg** [comment]
Dup|: https://github.com/aspnet/dnx/issues/2871
