### ISSUE TITLE
Allow dnx to be interrupted with ctrl+c

### ISSUE THREAD

**Issue by vestimir** [aspnet/dnx#1809]
For example whenever you run `dnx . kestrel` the only way to stop the server is <kbd>CTRL</kbd>+<kbd>Z</kbd>, but most of the people on OSX/Ubuntu are used to stop console apps (and especially servers like nodejs, or ruby ones) with <kbd>CTRL</kbd>+<kbd>C</kbd>. I think that it'll be good to have this option, to avoid confusion.

**Comment by davidfowl** [comment]
File this bug on aspnet/Hosting (btw there's already a bug on it) and a pull request https://github.com/aspnet/Hosting/pull/255

**Comment by vestimir** [comment]
Thanks!
