### ISSUE TITLE
DNU doesn't get correct local app data folder on *nix with CoreCLR

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1813]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/Restore/NuGet/HttpSource.cs#L193
(Search for `LocalAppData` in the file if it is updated)

To make it cross-plat, we can use similar approach as here: https://github.com/NuGet/Home/issues/472

@BrennanConroy

**Comment by ChengTian** [comment]
Talked to @davidfowl and @BrennanConroy . This cross-plat-related issue should be moved to next milestone.

**Comment by muratg** [comment]
Let's do this in Beta 6. 

cc @BrennanConroy

**Comment by BrennanConroy** [comment]
I believe this is waiting on #1692 which we will hopefully get in soon.

**Comment by ChengTian** [comment]
Yeah, I have a branch for this: https://github.com/aspnet/dnx/tree/wei/correct-local-appdata
and the final PR needs something from https://github.com/aspnet/dnx/pull/1692
