### ISSUE TITLE
DNX can't handle PCL profiles on a machine without targeting pack

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#1814]
https://github.com/aspnet/dnx/blob/master/src/Microsoft.Framework.Runtime/NuGet/NETPortable/NetPortableProfileTable.cs hardcodes the location of the PCL profile data.  It should probably first check an override environment variable.  I believe nuget used NuGetPortableReferenceAssemblyPath.  If that is not set then it can fallback to machine wide.  If machine wide is not there, maybe it should fall back to a static representation.

**Comment by muratg** [comment]
@davidfowl

**Comment by davidfowl** [comment]
The CLI code uses nuget now
