### ISSUE TITLE
Published site using no-source does not run

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#1815]
When I publish using no-source, the DNX says that a package (a build dep) could not be found. However this package is 100% reachable via the packages profile in the published image. 

```
dylan@ubuntu-server:/var/www/Code/dylannet/vnext/mypim/bin/output$ ./web
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   dylan.NET.K 

Searched Locations:
  /var/www/Code/dylannet/vnext/mypim/bin/output/approot/packages/mypim/2.0.0/{name}/project.json
  /var/www/Code/dylannet/vnext/mypim/bin/output/approot/packages/{name}/{version}/{name}.nuspec
  /usr/local/lib/mono/4.5/{name}.dll
  /usr/local/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) <0xb62fe3e0 + 0x00357> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xb420aca0 + 0x00035> in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) <0xb62fc110 + 0x00163> in <filename unknown>:0 
  at dnx.host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args) <0xb62f87f8 + 0x0039b> in <filename unknown>:0 
dylan@ubuntu-server:/var/www/Code/dylannet/vnext/mypim/bin/output$ 

```

**Comment by ChengTian** [comment]
Hi @borgdylan , thank you for reporting this issue. Could you please share the version of dnx used here?

**Comment by ChengTian** [comment]
BTW, I assume this is on Mono, please correct me if I am wrong.

**Comment by borgdylan** [comment]
Yes I am on mono. I am using dnx-mono v. 1.0.0-beta5-11735

**Comment by borgdylan** [comment]
The issues persists as of ```1.0.0-beta6-11921```

**Comment by borgdylan** [comment]
I do not know what the major differences are v.s publishing to source (apart from the source vs binary), but publishing to source is always working with publish to binary only failing.

**Comment by davidfowl** [comment]
Whats your active runtime? You might be running into an issue where you're not packing the runtime and it's just using whatever happens to be on the command line to run (which may be different from what you used to pack)

**Comment by borgdylan** [comment]
The runtime is the same thing i.e. mono with DNX ```1.0.0-beta6-11921```

**Comment by borgdylan** [comment]
How can I pack the dnx runtime with my app?

**Comment by borgdylan** [comment]
```dnu publish --no-source --runtime active``` ?

**Comment by borgdylan** [comment]
It still gives a 'splosion.
```
dylan@ubuntu-server:/var/www/Code/dylannet/vnext/mypim/bin/output$ ./web
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   dylan.NET.K 

Searched Locations:
  /var/www/Code/dylannet/vnext/mypim/bin/output/approot/packages/mypim/2.0.0/{name}/project.json
  /var/www/Code/dylannet/vnext/mypim/bin/output/approot/packages/{name}/{version}/{name}.nuspec
  /usr/local/lib/mono/4.5/{name}.dll
  /usr/local/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) <0xb623d6f8 + 0x00357> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xb41f1ca0 + 0x00035> in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) <0xb623b428 + 0x00163> in <filename unknown>:0 
  at dnx.host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env) <0xb6237d08 + 0x0035f> in <filename unknown>:0
```

**Comment by davidfowl** [comment]
I just tried this with `https://github.com/aspnet/Home/tree/dev/samples/latest/HelloWeb` and it seemed to work fine. Might be something else going on here. @borgdylan Can you try that as well.

**Comment by borgdylan** [comment]
That works fine. However it does not use a language loaded from packages that do not ship with DNX.

**Comment by borgdylan** [comment]
The language package is precisely what is not loading and it is no longer needed once we publish to binaries. However without that dependency one cannot even compile the binaries in the first place.

**Comment by davidfowl** [comment]
@borgdylan The point of getting you to run that is to narrow the issue down. Nobody tests dylan.NET besides you so we appreciate the bugs, but trying to help us narrow things down would be great next time as we can't reproduce the issue in normal scenarios.

**Comment by borgdylan** [comment]
It is why I keep testing everyday to see that no new regressions happen.

**Comment by davidfowl** [comment]
@borgdylan The bug title is missing specifics. Whenever you see something broken with dylan.NET, test it with C# to see if it's general or specific to language things. Also, provide a sample that is ready to go with your scenario so that we can reproduce it. This might not have anything to do with publish.

**Comment by borgdylan** [comment]
I may have fixed it. I had ```"dylan.NET.K": {"type": "build", "version": ""}``` in the dependencies section. When I changed it to ```"dylan.NET.K": {"type": "build", "version": "1.3.4.0"}``` it suddenly worked. So what is the version in the published output gets rewritten to the version of the published dependency package?

**Comment by davidfowl** [comment]
is dylan.NET.K a package or a project? Can you please provide a repro?

**Comment by borgdylan** [comment]
It is loaded as a project in this case. If it gets loaded as a package one would obviously have to specify the version number avoiding the bug in the first place.

**Comment by borgdylan** [comment]
For a repro would the dylan.NET version of HelloWeb suffice?

**Comment by davidfowl** [comment]
Anything at this point.

**Comment by borgdylan** [comment]
I will include DNK as source to reproduce the scenario.

**Comment by borgdylan** [comment]
https://github.com/borgdylan/dylandotnet-aspnet5

**Comment by borgdylan** [comment]
The workaround is applied in the repo so you may need to empty thr version of dylan.NET.K to hit the bug.

**Comment by borgdylan** [comment]
This seems to be resolved for me. Stuff works ok.
