### ISSUE TITLE
project.json: commented lines break "compile" arrays

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnx#1816]
Moving from https://github.com/aspnet/Tooling/issues/47

From @mgravell

This is fine elsewhere, for example:

    "commands": {
        //"dummy": "nothing",
        "test": "xunit.runner.dnx"
    },

Which is then validly ignored:

    D:\Dev\protobuf-net\Protobuf.Tests>dnx . dummy
    System.InvalidOperationException: Unable to load application or execute command
    'dummy'. Available commands: test.

However! It breaks the IDE when used in `"compile:"`:

    "compile": [
        //"../Examples/Diction*.cs",
        "../Examples/Program.cs"
    ],

This causes 3 errors:

- Illegal characters in path.
- NuGet Package Restore failed for one or more packages. See details in the Output window.
- The design time host build failed with the following error: Illegal characters in path.

And the "References" node in the solution explorer breaks (yellow hazard sign)

Note: this also breaks `dnx` when used at the command line, for example:

    D:\Dev\protobuf-net\Protobuf.Tests>dnx . test
    System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Microsoft.Framework.Runtime.PatternsCollectionHelper.CreateCollection(Stri
    ng projectDirectory, String[] patternsStrings)

**Comment by muratg** [comment]
We will be removing comment support as part of JSON internalization work.

**Comment by sayedihashimi** [comment]
>We will be removing comment support as part of JSON internalization work

Sounds like something to add to announcements repo

**Comment by muratg** [comment]
Yup will do when the change is actually in.

**Comment by mgravell** [comment]
@muratg well, I expect there's nothing I can do to change your mind on that, but: that's a major disappointment. It was *really*, and I mean *really* nice to be able to comment in there. I've heard lots of positive things about this, and removing it is going to be unpopular. Not perhaps revolutions worthy, but enough to take the shine off something that was really sweet.

If you *can* reconsider, I urge you to.

**Comment by muratg** [comment]
@mgravell I understand the value, but based on an internal discussion, we have decided that it's not worth it to break the [spec](http://www.ietf.org/rfc/rfc4627.txt). 

Tools like __npm__, __bower__ etc already lack the support so there was already a bit of inconsistency between the JSON files within an ASP.NET 5 project. 

Also, we expect 3rd party tools to interact with `project.json` files in the future, and we can't guarantee all their parsers will have support for comments.

Please see why Douglas Crockford decided to remove them from JSON [here](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr).

**Comment by mgravell** [comment]
Yes, I understand the dilemma. Quite the bind. Oh well. I guess I'm just
going to have `"_note0": "blah blah blah"` scattered in.

**Comment by GuardRex** [comment]
@mgravell Can I confirm with you from your testing that ...
```
"_comment": "comment here",
```
will be fine anywhere in `project.json`? This is going to be something I would like to use (sparingly, of course) when I need to note something.

**Comment by JamesNK** [comment]
Not that it matters since the Json.NET dependency is being removed from the DNX but the reason you are getting this error is the comment token with that value is still in the array.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/30

**Comment by GuardRex** [comment]
```
"_comment": "comment here",
```
... not going to work. Chokes `dnu` if placed in `dependencies`.

No comments in project.json then? It wasn't discussed that even one comment element could be allowed in each section of `project.json`? E.g. ...
```
{
    "comment": "Top-level comment",
    "webroot": "wwwroot",
    "version": "1.0.0",
    "authors": [ "Luke Latham" ],
    "description": "Beer pong online",
    "copyright": "Copyright 2015 Liquored Devs, Inc.. All Rights Reserved.",
    "dependencies": {
        "comment": "Dependency section comment",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta5-*",
        "Microsoft.AspNet.Mvc": "6.0.0-beta5-*"
    },
    "commands": {
        "comment": "Commands section comment",
        "test": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001"
    },
    "frameworks": {
        "comment": "Frameworks section comment"
        "dnxcore50": { }
    }
}
```

**Comment by dsplaisted** [comment]
Is there a chance of revisiting the decision not to support comments, or opening it up for some community discussion?

A simple, human-readable and editable project file format is one of the big features of DNX.  It becomes a lot less readable if you can't add comments to explain what's going on, and a lot less editable if you can't quickly disable and re-enable portions of the project.json to figure out what works.

I don't think people want to use comments to add parsing directives to project.json, so Douglas Crockford's reasoning doesn't seem to apply here.  Indeed, if you want comments in your source, he suggests including them there but stripping them out before the json is processed.

**Comment by glen-84** [comment]
@dsplaisted,

> Microsoft should push for comments to be included in the JSON spec. The reasons for it not being included are weak.

And ...

> The moment a parser expands the feature set, the document can no longer be parsed by other parsers. It's not at all intuitive that you can comment in project.json but not in bower.json or package.json. This is why it should be part of the spec once again, and why I thought it would be interesting to see how the spec writers would respond to such a request from a large corporation.
    
See https://github.com/aspnet/Tooling/issues/13#issuecomment-98988817.

**Comment by muratg** [comment]
https://github.com/aspnet/Announcements/issues/24

**Comment by NeelBhatt** [comment]
I tried to combine few points from https://github.com/aspnet/Announcements/issues/24 here in blog : https://neelbhatt40.wordpress.com/2015/08/21/new-json-parser-in-vnext-no-comments-yet/ for people who are not on Github. Hope it helps!

**Comment by ashic** [comment]
It's probably way too late now, but any reason to focus on json instead of js? There's precedence for using a language to specify a project - sbt does this successfully. This allows for comments, variables, custom stuff and leads to a lot of optional flexibility. Specifying the config as project.js could result in something like:

```
project = {
   //existing content goes here
}
```

Thoughts?

**Comment by davidfowl** [comment]
Way too late plus we don't have a javascript engine that we'd want to readily embed in our runtime environment.
