### ISSUE TITLE
Should project.json be renamed?

### ISSUE THREAD

**Issue by nil4** [aspnet/dnx#1817]
The file name `project.json` is very generic, with no indication of the actual technology stack it applies to. It shares this generic-naming problem with NPM's `package.json` file, and it's also easy to confuse one with the other. In contrast, [`bower.json`](https://github.com/bower/bower.json-spec) has a specific name that immediately identifies the applicable tool and provides an obvious search-engine keyword to find relevant documentation.

Since the `project.json` file now applies to more than just ASP.NET 5, and is becoming the recommended way to describe .NET projects going forward, I would suggest renaming it to something more relevant, perhaps `dnx.json` or `dnxproject.json`. 

I realize this would be a breaking change that would affect many tools besides Visual Studio. Looking back at the fallout of the K rename, I think it's fair to say that this rename would be much harder (or even impossible) to pull off after the final VS 2015 release, so I thought I should ask for feedback sooner rather than later.

Originally posted at aspnet/Home#569, copied here since this is applicable to any DNX-based application.

**Comment by timmydo** [comment]
I think it would be nice to see this changed also. Might make it easier for things like kudu to distinguish between nodejs and asp.net apps.

**Comment by davidfowl** [comment]
I think that ship has sailed tbh. we're also going to be using project.json more generally for nuget as well.

**Comment by tlk** [comment]
+1 for dnx.json

This is an excellent opportunity for [bikeshedding](http://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality)!

**Comment by tlk** [comment]
It is interesting to observe the different naming strategies for TypeScript, Azure Webjobs and ASP.NET on http://schemastore.org/json/

#### TypeScript - uses project related naming scheme
* http://json.schemastore.org/tsdrc
* http://json.schemastore.org/tsconfig
* http://json.schemastore.org/tslint

#### Azure Webjobs - uses project related naming scheme
* http://json.schemastore.org/webjobs-list
* http://json.schemastore.org/webjob-publish-settings
* http://json.schemastore.org/settings.job (outlier)

#### ASP.NET - lives in its own world
* http://json.schemastore.org/config
* http://json.schemastore.org/global
* http://json.schemastore.org/launchsettings
* http://json.schemastore.org/project

Warning: [bikeshedding](http://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality) alert!

**Comment by glen-84** [comment]
I think that NPM made the assumption that if your project depends on NPM packages, the project itself was an NPM package (an [issue](https://github.com/npm/npm/issues/8222), FWIW). Obviously, this is not always true – ASP.NET 5 projects, for example, are dependant on NPM packages, but are not themselves NPM packages. The same is true for Bower and any other package managers.

So I guess the question is, are there scenarios where this project.json file would be included in a non-DNX project? Are you able to use NuGet (v3?) without a project.json file?

It might be too late now, but something like `dnx-solution.json, dnx-project.json, and nuget.json` might have made sense.

**Comment by glennc** [comment]
At this point I think we are too late to change this. There are already too many things that assume project.json is the name and changing them would cost far more then the value that I have seen talked about so far.
