### ISSUE TITLE
CommandLineUtils: Support subcommand help

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#1820]
Currently, if I type `dnx . ef help migration add`, I get, "Error: unrecognized argument 'add'."

`CommandLineApplication.ShowHelp` should be able to accept and process a chain of commands and sub-commands.

**Comment by victorhurdugaci** [comment]
Have you tried `dnx . ef migration help add` ?

**Comment by bricelam** [comment]
I'm explicitly not adding the help command to sub-commands. I've made `dnx . ef migration add --help` (in that exact order) work, but the overall usability of help is awkward compared to other command line tools.

**Comment by bricelam** [comment]
Bonus points: make `dnx . ef --help migration add` work.

**Comment by muratg** [comment]
Feel free to send a PR.  BTW, this is now a sources package. :)

**Comment by bricelam** [comment]
The help command (but not the help option) was removed in #2139. As far as I'm concerned, this issue can be closed.
