### ISSUE TITLE
CommandLineUtils: Support multi-parameter escape sequences in AnsiConsole

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#1821]
Instead of combining parameters like `\x1b[1;37m`, I'm forced to split them into two sequences: `\x1b[1m\x1b[37m`. We should support the semicolon-separated syntax.

**Comment by muratg** [comment]
Feel free to send a PR.  BTW, this is now a sources package. :)

**Comment by bricelam** [comment]
@anurse Do you know if these are generally supported? I know bash supports them...

**Comment by anurse** [comment]
I have no idea ;). I believe it is always parsed and converted to ConsoleColor (meaning it's weirdly round-tripped on *nix), but if you want to adjust `AnsiConsole` to pass the escape sequence through on *nix, I'd be happy to see that ;)

**Comment by bricelam** [comment]
@anurse Per @BrennanConroy's PR #1724, it *does* pass-through outside of Windows. :wink:

**Comment by BrennanConroy** [comment]
We'd need to update the parsing in Common Testutils too

**Comment by anurse** [comment]
Ooh, cool. I hadn't seen that PR. Yeah, we should update the Windows parsing then.

**Comment by bricelam** [comment]
Cool. I did a prototype a while ago at https://gist.github.com/bricelam/39d8cf65f3da684657c9 I also tried to fix some of the strange behavior around bolding.

**Comment by BrennanConroy** [comment]
That wont work Cross-Plat, you can do a get on the console color :(

**Comment by bricelam** [comment]
Hence *prototype* :wink:
