### ISSUE TITLE
CommandLineUtils: Support argument validation

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#1822]
It would be nice if declarative argument validation was built into the framework. Otherwise, consumers are left to implement it themselves imperatively.

We should at least do required validation, if nothing else.

**Comment by muratg** [comment]
@bricelam Any particular design in mind for specifying argument expectations?

cc: @victorhurdugaci

**Comment by bricelam** [comment]
My initial thought was something trivial like the following:

```C#
// Required arguemnt
command.Argument("[arg]", "An argument", required: true);

// Enum option
command.Option(
    "-o|--option <value>",
    "An option",
    CommandOptionType.SingleValue,
    validValues: new[] { "value1", "value2", "value3" });
```

**Comment by muratg** [comment]
@glennc Could this be part of "uber" command line tool unification work item?
