### ISSUE TITLE
dnu wrap generates wrap and global.json in wrong folder if project.json did not exist before

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#1824]
This was opened as tooling bug #1167116 first, but after investigation i saw that this happens after we call a wrap command passing class library csproj file and correct solution folder. Follow instructions below for repro:
Affected Build: VS 2015 RC
Steps to reproduce:
1. File\New Project\Visual C#\Windows\Class Library
2. Right click on solution, Add\New Project..., choose Visual C#\Web\Console Application (Package)
3. In solution explorer, right click on Console app, choose Add Reference..., check the box for the class library, and click OK
 
EXPECTED: No errors, and solution builds successfully
ACTUAL: The following errors.  They are displayed even without manually trying to build

Error
 
 NuGet Package Restore failed for one or more packages. See details in the Output window.
 ConsoleApp1
 C:\Users\daplaist\Documents\Visual Studio 2015\Projects\ClassLibrary4\ConsoleApp1\project.json
 0
 
Error
 
 Dependency ClassLibrary4 >= 1.0.0-* could not be resolved
 ConsoleApp1
 C:\Users\daplaist\Documents\Visual Studio 2015\Projects\ClassLibrary4\ConsoleApp1\project.json
 20
 

 
REASON: VS is creating a global.json and a wrap folder in the same folder as the class library.  Since this global.json isn't in any of the parent directories of the DNX project, it's not found when trying to resolve the reference to the sibling project
 
If the solution is initially created via a DNX project template, then it will have a global.json file in the solution folder, the wrap folder will be placed in the solution folder, and everything will work as expected.  When you add a DNX project to an existing solution, there is no global.json, and you run into this failure.

**Comment by GuardRex** [comment]
Don't know if this is exactly related but it looks suspiciously similar: `dnu publish` when compiler-generated `project.json` and `project.lock.json` files get dependencies on the project itself: https://github.com/aspnet/Home/issues/494

**Comment by muratg** [comment]
@ChengTian can you have a look?

**Comment by ChengTian** [comment]
Dup of https://github.com/aspnet/dnx/issues/1654 and the fix is already checked in: https://github.com/aspnet/dnx/pull/1738

Please use the latest version of runtime.
