### ISSUE TITLE
Tests that check stdOut will fail on Cross-Plat if the text contains color

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#1826]
With the new way we get process output from: https://github.com/aspnet/dnx/commit/be5bb7b77550bc2297b1827687206341c3fb0ec2?diff=split#diff-c889083e2a55b6b0e4ad6cc6e256f8c4L67
If we are on non-Windows the text will contain the ANSI color codes and fail any test that checks the text from a command

@davidfowl

**Comment by muratg** [comment]
@BrennanConroy Can we strip the codes like we do elsewhere before the checks?

**Comment by BrennanConroy** [comment]
We could do something similar to AnsiConsole if we are ok with doing that.

**Comment by BrennanConroy** [comment]
Should be fixed by #1860

**Comment by BrennanConroy** [comment]
3ca17d571801e3db18cde4d017485bc2851a13cd

**Comment by muratg** [comment]
:+1:
