### ISSUE TITLE
Unable to create agregation solution

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/dnx#1830]
I have some solutions in folders `core/core.sln` `db/db.sln` ...
I create `full.sln` in parent folder with next `global.js`:

    {
        "projects": [
            "core/src",
            "db/src"
        ],
        "sdk": {
            "version": "1.0.0-beta5-11672"
        }
    }

And noone project is added in `full.sln`. Why? 
So, if vs2015 do not do it automatically, is it safe to add projects manually?

I need it to synchronous reference updates.
But for develop i use small solutions - fast rebuild, less memory usage and small solutions are hosted in different source repositories.

**Comment by muratg** [comment]
.sln files are VS artifacts.  Modifying `global.json` file does not modify .sln files. It's OK to add your projects to the .sln is fine.

**Comment by ggrnd0** [comment]
Oh=)
It worked good with adding `Autofac`, but did not with some other projects.
Thanks

**Comment by muratg** [comment]
:+1:
