### ISSUE TITLE
dnu build fails

### ISSUE THREAD

**Issue by johnpapa** [aspnet/dnx#1831]
branch: beta4 - EndOfStreamException on dnu build #140

Details here https://github.com/OmniSharp/generator-aspnet/issues/140

cc @spboyer @sayedihashimi

**Comment by sayedihashimi** [comment]
Note: This is blocking osx

**Comment by davidfowl** [comment]
This big has been filed about 20 times. It's a mono but that has been fixed in the latest. There's no known release that has the fix.

**Comment by johnpapa** [comment]
@davidfowl  Are you in talks with them on when this will be released? 

I might suggest adding some notes to your aspnet pages to give people a heads up on the friction like this, so they know you have a handle on it.

**Comment by miguellira** [comment]
@johnpapa Ran into this immediately after the BUILD announcements. Mono 4.1.0 (complied from git master) fixes this but introduces other bugs and that's only if you happen to grab a stable build. My thread here (https://github.com/aspnet/Home/issues/508#issuecomment-100231894) summarizes my current state, but honestly it's probably too much trouble for most people to bother setting up.

+1 on a note on the docs though.

**Comment by sayedihashimi** [comment]
@davidfowl
>This big has been filed about 20 times.

Probably because its impacting a lot of people. What can we do to get a fix out for it?

If we can't get a fix out soon, can we modify the templates somehow to avoid the issue?

**Comment by davidfowl** [comment]
Talk to mono people. I'm closing this out as aspnet/Home already details the issue and how to work around it.

**Comment by johnpapa** [comment]
where is the workaround documented in https://github.com/aspnet/Home ?
