### ISSUE TITLE
dnu publish PrunePackages function deletes every file

### ISSUE THREAD

**Issue by timmydo** [aspnet/dnx#1832]
I'm not sure how the path separators got mixed up, but a string equal compare is probably a risky way to compare file names...

Example:

```
dnu publish . --out C:\tmp\testout

From keep list: C:\tmp\testout\approot\packages\Microsoft.AspNet.Loader.IIS\1.0.0-beta5-11747\lib/dnx451/Microsoft.AspNet.Loader.IIS.dll

Delete file: C:\tmp\testout\approot\packages\Microsoft.AspNet.Loader.IIS\1.0.0-beta5-11747\lib\dnx451\Microsoft.AspNet.Loader.IIS.dll
```

as a result, all the DLLs were stripped out of my publish.

@davidfowl  #1712

**Comment by davidfowl** [comment]
Might just be a lock file issue

**Comment by timmydo** [comment]
Yeah, looks like the lock file uses forward slashes
