### ISSUE TITLE
dnu restore --no-cache creates temp file that isn't cleaned up (one for each dependency)

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/dnx#1835]
Running `dnu restore --no-cache` creates a file in %TEMP% for **each dependency** (containing the nuget feed response) each time the command is invoked. These files are not cleaned up when restore finishes and over time litter the directory.

My DNX version: 1.0.0-beta5-11744.

The only place in the codebase where GetTempFileName() is invoked is in [HttpSource.cs#L129-L130](https://github.com/aspnet/dnx/blob/ed972d44a86efd42955c8d4f1fb0167f7d66fb86/src/Microsoft.Framework.PackageManager/Restore/NuGet/HttpSource.cs#L129-L130), so that's the likely culprit.

**Comment by davidfowl** [comment]
@ChengTian shouldn't that temp file be delete on close as well?

**Comment by ChengTian** [comment]
Yeah, when we should make it delete-on-close only when `--no-cache` is given.

**Comment by kalluri-nb** [comment]
This still exists in Beta6. After few iterations dnu restore with --no-cache stops working and hangs without any error or failure. We have to cleanup our build servers on schedule to handle this.

**Comment by davidfowl** [comment]
we're at beta7 now and beta8 soon. Does it repro there?

**Comment by kalluri-nb** [comment]
Yes it does in  1.0.0-rc1-15798 build too.
