### ISSUE TITLE
Make "projects" in global.json accept project folder path directly

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1841]
Today, each element in  projects  of  `global.json`  should be a parent folder of your projects.

For example, you have  `src/WebApplication5/project.json` , then `src` should be added to  projects , instead of  `src/WebApplication5`. If you add `src/WebApplication5` as an element in `global.json`, we are unable to resolve it.

However, it's actually quite intuitive that I should be able to add `src/MyProject` to `projects` in `global.json` (based on name of the property).

As @davidfowl  suggests, we should measure the performance hit before doing it.

**Comment by glen-84** [comment]
:+1: How else would you reference a single project if src contains multiple?

**Comment by ChengTian** [comment]
@glen-84 , could you please give an example of the scenario you are talking about?

**Comment by glen-84** [comment]
@ChengTian,

If `src` contains multiple projects, then all[1] of those projects are included, when I may just want to include one.

[1] For some reason, right now, it's including three of my projects and excluding MyProj.Tests.

**Comment by ChengTian** [comment]
@glen-84 , thanks, I see your point. Yeah, with this change merged in, you will be able to add a specific project into `global.json`, without adding its peers.

**Comment by muratg** [comment]
Need to do some profiling and finish. Moving to beta6
