### ISSUE TITLE
Improve tests for dnx repo

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1844]
There are some fundamental problems with our tests for `dnx`. @davidfowl has a bunch of complaints when adding tests for `dnu publish`:

* What syntax would I use?
* Do I check in packages?
* Should I run a restore first?
* Samples end up in a temp folder then get deleted after the test, I can’t see what ends up on disk
* If we extract functional tests from `dnx` repo to run them somewhere else, CI can be significantly faster
* (to be continued)

We need to improve our tests or even do it over.

**Comment by ChengTian** [comment]
One conclusion from the design meeting is that we want to dump the output of our tests to a file on disk. @victorhurdugaci finds that we can use the convenient `xunit.runner.dnx -xml myfile` command to do it.

**Comment by ChengTian** [comment]
This is enhancement that should be done with incremental manner. Moving to next milestone.

**Comment by ChengTian** [comment]
The progress can be tracked at: https://github.com/davidfowl/DnxTestingPrototype/tree/wei/add-more-representative-cases

**Comment by ChengTian** [comment]
I am fixing and refining the branch for this: https://github.com/davidfowl/DnxTestingPrototype/tree/wei/add-more-representative-cases

Will work with @JunTaoLuo to integrate this into DNX after sign-off tasks.

**Comment by JunTaoLuo** [comment]
completed as #2617. Ongoing improvements are tracked via #2825.
