### ISSUE TITLE
How do I resolve Abstractions and Interfaces mixup when I try to use IApplicationEnvironment interface?

### ISSUE THREAD

**Issue by rajajhansi** [aspnet/dnx#1852]
I have a project where some of my references have dependencies on 1.0.0-beta4 of Microsoft.Framework.Runtime.Interfaces and other references have dependencies on 1.0.0-beta5 of Microsoft.Framework.Runtime.Abstractions. Since my startup.cs and few other classes need IApplicationEnvironment and it has been defined in the same namespace Microsoft.Framework.Runtime, the project wouldn't build. In the past versions of Visual Studio, you can get away with this by using an alias on the Reference properties window on each of those assemblies and use an `extern alias aliasname` and `aliasname::type` syntax. With Visual Studio 2015 RC, there is no such property called alias in the Reference properties window and I can't figure out how to add `/r: runtimeabstractions=Microsoft.Framework.Runtime.Abstractions.dll` to the Roslyn C# compiler. Any help to resolve this ambiguity is greatly appreciated. It is very frustrating not being able to build my project and run.

**Comment by davidfowl** [comment]
> I have a project where some of my references have dependencies on 1.0.0-beta4 of Microsoft.Framework.Runtime.Interfaces and other references have dependencies on 1.0.0-beta5 of Microsoft.Framework.Runtime.Abstractions.

That's your mistake. Stop mixing the versions.

**Comment by rajajhansi** [comment]
@davidfowl, it is easier said than done.Why isn't there a 1.0.0-beta4 version of Microsoft.AspNet.DataProtection?? Because of that, it downloads the dependent Microsoft.Framework.Runtime.Interfaces v1.0.0-beta4.

**Comment by davidfowl** [comment]
Because it got renamed. I suggest you follow https://github.com/aspnet/Announcements closely if you plan to use beta5 packages.

**Comment by davidfowl** [comment]
https://github.com/aspnet/Announcements/issues

**Comment by rajajhansi** [comment]
@davidfowl, I do follow the announcements. At times, the changes are really overwhelming. For e.g., today there was a long thread about JSON comments, which is good but can't follow that full thread. I know the framework is still in beta. Would it be possible for you tell me when can we expect an RC version of the framework (just like Visual Studio RC)?

**Comment by rajajhansi** [comment]
I got the thread relevant to my issue: https://github.com/aspnet/Announcements/issues/15
