### ISSUE TITLE
[PackageManager] Support nuget 'release notes' in project.json

### ISSUE THREAD

**Issue by karldodd** [aspnet/dnx#1853]
Hello,

I am creating a 'Class Library (Package)' project in VS2015RC. In project.json, we can find most fields that used to be in the nuspec file. But 'release notes' and 'requireLicenseAcceptance' are not supported yet. If I manually add them there they don't seem to be recognized and inserted into the nuget package built.

Thanks,
P.S. the type for 'release notes' probably should be array of strings as usually people have multi-line release notes.

**Comment by davidfowl** [comment]
It's supported in beta5 and it's a single string. If you want to change how it's represented in NuGet please file an issue over there. github/NuGet/Home

**Comment by karldodd** [comment]
Great. Thanks for the updates!

Btw, where can I see the release notes for dnx beta5?

**Comment by davidfowl** [comment]
beta5 isn't released, it's in development.

**Comment by karldodd** [comment]
I misunderstood 'It's supported in beta5' and the closing of the issue. So acutally it 'will be' supported in beta5. Right?

In that case, probably this issue should still be open with a tag 'beta5' until beta5 is released. Just my two cents.

**Comment by davidfowl** [comment]
God no if we did that then we'd never close anything. We don't keep bugs open because there's no official release. I marked it with the appropriate tags to show this was fixed in beta5.

**Comment by davidfowl** [comment]
Fixed in https://github.com/aspnet/dnx/commit/70010d2026de84cf4171830965d2971809eb9d0a

**Comment by karldodd** [comment]
Well understood. Thank you for your sub-second reponse!  :-)

**Comment by tsvetomir** [comment]
Can we get an updated schema for project.json?

The one on [schemastore.org](http://json.schemastore.org/project) does not list the new properties.
