### ISSUE TITLE
Rename and shuffle some of the core projects/assemblies

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1855]
Proposal:

merge:
- dnx.coreclr.managed
- dnx.clr.managed

into dnx.host with the appropriate ifdefs.

Renames
dnx.host -> Microsoft.Dnx.Host
Microsoft.Framework.ApplicationHost -> Microsoft.Dnx.ApplicationHost
Microsoft.Framework.DesignTimeHost -> Microsoft.Dnx.DesignTimeHost
Microsoft.Framework.DesignTimeHost.Abstractions -> Microsoft.Dnx.DesignTimeHost.Abstractions
Microsoft.Framework.Runtime -> Microsoft.Dnx.Runtime.Hosting
Microsoft.Framework.Runtime.Abstractions -> Microsoft.Dnx.Abstractions
Microsoft.Framework.Runtime.Caching -> Microsoft.Dnx.Compilation.Caching
Microsoft.Framework.Runtime.Loader -> Microsoft.Dnx.Loader

Compilation
Microsoft.Framework.Runtime.Roslyn -> Microsoft.Dnx.Compilation.CSharp
Microsoft.Framework.Runtime.Roslyn.Abstractions -> Microsoft.Dnx.Compilation.CSharp.Abstractions?
Microsoft.Framework.Runtime.Compilation -> Microsoft.Dnx.Compilation
Microsoft.Framework.Runtime.Compilation.DesignTime -> Microsoft.Dnx.Compilation.DesignTime

Package Manager
Make Microsoft.Framework.Project a separate global tool.
Microsoft.Framework.PackageManager -> Microsoft.Framework.PackageManager??

/cc @anurse @glennc @muratg @lodejard

**Comment by muratg** [comment]
"Microsoft.Framework.Runtime.Roslyn.Abstractions -> Microsoft.Dnx.Compilation.**CSharp**.Abstractions?"

How about VB?  I propose we keep Roslyn in the name if we are going with these changes.

Also /cc @Eilon

**Comment by Eilon** [comment]
These names are all fine by me.

**Comment by Eilon** [comment]
For the Roslyn thing, we might want to not say "Roslyn" at all because that's more of a codename.

So, maybe like:

* `Microsoft.Dnx.Compilation.Abstractions`
* `Microsoft.Dnx.Compilation.Compiler.Abstractions`

?

**Comment by muratg** [comment]
Re Roslyn, I like `Microsoft.Dnx.Compilation.Abstractions`.

@davidfowl "`Microsoft.Framework.PackageManager`"... did you mean `Microsoft.Dnx.PackageManager`?

Also, "Make Microsoft.Framework.Project a separate global tool."  What would this global command do?

**Comment by anurse** [comment]
Suggestion:

Microsoft.Framework.Runtime -> Microsoft.Dnx.Runtime<del>.Hosting</del>

**Comment by victorhurdugaci** [comment]
> Make Microsoft.Framework.Project a separate global tool.

@davidfowl , @ChengTian says that dnvm is using this tool (`k-crossgen.cmd`) and it probably it is not the right thing to install it globally. What do you think?

**Comment by victorhurdugaci** [comment]
@davidfowl 

> merge:
>•dnx.coreclr.managed
>•dnx.clr.managed

Should we also merge `dnx.mono.managed` ?

**Comment by davidfowl** [comment]
yep

**Comment by davidfowl** [comment]
Wait, that actually won't work. We need to keep that one. hmmm

**Comment by davidfowl** [comment]
Sure, lets leave the crossgen tool for now.

**Comment by victorhurdugaci** [comment]
We talked about this offline and we're going to do it in beta6.

**Comment by davidfowl** [comment]
We shoud rename PackageManager to something like Microsoft.DotNetUtility?

**Comment by anurse** [comment]
Microsoft.Dnx.Utility? ... We should consider creating a naming pattern for global commands. Microsoft.Dnx.Utility and Microsoft.DotNetUtility end up sounding a lot like class libraries...

**Comment by davidfowl** [comment]
Microsoft.Dnx.Tools

**Comment by davidfowl** [comment]
Microsoft.Dnx.Tooling

**Comment by anurse** [comment]
I like those. Tools/Tooling imply something that the user runs rather than code they can reference.

**Comment by davidfowl** [comment]
@muratg Let's close on this by tomorrow so that VS can get the final names in.

**Comment by anurse** [comment]
:+1: I'm good with all the names we've seen so far. After edits in comments, I think we're at this list (not final, just updating everything based on the thread so far):

**Renames/Merges**:
* (`dnx.host` + `dnx.clr.managed` + `dnx.coreclr.managed`) -> `Microsoft.Dnx.Host`
* `dnx.mono.managed` -> `dnx.mono.managed` (as discussed above, we need to keep that separate)
* `Microsoft.Framework.ApplicationHost` -> `Microsoft.Dnx.ApplicationHost`
* `Microsoft.Framework.DesignTimeHost` -> `Microsoft.Dnx.DesignTimeHost`
* `Microsoft.Framework.DesignTimeHost.Abstractions` -> `Microsoft.Dnx.DesignTimeHost.Abstractions`
* `Microsoft.Framework.Runtime` -> `Microsoft.Dnx.Runtime`
* `Microsoft.Framework.Runtime.Abstractions` -> `Microsoft.Dnx.Abstractions`
* `Microsoft.Framework.Runtime.Caching` -> `Microsoft.Dnx.Compilation.Caching`
* `Microsoft.Framework.Runtime.Loader` -> `Microsoft.Dnx.Loader`

**Compilation**:
* `Microsoft.Framework.Runtime.Roslyn` -> `Microsoft.Dnx.Compilation.CSharp`
* `Microsoft.Framework.Runtime.Roslyn.Abstractions` -> `Microsoft.Dnx.Compilation.CSharp.Abstractions`
* `Microsoft.Framework.Runtime.Compilation` -> `Microsoft.Dnx.Compilation`
* `Microsoft.Framework.Runtime.Compilation.DesignTime` -> `Microsoft.Dnx.Compilation.DesignTime`

**Package Manager**:
* `Microsoft.Framework.PackageManager` -> `Microsoft.Dnx.Tools` <del>Microsoft.Framework.PackageManager??</del>
* Keep dnx-crossgen around as an internal tool. <del>Make Microsoft.Framework.Project a separate global tool.</del>

I wonder if the following might be appropriate? Not a major thing, just a vague thought. Common names in namespaces stand out to me as options for parent namespaces :)
* `Microsoft.Framework.ApplicationHost` -> `Microsoft.Dnx.Hosting.Application`
* `Microsoft.Framework.DesignTimeHost` -> `Microsoft.Dnx.Hosting.DesignTime`

**Comment by muratg** [comment]
@davidfowl As we don't want to break people on the dev feed, the decision was to make this in Beta 7. If we do it now, people using Beta 6 bits on RC will be broken immediately.

cc: @danroth27 @DamianEdwards

**Comment by muratg** [comment]
@victorhurdugaci reminded me that we'll need to decide on the final set of the names for the code in VS. If no one objects, we'll go with the names in @anurse's comment above.

cc: @danroth27 @DamianEdwards @BillHiebert

**Comment by davidfowl** [comment]
What about Tooling instead of Tools? `Microsoft.Dnx.Tooling`? Application.Host and DesignTime.Host is kinda weird since those sub namespaces don't have any types in them.

**Comment by muratg** [comment]
@davidfowl sounds good to me.  let's close on this today and hand it over to @BillHiebert

**Comment by anurse** [comment]
I'm fine with all that. I'll update my comment.

**Comment by moozzyk** [comment]
dnx.clr.managed  must not be merged with anything. It is a domain manager for full Clr which has to have a real strong name. This is the reason why it does not have any dependencies and we use reflection to call Bootsrapper methods - the dependencies would have to be strong named too.

**Comment by anurse** [comment]
Ok, how about this:

* `dnx.clr.managed` -> `Microsoft.Dnx.DomainManager`
* `dnx.coreclr.managed` + `dnx.host` -> `Microsoft.Dnx.Host`

/cc @victorhurdugaci

**Comment by moozzyk** [comment]
`Microsoft.Dnx.DomainManager` does not convey the information that this is a domain manager for Clr only. Dnx.coreclr.managed contains a domain manager for CoreClr.  Note that dnx.coreclr.managed is loaded by CoreClr when bootstrapping CoreClr from native code. I don't know if what currently is in dnx.host will be available if the new host dll is being loaded when (before?) AppDomain is created and if this has any other consequences we don't realize (e.g. security?). 
I personally think that the separation we currently have makes sense whereas having dnx.host containing 1 of 2 app domain managers is weird. Names could be improved indeed.

**Comment by anurse** [comment]
Ok, how about a straight name change for now then. The exact structure of this is completely uninteresting to users so we should do whatever makes it easier for us to develop/service/etc. :)

* `dnx.clr.managed` -> `Microsoft.Dnx.Host.Clr`
* `dnx.coreclr.managed` -> `Microsoft.Dnx.Host.CoreClr`
* `dnx.host` -> `Microsoft.Dnx.Host`

**Comment by moozzyk** [comment]
I would prefer:
-  dnx.clr.managed  ->  Microsoft.Dnx.DomainManager.Clr  
-  dnx.coreclr.managed  ->  Microsoft.Dnx.DomainManager.CoreClr

but don't really feel very strong about this.

**Comment by anurse** [comment]
Sure. I did notice that even though there is a class called `DomainManager` in `dnx.coreclr.managed.dll`, it is not actually an AppDomain Manager, it is just a static class to hold an entry point. I still kinda feel like it could be merged in to the CoreCLR version of `dnx.host`. CLR is a different story because, for servicing purposes, we need a separate assembly.

Regardless, these are completely internal assemblies so renaming/refactoring them again will not break customers and we can revisit it later.

@victorhurdugaci - are you caught up on these changes? Let's go with @moozzyk 's final suggestion for now:

* `dnx.clr.managed` -> `Microsoft.Dnx.DomainManager.Clr`
* `dnx.coreclr.managed` -> `Microsoft.Dnx.DomainManager.CoreClr`

**Comment by muratg** [comment]
I assume these recent changes in naming do not have any tooling impact. If there's any impact, we'll need to talk to the tooling team and sort out the schedule.

**Comment by anurse** [comment]
The ones @moozzyk and I are discussing will have **no** tooling impact, but definitely good to check :). I think we're all happy with the names for the assemblies that do have tooling impact.

**Comment by muratg** [comment]
Cool, sounds good.

**Comment by victorhurdugaci** [comment]
Just FYI, there is not such thing as `Microsoft.Framework.Runtime.Compilation`. There is only `Microsoft.Framework.Runtime.Caching` which contains `Microsoft.Framework.Runtime.Compilation.xproj`

**Comment by anurse** [comment]
Oof. We should reconcile those names. Use `Caching` as the name since it looks like it only contains Caching stuff.
