### ISSUE TITLE
Unable to execute on Linux after dnu publish on Windows

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/dnx#1858]
Command to publish:

dnu publish --no-source --out .\deploy --runtime active

Contents of .\deploy are pushed to a Docker Container. Executing results in the following error:

root@0f31f2fc0af0:/app# ./SimpSamp
./SimpSamp: line 13: /app/approot/packages/dnx-coreclr-win-x64.1.0.0-beta5-11760/bin/dnx: No such file or directory

Dnx in this directory has the following extension:

/app/approot/packages/dnx-coreclr-win-x64.1.0.0-beta5-11760/bin/dnx.exe

contents of script generated by publish:

***

#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export SET DNX_APPBASE="$DIR/approot/packages/SimpleSample/1.0.0/root"

exec "$DIR/approot/packages/dnx-coreclr-win-x64.1.0.0-beta5-11760/bin/dnx" --appbase "$DNX_APPBASE" Microsoft.Framework.ApplicationHost SimpSamp "$@"

***

dnvm list:

***
1.0.0-beta5-11760 clr     x64          C:\Users\tdu\.dnx\runtimes
1.0.0-beta5-11760 clr     x86          C:\Users\tdu\.dnx\runtimes
active 1.0.0-beta5-11760 coreclr x64          C:\Users\tdu\.dnx\runtimes default
1.0.0-beta5-11760 coreclr x86          C:\Users\tdu\.dnx\runtimes
	   
***

**Comment by davidfowl** [comment]
Wait you published the windows runtime and expected it to work on Linux? Am I missing something?

**Comment by jsacapdev** [comment]
apologies, that's my mistake. is it possible (on a windows machine) to pull in the linux runtime as part of the publish? or would the linux runtime need to be installed on the target for the published app to work?

**Comment by jsacapdev** [comment]
i have downloaded the linux runtime, installed it using dnvm, used the publish as follows:

dnu publish --no-source --out .\deploy --runtime dnx-coreclr-linux-x64.1.0.0-beta5-11760

but when I attempt to run it, i get the following error:

root@f292fdbe1c7f:/app# ./SimpSamp
Loaded Module: dnx.coreclr.so
Found DLL Export: CallApplicationMain
failed to locate libcoreclr with error libcoreclrpal.so: cannot open shared object file: No such file or directory
