### ISSUE TITLE
Remove recursive project.json lookup in "dnu restore"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1862]
I believe @davidfowl talked about this but I couldn't find an issue for it.

Today `dnu restore` automatically enumerate subfolders recursively and restores for all `project.json` it sees. In this way, it sometimes restores for non-relevant projects, like the `dnu publish` output in your project output folder.

Here is my proposal for new logic:
1. If there is a `project.json` in target path, restore for it.
2. If there is a `global.json` in target path, restore for all projects specified in `projects` property of `global.json`.
3. If no condition above is met, we restore for all subfolers in target path. Note that it is not recursive and we only go one-level down.

**Comment by BrennanConroy** [comment]
:+1:

**Comment by moozzyk** [comment]
@ChengTian - I think this is the issue you were looking for #1494

**Comment by ChengTian** [comment]
Yeah, thanks for pointing it out. Need to improve my skills for searching on Github :smile:
