### ISSUE TITLE
dnu should always write out its version number as the first line of text

### ISSUE THREAD

**Issue by lodejard** [aspnet/dnx#1864]
it would really help know exactly what is doing the restore and build when looking at VS output windows

**Comment by muratg** [comment]
@ChengTian

**Comment by ChengTian** [comment]
Good idea. We can show the first line of `dnu --help` at the beginning of restore/build. So you can see
```
Microsoft .NET Development Utility v1.0.0-beta5-11760
<blank line>
<usual output>
```

**Comment by ChengTian** [comment]
Do we want copy right info like the header xUnit always output?
![capture](https://cloud.githubusercontent.com/assets/1383883/7638189/ecfab83e-fa27-11e4-9d7b-dad7e7125ce8.PNG)

**Comment by muratg** [comment]
First line of `dnu --help` seems good for this case. I don't think we need the (c), but adding @Eilon to let us know.

**Comment by Eilon** [comment]
Just product name and version is fine.

**Comment by ChengTian** [comment]
Should be a easy one but can improve user experience a lot. I can finish this quickly.
