### ISSUE TITLE
dnu publish with --no-source should prune the application package as well

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#1866]
Dev14 RC
1. New empty ASP.NET 5 app (EmptyApp10), add html page and a simple MVC controller / view
2. Ctrl-F5 and publish to a new Azure web app (no remote DB needed)
3. Don't make any changes
4. Publish again

ACTUAL
Publish preview shows several files (about 15 of them) are getting updated. This is a rough experience if I am re-publishing with no changes or with just 1 or 2 changes.

EXPECTED
Can dnu publish 'prune' the files for the application package EmptyApp10 so that it has just the files needed at runtime. Wei mentioned that we do a similar thing for the runtime packages (eg. Microsoft.AspNet.Authentication in screenshot below). Is the .nupkg file needed? Are the dlls for both dnx451 and dnxcore50 needed if I specified only one runtime for dnu publish?

![image](https://cloud.githubusercontent.com/assets/8246794/7624448/67f45116-f99d-11e4-966f-3820b037eb1f.png)

![image](https://cloud.githubusercontent.com/assets/8246794/7624488/2093d1ec-f99e-11e4-85de-280c539e3ec4.png)

**Comment by davidfowl** [comment]
Will be irrelevant
