### ISSUE TITLE
Why does the integer value change it's sign(positive to negative)

### ISSUE THREAD

**Issue by hanu412** [aspnet/dnx#1868]
I have this code. Interestingly the integer variable value is changing its sign(positive to negative) after I had assigned it to the Max possible value of integer and then incremented it. 
Where as when I decrement opposite is happening. Any thoughts on this? I am not 100% sure in which forum/section should I post. If this is not the place this query should be,kindly let me know the correct one.

P.S: There is no exception either.

class Program
        {
        static void Main(string[] args)
            {
          
            int x = 0;
            try
                {
                x = int.MaxValue;
                x++;
                }
            catch (Exception e)
                {
                
                throw;
                }
            Console.WriteLine("Value of x is : " + x.ToString()); 

            Console.WriteLine("\n");

            int z = 0;
            z = -300;
            z = z - 900;
            Console.WriteLine("Value of z is : " + z.ToString());
            Console.WriteLine(z.ToString());
            Console.WriteLine("\n");
            int y = 0;
            y = int.MinValue;
            y = y-100;
            Console.WriteLine("Value of y is :" + y.ToString());
            Console.ReadLine();
            }

Result :: 

![result](https://cloud.githubusercontent.com/assets/11040896/7635553/46357446-fa7f-11e4-983b-a1aa0ac9f8a4.JPG)

**Comment by davidfowl** [comment]
This has nothing to do either the dnx. I'd suggest you file this where other vs issues are filed

**Comment by moozzyk** [comment]
Isn't it just a standard [integer overflow](http://en.wikipedia.org/wiki/Integer_overflow)? Use a [`checked`](https://msdn.microsoft.com/en-us/library/74b4xzyw.aspx) block to enable checking for overflows in which case you should get an `OverflowException`.
