### ISSUE TITLE
dnu pack- provide a way to provide an icon

### ISSUE THREAD

**Issue by patrickjamesbarry** [aspnet/dnx#1871]
I currently do not see a way to provide an icon for the nuget package that is created via dnu pack. It would be great if we could just provide an icon in the package itself (https://nuget.codeplex.com/wikipage?title=Packages%20Containing%20Icon%20and%20License)

**Comment by ChengTian** [comment]
You can specify meta data of your package in your `project.json`:
https://github.com/aspnet/Home/wiki/Project.json-file#metadata

The link above doesn't contain a full list of meta data names, but most meta data names that works for nuget should work for `project.json` as well.

So please add
```
"iconUrl": "<url_of_icon>"
```
to your `project.json` and do `dnu pack`.

**Comment by ChengTian** [comment]
@muratg , we may want to have a full list of meta data names on our Wiki page: 
https://github.com/aspnet/Home/wiki/Project.json-file#metadata

Or at least let users know they can use all meta data names available in nuspec:
http://docs.nuget.org/Create/Nuspec-Reference

**Comment by davidfowl** [comment]
@ChengTian I think @patrickjamesbarry wants to actually put the icon in the package. I seems like NuGet can do this as well.

**Comment by patrickjamesbarry** [comment]
Thanks Cheng! That gets me what I need for now.  I wasn't aware that the metadata included nuget properties.

Regarding providing the logo inside the nuget package.
I played around with providing a logo inside my nuget package (instead of providing a url) and it never resolved. So it looks like that is a feature that has been requested of nuget, but they have not implemented yet. Sure is a great idea and would love to have it.

**Comment by ChengTian** [comment]
@davidfowl , just talked to NuGet team and confirmed that NuGet doesn't support having an icon inside nupkg.

https://nuget.codeplex.com/wikipage?title=Packages%20Containing%20Icon%20and%20License
This is a proposal but it hasn't been implemented.

If later NuGet supports this, users can just put correct file path to `project.json` and it should just work. So this is not a DNX bug.
