### ISSUE TITLE
Provide writers for the 3 json files in runtime

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1880]
We have readers but not writers for `project.json`, lock file and `global.json` and it seems that everyone is writing those files in their own way. Plus there is a lot of duplicated code.

We should make the object models mutable and have some write methods on them.

**Comment by victorhurdugaci** [comment]
@davidfowl , @troydai what do you think?

**Comment by davidfowl** [comment]
Sure, I think we should have an API for doing this but it shouldn't be in the runtime. We're actually moving all of this type of logic to NuGet

**Comment by troydai** [comment]
@victorhurdugaci can you give a few scenarios which requires writing? And a JSON serializer doesn't necessary need the result of JSON parser to be mutable. These are two different issues.
