### ISSUE TITLE
DNX does not include dependency <group> when <group targetFramework="txm"> exists

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#1881]
This is inconsistent with nuget v2 and is currently breaking for our packages.  I put all surface area dependencies in `<group>` and only the **additional** implementation dependencies in `<group targetFramework="txm">`.

**Comment by davidfowl** [comment]
Not sure what this means

**Comment by ericstj** [comment]
For the following I'd expect all dependencies to apply for DNXCore5.0, including System.Runtime and System.Security.Cryptography.Hashing.  That is what will happen when nuget installs the package.  That is not what happens when DNX resolves the package.  DNX omits System.Runtime and System.Security.Cryptography.Hashing
```
      <group>
        <dependency id="System.Runtime" version="4.0.0-beta-22915" />
        <dependency id="System.Security.Cryptography.Hashing" version="4.0.0-beta-22915" />
      </group>
      <group targetFramework="DNXCore5.0">
        <dependency id="System.Resources.ResourceManager" version="4.0.0-beta-22915" />
        <dependency id="System.Security.Cryptography.Encryption" version="4.0.0-beta-22915" />
        <dependency id="System.Runtime.InteropServices" version="4.0.0-beta-22915" />
        <dependency id="System.Security.Cryptography.RandomNumberGenerator" version="4.0.0-beta-22915" />
      </group>
```

**Comment by davidfowl** [comment]
Really, that's interesting because we use the same logic. Though I'm not surprised this as packages produced by the dnx just duplicate the dependency in each of the relevant groups. Can you just duplicate the dependencies?

**Comment by ericstj** [comment]
I can, but I thought you'd want to make sure you were compatible with existing packages.  This is a breaking change.

**Comment by davidfowl** [comment]
Sure, it's a good bug.

**Comment by davidfowl** [comment]
do you have any proof that nuget v2 supports this? I'm using the nuget v2 code and don't see any logic that merges these.

I believe the dependency logic matches the folder selection logic. Only one folder is chosen

**Comment by muratg** [comment]
We have a discussion today about this with @pranavkm @lodejard @troydai @Eilon

**Comment by ericstj** [comment]
Maybe not.  I could have sworn that it behaves this way.  I just explicitly tested it and confirmed it does not. :frowning: Perhaps it was with multiple PCLs that apply?  Anyhow since I can't repro I will close this and update the packages.

**Comment by pranavkm** [comment]
@ericstj could you let us know when the CoreCLR packages are updated so we re-resolve https://github.com/aspnet/CoreCLR/issues/26?

**Comment by ericstj** [comment]
I checked in the fix over the weekend so the next build you see should have the fix.
