### ISSUE TITLE
dnx use on Windows requires that you specify the runtime - why?

### ISSUE THREAD

**Issue by rkeithhill** [aspnet/dnx#1882]
On Linux I can use dnvm use latest and it will work correctly.  On Windows, dnvm use latest will failure saying it can't find dnx-clr-win-x86.1.0.0-beta5-11781.  When I create the alias I specify the runtime as coreclr.  Heck, the file ~\.dnx\alias\latest.txt contains:

dnx-coreclr-win-x86.1.0.0-beta5-11781

So why do I need to specify -r coreclr with dnvm use latest to make it work on Windows?

**Comment by ChengTian** [comment]
Hi @rkeithhill , this issue should be reported in dnvm repo. I moved it there for you: https://github.com/aspnet/dnvm/issues/268
