### ISSUE TITLE
PCL for Windows 8.1 + Windows Phone 8.1 (Profile 32)

### ISSUE THREAD

**Issue by smudge202** [aspnet/dnx#1883]
In addition to #1837, Profile 32 targeted PCL's are able to work with phone API's such as `Windows.Storage.StorageFolder`.

I believe it does this by referencing the `Windows.winmd` file for the Phone's SDK:
`C:\Program Files (x86)\Microsoft SDKs\Portable\v14.0\110C4FEFF2BA61C0746933A9ED6E248D\`

We are not able to this within a vNext class library targeting the same profile:
`.NETPortable,Version=v4.6,Profile=Profile32`

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#583
