### ISSUE TITLE
NuGet package with no version attribute in dependency node doesn't work in DNX

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/dnx#1885]
Consider the following nuspec:

``` xml
<?xml version="1.0"?>
<package xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <id>MyFancyTestLib</id>
    <title>MyFancyTestLib</title>
    <version>1.0.4</version>
    <authors>Me</authors>
    <description>MyFancyTestLib</description>
    <dependencies>
     <group>
       <dependency id="NLog" />
     </group>
    </dependencies>
  </metadata>
</package>
```

Note how the `<dependency id="NLog" />` has no `version` attribute, which is allowed by the nuspec docs.

Create a .nupkg from it by running `nuget pack MyFancyTestLib.nuspec` and add it to a folder that is in your package sources.

Next, create a DNX project with the following project.json:

``` json
{
  "version": "1.0.0-*",
  "dependencies": {
    "MyFancyTestLib": "1.0.4"
  },
  "frameworks": {
    "dnx451": {}
  }
}
```

Running `dnu restore` creates the following lockfile:

``` json
{
  "locked": false,
  "version": -9996,
  "targets": {
    "DNX,Version=v4.5.1": {
      "MyFancyTestLib/1.0.4": {
        "dependencies": {
          "NLog": null
        }
      }
    }
  },
  "libraries": {
    "MyFancyTestLib/1.0.4": {
      "sha512": "4wHpmNWxh/ZsdVkSUKOMiOPfNSqECm+9LpDdmvQdOqZ+712D7mt2GKYls0cZgcoqQjeuVKUOAIgeRwc+7GKy7Q==",
      "files": [
        "MyFancyTestLib.1.0.4.nupkg",
        "MyFancyTestLib.1.0.4.nupkg.sha512",
        "MyFancyTestLib.nuspec"
      ]
    }
  },
  "projectFileDependencyGroups": {
    "": [
      "MyFancyTestLib >= 1.0.4"
    ],
    "DNX,Version=v4.5.1": []
  }
}
```

Note the `"NLog": null` line.

Running `dnu list` complains about MyFancyTestLib being unresolved and `dnx . run` fails as well.

Version: DNX 1.0.0-beta5-11760 clr x86

**Comment by davidfowl** [comment]
Get the package author to update the package if possible.

**Comment by akoeplinger** [comment]
Sure, but given that leaving off the version is allowed in the nuspec there should at least be some better error messages if DNX doesn't support this scenario. How does nuget resolve the dependency in this case?

**Comment by davidfowl** [comment]
Yea it's allowed in nuget and it gets the latest but I'd rather not support that and see how many things break because with transitive dependencies, it's ambiguous

**Comment by akoeplinger** [comment]
Understood. Might be a good idea to run a query over the NuGet database and see how many packages are affected.

**Comment by muratg** [comment]
@yishaigalatzer
