### ISSUE TITLE
Dnu publish is missing a nice way to specify runtime \ architecture

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#1890]
We don't have an equivalent to `-r coreclr -arch x86` as part of the publish command.

**Comment by muratg** [comment]
We'll look at this unification of command line tooling.

**Comment by Tratcher** [comment]
Nor do we support aliases. The only special keyword is `active`

**Comment by muratg** [comment]
@davidfowl new publish should still support this IMO.

**Comment by davidfowl** [comment]
I'm not sure we need a publish step anymore.
