### ISSUE TITLE
project.json provide an error for an unknown PCL target

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#1896]
An unknown PCL framework target turns into DNX 4.5.1 under References in Solution Explorer.

If you have multiple framework targets then the unknown PCL framework target completely disappears.

There should be an error when there is an unknown PCL framework. Right now it appears to fail silently.

A related issue to this is whether there should be a way to decouple the framework target from what appears in the NuGet package. e.g. If I have the target "net45+win+wp80+wpa81" and I want to add "MonoAndroid10+Xamarin.iOS10+MonoTouch10" as well to help Mono choose the right package, right now project.json won't know what to do with it.

**Comment by JamesNK** [comment]
Example of this issue:

I wanted to add a framework target of "net40+sl5+win+wp80+wpa81". It wasn't recognized and didn't appear. Because I had no way to figure out what the magic string is I fell back to using ".NETPortable,Version=v4.0,Profile=Profile328"

**Comment by muratg** [comment]
We should raise an error in this case.
