### ISSUE TITLE
project.json PCL framework target meta package

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#1897]
Right now when defining a PCL framework target, all the individual assemblies used need to be specified in frameworkAssemblies. This is a pain: https://github.com/JamesNK/Newtonsoft.Json/blob/3cb2518b6c1d0cffb41c2c0b8aacbe0e60c63ec2/Src/Newtonsoft.Json/project.json#L61-L87

A classic PCL project automatically references all the assemblies and groups them together under references in solution explorer as ".NET". This is easy.

Make it easy, not a pain.

:smile_cat:

**Comment by muratg** [comment]
This issue was moved to dotnet/corefx#4971
