### ISSUE TITLE
Package restore should by default restore the exact version specified in project.json

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#1903]
Today package restore can result in package versions that are wildly different from what you specified in project.json based on what feeds you have available. This can result in some crazy runtime behavior. Instead we should only restore the exact version specified in project.json *unless* a different dependency requires that version be bumped up or down.

**Comment by Eilon** [comment]
@davidfowl I think we talked about this yesterday afternoon.

**Comment by MichaelKetting** [comment]
Very much looking forward to this getting fixed. Right now, switching between feature branches with different dependency version or simply updating to a version with a higher dependency is really involved, i.e. I usually have to delete the bin, obj, project.json.locked and \users\.dnx\packages folder before performing a dnu restore. And then, it usually works.

**Comment by davidfowl** [comment]
@MichaelKetting Just run restore again

**Comment by MichaelKetting** [comment]
Thanks for the update!
