### ISSUE TITLE
Support for client-side resources in NuGet packages

### ISSUE THREAD

**Issue by tsvetomir** [aspnet/dnx#1913]
Suppose you want to build a library that contains HtmlHelper extensions **and** their scripts and styles.

How is this addressed by `dnu pack`?
Can you add external files that would later be unpacked in `wwwroot`?

**Comment by ToddThomson** [comment]
I also would like to know how to include content into a Nuget package built with dnu pack.

Specifically, I would like to include cshtml files. I have a asp.net 5 class library which contains MVC6 controllers and views ( the *.cshtml file ).

**Comment by davidfowl** [comment]
Yea this is bigger than including content we don't have a consumption story for content at the moment.

**Comment by ToddThomson** [comment]
MVC6 modules/components. The class library contains the controllers and services; the packaged content contains the area views. I've been breaking down large projects like this since the beginning of MVC ( although I had to copy the module views manually to ./areas ).
This may be doable right now by using the "content" property in project.json ( "content": [ ./areas/area-name/**/* ). 
Should also be doable if dvu pack allowed for a .nuspec file.

**Comment by ToddThomson** [comment]
@davidfowl What do you mean by "This is bigger than including content..."?
If I have a "content" property defined in my project.json and I perform a dnu pack or dnu publish --no-source then what is stopping the generation of a content folder being created in the nuget package?

**Comment by davidfowl** [comment]
Content is never copied into the application when consuming packages that have content. It it also never included when creating nuget packages.

**Comment by tsvetomir** [comment]
Right, that's what I figured as well. Even if you add content to the archive it is still ignored. This is evident with older packages, e.g. EntityFramework that contains a README file I think.

I suppose one can do with Bower for the client-side resources. That's what it does best anyway.
This leaves the question open for editor templates and possibly other odds and ends.

**Comment by ToddThomson** [comment]
With nuget 2 you can obviously add scripts, css ( and I assume most anything ) to an application by andding to "Content" in the nuget package. @davidfowl R U saying that in Nuget 3 that this is no longer the case?
If content ( from a nuget package ) is never going to copied into an ASP.NET 5 application then I would ask for the following: Have nuget add "content" into an application specific directory in the application, for example: "nuget_components". The folder in "nuget_components" would be a component name + a  unique package identifier. The package contents layout would be whatever the provider conceived of ( no restrictions ).
With this structure I could at have MVC6 controllers AND views ( layouts, etc ) added to the application in a no harm way. An addition to the gulp build pipeline or a view locator added to have the application use the new cshtml.

**Comment by causer** [comment]
+1

**Comment by ToddThomson** [comment]
Coming back to this at Beta 8: I will use the precompiled view provider in MVC6 to package the views in modular MVC nuget packages.
