### ISSUE TITLE
NuGet package registration in Startup.cs

### ISSUE THREAD

**Issue by tsvetomir** [aspnet/dnx#1914]
What is the recommended way to register packages installed via NuGet in `Startup.cs`?
For example, the EntityFramework package can add the following in Startup.cs:
```
    services.AddEntityFramework()
            .AddSqlServer()
```

Currently `dnu restore` does not seem to execute the  `install.ps1` or any other scripts.

**Comment by davidfowl** [comment]
There is no way to do this and likely won't be. We won't support install.ps1 and currently don't support content.

**Comment by Eilon** [comment]
The problem with adding code to a project is that it is impossible to know where to add it. It might work in a trivial "default project" scenario, but you can't make it work in any realistic scenario.

**Comment by tsvetomir** [comment]
Right, makes sense. Adding the registration code would've been a gross hack at best.

Better solve this through documentation :) Thank you!
