### ISSUE TITLE
csproj dependency - modifying OutputPath for csproj breaks the dependency resolving

### ISSUE THREAD

**Issue by urigolani** [aspnet/dnx#1915]
* using dnx beta4 with VS 2015 RC.

It seems that if I modify the csproj OutputPath to something other than {Configuration}, for example:
<OutputPath>bin\x64\Debug\</OutputPath>  
Adding the Platform x64 to the path, than the wrapped file created by reference is malformed. for example:

```
{
  "version": "1.0.0-*",
  "frameworks": {
    "dnx451": {
      "wrappedProject": "../..//Models/Models.csproj",
      "bin": {
        "assembly": "../..//Models/obj/{configuration}/Models.dll",
        "pdb": "../..//Models/obj/{configuration}/Models.pdb"
      },
      "dependencies": {
        "Newtonsoft.Json": "6.0.8"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
Yep, we don't currently support platform but you can tweak the generated file as a workaround.

**Comment by muratg** [comment]
Closing this one.

**Comment by Quantumplation** [comment]
Would you accept a pull request which added a --platform command line argument to the dnu wrap command?

**Comment by davidfowl** [comment]
We're not adding anymore features to dnx at this point. We'll be revisiting the csproj integration for RC2 via nuget.
