### ISSUE TITLE
More package restore performance improvements

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1919]
When multiple projects are being restored. We can do a few things to improve the performance:

- Break restore into 2 parts, resolve and install. This allows use to restore per project sharing a cache per NuGet.Config (basically a cache based on the configured sources). We can then uniquify the results of each graph walk and install those packages.

**Comment by muratg** [comment]
Still valid?

cc: @anurse

**Comment by troydai** [comment]
Ping @anurse @davidfowl how do we deal with this in/after rc2?

**Comment by davidfowl** [comment]
We work on nuget
