### ISSUE TITLE
Don't show stack traces for "normal" errors running 'dnx'

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#1923]
Today when almost any error happens when running `dnx`, you get giant stack traces:

For example, if you run `dnx . run` when dependencies in `project.json` were changed, you get this slice of joy:

![newinvalidlockfile_run_dependencies](https://cloud.githubusercontent.com/assets/1383883/7740046/454091a6-ff20-11e4-9295-104f8b2f552e.PNG)

We need to avoid printing out any stack traces when "normal" errors occur. They should just show an error message, explain what's wrong, and return with a non-zero status code.

Note: This is tricky because Helios often needs to report the same types of errors, and throwing exceptions is "easiest."

**Comment by davidfowl** [comment]
We could throw specific exception types and print them out differently in the host. Exceptions that originate from the dnx vs ones that originate from user code.

**Comment by Eilon** [comment]
Wow, a seemingly legitimate use of custom exception types... I'm intrigued :trollface:

**Comment by victorhurdugaci** [comment]
Also, we shouldn't use exceptions to surface error messages. Use the build reports and write a human friendly, actionable message. If someone really wants call stacks, we could show them on verbose
