### ISSUE TITLE
Unable to use web.cmd after I do a dnu publish

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#1926]
1. New Empty web app 
2. Add index.html to wwwroot, add StaticFiles package to project.json and app.UseFileServer to Startup.cs
3. Ctrl-F5 works with the web command, works. I'm able to load the index page
4. Publish to File System
5. Run web.cmd from the published location

ACTUAL
Exception when web.cmd is run. 

Seems to be a regression with beta5 bits. Works fine with Dev14 RC (beta 4) bits.

![image](https://cloud.githubusercontent.com/assets/8246794/7757616/b43b3e4c-ffb8-11e4-92f8-c2c9118b0194.png)

**Comment by davidfowl** [comment]
What version of the runtime?

**Comment by balachir** [comment]
1.0.0-beta5-11749. This is the version that's available in the latest tooling at the moment.

**Comment by ChengTian** [comment]
Talked to @balachir and he will get the latest dnx build from CI output directly. Some bugs should be already fixed in the latest dnx build.

**Comment by balachir** [comment]
Yep, works fine with 1.0.0-beta5-11855
