### ISSUE TITLE
Package Manager throws exception 'onload' is an unexpected token.

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnx#1927]
_Originally filed on connect at https://connect.microsoft.com/VisualStudio/feedback/details/1297017/package-manager-throws-exception-onload-is-an-unexpected-token moving here_

I get this whenever I am trying to install EF7 at least. Of note, the errors say the cache file "The XML file C:\Users\sdjohnson\AppData\Local\dnu\cache\2dc71b1f1ade53369c4e7ad9e091254949655aef$ww.postsharp.net_nuget_packages_\list_EntityFramework_page1.dat" is corrupt and a slew of similar errors then a stack trace. 
Of note is the reference to postsharp, which I have uninstalled since I never use it anymore and never even installed into 2015 RC. I have gone through my registry and removed all references to PostSharp as well.

I have been playing around and it seems that this happens in projects targeting Asp.NET5. I have not tried to create any Asp.NET 4.6 projects so far and have been trying to teach myself the new technology first. I am getting the same or very similar errors anytime I try to install any stable packages that have been around before or are targeting the non-Asp.NET5 applications; EF6 is just one of them.

**Comment by davidfowl** [comment]
@ChengTian this is fixed now right?

**Comment by ChengTian** [comment]
Yeah, clean your `%userprofile%\AppData\Local\dnu\cache` and use latest version of dnx. The new dnu will never cache corrupted files.

**Comment by ChengTian** [comment]
Dup of https://github.com/aspnet/dnx/issues/1746
