### ISSUE TITLE
Native projects refactoring/clean up

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1937]
- [x] review all usages of `char *` and use `std::string` where appropriate (especially in places where we concatenate)
 - [x] review all operations on paths and make sure that we are not creating invalid (e.g. too long) paths and we don't write outside buffers (see #1358, #1363 for some examples)
 - [x] use x-plat types consistently - files used by different platforms should use x- types, platform specific types should use native types
 - [x] remove tchar.h from non-windows projects
 - [ ] consider removing hungarian and introduce consistent style/naming
 - [x] dnx.clr.vcxproj should use common dnx build settings/targets/props for native projects
 - [ ] organize files to folders (*.vcxproj.filters) in projects that currently don't do that

**Comment by muratg** [comment]
@moozzyk I think most of this is done, no?

**Comment by moozzyk** [comment]
I need to go over `pal.*.cpp` to call it done

**Comment by muratg** [comment]
:+1:

**Comment by davidfowl** [comment]
Do we still need this?

**Comment by moozzyk** [comment]
Probably not. Most of it was done anyways...
