### ISSUE TITLE
After win32/onecore split some file attributes are incorrect

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#1941]
![image](https://cloud.githubusercontent.com/assets/1438884/7780216/f76dfabe-0090-11e5-86b8-6eb8f0ed944b.png)

![image](http://retrolegends.wikidot.com/local--files/game:1941:counter-attack-game/1941_Arcade2.png)

(Hint: bug number)

**Comment by davidfowl** [comment]
I love that game

**Comment by muratg** [comment]
@moozzyk if this a quick fix, let's get it done with a check-in. If not, we can move this to backlog.

**Comment by muratg** [comment]
@moozzyk Let's get it in if this can be done quickly. Otherwise we can move this out since it's mostly a cosmetic change.

**Comment by moozzyk** [comment]
ACK - I will treat this as low pri for beta6

**Comment by moozzyk** [comment]
Fixed in d441627c59
