### ISSUE TITLE
Provide friendlier error message and/or line information when users put comments in JSON

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1943]
I've had more than one person come to me now asking for help with their ASP.NET 5 application for cryptic errors like this on F5:

Server Error in '/' Application.
 
Illegal character / /. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
 
Exception Details: System.Exception: Illegal character / /.
 
Source Error: 
 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  
 Stack Trace: 
  
[Exception: Illegal character / /.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303
 
[HttpException (0x80004005): Illegal character / /.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261
 
... this is, of course, caused by there being comments in the the project.json or other file after upgrading to bleeding edge version of DNX. There are three pieces of crucial information here that would have prevented these people from asking for my help:

- What the problem is (even if this was "illegal characters IN JSON FILE" would have been much clearer than "illegal character")
- Line information 
- File name(there can easily be > 1 json file)

**Comment by BrennanConroy** [comment]
How bleeding edge are we talking? https://github.com/aspnet/dnx/commit/6b0dc2bfeb79a6490f7613c8086c2d6de13a95a6 which should be in >= 11781 added better errors for json

**Comment by BrennanConroy** [comment]
Actually only > 11781

**Comment by muratg** [comment]
@troydai

**Comment by MattGal** [comment]
Yup, upgrading to 11855 definitely solves my line-number-related issues.   It'd be nicer to have a better error msg, but taking me directly to the offending comment is good enough.  (Except in packages.json, bower.json, etc, but that's a separate issue )
