### ISSUE TITLE
Add Startup class into an interface

### ISSUE THREAD

**Issue by prasannavl** [aspnet/dnx#1949]
Is there any particular reason why the Startup class, and its methods were not given as an interface? 
I find this usage to reflection to detect the startup path a bit concerning. 

```c#
public class Startup
{
     public void ConfigureServices(IServiceCollection services)
     {
     }

     public void Configure(IApplicationBuilder app)
     {
     }
}
```

This requires a memorization of the methods and parameters, while an interface would nicely derive them. 

The only advantage, if any that I see would be to remove any dependencies packages - which IMO really shouldn't matter, as this can easily be put into a separate package, with nothing but these basic interfaces, or into the Core package. I find the absence of a proper root for this `Startup` class to be little odd, and untidy.

**Comment by davidfowl** [comment]
The biggest reason is dependency injection. The Configure method can be dependency injected and an interface would complete block that. It the same for middleware.

Take a look at the Startup.cs in the mvc project template.

**Comment by davidfowl** [comment]
Closing this out as it doesn't belong on the DNX repository. If you have more questions, ask on aspnet/Home
