### ISSUE TITLE
DNX fails to restore some nuget packages

### ISSUE THREAD

**Issue by anfomin** [aspnet/dnx#1950]
I'm trying to add dependency to the [WindowsAzure.ServiceBus package](http://www.nuget.org/packages/WindowsAzure.ServiceBus/). Config.json:
```json
{
    "version": "1.0.0-*",

    "dependencies": {
        "WindowsAzure.ServiceBus": "2.6.7"
    },

    "commands": {
        "ConsoleApp2": "ConsoleApp2"
    },

    "frameworks": {
        "net45": { }
    }
}
```

Package manager log contains no error, however VS interface shows:
![2015-05-25 14 53 00](https://cloud.githubusercontent.com/assets/1905503/7795394/081097aa-02ee-11e5-850b-86571c2dfafd.png)

This bug reproduced on the latest DNX *dnx-clr-win-x86.1.0.0-beta5-11855*. When I switch to older 11682, package restored correctly.

**Comment by davidfowl** [comment]
There are 2 problems here. We have an issue with parsing nulls for versions in the lock file and the service bus package doesn't specify a version its dependencies.

**Comment by davidfowl** [comment]
@anfomin I pushed a fix for the lock file parsing, it'll take a while for the CI to pass but it won't fully resolve the issue. You should be able to work around this by doing the following in your `project.json`:

```JSON
{
    "version": "1.0.0-*",

    "dependencies": {
      "WindowsAzure.ServiceBus": "2.6.7",
      "Microsoft.WindowsAzure.ConfigurationManager": "3.1.0"
    },

    "commands": {
        "ConsoleApp2": "ConsoleApp2"
    },

    "frameworks": {
        "net45": { }
    }
}
```

This will override the broken dependency on `Microsoft.WindowsAzure.ConfigurationManager`
