### ISSUE TITLE
MissingMethodException on Microsoft.Net.Http.Server.WebListener

### ISSUE THREAD

**Issue by MaximRouiller** [aspnet/dnx#1951]
The machine does not have Visual Studio 2015.
Project created using the latest `generator-aspnet` and latest yeoman package.
`.dnx` folder completely deleted and completely reinstalled.

`dnu restore` executed. Package `Microsoft.Net.Http.Server` only have one version and it's `1.0.0-beta4`.

I run `dnx . web` / `dnx . kestrel` on the same port and I get the following:

![capture](https://cloud.githubusercontent.com/assets/209384/7800133/a4228852-02de-11e5-862a-3338982aaef8.PNG)

They are not running "at the same time". One after the other after the process is killed.

Here are the commands in my `project.json` file:

```json
"commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5002",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5002",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef": "EntityFramework.Commands"
    }
```

Thanks

**Comment by davidfowl** [comment]
Ca you file this on aspnet/Home

**Comment by MaximRouiller** [comment]
Yep. Will copy/paste.

**Comment by MaximRouiller** [comment]
Done.

https://github.com/aspnet/Home/issues/632
