### ISSUE TITLE
Servicing Wiki needs correction/update

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/dnx#1957]
https://github.com/aspnet/Home/wiki/Servicing
1. No reference to creating a file called _index.txt_ in the Servicing folder - can be figured out from the source but would be nice to mention it on the Wiki.
2. Format of file is incorrect - each line should begin with **nupkg** and not _nuget_.
3. Target for the redirection has to be fully qualified (this was unclear in the docs). So for example:
   _nupkg|SampleHelper|1.0.0|lib/dnx451/Samplehelper.dll=c://users/sujit/.dnx/packages/SampleHelper/1.0.1/lib/dnx451/SampleHelper.dll_
4. Does Servicing really support runtimes as well? As per the docs, you can have an entry starting with **dnx** to indicate an alternate runtime version, but I don't see that in the code (and it does not appear to work either).

**Comment by muratg** [comment]
@danroth27 Are we documenting Servicing feature?

cc @glennc
