### ISSUE TITLE
DTH: Protocol negotiation

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1961]

**Comment by troydai** [comment]
__Specification__

IDE and DTH follows the workflow defined in this spec to negotiate the communication protocol version.

The negotiation is initialized by a message sent by IDE:
```
HostID:      string
MessageType: string  /* == ProtocolVersion */
ContextID:   int     /* always 0, avoid context collusion */
PayLoad:     JSON token
```

Payload looks like
```
{
    "version": 1    /* an integer represents highest version  */
}
```

The __version__ represents the highest protocol version this IDE can support.

Once DTH receives the message and parse the prefer version, it returns the same message and payload with the __highest version__ it supports which is below or equal to IDE's prefer version.

IDE's behavior afterwards is undefined. It's up to the IDE to decide how to proceed should the DTH suggest version is not preferable. 

DTH will stay on the retruned __version__ of protocol afterwards until the end of its life-cycle or a new protocol negotiation. The protocol version is used across all contexts.

Protocol negotiation is not required. If the negotiation doesn't happen, DTH will stay on the version of protocol sent in the initialization message. If it doesn't support that version, it will stays on the highest protocol version below the given version.

**Comment by BillHiebert** [comment]
@davidfowl @muratg 

Note that the unit test host needs a similar feature. We talked about it but I don't think an official work item was created. I have the VS work done (same algorithm as for DTH).

**Comment by muratg** [comment]
@BillHiebert cc: @rynowak for the test host protocol negotiation feature. I believe he's working on that. Closing this one which only tracks DTH feature.
