### ISSUE TITLE
Including packages built for other frameworks adds cruft to .nuspec

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1962]
When including assemblies for other frameworks in my nupkg built by the DNX packaging system, I may use things like:

```
"net35": {
      "bin": {
        "assembly": "../../../build/foo.dll",
        "pdb": "../../../build/foo.pdb"
       }
    },
```

What I've noticed is that this produces entries in the nuspec that aren't needed and which produce undesired UI on tools for browsing the package.  

In the nuspec, it looks like:

``` xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework3.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework3.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework3.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework3.5" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.0-Client" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.0-Client" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.0-Client" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.0-Client" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
```

... which in turn translates into stuff like this in Nuget Package Explorer:

![image](https://cloud.githubusercontent.com/assets/7862010/7846032/c96876f2-046f-11e5-810a-7f43a971c197.png)

For these older frameworks, it is pretty impossible that DLLs like System and mscorlib would be missing without breaking the whole install.  It would be nice to not include these by default.

**Comment by davidfowl** [comment]
Do you have those dependencies declared in the top level section or per framework?

**Comment by MattGal** [comment]
I don't declare them at all actually.   For the other frameworks, the first snippet is literally it.  All dependencies specified exist purely under the dnxcore50 node.

**Comment by davidfowl** [comment]
Ah ok, its only adding those 4 assemblies. That's broken :smile:
