### ISSUE TITLE
TryGetProject should be optimized

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1971]
Today we spend a considerable amount of time parsing `project.json`:

![image](https://cloud.githubusercontent.com/assets/95136/7855387/113f660a-04d6-11e5-8923-da2a63541212.png)

**Comment by davidfowl** [comment]
The 3 things that are expensive:
- Microsoft.Framework.Runtime.ProjectFilesCollection..ctor()
- Microsoft.Framework.Runtime.Project.BuildTargetFrameworksAndConfigurations()
- Microsoft.Framework.Runtime.Project.PopulateDependencies()

The last one is a bunch of reflection that happens when we initialize LibraryDependencyType (totally unnecessary). I have a change to fix this.

@troydai We should consider making ProjectFilesCollection more lazy. Today we calculate all of the patterns up front even though you may never use them in an application (if you're precompiled for example).

ParseFrameworkName can be sped up to have a fast path for the known framework names and versions.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/dnx/commit/82f50f53059d0f7344b727f5dbfcd3a20b1e3daa

**Comment by troydai** [comment]
Analyzing log 2015/8/17:

I profiled the start up time of a standard Web application created from starter template. The time is profiled of two scenarios:
1) Web Listener;
2) Create an clean Program class and start as an empty command line application.

In both scenarios, the `DefaultHost.ctor` code pa

**Comment by troydai** [comment]
Analyzing log 2015/8/17:

I profiled the start up time of a standard Web application created from starter template. The application is pre-restored, but not published. The time is profiled of two scenarios:
1) Web Listener;
2) Create an clean Program class and start as an empty command line application.

Here's the observation:
1) Look at the inclusive time spent on each assembly, `Microsoft.CodeAnalysis.*.dll` account for lion share of the time
![image](https://cloud.githubusercontent.com/assets/1329240/9310024/1c22bbc2-44c2-11e5-9b2c-3857c5faf633.png)
![image](https://cloud.githubusercontent.com/assets/1329240/9310029/2889d4ea-44c2-11e5-952d-f0fd75a51563.png)

2) The code path of `DefaultHost.ctor` which comprised of the methods listed in previous comment is not heavy in these two scenarios. It only represent 5.5% (Console) and 1.64% (Web) of the time:
![image](https://cloud.githubusercontent.com/assets/1329240/9310142/c82d9252-44c2-11e5-8623-f8866697b8bb.png)
![image](https://cloud.githubusercontent.com/assets/1329240/9310144/d128a842-44c2-11e5-8b6a-e008f4c06aba.png)

3) Of the 5.5% time spent in Console app, `LockFileReader.Read` took up 2.47% which comprised of JSON deserialization and `LockFile` instance creation. It is consider one of the place can be potentially optimized. 

4) `Logger.TraceInformation` took up to 2.82% of time in web listener scenarios. Doesn't show up when `DNX_TRACE=0`.

**Comment by anurse** [comment]
Compilation is big when there is stuff to compile, but when publishing `--no-source` we need to ensure we have fast start-up time.

**Comment by troydai** [comment]
Yes. That's another scenario to profile.

**Comment by anurse** [comment]
I think we'll find DefaultHost (and friends) makes up a much bigger fraction of that scenario ;)

**Comment by davidfowl** [comment]
This was fixed
