### ISSUE TITLE
The type or namespace name 'MailMessage/SmtpDeliveryMethod/SmtpClient' could not be found in   ProjectName.DNX Core 5.0

### ISSUE THREAD

**Issue by Devansh3790** [aspnet/dnx#1972]
I am working on ASP.NET 5 & MVC 6 Website and i wanted to send mail.
For that purpose i write the following method:

//Send mail method

        private static void SendMail(MailMessage mailMessage)
        {
            var networkCredential = new NetworkCredential("", "");
            mailMessage.IsBodyHtml = true;
            // set your smtp server and smtp port 3535
            var smtpClient = new SmtpClient("", 25);

            smtpClient.EnableSsl = false;
            smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Timeout = 400000; // Set timeout
            smtpClient.Credentials = networkCredential;
            smtpClient.ServicePoint.MaxIdleTime = 1;
            smtpClient.Send(mailMessage);
        } 

when I Press F5 for run project its give me these kind of Error

![error](https://cloud.githubusercontent.com/assets/12626121/7857579/19807984-054f-11e5-9835-17c596c6dfe9.PNG)

Note : Intillsence does not show any error.

**Comment by GuardRex** [comment]
It's not available yet. See: https://github.com/dotnet/corefx/issues/1006

**Comment by BrennanConroy** [comment]
Intellisense will show up if you select DNX Core 5.0 from the drop-down in the top left.

**Comment by davidfowl** [comment]
You can remove dnxcore50 from project.json if you don't need to run on core clr. Otherwise there's not much else you can do other than wait for the .net team to port the package

**Comment by GuardRex** [comment]
> Otherwise there's not much else you can do other than wait for the .net team to port the package

Or use my nasty code guides to whip up something to tide you over. The code samples I posted at https://github.com/dotnet/corefx/issues/1006 work on core clr.
