### ISSUE TITLE
DNX no longer honors ref\any during restore.

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#1974]
Starting with today's build DNX is no longer honor's ref\any & lib\any.  This is a regression and needs to be fixed.  We rely on "any" semantics in many of our packages because we don't want the packages to encode any TFM dependency on in lib or ref since these libraries have no such dependency and only depend on the API they call out in package dependencies.

/cc @anurse

**Comment by muratg** [comment]
@davidfowl was a decision reached on this?  

cc @danroth27, this might need to happen in beta5.
