### ISSUE TITLE
Possible race in DTH causes references to be lost

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1975]
@davidfowl and I were looking at this on my desktop. I've experienced it before (@loudej had seen it with me previously too).

I was working in the aspnet/Localization repo and edited `global.json` to bring in source for `TestHost` and then xUnit. As soon as the xUnit source came in, I started getting thousands of errors in the Error List RE the xUnit project and Core CLR. We opened another instance of VS with just the xUnit sln open and the errors were there too. We saw in the DTH trace that references for the project were not being returned, although the Solution Explorer showed all dependencies were successfully resolved.

It fixed itself after a forced manual restore and/or a build, not sure which. We didn't see it repro again after that, in either solution.

**Comment by muratg** [comment]
Ugh.  cc @troydai

**Comment by davidfowl** [comment]
Closing
