### ISSUE TITLE
"dnvm install default" fails with nuget.org returning HTTP 400

### ISSUE THREAD

**Issue by MichaelKetting** [aspnet/dnx#1977]
I have set up a fresh system (Windows 10, VS2015RC) with:
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

When I run "dnvm install latest" the installation succeeds. When I run "dnvm install default", the installation fails with:

```
Downloading dnx-clr-win-x86.default from https://www.nuget.org/api/v2
Unable to download package: The remote server returned an error: (400) Bad Request.
At C:\Users\mk\.dnx\bin\dnvm.ps1:559 char:13
+             throw "Unable to download package: {0}" -f $Global:downlo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to downl...0) Bad Request.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to download package: The remote server returned an error: (400) Bad Request.
```

According to "dnvm", I'm using 
".NET Version Manager v1.0.0-beta6-10380"

It looks like this is related to some particular setup. I have a separate, older system (Windows 8.1, VS2015RC), which I updated to beta6 via "dnvm update-self", and there, "dnvm install default" works and gives me:

```
Downloading dnx-clr-win-x86.1.0.0-beta4 from https://www.nuget.org/api/v2
Installing to C:\Users\mk\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4
Adding C:\Users\mk\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin to process PATH
Native image generation (ngen) is skipped. Include -Ngen switch to turn on native image generation to improve application startup time.
```

Any ideas what I'm doing wrong? 

Best regards, Michael

**Comment by davidfowl** [comment]
Can you move this bug to aspnet/dnvm

**Comment by MichaelKetting** [comment]
Thanks for the tip! :smile:
