### ISSUE TITLE
feature request: "dnvm use default "  not necessary by default

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/dnx#1978]
From: Rowan Miller 
To: Rick Anderson; Glenn Condron; Murat Girgin
it seems like we already have the fact that a project is tied to a version of the framework reflected in global.json. Have we considered that the command line should just pick this up unless you explicitly state you want to use something other than what is specified.

**Comment by glennc** [comment]
Wrong repo, and dup of: https://github.com/aspnet/dnvm/issues/271

Closing in favor of that one.
