### ISSUE TITLE
Assembly.Load should erase version info on full CLR

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#1979]
https://github.com/aspnet/dnx/commit/e9b81446ec1931e08cbf125a13525c679d961528 broke things.

**Comment by davidfowl** [comment]
@muratg I'm not sure this matters anymore. This was the bug https://github.com/aspnet/dnx/commit/8ac58f641dba513e1b367c38a332adc08e2a9b63 that was causing other problems. I'll see if we still need this in beta5

**Comment by muratg** [comment]
@davidfowl closing this for now. Reopen if there's remaining work.
