### ISSUE TITLE
Dedup NuGet feeds before doing "dnu restore"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#1982]
Reported by @DamianEdwards 

If we have both
`https://www.nuget.org/api/v2/`
and
`https://nuget.org/api/v2/`
in NuGet.config, they are treated as two different feeds and `dnu restore` doubles the workload.

**Comment by davidfowl** [comment]
I'm not sure we should do this. We can't assume things like this. @DamianEdwards fix your configuration.
