### ISSUE TITLE
Version mismatched lock file shouldn't throw.

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#1985]
Source https://github.com/aspnet/Home/issues/644

Should a version mismatched lock file presented to DNX, it shouldn't throw exception. Simply invalid the lock file and return null.

**Comment by davidfowl** [comment]
@muratg This is a regression that I think should have been scheduled in beta5.

/cc @ChengTian

**Comment by muratg** [comment]
Approved for Beta 5.

**Comment by ChengTian** [comment]
Cannot reproduce with latest DNX
