### ISSUE TITLE
Capture details of which feed a package was restored from to aid in debugging

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#1988]
Right now, once a package is on disk in the packages folder, there's no easy way to tell which feed it came from. This can make it very hard to debug why a particular package exists on disk when multiple feeds are being used (which we do all the time).

Suggest we write a simple text file to the package folder (the actual that contains a specific package version) the details of the feed it was restored from, e.g. feed.txt. It would contain the URL of the feed and the date/time it was restored.

**Comment by serialseb** [comment]
one of the issues we had with system-wide packages on openwrap back in the old days was that one. We tried solving it by caching packages per feed and always having the original source feed persisted alongside the current version of the package. Not sure if it helps but thougth i'd share.
