### ISSUE TITLE
DNX never creates an entry point

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#1997]
The compiled assemblies DNX/dnu creates never have an actual program entry point. By entry point I mean an entry point at the IL level (.entrypoint). CoreRun or CoreConsole will not work on such assemblies.

The build command should provide an option to look for a "static void Main()" and create one. The new console app project template in visual studio should also make use of it.

**Comment by borgdylan** [comment]
DNX console applications are DLLs not EXEs and require the DNX to run. They cannot be run like standard console application that do have an entry point at the IL level.

**Comment by akoeplinger** [comment]
I just confirmed that decompiling a DNX-built console app and adding the `.entrypoint` IL and running it through ilasm produces an assembly that can be run with corerun.exe.

**Comment by xanather** [comment]
@borgdylan I am aware of that. An entry point however can easily be applied to a .dll with no downsides. CoreRun.exe/CoreConsole.exe requires this to run .NET Core applications. If the developers don't want assemblies produced by DNX to be consumed by CoreRun then I guess that will be the case, but as I said there is no downside if there is a "static void Main()" existing and .entrypoint can be applied.

**Comment by borgdylan** [comment]
But if one does a console app meant to be run by DNX on coreclr, t would still not need an entry pint at teh IL level as that would be in the dnx loader.

**Comment by am11** [comment]
:+1: to be able to execute binary via CodeRun.

**Comment by davidfowl** [comment]
Vote on this https://github.com/dotnet/roslyn/issues/1081

**Comment by xanather** [comment]
@davidfowl While I think that linked issue would be beneficial in general, what does that have to do with supporting an optional command which looks for and decorates a static Main method in the Program class (if it exists)? The people who would like DNX to support such things are people who are after using CoreRun or other bootstrappers that look for a traditional .entrypoint. I feel more and more like DNX is not designed for building end-user apps and is for cloud/server only.

**Comment by borgdylan** [comment]
@xanather you are forgetting that dnx apps are run using the dnx command, not by using CoreRun directly.

**Comment by davidfowl** [comment]
@xanather You can just run dnx.exe foo.dll to get the same effect as CoreRun. The bigger problem is that nothing is copying the closure of assemblies to a single folder. 

Just use `dnu publish --no-source` and that will give you something runnable. I'm not exactly sure why you to build with dnu and run with CoreRun.

**Comment by xanather** [comment]
@davidfowl That's a good point. Right now you do need to manually copy and get all the CoreFX/CoreCLR libs together. Maybe when there is a tool which does this and produces the absolute minimum to get the app working in a single directory for a single target platform (I heard on gitter someone on the .NET Core team is working on one) then I think it would be worthwhile to get DNX/DNU to produce .entrypoint's. Who knows though, such a tool may not need .entrypoint anymore and could work like DNX.

**Comment by akoeplinger** [comment]
@xanather at least on Unix, you should be able to modify the corerun source [here](https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp#L285-L287) to point it at the type+method name of the main method and it should then run dnx built assemblies.

**Comment by davidfowl** [comment]
We added support for emitting an entrypoint https://github.com/aspnet/dnx/issues/2754
