### ISSUE TITLE
1.0.0-beta6-11941 is unable to run on IIS Express in Visual Studio 2015 RC and DNX

### ISSUE THREAD

**Issue by regionbbs** [aspnet/dnx#1999]
I am downloaded 1.0.0-beta6-11941 in my environment, and create a new Web application from Visual Studio 2015 RC using Web Site Template, when I run it on IIS Express, the error message has shown:
![2015-6-1 01-33-12](https://cloud.githubusercontent.com/assets/1799428/7906790/3d6878d0-0863-11e5-8c16-c43118e87b79.png)

It also has error when running on DNX:
![2015-6-1 01-32-59](https://cloud.githubusercontent.com/assets/1799428/7906802/59fdc1da-0863-11e5-96b4-c72a30b55c9f.png)

**Comment by davidfowl** [comment]
Sure, it is. You just need to make sure you update your packages because beta4 and beta6 are incompatible.
