### ISSUE TITLE
Where did Assembly Neutral Interfaces go?

### ISSUE THREAD

**Issue by henkmollema** [aspnet/dnx#2003]
I know it's been a while, but somehow today I wondered again why ANI was somewhat silently removed (https://github.com/aspnet/dnx/commit/5f8bf5614d04b82dc69aedf48a5b2f832f00ca8f). Is there any particular reason for it?

cc @davidfowl

**Comment by pranavkm** [comment]
Since the feature required runtime support (via resource discovery), it was problematic to support it on desktop (Net45). The last time this was discussed, the plan was to revive this if we figured out a a more robust way to support this across all runtimes.

**Comment by henkmollema** [comment]
That makes sense, thanks!

**Comment by lilith** [comment]
Please bring back ANI. How are OSS libraries ever going to start being compatible with one another without this? We need loose coupling in .NET, and badly.
