### ISSUE TITLE
With produce outputs on build, errors from DNX are not in the right format

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#2025]
Clean install : D14Rel.23004 + Wte.Main.2015-06-04_b320

**REPRO STEPS** 
1. Create empty DNX class library app : KClassLibrary3 (4.5.1)
2. Paste the following in Class1.cs
public int MethodA()
{
}
3. Turn on "Produce outputs on build"
4. Right-click KClassLibrary3 in solution explorer > Build
 
**ACTUAL**
Errors are not in the right format -- see the part in bold below
 
_Error list with "Build Only" filter_
 
![image](https://cloud.githubusercontent.com/assets/8246794/8015557/724f3646-0b8e-11e5-8851-f6dc4a3fb73a.png)

 
_Output window_
1>------ Build started: Project: KClassLibrary3, Configuration: Debug Any CPU ------
1> C:\Users\balach\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11911\bin\dnx.exe --appbase "c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3" "C:\Users\balach\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11911\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" pack "c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3" --configuration $(Configuration --out "..\..\artifacts\bin\KClassLibrary3"
1> Microsoft .NET Development Utility CLR-x86-1.0.0-beta5-11911
1> Building KClassLibrary3 for DNX,Version=v4.5.1
1> Using Project dependency KClassLibrary3 1.0.0
1> Source: c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3\project.json
1> Using Package dependency System.Collections 4.0.10-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Collections\4.0.10-beta-22913
1> File: lib\net45\System.Collections.dll
1> Using Package dependency System.Linq 4.0.0-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Linq\4.0.0-beta-22913
1> File: lib\net45\System.Linq.dll
1> Using Package dependency System.Threading 4.0.10-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Threading\4.0.10-beta-22913
1> File: lib\net45\System.Threading.dll
1> Using Package dependency Microsoft.CSharp 4.0.0-beta-22913
1> Source: C:\Users\balach\.dnx\packages\Microsoft.CSharp\4.0.0-beta-22913
1> Using Package dependency System.Runtime 4.0.20-beta-22231
1> Source: C:\Users\balach\.dnx\packages\System.Runtime\4.0.20-beta-22231
1> Using Package dependency System.Threading.Tasks 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Threading.Tasks\4.0.10-beta-22816
1> File: lib\net45\System.Threading.Tasks.dll
1> Using Package dependency System.Dynamic.Runtime 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Dynamic.Runtime\4.0.10-beta-22816
1> File: lib\net45\System.Dynamic.Runtime.dll
1> Using Package dependency System.Linq.Expressions 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Linq.Expressions\4.0.10-beta-22816
1> File: lib\net45\System.Linq.Expressions.dll
1> Using Package dependency System.ObjectModel 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.ObjectModel\4.0.10-beta-22816
1> File: lib\net45\System.ObjectModel.dll
1> Using Package dependency System.Reflection 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Reflection\4.0.10-beta-22816
1> File: lib\net45\System.Reflection.dll
1> Using Package dependency System.IO 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.IO\4.0.10-beta-22816
1> File: lib\net45\System.IO.dll
1> Using Package dependency System.Reflection.Primitives 4.0.0-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Reflection.Primitives\4.0.0-beta-22816
1> File: lib\net45\System.Reflection.Primitives.dll
1> Using Package dependency System.Text.Encoding 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Text.Encoding\4.0.10-beta-22816
1> File: lib\net45\System.Text.Encoding.dll
1> Using Assembly dependency framework/mscorlib 4.0.0.0
1> Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll
1> Using Assembly dependency framework/System 4.0.0.0
1> Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll
1> Using Assembly dependency framework/System.Core 4.0.0.0
1> Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(151,5): error : c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3\Class1.cs(16,20): error CS0161: 'Class1.MethodA()': not all code paths return a value
1> Building KClassLibrary3 for DNXCore,Version=v5.0
1> Using Project dependency KClassLibrary3 1.0.0
1> Source: c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3\project.json
1> Using Package dependency System.Collections 4.0.10-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Collections\4.0.10-beta-22913
1> File: lib\contract\System.Collections.dll
1> Using Package dependency System.Linq 4.0.0-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Linq\4.0.0-beta-22913
1> File: lib\contract\System.Linq.dll
1> Using Package dependency System.Threading 4.0.10-beta-22913
1> Source: C:\Users\balach\.dnx\packages\System.Threading\4.0.10-beta-22913
1> File: lib\contract\System.Threading.dll
1> Using Package dependency Microsoft.CSharp 4.0.0-beta-22913
1> Source: C:\Users\balach\.dnx\packages\Microsoft.CSharp\4.0.0-beta-22913
1> File: lib\contract\Microsoft.CSharp.dll
1> Using Package dependency System.Runtime 4.0.20-beta-22231
1> Source: C:\Users\balach\.dnx\packages\System.Runtime\4.0.20-beta-22231
1> File: lib\contract\System.Runtime.dll
1> Using Package dependency System.Threading.Tasks 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Threading.Tasks\4.0.10-beta-22816
1> File: lib\contract\System.Threading.Tasks.dll
1> Using Package dependency System.Dynamic.Runtime 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Dynamic.Runtime\4.0.10-beta-22816
1> File: lib\contract\System.Dynamic.Runtime.dll
1> Using Package dependency System.Linq.Expressions 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Linq.Expressions\4.0.10-beta-22816
1> File: lib\contract\System.Linq.Expressions.dll
1> Using Package dependency System.ObjectModel 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.ObjectModel\4.0.10-beta-22816
1> File: lib\contract\System.ObjectModel.dll
1> Using Package dependency System.Reflection 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Reflection\4.0.10-beta-22816
1> File: lib\contract\System.Reflection.dll
1> Using Package dependency System.IO 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.IO\4.0.10-beta-22816
1> File: lib\contract\System.IO.dll
1> Using Package dependency System.Reflection.Primitives 4.0.0-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Reflection.Primitives\4.0.0-beta-22816
1> File: lib\contract\System.Reflection.Primitives.dll
1> Using Package dependency System.Text.Encoding 4.0.10-beta-22816
1> Source: C:\Users\balach\.dnx\packages\System.Text.Encoding\4.0.10-beta-22816
1> File: lib\contract\System.Text.Encoding.dll
**1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(151,5): error : c:\users\balach\documents\visual studio 2015\Projects\KClassLibrary3\src\KClassLibrary3\Class1.cs(16,20): error CS0161: 'Class1.MethodA()': not all code paths return a value
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(151,5): error : Build failed.**
1> 0 Warning(s)
1> 2 Error(s)
1> Time elapsed 00:00:02.5300458
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by davidfowl** [comment]
Did something change in the msbuild parsing logic? AFAIK we haven;t change this recently. Does it repro in the VS RC?

**Comment by balachir** [comment]
Does not reproduce with VS 2015 RC. Here's what we get with RC. @BillHiebert , any thoughts on whether this due to an msbuild change?

...
1>      Source: C:\Users\balach\.dnx\packages\System.Reflection.Primitives\4.0.0-beta-22816
1>      File: lib\contract\System.Reflection.Primitives.dll
1>    Using Package dependency System.Text.Encoding 4.0.10-beta-22816
1>      Source: C:\Users\balach\.dnx\packages\System.Text.Encoding\4.0.10-beta-22816
1>      File: lib\contract\System.Text.Encoding.dll
**1>c:\users\balach\documents\visual studio 2015\Projects\ClassLibrary5\src\ClassLibrary5\Class1.cs(16,20): error CS0161: 'Class1.MethodA()': not all code paths return a value**
1>  Build failed.
1>      0 Warnings(s)
1>      2 Error(s)
1>  Time elapsed 00:00:01.1792167
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

![image](https://cloud.githubusercontent.com/assets/8246794/8039577/aa596826-0dbf-11e5-8a5c-555e9962b773.png)

**Comment by balachir** [comment]
This was fixed in the tooling side. TFS #1183903
