### ISSUE TITLE
dnu publish get ambiguous error when dependency package source is on global.json

### ISSUE THREAD

**Issue by Bartmax** [aspnet/dnx#2027]
Having a dependency in a project.json that has the source added in global.json `projects` results on ambiguous error when publishing.

```
System.InvalidOperationException: The project name 'CustomHttpsPort' is ambiguous between the following projects:
c:\pt\approot\src\CustomHttpsPort
c:\Repos\Community\Bartmax\CustomHttpsPort\src\CustomHttpsPort
```

This is what I'm doing
project.json of the project I want to publish:

```
"dependencies": {
    ...
    "CustomHttpsPort": "1.0.0-beta5-*"
}
```

global.json on the solution level:

```
{
    "projects": [ "src", "test", "c:/Repos/Community/Bartmax/CustomHttpsPort/src" ],
    "sdk": {
        "version": "1.0.0-beta5-11911"
    }
}
```

publish command:

```
dnu publish -o c:\pt
```

If I use --no-source it build sucessfully.
both commands executed on an empty C:\PT folder.

**Comment by gavdraper** [comment]
Getting this same issue both locally and when deploying to Azure although in my case the project I'm publishing has no dependancies to other projects in the global.json paths but other projects that I'm not publishing do.

**Comment by gavdraper** [comment]
Actually on beta6 this issue seems to solve itself if I rename the src folder and entry in global.json to source like this...

"projects" : ["Src","Test"],

to

"projects" : ["Source","Test"],

I guess there must be some stuff going on internally with a src folder which was conflicting with my source folder?
