### ISSUE TITLE
dnu error (red) color is too dark

### ISSUE THREAD

**Issue by Bartmax** [aspnet/dnx#2028]
doing something like `dnu publish hkjh` returns `Unable to locate project.json.` in a very dark red which is hard to read on powershell (black background).

**Comment by davidfowl** [comment]
The new CLI fixes this

**Comment by Bartmax** [comment]
maybe we can make it more bright ?

in this screen, `#3 [bart]` is perfectly readable, `no executable found`  is not.

![image](https://cloud.githubusercontent.com/assets/3386797/14702861/3af55cd8-0783-11e6-984e-f4dc4e5f8e7c.png)
