### ISSUE TITLE
Design-time facades shouldn't be added to the nuspec for Full .NET

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#2031]
```JSON
{
  "dependencies": {
    "System.Collections.Immutable": "1.1.36"
  },
  "frameworks": {
    "net45": {
      "dependencies": {
        "System.Collections": "4.0.0.0"
      }
    }
  }
}
```
The reference to `System.Collections` is required to build on DNX, but if you try to install the resulting nupkg into a net45 project, you'll get the following error.

> Multiple assemblies with equivalent identity have been imported: 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Collections.dll'. Remove one of the duplicate references.

The workaround is to declare it as a built-time dependency.

```JSON
{
  "System.Collections": { "version": "4.0.0.0", "type": "build" }
}
```

**Comment by herecydev** [comment]
May be relate to [what I raised](https://github.com/aspnet/dnx/issues/2029) just hours ago.

**Comment by Eilon** [comment]
Hmm but is this actually correct? Isn't the reference needed? Is the package itself just broken?

**Comment by davidfowl** [comment]
The unfortunate thing about this is that the msbuild based projects fail instead of noop. I would love to get that fixed instead of mimicking that behavior in the dnx

**Comment by jonesopolis** [comment]
thanks for the fix brice. Was killing me.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#578
