### ISSUE TITLE
runtime returns incorrect framework short name when netcore451 is specified in project.json

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2032]
See this issue for full details and repro: https://github.com/aspnet/Tooling-Internal/issues/344

**Comment by anurse** [comment]
`win81` is the correct normalized short-form name for `.NETCore, Version=v4.5.1`... The tooling should be using long-form names everywhere since they are unambiguous.

**Comment by abpiskunov** [comment]
How do we get this correct-long-form name for each framework moniker ? We take monikers that runtime sends us and don't have our own name resolution logic.

**Comment by abpiskunov** [comment]
In any case , runtime should be consistent with the info it sends us.

**Comment by davidfowl** [comment]
We should fix this

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#577
