### ISSUE TITLE
Why don't Console Apps use a Startup Class

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/dnx#2038]
The Startup class pattern is great for setting up everything, including the dependency injection, while keeping it isolated from the rest of the application.

Why don't console apps optionally instantiate a Startup class, if it exists, and call the ConfigureServices and Configure methods.

The required code is not large.  Here is my first attempt which seems to work, but assumes that the Startup class exists.  You could even constructor inject arbitrary dependencies into Main.
```c#
    public class Program
    {
        private readonly IServiceProvider _hostServiceProvider;

        public Program(IServiceProvider serviceProvider)
        {
            _hostServiceProvider = serviceProvider;
        }

        public void Main(string[] args)
        {
            var app = StartupApplication();
        }

        /// <summary>
        /// Initializes the application by 
        /// </summary>
        private ApplicationBuilder StartupApplication()
        {
            var services = new ServiceCollection();
            AddHostServices(services);

            var diagnosticMessages = new List<string>();

            // create a service provider with the HostEnvironment.
            var hostingEnv = new HostingEnvironment();
            services.AddInstance<IHostingEnvironment>(hostingEnv);
            var serviceProvider = services.BuildServiceProvider();

            var loader = new StartupLoader(serviceProvider, hostingEnv);
            var startup = loader.LoadMethods(typeof(Startup), diagnosticMessages);

            var app = new ApplicationBuilder(serviceProvider);
            app.ApplicationServices = startup.ConfigureServicesDelegate(services);
            startup.ConfigureDelegate(app);

            return app;
        }

        private void AddHostServices(ServiceCollection services)
        {
            // add the host services to the collection
            var manifest = _hostServiceProvider.GetService<IServiceManifest>();
            if (manifest != null)
            {
                foreach (var service in manifest.Services)
                    services.AddTransient(service, sp => _hostServiceProvider.GetService(service));
            }
        }
    }
```

**Comment by davidfowl** [comment]
> Why don't console apps optionally instantiate a Startup class, if it exists, and call the ConfigureServices and Configure methods.

The Startup class is a web convention.

> The required code is not large. Here is my first attempt which seems to work, but assumes that the Startup class exists. You could even constructor inject arbitrary dependencies into Main.

It actually is large. The dnx does not depend on any of those services you have in your application. The Program.Main is the lowest layer in the stack and has no dependencies on anything else. 

But as you discovered, you could totally build it on top of the dnx. It's just a layering issue. We don't want dependencies in the lowest layer of the stack. Higher level things like Hosting build on top of that and provide the added functionality

**Comment by matthewDDennis** [comment]
> The Startup class is a web convention.

Why should this be a Web Convention.  It is a powerful pattern that makes DI, and a lot of other great features, available to the programmer. When I created 'vNext' Console app, my default expectation was that I would easily be able to use the vNext features.  There is no reason other than a Web mindset that makes this Web Only.  Its a Pattern or Convention that promotes good programming practices and reduces the boiler-plate code a developer needs to write.

>It actually is large. The dnx does not depend on any of those services you have in your application. The Program.Main is the lowest layer in the stack and has no dependencies on anything else. 

My implementation probably pulls in more stuff than is required.  I'm sure with a little thought, most or all of the extra dependencies could be removed.

IMHO, I think this would be a powerful addition.

**Comment by smudge202** [comment]
I agree with both points. I don't think DNX should grow in order to support conventions such as the `Startup` class, but it is a very nice pattern. It's why we made [Compose](https://github.com/smudge202/compose) and why I'm sure many other such frameworks will appear. It simply doesn't belong in DNX itself, but it doesn't mean you can't use it.

**Comment by leus** [comment]
A web application consisting of different class libraries may greatly benefit from this (for example, having dnx commands in a different class library that runs every night loading data, etc. using the same context and configuration than the web application would be a big help)

**Comment by davidfowl** [comment]
Closing this, we can expose a library that does this.
