### ISSUE TITLE
dnx sends incorrect diagnostics (recommend atleast investigating this for beta5)

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#2044]
I talked to @troydai  about this issue.

Right now, as part of 'Build', VS sends 'RefreshDependencies' first and then send 'GetDiagnostics'. I am experimenting a change not to send 'RefreshDepdenencies' , I have seen that it substantially improves performance (Mvc which has 76 projects takes 6 seconds on my machine for build with the change, before it takes 15 seconds).

However, there is an issue in one scenario, if I edit project.json and remove/add a dependency and immediately do Ctlr + Shift + B , I see incorrect diagnostics from build. 

If I build again , the diagnostic information is corrected. If instead of doing Ctlr + Shift + B, I hit save which starts a restore and then to a build (which waits for restore), I don't see the issue.

I shared with Troy the messages that we get from DTH, we need to at least understand the issue for beta5 and can perhaps take a fix if it's less risky for the timing.

**Comment by muratg** [comment]
Is there still issues with this? @troydai
