### ISSUE TITLE
Clean up dnx.mono.managed build

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#2045]
There's a bit of cleanup we need to do:

1. Delete this file: https://github.com/aspnet/dnx/blob/dev/src/dnx.mono.managed/makefile (I talked to @davidfowl and it isn't used anymore)

2. Add the "Servicing" attribute to the assembly. It's not actually needed in Mono but then it's less stuff to exclude in the post-build verification. The build for this file is [here](https://github.com/aspnet/dnx/blob/dev/makefile.shade#L177-L183). Need to add the attribute as defined [here](https://github.com/aspnet/dnx/blob/dev/src/dnx.coreclr.managed/Properties/AssemblyInfo.cs).

3. Ensure the right version attributes are on it. It is missing the `AssemblyFileVersionAttribute` and `AssemblyInformationalVersionAttribute` attributes. Need to make sure this is done the same way as it's done for other assemblies. Maybe the CI does it automatically or something... I think @victorhurdugaci worked on that.

**Comment by davidfowl** [comment]
@Eilon do we need this?

**Comment by Eilon** [comment]
Probably not. None of this stuff will exist, right?

**Comment by davidfowl** [comment]
Nope
