### ISSUE TITLE
Add servicing attribute to a few Microsoft.Framework.* assemblies

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#2046]
These assemblies don't have it:

1. Microsoft.Framework.ApplicationHost.dll
2. Microsoft.Framework.Runtime.Caching.dll
3. Microsoft.Framework.Runtime.Compilation.DesignTime.dll

It's not actually needed on these assemblies as far as I know (because they ship in the DNX) but then it's less stuff to exclude in the post-build verification.

**Comment by Eilon** [comment]
@ajaybhargavb this is ever-so-slightly related to the Package Verifier work you're doing. These assemblies have been renamed since I logged this bug, but please make sure when you enable the package verifier in this repo that we don't miss any assemblies.

**Comment by muratg** [comment]
@ajaybhargavb is Caching pending the change?

**Comment by ajaybhargavb** [comment]
No. That package no longer exists. It was merged into something else.
