### ISSUE TITLE
Running program with DNX on Minnow board MAX with Windows IoT Core

### ISSUE THREAD

**Issue by hpaiemen** [aspnet/dnx#2048]
Hi,
I'm trying to run a small application on a Minnow board MAX with Windows IoT Core on it. It's a pretty basic application that consist of looping on string manipulation with basic math operations to bench performance of the garbage collector on different platforms. I use the "dnu publish" tool to create a package that can be deploy on Windows platform (I use CoreCLR v1.0.0-beta6-12005 x86 runtime and its been "publish" from a standard Windows 7 desktop).

After using ftp to put my package on the Minnow board, I use powershell remotely to exec a batch file to run dnx with proper parameters on the IoT device. Here's the error I get from my powershell:

"dnx.onecore.dll could not be loaded. Last error: 126"

I successfully run my program on different Windows 7 machine (Windows 7 Embedded also) with no problem what so ever. I thought maybe the one cored machines were not supported yet, but really I have no clue.

Thx for your help.

**Comment by moozzyk** [comment]
This is on my task list - we need to update CI agents to produce OneCore versions. I am trying to confirm that we can build for one core on Windows 8.1 the agents are running on. 

@hpaiemen - if you feel adventurous you can try building your own runtime with support for one core. You need to have Windows 10 SDK installed on the machine and then when you run build.cmd from the root of the dnx repo you should get dnx.onecore.dll. As pointed above - I don't know if it works on non-Windows 10 machine yet (I am currently running build 10074 and Windows 10 SDK 10069)

**Comment by hpaiemen** [comment]
@moozzyk - I tried to build my own runtime like you suggest on Windows 10 Insider preview build 10074 with Win 10 SDK 10069 installed but I get an error while building (actually it looks like a single missing assembly) : 

[...]\dnx-dev\src\Microsoft.Framework.Runtime\PatternGroup.cs(8,27): error CS0234: The type or namespace name 'FileSystemGlobbing' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)

**Comment by moozzyk** [comment]
@hpaiemen - are you using beta4 to build this (dnvm list)? If you do, I think you may need to use a later (latest?) version - e.g. from our dev feed `dnvm install latest -unstable`

**Comment by hpaiemen** [comment]
@moozzyk - I use clr x86 1.0.0-beta6-12005 already, but I'm not sure to understand well : I must use a runtime to build a runtime ? This is the output of "dnvm list":

Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
       1.0.0-beta4       clr     x64          C:\Users\DaWin10\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\DaWin10\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\DaWin10\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\DaWin10\.dnx\runtimes
  *    1.0.0-beta6-12005 clr     x86          C:\Users\DaWin10\.dnx\runtimes default

I installed beta6 a couple days ago, but the beta4 versions, I think, were install while running build.cmd...

**Comment by anurse** [comment]
It sounds like you didn't get all the submodules. Try running `git submodule update --init` from the root of your clone of the aspnet/dnx repo.

**Comment by moozzyk** [comment]
build.cmd should get/update submodules...
on the other hand. This path

C:\Users\DaWin10.dnx\runtimes

Looks wrong. @muratg - I vaguely remember someone reported a malformed .dnx folder name before - do you remember?

**Comment by hpaiemen** [comment]
Sorry for that, there really is a `\` between `DaWin10` and `.dnx` I just checked it out (probably a bad copy-paste). I tried `git submodule update --init` like @anurse suggested but I got the same error as before.

**Comment by moozzyk** [comment]
@hpaiemen - Can you share the entire build output?

**Comment by hpaiemen** [comment]
https://www.dropbox.com/s/0mf4cj4q490hkry/buildOutput.zip?dl=0 : a link on a zip file containing piped output of the console while executing build.cmd and a paste of the actual console output (in which the error showed up).

**Comment by moozzyk** [comment]
@hpaiemen Unfortunately I don't know why you get the errors when building the dev branch. However, I upgraded the CI agents over the weekend and the next build should contain one core binaries. Stay tuned.

**Comment by moozzyk** [comment]
@hpaiemen - the latest build now contains onecore binaries.
