### ISSUE TITLE
Add user-specific native library loading support

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2054]
Currently it is not possible to specify custom native library loading. Extending the current extensibility framework and supporting it in DNX would be helpful. Might involve extending IAssemblyLoaderContainer to support adding a different type of interface container which is used for native library loading just like https://github.com/aspnet/dnx/blob/32358ec9b8970070ff77cbc5beef28c13e3ab09b/src/Microsoft.Framework.Runtime.Abstractions/IAssemblyLoader.cs?

Adding another extension method which will invoke the platform-specific native library load function and return a IntPtr (not necessary though) would be helpful for this too. Similar to what is discussed here https://github.com/dotnet/coreclr/issues/937.

**Comment by xanather** [comment]
Is this something that may be added in the future? It's really needed if people want to consume native libraries while using DNX and I think would be straight forward to implement.

For example, I cannot consume OpenAL 1.1 library (which has completely identical API's on multiple platforms) without this.

**Comment by davidfowl** [comment]
Sure, we can look at extending the current API to support native binaries. We just need to figure out what to do with it on full CLR

**Comment by xanather** [comment]
Yeah, it doesn't seem like its possible override/extend CLR native library loading, maybe something like CoreCLR's solution should try to be added to .NET 4.6 before it RTM happens (might already be too late for that)?

**Comment by davidfowl** [comment]
> maybe something like CoreCLR's solution should try to be added to .NET 4.6 before it RTM happens (might already be too late for that)?

It is too late. We have some other terrible ideas like modifying the path, or calling LoadLibrary/dlopen before loading the managed binary.

**Comment by xanather** [comment]
I was thinking about LoadLibrary before too, I have used it myself for loading x86 or x64 versions of the same library depending on what environment the runtime was running on. The problem though was that I was forced into making sure that the libraries were named the same (so they had to be in different folders) for DllImport(NAME) to map correctly to the loaded module name.

**Comment by xanather** [comment]
I don't think this will be possible on CLR for a while, this is mainly a cross-plat (non-windows) issue however, therefore, is an implementation possible on CoreCLR and Mono only, or does that go against the design of DNX (no fragmentation between abstractions)?

Are there any other alternative ways to override native library loading in DNX? Just an idea but DNX could just make it simple and just provide a basic single overridable method/event/delegate for the platforms in which it does support and document the platforms which would call it (could be just a string as a parameter as module name and returns an IntPtr, that's all).

I really can't distribute this app on multiple platforms (which defeats the purpose of using DNX/.NET Core) without such a feature, I'm sure when VS2015 RTM releases there would be many more in the same boat.

**Comment by xanather** [comment]
This is closely related to https://github.com/aspnet/dnx/issues/402. Is there any chance this will be implemented anytime soon, how far away is 1.0.0 release? Anyway, I think for now I will create a lightweight native library loader class and retrieve function pointers as this will work on all platforms http://stackoverflow.com/questions/13461989/p-invoke-to-dynamically-loaded-library-on-mono, not 100% sure about the performance implications though over using DllImport. Any CLR implementation should theoretically support this and allows specifying specific location to load libraries.

**Comment by davidfowl** [comment]
I'm not sure if this will be implemented for v1, we'll see how it goes. We're already using the technique you posted in several (if not all) of our libraries that pinvoke into native components.

**Comment by Jetski5822** [comment]
+1 - This would certainly help cleanup some of the plumbing in Orchard VNext.

**Comment by davidfowl** [comment]
Prototype here https://github.com/aspnet/dnx/commit/afb29037e8c9aa21cdd9138cf3de74d30e39dc7f

**Comment by akoeplinger** [comment]
@davidfowl one problem (which you may not care about :smile:) with the prototype and similar code in Kestrel is that it doesn't work on e.g. FreeBSD, which provides `dlopen()` in `libc` instead of `libdl`: https://github.com/aspnet/KestrelHttpServer/issues/94

**Comment by davidfowl** [comment]
Yep!

**Comment by davidfowl** [comment]
Added in rc1
