### ISSUE TITLE
DTH doesn't send us new "Error" message with the fixed version for global.json change

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#2060]
This is logged from TFS issue : http://bung/#/DevDiv/search/table?q=CID%3DDevDiv.1156067 

The repro steps are open any project, open it's global.json, introduce some syntax error (remove an existing comma), see that References node says to see error list, correct the error in global.json, notice that references node is still like that.

I debugged through the issue and this is what I found.

We used to send 'FilesChanged' for any global.json changes and the above used to work then (I tried that change that fixes the issue though regresses a scenario).

That means, we send a FilesChanged first, DTH sends us 'Error' message with error information from global.json parsing, user fixes global.json, we send FilesChanged again and DTH sends us new 'Error' message which does not contain an error (values being null and -1).

We are currently sending 'RefreshDependencies' for global.json change (for a valid reason, changes to global.json can change the dependency type from package to project).

The above sequence doesn't seem to work in that order.

We send 'RefreshDependencies', DTH sends us 'Error' message with the error information from global.json parsing, user fixes global.json, we send 'RefreshDependencies' again and DTH does not send us new 'Error' message without the error (values being null and -1).

**Comment by davidfowl** [comment]
@PradeepKadubandi was this supposed to be for beta5?

**Comment by troydai** [comment]
Fixed in 1033f3103a2bb5c6af3d325f6444604ef3a54c59
