### ISSUE TITLE
Is static Main not required anymore?

### ISSUE THREAD

**Issue by glennsills** [aspnet/dnx#2062]
I've noticed Program.Main isn't static anymore. Is this a recent change or have I been living under a rock?

**Comment by xanather** [comment]
No its not, but only while use DNX, when using something like CoreRun/CoreConsole as a bootstrapper it's still needed as discovered here https://github.com/aspnet/dnx/issues/1997.

DNX reflects into the assembly and finds the entry point (there are multiple different types that can be defined with DNX).

**Comment by glennsills2** [comment]
Thanks for the explanation and pointer to the other thread.
