### ISSUE TITLE
architecture is "x86' on arm

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2063]
To determine OS architecture we just check the size of the pointer (https://github.com/aspnet/dnx/blob/32358ec9b8970070ff77cbc5beef28c13e3ab09b/src/dnx.host/RuntimeEnvironment.cs#L21). As a result Win10 IoT one core on ARM is retported to be x86.

**Comment by BrennanConroy** [comment]
Here too if we run tests on arm: https://github.com/aspnet/dnx/blob/32358ec9b8970070ff77cbc5beef28c13e3ab09b/test/dnx.host.Tests/RuntimeEnvironmentTests.cs#L42

**Comment by moozzyk** [comment]
And in kestrel where we use it to load libuv.dll.

**Comment by anurse** [comment]
Shouldn't the native bootstrapper just pass this data in and the managed code just read it rather than trying to redetect it? The bootstrapper is unique per architecture and OS (and there's a bootstrapper for Mono too).

**Comment by moozzyk** [comment]
Possibly. Might part of #1970

**Comment by muratg** [comment]
@DamianEdwards is ARM in scope for V1?  

cc @davidfowl @Eilon @danroth27 

Also see https://github.com/aspnet/KestrelHttpServer/issues/106

**Comment by moozzyk** [comment]
Actually this should resolve itself semi-automatically when dnx starts loading native dlls automatically. - then we will be able to remove the code where we have the check.

**Comment by moozzyk** [comment]
We seem to be doing this only in one place: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Loader/LoadContext.cs#L71

**Comment by davidfowl** [comment]
Do we still need this?

**Comment by moozzyk** [comment]
Possibly - depending on what happens with `LoadContext` and if ARM is going to be officially supported.
