### ISSUE TITLE
Start DNX without a console

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2067]
Is it possible to prevent the creation of a console window with a command somehow? I realize right now DNX's main target is not desktop apps but nothing prevents it from being used in such a way.

I use my own native libraries and other .NET assemblies for creating UI (since it's not included in .NET Core). Downside is doing such a thing results in two windows for the app, the background console window and the actual app UI window.

Such a feature can be helpful for enabling background operations anyway and isn't just limited to this use case.

**Comment by moozzyk** [comment]
You could try loading the `dnx.win32.dll` and invoking this function: https://github.com/aspnet/dnx/blob/dev/src/dnx/dnx.cpp#L305 make sure to pass the parameters. More or less what we do here: https://github.com/aspnet/dnx/blob/dev/src/dnx.windows/dnx.cpp#L28

**Comment by xanather** [comment]
Easy enough, thanks :)
