### ISSUE TITLE
Crash in dnx.exe when I try to UseMvc without doing services.AddMvc in an empty web app

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#2068]
Win8.1 x64 + D14Rel.23012 + WSR32 + Wte.Main
 
1. File > New Project > ASP.NET 5 (Empty Web)
2. Open project.json, add "Microsoft.AspNet.Mvc"
3. In Startup.cs, add MVC (**Note**: I forgot to do services.AddMvc in ConfigureServices method):
 
```
// Add MVC to the request pipeline.
app.UseMvc(routes =>
{
routes.MapRoute(
name: "default",
template: "{controller=Home}/{action=Index}/{id?}");
});
 ```

4. With "web" profile selected, Ctrl-F5

ACTUAL

![image](https://cloud.githubusercontent.com/assets/8246794/8166610/c205e556-134d-11e5-9976-e13acf841e43.png)

Command window shows the correct exception, but it shouldn't crash the dnx.exe process though

![image](https://cloud.githubusercontent.com/assets/8246794/8166619/d07717f4-134d-11e5-8ea0-00e40eaff0cb.png)

**Comment by muratg** [comment]
What's the DNX build here?

**Comment by balachir** [comment]
1.0.0-beta5-11911, this is the one that we currently have in WTE

**Comment by davidfowl** [comment]
Looks about right. This is by design. The difference is now that VS is letting the exception bubble vs letting the console pop up and disappear. This is a recent change that @BillHiebert made

**Comment by balachir** [comment]
Should this crash the dnx.exe process though? If I run under the debugger, I get

![image](https://cloud.githubusercontent.com/assets/8246794/8246893/546c99b2-15fb-11e5-8a96-ad77f1f24315.png)

I can reproduce with latest tooling bits for Dev14 RTM

**Comment by davidfowl** [comment]
Yep that's by design. It's the same thing you'd see with a console application if you deleted one of the required DLLs. DNX is the host and we're letting exception bubble out of it in VS.
