### ISSUE TITLE
dnx commands list

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#2071]
Provide a way to list the set of installed commands and the commands available in a given project.

**Comment by nosami** [comment]
If you use bash and you install this https://github.com/nosami/dnx-bash-completion - you can get available commands via tab completion (as well as dnvm version completion etc)

**Comment by kichalla** [comment]
:+1:  for this support

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by davidfowl** [comment]
Move to CLI removes commanding support
