### ISSUE TITLE
Latest DNU does not have the executable bit set

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#2081]
When running the following DNX:
```
Microsoft .NET Execution environment
 Version:      1.0.0-beta6-12085
 Type:         Mono
 Architecture: x86
 OS Name:      Linux
```

I found out that the dnu script did not have the executable bit set. Without that bash will not let the dnu command to be used.

**Comment by dougbu** [comment]
This is a `dnvm` incompatibility with latest DNX scripts. I'm working on it.

**Comment by henkmollema** [comment]
https://github.com/aspnet/Home/issues/679

**Comment by dougbu** [comment]
Latest `dnvm.sh` on aspnet/Home repo contains necessary fix. Execute `dnvm update-self` then `. .dnx/dnvm/dnvm.sh`. (The `dnvm update-self` sources the new file but that's in a separate process :frowning:) Unfortunately the DNX bits you downloaded are likely broken. Can either set all the executable bits or (simpler) `rm -r .dnx/runtimes; dnvm upgrade; dnvm upgrade -u` to get the latest stable and unstable bits.

**Comment by borgdylan** [comment]
I set the exec bit in dnu by hand already. I will update dnvm.

**Comment by henkmollema** [comment]
Works, thanks! :+1:

**Comment by dougbu** [comment]
FYI, commit that should have gone in _after_ dnvm repo changes: 2c3d535
dnvm repo changes:
- aspnet/dnvm@ad8fdd9 (use `/usr/bin/env`)
- aspnet/dnvm@85653d8 (fix bootstrapping issue in above)
- aspnet/dnvm@d9713ee (another attempted fix, reverted in next commit)
- aspnet/dnvm@4bc5e73 (pass enough characters for `grep` to succeed)

**Comment by dougbu** [comment]
See also PRs aspnet/dnvm#295 and #2066
