### ISSUE TITLE
Need an actionable error message for dnx command when .net451 is not installed on the machine

### ISSUE THREAD

**Issue by kirthik** [aspnet/dnx#2084]
On a machine that does not have .NET 4.5.1 installed if I type `dnx`, I see the following error message
`Failed to initalize runtime (80004001)`

It does not tell user anything about installing .NET 4.5.1. Error message needs to be more actionable.

**Comment by moozzyk** [comment]
This might be hard. There is only a handful of common HRESULT values (https://msdn.microsoft.com/en-us/library/windows/desktop/aa378137(v=vs.85).aspx) and 0x80004001 is one of them. They are all very generic and each of them can have multiple root causes. We can add a suggestion to the message though. 
Btw. Does it have to be .NET Framework 4.5.1 (and not for instance .NET 4.5)? From what I remember the bootstrapper only passes the required version of the CLR (which is 4.0.30319 which is used for .NET Framework 4 and above)

**Comment by davidfowl** [comment]
@moozzyk We'd have to check the registry after a failure. That might help detect this type of situation.

**Comment by moozzyk** [comment]
@davidfowl - it does not make much sense in my opinion - it adds another layer of problems (accessing registry + potential permission issues etc.) just to optimize a message for an error scenario.
Instead, we could just blindly add "Is .NET Framework xxx installed?" for E_NOIMPL to the message.

**Comment by moozzyk** [comment]
(It would be actually interesting to see what `GetLastError()` returns in this case and if displaying it can be helpful.

**Comment by davidfowl** [comment]
That's how you check for .NET. I'm not sure it would be that complicated.
