### ISSUE TITLE
'--dependencies' option on 'dnu pack' doesn't seem to be doing anything

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2090]
The help on `--dependencies` option mentions `Copy dependencies`, but I do not see any dependent packages being copied on using it...

Looks like we are ignoring this option entirely:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/ConsoleCommands/PackConsoleCommand.cs#L22

**Comment by BrennanConroy** [comment]
dupe #1553
