### ISSUE TITLE
dnu is not marked as executable in latest mono & core clr OSX DNX builds

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#2091]
I installed latest DNX on OSX for Mono and Core CLR and it appears the "dnu" file is not marked as executable, which leads to all sorts of confusing error messages. I checked the beta4 DNX and it's executable there so I manually made "dnu" executable after I installed and then it started working (for the Mono build at least, not for Core CLR as outlined in #1793).

**Comment by davidfowl** [comment]
It's already fixed and it's a dnvm bug.

**Comment by davidfowl** [comment]
https://github.com/aspnet/dnx/issues/2081

**Comment by DamianEdwards** [comment]
Wow, that'll teach me for not logging the bug immediately when I found it, but I was on stage at the time :confused:
