### ISSUE TITLE
dnx --packages does not work

### ISSUE THREAD

**Issue by kirthik** [aspnet/dnx#2092]
I tried this command 

`dnx --packages D:\Test\packages C:\Users\kirthik\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\M
icrosoft.Framework.ApplicationHost.dll web` 
I get this error `The option '--packages' can only be used with Microsoft.Framework.ApplicationHost`

just trying `dnx --packages D:\Test\packages web` gives following message
`Please specify the command to run`

It is first of all unclear what `--packages` option expects. We should have better documentation overall.

**Comment by davidfowl** [comment]
```
Microsoft .NET Execution environment Mono-x86-1.0.0-beta6-12100

Usage: dnx [options]

Options:
  --appbase <PATH>                 Application base directory path
  --lib <LIB_PATHS>                Paths used for library look-up
  --debug                          Waits for the debugger to attach before beginning execution.
  -?|-h|--help                     Show help information
  --version                        Show version information
  --watch                          Watch file changes
  --packages <PACKAGE_DIR>         Directory containing packages
  --configuration <CONFIGURATION>  The configuration to run under
  --port <PORT>                    The port to the compilation server
```

It does work:

dnx --packages <DIR> <applicationpath> <command name>
