### ISSUE TITLE
Add 'kestrel' to the list of skipped global command names

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2094]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/Install/CommandNameValidator.cs#L21

**Comment by muratg** [comment]
New link to the validation list: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Install/CommandNameValidator.cs#L21

**Comment by davidfowl** [comment]
Why?

**Comment by muratg** [comment]
Is it going to be just "web" defaulting to kestrel only from now on?  If we plan to keep "web" for httpplatformhandler module + kestrel, then it kinda makes sense to reserve "kestrel" (or some other word) for runs wihout httpplatformhandler.

**Comment by davidfowl** [comment]
I'd actually prefer to call to web but I don't know what damage that will cause to people's brains :smile:

**Comment by muratg** [comment]
Perhaps we can default "web" to kestrel only, and have an additional one "iis" (or something)?
