### ISSUE TITLE
Restore on a locked lock file does not download packages

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#2095]
Reproing this in CoreCLR-x86-1.0.0-beta5-12087 and CoreCLR-x86-1.0.0-beta5-12077.  If I have a locked lock file and an empty packages folder restore will not download the packages.  If the lock file is absent or unlocked it works fine.  Found by @akoeplinger https://github.com/dotnet/corefx/issues/2073#issuecomment-113283797.

**Comment by ericstj** [comment]
/cc @anurse 
Please let us know when there is an official build with this fix.  It's currently blocking our move to the latest DNX.

**Comment by anurse** [comment]
1.0.0-beta5-12101 should have the fix when it arrives in the release feed. The DNX build succeeded but our Coherence build failed so we don't have a signed build yet.

**Comment by anurse** [comment]
Closed as this should require no more specific action (fix is in, just waiting for build to clear up)
