### ISSUE TITLE
project.lock.json locked by some process error after restore

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2097]
![projectlock](https://cloud.githubusercontent.com/assets/1592091/8244935/7198a6ee-15f5-11e5-9dcc-27f6d411f548.png)

I commented out all code in project system that touches project.lock.json in any possible way and could repro it on latest D14Rel + latest WTE. I suppose it is dnu..

**Comment by Eilon** [comment]
Resolved by https://github.com/aspnet/dnx/pull/2103
