### ISSUE TITLE
No error for incompatible dependencies when targeting dotnet.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/dnx#2100]
Steps to reproduce:

1. Create new class library.
1. Add xunit/xunit.runner.dnx to library.
1. Add test command
1. Build project. It builds successfully, restores successfully but it's invalid because xunit/xunit.runner.dnx only target dnx451/dnxcore50 (not to mention its an executable project).
1. You only then get an error message when attempting to run the test project that states that it couldn't resolve dependencies and that you should run dnu restore which is extremely misleading since running restore succeeds.

Ultimately, if I target `dotnet` and add dependencies that don't also target `dotnet` I should get some sort of error or indication that I messed up.

**Comment by Eilon** [comment]
Yeah I think @anurse and I chatted about this yesterday when we talked about the 4.0.20 issue. I think this feature is coming to NuGet but isn't there yet.

**Comment by anurse** [comment]
Yeah, this will probably come easiest when we pull some of the NuGet3 code into DNU

**Comment by natemcmaster** [comment]
:+1: Yes the error message is misleading. `dnu restore

**Comment by davidfowl** [comment]
@ChengTian is doing work in this area
