### ISSUE TITLE
Publish to azure fails in x64 runtime

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/dnx#2101]
Not sure which is the right place to file this issue.

Repro steps:
1. Create a new project
2. Right click project -> Publish
3. Select subscription, webapp etc
4. Select x64 clr as the target runtime
(don't edit the architecture in global.json, use the wizard to select runtime)
5. Publish
6. Server error "/" in application.

Workaround:
1. change the target runtime to x86 and publish and it should work.
2. Then change it back to x64 and then it works.

**Comment by Eilon** [comment]
File in Tooling-Internal?

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/Tooling-Internal/issues/392
