### ISSUE TITLE
It is unclear when to use . for dnx

### ISSUE THREAD

**Issue by kirthik** [aspnet/dnx#2104]
`dnx --debug kestrel` starts the server but `dnx . --debug kestrel` throws an exception.

`dnx . --configuration release kestrel` starts the server while `dnx --configuration release kestrel` does not.

It is unclear (and there is no documentation) when to use . and when not to use it.

**Comment by ramtinkermani** [comment]
The "dot" refers to the current directory. You can replace it with the target projects directory path if you are not running dnx from current directoy.
Here is the documentation:
https://github.com/aspnet/Home/wiki/DNX-structure#dnx-usage

**Comment by Eilon** [comment]
Related: https://github.com/aspnet/Announcements/issues/52

@moozzyk thoughts on this? Anything to do here?

**Comment by davidfowl** [comment]
Closing this out nothing to do heee
