### ISSUE TITLE
Generating wwwroot contents in the output folder specified in dnu publish.

### ISSUE THREAD

**Issue by kalluri-nb** [aspnet/dnx#2112]
Is there a way i can generate the publish package with the contents of wwwroot in the output folder rather than a sub folder "wwwroot" in the output folder. 
Specifying --wwwroot-out "." does not generate or deleted the approot folder before copying the wwwroot contents in the output folder

**Comment by davidfowl** [comment]
Why?

**Comment by kalluri-nb** [comment]
I'm trying to create and cspkg file using cspack using the command 
cspack.exe c:\tmp\azure\ServiceDefinition.csdef /role:Empty;c:\tmp\azure\cs1;wwwroot\bin\aspnet.loader.dll /out:c:\tmp\azure\api.cspkg
which copies only the wwwroot folder to the site root and the reference to approot is lost when deployed. 
The application throws the below error
Unable to find the runtime directory 'F:\sitesroot\0\..\approot\runtimes\dnx-clr-win-x64.1.0.0-beta6-12114'.
Possible causes:
1. The runtime was not packaged with the application.
2. The packaged runtime architecture is different from the application pool architecture.

**Comment by kalluri-nb** [comment]
@davidfowl I understand currently there is no support for deploying a ASPNET5  application directly to the webrole . Is there is recommended way to do this.

**Comment by davidfowl** [comment]
It's not currently supported no.

**Comment by muratg** [comment]
Putting this in backlog for now. 

@DamianEdwards do we plan to support WebRole's in the future at all?
