### ISSUE TITLE
dnx.coreclr.dll will leak if platform assemblies not found

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2114]
returning here:
https://github.com/aspnet/dnx/blob/dev/src/dnx.coreclr/dnx.coreclr.cpp#L446

will not release memory allocated here:
https://github.com/aspnet/dnx/blob/dev/src/dnx.coreclr/dnx.coreclr.cpp#L433

**Comment by davidfowl** [comment]
@moozzyk did you fix this?

**Comment by moozzyk** [comment]
@davidfowl this will be fixed in my next pr
