### ISSUE TITLE
Create a TFM for DNX on Mono

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2118]
We want to create a TFM for DNX on Mono: `dnxmono`. It should probably be tied to Mono version. It should also inherit from a `dnx` (desktop CLR) TFM.

We'll want to get this in to NuGet as well.

**Comment by anurse** [comment]
Ping @davidfowl

**Comment by aggieben** [comment]
What's the motivation behind this?

**Comment by anurse** [comment]
In my mind, the main motivation is to make it easier to conditionally compile code for Mono. This would allow packages to, in theory, provide a more appropriate implementation of their assembly on Mono (in case of differences between the Mono BCL and the .NET BCL, among other things).

If we did this, it would be compatible with the regular `dnx` framework applicable to the Mono version, so say `dnxmono40` might be compatible with `dnx451` (just spitballing, we'd need to work out the exact version mappings). This means that existing packages would work fine with a `dnxmono` project.

This is definitely and area where we want feedback from the Mono community though!

**Comment by davidfowl** [comment]
It's to avoid things like this https://www.nuget.org/packages/Ninject.Mono/

**Comment by anurse** [comment]
@davidfowl @lodejard we need to decide a) if we need/want to do this and b) how we're going to do it in beta8 or there won't be time to react to user feedback for RC.

**Comment by davidfowl** [comment]
Sigh seems like these issues weren't triaged. This was punted

**Comment by anurse** [comment]
That's what I thought.

**Comment by PinpointTownes** [comment]
+1 for a Mono TFM! :tada:

**Comment by kieranfoot** [comment]
This would be a great help, as Mono is already truly cross platform and widely supported, however coreclr isn't and a lot of great libraries simply aren't supported. So being able to target Mono would be great.

**Comment by davidfowl** [comment]
> This would be a great help, as Mono is already truly cross platform and widely supported, however coreclr isn't and a lot of great libraries simply aren't supported. So being able to target Mono would be great.

This bug isn't about targeting mono all up. It's about targeting either mono specific APIs that *DO NOT* exist in the .NET Framework itself, or targeting mono because of missing APIs. Either way, this is no longer a DNX issue and is a nuget issue.

**Comment by PinpointTownes** [comment]
I opened a ticket at NuGet/Home to track that: https://github.com/NuGet/Home/issues/2320.

**Comment by aggieben** [comment]
Without a TFM for mono in DNX, how would one use Mono as the desktop runtime in Windows?

**Comment by BrennanConroy** [comment]
Probably just make sure you have the mono dnx runtime selected and do your normal app execution with it?

**Comment by aggieben** [comment]
Uh...right.  Duh ;-)
