### ISSUE TITLE
There is no way for packages to read from a configuration file...

### ISSUE THREAD

**Issue by ramsees** [aspnet/dnx#2122]
Greetings.

I'm having this issue with dnx, I created a package that needs to read from a file for runtime configurations, but right now, there is no way to embbed or use the configuration file from an application, if I want to access to the App.config it wil try to access to dnx.config in the dnx path, it makes sense, since I'm running my application with "dnx . web", now, If I want to access to the config.json file in my application, there is no way for the package to guess the path of the file,and if it doesn't exist there is no way to create it, so my package can't read configurations from a file.

So, there needs to be a way for a package to read from a configuration file, since the estandar App.config is deprecated.

**Comment by davidfowl** [comment]
I'm noI'm not sure what you mean, what config file are you trying to read? Can you give a more end to end example?

**Comment by ramsees** [comment]
Sure, I created a package from an assembly, the assembly needs needs to read from a configuration file at runtime to get the IP of the services it will consume, this was trivial with System.Configuration because it was implying there would be an App.config or a Web.config with an <appsettings> section.

But now with dnx where there is no App.config and you need to add the configuration file in the startup and my package has no clue from where to get that runtime configuration, this is the scenario:

I create an ASP.5 application, I add the package to the dependencies to Project.json, I use dnu restore to retrive the package, I run the application with "dnx .web", my application crashes because the package has no way to retrieve the IP for the services it will consume and this is because there is no App.config now, so, the package needs to know from where to read that information, and there is no current way to do it because the package doesn't have access to the IHostingEnviromen service and It shouldn't because this package can also be used in desktop applications.

So, my package needs a way to access to a configuration file ala App.config and with dnx is not possible,

**Comment by davidfowl** [comment]
> Sure, I created a package from an assembly, the assembly needs needs to read from a configuration file at runtime to get the IP of the services it will consume, this was trivial with System.Configuration because it was implying there would be an App.config or a Web.config with an "appsettings" section.

That's correct, there's no static System.Configuration anymore.

> But now with dnx where there is no App.config and you need to add the configuration file in the startup and my package has no clue from where to get that runtime configuration, this is the scenario:

Sure there is, we do it all the time. You just need to change how you did it.

> my application crashes because the package has no way to retrieve the IP for the services it will consume and this is because there is no App.config now, so, the package needs to know from where to read that information, and there is no current way to do it because the package doesn't have access to the IHostingEnviromen service and It shouldn't because this package can also be used in desktop applications.

Sure it does. Use dependency injection to get the IApplicationEnvironment. Maybe you're saying you don't want to use it?

We do this in a bunch of places. Hosting has an example of that https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L31.

**Comment by ramsees** [comment]
> Use dependency injection to get the IApplicationEnvironment

That's what I woulnd't like to do, It would need a lot of changes and I dont't even have the source from some assemblies.

So, a method for a package to read from a configuration file w/o using dependency injection is what is needed.

**Comment by davidfowl** [comment]
You mean you want to use a static. We pretty much have tried to remove as many statics as possible from the new framework because in general it makes things harder to test and parallelize. You just need a way to get the current application base as there is no "current configuration file", you need to make one up and choose a name.

**Comment by ramsees** [comment]
> you need to make one up and choose a name.

I would gladly do that, the problem is that there is no way in the package to know the path of the application w/o IHostingEnviroment, and my package doesn't have access to it.

**Comment by davidfowl** [comment]
Seems like you missed the critical part of the last comment:

> You mean you want to use a static. We pretty much have tried to remove as many statics as possible from the new framework because in general it makes things harder to test and parallelize.

Also IHostingEnvironment is wrong, you need IApplicationEnvironment. Make your package take in the base path the configuration file, or have the application pass it in to your package. There really isn't a clean way to get the IApplicationEnvironment if you're not using DI.

**Comment by ramsees** [comment]
I use IHostingEnviroment because it gives me the webroot path, now, I see that by desing everything now must be used with nuget and dependency injection, but looks like you missed the part were I said I don't have the source code for some assemblies and it means those are useless now and a new version of those assemblies is needed and that is a lot of problem.

I understand that the prefered way for asp.net vnext is to use dependency injection, but what I see is not he prefered but the only way leaving lot of legacy assemblies int the cold.

**Comment by davidfowl** [comment]
IHostingEnvironment is *WRONG* it represents the webroot, which is for serving static files. It does *NOT* represent the application root, where code and configuration files are located.

> but looks like you missed the part were I said I don't have the source code for some assemblies and it means those are useless now and a new version of those assemblies is needed and that is a lot of problem.

Then I assume you only care about running on full .NET, not .NET Core because System.Configuration isn't there.

If this third party assembly is always reading from app.config and cannot be changed then I think you're out of luck. The AppDomain's ApplicationBase isn't even pointing to the application base path (like it does in vanilla .NET Framework) so none of those calls will just work without specifying full paths.

**Comment by ramsees** [comment]
>IHostingEnvironment is WRONG 
And that's now the point of this disccussion, asume I said IApplciationEnviroment.

>Then I assume you only care about running on full .NET, not .NET Core because System.Configuration isn't there.

That's right, not interested in cross platforming for the momento, so no core clr is needed.

>I think you're out of luck

That's what I needed to now,if vnext was an option for the Project we are going to work and looks like is not and we are going to use something else instead.

Thank you.

**Comment by davidfowl** [comment]
> That's what I needed to now,if vnext was an option for the Project we are going to work and looks like is not and we are going to use something else instead.

That's good feedback. We might be able to make some existing scenarios compatible in very narrow situations. Like a web.config on IIS (maybe), but not across the board for general App.Config files. 

Does the library support passing in any sort of configuration or does it just assume that System.Configuration is available?

**Comment by ramsees** [comment]
It doesn't asume System.Configuratin available, it just needs the path of the configuration file, it can be a ini file or an XML file.

**Comment by davidfowl** [comment]
What does the API look like and how to you tell it where to read from?

**Comment by ramsees** [comment]
It is like this:

var pConfigs = GetConfigurations(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "configs.ini"));

var pIp = pConfigs["ServicesIP"];

**Comment by davidfowl** [comment]
Is that the code from the library itself? Or the application using the library?

**Comment by ramsees** [comment]
It is my code, when third party libraries need configurations from runtime I read them from the ini file (or App.config) and then pass them to the library.

Other llibraries from a third party vendor need the path to a ini file to read configurations.

**Comment by davidfowl** [comment]
I'm confused. You said you don't have the source code to something. What was that thing? Can you show me how the application developer uses your library to tell it what configuration file to look at? Lets say I wanted you to read configuration from `"c:\mysharedconfig.ini"`, can I make your library look there?

**Comment by ramsees** [comment]
There are two escenarios, I have to source to the libraries I use, this is a very extensive library lets call it BussinessLogic.dll, this library depends of another library that has the persistence since use n tier architecture lets call it Persistence.dll, the Persistence.dll needs to read from a configuration file at runtime to get the ip of services ip and databases connection strings, I do this reading from App.config or web.config depending of the case, not problem so far.

Now, my BussinessLogic.dll also depends from third party libraries from SAP B1 to be specific developed specially for us year ago, these libraries need the path to a ini file or to the directory it is the ini file, I don't have the source of this but I guess I could pass them via dependency injection using my BussinessLogic.dll as a proxy, so far is plausible, the library is big and to pass the dependency injection in the constructor is possible but implies a lot of changes in out architecture that we would need to evaluate if it is worthy.

But, other libraries that are needed for financies reporting asume there will be an App.settings file because it will read some variables from the appsetings sections, there is no way make that assembly to read the file from dnx since there is no App.config file and I don't have the source code eather, and that is the main problem.

I hope I've explained my self a litle better this time.

**Comment by RickStrahl** [comment]
David - this is a great discussion because it points at some of the difficulties in figuring out how to find stuff.  How would you find out about how to manually instantiate ConfigurationBuilder for example? Is that even documented anywhere?

Also, I know I've been having a bit of trouble finding good examples and description of the process of how to hook up DI into your own components. If I create a component that I want to have participate in DI how do you set that app effectively? At the moment it looks the only way to figure this out is to look at examples in the source code, which is useful, but I think this could really use some formal documentation somewhere. Apologies if this exists somewhere - but I haven't been able to find it.

**Comment by davidfowl** [comment]
> But, other libraries that are needed for financies reporting that asume there will be an App.config file because it will read some variables from the appsetings section, there is no way to make that assembly to read the file from dnx since there is no App.config file and I don't have the source code eather, and that is the main problem.

@ramsees Thanks for the clarification. Today things that try to read app config are broken. I'll see if there's anything we can do to make this work. The application base path is different for DNX based applications but maybe we can enable a mode where the application base path is the application folder itself. We might be able to tweak the configuration file location to be more compatible with existing libraries for DNX 4.5.1. This obviously won't work on CoreCLR (as I've stated before).

**Comment by davidfowl** [comment]
@RickStrahl 

> David - this is a great discussion because it points at some of the difficulties in figuring out how to find stuff. How would you find out about how to manually instantiate ConfigurationBuilder for example? Is that even documented anywhere?

The docs are a version behind and don't show the new configuration builder API. Stuff shifted around a bit but the fundamentals are still the same. See http://docs.asp.net/en/latest/fundamentals/configuration.html

> Also, I know I've been having a bit of trouble finding good examples and description of the process of how to hook up DI into your own components

You can do this in several ways. MVC for example is a library that chooses to expose it's registrations for the IServiceCollection. The app developer needs to call services.AddMvc before they can use MVC. You can follow this pattern for your libs. You can also just declare dependencies in the constructor of your libraries classes and have them be injection friendly, that way the application code wires your library and it just works. You could also just have your library take an `IConfiguration` instance.

**Comment by muratg** [comment]
@davidfowl Putting this in Backlog for now.

**Comment by davidfowl** [comment]
Config respects relative paths now.
