### ISSUE TITLE
OS X : DNU installed without execute permissions

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2126]
Upgraded the dnx runtime using DNVM. dnu is not installed with +x permissions on OS X.

Although a simple fix, it leads to 'dnu not found' errors unless you manually navigate to the .dnx/runtime/ folder and `chmod` to add execution permissions.

DNX version:  1.0.0-beta6-12114
DNVM version (homebrew installation):  1.0.0-dev

```
$ ls -l
...
-rw-r--r--  1 namc  staff   539B Jun 23 00:21 dnu
-rwxrwxr-x  1 namc  staff   593B Jun 23 00:21 dnx
```

**Comment by troydai** [comment]
+1. Confirm this issue. @moozzyk

**Comment by BrennanConroy** [comment]
You probably have an older dnvm, this issue has been fixed.

**Comment by natemcmaster** [comment]
@BrennanConroy If so, how do we users upgrade dnvm? `dnvm update-self` doesn't work https://github.com/aspnet/dnvm/issues/246 or it destroys itself `https://github.com/aspnet/dnvm/issues/257`. Can we offer dnvm updates through brew instead?

**Comment by BrennanConroy** [comment]
I don't think we have a way to upgrade right now, except brew remove, then reinstall

**Comment by natemcmaster** [comment]
Upgrading dnvm fixed this.
