### ISSUE TITLE
Show more friendly error message in "dnu restore" when HTTP requests time out

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2127]
Reported by @glennc 

![capture](https://cloud.githubusercontent.com/assets/1383883/8343888/4ac0e7b8-1a8f-11e5-9736-3676157ea98c.PNG)

The message `A task was canceled` doesn't make sense to users. We should display something like
```
HTTP request timed out. Retrying.
```

**Comment by cnblogs-dudu** [comment]
Still get `A task was canceled`.

![screen shot 2015-06-27 at 13 47 38](https://cloud.githubusercontent.com/assets/3196961/8390651/21b38ef2-1cd3-11e5-854a-914cd7da8ec3.png)

**Comment by BrennanConroy** [comment]
You have to wait for the next dnx version to come out.

**Comment by cnblogs-dudu** [comment]
Sorry. I made a mistake.

**Comment by ciznx** [comment]
@cnblogs-dudu  What mistake did you make? I suffered the same problem when restoring my project...why didn't you write more detail about your solution?

**Comment by cnblogs-dudu** [comment]
@ciznx 
It's a natural problem. Up to now, restoring packages from myget.org is always timeout in China.

**Comment by ciznx** [comment]
@cnblogs-dudu Thank you for your reply.
Yes, I found it too that restring packages on a Linux from China will always timeout. (But how a Windows PC works perfectly...)
It's such a pity.
