### ISSUE TITLE
[Question] Configure dnx to use a mixed mode assembly

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/dnx#2128]
There is a need to use v1.1.4322 framework assembly (put into a NuGet package) in my vnext web api project. It works fine when I start the project under IISExpress. 

"dnx . web", on the other hand, throws an exception
"Unhandled Exception: System.IO.FileLoadException: Mixed mode assembly is built against version 'v1.1.4322' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.". I understand that dnx.clr.config has to be modified somehow and tried useLegacyV2RuntimeActivationPolicy="true" attribute which did not work. Could you please point me to the right direction?

**Comment by davidfowl** [comment]
It'll be possible (probably) with tthe move to the new dotnet CLI

**Comment by leo9223** [comment]
@davidfowl, Any updates on consuming mixed mode DLL in ASP.net 5 ? I am trying to use an old mixed mode assembly but no success yet, using RC1 Update1
