### ISSUE TITLE
Add "Effective Feeds" to dnu summary

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2131]

**Comment by glennc** [comment]
What?

**Comment by davidfowl** [comment]
Effective feeds are the set of feeds that were actually used during a restore. If you have 10 feeds configured but packages only came from 2 of them, those would be "effective".

**Comment by glennc** [comment]
Ok, got it.

**Comment by troydai** [comment]
/cc @muratg 
close and move to cli or nuget?

**Comment by davidfowl** [comment]
nuget

**Comment by muratg** [comment]
Do we have a nuget bug filed?  Can we link?

**Comment by davidfowl** [comment]
https://github.com/NuGet/Home/issues/1811
