### ISSUE TITLE
"dnu pack" fails when using current directory (. or ./project.json) as an argument

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2140]
While `dnu pack ..\ConsoleApp21\project.json` works fine. (`..\ConsoleApp21\project.json` and `.\project.json` point to the same file)

![capture](https://cloud.githubusercontent.com/assets/1383883/8369010/dd126db6-1b67-11e5-94c2-fa7b48c72fd2.PNG)

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#573
