### ISSUE TITLE
`dnu publish` fails if there's no `wwwroot` folder

### ISSUE THREAD

**Issue by friism** [aspnet/dnx#2141]
Take, for example, the `HelloMVC` project:

    # rm -rf wwwroot/
    # dnu publish --out /tmp/out --no-source --configuration Release
    Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12120

    The specified wwwroot folder 'wwwroot' doesn't exist in the project directory.

I would have expected the build to complete with no wwwroot or empty wwwroot folder. While it might be reasonable to require a `wwwroot` folder, it's a bit annoying, for example if one has an empty `wwwroot` folder that's not tracked by git.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/636

**Comment by muratg** [comment]
@ChengTian did we have a work item to create a wwwroot folder when publishing if it doesn't exist?

**Comment by moozzyk** [comment]
FWIW - I hit this yesterday too...

**Comment by friism** [comment]
Thanks guys! :dancer:
