### ISSUE TITLE
Support Roslyn Analyzers on dnx

### ISSUE THREAD

**Issue by giggio** [aspnet/dnx#2145]
At the moment we need to install vsix pkgs to VS to be able to use Roslyn analyzers. But this is insufficient, as it will not break a build, even if it is ran in VS.
We need to be able to reference analyzers on `project.json` and they should be able to run within the compilation process, independent of VS, as it already happens on non-dnx projects.

**Comment by muratg** [comment]
We are considering adding analyzer support in some capacity (tentatively in Beta 7.

**Comment by muratg** [comment]
This is tracked here: https://github.com/aspnet/dnx/issues/2311
