### ISSUE TITLE
Maintain prelease versions on the feed longer

### ISSUE THREAD

**Issue by MiguelAlho** [aspnet/dnx#2150]
Over the weekend the beta5 dnx packages have seemed to dissapeared from the feed. This ends up being a problem when pointing to a specific package, or trying to install/ upgrade to a specific version in dnvm.

I couldn't determine if it was dnvm failing to pull or if the packages simply no longer exist, but the 404's returned suggest the second. If it is a matter of deleting older packages based on some time constraint, then maybe making the time window wider might help avoid this type of problem, or keep all intermediate builds available until the specific beta version is available (keep all the intermediate beta5 packages available until the final one comes out).

Also noticed that the dnx package isn't persisted in the .dnx folder (or at least not the beta5 ones that I previously installed). Could it be that the upgrade and install options are presenting different behaviours? My /runtimes/dnx...beta4 folders all have a .nupkg, but beta5 and beta6 folders only have a .nuspec

**Comment by muratg** [comment]
@MiguelAlho Are you talking about [aspnetvnext](https://www.myget.org/gallery/aspnetvnext) feed? This is mainly for the dev branches.  When we cut the release feeds for a particular release (in this case beta5) we start using [aspnetrelease](https://www.myget.org/gallery/aspnetrelease) feed instead.  You can set this as your `DNX_UNSTABLE_FEED` environment variable and use `-Unstable`  command line switch when you do a `dnvm install`.

**Comment by Eilon** [comment]
I'll look into keeping more packages around... we used to keep 20 builds of every package but I lowered it to 15 builds because we kept running out of space. We're using around 5GB of storage already :smile:

**Comment by MiguelAlho** [comment]
@muratg I was using the -Unstable switch but couldn't get any Beta5 runtimes; I've been working with my colleagues on some prototypes, and syncing became a problem. I upgraded to beta5 some time ago, but every one else on the team got locked out because they couldn't pull the same version. It's more of a syncing thing at the moment, when more than one person is working on a project.

@Eilon - would it possible (or even worth the effort) to keep at least the last version of a specific beta around? Or add something to dnu that could list the available versions of a specific package (might help debug why a specific version of a package is missing)?

**Comment by Eilon** [comment]
The `aspnetvnext` feed is the "nightly" builds that get rebuilt several times a day. For stable releases, use `nuget.org` which has "permanent" copies of the official releases (beta1, beta2, etc.).
