### ISSUE TITLE
`dnu restore` silently ignores invalid NuGet.Config

### ISSUE THREAD

**Issue by friism** [aspnet/dnx#2152]
Eg. if there's an XML syntax error, `dnu restore` will simply ignore the NuGet.Config file and restore from default sources with no error or warning.

I think expected behavior is for `dnu restore` to error in that case. If user has `NuGet.Config`, they probably expect it to be honored and would like an error if there's a syntax error in the file.

**Comment by muratg** [comment]
Ugh. Does nuget.exe raise an error or warning in this case?

**Comment by friism** [comment]
@muratg haven't checked `nuget.exe` behavior.

**Comment by pranavkm** [comment]
NuGet ignores invalid Settings files. I think dnu's parsing code is verbatim taken from NuGet - http://nuget.codeplex.com/SourceControl/latest#src/Core/Configuration/Settings.cs

```C#
private static Settings ReadSettings(IFileSystem fileSystem, string settingsPath, bool isMachineWideSettings)
{
    try
    {
        return new Settings(fileSystem, settingsPath, isMachineWideSettings);
    }
    catch (XmlException)
    {
        return null;
    }
}
```

**Comment by davidfowl** [comment]
We need to fix this

**Comment by anurse** [comment]
Given that NuGet does the same thing though, we need to coordinate the fix with them /cc @yishaigalatzer 

Both should definitely be showing a warning at the very least when an invalid settings file is encountered.
