### ISSUE TITLE
Use type instead of whereis in dnu sources

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2155]
From https://github.com/aspnet/dnx/pull/2010#discussion_r33588481:

>  whereis  is present on most distributions but is not part of the POSIX spec. The recommended approach is usually  type  since that is part of the POSIX spec: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/type.html

**Comment by borgdylan** [comment]
Type gives the exact location of the binary. Whereis gives way more information and may include the version of the binary that the user compiles by hand and the one installed by the package manager for the distribution. So if you are trying to find mono type is better.

**Comment by anurse** [comment]
For this purpose, I believe we are just trying to identify if a command exists, so going for the broadest compatibility is desired over going for a broad feature set.

**Comment by borgdylan** [comment]
Also type appears to be a bash builtin i.e. its bash that provides it. So you may be able to do Process.Start on it directly.

**Comment by anurse** [comment]
Good point, it it a shell builtin on my Mac OS X system. In theory, we could launch `sh` to run `type` but that may overcomplicating things when `whereis` is generally available on most systems. We should have code to handle the failure case of `whereis` being missing though :)

**Comment by borgdylan** [comment]
If you will use whereis, you may get multiple location results for a binary. Always prefer /usr/local paths to /usr/ paths as that's what the PATH on UNIX systems ensures. I.e. it would be alarm many people, me included if it is not like that.

**Comment by victorhurdugaci** [comment]
The point of using `whereis` in this particular scenario is not to see where a particular executable is but to see if it exists at all before invoking it. The output of the command doesn't matter, only the return code.

**Comment by anurse** [comment]
I wonder if, rather than checking for the command in advance, we could just optimistically invoke the command and catch the exception that occurs when it fails. I don't generally like exceptions-as-control-flow but in this case it actually seems cleaner, given that our `whereis` check may also cause exceptions.

**Comment by muratg** [comment]
We won't be doing this for now.
