### ISSUE TITLE
Friend assemblies not supported with DNX ? How to strong-names and signs assemblies?

### ISSUE THREAD

**Issue by hpaiemen** [aspnet/dnx#2157]
While porting code from full framework 4.6 to DNX Core 5, I saw that I can't sign assemblies anymore to enable internal members to be use across projects of same solution. When I build, compiler sends me this error : `Assembly signing not supported.`

Will it be supported in near future or is there another way to strong-name assemblies ?
Thx.

**Comment by moozzyk** [comment]
With this commit 56f7dd8bc you should be able to fake strong sign assemblies on CoreClr. Just add `"strongName" : true` to your compilation options.

**Comment by hpaiemen** [comment]
"fake" ? does that mean that `[assembly: InternalsVisibleTo("MyAssembly, PublicKey='myKey'")]` won't work ? Because I tried with the "strongName" option set to true and it still can't give friend access to another assembly. However, I don't get the compilation error anymore.
Do you have any idea how I can get `InternalVisibleTo` to work, with or without strong name signature ?
Thx.

**Comment by smbecker** [comment]
I think the pattern has been to use a `*.Sources` package with `"shared": "**/*.cs"`. Something like https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.CommandLineUtils.Sources. This effectively copies the internal code to all referenced projects. Not a perfect solution but that seems to be the pattern based on looking at other projects.

**Comment by moozzyk** [comment]
CoreClr does not support signing assemblies with private and public key pair. However it does supports 
"signing" with a public key only (which is what I referred to as "fake" signing"). If you use `"strongName" : true` the assembly will be faked strong signed with a predefined public key (https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Roslyn.Common/CompilerOptionsExtensions.cs#L97-L110). You can get the key and the public key token with `sn -Tp` and you can use it for `InternalsVisibleTo`. One caveat - when I tried it with VS Intellisense reported bogus errors but compilation worked. I reported this issue to the VS team.

**Comment by moozzyk** [comment]
@smbecker - did you really want to comment on this issue?

**Comment by smbecker** [comment]
Yes, I did. I was trying to provide an alternate method to getting similar behavior to `InternalVisibleTo`.

**Comment by moozzyk** [comment]
I see. The idea is that strong naming was introduced to the stack and if it there are problems with that we need to fix them now so that workarounds are not needed. Obviously sharing sources is another way of doing this but in many cases is not preferable.

**Comment by davidfowl** [comment]
BTW you don't need to strong name to use InternalsVisibleTo

**Comment by moozzyk** [comment]
:+1:

**Comment by muratg** [comment]
@hpaiemen you can find some examples of InternalsVisibleTo usage in our own code.  For example, see here: https://github.com/aspnet/dnx/search?utf8=%E2%9C%93&q=InternalsVisibleTo.  Like @davidfowl says, you shouldn't need to sign your assemblies to get this working.

**Comment by hpaiemen** [comment]
Thx for all answers, it works now without strong naming.
