### ISSUE TITLE
Can not restore Microsoft.Framework.CommandLineUtils.Sources (≥ 1.0.0-beta5)

### ISSUE THREAD

**Issue by gbdrm** [aspnet/dnx#2163]
There is an issues with restoring Microsoft.Framework.CommandLineUtils.Sources (≥ 1.0.0-beta5) package from nuget.org

https://www.nuget.org/packages/Microsoft.Framework.CommandLineUtils.Sources/
returns 404

and it is a dependency in
https://www.nuget.org/packages/Microsoft.Framework.CodeGeneration.Core/

that is causing the issues, like
http://stackoverflow.com/questions/31151388/vs2015rc-mvc-project-upgrade-from-beta4-to-beta5

I have the same issue with
"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta5"
can not restore it because of:
Unable to locate Microsoft.Framework.CommandLineUtils.Sources >= 1.0.0-beta5

**Comment by mangibu** [comment]
I have the same problem...

**Comment by terryt2000** [comment]
+1

**Comment by betimd** [comment]
+1

**Comment by mxpv** [comment]
+1

**Comment by dgee2** [comment]
@Eilon @davidfowl @DamianEdwards Are any of you able to enlighten us?

**Comment by joergjo** [comment]
+1

**Comment by premkumar-gg** [comment]
+1

For me it is a dependency in "xunit.runner.dnx"

**Comment by henriqueprj** [comment]
Me too. => "xunit.runner.dnx"

**Comment by muratg** [comment]
Recommended workaround for Visual Studio RC users is:
- Remove `"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta5"` from `project.json`
- Remove `gen` command from `project.json`

In the next release of Visual Studio, we do not have these dependencies in the web application template anymore.

**Comment by muratg** [comment]
Line that needs to be fixed: https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Framework.CodeGeneration.Core/project.json#L7

**Comment by RehanSaeed** [comment]
+1

**Comment by milutinovici** [comment]
What's the workaround for xunit runner?

**Comment by mehtkab** [comment]
same question as milutinovici. Can't install the xunit.runner.dnx, because it can't resolve the commandlineutils (beta5).

**Comment by iceclow** [comment]
The problematic package seems to be Microsoft.Framework.TestHost as is published in nuget still carries dependecies with Microsoft.Framework.CommandLineUtils.Sources.

I get around it by changing my nuget package source settings to the master builds feed from nuget: https://www.myget.org/F/aspnetmaster/ The Microsoft.Framework.TestHost hosted there has the correct dependencies.

That change makes xunit runner to work.

**Comment by joergjo** [comment]
Thanks, that did the trick!

**Comment by iceclow** [comment]
Glad to help!

**Comment by muratg** [comment]
The following two will need to updated to build time dependencies:

- https://github.com/aspnet/Testing/blob/dev/src/Microsoft.Framework.TestHost/project.json#L12
- https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Framework.CodeGeneration.Core/project.json#L7

**Comment by muratg** [comment]
Microsoft.Framework.CommandLineUtils.Sources.1.0.0-beta5 is pushed to nuget.org now. This should unblock folks. We will remove this dependency from the impacted packages in Beta 6.

**Comment by Eilon** [comment]
@muratg are we still tracking the actual fixes for beta 6?

**Comment by muratg** [comment]
Yes.
- TestHost: https://github.com/aspnet/Testing/issues/128
- CodeGeneration.Core: https://github.com/aspnet/Scaffolding/issues/99
