### ISSUE TITLE
dnu publish does not work with additional references in global.json

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2169]
If my global.json has some additional references apart from the default like this:

```
{
  "projects": [ "src", "test", "C:/source/Helios/src" ],
```

dnu publish will fail with:

The project name 'Microsoft.Web.Administration.Interop' is ambiguous between the following projects:
C:\source\Helios\src\Microsoft.Web.Administration.Interop
c:\temp\WebApp\approot\src\Microsoft.Web.Administration.Interop

The issue is that `dnu publish` will copy the referenced projects under to the `src` target folder but will keep the "C:/source/Helios/src" in the global.json file like this

```
{
  "projects": [
    "src",
    "test",
    "C:/source/Helios/src"
  ],
```
As a result the projects are referenced twice. 

Also note that absolute paths or paths outside the target folder do not make much sense if publish for deployment.

**Comment by muratg** [comment]
@ChengTian

**Comment by ChengTian** [comment]
During `dnu publish`, we can fix this error by removing `projects` entries pointing to folders outside of solution root.

**Comment by ChengTian** [comment]
@davidfowl , are you happy with my solution above?

**Comment by ChengTian** [comment]
Talked to @davidfowl , in `dnu publish` output bundle, we want to copy all source code to `approot/src` subfolder and delete all other `projects` entries from `global.json` while copying it.
