### ISSUE TITLE
IRuntimeEnvironment.RuntimeVersion value is wrong

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#2171]
`IRuntimeEnvironment.RuntimeVersion` value is not actually the runtime version. it gets the version of the `dnx.host.dll` assembly and returns it as the value but it is different than the package version for some reason for `dnx-clr-win-x64.1.0.0-beta5` runtime.

![screenshot 2015-07-01 20 51 34](https://cloud.githubusercontent.com/assets/328122/8463773/28c29d68-2035-11e5-8694-85400810649e.png)

**Comment by davidfowl** [comment]
It's not wrong. That's the version. We rewrite the nupkg version before publish.

**Comment by tugberkugurlu** [comment]
OK but it is confuaing a LOT :smile:
