### ISSUE TITLE
dnu kestrel run error : unrecognized argument 'Kestrel'

### ISSUE THREAD

**Issue by LadyNaggaga** [aspnet/dnx#2174]
Hello, 

I am having issue running dnu Kestrel on Windows.  I am using VsCode to build an aspnet.template and I get the error below every time I run dnu kestrel command. 
Could really appreciate some insight to why this might be happening. 
![kestrel](https://cloud.githubusercontent.com/assets/2546640/8469088/f38c31aa-2042-11e5-8828-8627878ac402.PNG)

Thank you !

**Comment by davidfowl** [comment]
Can you file this on aspnet/Home?

**Comment by LadyNaggaga** [comment]
Sure I  post this over there

**Comment by smbecker** [comment]
Why are you running dnu and not dnx?
