### ISSUE TITLE
project.json match matter

### ISSUE THREAD

**Issue by back5576** [aspnet/dnx#2176]
What is the formal definition of the pattern syntax?
And specifically, what would be a pattern to exclude files which begin with a # character? Or that begin with .# two char sequence. Basically neededing to filter out emacs temporary files.

**Comment by muratg** [comment]
@troydai

**Comment by troydai** [comment]
@back5576 we support two types of wildcards only today.
* `**` match multiple segments 
* `*` match in one segment

**Comment by back5576** [comment]
segment?

**Comment by troydai** [comment]
@back5576 for example:

`/src/alpha/bravo` contains three segments: `src`, `alpha` and `bravo`.

**Comment by back5576** [comment]
I wish to exclude files based upon a file pattern. Specifically, need to exclude files beginning with
  .#
and 
  #

**Comment by troydai** [comment]
Can you try
```
exclude: ["**/#*", "**/.#*"]
```

**Comment by back5576** [comment]
Yes, that worked. Thanks.

**Comment by troydai** [comment]
@back5576 you're welcome.
