### ISSUE TITLE
Parallel dnu restore fails intermittently

### ISSUE THREAD

**Issue by nguerrera** [aspnet/dnx#2181]
We are experiencing intermittent issues with package restore, but they have only been seen when the --parallel option is passed.

Sample Command line:

```
"D:\Src\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta5-12101/\bin\dnu.cmd" 
    restore 
    --parallel 
    --packages "D:\Src\corefx\packages" 
    --source https://www.myget.org/F/dotnet-core/ 
    --source https://www.myget.org/F/dotnet-coreclr/  
    --source https://www.myget.org/F/dotnet-corefx/ 
    --source https://www.myget.org/F/dotnet-corefxtestdata/ 
    --source https://www.myget.org/F/dotnet-buildtools/ 
    --source https://www.nuget.org/api/v2/ 
    "D:\Src\corefx\src" 
    "D:\Src\corefx\packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00056/lib/"
```

And here is a sample error from that invocation (there are typically a ton just like it and it happens on myget.org and nuget.org):

```
1>EXEC : warning : FindPackagesById: System.Globalization [D:\Src\corefx\build.proj]
  Unable to write data to the transport connection: An existing connection was forcibly 
  closed by the remote host.
  GET https://www.myget.org/F/dotnet-core/FindPackagesById()?id='System.Globalization' (TaskId:7)
```

You can probably reproduce this by cloning dotnet/corefx and running "build.cmd /p:ParallelRestore=true" a few times with the packages folder wiped out each time. I extracted the above from the resulting msbuild.log after doing just that right now.

@Tratcher suggests this might be due to rate limiting from myget/nuget and a connection limit that is way too high here:

https://github.com/aspnet/dnx/blob/d66611a8530a476bc914ef60d5d729f3420b9edb/src/Microsoft.Framework.PackageManager/Program.cs#L28

**Comment by muratg** [comment]
@pranavkm will you be able to have a look at this one?

@Eilon for prioritizing with the rest of Pranav's items.

**Comment by Eilon** [comment]
@pranavkm please have a stab at this when you have a chance.

**Comment by pranavkm** [comment]
Will do.

**Comment by pranavkm** [comment]
@nguerrera, is this still an issue?

**Comment by nguerrera** [comment]
@pranavkm I believe that it is. We still have --parallel disabled.

**Comment by pranavkm** [comment]
@davidfowl \ @anurse should I investigate this?
