### ISSUE TITLE
Consider shadow copying when loading DLLs

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#219]
Or maybe use `LoadFrom(byte[])`. This is to prevent locking the DLL on disk while working in VS and recompiling, or perhaps doing some other in-place update.

**Comment by Eilon** [comment]
This might be a manifestation of the issue: http://stackoverflow.com/questions/27922532/using-ravendb-embedded-on-asp-net-5-vnext

I *think* that RavenDB is trying to delete and overwrite a DLL on disk and it *might* be failing because *maybe* ASP.NET 5 has already loaded the DLL (and thus it is locked).

**Comment by davidfowl** [comment]
CLosing this due to the new CLI work
