### ISSUE TITLE
Alter the DLL search paths for native to native dependencies

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2193]
When we have a package with native code depending on another package that also have native code, we'll need to modify the search paths for the process so that we are able to load the library.

cc: @blowdart @moozzyk @davidfowl

**Comment by blowdart** [comment]
Modify *how*? What's so special about native to native that they aren't in the same path?

**Comment by muratg** [comment]
Modify by adding the native dll location to the path otherwise dll that depends on the other one will not be able to load it.

**Comment by blowdart** [comment]
How did it get loaded in the first place if it wasn't in the search path already? 

Where does this stop? If the file was in system32 and you now start searching there we have problems

**Comment by muratg** [comment]
These are native dll's not managed.  Also, these will be coming in nupkgs.  @davidfowl can clarify the difference between managed assemblies and native dlls.

**Comment by blowdart** [comment]
Are we expecting the nupkgs to drop them in random directories then?

@davidfowl can you set up some time tomorrow to explain this to me please

**Comment by muratg** [comment]
Closing this, as this is covered in https://github.com/aspnet/dnx/issues/402.
