### ISSUE TITLE
Split NuGetDependencyResolver into LockFileDependencyResolver and NuGetDependencyResolver

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2196]
/cc @anurse @muratg

**Comment by muratg** [comment]
@davidfowl is this just clean up? if so, should we do this later?

**Comment by anurse** [comment]
No, this is part of runtime refactoring

**Comment by glennc** [comment]
@anurse Is this done?

**Comment by anurse** [comment]
No, it can go in beta8

**Comment by anurse** [comment]
@davidfowl didn't you basically do this already?

**Comment by davidfowl** [comment]
Yep
