### ISSUE TITLE
Add host configuration

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#22]
We need a more configurable API and an external file format for changing host (core  CLR) settings.

**Comment by muratg** [comment]
https://github.com/aspnet/XRE/issues/464

@KKhurin do you have any proposals/PRs for this?

**Comment by davidfowl** [comment]
@moozzyk With the recent refactoring is it easy to add command line options in the native code?

**Comment by moozzyk** [comment]
Yes, if they are shown in the host options.

**Comment by davidfowl** [comment]
Irrelevant, new CLI work
