### ISSUE TITLE
'dnu feeds list' shows an unknown entry

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2200]
Following image has the details of my user-specific nuget.config, project specific nuget.config and I am not clear where the 'disabled' entry is coming from:

![image](https://cloud.githubusercontent.com/assets/6559784/8552272/ef1c3b36-2490-11e5-8c9e-99638f693ac9.png)

**Comment by BrennanConroy** [comment]
Do you have any redirect config files?

**Comment by kichalla** [comment]
@BrennanConroy No, I did not have any redirect files when I ran into this

**Comment by BrennanConroy** [comment]
@anurse

**Comment by anurse** [comment]
This is likely related to ye olde NuGet.org getting disabled issue. Ping @davidfowl. It's the main reason we put the new "NuGet" entry into the list (the one that doesn't use `www`)

@kichalla Now that we have `dnu feeds list`, can you try a few things with your local NuGet.config (the last one in your screenshot)? Try removing the `clear` node and the `add key=NuGet` node and see what changes. I haven't heard a super-clear answer of what the exact behavior we're seeing is so this will be helpful :)

**Comment by davidfowl** [comment]
The better fix is to show what nuget config eadh feed originates from. That will avoid this type of confusion

**Comment by glennc** [comment]
We now show the location of the config files, so this shouldn't be an issue anymore.
