### ISSUE TITLE
Unable to setup project to sign assemblies for full Clr and CoreClr

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2206]
Currently it is possible to strong name assemblies for Clr or fake strong name for CoreClr but it is not possible to set up the project so that the assembly is strong named when built for Clr and fake strong named when built for CoreClr

**Comment by davidfowl** [comment]
Why do we need this? When building with Coreclr?

**Comment by moozzyk** [comment]
This came from stackoverflow: http://stackoverflow.com/questions/31001880/signing-asp-net-5-class-library-assemblies/31259763?noredirect=1#comment50521697_31259763
The scenario is you want to build two versions of the same assembly - one for dnx451 and one for dnxcore and you want them both to be signed. It is currently not possible because you cannot set compilation options per framework. Putting all the different values does not work since Roslyn will throw saying that you cannot both fake sign and strong sign the same assembly.

**Comment by davidfowl** [comment]
That doesn't make any sense. If you're using dnx-clr you should be able to create signed class libs if you're on windows.

**Comment by moozzyk** [comment]
(Assuming "this doesn't make any sense" relates to the way the code behaves and not to the scenario). The current behavior is a result of not having framework specific compilation options. On dnx-clr you can both fake strong name and real strong name assemblies. So if both - `keyFile` and `strongName` - are specified we don't decide for the user which one they wanted but pass them both to Roslyn and let the compiler throw (https://github.com/aspnet/dnx/blob/5569c699d8d9ebe81d301a948a55cb2ed5ba2cad/src/Microsoft.Framework.Runtime.Roslyn/RoslynCompiler.cs#L225). 
There is also the opposite scenario - the user specifies `keyFile` in project.json in which case we would currently throw for CoreClr (https://github.com/aspnet/dnx/blob/5569c699d8d9ebe81d301a948a55cb2ed5ba2cad/src/Microsoft.Framework.Runtime.Roslyn/RoslynCompiler.cs#L218-L221). To fix this we could simply ignore `keyFile`/`delaySign` for CoreClr instead of erroring out but the first problem is not that easy to solve. The cleanest solution seems to be to enable specifying framework specific compilation options (in addition to comon compilation options) - e.g. under framework property in project.json.An alternative would be to give real strong naming a higher priority than fake strong naming (if both are present) which - along with ignoring `keyFile`/`delaySign` for CoreClr - would make the scenario work but introduces weird magic into the system.

**Comment by moozzyk** [comment]
I missed the fact that CoreClr can be signed with real strong names and it's not about what the target framework of the assembly being signed but the framework the compilers run on. Fixed!
