### ISSUE TITLE
Debugging into sources and common dependencies

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2215]
Scenario: A and B depend on C. if B and C were added as a source in A's global.json, I was expecting both A and B pointing to the "sources" of C in the solution.

In the following image, the project `Microsoft.AspNet.Hosting` is using a Nuget package instead of the "sources" present in the solution...is this by design?

Note: I know that I need not refer to Logging again in the sample project as it transitively available through Hosting but I simplified the example for this bug.

![image](https://cloud.githubusercontent.com/assets/6559784/8585102/9577b77e-2592-11e5-8434-16f209cb0317.png)

**Comment by davidfowl** [comment]
It is by design because each solution has their own `global.json` and each of those will have to be updated to get sources for your entire closure. See https://github.com/aspnet/dnx/issues/950 for more details

**Comment by davidfowl** [comment]
If you open up the Logging node under your project you should see your project reference. From Hosting's POV it's still referencing the package, but your application is seeing the project for the entire closure.

**Comment by kichalla** [comment]
Thanks @davidfowl
