### ISSUE TITLE
DNU Build fails to find project references when called from Powershell without project.lock.json files

### ISSUE THREAD

**Issue by pprice** [aspnet/dnx#2216]
Howdy.

I have a solution setup with 3 projects using beta5.
- A
- B (References A)
- C (References A, B)

For my CI system I'm using powershell to kick off some final steps before deployment. I can "successfully" install the latest dnx with dnvm, do a `restore` and a `publish`. However I'd like to do a DNU to check for any code or reference errors via `dnu build` but I'm getting build errors due to missing references from project C to B and A. 

From powershell i'm doing a `Start-Process` with `-Working-Directory` set to the solution root, but this always fails, and C seems to _not_ find project's A and B. However if I Invoke `dnu build path\to\c\project.json` from an interactive powershell prompt this appears to work, when automated it does not. I've tracked this down to differences in the `project.lock.json` file, previously I had these checked into source control, and I decided to remove `.gitignore` them due to high churn. Without the `project.lock.json` coming from _source control_ (previously "good") the build will fail, `dnu restore` will generate the lock file, but it seems incorrect. 

If I had to guess there is _something_ (environment variable, base directory etc) not being passed along. The full arguments to `Start-Process` are `dnu -ArgumentList "build "$PathToProjectJson"" -LoadUserProfile -NoNewWindow -PassThru -Wait -WorkingDirectory $SouceRoot` 

Couple of asks: 
- Any ideas what I am doing wrong? I've been stumped on this pretty much all day. 
- Guidance / examples on how to kick off `dnu` correctly from powershell (dnvm works great) 
- Better diagnostics tools for these situations, how does dnu build resolve project references? Diagnostic dumps would be super useful.

**Comment by davidfowl** [comment]
> For my CI system I'm using powershell to kick off some final steps before deployment. I can "successfully" install the latest dnx with dnvm, do a restore and a publish. However I'd like to do a DNU to check for any code or reference errors via dnu build but I'm getting build errors due to missing references from project C to B and A.

You can use `dnu publish --no-source` if you want to published compiled binaries.

> From powershell i'm doing a Start-Process with -Working-Directory set to the solution root, but this always fails, and C seems to not find project's A and B. However if I Invoke dnu build path\to\c\project.json from an interactive powershell prompt this appears to work, when automated it does not. I've tracked this down to differences in the project.lock.json file, previously I had these checked into source control, and I decided to remove .gitignore them due to high churn. Without the project.lock.json coming from source control (previously "good") the build will fail, dnu restore will generate the lock file, but it seems incorrect.

- Assume you always need a lock file.
- dnu restore should make a good one. You don't need to check it in. You should restore then build.

Can you share your project structure? 

> Any ideas what I am doing wrong? I've been stumped on this pretty much all day.

I'd have to see a repro to know that. A minimal one would be good.

> Guidance / examples on how to kick off dnu correctly from powershell (dnvm works great)

The obvious thing should just work without much changes. 

> Better diagnostics tools for these situations, how does dnu build resolve project references? Diagnostic dumps would be super useful.

One thing we don't show when there's build failures is the project search path. We should add that information.

**Comment by pprice** [comment]
Thanks for the quick response @davidfowl. I'll get a repro to you offline.

I played around a little more and I found that If I call restore on ALL project's before attempting the build of the target project, this seems to work. This was non-obvious to me, I would have expected `restore` to talk the dependency graph, or be presented with potentially missing package errors. Instead I got build errors for types from "Project A", as I guess it's dependencies couldn't be fulfilled. 

```powershell
Write-Host "Remove exiting project.lock.json files";
Get-ChildItem *.lock.json -Recurse | Remove-Item;
	
Write-Host "Restoring packages...";
Get-ChildItem project.json -Recurse | % {
    $FullPath = $_.FullName;
    $dnuRestoreCommand = "restore `"$FullPath`"";
   Write-Host "Executing dnu with '$dnuRestoreCommand'";
   _Execute -Command "dnu" -Args $dnuRestoreCommand -ExitOnFailure | Out-Null;   
};
```

`_Execute` is a wrapper around Start-Process

**Comment by davidfowl** [comment]
We need to make restore do this by default.
