### ISSUE TITLE
could not discover the mach TLS offset 

### ISSUE THREAD

**Issue by fishg** [aspnet/dnx#2217]
When upgrade to Yosemite El Capitan 10.11 beta3,can't run dnx:
~/.dnx/runtimes/dnx-mono.1.0.0-beta4/bin/dnx
could not discover the mach TLS offset
Thread 0x7fff7a897000 may have been prematurely finalized

What's the error mean?

**Comment by davidfowl** [comment]
No idea , try updating mono and the dnx.

**Comment by smbecker** [comment]
Looks like that is a low level issue in mono due to it not recognizing the OSX version...

https://github.com/mono/mono/blob/master/mono/utils/mach-support-amd64.c

**Comment by fishg** [comment]
Wait for new mono version.
