### ISSUE TITLE
Minor DNX Changes from API Review

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2222]
Microsoft.Framework.Runtime.Abstractions
* <del>Rename `CompilationMessageSeverity` to `DiagnosticsSeverity`</del> (I'm going to be doing this in #2225 because I'm touching all of these related types -@anurse)
* [ ] Rename `IApplicationEnvironment.Version` to `ApplicationVersion`
* [ ] Move `IAssemblyLoadContextFactory` to `M.F.Runtime.Infrastructure`
* [ ] Rename `IServiceManifest` to `IRuntimeServices`

**Comment by muratg** [comment]
@ChengTian Load balancing this one to you as well :)

**Comment by anurse** [comment]
I'll roll these in to #2225, and just get it done in one big batch of renames.
