### ISSUE TITLE
POCOify and rename Compilation Message interfaces

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2224]
* [ ] `ICompilationFailure` -> POCO `DiagnosticResult`
* [ ] `IDiagnosticResult` -> Removed/merged in to `DiagnosticResult`
* [ ] `ICompilationMessage` -> `DiagnosticMessage`

**Comment by muratg** [comment]
@ChengTian load balancing this to you.

**Comment by anurse** [comment]
Looks like I'll take this on in #2225 anyway. Merging with that.
