### ISSUE TITLE
API Review Refactoring

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2225]
Refactoring Compilation code from DNX API review:

* [x] Rename `Library` to `LibraryIdentity`
* [x] Rename `ILibraryInformation` to `Library` POCO
* <del>Merge `LibraryInformation` and `LibraryDescription` into new POCO class `Library`</del> `LibraryDescription` is an internal runtime class and doesn't need a super clean name. Also, it can't be merged :)
* [x] Move `Microsoft.Framework.Runtime.Caching`-related abstractions into a Compilation-related Abstractions assembly (i.e. not referenced by Apps, only by Compilers)
* [x] Refactor `ICompilationProject` and `IProjectCompiler.CompileProject` arguments into a Context class
* [x] Merge `IFileMonitor` into `IFileWatcher`
* [x] Consider stripping down `IProjectFilesCollection` to a set of flattened lists (i.e. resolve all the globs) and embedding in the Context class that `ICompilationProject` becomes
* [x] POCOify `ILibraryKey` to `LibraryKey`
* [x] Rename `LibraryKey` to `CompilationTarget`
* [x] `ICompilationFailure` -> POCO <del>`DiagnosticResult`</del> `CompilationFailure` (this is specific to compilation, not a general-purpose diagnostic result)
* [x] `IDiagnosticResult` -> POCO `DiagnosticResult`
* [x] `ICompilationMessage` -> `DiagnosticMessage`
* [x] Rename `IApplicationEnvironment.Version` to `ApplicationVersion`
* [x] Move `IAssemblyLoadContextFactory` to `M.F.Runtime.Infrastructure`
* [x] Rename `IServiceManifest` to `IRuntimeServices`
* <del>Add `Stream ISourceReference.OpenRead()`</del> We're not doing this, it's optimizing for a future we're not even sure about.

**Comment by davidfowl** [comment]
Here are my notes https://gist.github.com/davidfowl/eedd4a3ec4e49d35bef3. I have a branch with some changes where I started some of the work.

**Comment by anurse** [comment]
@davidfowl Remind me why we want `OpenRead` on ISourceReference? It seems to be useless since we already need to try-cast in all the cases we use it to get the Path for file watching.

**Comment by anurse** [comment]
![image](https://cloud.githubusercontent.com/assets/7574/8680190/8009ca90-2a14-11e5-8e50-8f487252daa0.png)

?

:trollface: (I'm going to use `CompilationTarget` for now)
