### ISSUE TITLE
Error opening nuget package in package explorer

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2227]
Not sure if is this expected or if that we are not populating some details which the explorer is not able to understand...
 
![image](https://cloud.githubusercontent.com/assets/6559784/8604121/4c34ff00-2631-11e5-9066-d4f4407151ad.png)

**Comment by anurse** [comment]
This is expected. NuGet Package Explorer has not been updated to support the various new frameworks and until that happens, these kind of errors occur. NPE is an external tool, so we'll need to work with the author to update to support this.

Ping @Eilon @davidfowl
