### ISSUE TITLE
Empty web app + class lib, we get a warning when we build the solution

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#2229]
Dev14 RTM (beta5)

1. File > New Project > ASP.NET 5 Class Library
2. Add New Project > Empty App
3. Add reference from empty app to KClassLibrary1
4. Build solution
 
**ACTUAL**
Warning from the web app build

1>------ Build started: Project: KClassLibrary1, Configuration: Debug Any CPU ------
1>
1> Build succeeded.
1> 0 Warning(s).
1> 0 Error(s).
1>
1> Time elapsed 00:00:01.7185686
1>
2>------ Build started: Project: EmptyApp1, Configuration: Debug Any CPU ------
2>c:\users\balach\documents\visual studio 2015\Projects\KSolution1\src\KClassLibrary1\project.json(13,23): DNX Core 5.0 warning : Dependency specified was System.Runtime >= 4.0.10-beta-23019 but ended up with System.Runtime 4.0.20-beta-23019.
2>
2> Build succeeded.
2> 1 Warning(s).
2> 0 Error(s).
2>
2> Time elapsed 00:00:00.5468843
2>
========== Build: 2 succeeded or up-to-date, 0 failed, 0 skipped ==========
 
 **EXPECTED**
No warning

**Comment by muratg** [comment]
@davidfowl @troydai

**Comment by davidfowl** [comment]
I'll take this one.

**Comment by muratg** [comment]
:watch:

**Comment by davidfowl** [comment]
Pretty sure this wont' make it for beta6. Can we make this an escrow bug? /cc @muratg @danroth27 @DamianEdwards

**Comment by davidfowl** [comment]
Back logging this. We made some attempts to fix this but it was messy so punting.

**Comment by davidfowl** [comment]
irrelevant with the CLI
