### ISSUE TITLE
Add actual dnu restore integration test case

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2231]

**Comment by davidfowl** [comment]
Turns out we do have restore tests /cc @ChengTian

**Comment by troydai** [comment]
We have a restore test in name which actually test the pre restore script execution only. But there is a `install command` case test, which we can borrow.

**Comment by ChengTian** [comment]
I am adding a functional test for `dnu restore` in this PR: https://github.com/aspnet/dnx/pull/2232/files#diff-edbeb3b05a45a6c482241e1d17d0c4d1R153

In new functional test infrastructure, we should add some utils for creating some fake packages and put them to a local feed.

**Comment by ChengTian** [comment]
Some utils and a `dnu restore` functional test was added to new functional test infrastructure prototype: https://github.com/davidfowl/DnxTestingPrototype/commit/71e1dc99de1ba223b3432d4abd9ab6b5a17ae8a6

**Comment by ChengTian** [comment]
We can add more functional tests for `dnu restore` when new test infrastructures are in use later. However, that will happen after beta 6.

Talked to @troydai , we can still add `dnu restore` tests with old test infrastructures. So this is not a blocking issue, moving to beta 7.

**Comment by ChengTian** [comment]
This should be part of https://github.com/aspnet/dnx/issues/1844

**Comment by ChengTian** [comment]
We already added some functional tests with old test utils: https://github.com/aspnet/dnx/blob/dev/test/Microsoft.Dnx.Tooling.FunctionalTests/DnuRestoreTests.cs

Should add more while porting to new test utils
