### ISSUE TITLE
Is NuGet.redirect.Config supported in non-Windows platforms?

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2233]
On my Linux machine the content in NuGet.Redirect.Config is not being picked up. Is this supported?

![image](https://cloud.githubusercontent.com/assets/6559784/8607363/38aa834a-2647-11e5-9c85-8ba74c842010.png)

**Comment by davidfowl** [comment]
It's likely a casing problem. It should be all lowercase (unfortunately) `nuget.redirect.config`

**Comment by anurse** [comment]
That is unfortunate given that the config is required to be `NuGet.Config`. Can we normalize the casing for all those files in both DNX and NuGet? We can support the old casings but in general, all lowercase is the pattern used for this kind of file.

**Comment by muratg** [comment]
With different casing support in, closing this one. @kichalla feel free to reactivate if `nuget.redirect.config` doesn't work for you.

**Comment by pranavkm** [comment]
Is the redirect config something we plan on supporting in RTM? NuGet doesn't have this feature.

**Comment by muratg** [comment]
I believe longer term plan is to make nuget and dnu be as similar as possible for a lot of the scenarios, although dnu would have additional functionality that nuget doesn't need to support. 

Good point though, if we need to remove the redirection, we better do it in RC1 @davidfowl
