### ISSUE TITLE
We need a mechanism to pass exception details to native code

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2235]
To "fix" #1825 and prevent from Access Violations we catch the exception before it escapes managed code and turn into an error/HRESULT. This way we are loosing all exception details. In addition native parts of the code just write to the stdout in case of errors but in some scenarios (like Helios) it's useless because there isn't really stdout. 
The idea is to create another dll which would contain an error sink. It will be used by both managed Managed (P/Invoke) and native code to report errors that occurred during application startup. Users should also be able to plug-in to the error sink to be able to observe these errors.

Some additional context here: https://github.com/aspnet/Helios/pull/179

**Comment by davidfowl** [comment]
This is pretty important to do. Any exception that happens before the application boots up shows:

![image](https://cloud.githubusercontent.com/assets/95136/9022279/b28c7d14-3824-11e5-8270-b14b513a7c5d.png)
