### ISSUE TITLE
Add `--framework` flag to `dnu publish` command

### ISSUE THREAD

**Issue by friism** [aspnet/dnx#2238]
This would be useful to me, at least: I'm building for a known framework, and I don't want to spend time and space creating dlls for other frameworks

**Comment by anurse** [comment]
Makes some sense to me. Similarly, if for some reason the app has both `dnx46` and `dnx451` in the project.json, this could allow the user to choose the version we will write in to `web.config`.

Thoughts @davidfowl ? It seems like it's basically just the same as letting you constrain `dnu build` by framework.

**Comment by davidfowl** [comment]
Was added
