### ISSUE TITLE
Can not restore package `System.Runtime.Extensions`

### ISSUE THREAD

**Issue by anfomin** [aspnet/dnx#2241]
If I add dependency to EF then I get package restore error:
```
Error: DownloadPackageAsync: https://www.myget.org/F/aspnetvnext/api/v2/package/System.Runtime.Extensions/4.0.0-beta-23109
  Response status code does not indicate success: 404 (Not Found).
```
I'm using latests DNX `1.0.0-beta6-12207`.

**Comment by davidfowl** [comment]
This is on windows right?

**Comment by anfomin** [comment]
Yes, Windows 10 build 10162. Yesterday it was ok, but today throws exception.

**Comment by anfomin** [comment]
I was investigating why old assembly version `4.0.0-*` is downloaded however newer one `4.0.10-*` exist. Some other DNX Core libraries use version `4.0.0`:
https://github.com/dotnet/corefx/issues/2304

**Comment by davidfowl** [comment]
/cc @Eilon @maartenba Looks like something bizzare going on with the myget feed. The query for finding all versions is there but it looks like the blob is missing somehow.

Minimal repro:

```
{
    "dependencies" : {
        "System.Runtime.Extensions": "4.0.0-beta-23109"
    },
    "frameworks": {
        "dnx451": {}
    }
}
```

`dnu restore --no-cache -s https://www.myget.org/F/aspnetvnext/api/v2`

**Comment by maartenba** [comment]
Seems the binary is indeed gone, may have to do with @eilon's retention policy update this morning. Any chance you can re-upload it if needed?

**Comment by Eilon** [comment]
Hmm yeah that might be it... I changed the setting back on the `aspnetvnext` feed and am working on re-uploading the packages.

Does MyGet do package retention based on what SemVer defines as "oldest" as opposed to the packages that were the oldest ones uploaded in terms of time? That might affect this. (Not saying MyGet is wrong, but it might not be exactly what we want.)

**Comment by maartenba** [comment]
SemVer indeed

**Comment by Eilon** [comment]
Ok the old packages should be uploaded again.

I think the issue was that these packages have a mix of `4.0.0-*`, `4.0.10.*`, and `4.0.20-*`, and we kind of want the most recent of each of these.

**Comment by anfomin** [comment]
Now I'm getting restore error for each project:
```
Unable to locate System.Reflection.Primitives >= 4.0.0
```

However there are 3 versions installed after the restore:
```
4.0.0-beta-23029
4.0.0-beta-23109
4.0.0-beta-23110
```
And I can build & run my projects.

**Comment by troydai** [comment]
The problem is that _System.Resources.ResourceManager/4.0.0-beta-23110_ dependes on _System.Reflection/4.0.0_ which looks for _System.Reflection.Primitive/4.0.0_ and it's missing.

We need to retired 23110 series of CoreCLR packages from vNext feed.

**Comment by anfomin** [comment]
@Eilon any news when **System.Reflection.Primitive/4.0.0** will be restored?

**Comment by troydai** [comment]
Hi @anfomin, sorry for the trouble. I'm working on this right now. Hopefully we can solve this today.

**Comment by troydai** [comment]
@anfomin please clean your packages cache and try https://www.myget.org/F/aspnetvnext/api/v2 feed again. We unlisted the wrong packages. If you're sure about what's the local cache to clear up, you use this script https://github.com/troydai/k.toolkit/blob/master/clean-packages.py.

**Comment by anfomin** [comment]
Thank you! Restore works without error now.

**Comment by troydai** [comment]
Cheers.
