### ISSUE TITLE
Cannot build web application project after upgrading to beta 5

### ISSUE THREAD

**Issue by mbharodia** [aspnet/dnx#2242]
I upgraded web application project to use beta 5. I have made sure that all the references are proper in project.json file. I am not able to build the project. As shown in the image Visual Studio 2015 complains about overloaded method. I see that parameters do match to the method signature. I am not sure why it is like this. 

Additionally the error list shown in VS has code CS1501. Searching that on internet indicates that the compiler version may be out of date. 

Is it a compiler issue? How do I make sure that I have updated compiler version

![error](https://cloud.githubusercontent.com/assets/10344641/8618390/0370889e-26cb-11e5-8af5-b7f0039e9a32.png)

**Comment by CuddleBunny** [comment]
The last parameter doesn't take `shouldLockout` anymore. I got it working by changing it to:

    SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

**Comment by mbharodia** [comment]
Hi Josh,

Thanks a lot for reply. I will double check that.

However, earlier, as soon as I looked into error code suggested by VS, I was all into that. I did not think about modifying anything else. Good suggestion. I will update the codebase and let you know.

**Comment by davidfowl** [comment]
Please open issues like these on aspnet/Home.
