### ISSUE TITLE
Support publishing any 'dnx' framework with a CLR runtime

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2246]
Right now, if you `dnu publish --runtime [some CLR variant]` and your project has `dnx452` and `dnx46` as the only target framework, you will get this error:

```
'DNX,Version=v4.5.1' is not a target framework of the project being published
```

We should change this code so that publish will accept `dnx452` and `dnx46` as well. I almost have a fix ready for this. It is blocking some Helios work.

**Comment by muratg** [comment]
:+1:
