### ISSUE TITLE
build failed when embedding the js files which locate outside of the current project folder.

### ISSUE THREAD

**Issue by yangyang80** [aspnet/dnx#2255]
When I create a VNext classlibrary project based on the released beta5 via vs2015rc, if I embed some special js files which locate outside of the current project folder, the build would fail.  It is fine in beta4.
Steps to reproduce:
1.create a classlibrary project.
2. create a folder "resources" which locates in the same folder where the folder of the classlibrary solution locates.
In "resources", create two folders: "shared" and "my". Simply create a js file called "mytest.js" and leave it empty. Copy it to the two folders "shared" and "my".
3. Open the project.json file of the classlibrary project and add the following node into it:
  "resource": [
    "../../../resources/**/*.*"
  ]
4. Check the item "Produce outputs on build" of the classlibrary project to make sure the packages would be generated when building the project.
5. Build the project, you would find the following error information shows:
Error	 error CS1508: Resource identifier 'ClassLibrary1.control.js' has already been used in this assembly	ClassLibrary1.

I find it is because the names of the js files are same, although they locate in different folders. When embedding them, the folder would be ignored to generate the resource identifier. Only the current project namespace would be appended. If I copy the resources folder to the path where the project.json file locates and update the resource node in the project.json file, it works.
This issue only reproduces when using beta5. It is fine in beta4. 
Is it a bug of beta5?

**Comment by victorhurdugaci** [comment]
it's a known limitation. Resources outside of the project folder are named using the file name. If two files have the same name, you'll get a naming conflict.
 
Use named resources to solve the conflict 
https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/project.json#L12

**Comment by yangyang80** [comment]
@victorhurdugaci  thanks for your reply. When I open the link you provided, it reported the page is not found. Please confirmed whether the link is correct.

**Comment by victorhurdugaci** [comment]
@yangyang80 here's an updated link. The other one didn't work because the EF packages got renamed: https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework7.Commands/project.json#L13-L14

**Comment by yangyang80** [comment]
Thanks a lot. It works.
