### ISSUE TITLE
dnx command fails while regenerating migration template while mirgration from beta 4 to beta 5

### ISSUE THREAD

**Issue by mbharodia** [aspnet/dnx#2256]
As per announcement https://github.com/aspnet/Announcements/issues/35#issuecomment-120981504 I have tried regenerating the migration but it fails. The following was an error message generated.

![image](https://cloud.githubusercontent.com/assets/10344641/8649479/f79c17e0-2927-11e5-8828-0a804ab13f70.png)
Any idea to fix it ?

I am running this command at a location where project.json file exists as shown below.

![image](https://cloud.githubusercontent.com/assets/10344641/8649572/def2ddae-2928-11e5-90dd-0459ca43ba23.png)

**Comment by muratg** [comment]
Can you paste your project.json?

**Comment by mbharodia** [comment]
Here it is. Thanks a lot for looking into this.
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-CCClientWeb-8bbc0c70-ab78-4053-a5bf-492342d52f2a",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta5",
    "EntityFramework.Commands": "7.0.0-beta5",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta5",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta5",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta5",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta5",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta5",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
    "Microsoft.Framework.Configuration": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*",
    "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta5",
    "Microsoft.Framework.Logging": "1.0.0-beta5",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta5",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta5",
    "Microsoft.AspNet.Identity": "3.0.0-beta5"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
    "gen": "Microsoft.Framework.CodeGeneration",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.AspNet.Http.Core": "1.0.0-beta4",
        "CCClients.Interfaces": "1.0.0-*"
      }
    },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }
}

**Comment by muratg** [comment]
Looks fine to me, not sure why it may be throwing.  @troydai any ideas?
