### ISSUE TITLE
Issue running dnz after installing Mac OS X 10.11 public beta

### ISSUE THREAD

**Issue by lukemurray** [aspnet/dnx#2257]
Have run dnvm upgrade, it tells me I have this version dnx-mono.1.0.0-beta5.

If I try "dnx . test" (or the web command) I get the following:
```
could not discover the mach TLS offset
Thread 0x7fff77d67000 may have been prematurely finalized
```

I couldn't find a new issue for this, and google didn't bring up much. Have I missed something, or is this known at least?

**Comment by davidfowl** [comment]
Looks like a mono bug. I'd suggest reporting it on their issue tracker

**Comment by smbecker** [comment]
dup of #2217
