### ISSUE TITLE
Dependancy version conflicts solving

### ISSUE THREAD

**Issue by Ph47** [aspnet/dnx#2264]
Good day!

In my project i have two dependencies what have another dependencies both to same package but different version.

For example EntityFramework and Lucene.Net.Linq:
EntityFramework (7.0.0-beta5-13549)
EntityFramework.Commands (7.0.0-beta5-13549)
EntityFramework.Relational.Design (7.0.0-beta5-13549)
EntityFramework.Relational (7.0.0-beta5-13549)
EntityFramework.Core (7.0.0-beta5-13549)
Remotion.Linq (2.0.0-alpha-002)

Lucene.Net.Linq (1.0.22)
Remotion.Linq (1.13.183.0)

But actually both dependencies resolves to 2.0.0-alpha-002 on my project. NuGet packages link to correct versions in Lucene.Net.Linq.nuspec and EntityFramework.Core.nuspec.

I found no way to resolve conflict through project.config.

We need a right way to use different version of subdependencies for each dependancy.

**Comment by davidfowl** [comment]
Is there an actual conflict? What are you trying to resolve?

**Comment by Ph47** [comment]
I am trying to allow EntityFramework use version 2.0.0-alpha-002 of Remotion.Linq and Lucene.Net.Linq - 1.13.183.0. But i cant find a way to make this move. 

DNX compile silently my project with one version of this package if i add direct dependency to project.config. Without direct dependency DNX silently substitutes version for Lucene.Net.Linq with newer one from EntityFramework.

This is not good behavior. DNU must at least make a warring or use different versions at once.
I can upload sample if you need it.

**Comment by davidfowl** [comment]
@Ph47 That's actually not how any of this works. You should take a look at this documentation https://github.com/aspnet/Home/wiki/Dependency-Resolution and after, show the `project.json` and the *exact* problems you're running into and I'll be able to show you how to fix it.

**Comment by Ph47** [comment]
I understand how it work now. But is a mistake here. Looks at figure 3 at this document. I have this situation at Remotion.Linq - low version dependency silently replaced with high version. Nobody cares about version compatibility. 

Because of this approach, I spent two hours to understand exactly where the error is. Nor DNU nor runtime displays actual error ("Version conflict"). Instead of this a actual execution error was displayed ("No such method").

Back to figure 3: we need a solution where package A use package B version 1.0 and SAME TIME package C use package B version 2.0. It can be a problem if classes flows from package, but if usage is internal for package it is possible to implement.

At article we have a text: 
>Today, because the resolver treats versions as minimums, that generally means the highest version wins. However, if version ranges are introduced in the future the algorithm will need to choose the best version that fits within the range constraints. This could mean that the highest version is not chosen or that the runtime throws an exception due to irreconcilable range differences.

I mean what we need at least "...the runtime throws an exception..." but we have nothing.

My project file here: https://gist.github.com/Ph47/9b50dba0adf992ed0fad but i have no ided how you can fix this with strategies described in article - none will works.

**Comment by davidfowl** [comment]
> I understand how it work now. But is a mistake here. Looks at figure 3 at this document. I have this situation at Remotion.Linq - low version dependency silently replaced with high version. Nobody cares about version compatibility.

It's not silent, it's how NuGet works. Versions are a minimum so they float when another dependency requires a higher version. That's actually how most systems work. Exact versions are terrible to use and stop things from working most of the time.

> Because of this approach, I spent two hours to understand exactly where the error is. Nor DNU nor runtime displays actual error ("Version conflict"). Instead of this an actual execution error was displayed ("No such method").

Again, it's not a bug, it's absolutely by design and intentional. Seems like you have a true incompatiblity and you need to talk to the package owners about updating their package to work?

> However, if version ranges are introduced in the future the algorithm will need to choose the best version that fits within the range constraints.

That is actually incorrect and we'll need to get our document fixed /cc @glennc. Adding maximums simply makes things fail and today, we don't check them and that *is* a bug. But I'm not even sure that's what you're running into.

If you want to force your project to use a particular version of a dependency, specify it in your project.json directly. It will override anything up the dependency chain with your version. If that combination is truly incompatible then you need to figure out something else.

> My project file here: https://gist.github.com/Ph47/9b50dba0adf992ed0fad but i have no ided how you can fix this with strategies described in article - none will works.

Can you narrow down your project.json to a minimal one that reproduces the problem and call out which versions are used where?

**Comment by davidfowl** [comment]
> We need a right way to use different version of subdependencies for each dependancy.

@Ph47 So you actually want side by side loading (which has its own problems). That doesn't work and will not work for the forseeable future. You are at an impass and need to use compatible dependencies.

**Comment by Ph47** [comment]
So make at least an error or warring message about conflicts at build time. It is quiet now.

**Comment by davidfowl** [comment]
You'd need to talk to the package owners about that. We can have a greater discussion about jumping past major versions triggering a warning.

**Comment by Ph47** [comment]
At Least major version conflict needs a warring. It is really hard to find problem if you don't think about versions of subdependencies. I know none of developers who investigate entire tree of dependencies before installing package. May be level 1 or 2 no more. 

Package owner already notified: https://github.com/themotleyfool/Lucene.Net.Linq/issues/86

No more discussion from me because as you heard me and understood.
