### ISSUE TITLE
First Chance Exception on Windows when finding which OS user is on

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2265]
Throwing line: https://github.com/aspnet/dnx/blob/dev/src/dnx.host/NativeMethods.cs#L16

@muratg @davidfowl

**Comment by davidfowl** [comment]
This is the cause https://github.com/aspnet/dnx/blob/dev/src/dnx.host/RuntimeEnvironment.cs#L28

**Comment by muratg** [comment]
@BrennanConroy were you already looking into this one?

**Comment by BrennanConroy** [comment]
1d23ce503d5a2b305320cd1c7c607d5e5e4efc03
