### ISSUE TITLE
Command-line build fails for DNX projects when global.json is empty.

### ISSUE THREAD

**Issue by mpiroc** [aspnet/dnx#2266]
When a vanilla DNX project is created, a `global.json` file containing the `sdk.version` property is generated. When a Service Fabric DNX project is created, an empty `global.json` file is generated (see https://github.com/aspnet/dnx/issues/1654).

If `global.json` is missing the `sdk.version` property, command-line builds fail. This is because the `GetRuntimeToolingPath` task (`$/DevDiv/Offcycle/WPT/WebToolsExtensions/Main/src/ProjectK/MSBuildTasks/GetRuntimeToolingPath`) throws an exception if `sdk.version` is missing from `global.json`. This task is invoked by `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets`.

There are two approaches we could take to fix this:
1. Make sure `global.json` is generated with an `sdk.version` property (it should probably be `beta4` for now).
2. Modify the build targets to use a default value (`latest`?) if the `sdk.version` property does not exist.

The issue if we only take the second approach is that Service Fabric doesn't currently support `latest` (beta5). So if we generate an empty `global.json`, and the msbuild targets default to `latest`, it will break Service Fabric customers. So ideally, we would implement both approaches.

**Comment by muratg** [comment]
@mayurid @PradeepKadubandi this should probably go into Tooling repo.
