### ISSUE TITLE
NuGet-related paths/files should be case-sensitively consistent

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2270]
`NuGet.Config` or `NuGet.config`?
`NuGet.redirect.config` or `NuGet.Redirect.config`?
We should enforce consistency in `PackageManager` (specifically under `NuGet` namespace) as part of cross-plat efforts.

**Comment by muratg** [comment]
@pranavkm IIRC, you had a check-in related to this. Is this fixed and good to close?

**Comment by pranavkm** [comment]
For most parts - there's one missing piece that I'll have a look at: https://github.com/aspnet/dnx/issues/2747

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/dnx/issues/2747
