### ISSUE TITLE
Dnu publish should use IPackagePathResolver to resolve package path

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2273]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/Publish/PublishPackage.cs#L28

**Comment by davidfowl** [comment]
@troydai Why isn't this issue closed and tagged and put in a milestone?

**Comment by davidfowl** [comment]
@troydai problems here:

- No bug or enhancement tag
- No assigned person
- Fix not linked to commit

/cc @muratg
