### ISSUE TITLE
Make CLI error messages less verbose

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2274]
Error responses are too verbose. For example, misspelling a command name leads to this massively ugly stack trace.

<img width="716" alt="screen shot 2015-07-16 at 10 50 04 am" src="https://cloud.githubusercontent.com/assets/2696087/8729441/80c74c92-2ba8-11e5-8941-f0485ac971d8.png">

What if instead it was simplified to something like:

```
$ dnx . kesterl
Error: Invalid command name 'kesterl'

Available commands:
     kestrel
     web
```

**Comment by muratg** [comment]
Dup: https://github.com/aspnet/dnx/issues/1923
