### ISSUE TITLE
Figure out a better way to test "dnu commands install"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2279]
Currently we redirect `USERPROFILE` to some temporary folder and install to that fake home dir. However, if later we change the approach to resolve home dir by using `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` here:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.PackageManager/Install/AppCommandsFolderRepository.cs#L149
changing value of `USERPROFILE` can no longer affect the resolved home dir.

We need to figure out a better way to test `dnu commands install`.

@victorhurdugaci @BrennanConroy

**Comment by victorhurdugaci** [comment]
We can probably add an environment variable to specify where global commands are installed

**Comment by ChengTian** [comment]
:+1:

**Comment by victorhurdugaci** [comment]
However... that is a little flaky because the folder specified in that env var must be on the path
