### ISSUE TITLE
Create a unified "RuntimeInfo" class

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2285]
It would be nice to have a central class to retrieve information about a specific DNX runtime:

* CLR Flavor
* OS
* Architecture
* Version
* Supported Frameworks
* etc.

/cc @davidfowl @muratg Suggest for beta7 (and I'm happy to take it on).

**Comment by moozzyk** [comment]
#1970 is kind of related - OS, Architecture etc. should be passed from the native layer.

**Comment by anurse** [comment]
It is related, but (and I should have called this out clearer in the bug) this is more about asking for this information for a **different** runtime (i.e. given the name of the runtime), not for the currently executing runtime. Right now we have some string parsing code in multiple places.

**Comment by muratg** [comment]
Seems like a nice to have to me. I'm OK to do it in beta 7 though with lower pri than other items.
