### ISSUE TITLE
How to uninstall DNX and DNVM?

### ISSUE THREAD

**Issue by lleraromero** [aspnet/dnx#2287]
Hi,

I would like to know how to uninstall dnvm and dnx, so I could manage the runtimes myself. How should I do it?

Thankk

**Comment by anurse** [comment]
DNX **is** the runtime, so if you just want to manage the runtimes yourself, you shouldn't remove it :). You can delete the ones installed by DNVM by emptying the `C:\Users\[username]\.dnx\runtimes` folder.

DNVM can be removed by simply deleting the `dnvm.cmd` and `dnvm.ps1` files from `C:\Users\[username]\.dnx\bin`.

Out of curiosity, why do you want to manage the runtimes yourself? Do you have suggestions for how DNVM could be improved to better serve your needs?

**Comment by lleraromero** [comment]
Thank you very much for you answer. 

I'm actually building an application on top of .NET Core, but right now there are no plans to include DNX as a dependency in my deployment. So basically, I wanted to be sure that my environment is not aware of CoreCLR unless I explicitly specify it.

So far, you have being doing a great job :).

**Comment by per-samuelsson** [comment]
@anurse 

> DNX is the runtime, so if you just want to manage the runtimes yourself, you shouldn't remove it :). You can delete the ones installed by DNVM by emptying the C:\Users\[username]\.dnx\runtimes folder.

> DNVM can be removed by simply deleting the dnvm.cmd and dnvm.ps1 files from C:\Users\[username]\.dnx\bin.

You guys should consider putting those lines somewhere in the basic docs, like in the overview or (possibly better) in some Getting Started context. It's the kind of stuff that is trivial to you, and once you get to know it, but probably in the heads of quite a few developers learning dnx.

Furthermore, it is also good in a marketing kind of way, since it really shows this great new stuff you do really *is* about getting away from global locations, GAC, registry and what not (i.e. going towards xcopy like approach). And thats one of the things that really excite a lot of people IMO.

**Comment by per-samuelsson** [comment]
> [...] in some Getting Started context

Maybe [here](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-standalone) (for Windows), or just some hint / link to a section about it at least.

**Comment by anurse** [comment]
https://github.com/aspnet/Docs/blob/master/aspnet/getting-started/installing-on-windows.rst :wink: just sayin'

Feel free to at least log an issue on https://github.com/aspnet/Docs, but if you feel so inclined, you can send a pull request and fix it yourself! (speaking of wonderful things in this new world!)

**Comment by per-samuelsson** [comment]
> [...] send a pull request and fix it yourself! (speaking of wonderful things in this new world!)

Couldn't agree more. Most def will! :+1:

**Comment by ivanbuhov** [comment]
`dnvm uninstall` command [was added](https://github.com/aspnet/dnvm/pull/375) recently, so you can use it to remove unused `dnx` versions.
Example:
````
dnvm uninstall 1.0.0-beta8 -r clr -arch x86
````

**Comment by sulhome** [comment]
@ivanbuhov using dnvm uninstall is giving "Unknown command: 'uninstall'"

**Comment by anurse** [comment]
Try using `dnvm update-self` to ensure you have the latest version of dnvm with the new command.

**Comment by sulhome** [comment]
@anurse 100%. thank you

**Comment by ivanbuhov** [comment]
@sulhome, `dnvm uninstall` was added in `1.0.0-beta8`, so I guess you have an older version. Try running `dnvm update-self` to update to the latest version of `dnvm` tool and `dnvm uninstall` command should appear.You can also run
```
dnvm
```
and a list wih all existing commands will appear. The `uninstall` command should be there.

**Comment by ElanHasson** [comment]
How can you actually remove dnvm? My understanding is that it is no longer needed.

**Comment by pranavkm** [comment]
Deleting `%UserProfile%/.dnx/` on Windows or `~/.dnx` on OSX \ Linux should remove the dnvm command along with any other DNX binaries that came with it. If you have old VS tooling installed, updating to the `preview2` tooling should remove copies installed by VS.
