### ISSUE TITLE
We need to close on options design

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2289]
http://stackoverflow.com/questions/31485311/configure-a-component-in-asp-net-5

**Comment by glennc** [comment]
@divega where is this at now?

**Comment by divega** [comment]
I don't think there is anything actionable left here. For DI, we decided to remove the `ConfigureXyz()` methods and have the `AddXyz()` methods take `Action<TOptions>` more consistently. We are still working on making the usage in middleware more consistent and simple. That is tracked at https://github.com/aspnet/Options/issues/78. 

cc @HaoK
