### ISSUE TITLE
No IsValueType property in System.Type.

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/dnx#2299]
Hi,

I just migrated a project from full .NET and discovered this property is missing.
Neither does `IsAssignableFrom` work.

**Comment by davidfowl** [comment]
All of those methods have moved to Type.GetTypeInfo(). For further details file an issue on https://github.com/dotnet/corefx

**Comment by weitzhandler** [comment]
I can't find `Type.GetTypeInfo`. Here's a snippet from the `Type` metadata:

    #region Assembly System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    // C:\Users\weitz\.dnx\packages\System.Runtime\4.0.20-beta-23019\ref\dotnet\System.Runtime.dll
    #endregion
    
    namespace System
    {
      public abstract class Type
      {
        public static readonly Type[] EmptyTypes;
        public static readonly object Missing;
    
        public abstract string AssemblyQualifiedName { get; }
        public abstract Type DeclaringType { get; }
        public abstract string FullName { get; }
        public abstract int GenericParameterPosition { get; }
        public abstract Type[] GenericTypeArguments { get; }
        public bool HasElementType { get; }
        public virtual bool IsArray { get; }
        public virtual bool IsByRef { get; }
        public abstract bool IsConstructedGenericType { get; }
        public abstract bool IsGenericParameter { get; }
        public bool IsNested { get; }
        public virtual bool IsPointer { get; }
        public abstract string Name { get; }
        public abstract string Namespace { get; }
        public virtual RuntimeTypeHandle TypeHandle { get; }
    
        public static Type GetType(string typeName);
        public static Type GetType(string typeName, bool throwOnError);
        public static Type GetType(string typeName, bool throwOnError, bool ignoreCase);
        public static Type GetTypeFromHandle(RuntimeTypeHandle handle);
        public bool Equals(Type o);
        public override bool Equals(object o);
        public abstract int GetArrayRank();
        public abstract Type GetElementType();
        public abstract Type GetGenericTypeDefinition();
        public override int GetHashCode();
        public abstract Type MakeArrayType();
        public abstract Type MakeArrayType(int rank);
        public abstract Type MakeByRefType();
        public abstract Type MakeGenericType(params Type[] typeArguments);
        public abstract Type MakePointerType();
        public override string ToString();
      }
    }

**Comment by weitzhandler** [comment]
@davidfowl I can't find `Type.GetTypeInfo`. Here's a snippet from the `Type` metadata:

    #region Assembly System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    // C:\Users\weitz\.dnx\packages\System.Runtime\4.0.20-beta-23019\ref\dotnet\System.Runtime.dll
    #endregion
    
    namespace System
    {
      public abstract class Type
      {
        public static readonly Type[] EmptyTypes;
        public static readonly object Missing;
    
        public abstract string AssemblyQualifiedName { get; }
        public abstract Type DeclaringType { get; }
        public abstract string FullName { get; }
        public abstract int GenericParameterPosition { get; }
        public abstract Type[] GenericTypeArguments { get; }
        public bool HasElementType { get; }
        public virtual bool IsArray { get; }
        public virtual bool IsByRef { get; }
        public abstract bool IsConstructedGenericType { get; }
        public abstract bool IsGenericParameter { get; }
        public bool IsNested { get; }
        public virtual bool IsPointer { get; }
        public abstract string Name { get; }
        public abstract string Namespace { get; }
        public virtual RuntimeTypeHandle TypeHandle { get; }
    
        public static Type GetType(string typeName);
        public static Type GetType(string typeName, bool throwOnError);
        public static Type GetType(string typeName, bool throwOnError, bool ignoreCase);
        public static Type GetTypeFromHandle(RuntimeTypeHandle handle);
        public bool Equals(Type o);
        public override bool Equals(object o);
        public abstract int GetArrayRank();
        public abstract Type GetElementType();
        public abstract Type GetGenericTypeDefinition();
        public override int GetHashCode();
        public abstract Type MakeArrayType();
        public abstract Type MakeArrayType(int rank);
        public abstract Type MakeByRefType();
        public abstract Type MakeGenericType(params Type[] typeArguments);
        public abstract Type MakePointerType();
        public override string ToString();
      }
    }

**Comment by davidfowl** [comment]
That's because it's an extension method brought in by System.Reflection

**Comment by weitzhandler** [comment]
Thank you!
