### ISSUE TITLE
beta7: Microsoft.DNX.PackageManager.dll could not be found

### ISSUE THREAD

**Issue by Grinderofl** [aspnet/dnx#2300]
DNX: 1.0.0-beta7-12255, x86, coreclr & clr both

Using Visual Studio 2015 REL

*Steps:*
Set DNX to beta7-12255
Run Visual Studio
Create new project -> Choose ASP.NET Console project.

*Expected:*
Project is loaded, Program.cs is opened, there are no errors, warnings, red keywords/identifiers or squigly lines. "Build" should build the project. "Start" should run the project.

*Actual:*
Project is loaded, Program.cs is opened, there are no errors or warnings. class names and types from other packages (void, string, System...) are colored red (not found). "Build" produces the following output: http://pastebin.com/Yq2rE1q0, "Start" yields "The debugger cannot continue running the process. Unable to start debugging" error.

*Workaround:*
Use 1.0.0-beta6-12161

This started occurring after upgrading VS2015 from RC to REL.

global.json
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta7-12255",
    "runtime": "clr",
    "architecture": "x86"
  }
}
```

project.json
```
{
  "version": "1.0.0-*",
  "description": "ConsoleApp8 Console Application",
  "authors": [ "Nero" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
  },

  "commands": {
    "ConsoleApp8": "ConsoleApp8"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23019",
        "System.Console": "4.0.0-beta-23019",
        "System.Linq": "4.0.0-beta-23019",
        "System.Threading": "4.0.10-beta-23019",
        "Microsoft.CSharp": "4.0.0-beta-23019"
      }
    }
  }
}

```

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/44
