### ISSUE TITLE
dnu publish should handle --out pointing to an existing directory better

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#2303]
Right now, `dnu publish --out` doesn't do anything to explicitly handle the case where the out directory already exists. It just outputs the content into the existing folder, meaning it might contain files from a previous publish action, which can result in errors.

I suggest that it should fail if the specified out directory already exists. You could then use `--force` to have publish delete the target directory if it already exists, before the publish operation runs.

**Comment by Eilon** [comment]
BTW `--force` isn't logically the same as `--delete-target` or whatever. Specifying `--force` just means "go make a mess and I don't care".

**Comment by DamianEdwards** [comment]
Yeah fair point. Perhaps we have two switches then, e.g. --delete-target
