### ISSUE TITLE
`dnu restore` hangs indefinitely

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2304]
Running `dnu restore` on Linux and OS X frequently hangs. It hangs indefinitely. SIGINT (`ctrl+c`) doesn't kill the task. Instead I have to send SIGKILL for the mono-sgen process.

This bug is inconsistent and produces no error message. Sorry I cannot provide more info to reproduce. Anyone else seeing this problem? Is this a myget.org problem?

**Comment by natemcmaster** [comment]
Update: this is not limited to Mono. It also happens on CoreCLR on OS X (latest dev branch)

**Comment by BrennanConroy** [comment]
We run restore many times a day on both Linux and OS X on mono and it doesn't hang. We don't use myget.org though, so maybe it is related to that.

**Comment by borgdylan** [comment]
I observe such hanging with beta4 while restoring omnisharp. I do not observe this with teh latest bet7 bits from the unstable feed.

**Comment by natemcmaster** [comment]
More testing - this is not exclusive to myget.org.   Nuget.org sometimes triggers the same deadlock.

**Comment by natemcmaster** [comment]
I've tracked this down to an issue in HttpSource.GetAsync. In projects with dozens of projects => hundreds of dependences => thousands of dependencies on dependencies, [NuGetv2Feed](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/NuGet/NuGetv2Feed.cs#L109) can end up hung with over a thousand threads waiting on _httpSource.GetAsync (See [line 109](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/NuGet/NuGetv2Feed.cs#L109)).

The culprit:  the call to **ConcurrencyUtilities.ExecuteWithFileLocked**
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/Internal/ConcurrencyUtilities.cs#L45

```c#
 var signaled = fileLock.WaitOne(TimeSpan.FromSeconds(5));
```

![image](https://cloud.githubusercontent.com/assets/2696087/9206375/3dd4d520-401c-11e5-8ae6-6e68fdeba957.png)

**Comment by natemcmaster** [comment]
@BrennanConroy  https://github.com/aspnet/dnx/commit/f3e22af80c7bddea28c8f24b00f175ae67b9e835

**Comment by branciat** [comment]
I've the same problem with the latest beta8 on linux installed in a virtual machine only. the process generate 50 files in the tmp folder. The 2 others linux not virtual restore with success.

**Comment by davidfowl** [comment]
@natemcmaster can you reproduce this on demand?

**Comment by natemcmaster** [comment]
@davidfowl it's somewhat nondeterministic, but the deadlock usually occurs on the first run of dnu restore on entityframework after cleaning out `~/.dnx/packages`

**Comment by natemcmaster** [comment]
@brennanconroy I haven't been testing for it. I (and others) avoid cleaning packages and running a full restore unless necessary. The deadlock doesn't occur when pointing restore to the CI file share.

**Comment by muratg** [comment]
I've been trying to hit it with a big project (MVC) and couldn't repro it so far.  @natemcmaster did you see this with the EF project?

**Comment by natemcmaster** [comment]
I tried reproducing again. This appears to be fixed.

**Comment by tparnell8** [comment]
I am running into this on beta8 I am trying to dnu restore without much luck. Everything just hangs. I am trying to run it at the root of this project: https://github.com/tparnell8/LinqRb

**Comment by bilal-fazlani** [comment]
I still see this problem in RC1

**Comment by muratg** [comment]
@bilal-fazlani OS? CoreCLR or Desktop CLR?

BTW, FYI we're retiring dnx/dnu in RC2.  We'll be instead be using dotnet CLI for dev workflow.

**Comment by bilal-fazlani** [comment]
linux, coreclr.

I put ENV variable
MONO_THREADS_PER_CPU=2000

and it fixed the issue.

**Comment by muratg** [comment]
Are you sure you're not running on Mono?  Because the above workaround should be for Mono, not CoreCLR.

**Comment by bilal-fazlani** [comment]
@muratg  I thought it fixed the issue. But it didn't :( 
This problem still exists

**Comment by muratg** [comment]
Can you paste your `dnvm list` output?

**Comment by bilal-fazlani** [comment]
Ok.

**Comment by bilal-fazlani** [comment]
interesting.
I am using docker image `microsoft/aspnet:1.0.0-rc1-update1-coreclr`
I don't seem to have dnvm in it

**Comment by ddikman** [comment]
I'm also getting this freeze (although I can break it using Ctrl+C when attached to docker container).
I'm using a copy of the debian:jessie [1.0.0-rc1-final docker file](https://github.com/aspnet/aspnet-docker/tree/master/1.0.0-rc1-final) on aspnet github. 

`dnvm list` output shows:
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          linux           default
```
Seems to hang on different packages, sometimes not at all. I'm not too comfortable with Linux so I'm not sure how I could track the issue but I'm happy to help if you've got any tips?

**Comment by carlosrfernandez** [comment]
Same issue here, using latest Dockerfile from 1.0.0-rc. It doesn't happen with the Mono container, at least as far as I can tell.

**Comment by ddikman** [comment]
This is getting a bit annoying since it breaks our CI when I have to manually go in and restart the container every time. It works about every 5-10th time. Any ideas for troubleshooting or workaround? How are other people doing the restore step? Can I use dotnet restore?

**Comment by carlosrfernandez** [comment]
You can switch to dotnet restore. In my case that didn't work because I'm behind a corporate proxy and there's an issue with the nuget client in linux and proxy authentication... So I'm kind of stuck now with this whole docker thing

**Comment by bilal-fazlani** [comment]
I tried switching to dotnet restore but I couldn't. Not sure how the -s
and -f swiches work. I have multiple nuget sources a -s and -f dint work
for me.

**Comment by pranavkm** [comment]
dotnet restore has the same flags for source `-s` and fallback sources `-f`:

**Comment by ddikman** [comment]
Thanks for the suggestion however there seems to be a few too many issues involved in getting the CLI to work on the debian:jessie docker machine so I think we'll just have to wait until RC2 with the full CLI support is released and migrate to using dotnet restore at that time.

**Comment by Kosta-Github** [comment]
@natemcmaster: can this be reopened, since a lot of people still have this issue (me included)...

**Comment by natemcmaster** [comment]
@Kosta-Github as you know DNX is retired, which means even if we re-opened this bug, it's unlikely to get. `dotnet restore` is the "new" dnu restore.
