### ISSUE TITLE
Remove test dependency on Windows Phone tools

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2308]
For the longest time I haven't been able to get a totally clean `build verify` on my machine, yet the CI works fine. Finally, I tracked it down, I generally don't install the Windows Phone 8 tools on my dev machines, and there are dnu wrap tests that require MSBuild targets provided in that installer. We should remove those tests and stick to just the bare minimum VS stuff.

/cc @davidfowl @ChengTian

**Comment by ChengTian** [comment]
That test case is for the scenario where we wrap multiple csprojs with a single `project.json`. We have 3 frameworks in the test case, I guess removing wp8 framework and testing with 2 frameworks is still acceptable.
