### ISSUE TITLE
Project.Lock.JSON not updating on upgrade from beta 4 to beta 5

### ISSUE THREAD

**Issue by radenkozec** [aspnet/dnx#2310]
I am in process of migration from beta 4 to beta 5 and project.lock.json is not updating.
Old beta4 references are still in project.lock.json and when I click restore packages nothing happens.

I am in big problem here because I cannot upgrade to beta 5

See StackOverflow for project.json and more info:
http://stackoverflow.com/questions/31563564/upgrading-from-asp-net-5-beta-4-to-beta-5-project-lock-json-has-old-values

**Comment by davidfowl** [comment]
It is updating you should be able to determine what package is bringing in beta4 packages by looking at the lock file. Just because your `project.json` states beta5 doesn't mean you'll get it. If beta5 of that package doesn't exist, or your feeds are misconfigured means you'll get errors.  Did you read the https://github.com/aspnet/Announcements/issues repository?

**Comment by radenkozec** [comment]
@davidfowl Take a look at http://stackoverflow.com/questions/31563564/upgrading-from-asp-net-5-beta-4-to-beta-5-project-lock-json-has-old-values
There is a screenshot my issue.
I am getting all packages in project as beta4 and not beta5 like is in project.json.

I already run PowerShell run: $env:DNX_FEED="https://www.nuget.org/api/v2" 
to set-up URL of feeds.
Not sure how to resolve this?

**Comment by davidfowl** [comment]
That doesn't affect package restore. The NuGet.config does. What NuGet sources do you have configured

**Comment by radenkozec** [comment]
Here is NuGet.config from  %AppData%/NuGet/NuGet.Config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="NuGet" value="https://nuget.org/api/v2/" />
    <add key="NightlyBuilds" value="https://www.myget.org/F/aspnetvnext/" />
  </packageSources>
</configuration>
```

**Comment by radenkozec** [comment]
Managed to fix issue. Problem was Microsoft.Framework.ConfigurationModel.UserSecrets. This package and few others don't exists anymore.
This cause my issues with package restore with no smart error info.
After I removed these packages I managed to restore beta5 packages.
I will close this issue now.
