### ISSUE TITLE
Kestrel repo.json doesn't have commit hash which is throwing exception when doing 'dnu sources get Kestrel'

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2314]
![image](https://cloud.githubusercontent.com/assets/6559784/8837661/473c1466-307c-11e5-8f46-298927da0be2.png)

![image](https://cloud.githubusercontent.com/assets/6559784/8837757/e025490e-307c-11e5-870f-8300043c1297.png)

![image](https://cloud.githubusercontent.com/assets/6559784/8837771/fbce36fc-307c-11e5-8fa8-af9583931484.png)

**Comment by kichalla** [comment]
Some other packages are also missing this info...probably we can do a search of all the packages we ship and verify this:

![image](https://cloud.githubusercontent.com/assets/6559784/8838059/ad39a04c-307e-11e5-8e30-ae44179af19b.png)

**Comment by anurse** [comment]
We should definitely fix the missing hashes, but we should also ensure we don't throw here and instead display a useful error message (something like `The package '{ID}' does not contain valid source code repository information`)
