### ISSUE TITLE
Install 'latest' version of DNX by default when using 'dnvm install'

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2321]
We should install the `latest` version by default when someone types in `dnvm install`

If this is required, we should probably fail with a proper error message, currently it creates a folder with name like `dnx-mono.` under runtimes.

![image](https://cloud.githubusercontent.com/assets/6559784/8855265/2aa444f2-3119-11e5-899d-66ef8d81bd6e.png)

**Comment by BrennanConroy** [comment]
Move to dnvm repo please
