### ISSUE TITLE
DNX's '--packages' falls back silently to '.dnx\packages' folder

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2324]
I am not sure if this is by design, but based on the available help information I was guessing that the `--packages` option says where to look for packages when executing an application.

Here the '--packages' path doesn't exist but I do not get any error
![image](https://cloud.githubusercontent.com/assets/6559784/8856376/513426fe-311f-11e5-852b-d67f91390d94.png)

BTW, if i the packages folder does indeed exist and has packages, it works fine actually

**Comment by davidfowl** [comment]
We removed this feature
