### ISSUE TITLE
Why specify path when running dnx command?

### ISSUE THREAD

**Issue by tinganho** [aspnet/dnx#2331]
I'm just curious why I need to specify the path everytime I run `dnx`? Like `dnx . kestrel`. Why not just `dnx kestrel`?

**Comment by smbecker** [comment]
I think that's the point of these two pull requests

https://github.com/aspnet/dnx/pull/2263
https://github.com/aspnet/dnx/pull/2316

**Comment by tinganho** [comment]
@smbecker thanks.

**Comment by moozzyk** [comment]
Yes!
