### ISSUE TITLE
DNX always chooses the highest framework

### ISSUE THREAD

**Issue by Kieranties** [aspnet/dnx#2333]
**Scenario**: I have a console application that may be ran in both dnx451 and dnx46

When running `dnx . run` the application is always ran as a dnx46 application.  In the code base there has been an explicit decision  to always run against the highest discovered framework version: https://github.com/aspnet/dnx/blob/90d2bdb75f4576ed4eff4be6511c3011b47d0cad/src/dnx.clr.managed/DomainManager.cs#L97

Why is that?  Would it be possible to provide a flag to dnx when executing for the target framework (e.g. `dnx . run -fw dnx451`)

**Trivial example**:

```json
/* project.json */
{
  "userSecretsId": "aspnet5-ConsoleApp1-20150724092501",
  "version": "1.0.0-*",
  "description": "ConsoleApp1 Console Application",
  "authors": [ "kieranties" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6-*"
  },

  "commands": {
    "ConsoleApp1": "ConsoleApp1"
  },

  "frameworks": {
    "dnx46": { },
    "dnx451": { }
  }
}
```

```c#
/* Program.cs */
using Microsoft.Framework.Runtime;
using System;

namespace ConsoleApp1
{
    public class Program
    {
        private readonly IApplicationEnvironment _appEnv;

        public Program(IApplicationEnvironment appEnv)
        {
            _appEnv = appEnv;
        }

        public void Main(string[] args)
        {
            Console.WriteLine(_appEnv.RuntimeFramework);
            Console.WriteLine(_appEnv.ApplicationBasePath);
#if DNX46
            Console.WriteLine(AppContext.BaseDirectory);
#endif
        }
    }
}
```

```
/* Current result */
> dnx . run
DNX,Version=v4.6
C:\dump\x\ClassLibrary1\src\ConsoleApp1
C:\Users\kieranties\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6-12231\bin\
```

**Comment by davidfowl** [comment]
This is actually part of the intended design. You should be able to pass in the framework for quirking and compilation on the command line. 

/cc @anurse

**Comment by Kieranties** [comment]
@davidfowl It's still to do then?

**Comment by davidfowl** [comment]
Yes

**Comment by Kieranties** [comment]
Super!

**Comment by moozzyk** [comment]
Related to #1970. We need to find a way passing arguments (this, DNX_DEFAULTLIB, OS, architecture) to the app domain manager without using environment variables.
