### ISSUE TITLE
Servicing follow up items

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2336]
- [x] we should not fallback to ProgramFiles if DNX_SERVICING is set
    - [x] +Helios
- [x] when DNX_SERVICING is set it must point to a location that contains a readable index.txt file or the application will not run
    - [x] +Helios
- [x] do not allow using network shares in DNX_SERVICING variable
    - [x] +Helios
- [x] if reading the index.txt fails (sharing violation etc.) we should retry and then fail if it is not successful
    - [x] +Helios
- [x] if Servicing folder exists but there is no index.txt file we should fail
    - [x] +Helios
- [ ] fuzz testing for contents of the index.txt (empty file, binary file, short file - shorter than source framework etc.) file and DNX_SERVICING variable name
- [ ] End-to-end testing
- [x] ~~detailed documentation (folder structure, including index.txt format, recommended ACLs on the files etc.)~~ - tracked in the [Docs repo](https://github.com/aspnet/Docs/issues/374)
- [x] ~~enable preparing machines for servicing~~ - tracked as #2526

**Comment by muratg** [comment]
@victorhurdugaci will be helping with some of the items.

@joeloff we'll need to create an MSI to test servicing E2E in the Beta 7 milestone.

**Comment by moozzyk** [comment]
#2488

**Comment by moozzyk** [comment]
#1122

**Comment by muratg** [comment]
@victorhurdugaci E2E testing & coordination assigned to you in RC1.

**Comment by victorhurdugaci** [comment]
E2E validated. I was able to deliver an update in a test environment.

**Comment by moozzyk** [comment]
:clap:
