### ISSUE TITLE
Implement DNX acquisition story

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#2337]
- [ ] MSI for Windows (cc @joeloff)
- [x] DMG/PKG for OSX
- [ ] Automate Man and Changelog pages
- [ ] Signing PKG
- [ ] Linux installers (.deb, more?)
- [ ] Signing Deb

**Comment by anurse** [comment]
@glennc is driving the design on this. Looks like we're close to ready to call the design done, Glenn just needs to get sign offs from CLR.

**Comment by akoeplinger** [comment]
@anurse can you share a bit more about the plans here?

**Comment by anurse** [comment]
Certainly, once we have them :). @glennc is almost finished a draft design

**Comment by akoeplinger** [comment]
Thanks :)

**Comment by muratg** [comment]
Postponing rest of the work to RC1 for now. If CoreCLR issues are ironed out quickly, we can return back to this this week.

**Comment by factormystic** [comment]
At least for Windows, could dnx be delivered via powershell package management? I'm sure someone somewhere enjoys manually downloading and double clicking msi's, but I sure don't. I'd much rather set up your package source once and then do `install-package aspnet.dnx`

**Comment by glennc** [comment]
@factormystic I haven't actually looked at that myself yet. But it is definitely something we will investigate. We've mentioned it before, but not put the time into it yet.

**Comment by anurse** [comment]
As far as I know, PowerShell's package management can integrate smoothly with MSIs. So using the MSI route will not hinder our ability to integrate there. Good idea!

**Comment by muratg** [comment]
@glennc we'll need to do this manually for RC1.

**Comment by factormystic** [comment]
Why'd this get closed @davidfowl? I assume dnx will be packaged with more than just "DMG/PKG for OSX", and yet, no updates......

**Comment by muratg** [comment]
@factormystic because we'll be moving away from DNX to dotnet CLI.

**Comment by TJSoftware** [comment]
@factormystic https://channel9.msdn.com/events/ASPNET-Events/ASPNET-Fall-Sessions/Introducing-the-dotnet-CLI

@muratg I was able to download an exe that got me going with the DOTNET commands, I am unable to find that site now.  Can you provide a link on how to get this going or is this supposed to wait for RC2?

![image](https://cloud.githubusercontent.com/assets/4823412/11642554/a3e30558-9cfb-11e5-9bfd-fe7abd2619c6.png)

**Comment by muratg** [comment]
@TJSoftware Sure, you can get it from https://github.com/dotnet/cli

**Comment by factormystic** [comment]
@muratg ok thx. might want to add that to the readme or something

**Comment by TJSoftware** [comment]
@muratg Ahh, thank you, that makes sense that it is under dotnet and not under aspnet repo.  :smile:

**Comment by muratg** [comment]
You're welcome guys and @factormystic we'll be updating the roadmap on Home repo with this information soon.

**Comment by anurse** [comment]
FYI: It's definitely going to be a very bumpy road on the dev channel for a while. We have ASP.NET apps running on `dotnet` but it requires a lot of in-depth knowledge right now :). We'll be updating things as we smooth them out but feel free to explore and try things out!

**Comment by TJSoftware** [comment]
@anurse Certainly understandable, I am sure everyone looks forward to things being smoothed out by Junber :wink:
