### ISSUE TITLE
how can I add a compiled class library to a project

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/dnx#234]
Hi,
  I have a my compiled custom class library with some routines I want to use, how can I configure the project.json to add in net45 mode?

**Comment by RobSeder** [comment]
@davidfowl this is very disappointing. Bob Martin teaches us that "the application" should exist in code; in a class library (for .NET). Then, as an afterthought, I may choose to add a web front-end to my existing application, which exists in code.

Primarily though, my application is a class library, and then a unit test class library to test it. If you are saying that will be an "afterthought" going forward, you guys are heading in the exact wrong direction! A class library and unit test project should be the first-class citizen, then, if you have time, add support for an ASP.NET 5 project too.

**Comment by davidfowl** [comment]
@RobSeder this issue is almost a year old and stuff has changed. You can reference regular class libraries and you'll be able to reference dlls in the next version. Unit tests projects are different as the ones that exist today don't run on CoreCLR so there's a new way to do that but if you don't care about CoreCLR then you can party on the way you used to do things.

**Comment by RobSeder** [comment]
@davidfowl That's good to hear, but I'm not seeing that in VS2015 RC. I cannot create a DNX class library, and if I reference a regular .NET library, I get DNX build errors. From ASP.NET 5 project, I can only successfully add NuGet packages, everything else fails with DNX build errors.

**Comment by davidfowl** [comment]
That doesn't work yet. You can reference a class library from a DNX project but not vice versa

**Comment by RobSeder** [comment]
Ok - thanks!

**Comment by jwittner** [comment]
So is it the case that I can reference DLLs from my project.json now? Is there documentation that includes how to do this?
