### ISSUE TITLE
`dnu feeds` should be renamed `dnu sources`; `dnu sources` should be renamed something else

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#2348]
A command named `dnu sources` should do what `dnu feeds` does today. Changing NuGet terminology while in the midst of a grand unification is counter-productive.

I'd expect a command such as `dnu fetch-sources` to do what the current `dnu sources get` does today.

**Comment by anurse** [comment]
We had this exact discussion and decided `dnu feeds` was the better way to align these. /cc @davidfowl @muratg @yishaigalatzer 

An anecdotal survey indicates that most people already call them NuGet Feeds.
