### ISSUE TITLE
Defining alternative NuGet feeds for DNU

### ISSUE THREAD

**Issue by wholroyd** [aspnet/dnx#2357]
According to the [ASP.NET wiki](https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages), the config files are per-machine. What is the proper way to do this per-project or per-solution?

**Comment by anurse** [comment]
NuGet actually walks up from the current directory up to the root of the drive searching for NuGet.Config files, so you can place a NuGet.Config file next to your project.json or at a higher folder to affect only projects/solutions in or below that folder.

**Comment by wholroyd** [comment]
Thanks!

**Comment by anurse** [comment]
No problem at all!
