### ISSUE TITLE
Error loading System.Runtime.Serialization.Primitives with CoreCLR runtime after updating from beta5 to beta6

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/dnx#2364]
Steps:

1. Switch to beta6/coreclr: `dnvm use 1.0.0-beta6 -r coreclr -p`
2. In Visual Studio 2015, create new Web Application with "No Authentication" option
3. Replace beta5 -> beta6 in project.json and global.json
4. Set runtime "coreclr" in global.json
5. Fix compilation errors by removing BrowserLink and `if(env.IsDevelopment())` branch in Startup.cs 

Run the app:

     dnu restore
     dnx . web
     open http://localhost:5000/

Error occurs:

	error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
	System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
	File name: 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
	File name: 'System.Runtime.Serialization.Primitives'

The same error occurs during running xunit tests in AppVeyor, see [here](https://ci.appveyor.com/project/AlekseyMartynov/limebean-ra69c/build/25#L1469)

**Comment by DamianEdwards** [comment]
We believe that's caused by an issue with the JSON.NET package (https://github.com/JamesNK/Newtonsoft.Json/issues/618).

Can you try adding `System.Runtime.Serialization.Primitives ` to you project.json file directly?

**Comment by AlekseyMartynov** [comment]
@DamianEdwards yes adding this helps:

      "dependencies": {
        "System.Runtime.Serialization.Primitives":  "4.0.10-*"
      }
