### ISSUE TITLE
[ci] Darwin and Linux builds use non volatile dnx build

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2368]
The Darwin and Linux builds use the non volatile dnx build while the Windows one using volatile. It makes bootstrapping a pain because you have to manually update packages.

**Comment by davidfowl** [comment]
Does it require a change to the dnx source code? If not, then why file it here? We usually use universe for that

**Comment by glennc** [comment]
@victorhurdugaci Can you close this if it doesn't actually require DNX changes?

**Comment by pranavkm** [comment]
Think it might need a `build.sh` change. But
