### ISSUE TITLE
DNX in VS will not reference .net4.6

### ISSUE THREAD

**Issue by glatzert** [aspnet/dnx#2369]
Probably I am missing something - but I see no chance to figure out what exactly:

The situation:
* ASP.NET Beta 6 Project (Frameworks: dnx46)
* Legacy Library Project (Targeting 4.6)

Referencing the Library Project from the ASP.NET Project will print the following warning - and lots of errors about references to the .NET4.6 Project:

> The primary reference "C:\Dev\\...\\Service.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

**Comment by glennc** [comment]
Can we see your project.json?

/cc @anurse

**Comment by anurse** [comment]
It sounds like an issue with `dnu wrap`. To be clear @glatzert , the library is a standard csproj?

**Comment by davidfowl** [comment]
Seems like a tooling bug. Can you show your `project.json`? How many frameworks do you have listed?

**Comment by davidfowl** [comment]
Yep, it's a tooling issue. We seem to hard code this in the DNX.props file:

```XML
<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Client</TargetFrameworkProfile>
    <TargetFrameworkMoniker>.NETFramework,Version=$(TargetFrameworkVersion)</TargetFrameworkMoniker>
```

It makes msbuild complain constantly

**Comment by davidfowl** [comment]
Moving to the tooling repository
