### ISSUE TITLE
[Announcement] Breaking DNX renames

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2371]
Discussions for https://github.com/aspnet/Announcements/issues/51

**Comment by avanderhoorn** [comment]
I've just done the Beta6 VS update in my RC version of VS and now I'm getting a whole bunch of the following when I try and open my solution:

```
C:\Users\...\Glimpse\src\Glimpse.Agent.AspNet.Mvc\Glimpse.Agent.AspNet.Mvc.xproj : error  : The project file 'C:\Users\...\Glimpse\src\Glimpse.Agent.AspNet.Mvc\Glimpse.Agent.AspNet.Mvc.xproj' cannot be opened.

The project type is not supported by this installation.

C:\Users\...\Glimpse\src\Glimpse.Client.Web.Simple\Glimpse.Client.Web.Simple.xproj : error  : The project file 'C:\Users\...\Glimpse\src\Glimpse.Client.Web.Simple\Glimpse.Client.Web.Simple.xproj' cannot be opened.

The project type is not supported by this installation.
```

I'm running DNX 12290 and if I use dnx from the command line using weblistener the app still runs.

**Comment by bradwilson** [comment]
That package name is pretty much the exact opposite of what I asked you to do. :angry:

**Comment by victorhurdugaci** [comment]
We already had a zpatch-0003 on the feed. It's been uploaded earlier so I had to upload a higher version... Sorry about that. I can delete both of them, upload the version that you told me. Then we can tell people to delete the previous version, if they have it

**Comment by victorhurdugaci** [comment]
@bradwilson Changed to 2.1.0-beta5-aspnet-2 and removed the other packages.

**Comment by bradwilson** [comment]
Thanks. :+1:

**Comment by egorpavlikhin** [comment]
VS 2015 Community Edition has a reference to the old names even after installing updated tooling.

    1>  C:\Users\Egor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\dnx.exe --appbase "G:\Projects\New\Bestla.Website\src\Bestla.Website" "C:\Users\Egor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12302\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" pack "G:\Projects\New\Bestla.Website\src\Bestla.Website" --configuration Debug --out "..\..\artifacts\bin\Bestla.Website"
    1>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.PackageManager' or one of its dependencies. The system cannot find the file specified.

**Comment by victorhurdugaci** [comment]
@egorpavlikhin 

1. Did you apply [this workaround](https://github.com/aspnet/Announcements/issues/44) described by any chance?
2. What VS version do you have?
3. What tooling version do you have? (that's in the VS about page: ASP.NET and Web Tools)

**Comment by egorpavlikhin** [comment]
@victorhurdugaci well turned out I had WEBPROJ_ENABLEBETA7RENAMES set up, although I never did it manually. Everything working now, so the updated tooling does work.

**Comment by mdekrey** [comment]
Seems that [a couple of others](http://stackoverflow.com/q/32330004/195653) and I are having this issue inside Visual Studio with the latest versions, while it works fine (at least for me) from the command line (using `dnu restore`). 

Let's see, quick dump from the questions @victorhurdugaci asked:

For the workaround link... I installed the [Microsoft ASP.NET and Web Tools 2015 (Beta6) – Visual Studio 2015](http://go.microsoft.com/fwlink/?LinkID=619565) package. I don't have an environment variable named `WEBPROJ_ENABLEBETA7RENAMES`. My projects are referencing "beta8-*" from [the dailies feed](https://www.myget.org/F/aspnetvnext/) and the [Azure nightly feed](http://www.myget.org/F/azureadwebstacknightly), and my global.json has the sdk version specified as `1.0.0-beta8-15548`. I don't think I'm to the point where I can check to see if the PR specified in the workaround has been applied to the NuGet `xunit` package.

Here's the information copied from my about dialog:

    Microsoft Visual Studio Professional 2015
    Version 14.0.23107.0 D14REL
    Microsoft .NET Framework
    Version 4.6.00079
    
    Installed Version: Professional
    
    Visual Basic 2015   00322-40000-00000-AA556
    Microsoft Visual Basic 2015
    
    Visual C# 2015   00322-40000-00000-AA556
    Microsoft Visual C# 2015
    
    Visual C++ 2015   00322-40000-00000-AA556
    Microsoft Visual C++ 2015
    
    Application Insights Tools for Visual Studio Package   1.0
    Application Insights Tools for Visual Studio
    
    ASP.NET and Web Tools   14.0.20711.0
    ASP.NET and Web Tools
    
    ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
    For additional information, visit http://www.asp.net/
    
    Common Azure Tools   1.6
    Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
    
    GenerateUnitTest   1.0
    Generates unit test code for methods in classes under test.
    
    GitHub.VisualStudio   1.0
    A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
    
    Microsoft Azure HDInsight HQL Service   2.0.2600.0
    Language service for Hive query
    
    Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
    An integrated development environment for HDInsight application development.
    
    Microsoft Azure Mobile Services Tools   1.4
    Microsoft Azure Mobile Services Tools
    
    Microsoft Azure Tools   2.5
    Microsoft Azure Tools for Microsoft Visual Studio 2015 Preview - v2.5.21104.1601
    
    Microsoft Azure Tools   2.7
    Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601
    
    NuGet Package Manager   3.0.0
    NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
    
    PreEmptive Analytics Visualizer   1.2
    Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
    
    SQL Server Data Tools   14.0.50616.0
    Microsoft SQL Server Data Tools

This is my error message from Visual Studio's output window, redacted only slightly:

    PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
    C:\Users\<User>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8-15548\bin\dnx.exe "C:\Users\<User>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8-15548\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "C:\Users\<User>\Source\<Solution>\src\<Project>" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
    File name: 'Microsoft.DNX.PackageManager'
    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
    at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
    WRN: Assembly binding logging is turned OFF.
    To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
    Note: There is some performance penalty associated with assembly bind failure logging.
    To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

I'm still working on solving it myself, but my knowledge of the VS2015 ecosystem is unfortunately a bit less than I'd like! Thanks in advance!

**Comment by victorhurdugaci** [comment]
@mdekrey you are not using the latest tooling version. Your version `14.0.20711.0` is while the latest is `14.0.20723.0`.

20711 had a bug because it was trying to load `Microsoft.DNX.PackageManager` which is actually `Microsoft.Dnx.Tooling`.

Get the latest version: http://www.microsoft.com/en-us/download/details.aspx?id=48222

**Comment by mdekrey** [comment]
Ah, looks like I forgot to install the WebToolsExtensionsVS14.msi - thanks for your time @victorhurdugaci! (Hopefully other people who see the version numbers here will find the solution, too!)

**Comment by victorhurdugaci** [comment]
We'll add the required tooling version in future release notes. Hopefully, that will help avoid confusions.

**Comment by chandrasekarkesavan** [comment]
Thanks victor and mdekrey. I helps me to solve the problem.
