### ISSUE TITLE
Package names from project.json should be normalized to match the actual package name (cross plat)

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#2372]
When publishing the following message pops up:

```
System.IO.DirectoryNotFoundException: Directory '/home/dylan/Desktop/git/vnext/test/bin/output/approot/packages/Microsoft.Dnx.Compilation.Csharp.Common/1.0.0-beta7-12290' not found.
```

I added the package but it will still not work due to the fact that the package is called ```Microsoft.Dnx.Compilation.CSharp.Common``` with the capital 'S' not with a lowercase 's'.

**Comment by victorhurdugaci** [comment]
Is your project referencing the package with a lower case `s` or one of our packages?

**Comment by borgdylan** [comment]
Initially I did not reference it all. I had to reference it just to carry out a workaround. The reference I added is with the upper case 'S' and thats the actual package name according to the myget feed.

**Comment by borgdylan** [comment]
Publish is currently plagued by issues where I have to apply workarounds including the now 'normal' issue where  Package.1.0.0.0.nupkg is made while Package.1.0.0.nupkg is expected.

**Comment by borgdylan** [comment]
I think the case is that this package is needed while publishing and since the publish code was written on Windows, the spelling mistake went unnoticed. I am on Linux and the filesystem is 100% case sensitive!

**Comment by victorhurdugaci** [comment]
We should normalize the reference package names to match the original package name. cc @troydai @ChengTian

**Comment by borgdylan** [comment]
Also, remember that the package in question, was not referenced at the beginning with the error still happening. Something in the ASP.NET 5 package ecosystem has the bad reference.

**Comment by victorhurdugaci** [comment]
I'll look for it

**Comment by borgdylan** [comment]
The violation is here https://github.com/aspnet/Mvc/blob/e96b4d7b94112fd087628544e3f9a3f1f3f3b08d/src/Microsoft.AspNet.Mvc.Razor/project.json

**Comment by victorhurdugaci** [comment]
thanks! will send a pr for it

**Comment by glennc** [comment]
@victorhurdugaci Can this be closed?

**Comment by victorhurdugaci** [comment]
Nope. I only fixed the casing of the package but the root problem is still there

**Comment by davidfowl** [comment]
No the casing should just be correct is all.

**Comment by glennc** [comment]
Closing. Package names are case sensitive. We fixed our broken package references.
