### ISSUE TITLE
Solution file based builds fail due to missing DNX props and target files

### ISSUE THREAD

**Issue by MiguelAlho** [aspnet/dnx#2373]
This is similar to what is at https://github.com/aspnet/dnx/issues/2207

I ran in to this moments ago on my build server( TFS 2015 with the new build system). Building the projects in the repo is generally done through the solution file and the easy way to get to that is to use the MSBuild task. Since VS does create project (xproj) and solution files, it makes sense that it should work.

xproj files directly reference the Microsoft.DNX.props and Microsoft.DNX.targets file, and so get searched for at C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.Props which is now added when installing the WebToolExtensions from http://www.microsoft.com/en-us/download/details.aspx?id=48222. This needs to be installed in each build agent's machine. It is somewhat combersome, and would be nice to not have to do. 

Would creating a package with these dependencies and referencing the package's files instead of the pre-installed ones make sense? This was possible for projects that depended on TextTemplating targets in previous versions. This would require that the xproj file be manipulated on package install (which I believe is no longer possible for DNX oriented projects).

Also, if it were preferable to go directly to command line based builds, what would be the best way to build all the projects in the solution (and considering the associated dependency graph), not only projects in the src directory but also tests and any other project under the solution folder?

**Comment by ryanvgates** [comment]
I'm experiencing a similar issue to what @MiguelAlho has pointed out.

As an aside, it's always been really frustrating when VS and msbuild did things differently like with the way that nuget packages are handled. I'm disappointed to see that this paradigm is moving forward with DNX as well.

**Comment by glennc** [comment]
@sayedihashimi What do you think the right way to go about fixing something like this is? Is what we have right now as good as it gets or would a NuGet package or something make sense?

**Comment by sayedihashimi** [comment]
We don't have a good story for CI today when Visual Studio is not installed. For ASP.NET 5 there is some work that we can do to simplify this, but we are not likely to get to that until later on. In about a week I'll be posting a roadmap to the [tooling repo](https://github.com/aspnet/tooling), there should be an item for this feature on that when it's posted.

With that said even if we are able to simplify this for ASP.NET 5 projects, in a real world scenario there are a bunch of other project types used. What we are able to deliver would just cover the ASP.NET 5 parts. I think in many scenarios VS will still need to be installed :(

**Comment by glennc** [comment]
Closing this, @sayedihashimi can you try and remember to link this to a relevant tooling bug? That's the best we can do for now I think
