### ISSUE TITLE
Polish "dnu publish" output

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2376]
Reported by @DamianEdwards 

![capture](https://cloud.githubusercontent.com/assets/1383883/8994074/fd8e17cc-36bd-11e5-83dd-b8487f663004.PNG)

The information in red rectangles should be removed, to make it less noisy and less confusing.

@muratg , I can work on this issue.

**Comment by MisterJames** [comment]
@ChengTian I could take this one if you're open to it.

**Comment by ChengTian** [comment]
@MisterJames , thank you, community contribution is very welcome :smile: 

Please remember to mention me in your PR, I can help merge changes in after code review.

**Comment by MisterJames** [comment]
Great, I'll get started on this tomorrow. Thanks @ChengTian, cheers.

**Comment by ChengTian** [comment]
This should be done as part of https://github.com/aspnet/dnx/issues/2429. Otherwise the parallelized package installation will have messed up output. I am working on it.
