### ISSUE TITLE
DNX can't execute windows service application using mono runtime

### ISSUE THREAD

**Issue by git-naili** [aspnet/dnx#2384]
I have a windows service application. It's running perfectly on linux ( ubuntu 14.04.2 ) using the command mono-service . Which seems impossible for dnx. The execution fails always with the mono error message : 

<b> Use mono-service to start service processes </b>

**Comment by glennc** [comment]
@BrennanConroy Can you investigate this a bit more see if you can see what's going on?

**Comment by BrennanConroy** [comment]
Can you provide an example of your application?

**Comment by glennc** [comment]
Closing because its been a while. If you want to provide some more info then feel free to reopen and we will look at it.
