### ISSUE TITLE
Issue upgrading from beta 5 to beta 6 with System.Runtime

### ISSUE THREAD

**Issue by yhax** [aspnet/dnx#2385]
I am trying to upgrade my solution to beta 6. I did a dnvm upgrade, as well as a dnvm update-sellf.

Active Version           Runtime Architecture

------ -------           ------- ------------
       1.0.0-beta5       clr     x64
       1.0.0-beta5       clr     x86
       1.0.0-beta5       coreclr x64
       1.0.0-beta5       coreclr x86
       1.0.0-beta5-12103 clr     x86
  *    1.0.0-beta6       clr     x86 -------------- default

My solution has 7 or 8 projects. All of them are failing to resolve System.Runtime classes, so System.Object etc which means it can't resolve strings etc. My nuget packages are pointing to master, all of the references download correctly and restore correctly. I've tried a dnu restore in the dnx folder as well as the solution root directory. They all restore fine.

The solution however has over 90k errors. When I do a dnu build in one of the projects, I get this:

warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
warning CS1685: The predefined type 'CompilationRelaxationsAttribute' is defined in multiple assemblies in the global alias; using definition from 'System.Runtime, Version=4.0.20.0, Culture=neutral, P
ublicKeyToken=b03f5f7f11d50a3a'
warning CS1685: The predefined type 'RuntimeCompatibilityAttribute' is defined in multiple assemblies in the global alias; using definition from 'System.Runtime, Version=4.0.20.0, Culture=neutral, Pub
licKeyToken=b03f5f7f11d50a3a'
Total build time elapsed: 00:00:02.3751956
Total projects built: 1

I think all of the solution errors are related to some kind of conflict with system.runtime. Using the latest VS, and I have installed the latest nuget package manger update as well.

Any ideas?

**Comment by carstenschuette** [comment]
You've closed this issue. How did you fix it?
