### ISSUE TITLE
Setting the version to 1.0.0.0 makes dnu throw a FileNotFoundException

### ISSUE THREAD

**Issue by dromanchenko** [aspnet/dnx#2390]
I am getting this when setting the version to 1.0.0.0 in project.json:
...
Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12256
Copying to output path C:\Users\Dima\AppData\Local\Temp\PublishTemp
System.IO.FileNotFoundException: Could not find file 'D:\Projects\My\Test\src\TestProject\bin\Release\TestProject.1.0.0.nupkg'.

It seems dnu not picking up the last zero from the version number and trying to find *.1.0.0.nupkg instead of *.1.0.0.0.nupkg. Or... the nuget package should be created as *.1.0.0.nupkg instead

**Comment by Eilon** [comment]
NuGet uses SemVer, which has only 3 segments: http://semver.org/

Having said that, there should be a proper error for this.

**Comment by borgdylan** [comment]
This is due to the new versioning code which requires the fourth number only if it is not zero. Set it to 1.0.0 instead and you will no problems publishing etc.

**Comment by anurse** [comment]
We should still be properly normalizing input. You should be able to type `1.0.0.0` in any input field (version number in project.json, dependencies, etc.) and we should normalize it to `1.0.0`

**Comment by borgdylan** [comment]
Currently if I do not type 1.0.0 i get many issues on publish. i ended up normalizing them by hand as it was getting too tedious to publish apps.

**Comment by anurse** [comment]
@troydai Hey look, more normalization issues :P

**Comment by davidfowl** [comment]
@glennc When does this need design?
