### ISSUE TITLE
Could not load file or assembly 'Microsoft.Dnx.Host.Clr' or one of its dependencies.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2392]
After update package to last version on https://www.myget.org/gallery/aspnetvnext I get this error during running the project! 
What is my mistake? Is there any breaking changes?

Could not load file or assembly 'Microsoft.Dnx.Host.Clr' or one of its dependencies. The system cannot find the file specified

Thanks in advance

**Comment by anurse** [comment]
Have you also updated your DNX to `1.0.0-beta7-12290` or higher? There were some breaking changes (announced here: https://github.com/aspnet/Announcements/issues/51) in the DNX runtime. Try running `dnvm upgrade -u default` to get the latest version from the dev feed.

If you are running a recent DNX and still having this issue, please re-open this to comment further, but upgrading the DNX should fix your issue so I'm going to close this.

**Comment by ghithub** [comment]
I am also getting the same error. I forked the aspnet/mvc branch yesterday. Build succeeds, but when I try to launch the BasicWebSite via F5, I got the same error as MikeAndersun reported. 

When I ran `dvm upgrade -u default`, I get the following error:

C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : A parameter cannot be found that
 matches parameter name 'u'.
At line:1 char:182
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade -
u defau ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,dnvm.ps1

**Comment by anurse** [comment]
That indicates that you have an old version of DNVM (one prior to the addition of the `-u` flag). Can you update to the latest DNVM using the instructions in https://www.github.com/aspnet/Home and try again?

**Comment by ghithub** [comment]
Thanks for letting me know. I will try it now and see how it goes.

**Comment by ghithub** [comment]
So, I tried the following command provided at https://github.com/aspnet/Home#cmd

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

I removed my old dnvm.ps1 and dnvm.cmd before I issued the command. Everything seems to have gone well with no errors. But I am still getting the exact same error when trying to launch BasicWebSite via F5.

**Comment by ghithub** [comment]
I didn't realize that I needed to run `dnvm upgrade`. I have done that, rebuilt the solution and now when I tried to launch BasicWebSite via F5, I get a Microsoft Visual Studio error popup which says `Project Microsoft.AspNet.Mvc.Core does not contain any commands in project.json and cannot be started directly. In order to debug this project, add anew command in project.json and try again. Alternatively, add an executable project to this solution which references this project and set that as the default project.`

**Comment by ghithub** [comment]
Apparently I am getting tons of build errors after the dnvm upgrade.

**Comment by anurse** [comment]
What version of DNX are you using and what is the version of your ASP.NET tools (i.e. have you installed any of our tools packages since the VS 2015 RTM)?

**Comment by ghithub** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnx --version`
Microsoft .NET Execution environment
**Version:      1.0.0-beta7-15524**
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.1.7601.65536

I am not suer what tools packages you are referring to.

**Comment by renaldas** [comment]
try to open global.json file and change "version": "1.0.0-beta6", to "version": "1.0.0-beta7",

**Comment by MarcoGaribaldi** [comment]
I had the same issue. @renaldas' suggestion resolved it.

**Comment by RickStrahl** [comment]
Updating to post-beta 7 DNX worked for me, but man that sucks.With the beta 7 release builds I had no luck.

**Comment by Anderman** [comment]
I have the same problem from VS2015. But the from the command prompt i can start the application.
from cmd prompt I use
`Microsoft .NET Execution environment CLR-x86-1.0.0-beta7-15532`

My global.json is
```
{
    "projects": [ "src", "test", "../TagHelpers/src", "Sample" ],
    "sdk": {
        "version": "1.0.0-beta7"
    }
}
```
My Dnvm list say
```
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-beta5       clr     x64          win
       1.0.0-beta5       clr     x86          win             b5
       1.0.0-beta5       coreclr x64          win
       1.0.0-beta5       coreclr x86          win
       1.0.0-beta6       clr     x64          win
       1.0.0-beta6       clr     x86          win             b6
       1.0.0-beta6       coreclr x64          win
       1.0.0-beta6       coreclr x86          win
  *    1.0.0-beta7       clr     x86          win             b7, default
       1.0.0-beta7-12290 clr     x86          win
       1.0.0-beta7-12290 coreclr x86          win
       1.0.0-beta8-15120 clr     x86          win
       1.0.0-beta8-15120 coreclr x86          win
```
I thougth VS2015 use the Default.
