### ISSUE TITLE
Remove "already exists" messages from `dnu restore --quiet` output

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#2395]
Repeating `dnu restore --quiet` commands relatively close together leads to lots of output like

```
Microsoft.Framework.PropertyHelper.Sources.1.0.0-beta7-10620 already
Microsoft.AspNet.Http.Extensions.1.0.0-beta7-11771 already exists
Microsoft.Framework.WebEncoders.Core.1.0.0-beta7-11771 already exists
Microsoft.AspNet.Http.Abstractions.1.0.0-beta7-11771 already exists
```

Since this command already outputs messages like "Installing Microsoft.AspNet.FileProviders.Physical.1.0.0-beta7-11666", the above information can be inferred from  the absence of the "Installing" messages. Definitely not necessary in the `--quiet` output.

**Comment by dougbu** [comment]
See this has been moved to the backlog.

@glennc still wondering why the message is output at all. Is it ever actionable?

**Comment by glennc** [comment]
It is a hint that you might need to clear your cache for some categories of errors. But otherwise probably not super useful in a whole lot of circumstances.

**Comment by dougbu** [comment]
Thanks @glennc In addition to being "not super useful", the message doesn't hint at the interpretation you just provided.
