### ISSUE TITLE
dnu commands install does not work when passing relative packages path

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/dnx#2398]
This command works,
`dnu commands install --source http://www.myget.org/F/some-feed/api/v2 SomePackage --packages C:\Users\myprofile\Documents\SomeRepo\SomeFolder`

But this doesn't
`dnu commands install --source http://www.myget.org/F/some-feed/api/v2 SomePackage --packages .\SomeFolder`

When I try to run the command it says,
`The system cannot find the path specified.`

cc' @victorhurdugaci

**Comment by victorhurdugaci** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
Works for me, do you not have permission to add .\SomeFolder?

**Comment by ajaybhargavb** [comment]
Spoke offline. The error shows up when running the command that was installed from the package. Not when running the install command.

**Comment by glennc** [comment]
@victorhurdugaci Can you see what the issue here is?

**Comment by victorhurdugaci** [comment]
@ajaybhargavb isn't this PR fixing this issue? https://github.com/aspnet/dnx/pull/2399

**Comment by ajaybhargavb** [comment]
No. That only fixes the issue mentioned here https://github.com/aspnet/dnx/pull/2399#issue-98851638.  After that fix you still need to pass in full path for it to work. Otherwise it creates a bad cmd file.

**Comment by victorhurdugaci** [comment]
I cannot reproduce this anymore
