### ISSUE TITLE
Add a dnu command to clear the HTTP cache

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#2401]
`dnu` caches results for the various categories of HTTP requests it makes (e.g. feed check, list package, v3 feed check, etc.) for various amounts of time.

While it's possible to run a `dnu restore` at any time with the cache disabled via `--no-cache`, there isn't a way to clear the cache completely, other than just deleting the folder in the user profile.

Propose we add a command to clear the HTTP cache, e.g. `dnu --clear-cache`. Might be nice to support clearing it only for specified feeds too, e.g. `dnu --clear-cache https://www.myget.org`

This hit me today as we found an issue in the NuGet v3 feed root `index.json` file which is now fixed. However, `dnu` caches the request to that file for a week, so customers will need to manually delete the cache folder to see the change in the meantime.

**Comment by glennc** [comment]
Assigning to beta8 for at least the clear-cache command, we will talk about clearing a specific URL but we might punt that part to beta8

**Comment by MisterJames** [comment]
@glennc I could take this one on if you like.

 1. Can I assume that a raw `dnu --clear-cache` would clear out the `DnuFolderPath.HttpCacheDirectory` folder entirely?  Or should it clear the `list_` and `nupkg_` but preserve the dir structure and leave the `index_json.dat`?

 1. When clearing for a specific feed, would `https://www.myget.org` match all entries in the cache with the start of that domain? Or would it be only on direct matches such as `https://www.myget.org/F/aspnetvnext/api/v2/` or `https://www.myget.org/F/roslyn-nightly/`?

**Comment by glennc** [comment]
I had assumed it would nuke the whole folder. But I am not familiar enough with the entire mechanism to say for certain. @davidfowl @anurse @lodejard What do you guys think?

**Comment by MisterJames** [comment]
@glennc Whole folder for the base scenario, yes. But @DamianEdwards had said:

> Might be nice to support clearing it only for specified feeds too, e.g. `dnu --clear-cache https://www.myget.org`

**Comment by muratg** [comment]
Done: https://github.com/aspnet/dnx/commit/3d0edc0914f341794a56fb8c0d927ddbd96dec31
