### ISSUE TITLE
It's possible to resolve the wrong dependency version

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2402]
http://stackoverflow.com/questions/31770106/dependency-specified-was-microsoft-aspnet-mvc-6-0-0-beta6-but-ended-up-with-m/31777542

**Comment by DannyVarod** [comment]
I am getting this exact error with VS2015 RTM - all the packages I've updated are not restored and direct run of the restore packages outputs "All packages are already installed and there is nothing to restore.".
The project.json is updated, however, the project.lock.json still has the older versions in it.

**Comment by davidfowl** [comment]
Can you give repro steps

**Comment by DannyVarod** [comment]
Using Visual Studio 2015 RTM Community edition (Version 14.0.23107.0 D14REL with .NET Version 4.6.0081 and NuGet Package Manager Version 3.2.60914.10516):

1. Create new ASP.NET Web Application, .NET version = 4.5.2, with a new solution, select ASP.NET 5 Preview Templates, Web Application, authentication = Individual User Accounts, do not check Host in the cloud.

2. Build solution, build succeeds.

3. Right click on solution, Manage NuGet Packages, filter by Upgrade available, Include prerelease.

4. Update a NuGet e.g. EntityFramework.SqlServer from 7.0.0-beta5 to 7.0.0-beta7 (same effect if you update them all).

5. Build solution, build fails with loads of errors and one warning per updated package which explains the errors e.g.:

Severity	Code	Description	Project	File	Line

Warning		Dependency specified was EntityFramework.SqlServer >= 7.0.0-beta7 but ended up with EntityFramework.SqlServer 7.0.0-beta5.	WebApplication1	C:\DEV\Examples\Web2\src\WebApplication1\project.json	7

**Comment by DannyVarod** [comment]
Another issue I've found: uninstalling a NuGet doesn't remove it from project.lock.json, this breaks the build with unrelated errors.
