### ISSUE TITLE
When csproj project reference can not be resolved, it still should be sent as project reference

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2405]
When Project A references project B - a wrapped csproj which can not  be resolved by some reason, project B is not sent as project reference to project A, however exist as unresolved dependency. This make its is hard for tooling to show it correctly in Add Reference dialog.

However if you look at dependency info, it can be determined that Project B is actually a project, since it has a path to wrapped project.json, thus DTH could notice that and send it also as project reference in references message.

![image](https://cloud.githubusercontent.com/assets/1592091/9070665/e80794a0-3abe-11e5-8671-22285df42151.png)

**Comment by abpiskunov** [comment]
It still should be unresolved in Dependencies message though.

**Comment by abpiskunov** [comment]
It would be nice if it could be beta7 issue.

**Comment by abpiskunov** [comment]
Please let me know when fix is checked in and I will verify that tooling works with it as expected.

**Comment by davidfowl** [comment]
This is actually a bigger change than it looks like. We'd need to add a new field that determines if the dependency is resolved or not so we can preserve the original type.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.DesignTimeHost/Models/OutgoingMessages/DependencyDescription.cs

**Comment by abpiskunov** [comment]
I see, sounds good.

**Comment by troydai** [comment]
__Proposal__

_Solution 1_
Adding a new boolean property `Resolved` to the `DependencyDescription` model to indicate if the dependency resolved. And the `Type` property accept the `LibraryDescription`'s `Type` value.

_Solution 2_
Reuse the `Type` property but append the `LibraryDescription.Type` with a string indicate if it is resolved or not. So it will look like:
- `Project`
- `Package`
- `Project:Unresolved`
- `Package:Unresolved`

**Comment by abpiskunov** [comment]
Both of the would require tooling changes in parsing messages we receive from DTH, but Solution1 looks more neat.

**Comment by troydai** [comment]
Either way it's a breaking change requires tooling coordination. Data in solution 1 will be easier to be consumed. ping @davidfowl

**Comment by davidfowl** [comment]
Solution 1 is better 😁
