### ISSUE TITLE
Specifying keyFile causes assembly load error under CoreCLR

### ISSUE THREAD

**Issue by tillig** [aspnet/dnx#2409]
Say I have an assembly (like [Autofac](https://github.com/autofac/Autofac)) that is built to support multiple platforms (`dnx451`, `dnxcore50`, etc.) and needs to be strong named. Previous to beta 6, the `project.json` file just allowed you to specify `"strongName": true` and a default strong name key would be used. [With the release of beta 6](http://blogs.msdn.com/b/webdev/archive/2015/07/27/announcing-availability-of-asp-net-5-beta-6.aspx) you can now specify `"keyFile": "MyFile.snk"` and have your own key used.

**If you try to use a cross-platform assembly signed with a custom key in the CoreCLR (`dnxcore50`) environment under beta 6, the assembly will fail to load.**

You get an error from Roslyn:

```
System.IO.FileLoadException : Could not load file or assembly 'CrossPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
---- Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException : warning DNX1001: Strong name generation is not supported on CoreCLR. Skipping strongname generation.
error CS7027: Error signing output with public key from file '../../CustomKey.snk' -- Assembly signing not supported.
Stack Trace:
     at DnxOnly.Test.ReproductionTests.IdIsNotEmpty()
  ----- Inner Stack Trace -----
     at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
     at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
     at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
     at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
     at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
     at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
     at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
     at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
     at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

The project will _build_ just fine, it just won't load at runtime.

[I've posted a repro of the issue here.](https://github.com/tillig/DnxStrongNameIssueRepro) It uses a PowerShell script to build the solution and then try to run some xunit tests first under 32-bit DNX 4.5.1 (success) and then under 32-bit DNXCore 5.0 (fail).

You'll find three assemblies in there:

- `CrossPlatform`  - the assembly built targeting multiple platforms, strong-named.
- `DnxOnly` - a DNX only assembly, not strong-named, references the `CrossPlatform` assembly.
- `DnxOnly.Tests` - an xunit test assembly that tries to use code in the `DnxOnly` assembly.

If you switch the `project.json` in `CrossPlatform` from using `keyFile` to using `strongName` instead, the tests will run and pass under both DNX 4.5.1 and DNXCore 5.0.

**Comment by tillig** [comment]
Potentially related: the [code gist](https://gist.github.com/csharpfritz/d66017d22d7a534ea44c#file-project-json) on [the release announcement blog entry](http://blogs.msdn.com/b/webdev/archive/2015/07/27/announcing-availability-of-asp-net-5-beta-6.aspx) shows specifying both `strongName` and `keyFile` like this:

``` json
"compilationOptions": {  
   "delaySign": true, 
   "keyFile": "myApp.snk", 
   "strongName": true  
}  
```

I wasn't able to do that - I can only specify `strongName` **or** `keyFile`, but not both. You get a compilation error when specifying both.

**Comment by moozzyk** [comment]
I believe that because you run tests like this - `ForEach-Object { Test-Projects $_.DirectoryName }` you actually don't run tests against what you build but you run tests against the project and therefore you compile the project again when the tests are being run. Therefore you try sign with a private key after switching to CoreClr. However, signing assemblies with private keys is not supported on CoreClr and hence the error (you can easily repro this with just `dnu build` - go to the CrossPlatform project, change your runtime to coreclr - `dnvm use default -r coreclr` and run `dnu build`). 

You can't use both "keyFile" and "strongName" together - they are mutually exclusive. Thanks for the pointer to the announcement blog post - I already reported this issue and asked it to be fixed.

**Comment by tillig** [comment]
Basically that test logic is:
```
dnvm use 1.0.0-beta6 -r CoreCLR
dnx test/DnxOnly.Test test
```

I don't see it rebuild, it just goes right into testing. How would I change my script to run tests successfully in both runtimes?

**Comment by moozzyk** [comment]
If you turn on tracing (`set DNX_TRACE=1`) and run `dnx . test` you will see:

```
Information: [LoaderContainer]: Load name=CrossPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Information: [ProjectLibraryExportProvider]: GetLibraryExport(CrossPlatform, DNXCore,Version=v5.0, Debug, )
Information: [RoslynProjectReference]: Emitting assembly for CrossPlatform
Information: [CompilationContext]: Generating resources for CrossPlatform
Information: [CompilationContext]: Generated resources for CrossPlatform in 0ms
Information: [RoslynProjectReference]: Emitted CrossPlatform in 10ms
```

One way to avoid compilation is to publish the application with no sources and then you can run it using different runtimes, e.g. run the following command from your DnxOnly.Test folder:

`dnu publish -o c:\temp\app --no-source`

and then you can run it using different runtimes: 

```
PS C:\temp\DnxStrongNameIssueRepro\test> dnvm use 1.0.0-beta6 -r clr
Adding C:\Users\ja\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin to process PATH

PS C:\temp\DnxStrongNameIssueRepro\test> c:\temp\app\test.cmd
xUnit.net DNX Runner (32-bit DNX 4.5.1)
  Discovering: DnxOnly.Test
  Discovered:  DnxOnly.Test
  Starting:    DnxOnly.Test
  Finished:    DnxOnly.Test
=== TEST EXECUTION SUMMARY ===
   DnxOnly.Test  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.089s

PS C:\temp\DnxStrongNameIssueRepro\test> dnvm use 1.0.0-beta6 -r coreclr
Adding C:\Users\ja\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin to process PATH

PS C:\temp\DnxStrongNameIssueRepro\test> c:\temp\app\test.cmd
xUnit.net DNX Runner (32-bit DNXCore 5.0)
  Discovering: DnxOnly.Test
  Discovered:  DnxOnly.Test
  Starting:    DnxOnly.Test
  Finished:    DnxOnly.Test
=== TEST EXECUTION SUMMARY ===
   DnxOnly.Test  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.096s
```

**Comment by tillig** [comment]
:smiley_cat: **YES YES YES** This works perfectly. Somewhat unintuitive, but it works like a charm. Thanks!

**Comment by tillig** [comment]
For posterity, I updated the [posted reproduction solution](https://github.com/tillig/DnxStrongNameIssueRepro) to include both an incorrect build script and a fixed one illustrating the updated process. Folks interested in seeing it in action can check it out.
