### ISSUE TITLE
Beta 6 no longer recognizes dependency

### ISSUE THREAD

**Issue by r2musings** [aspnet/dnx#2410]
See this SO post:
http://stackoverflow.com/questions/31750350/vnext-beta6-deployment-error-the-dependency-entityframework-6-1-2-could-not

**Comment by glennc** [comment]
@r2musings Is there any chance of seeing the project? Publish to GItHub maybe?

**Comment by r2musings** [comment]
Hi Glenn, we already have this in a private repo.  I'll get you access.

**Comment by r2musings** [comment]
Gave you access, @glennc.  Let me know if you have any problems getting to it.

**Comment by glennc** [comment]
Looks like this is caused by this: https://github.com/aspnet/dnx/issues/2352

Does manually running restore on the wrapped projects help?

**Comment by moozzyk** [comment]
Can this be related to https://github.com/aspnet/dnx/issues/2454?
