### ISSUE TITLE
dnu publish not excluding folders

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2411]
From here: http://stackoverflow.com/questions/31820294/exclude-folders-on-publish-project-using-dnu-publish

I tried doing the following, but this doesn't seem to work...is this syntax ok?
```
"publishExclude": [
        "wwwroot/lib",
        "wwwroot/source"
    ]
```

**Comment by glennc** [comment]
@troydai Do you have to put glob patterns in here or do we exclude folders?

**Comment by troydai** [comment]
You need a trailing `/` to indicate it is a folder or append `/**/*.*` to it.

**Comment by glennc** [comment]
Ok thanks, can you go and answer the SO question as well?

**Comment by kichalla** [comment]
> You need a trailing  /  to indicate it is a folder 

@troydai  But is this convention not true for top level folders?...example:
https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/project.json#L27

**Comment by cscleison** [comment]
@troydai same problem here. tried different patterns but doesn't work

**Comment by troydai** [comment]
@kichalla can you still repo this issue?

**Comment by kichalla** [comment]
@troydai yes, I am able to repro(with the suggested pattterns) it with beta6

**Comment by troydai** [comment]
I'll take a look

**Comment by troydai** [comment]
It appears to me that __webroot__ folder doesn't participate in the globbing during the publish. It's not an regression. Should we go over the design decision? https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Publish/PublishProject.cs#L637

**Comment by awflierman** [comment]
Tried the same as kichalla, and taking this [SO answer](http://stackoverflow.com/a/32790748/551030) into account it would be nice to be able to exclude some folder inside wwwroot.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#565
