### ISSUE TITLE
Allow git commit for dnu sources to come from an environment variable

### ISSUE THREAD

**Issue by tillig** [aspnet/dnx#2418]
Related to #2416 and https://github.com/aspnet/Announcements/issues/46:

If you're in a build server environment where the code is cloned and shipped to the agent (e.g., AppVeyor), the `commit` in `repo.json` will always be empty. There needs to be another way to specify what that value is so `dnu sources get` can be made to work for projects built in these environments.

**Comment by victorhurdugaci** [comment]
:+1: yes, we'll add this soon. It's been requested by multiple people

**Comment by tillig** [comment]
Sweet. I just didn't see an issue or anywhere else to track it, so... I figured this was as good as any. Thanks!

**Comment by Anderman** [comment]
I seems that this command `dnu sources get` is not available anymore????

**Comment by victorhurdugaci** [comment]
That's correct. We had to remove it because it was not working well with source/build time references. We hope to bring it back in a future release

**Comment by davidfowl** [comment]
This feature was cut
