### ISSUE TITLE
Rename project.json to dnxconfig.json

### ISSUE THREAD

**Issue by Lenne231** [aspnet/dnx#2420]
TypeScript has "tsconfig.json", VS Code has "jsconfig.json" and there are many other technologies with other configuration files that could be part of a DNX application. 

It would be nice if DNX would not choose such a general name for the configuration file. There will be projects with many different technologies so "project.json" seems a little bit confusing. "netconfig.json" should be ok as well.

**Comment by glennc** [comment]
At this point I don't think dealing with the breaking changes of renaming project.json is something we would want to do.

So a rename would have to have a large amount of value. So far I haven't seen a huge number of downsides to the name, it could perhaps be better, but I haven't seen a suggestion so far that seems significantly better. Better enough to go and reset all the tooling and documentation that talks about project.json already anyway.
