### ISSUE TITLE
Error when targeting dnx451 with MVC 5 nuget packages

### ISSUE THREAD

**Issue by XiaoweiJia** [aspnet/dnx#2421]
I tried to target dnx451 in project.json and reference asp.net mvc 5. when I run an error says: my project is not compatible with the target framework dnx45. Any ideas? Do I have to use asp.net 5 when targeting dnx451?
Can I target net46 when using mvc 5?

Thanks

**Comment by Eilon** [comment]
To use ASP.NET MVC 6 you need to use ASP.NET 5.
To use ASP.NET 5 you must use DNX.
To use ASP.NET MVC 5 you can use .NET 4.5 and newer (including .NET 4.5.1, 4.5.2, and 4.6).
ASP.NET MVC 5 does not work on ASP.NET 5 or DNX.
