### ISSUE TITLE
Method not found: 'Microsoft.Dnx.Runtime.Library Microsoft.Dnx.Runtime.ILibraryManager.GetLibraryInformation(System.String)'.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2423]
Method not found: 'Microsoft.Dnx.Runtime.Library Microsoft.Dnx.Runtime.ILibraryManager.GetLibraryInformation(System.String)'.
Dnx :1.0.0-beta7-12302
project packages are updates to latest version on aspnetvnext

What is my mistakes.
Please help me

**Comment by anurse** [comment]
Does this error only happen when you host via IIS? Can you try using WebListener or a console application? There is a bug currently in the IIS host that has just been fixed but is working it's way through our build system (/cc @Tratcher @troydai)

**Comment by mikeandersun** [comment]
I only use IIS. 
If it is a bug I can wait for next build.

**Comment by Tratcher** [comment]
It's all fixed, we're just waiting on the next build. Should be sometime today.
