### ISSUE TITLE
Dnu publish should have an option to prune packages when the runtime flag is not passed.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/dnx#2428]
Currently, when the runtime flag is not passed dnu publish bundles the packages for both core and clr. Need an option in dnu publish to target the packages for a specific framework even when runtime is not specified.

This is needed to decrease the payload during Azure publishing.

**Comment by ChengTian** [comment]
@davidfowl , we can have
```
dnu publish --framework dnx451
```
and report error when the following configuration is specified
```
dnu publish --framework dnx451 --runtime dnx-coreclr-win-x86.1.0.0-beta6
```

**Comment by davidfowl** [comment]
That looks good and is consistent with build. We should allow passing multiple frameworks as well.
