### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by aliveli186** [aspnet/dnx#2433]
The so called simplified dependency feature is a big problem.
It's not simple, it's not functional, not self explanatory, not well documented.
It adds unnecessary complexity from the beginning.
What is simple is add the dependency and write your code. Which was so until that new "simplified dependency" feature was invented.
Now it's add the dependency and figure it out why it doesn't work. Edit some json config manually, try if it works, etc.
Please make some videos on this issue.

My scenario:
I start a new ASP 5.0 web api project, add "System.Data.SqlClient" dependency from NuGet.
It adds under "DNX Core 5.0".
Everything is OK, but after writing my first line of code inside the controller:

var connection = new SqlConnection("...");

I get these errors:

DNX 4.5.1 error CS0246: The type or namespace name 'SqlConnection' could not be found (are you missing a using directive or an assembly reference?)
DNX Core 5.0 error CS0246: The type or namespace name 'SqlConnection' could not be found (are you missing a using directive or an assembly reference?)

Now figure it out and write your code. No way.
What should I do? Any updated tutorials?

**Comment by davidfowl** [comment]
Yep, we're working on better diagnostics. Sometimes it's hard to know upfront unless you know what the package supports. The errors will get better when things are incompatible. What version of System.Data.SqlClient are you using?

**Comment by aliveli186** [comment]
"frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Data.SqlClient": "4.0.0-beta-23019"
      }
    }
  }

**Comment by kichalla** [comment]
Modify your `dnx451` to like below and try again

```
"dnx451": {
            "frameworkAssemblies": {
                "System.Data": "4.0.0.0"
            }
        }
```

**Comment by shipitfaster** [comment]
I had the same issue on Beta5, though the reference was already under the "dnx451" node as @kichalla points out above. What I did find, though, was that I had an empty dnxcore50 node.

**This works**
```javascript
"frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0"
      }
    }        
  },
```
**This doesn't work**
```javascript
"frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0"
      }
    },
    "dnxcore50": {
      "dependencies": {

      }
    }
  },
```
