### ISSUE TITLE
Beta7-12321 Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':   Microsoft.CodeAnalysis.CSharp 2.0.0-beta1-20150805-03   System.Reflection.Metadata 1.1.0-alpha-00008

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/dnx#2435]
Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  Microsoft.CodeAnalysis.CSharp 2.0.0-beta1-20150805-03
  System.Reflection.Metadata 1.1.0-alpha-00008

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
Version:      1.0.0-beta7-12321
Type:         CLR
Architecture: x86
OS Name:      Windows
OS Version:   6.2.9200.0

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  Microsoft.CodeAnalysis.CSharp 2.0.0-beta1-20150805-03
  System.Reflection.Metadata 1.1.0-alpha-00008

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
Version:      1.0.0-beta7-12321
Type:         CLR
Architecture: x86
OS Name:      Windows
OS Version:   6.2.9200.0

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.CodeAnalysis.CSharp 2.0.0-beta1-20150805-03
   System.Reflection.Metadata 1.1.0-alpha-00008

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-12321
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
]

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9920760
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by mikeandersun** [comment]
I Have the issue too. :(

**Comment by davidfowl** [comment]
Sounds about right. Those packages failed to restore right?

**Comment by mikeandersun** [comment]
yes. Unable to locate them!

**Comment by borgdylan** [comment]
Add these sources to your nuget config file
```
<add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly" />
<add key="DotNetFx" value="https://www.myget.org/F/dotnet-corefx" />
```

**Comment by glennc** [comment]
@CarlosFreire and @mikeandersun Looks like this is because of missing MyGet feeds, the aspnetvnext feed no longer has copies of the corefx or roslyn packages. Reopen if adding the feeds doesn't help. We're looking for a way to make this experience better in the future.
