### ISSUE TITLE
[Announcement] dnx now implicitly uses current folder as the appbase

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2436]
Discussion for https://github.com/aspnet/Announcements/issues/52

**Comment by akoeplinger** [comment]
This is really great :+1: 

Question: If I'm reading https://github.com/aspnet/dnx/pull/2263 correctly, then the old format with `.` was removed and will start breaking, right? I think this should be called out more prominently in the post.

**Comment by moozzyk** [comment]
@akoeplinger I updated the post.

**Comment by akoeplinger** [comment]
@moozzyk Thanks!

**Comment by mykebates** [comment]
+ 10

**Comment by damccull** [comment]
Woo! About time :D Good job.

**Comment by lwinch2006** [comment]
It seems that Visual Studio Code 0.7.0 and 0.8.0-preview use the old format of the command namely "dnx . kestrel" for example and fail to start application. Is it some way to fix it according to the new format or it is just to wait until new release of Visual Studio Code will be available.
