### ISSUE TITLE
Add diagnostic monikers for DNX messages

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnx#2440]
It would be helpful if dnx errors/warnings each had their own unique error codes. This will be helpful in case Visual Studio needs to de-duplicate errors and it also enables a help link for each error message.

cc @glennc @BillHiebert @davidfowl @DamianEdwards

**Comment by Eilon** [comment]
What kind of DNX errors/warnings is this specifically in reference to?

**Comment by davidfowl** [comment]
Similar to how CSC has CS1034 etc

**Comment by Eilon** [comment]
I got that; I'm wondering for which cases it's interesting.

**Comment by davidfowl** [comment]
Ah! We have a few: 

- Unresolved dependency
- Incompatible dependency
- Unexpected version resolved

**Comment by victorhurdugaci** [comment]
- Moniker: NUAAAA (A = digit)
- Start at 1000. 
- Consecutive but not categorized (could allocate blocks if needed)
- NU1000 - Unexpected error (unhandled)
- Use DNX is the error is DNX specific
