### ISSUE TITLE
Garbled output from the dnu restore step when running build.cmd

### ISSUE THREAD

**Issue by halter73** [aspnet/dnx#2441]
Repro steps:

1. Set the `DNX_TRACE` environment variable. This may or may not be important.
2. Run the `build.cmd` script from [KestrelHttpServer](https://github.com/aspnet/KestrelHttpServer). I think this will repro for other projects as well.

Result:

![image](https://cloud.githubusercontent.com/assets/54385/9143240/f7888730-3cf9-11e5-9614-cf927edf6d0c.png)
![image](https://cloud.githubusercontent.com/assets/54385/9143092/fa9f8302-3cf8-11e5-9ab8-1cd40ea345e3.png)

In rare instances this garbled output has left my console in a bad state where all future output was the wrong color. Even for commands run after the build completed.

**Comment by davidfowl** [comment]
@halter73 does it repro on cmd?

**Comment by halter73** [comment]
@davidfowl Yes it does.
