### ISSUE TITLE
CallContextServiceLocator.Locator is null on CoreCLR x-plat

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2442]
CallContextServiceLocator.Locator is not set by the time applications have been bootstrapped and launched. This only happens coreclr + {linux, darwin}, not Mono or any Windows runtime.

Versions: dnx beta7-12328
(See the full [dnu list](https://gist.github.com/natemcmaster/892b690f1962122f4337)).

### Repro

Make the following small project.

```c#
using System;
using Microsoft.Dnx.Runtime.Infrastructure;

namespace CallLoc
{
	public class Program
	{
		public static void Main(string[] args)
		{
			var output = CallContextServiceLocator.Locator == null ? "locator is null" : "(ツ)";
			Console.WriteLine(output);
		}
	}
}
```

```json
{
	"dependencies": {
		"Microsoft.Dnx.Runtime":"1.0.0-*"
	},
	"frameworks": {
		"dnx451":{},
		"dnxcore50":{
			"dependencies": {
				"System.Console":"4.0.0-beta-*"				
			}
		}
	}
}
```
### Results
```
$ dnvm use 1.0.0-beta7-12275 -r coreclr
$ dnx . run
locator is null
```

**Comment by glennc** [comment]
@davidfowl Any idea why it would be null in this case?

**Comment by BrennanConroy** [comment]
I could repro this before, but on dnx 1.0.0-beta7-12348 it is no longer null.

**Comment by natemcmaster** [comment]
How did you verify? with 12348/Darwin, I get:
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Cci.MetadataWriter.GetRowCounts()
   at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[] methodBodyRvas, BlobBuilder mappedFieldDataWriter, BlobBuilder resourceWriter)

**Comment by BrennanConroy** [comment]
You have to replace System.Reflection.Metadata and System.Collections.Immutable

**Comment by davidfowl** [comment]
You should never depend on  Microsoft.Dnx.Runtime directly. You only need the abstractions.

**Comment by natemcmaster** [comment]
@BrennanConroy replace them with what?

So this is fixed by changing the dependency to Microsoft.Dnx.Runtime.Abstractions?

**Comment by davidfowl** [comment]
Nope, just an observation

**Comment by BrennanConroy** [comment]
Haven't been able to repro this for quite a few builds. Closing.

**Comment by grahamehorner** [comment]
was this fixed in the beta7 release; I'm still seeing the issue with aspnet console applications?

**Comment by BrennanConroy** [comment]
Could you give some details please

Sent from my HTC

----- Reply message -----
