### ISSUE TITLE
Interoperability with Zero Install

### ISSUE THREAD

**Issue by bastianeicher** [aspnet/dnx#2444]
I hope a ticket here is the right place for this kind of high-level idea, otherwise I'm happy to repost if somebody can point me to a suitable mailing list or similar.

I work on [Zero Install for Windows](http://0install.de/), a package manager written in C#. It has a lot of design commonalities with DNX:

* packages are installed per-user
* multiple versions can exist side-by-side
* "installing" an app to `PATH` is handled by creating stubs that point back to the package manager which is responsible for launching the app

I was wondering whether you guys think there is any potential for synergy between DNX and Zero Install?

Zero Install provides a GUI and "desktop integration" options such as file type associations and Start Menu entries. It uses uses XML feeds as its package format. We have already created a [service that maps Maven artifacts to Zero Install feeds](https://github.com/0install/pom2feed). Something similar could probably be done for NuGet packages.

Looking forward to your feedback. :)

**Comment by glennc** [comment]
What sort of integration did you have in mind? I'm not familiar with Zero Install but it appears to be mostly about installing and managing applications and utilities, something like what Chocolatey is often used for. Is that assumption correct?

**Comment by bastianeicher** [comment]
You're right, Zero Install is a package manager like Chocolatey. However, there a lot of [design differences](https://0install.de/about/product-comparison/) that make Zero Install, imho, better suited for isolated apps and Chocolatey better for stuff that integrates more deeply with the OS. Zero Install also runs on Linux and OS X.

I was thinking about using Zero Install for deploying DNX console applications. If someone were, for example, to implement a .NET Core version of Scala (let's call it CoreScala) a [Zero Install feed](http://0install.net/interface-spec.html) for it might look something like this:
```xml
<interface uri="http://scala.org/core-scala.xml">
  <name>CoreScala</name>
  <summary>a .NET Core version of Scala</summary>
  <implementation version="1.0">
    <!-- Get the binaries from a NuGet package -->
    <archive href="https://www.nuget.org/api/v2/package/CoreScala/1.0" type="application/zip"/> 

	<!-- Pull in a dependency from another feed (which is probably also backed by a NuGet package) -->
    <requires interface="http://somserver.org/awesome-lib.xml"/>

	<!-- Define main command for launching the app (named "run" by convention) -->
    <command name="run" path="app">
	  <!-- Special kind of dependency that is used as a launcher for this application (other examples: JRE, Python, ...) -->
      <runner interface="http://asp.net/dnx.xml"/>

	  <!-- Command-line arguments passed to the launcher; the fully expanded path to the "app" directory is appended at the end -->
      <arg>Microsoft.Framework.ApplicationHost</arg><arg>scala</arg><arg>--appbase</arg>
    </command>

	<!-- Define secondary command -->
    <command name="scaladoc" path="app">
      <runner interface="http://asp.net/dnx.xml"/>
      <arg>Microsoft.Framework.ApplicationHost</arg><arg>scaladoc</arg><arg>--appbase</arg>
    </command>
  </implementation>

  <!-- Offer "desktop integration" of app capabilities (e.g. file associations) to user -->
  <capabilities>
    <file-type id="Scala.Code">
      <description>Scala Code File</description>
      <extension value=".scala"/>
    </file-type>
  </capabilities>
</interface>
```
The user could then run Scala without an explicit install step:
`0install run http://scala.org/core-scala.xml`
Or show a GUI for creating command-line aliases, start menu entries, file type associations, etc.:
`0install integrate http://scala.org/core-scala.xml`

All of this already works in principle, but manually creating Zero Install feeds for everything is quite a time-hog. If you guys think using Zero Install as a deployment option for DNX apps makes sense, working on a web-service that transparently maps NuGet packages to Zero Install feeds could be the next step.

**Comment by bastianeicher** [comment]
One more thought: The recently introduced `dnu sources` (aspnet/Announcements#46) command requires `git` to be in the `PATH`. Zero Install can be used to download such dependencies transparently on-demand.

**Comment by muratg** [comment]
Thanks for the discussion, @bastianeicher.  We do not have any plans to officially support 3rd party package managers for our acquisition story.  Scenarios like above can be community driven and maintained. Closing this one.
