### ISSUE TITLE
Support extern aliases in DNX

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/dnx#2445]
![image](https://cloud.githubusercontent.com/assets/6998306/9151979/bf283e20-3e17-11e5-924a-dc403b560d46.png)

Though not very popular, extern aliases are useful to work around `CS0433 Type 'X' already exists in both 'A.dll' and 'B.dll'` compilation errors, specially since we can't exclude transitive dependencies yet.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#564
