### ISSUE TITLE
DNU should allow absence of "versions" property in v3 index.json

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2447]
That means we also consider unlisted packages during restore. It can also fix the exception thrown by `dnu restore` when restoring package like https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json

@davidfowl  agrees that this can be assigned to me.

**Comment by pranavkm** [comment]
cc @yishaigalatzer Might be something that needs to be ported to nuget.

**Comment by yishaigalatzer** [comment]
This seems wrong. The plan is to fix the server, although we can revisit the discussion worth a short f2f tomorrow

**Comment by ChengTian** [comment]
@yishaigalatzer , to fix at server side, do you want to return `index.json` that always contain `versions` property, even it is empty?

The current problem is that if all versions of a package are unlisted, we get `index.json` like
```json
{
  "unlistedVersions": [
    "1.0.0"
  ]
}
```
The absence of `versions` property makes `dnu` think it is an invalid response.

/cc @davidfowl @lodejard

**Comment by ChengTian** [comment]
Talked to @davidfowl and we want to leave the current implementation for now. I filed an issue for fixing at server side: https://github.com/NuGet/NuGetGallery/issues/2617

**Comment by ChengTian** [comment]
Need a discussion to decide whether we still want this change. Putting to backlog.

**Comment by lodejard** [comment]
Seems reasonable to treat missing property the same as an empty array

**Comment by ChengTian** [comment]
@lodejard , makes sense, I have a PR for it here: https://github.com/aspnet/dnx/pull/2459. Please help to review.

**Comment by ChengTian** [comment]
The work at server side is tracked at https://github.com/NuGet/NuGetGallery/issues/2617 and NuGet team is deploying the changes now. The fix at DNX side is merged. Closing.
