### ISSUE TITLE
Suggestions to improve publish performance to Kudu

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#2448]
Publish time to Azure using Kudu isn't awesome right now. Here's some suggestions of things we can try to make it better:

- [x] Make 'dnu publish' copy already unzipped package contents rather than copy then unzip at destination. This should help speed up deployments as there will be significantly less IO on the durable (slow) drive.
- [x] `dnu build` (called by `dnu publish`) on project with commands configured results in `project.json` in bin folder, which will cause attempted restore on next `dnu restore` (as it dives into the bin folder).
(done in 0dda8bf86863364cc20421f1af7494f1b2a3256f)
- [ ] Kudu sync seems to copy more than just the expected changed items across on each deployment, perhaps time-stamps aren’t being set properly or something.
- [ ] `dnu restore` could potentially use the package cache (once installed) during restore and create junctions in place, so that restore on a cold site doesn’t have to hit the feed or copy any files for packages in the cache.

**Comment by troydai** [comment]
Currently working __item 2__. I plan to stop dnu restore from diving into subfolder of a folder already containing a `project.json`

**Comment by troydai** [comment]
Update: looks like we already did it however __partially__ (https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/RestoreCommand.cs#L107)
If the given `restoreDirectory` doesn't contain a `project.json` it will still dive into deeper level.

**Comment by muratg** [comment]
Yeah, nuget/dotnet tasks to improve restore time are tracked elsewhere. Closing
