### ISSUE TITLE
Passing arguments to project.json

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#2450]
When building a csproj with msbuild you can pass it arguments. For example, treating errors as warnings can be enabled with this argument:

/p:TreatWarningsAsErrors=true

It was be useful to be able to pass arguments to a project.json on build (treat warnings as errors, strong name path, etc)

**Comment by Eilon** [comment]
Hmm, interesting. I think there are a couple ways (at least) to go about this:

1. MSBuild style, where "everything's a variable/list" (you know, the PropertyGroup stuff)
2. Allow some sort of `$(variable)` syntax for variables that are either env-vars, or command-line params

I don't see (1) happening, but (2) is certainly interesting (to me). Might be other reasonable options as well.

**Comment by JamesNK** [comment]
You could do option 1 with some kind of path (since Json isn't a flat list)

Eg compilationOptions.treatWarningsAsErrors=true

For now I'm going to have to transform the file myself in my build script and I'll probably use a path to insert the new value.

**Comment by Eilon** [comment]
@JamesNK ah interesting. I hope you know a good JSON parser for your transformations :smile: 

With paths we'd have to consider how some more complex items would be persisted, e.g. dictionaries that have complex property names, or arrays. For example, even with setting compilation options, you can have that vary per framework, and the "path name" for those could get ugly (especially when they have weird characters in them).

I do think this would be an interesting feature (whatever it ends up being).

**Comment by JamesNK** [comment]
Ok. I'm not a fan of (2) because it would force those params to always be passed it. Optionally passing them in as overrides is more flexible.

I ended up using PowerShell's JSON functionality to modify the project.json so didn't do anything with paths myself.

**Comment by JamesNK** [comment]
FYI there are some cases where you can pass settings in via environment variables, e.g. DNX_BUILD_KEY_FILE

https://github.com/JamesNK/Newtonsoft.Json/commit/b7cfafb8ed5223a2cf9ea7a893292edaa63eb27b#commitcomment-12644907

**Comment by moozzyk** [comment]
AFAIR we decided to leave DNX_BUILD_KEY_FILE to not break the CI... @davidfowl do you remember?

**Comment by davidfowl** [comment]
We added it originally for the NuGet build.

**Comment by anurse** [comment]
It's also a useful feature for cases where you want CI builds to do something but not dev builds. Having said that, a general purpose override system is also useful for that...

**Comment by victorhurdugaci** [comment]
+1 for this. We need it for feature defines (like disabling the min version check on dev)

**Comment by victorhurdugaci** [comment]
Related: https://github.com/aspnet/Home/issues/450#issuecomment-145644823

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#563
