### ISSUE TITLE
During restore, if a package fails to be found, show why it was requested.

### ISSUE THREAD

**Issue by Alxandr** [aspnet/dnx#2451]
The last few days, I've been getting errors during restore that it can't find Roslyn v2. Now, I've resolved this by adding a new nuget feed, but the main problem was I had no idea why this was happening. I didn't know if this was caused by some renamed package, or something wrong in my project. When errors like this occur, please show why the package was requested in the first place (Roslyn required by Razor required by Mvc required by my project).

**Comment by davidfowl** [comment]
Did you try `dnu list`? This can get complicated if multiple packages are missing and there's no good way to show it on the command line. We actually went through several iterations of this before and opted to not show a dependency tree for each unresolved thing because it got too noisy.
