### ISSUE TITLE
DNX working directory

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#2453]
I have the following directories:

c:\src
c:\src\Newtonsoft.Json.Tests

I am executing a unit test project from a CMD open at c:\src

    c:\src\> dnx .\Newtonsoft.Json.Tests\project.json test

However this causes some tests to fail because the working directory is still c:\src. A test that has code like File.ReadAllText("test.json") will fail because .NET will attempt to load it from c:\src\test.json.

I thought maybe setting --appbase to Newtonsoft.Json.Tests would fix this but it gave me this error:

    System.IO.FileLoadException: The given assembly name or codebase was invalid.

I could change the working directory in PowerShell/CMD prior to calling the test project but passing it as an argument to dnx would be simpler/nicer.

**Comment by victorhurdugaci** [comment]
Assuming you use the latest beta7: https://github.com/aspnet/Announcements/issues/52

**Comment by davidfowl** [comment]
We wouldn't change the working directory. I'm not sure of many tools that do that. It just seems like a bad idea.

**Comment by fddima** [comment]
@JamesNK DNX should not change working directory.

Just see on dnu.cmd:
```
"%~dp0dnx" %DNX_OPTIONS% "%~dp0lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" %*
```

Similar "shortcut" shell scripts used widely in all existing systems with java, mono and other programs, what allow us to pass filename as parameter.

**Comment by tuespetre** [comment]
dnx-watch has this option for some reason?

https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher/Program.cs#L86
