### ISSUE TITLE
`dnu pack` hangs at "Embedding repository information..."

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#2455]
Seeing this issue quite regularly. `dnu pack` completes and the build script hangs for 3-5 minutes at `Embedding repository information...`. Terminating the spawned git.exe sorts this issue out. 

Process Explorer snapshot for reference:
![screenshot](https://cloud.githubusercontent.com/assets/174281/9205806/31d770a0-4019-11e5-9802-df4f8848805a.png)
Reproed this with dnx-clr-win-x86.1.0.0-beta7-12335

That said, embedding the commit information for a work in progress commit seems quite pointless. Why isn't this an opt-in feature so the CI sets it up for you?

**Comment by davidfowl** [comment]
We can't backlog this. It hangs on some people's machines making build unreliable.

**Comment by NTaylorMullen** [comment]
Just ran into this. Please don't backlog! :smile:

**Comment by galexandrov** [comment]
simple workaround is just to rename .git folder where git status is executed. :smile:

**Comment by pranavkm** [comment]
I'm still seeing this. This hangs my local builds for 3+ minutes per project.
