### ISSUE TITLE
React to System.Security.Cryptography.* changes in CoreFX

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/dnx#2456]
https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c

![image](https://cloud.githubusercontent.com/assets/6998306/9151283/543630a0-3dfd-11e5-9d66-d5b3e0d73dbd.png)

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/project.json#L45

/cc @Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/dnx/blob/dev/makefile.shade#L599-L604
