### ISSUE TITLE
Add API to determine number of physical CPU cores

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/dnx#2458]
`Environment.ProcessorCount` returns the number of virtual CPU cores, which on machines with HyperThreading is twice the actual number of physical cores. Some work is better suited to matching the number of physical cores (e.g. network IO) but there is currently no API to get this information.

Suggest we do something like `IRuntimeEnvironment.PhysicalProcessorCount`.

**Comment by moozzyk** [comment]
#1970/#2063
