### ISSUE TITLE
How to nest files?

### ISSUE THREAD

**Issue by Fosol** [aspnet/dnx#2465]
My search for answers has led me here.

By default a DNX project nest files like config.json -> config.debug.json

I want to be able to nest files like config.json -> config.development.debug.json

How do I do this? I can no longer edit my project file to do this because someone has decided to extract all that functionality and hide it away in some black box. 

Feel free to point me to the right place to ask this question.

Thanks,
 Jeremy

**Comment by davidfowl** [comment]
Can you file this bug on aspnet/Tooling?
