### ISSUE TITLE
The design time host build failed with the following error: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#2469]
Trying to build EntityFramework-dnx.sln in Visual Studio using the latest bits...

**Comment by troydai** [comment]
Is it constant?

**Comment by troydai** [comment]
https://github.com/aspnet/dnx/issues/2483

**Comment by anurse** [comment]
Fixed in https://github.com/aspnet/dnx/pull/2486, which is chugging through the (new and fancy) CI
