### ISSUE TITLE
Xml documentation missing in debug

### ISSUE THREAD

**Issue by scabana** [aspnet/dnx#2472]
I don't know if it's the right place for this, my guess it's either here or in the [Hosting](https://github.com/aspnet/Hosting) repository.

The problem is getting the xml documentation while debugging. At this point in time, it's not outputted anywhere and there's no way (that I know) to get it. As for packaging the website (with pubxml) and the option of pre-compiling set to true, you then get a dll and an xml file for that dll (which is outside of the wwwroot). I haven't tried to get ahold of that file from the application (yet). If there's no solution for that right now, one solution would be to have it accessible as metadata or property of the ```Library``` class. 

My usecase is to provide it to Swashbuckle for documentation purposes.

**Comment by davidfowl** [comment]
It'll be back post RC2
