### ISSUE TITLE
Make the runtime working memory disposable

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2475]
After building LibraryManager we should be able to drop a whole bunch of state from memory. Let's try building something like the RuntimeBuilder we had in the "new runtime". All the data used for dependency walking should be dumped once we are able to create a LibraryManager. Similarly, the LibraryExporter can be a transient data structure with a cache. Once the project is compiled, the exports aren't needed (except for things like Razor that re-read the exports for their own compilations). Those that do need the exports can re-calculate them (and we can have a cache that tries to keep them around)

**Comment by anurse** [comment]
(This is mostly notes for me from a convo with @davidfowl - Self-assigning in beta8 /cc @Eilon)

**Comment by davidfowl** [comment]
Some of this is done already. We need to look at exports and other things of that nature.

**Comment by anurse** [comment]
Yep, I'm keeping this open to make sure to spend time this milestone really going through the memory usage. I expect to do a full dotMemory profile, and probably work on #1446 at about the same time

**Comment by anurse** [comment]
Closing and NOT tagging Done as @davidfowl has been mostly working on this and should have most of it done now.
