### ISSUE TITLE
Upon start, DNX should print all environment variables that it uses and their value

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2479]
When running with `DNX_TRACE`, dnx should show the values of all the environment variables that are used to configure it (like `DNX_SERVICING_ROOT` or `DNX_REQUIRE_SERVICING`). It would help debugging and it would also make them more discoverable.

Example output:

    DNX_SERVICING_ROOT: C:/foo
    DNX_REQUIRE_SERVICING: <not set>

**Comment by Eilon** [comment]
I like this.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#562
