### ISSUE TITLE
Extremely high memory usage in DTH for Mvc.NoFun.sln

### ISSUE THREAD

**Issue by rynowak** [aspnet/dnx#2483]
I'm now regularly seeing memory usage climb to around 1.2gb in DTH on the smaller MVC solution (~30 projects). This makes VS slow to crawl and every operation feels extremely sluggish. 

Using 1.0.0-beta7-12356

I can easily repro this, and it seems to occur most frequently when doing a build in VS resulting in compilation errors.

I have a memory dump available, here's what's using all of the memory and how it's rooted:
![image](https://cloud.githubusercontent.com/assets/1430011/9279126/239af536-426a-11e5-9e43-4b902b31ab1d.png)

**Comment by troydai** [comment]
Similar issue happens in EF as well. Our allocation is intensive.

**Comment by anurse** [comment]
I'm taking a look at this. I'm not sure why my change would have caused it, but it seems connected :)

**Comment by anurse** [comment]
I've identified a potential leak, once I've got a repro I should be able to do a before/after comparison and have a fix out.
