### ISSUE TITLE
Error message does not show up in error list when the error is only in one framework

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2487]
This reproed with specific repro steps:
 
- Create a new class library
 
- Remove "dnx451" framework from the dependencies list
 
- Remove all dependencies in the "dnxcore50" and add one dependency, 
"EntityFramework" : "6.1.3" (which is not supported in core, so an error is shown)
 
- Now add back "dnx451" framework and observe that the previous error message disappeared whereas it should be shown. 
 
Note: Restore does happen and after debugging I saw 4 DependencyDiagnostics messages received when last one removes expected error for dnxcore50 and we and up with no errors in error list:

![nodependenciesdiagnostics](https://cloud.githubusercontent.com/assets/1592091/9284732/47528b64-42ac-11e5-87f0-c66afc8abbb7.png)

**Comment by troydai** [comment]
I'll take a look.

**Comment by troydai** [comment]
I can confirm this issue. `DependencyDiagnostics` are sent twice for two frameworks. The second one suppress the first one.

```
Information: [ProcessingQueue]: Send((59db3afca7fd498ab7f75cbea9f3b944, DependencyDiagnostics, 4) -> {
  "Framework": {
    "FrameworkName": "DNXCore,Version=v5.0",
    "FriendlyName": "DNX Core 5.0",
    "ShortName": "dnxcore50",
    "RedistListPath": null
  },
  "Errors": [
    {
      "SourceFilePath": "c:\\Users\\Xueyuan\\Documents\\Visual Studio 2015\\Projects\\ClassLibrary3\\src\\ClassLibrary3\\project.json",
      "Message": "The dependency EntityFramework 6.1.3 in project ClassLibrary3 does not support framework DNXCore,Version=v5.0.",
      "Severity": 2,
      "StartLine": 15,
      "StartColumn": 28,
      "EndLine": 15,
      "EndColumn": 28,
      "FormattedMessage": "c:\\Users\\Xueyuan\\Documents\\Visual Studio 2015\\Projects\\ClassLibrary3\\src\\ClassLibrary3\\project.json(15,28): error: The dependency EntityFramework 6.1.3 in project ClassLibrary3 does not support framework DNXCore,Version=v5.0."
    }
  ],
  "Warnings": []
})
Information: [ApplicationContext]: OnTransmit(DependencyDiagnostics)
Information: [ProcessingQueue]: Send((59db3afca7fd498ab7f75cbea9f3b944, DependencyDiagnostics, 4) -> {
  "Framework": {
    "FrameworkName": "DNX,Version=v4.5.1",
    "FriendlyName": "DNX 4.5.1",
    "ShortName": "dnx451",
    "RedistListPath": "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.5.1\\RedistList\\FrameworkList.xml"
  },
  "Errors": [],
  "Warnings": []
})
```

**Comment by troydai** [comment]
The messages looks good to me. @PradeepKadubandi will help further inspect into VS tooling's logic.

**Comment by abpiskunov** [comment]
Troy you showed snapshot with only 2 messages when I had at least 4 messages received and for the last one I took a screen snapshot - it removes error diagnostic

**Comment by abpiskunov** [comment]
Could you try repro again?

**Comment by troydai** [comment]
@abpiskunov I can repo this issue, but I think we need to work together to locate the root cause.

The two messages I listed above were sent after DTH got `RestoreComplete` and `RefreshDependencies`.

**Comment by abpiskunov** [comment]
Figured it out. Diagnostics sent per framework and our code for dependency diagnostics specifically did not take into account frameworks and grouped them all together, which resulted in last diagnostic for dnx451 clear diagnostic for dnxcore. Reopened tooling bug.
