### ISSUE TITLE
No Mono support (on Windows)?

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2493]
"dnvm install latest -arch x86 -r mono" causes an error in Windows:

dnvm-install : Cannot validate argument on parameter 'Runtime'. The argument "mono" does not belong to the set ",clr,coreclr" specified by the ValidateSet attribute.

Is this intended? I was working towards making my app support every CLR flavor currently but I am unable to test the mono back-end out on Windows because of this.

**Comment by davidfowl** [comment]
We don't support mono on windows.

**Comment by xanather** [comment]
Okay, no problem closing...

**Comment by dougbu** [comment]
Hmm @davidfowl with the latest `dnvm`, `dnvm install latest -os linux` works fine, installing the Mono bits in case I want to `publish` with them. Probably won't execute but the installation went fine.

Looks like the main issue here is `-r mono` versus `-os linux`. FYI current error for `dnvm install latest -r mono` is
```
Unable to determine an operating system for a mono runtime. You must specify which OS to use with the OS parameter.
At C:\Users\dougbu\.dnx\bin\dnvm.ps1:284 char:13
+             throw "Unable to determine an operating system for a $($runtimeInfo. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to deter...e OS parameter.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to determine an operating system for a mono runtime. You must specify which OS to
    use with the OS parameter.
```

**Comment by anurse** [comment]
That looks like a DNVM issue. I believe dnvm.sh may have some defaults that dnvm.ps1 doesn't have. /cc @glennc @BrennanConroy

**Comment by davidfowl** [comment]
We still don't support mono on windows even after we fix dnvm :smile:

**Comment by anurse** [comment]
Right, but you should be able to install it in order to publish with it.

**Comment by davidfowl** [comment]
Publish what exactly?

**Comment by anurse** [comment]
Publish an app with `--runtime`
