### ISSUE TITLE
IRuntimeEnvironment.OperatingSystemVersion returns "6.2" on Windows 10

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2494]
IRuntimeEnvironment.OperatingSystemVersion returns 6.2 on Windows 10. Maybe it's hardcoded?

**Comment by davidfowl** [comment]
Maybe what is hardcoded?

**Comment by xanather** [comment]
The windows 10 version is Version 10.0.10240, I think 6.2 is Windows 8

**Comment by PinpointTownes** [comment]
`IRuntimeEnvironment`'s default implementation relies on `Environment.OSVersion` (at least for the DNX451 bits), which internally calls `GetVersion`/`GetVersionEx`, whose behavior has changed with Windows 8.1:

> With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version. The value returned by the GetVersionEx function now depends on how the application is manifested.
Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases. To manifest your applications for Windows 8.1 or Windows 10, refer to Targeting your application for Windows.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx

**Comment by xanather** [comment]
Well that's abit silly, I'm sure it was for compatibility reasons though. Seems like the only way to return the correct value now is to check if GetVersion returns 6.2 and then determine if we're on windows 10 or not using some other method.

**Comment by anurse** [comment]
It looks like we can manifest for multiple OSes, it's not a matter of building, just a matter of writing an XML file (https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx)

/cc @moozzyk @davidfowl

**Comment by anurse** [comment]
Though Windows recommends use of the [IsWindows...](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx) APIs instead, so maybe we should be looking to get managed versions of those APIs?

**Comment by moozzyk** [comment]
We should address this in #2282

**Comment by davidfowl** [comment]
The CLR team added RuntimeInformtion.Is{Os}

**Comment by xanather** [comment]
Seems to be fixed in beta8.

**Comment by moozzyk** [comment]
@xanather we changed it a bit post-beta8 - you will get 6.x for pre-win10 versions of Windows (and not 7, 8, 8,1). For Windows 10 you will continue to get 10.0. Out of curiosity what do you use Windows version for?

**Comment by xanather** [comment]
I am using Windows 10.

**Comment by moozzyk** [comment]
Yes, but why do you need to know the version?

**Comment by xanather** [comment]
Its more of a diagnostics/stats thing. If the end-user of my app experiences crashes they will be able to submit a Crash.log file which includes what OS version they are running.

**Comment by moozzyk** [comment]
Thanks @xanather
