### ISSUE TITLE
Missing package on nuget feed -> exception on dnu restore

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2496]
Original question here: http://stackoverflow.com/questions/32033532/asp-net-5-failing-to-install-asp-net-5-nuget-package

They have http://MyGet.org/aspnetmaster as a feed and they look for a package that doesn't exist.

Request:
`http://MyGet.org/aspnetmaster/FindPackagesById()?id='Boilerplate.Web.Mvc6'`

Response: 

```
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
1	302	HTTP	myget.org	/aspnetmaster/FindPackagesById()?id='Boilerplate.Web.Mvc6'	181	private		fiddler:8188			
2	200	HTTP	myget.org	/Error/Status/404?aspxerrorpath=/aspnetmaster/FindPackagesById()	9,873	public, no-cache="Set-Cookie", no-store, max-age=0, s-maxage=0; Expires: Mon, 17 Aug 2015 02:09:49 GMT	text/html; charset=utf-8	fiddler:8188			
```

and the body is HTML.

This might be a myget bug (cc @maartenba)...

Anyway, the point is that we get HTML back and we try to parse it as XML. dnu should be more resilient to that.

**Comment by davidfowl** [comment]
What version of DNX is being used? I'm pretty sure we try to validate the actual http response now /cc @ChengTian

**Comment by victorhurdugaci** [comment]
CLR-x86-1.0.0-beta7-12364

**Comment by davidfowl** [comment]
Ah, looking at the exception it's doing the right thing. We used to cached these responses (200 and invalid) now we don't. The user can run --ignore-failed-sources to work around. Unfortunately you can't pass this flag within visual studio... /cc @sayedihashimi

**Comment by victorhurdugaci** [comment]
Should myget return a 404?

**Comment by victorhurdugaci** [comment]
Or at least an XML with no results

**Comment by davidfowl** [comment]
Oh yes this is a myget bug I'm just saying this bug can be closed.

**Comment by victorhurdugaci** [comment]
Shouldn't dnx just give a warning instead of throwing?

The 200 response seems to be a myget bug: https://twitter.com/xavierdecoster/status/633137056009555968

**Comment by davidfowl** [comment]
There's a more general bug to clean up the exception messages for dnu as a whole.

**Comment by maartenba** [comment]
If we return a proper 404, can we still return html?

**Comment by davidfowl** [comment]
Yes we treat 404s specially

**Comment by maartenba** [comment]
This has been fixed on MyGet side. We now return proper 404 (and empty collection on the above call)

Side note: the request log above denotes a wrong URL. Instead of `/aspnetmaster/FindPackagesById()?id='Boilerplate.Web.Mvc6'` it should be `/F/aspnetmaster/FindPackagesById()?id='Boilerplate.Web.Mvc6'` (note the `/F/`)

**Comment by davidfowl** [comment]
Yep so it would have failed anyways.
