### ISSUE TITLE
Handling of incorrectly cased project.json in dnu restore on Linux

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/dnx#2497]
I just tried `dnu restore` on a project that had `Project.json` instead of `project.json` on Linux. Restore just printed nothing. Only after running `dnu build` I found out that the file is incorrectly cased since it complained about not finding `project.json`.

Should `dnu restore` complain similarly?

**Comment by muratg** [comment]
@davidfowl IMO, this should only go to nuget.  The restore feature in CLI is only temporary.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#561
