### ISSUE TITLE
Cross-process synchronization in DNX (named mutex, semaphore)

### ISSUE THREAD

**Issue by kouvel** [aspnet/dnx#2501]
There are a couple of named sync objects created in DNX. It looks like they are used to prevent concurrent writes to files:
- https://github.com/aspnet/dnx/blob/219871c6063d00f8297eeafe93266f1048f59a45/src/Microsoft.Dnx.Runtime/Internal/ConcurrencyUtilities.cs#L38
- https://github.com/aspnet/dnx/blob/219871c6063d00f8297eeafe93266f1048f59a45/src/Microsoft.Dnx.Tooling/NuGet/Core/Configuration/Settings.cs#L777

I understand that DNX is currently using Mono. Some tests I had done showed that while Mono allows creating and using named sync objects, the sync objects are actually process-local, so two process cannot synchronize on them. So this may not be working as expected currently.

Also, it has recently been decided that CoreCLR/CoreFX won't be supporting named sync objects at this time. Instead, in an interest to reduce confusion and the impact of breaking changes in the future if we do add that feature, CoreCLR/CoreFX will currently throw PlatformNotSupportedException when attempting to create a named sync object, see:
- https://github.com/dotnet/coreclr/pull/1387
- https://github.com/dotnet/corefx/pull/2796

So if DNX were to switch to CoreCLR/CoreFX, the code above would break.

A couple of potential solutions involving creating a file in some predetermined location with the name currently being used for the sync object:
- If it is not expected for these scenarios to have high contention, a simple, portable solution may be to use a FileStream to create/open a file using FileShare to get exclusive access to the lock file. Another thread/process trying to open the file with the same FileShare value would get an exception, and it can poll for access in a loop with short pauses.
- Another solution is on Unix to use flock() directly on a lock file. flock() can exclusively lock a file and another attempt to exclusively lock the same file would block. The lock is automatically released on process termination (in case of crash). But the lock file cannot be deleted safely since there won't be any ref counting.

CC @ChengTian, @loudej, @davidfowl

**Comment by ChengTian** [comment]
Here are some statistics that may help us make decision on which alternative we should use.

To roughly quantify the degree of contention, I introduce a global counter `ContentionCount` in `dnu restore`.

**Definition: each time a thread/process tries acquiring a named semaphore but has to wait, we do `ContentionCount++`.**

Here are values of `ContentionCount` in different scenarios:

**1 . `dnu restore --parallel` in root dir of Mvc repo:**

Average `ContentionCount`: 4390

Average Restore Time: 53.2s

`ContentionCount` per Second: 82.5

Comments: in this scenario we only run one `dnu restore` process and the contentions happen between threads

**2 . Two instances of `dnu restore --parallel <Mvc_Root_Dir>` running simultaneously:**

Average Total `ContentionCount` (`Instance1.ContentionCount` + `Instance2.ContentionCount`): 9989

Average Restore Time (per `dnu restore` instance): 65.8s

`ContentionCount` per Second: 151.8

**Comment by anurse** [comment]
As much as it may seem ugly, it seems to me that the unix-y way would be to [`flock`](http://man7.org/linux/man-pages/man2/flock.2.html) the directory into which we are installing packages.
