### ISSUE TITLE
Adding DTH integration test

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2502]
Port from https://github.com/troydai/Sparrow

- [x] Protocol Negotiation
- [x] Perform Compilation
- [x] Refresh Dependencies
- [ ] Wrap project
- [ ] Enumerate project (__in progress__: https://github.com/aspnet/dnx/pull/2922)
- [ ] Get compiled assembly
- [ ] File format exception
- [x] Compile error / warning
- [x] Change configuration

**Comment by anurse** [comment]
just attaching myself to the thread so I get notifications under the participating section ;)

**Comment by troydai** [comment]
The first test case has been checked in d4465d83c176bab267bca61b205d7ac7a13b625f.

**Comment by troydai** [comment]
Adding following tests now:
[] Protocol Negotiation
[] Compilation messages
[] Dependencies messages
[] Compilation diagnostics
[] Dependencies diagnostics

**Comment by troydai** [comment]
More work planned.

**Comment by muratg** [comment]
Remaining work can be done in RC1.

**Comment by troydai** [comment]
Not validate any more. Close.
