### ISSUE TITLE
When --no-cache is specified, dnu restore eats your disk like crazy

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2505]
Repro steps:
1. Clean your `%userprofile%/AppData/Local/Temp` folder
2. Run `dnu restore --no-cache --parallel` in root dir of Mvc
3. Your `%userprofile%/AppData/Local/Temp` keeps growing and becomes 700MB+.

There is no automatic cleanup after `dnu restore --no-cache` is done. It means that each time you do `dnu restore --no-cache` for Mvc repo, your temp folder grows by 700+MB.

Note that `dnu restore` does do temp file cleanup if `--no-cache` is not specified.

**Comment by akoeplinger** [comment]
https://github.com/aspnet/dnx/issues/1835
