### ISSUE TITLE
Could not restore Nowin package

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#2511]
When trying to restore Nowin v. 0.17.1 I get an error telling me that the package could not be located. The rest the DNX packages restored fine. I am using DNX v. 1.0.0-beta7-15019

**Comment by davidfowl** [comment]
Works fine for me. What error are you seeing? Can you show the restore output.

**Comment by borgdylan** [comment]
Errors in /var/www/Code/dylannet/vnext/NowinServerFactory/project.json
    Unable to locate Nowin >= 0.17.1

NuGet Config files used:
    /home/dylan/.config/NuGet/NuGet.Config

Feeds used:
    http://www.myget.org/F/aspnetwebstacknightly/
    /var/www/nugetfeed
    https://nuget.org/api/v2/curated-feeds/dotnetframework/
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://www.myget.org/F/npgsql-unstable/api/v2/
    https://www.myget.org/F/roslyn-nightly/
    https://www.myget.org/F/dotnet-corefx/

**Comment by borgdylan** [comment]
The same happens with 1.0.0-beta8-15118. I think its that package version normalization thing again.

**Comment by borgdylan** [comment]
Why isn't NuGet gallery listed? I certainly have it added:
```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="ASP.NET/EF MyGet" value="http://www.myget.org/F/aspnetwebstacknightly/" />
    <add key="My NuGet" value="/var/www/nugetfeed" />
    <add key=".NET NuGet" value="https://nuget.org/api/v2/curated-feeds/dotnetframework/" />
    <add key="ASP.NET vNEXT" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <!--<add key="NuGet v3" value=" https://api.nuget.org/v3/index.json" />-->
    <add key="Official NuGet Gallery" value="https://www.nuget.org/api/v2/" />
    <add key="Npgsql" value="https://www.myget.org/F/npgsql-unstable/api/v2" />
    <add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly" />
    <add key="DotNetFx" value="https://www.myget.org/F/dotnet-corefx" />
  </packageSources>
  <disabledPackageSources>
    <!--<add key="NuGet v3" value="true" />-->
    <add key="Official NuGet Gallery" value="true" />
  </disabledPackageSources>
</configuration>
```

**Comment by borgdylan** [comment]
It worked without ```disabledPackageSources``` being present in the file. This is an incompatibility with soem tools like MonoDevelop/Xamarin Studio which add the element inside teh config.

**Comment by borgdylan** [comment]
So we may need to move the bug to one of the nuget repos?

**Comment by davidfowl** [comment]
Yep.
