### ISSUE TITLE
Unable to locate Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150806-01

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2517]
Update to Latest dev version(v1.0.0-beta7-15019) produce this error.
Where is the Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150806-01?
Is it moved to another feed?

dnu restore has the same result.
Thanks

**Comment by per-samuelsson** [comment]
@mikeandersun 

I had the same this morning, and I started looking around the different feeds. Looks like there are now a bunch of feeds on `myget` and it's rather time-consuming to figure out how to set things up.

Here's a few now published:

```
aspnetlitedev
aspnetliterelease
aspnetvnext
aspnetrelease
dotnet-core
roslyn-nightly
```

Can't really help you to a "right" path to go unfortunatelly, since I haven't found any guidelines of what to use and what not. But for me, I managed to resolve this issue by changing my feed like this:

```
<!-- <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" /> -->
<add key="AspNetVNext" value="https://www.myget.org/F/aspnetliterelease/api/v2" />
```

How I got there? Well, I basically just skimmed through the recent DNX commits and found [this one](https://github.com/aspnet/dnx/commit/1b04cd1e786ba84f88496a3eae2e08f84701f533) from a few days back. Took a shoot at it and it worked out it seems. :sunglasses:

**Comment by troydai** [comment]
/cc @victorhurdugaci 

Hi @mikeandersun, sorry for the inconvenience. Unfortunately the latest DNX build on aspnetvnext is broken. We're working on publishing a good build as fast as we can, if you don't mind waiting for a day or two. If you need a workable build right now, please try set `DNX_FEED` to `https://www.myget.org/F/aspnetlitedev/api/v2` to get a unstable DNX build. It should solve your issue.

**Comment by troydai** [comment]
Thanks @per-samuelsson , you beat me by seconds. Yes the `aspnetliterelease` is also an option, which maps to beta7 build while `aspnetlitedev` hosts beta8 build.

**Comment by davidfowl** [comment]
Just FYI the lite{branch} feeds are untested so avoid using them if possible. It's better if apps are using aspnetvnext and aspnetrelease.

**Comment by per-samuelsson** [comment]
> Just FYI the lite{branch} feeds are untested so avoid using them if possible. It's better if apps are using aspnetvnext and aspnetrelease.

OK, got it. Thanks for sharing that @davidfowl.

FWIW, I tested to change from `aspnetliterelease` as suggested in this https://github.com/aspnet/dnx/issues/2517#issuecomment-132913634 to `aspnetrelease`, ran `dnu restore --no-cache` and it seems to work fine as well.

**Comment by mikeandersun** [comment]
`dnu restore --no-cache` use `aspnetvnext` rather that `aspnetrelease`.
How to I force it to use aspnetrelease. Or may may be install `dnx-*` from `aspnetrelease`
Thanks to clarify me

**Comment by per-samuelsson** [comment]
> dnu restore --no-cache use aspnetvnext rather that aspnetrelease.

[NuGet.config](https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages) is one way to set things up. The `DNX_FEED` env variable is the other I know of, but I haven't tried that one myself. 

If someone has a pointer to when/where `DNX_FEED` was introduced, and what tools consume it, I'd like to read about it also.

**Comment by mikeandersun** [comment]
The compilation errors go away but afer run i get this error:
`Method not found: 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions Microsoft.Dnx.Compilation.CSharp.CompilationSettings.get_CompilationOptions()'.`

**Comment by troydai** [comment]
@mikeandersun what's the project are you trying to run?

**Comment by troydai** [comment]
@mikeandersun we're pushing tested packages to `aspnetvnext` feed now. Can you that out?

**Comment by victorhurdugaci** [comment]
Package upload is in progress. Try in like 10 min or so

**Comment by 4nonym0us** [comment]
I'm having the same issue: the error message **Unable to locate Microsoft.CSharp >= 4.0.1-beta-23225** occurs when i try to run `dnu restore` with following feeds:
```
<add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
<add key="NuGet" value="https://nuget.org/api/v2/" />
<add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly/" />
<add key="DotNet" value="https://www.myget.org/F/dotnet-corefx/" />
```
`dnu restore --no-cache` works fine if i use the following feeds:
```
<add key="AspNetLiteRelease" value="https://www.myget.org/F/aspnetliterelease/api/v2/" />
<add key="NuGet" value="https://nuget.org/api/v2/" />
<add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly/" />
<add key="DotNet" value="https://www.myget.org/F/dotnet-corefx/" />
```
but I receive the following error when I try to run the application:
![image](https://cloud.githubusercontent.com/assets/2701409/9549849/c97d0d9e-4db0-11e5-87c5-86cf163ab06d.png)

It looks like some dependencies are still missing or they have incorrect version number.
Am I using the wrong feeds?
