### ISSUE TITLE
How to install bata8

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2520]
I use following command in PowerShell:
`dnvm install 1.0.0-beta8-15116 -unstable`
but it seems that ` -unstable` refer to aspnetvnext feed but beta8-* are in aspnetlitedev feed

**Comment by davidfowl** [comment]
Wait until it gets to aspnetvnext. aspnetlitedev isn't for use in your apps. It's untested builds used to develop our repositories.
