### ISSUE TITLE
Breadcrumbing other load contexts

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2522]
Today we only breadcrumb all packages at runtime only. Do we want to potentially breadcrumb all p2p build time graphs as well (aka any assembly loaded during compilation)?

**Comment by per-samuelsson** [comment]
> Do we want to potentially breadcrumb all p2p build time graphs as well (aka any assembly loaded during compilation)?

Sorry if I'm not really understanding this, but would it mean e.g. compile module dependencies being loaded where tracked too? 

Kind of funny if so, b/c I'm just in the middle trying to diagnose a kind of weird case in a compile module, and I might need to ask for help on it. I might have been better of if this was in place.

**Comment by per-samuelsson** [comment]
> Kind of funny if so, b/c I'm just in the middle trying to diagnose a kind of weird case in a compile module, and I might need to ask for help on it.

#2523

**Comment by moozzyk** [comment]
We breadcrumb to be able to service - would you want to service a project? Or there is a different scenario here?

**Comment by davidfowl** [comment]
It's about servicing code running in the compiler of the project. It's really and edge case but I just wanted to track it. By default we're fine because our compilers come in the dnx but you could imagine us in the future shipping compilers as nuget packages which we may want to service oob?
