### ISSUE TITLE
Compile module fail to load - RoslynCompiler CS1705

### ISSUE THREAD

**Issue by per-samuelsson** [aspnet/dnx#2523]
In short: my **compile module** meta assembly compile but **fail to load**. I think it's because a dependency chain issue where the DNX host has a different version that the compile module.

So, here it goes. I'm on a Win7 box, running DNX CoreCLR beta 7 (`dnx-coreclr-win-x64.1.0.0-beta7-15019`). I can trim my project down to the minimum:

```
src>dir /s
app1\Program.cs
app1\project.json
app1\compiler\preprocess\CompileModule.cs
```

_project.json_

``` json
{
    "version": "0.1.0",
    "dependencies": {
        "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-*"
    },
    "frameworks": {
        "dnxcore50": {
            "dependencies": {
                "System.Runtime": "4.0.20-beta-*",
                "System.Threading.Tasks": "4.0.10-beta-*",
                "System.Console": "4.0.0-beta-*"
            }
        }
    }
}
```

_CompileModule.cs_

``` C#
using System;
using Microsoft.Dnx.Compilation.CSharp;

namespace Test {
    public class CompileModule : ICompileModule {
        public void BeforeCompile(BeforeCompileContext context) {}
        public void AfterCompile(AfterCompileContext context) {}
    }
}
```

The _Program.cs_ is just an empty entrypoint.

I start totally clean, even deleting the `.dnx\packages` folder, and `dnu restore` will bring me down a set of ~30 packages or so.

In this context, running my thing, will give me this (ran it with tracing, but just picked out the central piece):

```
Error: [RoslynCompiler]: Failed loading meta assembly 'app1':
 Microsoft.Dnx.Compilation.CSharp.RoslynCompilationException: 
error CS1705: Assembly 'Microsoft.Dnx.Compilation.CSharp.Abstractions' with identity 'Microsoft.Dnx.Compilation.CSharp.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error CS1705: Assembly 'Microsoft.Dnx.Compilation.CSharp.Abstractions' with identity 'Microsoft.Dnx.Compilation.CSharp.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error CS1705: Assembly 'Microsoft.Dnx.Compilation.CSharp.Abstractions' with identity 'Microsoft.Dnx.Compilation.CSharp.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
error CS1705: Assembly 'Microsoft.Dnx.Compilation.CSharp.Abstractions' with identity 'Microsoft.Dnx.Compilation.CSharp.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.<>c__DisplayClass10_0.<GetCompileModules>b__0(CacheContext _)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
```

From my understanding of the massive (omitted) output, it looks like Roslyn can build and emit my module. But fails to _run_ it.

I've read up on dependency resolving and read @davidfowl blog post a second time, and I'm still nowhere closer on this than a guess. My guess is that when Roslyn precompile my application, it will emit metadata that reference `Microsoft.Dnx.Compilation.CSharp.Abstractions` as it comes down in a _package_, and that one has a reference to `System.Runtime 4.0.21.0`. Hence, compiling works. But when it attempt to _load_ that package, the current DNX host / CLR have `System.Runtime 4.0.20.0` loaded, and hence they collide. (I have reflected over `System.Runtime` in the CLR runtime folder, and it's indeed `4.0.20.0`).

Phew.

Now, what about my guess? And if it's right: how would one resolve such thing?

**Comment by per-samuelsson** [comment]
Addition to OP:

1. I have tested moving the reference to `Microsoft.Dnx.Compilation.CSharp.Abstractions` to the framework specific dependencies, hoping that it might bind to the assembly there. Same thing happens.

2. If I change the framework dependency from `System.Runtime": "4.0.20-beta-*` to `System.Runtime": "4.0.21-beta-*`, I get another error:

```
Error: [RoslynCompiler]: Failed loading meta assembly 'app1':
 System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.<>c__DisplayClass10_0.<GetCompileModules>b__0(CacheContext _)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
```

**Comment by per-samuelsson** [comment]
On a more general level, I'd really like to see some kind of text that outlines the important differences and nuances of specifying dependencies in general.

First, there is the top level **project.json** `dependencies` hive. Than another one scoped in target frameworks. Then an additional one in frameworks, dubbed `frameworkAssemblies`, as can be seen [here](https://github.com/aspnet/Home/wiki/Project.json-file#example-projectjson-from-one-of-the-ef-projects).

```
{
  "dependencies": {
    "Foo": ""
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "Bar": ""
      }
    },
    "dnxcore50": {
      "dependencies": {
        "Baz": ""
      }
    }
  }
}
```

On top of that, theres an SDK-thingy you can specify in the **global.json**.

I guess the main difference between top-level and framework-specific dependencies are that the ones you scope to a framework only... well, relates to builds that target it? Are they also resolved from some other kind of feed/source?

I did notice that if I skipped project-level dependencies as a whole, and scoped my single `Microsoft.Dnx.Compilation.CSharp.Abstractions` reference to the framework (after all, there is an assembly with that name inside the runtime folder), doing `dnu restore` on an empty `packages` folder still brought down a lot of packages.

**Comment by davidfowl** [comment]
Are you running from the command line?

Try making your project.json this:

```JSON
{
    "version": "0.1.0",
    "dependencies": {
        "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-*"
    },
    "frameworks": {
        "dnxcore50": { }
    }
}
```

Microsoft.Dnx.Compilation.CSharp.Abstractions should already bring in the relevant transitive dependencies.

This type of thing is sorta new to .NET in some ways, combined with `project.json` there are a bunch of new concepts to understand that aren't clearly documented today because things are in flux (we're just not done yet). 

Here's a brief overview:

There are 2 dependency graphs in your application, the one required to run your application and resolve compilation dependencies (e.g. you're compiling for and running on dnxcore50) . The other one is required dependencies of the compiler and ICompileModules themselves, e.g. what we call the "build time graph" (where the target framework of the compiler itself matters not your application). In your above `project.json` you only list `dnxcore50` which maps to dnx-coreclr-{whatever}, but your could be running under under `dnx-clr-{whatever}` so you need to specify the required by the compiler itself as well as your application.

On top of that, we currently allow you to write these ICompileModules within your project, but they cannot come as package dependencies (i.e. they won't be discovered if they are only in nuget packages). That makes it a little more complicated. They are also hard to debug since they can run in the build process or in the design time host process.

We're still trying to decide if we keep this feature or not (depending on how well we can make it work across the board).

**Comment by per-samuelsson** [comment]
@davidfowl, thanks for the extended feedback!

> Are you running from the command line?

Yes, I am. Trying to avoid VS at any cost initially while learning your new stack. Those kind of tools tend to get in the way when doing so IMO. :smile: 

> [...] there are a bunch of new concepts to understand that aren't clearly documented today because things are in flux (we're just not done yet).

I do know that, and I totally respect that. I love what you are doing, and when I ask for something, I consider it a "shoutout", you know, just sharing what I think should be adressed at some point. I don't expect it to be there, as I might have in a mature product.

> Here's a brief overview:

Thanks. I'll think this through a little. I might come back if there's something in it I dont fully understand.

> Try making your project.json this:

I'll try that, and consider what it means too, given the info you provided above.

> On top of that, we currently allow you to write these ICompileModules within your project, but they cannot come as package dependencies.

So thas why there was not response in #1072 then. :smile: 

> We're still trying to decide if we keep this feature or not (depending on how well we can make it work across the board).

Ouch. This feature is really a main attractor for us and the product I work on (we are switching from a PostSharp-based binary IL weaver to this new approach, modifying the syntax trees) . If you decide to drop it, would there be some other means modifying trees before they are consumed by the compiler do you think?

**Comment by davidfowl** [comment]
I haven't given up yet. We're trying to see if we can salvage the feature for v1😀

**Comment by Antaris** [comment]
@davidfowl If this makes V1, it would be epic. the way in which `ICompileModule` opens up new scenarios is amazing - it's a hidden gem but a real killer feature of the DNX platform. Couple of the scenarios I am hoping to use it with:

- Build-time discovery of extensibility modules in for a CMS framework - no more System.Reflection runtime discovery - find them, generate some wire-up code and you're done :-)
- Build-time generation of database script migration classes - per module assembly, taking versioning into consideration
- Build-time discovery of a entity type configurations to compose per module EF database contexts with shared types.

I've been prototyping the first two and am very happy with the results - the latter I haven't look at yet, but it's all thanks to `ICompileModule`!

Now if only we *could* deploy them as NuGet packages, it would make it even simpler for consumers :-)
