### ISSUE TITLE
DNU is missing the compatibility check present in Nuget v3

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#2525]
Nuget v3 does a probe of the run-time graph to ensure that every ref has a matching lib.  This check is absent from DNX and its causing folks to install packages and either a) get the wrong reference assembly or b) get a reference assembly and no implementation.

The first problem will result in type collisions at compile time on desktop based profiles since dnx will use the reference assembly instead of a facade.  The second problem results in file-not-found at runtime.

**Comment by anurse** [comment]
I think this is a dupe of #2356 but we may need to investigate this specific scenario further.

**Comment by ericstj** [comment]
Yeah, let it be a dupe.  For some reason github couldn't find that when searching for compat.

**Comment by anurse** [comment]
No problem :)
