### ISSUE TITLE
Enable preparing machines for servicing

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2526]
We would like make it possible to prepare a machine for servicing (e.g. create a script that the user would run before running an ASPNET vNext app that would create the right folder structure etc.). This might be even more important given that it is now possible to set an environment variable that will block running any ASPNET vNext app if servicing is not enabled. The scenario is mostly servers where the user runs an app that was published on a different box.

**Comment by muratg** [comment]
@glennc Move out of this milestone?

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#557
