### ISSUE TITLE
Preserving file path, file name, and extension in embedded resources

### ISSUE THREAD

**Issue by Agiclaw** [aspnet/dnx#2527]
We have a shared assembly that contains embedded JavaScript/image/etc resources in a well defined directory structure. These files are then served from an AspNET.vNext site using a custom EmbeddedResourceFileProvider that maintains directory structure. It was able to properly distinguish between directories and files because of the resource names containing both '/' and '.'.

With the changes made by; https://github.com/aspnet/dnx/commit/689062357804056669c6ceeb455532ff5356dd08 the directory, file name, and extension information is now ambiguous.

For example:
   a.b.js
Could be interpreted as:
  a/b/js
  a/b.js
  a.b.js

This issue was previously discussed in https://github.com/aspnet/dnx/issues/260 where @Alxandr indicated that switching to the '.' delimiter would cause problems.

+1 for URI formatted resource strings

**Comment by davidfowl** [comment]
We removed that logic for compatibility with existing msbuild projects. If you want this logic you'll have to author an `ICompileModule`, see an example here https://github.com/aspnet/Entropy/tree/dev/samples/Project.CompileModule
