### ISSUE TITLE
High memory usage of LibraryManager in Mvc.NoFun.sln

### ISSUE THREAD

**Issue by rynowak** [aspnet/dnx#2532]
This is after working in VS for a while. DTH is using 1.0gb of memory. The build I'm using includes recent fixes by @troydai.

![image](https://cloud.githubusercontent.com/assets/1430011/9397777/ef09bcc2-4754-11e5-92e2-6b8b32d3b9e6.png)

All of the usage in this dictionary is actually the strings. The `Library` class itself is only consuming 2mb.

**Comment by rynowak** [comment]
Here's part two:

![image](https://cloud.githubusercontent.com/assets/1430011/9397804/3bd9fed6-4755-11e5-8a52-7ff81601018b.png)

Lookup of library descriptions is using 636mb.. on these things:
![image](https://cloud.githubusercontent.com/assets/1430011/9397824/625db070-4755-11e5-99df-b043a9ffc14e.png)

**Comment by davidfowl** [comment]
Closing this
