### ISSUE TITLE
Add RuntimePath to IRuntimeEnvironment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2534]
Makes it easy to figure out where the current dnx is running from. Also nice for locating other things like dnu for the running dnx.

**Comment by moozzyk** [comment]
Shouldn't this basically be %DNX_DEFAULT_LIB%? The runtime folder might be different from the location of dnx.exe due to servicing. I wonder if this is not yet another aspect of #1970

**Comment by davidfowl** [comment]
It is! Do you want to lump this in with that work?

**Comment by moozzyk** [comment]
Yes. My comment was to link to this issue to the other one so that I won't forget about it...

**Comment by davidfowl** [comment]
@moozzyk We should do this now

**Comment by davidfowl** [comment]
@moozzyk Moved to RC1
