### ISSUE TITLE
Can't have files that are both resources as well as compiled

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#2536]
Seems like anything that is listed in the `resources` node gets excluded from `compile` (even if it's explicitly called out). Perhaps we can change the behavior so that anything that is listed as `compile` always gets included?

**Comment by davidfowl** [comment]
What's the scenario?

**Comment by pranavkm** [comment]
Unusual scenario in the Razor precompilation tests where I want have the source of the files as well as the compiled types.

**Comment by glennc** [comment]
How impact-full is it? Blocking the tests?

**Comment by pranavkm** [comment]
No, I worked around it by creating a new project which included the files via `../other-project/resources/*.cs`

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#556
