### ISSUE TITLE
Per framework file exclude

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#2540]
Right now exclude is for all frameworks. It would be useful to be able to exclude files for certain frameworks on build.

**Comment by glennc** [comment]
I like the idea, but don't think it fits into any of the milestones we have at the moment. So backlog for now.

**Comment by anurse** [comment]
As a workaround, and yes I know it's kinda gross, you can wrap the whole file in `#if`

**Comment by JamesNK** [comment]
That's what I'm doing. Not blocking.

**Comment by Mpdreamz** [comment]
Huge +1 to this, would reduce the number of needed ifdefs.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#554
