### ISSUE TITLE
[DTH] project.json net20 - dynamic bug

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#2545]
https://github.com/JamesNK/Newtonsoft.Json/blob/a9ea63da59cc90b474bee5a6f351e9fad55a44bf/Src/Newtonsoft.Json.Tests/Documentation/Samples/Linq/QueryJsonDynamic.cs

That file "compiles" in VS without error for a project with a .NET 2.0 framework but `dnu build` gives this error:

C:\Development\Source\Json\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\Documentation\Samples\Linq\QueryJsonDynamic.cs(67,32): .NETFramework,Version=v2.0 error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

VS should tell the user that dynamic is not allowed in .NET 2 and 3.5 with an error.

**Comment by anurse** [comment]
To be clear, both cases are a DNX project? One in VS and one building from the command line?

**Comment by JamesNK** [comment]
Yes

**Comment by anurse** [comment]
Comparing with a traditional CSProj, `dnu build` is exhibiting the correct behavior. I'll look in to why this error isn't occurring in DTH.

**Comment by anurse** [comment]
Moving to RC, this is a bug and shouldn't require design changes. /cc @muratg

**Comment by muratg** [comment]
:+1:

**Comment by troydai** [comment]
@anurse is this bug still valid under the context of `dotnet`?

**Comment by muratg** [comment]
@troydai nope :)

**Comment by JamesNK** [comment]
RIP
