### ISSUE TITLE
dnu restore fails with sub directories

### ISSUE THREAD

**Issue by sklose** [aspnet/dnx#2548]
I have the following folder structure in my Visual Studio project:

![image](https://cloud.githubusercontent.com/assets/546088/9429867/e1213b44-49ac-11e5-9d63-b068acb838b2.png)

which reflects the same folder structure on disk

![image](https://cloud.githubusercontent.com/assets/546088/9429877/22b919d2-49ad-11e5-90d5-72826283cd9a.png)

**ComponentB.Impl needs to reference ComponentA.Abstractions** (and ComponentB.Abstractions). In order to get that to work I added a global.json in the ComponentB folder with this content

```
{
  "projects": [ "../ComponentA" ]
}
```

Everything works fine from within Visual Studio, but on the command line I noticed dnu restore behaves differently depending on from what directory I run it. If I run "dnu restore" from the root it complains that it cannot resolve ComponentA.Abstractions. If I run "dnu restore" from within the ComponentB.Impl folder everything works fine.

I created a project here https://github.com/sklose/AspNetSakeKoreBuildError that reproduces the problem.

Question: is this a bug or is the way I structured my projects simply not supported? If it's not supported, what's the recommended approach in this case?

**Comment by davidfowl** [comment]
This is actually a bug in DNU, it should be using the `global.json` relevant per project but it isn't today. It resolves the root directory once and then fails to find your `global.json`

**Comment by sklose** [comment]
Is this on the road map to be fixed for v1? I am using Sake/KoreBuild as my build system, I think doing your workaround requires some signification changes in there to make it run dnu restore for each project instead of once on the root. I might just flatten my folder structure if this is a rather long term change for dnu.
