### ISSUE TITLE
dnu restore CoreCLR Mac fails with "Too many open files"

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2550]
By default 256 is the max open files allowed per process, doing ```ulimit -n 2500``` will up the limit and restore will work.

At the end of restore it displays ```Trace/BPT trap: 5``` but restore succeeds (exit code 133)

**Comment by glennc** [comment]
What are you suggesting we do about this? Setting ulimit requires root does it not?

**Comment by benjamin-hodgson** [comment]
Surely the fix is for `dnu` to not open so many files, rather than fiddle with environmental settings?

**Comment by BrennanConroy** [comment]
Oh, this is fixed by: 1f0e103a277c6774be5cdb1f665841e4c5e75fb0 and f3103122c058632007ce915a2edd0884130d427b

**Comment by benjamin-hodgson** [comment]
Oh, excellent :sweat_smile: I'll update to the dev version then. Thanks!
