### ISSUE TITLE
dnx doesn't properly handle duplicated dependencies in a single project.json

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2554]
Repro steps:

(1) Create a solution which has two projects:
`ProjectA/project.json`:

``` json
{
  "version": "1.0.0-*",
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "ProjectB": "1.0.0-*"
      }
    }
  }
}
```

`ProjectB/project.json`:

``` json
{
  "version": "1.0.0-*",
  "dependencies": {
    "EntityFramework": "6.1.3"
  },
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "EntityFramework": "6.1.3"
      }
    }
  }
}
```

(2) Run `dnu restore` in ProjectA root dir and see
![capture](https://cloud.githubusercontent.com/assets/1383883/9453230/b95fc41a-4a6d-11e5-8017-617f4122dd12.PNG)

/cc @davidfowl @glennc

**Comment by glennc** [comment]
@BillHiebert @sayedihashimi In addition to whatever we do in the runtime this feels like something that we could provide warnings for in tooling. Right?

**Comment by sayedihashimi** [comment]
@glennc why provide warnings in tooling for this? If dnu issues warnings for this they should flow through and be displayed in the error list.

One suggestion for @madskristensen is to have some experience while editing project.json to let users know about the issue.
