### ISSUE TITLE
After project.lock.json is deleted, dnu says it recreated it, but it does not exist in the project folder

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2556]
1. Create an empty ClassLibrary
2. In SolutionExplorer delete project.lock.json
3. Restore is triggered and dnu output said that project.lock.json was generated, BUT it does not exist on disk.

(you might delete project.lock.json several times, since it works sometimes)

![image](https://cloud.githubusercontent.com/assets/1592091/9472827/893d6fb8-4b25-11e5-8ff4-7af883f7ff36.png)

**Comment by ChengTian** [comment]
Cannot reproduce with beta 6 Tooling.

BTW, in my VS, it is only the first time you delete project.lock.json, the automatic restore is triggered. Following deletion doesn't trigger restore any more.

Tooling version:
![capture](https://cloud.githubusercontent.com/assets/1383883/9476074/97661e60-4b1f-11e5-9f70-b6c8db223393.PNG)

@abpiskunov , did you clear Package Manager output before you delete lock file? Maybe you just saw some leftover output from previous restore？

**Comment by abpiskunov** [comment]
Hm yes , I did not clear the output.
