### ISSUE TITLE
Skip strong name signing on Mono until Roslyn supports it

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/dnx#2558]
Building projects that specify a `keyFile` in project.json (like [serilog](https://github.com/serilog/serilog/blob/b53cc797bc4a96a49912987b69a49762e12edb92/src/Serilog/project.json#L11)) doesn't work on Mono currently since the following error is generated:

```
error CS7027: Error signing output with public key from file '../../assets/Serilog.snk' -- Assembly signing not supported.
```

Since signing isn't supported by Roslyn on non-Windows platforms yet, signing should just be skipped and a warning printed instead.

**Comment by moozzyk** [comment]
On Mono you should be able to sign with [OSS Sigining] (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/oss-signing.md) by using `"strongName" : true` instead of `"keyFile" : ...".

**Comment by akoeplinger** [comment]
@moozzyk that doesn't help me for projects which I don't control :smile:

**Comment by akoeplinger** [comment]
To be clear, I can just remove the `keyFile` from project.json and it builds fine, but that is annoying and means a subpar out of the box experience when working with community projects on Mono.

**Comment by moozzyk** [comment]
@akoeplinger - I wonder why not commit a change to the project and change the signing to OSS? If the snk is distributed with the project then I think there is not much difference between this and  OSS signing. If snk is not distributed with the project you would not be able to compile anyways.

**Comment by davidfowl** [comment]
@moozzyk the only valid reason would be because of it being a breaking change.

**Comment by moozzyk** [comment]
@davidfowl Yeah, you're right. How about falling back to OSS signing + warning if the platform does not support snk?

**Comment by akoeplinger** [comment]
That sounds OK to me as well.

**Comment by glennc** [comment]
@moozzyk Would you be likely to fit this into beta8 or should we assign it to the next milestone?

**Comment by borgdylan** [comment]
Will this be done specifically for roslyn? Compilers based on IKVM.Reflection should not have issues signing with an SNK on mono. So the decision of not supporting SNK on mono should be the compiler's decision.

**Comment by davidfowl** [comment]
This issue is about the roslyn compiler.

**Comment by Illeris** [comment]
Same issue on Windows, providing a ".snk" file in WithCryptoKeyFile:
CSharpCompilationOptions compilationOptions = new CSharpCompilationOptions(Microsoft.CodeAnalysis.OutputKind.DynamicallyLinkedLibrary).WithCryptoKeyFile(String.IsNullOrEmpty(ca.AssemblySigningFile) ? null : ca.AssemblySigningFile);

**Comment by davidfowl** [comment]
@Illeris what?
