### ISSUE TITLE
We never dispose HttpClient in restore

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2560]
HttpClient implements IDisposable and can hold FileHandles which caused an issue on Mac OSX. We should dispose it properly.

**Comment by glennc** [comment]
How bad are the issues?

**Comment by Tratcher** [comment]
Bad enough to make restore fail on Mac. However this is primarily because we create far too many instances. We create 2 per feed, per project, resulting in 100+ instances on MVC. The actual solution is to create fewer instances, disposal is a secondary concern.

**Comment by glennc** [comment]
@muratg we should put this in a milestone.

**Comment by muratg** [comment]
@BrennanConroy Is this still needed after your change?

**Comment by BrennanConroy** [comment]
Like Chris said, we should do this but it's not as bad after my change

Sent from my HTC

----- Reply message -----
