### ISSUE TITLE
publish on Unix with windows runtime tries to chmod dnx.exe

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2563]
Still succeeds, just some minor polish

**Comment by glennc** [comment]
If we can I would like to know how we would improve this in beta8.

**Comment by anurse** [comment]
AFAIK, it's not trying to chmod `dnx.exe`, it's trying to chmod `dnx`, which doesn't exist in Windows runtimes. We can probably just fix this with a simple `File.Exists` check

**Comment by glennc** [comment]
This will probably not be needed once we have a tar dnx. Moving to backlog for now, should be able to close it once we are not running chmod anymore.
