### ISSUE TITLE
Rename Microsoft.Dnx.Runtime.ProjectResolver

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#2564]
The only method in `Microsoft.Dnx.Runtime.ProjectResolver` is `ResolveRootDirectory`:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/ProjectResolver.cs

Obviously, the interfaces a project resolver should have were moved to `Microsoft.Dnx.Tooling.ProjectResolver`:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/ProjectResolver.cs

Also, the type conflict is annoying when you using both `Microsoft.Dnx.Runtime` and `Microsoft.Dnx.Tooling`

**Comment by JunTaoLuo** [comment]
This is fixed by @davidfowl in 9b710db84a917260eac368f7f5c272e4d26e984f
