### ISSUE TITLE
Consider moving --debug up the stack

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2565]
Currently we check for the --debug flag as soon as dnx starts. If the flag is specified dnx waits for the debugger to be attached and as soon as it happens it continues execution. 
However there is a limitation on CoreClr where there won't be any debugger events if CoreClr code type is selected until CoreClr is loaded. This results in dnx never waking up despite attaching the debugger to the process if CoreClr code type is selected. The process will wake up when only native code is selected but then it is not possible to debug managed code at all. 

Additional considerations:
- if we move --debug up the stack we may need to add an internal flag that could be used for debugging native code (i.e. bootstrapping) 
- currently --debug flag does not work on non-windows at all  (https://github.com/aspnet/dnx/blob/dev/src/dnx/pal.linux.cpp#L29) but we bootstrap CoreClr differently for non-windows so we need to make sure it works too

**Comment by anuchandy** [comment]
+1

**Comment by moozzyk** [comment]
@Eilon @muratg: Managers dream come true : moozzyk added this to the 1.0.0-beta8 milestone just now

**Comment by muratg** [comment]
@moozzyk :musical_note:

**Comment by moozzyk** [comment]
:clap:

**Comment by Eilon** [comment]
:smile:

**Comment by davidfowl** [comment]
@moozzyk but it isn't marked as done
