### ISSUE TITLE
Support 'dnu publish' skipping copy of nuget package references

### ISSUE THREAD

**Issue by marcind** [aspnet/dnx#2567]
Please have a read and let me know if this makes sense (point out any corner cases I'm not aware of). I'd be totally happy to contribute my time to make this happen.
### Goal (TL-DR)

Enable application publishing workflow that minimizes the deployment unit size by omitting downloading nuget package references into the `packages` folder during a `dnu publish` on the build machine and instead shifting the responsibility to a `dnu restore` performed on the deployment target machine.
### Justification

The current publish workflow works great for deploying an app to a bare target (since everything is included in one x-copyable folder). However, for scenarios where you are redeploying an updated app or deploying multiple apps to a single container having each app include its full list of dependencies will result in redundant copies, specially when the target machine might already have most of the dependencies in its package cache. By omitting nuget package references we could get smaller deployment sizes, thus improving deployment speed and network impact.
### The proposal

Add a new flag (e.g. `--no-package-references`) to `dnu publish` which will cause the publish process to not emit references of type `LibraryTypes.Package` into the publish output dir.

The assumption is that the package references are in a repository that will be accessible to the deployment target machine. Other types of references (notably `LibraryTypes.Project`) should be emitted since there's no guarantee they will be made available via nuget.

Once the publish output gets copied over to a production machine, the deployment process will have to invoke dnu restore to get the app into a runnable state.
### Current alternatives (and what's bad about them)
- Use existing `dnu publish` behavior and copy all the files during deployment.
  - This can result in repeated copies of the same content, slowing down deployment and increasing network traffic
- Use `dnu pack`
  - Output doesn't include the contents of wwwroot
  - Output doesn't include any local libraries that my app depends on, have to track those down seperately
- Deploy application sources and run the app directly out of them
  - Either have to deploy my entire source base or figure out stuff that shouldn't be deployed (e.g. test projects)
  - Circumvents `project.json` options such as excludes etc.
  - If my solution uses 'legacy' projects (e.g. csproj-based class libraries) I now need to make sure my deployment target machines include all the appropriate tooling to build my solution before I can use `dnu`
- Use existing `dnu publish` and try to prune the packages folder manually before deployment
  - Hard to determine which packages are available somewhere via nuget and which ones came from local library references
### Things to test for (Acceptance criteria)
- When setting flag, output includes everything it does today except for packages that come from nuget references
- New flag works with or without `--no-source` flag
- Resultant output can be easily `dnu restore-d` (initial testing indicates pointing restore at the approot folder works just fine)
- Package references get validated just as they do today, they're just not copied to output
- Project lock file gets emitted just as it does today

**Comment by anurse** [comment]
I think this sounds like a reasonable idea. I wonder if the `dnu pack` alternative will be more usable after https://github.com/aspnet/dnx/issues/848 is finished, and you can embed the `wwwroot` content in the package when you `dnu pack`

**Comment by marcind** [comment]
The `dnu pack` changes make sense but I think my proposal still has value because it gives me the ability to have a single command build process that gathers all the essential files I need to deploy an application into a single location. `dnu pack` only packages up the project itself, whereas `dnu publish` also packages up all the local libraries I might have referenced.

I'll give a shot figuring out the scope of the required code changes. But it looks like @davidfowl has been making some significant refactorings in that area lately so I just want to make sure I don't conflict with whatever you guys might be planning.
