### ISSUE TITLE
Leaked nuget packages in %userprofile%\AppData\Local\Temp\nuget 

### ISSUE THREAD

**Issue by KKhurin** [aspnet/dnx#257]
I have an IIS hosting MVC music store set up to periodically recycle.
We have 2 issues here:
1. Unbound growth of C:\Users\Administrator\AppData\Local\Temp\nuget 
2. nobody deletes the old packages
3. We don't seem to reuse already loaded packages - instead we load new ones every so often. It does not seem to load all the packages all the time. 
For example when w3wp recycled about once every minute a new Remotion.Linq.dll got loaded at: 9:33AM, 9:29AM, 8:34AM, 7:20AM, <~2500 copies more....> - all of them are identical copies.

**Comment by christianarg** [comment]
This exactly is happening with the Nuget Server, even with the latest version. Any chance it can be fixed over there? (worth trying)

**Comment by davidfowl** [comment]
File the bug on codeplex

**Comment by christianarg** [comment]
I did, but I found that someone already did it about 2 months ago (https://nuget.codeplex.com/workitem/4426) and didn't even get a reply. I was posting this just in case you were sitting next to some Nuget developer :P Thanks anyway
