### ISSUE TITLE
Regression: When on Linux and publishing for the x64 Windows CLR, wwwroot is omitted

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#2571]
I tried to publish a project for the x64 Windows Desktop CLR (targeting Helios) while on Linux. In the past the wwwroot directory was included in the output. This is no longer the case.

**Comment by borgdylan** [comment]
When I tried in another project with a later DNX, the wwwroot directory was copied over. I am not sure if the dependencies are affecting this. The affected project happens to use Hangfire where two separate versions are being pulled by the actual dependencies in project.json.

**Comment by davidfowl** [comment]
As usual please provide a repro project.

**Comment by borgdylan** [comment]
No need, when trying to cross publish for ```dnx-clr-win-x64.1.0.0-beta8-15530``` (the latest), the issues disappears. It might have been temporary regression due to code churn.

**Comment by borgdylan** [comment]
The issue is manifesting itself again. Also why is dnu trying to chmod a dnx meant for Windows? That makes the publish fail.
