### ISSUE TITLE
dnx . test (xunit.runner.dnx) no longer outputs the failure errors

### ISSUE THREAD

**Issue by lukemurray** [aspnet/dnx#2572]
When I run my tests in a console (Mac OS X) I used to get the failure errors, now I get just the summary that a test failed but I have no information on why.

I have not updated xunit, but I did update dnvm and am running the latest Mac OS X 10.11 public beta.

Thanks

**Comment by bradwilson** [comment]
This is the wrong place to open issues for the xUnit.net DNX runner. Please use https://github.com/xunit/xunit instead.

We've identified several issues with xUnit.net 2.1 Beta 4 and DNX (especially on Mono). Our recommendations:

- Using DNX beta 6 or earlier? Use `xunit` and `xunit.runner.dnx` 2.1 Beta 3 (on NuGet)
- Using DNX beta 7 or later? Use `xunit` 2.1 RC 1 and `xunit.runner.dnx` 2.1 Beta 5 (on [MyGet](https://www.myget.org/F/xunit/))

**Comment by lukemurray** [comment]
Hmm having not changed xunit I though it might be something dnx broke, but I'll see if using those versions fix it and post of xunit if not. Thanks.
