### ISSUE TITLE
Running dnx from a service

### ISSUE THREAD

**Issue by ArnaudFaucher** [aspnet/dnx#2573]
Hi,

Is launching dnx from a service process (Windows/Linux service, OS X daemon or agent) a supported scenario?

Best regards and thanks for all your fantastic work!

**Comment by anurse** [comment]
I've definitely heard of people doing this with Linux daemons, and it should be straightforward to do it for OS X daemons as well. DNX itself isn't designed to run as a Windows Service, but there are various tools to allow you to run an arbitrary executable as a Windows Service. You can also write a small shim Windows Service that launches DNX.

**Comment by anurse** [comment]
@DamianEdwards just pointed me to http://taskmatics.com/blog/host-asp-net-in-a-windows-service/ which should work :)
