### ISSUE TITLE
Xplat coreclr DNU/DNX fail without any error/output (or sometimes just Trace/BPT trap: 5)

### ISSUE THREAD

**Issue by salerth** [aspnet/dnx#2580]
Version:  *    1.0.0-beta8-15530    coreclr x64  darwin          default

Running dnu restore, or dnx kestrel (or any dnx/dnu command including just --help) returns immediately without any messages... occasionally it will spit out `Trace/BPT trap: 5` if you try enough times.

I tried the ulimit setting but that had no impact... switching back to mono works fine.

**Comment by BrennanConroy** [comment]
15530 was a bad build, sorry about that. You can either go down to 15517 or wait for a newer version that works to come out.

**Comment by Netshroud** [comment]
I can't find `1.0.0-beta7-15517` or `1.0.0-beta8-15517`. How can I go down to 15517?

**Comment by salerth** [comment]
I set my DNX_UNSTABLE_FEED var to `https://www.myget.org/F/aspnetlitedev/`, downloaded `1.0.0-beta8-15542` and these utils now work.
