### ISSUE TITLE
Dnu publish --runtime does not account for OS when generating command files

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#2582]
dnu publish generates a cmd and a bash file with windows and bash commands for running the project. When publishing with the --runtime option these commands include the path to the published runtime.  However, this process does not account for the fact that the published runtime is os specific.  E.g. If I publish the osx runtime then I get a web.cmd that includes a path to the osx runtime.

Recommendation A) Don't generate a windows cmd when publishing an osx runtime, or a bash script when publishing a windows runtime.

Recommendation B) You can publish multiple runtimes, and right now it just uses the first one to generate both of the command files. Instead it could use the first one from the appropriate OS when generating the command file for that OS.

**Comment by anurse** [comment]
I agree, but there's a bigger issue there. If you publish both a darwin and a linux runtime, we need to generate a bash script that does OS detection to pick the right runtime.

In general, I think we need to do some design evaluation of our publishing story. We also have issues with file permission flags (execute bits on Linux/Mac, etc.).

/cc @BrennanConroy @davidfowl @glennc
