### ISSUE TITLE
DTH goes silent when K project in the solution root has a syntax error in the project.json

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2584]
Open \\vwdbuild01\Temp\antonpis\repro\ErrorInRootProjectBlockDTH.zip  solution and notice no restore happens (no DependenciesChanged or Diagnostics coming from DTH).

This solution has one normal K project in src and one K project in solution root. Project in the solution root has a syntax error in project.json extra }). This makes DTH to be silent for all projects in the solution.

**Comment by BillHiebert** [comment]
This is actually a tooling bug which has been fixed.
