### ISSUE TITLE
DNX . kestrel killed unexpectly

### ISSUE THREAD

**Issue by JerryBian** [aspnet/dnx#2588]
I ran `DNX . Kestrel` command under Ubuntu to make site running. After it starts, it would print 'Started'. However several minutes later, the site would turns to shutdown, and Console would print 'Killed'.
It always happened like this. I guess maybe some code in the website caused the DNX down. But any way I can quickly find out the root cause, any logging or something.
BTW, the version is beta6, and I run the command in separate Screen host, which would keep running after  SSH  session disconnected.

**Comment by davidfowl** [comment]
Please file this issue on kestrel

**Comment by JerryBian** [comment]
@davidfowl alright, I have created issue in [kestrel page](https://github.com/aspnet/KestrelHttpServer/issues/179).

**Comment by davidfowl** [comment]
Also when filing bugs specify the versions of the software you are using. Which dnx which kestrel versions
