### ISSUE TITLE
dnu restore does not follow redirect

### ISSUE THREAD

**Issue by chriseldredge** [aspnet/dnx#2589]
When a NuGet V2 Feed redirects `dnu restore`, it does not seem to issue operations against the redirected URI, instead preferring to use the old wrong location.

A command like `dnu restore -s http://example.com/` may issue a response such as:

```
HTTP/1.1 307 Temporary Redirect
Content-Length: 0
Location: http://example.com/api/odata
```

But then `dnu restore` blindly issues `FindPackagesById` queries like `http://example.com/FindPackagesById()` when it should issue them to `http://example.com/api/odata/FindPackagesById()`.

The `NuGet.exe` command line client works correctly and follows the redirect. `dnu restore` should too.

**Comment by davidfowl** [comment]
Afaik it does. What version of he tools are you using?

**Comment by chriseldredge** [comment]
```
dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-beta6-12256
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
```

The client follows the redirect but does not base `FindPackagesById()` queries against the new URI. It seems to follow it for a short code path but then reverts to the entry URI instead of remembering the redirected URI.

**Comment by chriseldredge** [comment]
Steps to reproduce:

1. Download and unzip `Klondike.zip` from https://ci.appveyor.com/project/chriseldredge/klondike/build/119/artifacts
1. Run `.\dist\Klondike.SelfHost.exe --interactive`

**Comment by NickCraver** [comment]
The response code here in the example is a 307, so `dnu restore` is behaving correctly. Unlike a 302, a 307 **shouldn't** automatically be followed without user content. [The relevant W3C section is here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.8):

> If the 307 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

That being said, if this happens with a 302, it would indeed be a bug.

**Comment by chriseldredge** [comment]
I just tested 301 and 302 redirect status codes and the same bug exists for both of those too.

However, my reading of the cited W3C section leads me to believe that it should only apply to "a request other than GET or HEAD" and since `dnu restore` is issuing GET requests, that the section does not apply. Furthermore, the NuGet.exe command line client follows a 307 redirect, so for best compatibility I think it makes sense for `dnu restore` to follow 301, 302 and 307 redirects in the same way.

**Comment by NickCraver** [comment]
Ah I see your issue now, it's not that it doesn't follow the redirect (the `HttpClient` does this just fine). It's that it doesn't have the special `nuget.exe` behaviour of *updating the base URL* on redirect. 

@davidfowl  the functionality he's talking about [is here in NuGet](https://github.com/NuGet/NuGet2/blob/861741bd780225a542c73a1d0904dd33b33a7a3d/src/Core/Server/PackageServer.cs#L295). I agree this should happen - though ideally without the extra HTTP hit that the current NuGet approach takes just to ultimately read a `Location` header when it comes down to it.

**Comment by davidfowl** [comment]
Yep
