### ISSUE TITLE
Remove the fallback to GAC behavior

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2591]
See https://github.com/Microsoft/msbuild/issues/173.

We'll need a better error message when we can't locate reference assemblies for said target framework. It could be a set of diagnostics.

**Comment by anurse** [comment]
This would also solve #2539

**Comment by davidfowl** [comment]
@anurse we need to figure out how to handle GAC references in general if we remove the fallback. Do we special case System* assemblies? Or ones that we know are in the redist list? What if you just want to reference something in the GAC explicitly (if you're a bad person)
