### ISSUE TITLE
DNX on OSX/Linux loads the wrong System.Runtime.InteropServices.RuntimeInformation package

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2594]
`System.Runtime.InteropServices.RuntimeInformation.IsPlatform(OSPlatform.Windows)` always returns true, even on OSX and Linux.

**Repro**
Run this on different platforms. It will always print "Windows".
```json
{
	"dependencies": {},
	"frameworks": {
		"dnxcore50":{
			"dependencies": {
				"System.Console":"4.0.0-*",
				"System.Runtime.InteropServices.RuntimeInformation": "4.0.0-*"
			}
		}
	}
}
```

```c#
using System;
using System.Runtime.InteropServices;

namespace Test
{
	public class Program
	{
		public void Main(string[] args)
		{
			if(RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
			{
				Console.WriteLine("Windows");
			}
			if(RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
			{
				Console.WriteLine("Darwin");
			}
			if(RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
			{
				Console.WriteLine("Linux");
			}
		}
	}
}
```

**Versions**
```
1.0.0-beta8-15545    coreclr x64  darwin       
and
1.0.0-beta8-15545    coreclr x64  linux      

System.Runtime.InteropServices.RuntimeInformation 4.0.0-beta-23231

Pulling from https://www.myget.org/F/aspnetlitedev/api/v2
```

This is related to #2387. Our myget feed publishes a package of System.Runtime.InteropServices.RuntimeInformation that includes the Windows version of the dll. This gets loaded at runtime, and thus misinforms the `IsPlatform` API about which OS is actually running.

**Comment by muratg** [comment]
@anurse @moozzyk @BrennanConroy 

Any ideas on this one guys?

**Comment by moozzyk** [comment]
We don't own `System.Runtime.InteropServices.RuntimeInformation` don't we? It's probably on CoreClr. We have `IRuntimeEnvironment`.

**Comment by BrennanConroy** [comment]
Ya, this is because the dll in the nupkg was windows specific.

**Comment by BrennanConroy** [comment]
Later versions of this package have a runtime.json with osx and Linux targets defined

**Comment by muratg** [comment]
@BrennanConroy So is this fixed now?

**Comment by BrennanConroy** [comment]
It might be once Coherence passes.

**Comment by muratg** [comment]
@BrennanConroy Please test this once we have Coherence.

**Comment by anurse** [comment]
This will still be broken after Coherence, it looks like the `runtime.json` for it refers to `osx` (version-less) but we fallback directly from `osx.10.10` to `unix`. Instead we should fall through `osx`. @BrennanConroy or I can fix that fairly easily.

**Comment by anurse** [comment]
The same should probably be done for `ubuntu.14.04` -> `ubuntu`

**Comment by BrennanConroy** [comment]
Should also update the NetCore.Platforms list too

**Comment by anurse** [comment]
I'll take this and also ping the necessary folks about updating that package.
