### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by Ph47** [aspnet/dnx#2600]
Case sensitivity is present on dnx beta6 on windows 8.

Actual project path: "c:\Data\CRM\Web\"

When "cd c:\data\crm\web\", "dnx . web":
"System.InvalidOperationException: Unable to resolve project 'web' from C:\data\crm\web"

When "cd c:\Data\CRM\Web\", "dnx . web":
"Started"

Windows is not case sensitivity in file paths.

**Comment by pranavkm** [comment]
Related: https://github.com/aspnet/dnx/issues/2260

**Comment by glennc** [comment]
This is known, and will be resolved when we fix the linked issues. Until then it is going to be case sensitive :).
