### ISSUE TITLE
DNU is able to restore packages to custom folder

### ISSUE THREAD

**Issue by xandraele** [aspnet/dnx#2601]
It would be nice if we have an option where nuget packages should restore to.
The old nuget engine restores to "packages" folder near the solution file. Will be great if new engine is able to restore to this folder as well instead of appdata.

Anyway, thank you for hard work.

**Comment by davidfowl** [comment]
It won't restore to both places, however you can change `global.json` to point to a location to restore packages to:

```JSON
{
   "packages": "packages"
}
```

The path specified is relative to the `global.json`, so you can have packages appear at the solution root instead of the user profile if you wish.
