### ISSUE TITLE
Remove the dependency resolution output spew from dnu build by default

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#2612]
When you do a `dnu build` you mostly see a seemingly endless spew of dependency resolution logic. Really all you want to see is what the compilation errors were and whether the build succeeded or not. Suggest putting the dependency resolution spew behind an option.

**Comment by MJomaa** [comment]
Like making `dnu build --quiet` standard?

**Comment by davidfowl** [comment]
Yes, I've heard enough complaints about this now :smile:
