### ISSUE TITLE
Project model from DesignTimeHost

### ISSUE THREAD

**Issue by xtmq** [aspnet/dnx#2624]
Hi all

I'm trying to get a project model from a DesignTimeHost, but it returns only source files. How I can get others (e.g. resource files)? The project in the host knows about them. Maybe I can use plugins...

**Comment by davidfowl** [comment]
It's not exposed in DTH right now.

**Comment by xtmq** [comment]
Can I write plugin to get active projects and extract resource files from them?
Or do you have plans to expose this?

**Comment by xtmq** [comment]
Any updates here? Can I write plugin for that?
