### ISSUE TITLE
Output of dnu restore shows the wrong URI under "feeds used" when using the nuget v3 feed

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#2626]
The output of `dnu restore` shows the CDN URI of the v3 under "feeds used" feed instead of the URI listed in NuGet.Config.

**Comment by glennc** [comment]
Is this not the correct behavior? It is showing you the url that it downloaded from. Is it confusing because you expected to see nuget.org and didn't?

**Comment by danroth27** [comment]
Feeds used should list the URIs that I configured in NuGet.Config.
