### ISSUE TITLE
Rebuild dnu publish off the lock file

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2628]
Right now we do a lot of rewalking in dnu publish. @lodejard, @davidfowl and I discussed this and decided we should change the logic a bit, but want to do so after the changes I and @victorhurdugaci are doing. This bug is to track those changes.

* [ ] Add a static API to AppHostContext that takes a project (and other related data) and creates one AHC for every TFM/RID combo in the lock file
* [ ] Change Publish to use that API to get a set of all the targets to publish for
* [ ] Change `--framework` and `--runtime` to filter this list of AHCs. This means that if you want to publish from windows to linux, you MUST have restored for linux (or the lock file won't have it).
* [ ] Revisit embedding multiple runtimes. Should that work? How?

**Comment by anurse** [comment]
This should probably be done in beta8 and I think I can take it on (after some rebalancing of other issues), but I didn't want it to block #2387

**Comment by anurse** [comment]
This should be scheduled for rc1

/cc @muratg @davidfowl @moozzyk

**Comment by anurse** [comment]
I think @JunTaoLuo is taking this actually. @davidfowl assigned a different version of the same bug to him :).

**Comment by JunTaoLuo** [comment]
@anurse yup.

**Comment by JunTaoLuo** [comment]
This feature will no longer be implemented
