### ISSUE TITLE
ICompileModule seems to do... nothing

### ISSUE THREAD

**Issue by tuespetre** [aspnet/dnx#2636]
Using beta 7, with the following class file in the `./compiler/preprocess` folder:

```
using Microsoft.AspNet.Mvc;
using System;

namespace Checkout.AspNet5
{
    public class RazorPreCompilation : RazorPreCompileModule
    {
        public RazorPreCompilation(IServiceProvider provider) : base(provider)
        {
        }
    }
}
```

This was modelled after [this class file from beta 7](https://github.com/aspnet/Mvc/blob/6.0.0-beta7/test/WebSites/PrecompilationWebSite/compiler/preprocess/RazorPreCompilation.cs), with the only change being the project's namespace. I have also tried re-casing the folders (`./Compiler/Preprocess`, `/Compiler/PreProcess`, etc.) just in case.

I can't seem to get any indication that anything is happening with this, whether I build from command line or Visual Studio 2015.

`dnx` and `dnu` are both at version `CLR-x86-1.0.0-beta7-15532`.

**Comment by Antaris** [comment]
I'm also finding this issue, both times I last performed an updated, my compile modules seems to have stopped. Can't remember how I resolved it the first time either.

Through testing, I generally place a `Debugger.Launch()` in my `BeforeCompileContext` method, and this usually causes the Debugger Selector to launch on build, but this not even being fired :-/

**Comment by davidfowl** [comment]
Can you try this sample https://github.com/aspnet/Entropy/tree/dev/samples/Project.CompileModule

**Comment by Antaris** [comment]
@davidfowl The Entropy sample works fine, so it's likely just a references issue. In my instance, I am targeting only `dnx46` and am using the `"Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-beta7"` package in my samples console app. My sample references another project in the same solution that contains the abstract compile module (akin to how the `RazorPreCompileModule` is packaged).

I had just discovered a package change that I needed, from:

    "dependencies": {
      "Microsoft.Framework.Runtime.Roslyn": "1.0.0-beta6"
    }

to

    "dependencies": {
      "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-beta7"
    }

But now the compilation fails (progress :-)). Here is my example compile module:

    namespace SampleConsole.compiler.preprocess
    {
        using Microsoft.Dnx.Compilation.CSharp;

        public class DiscoverModulesCompileModule : Fx.ModulesCompileModule
        {
            public override void BeforeCompile(BeforeCompileContext context)
            {
                System.Diagnostics.Debugger.Launch();

                base.BeforeCompile(context);
            }
        }
    }

And gives the following set of compile errors:

    Severity	Code	Description	Project	File	Line	Source
    Error	CS0246	The type or namespace name 'Fx' could not be found (are you missing a using directive or an assembly reference?)	SampleConsole	C:\vnext\projects\Framework\samples\SampleConsole\compiler\preprocess\DiscoverModulesCompileModule.cs	5	Build
    Severity	Code	Description	Project	File	Line	Source
    Error	CS0234	The type or namespace name 'Dnx' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	SampleConsole	C:\vnext\projects\Framework\samples\SampleConsole\compiler\preprocess\DiscoverModulesCompileModule.cs	3	Build
    Severity	Code	Description	Project	File	Line	Source
    Error	CS0246	The type or namespace name 'BeforeCompileContext' could not be found (are you missing a using directive or an assembly reference?)	SampleConsole	C:\vnext\projects\Framework\samples\SampleConsole\compiler\preprocess\DiscoverModulesCompileModule.cs	7	Build
    Severity	Code	Description	Project	File	Line	Source
    Error	CS0115	'DiscoverModulesCompileModule.BeforeCompile(BeforeCompileContext)': no suitable method found to override	SampleConsole	C:\vnext\projects\Framework\samples\SampleConsole\compiler\preprocess\DiscoverModulesCompileModule.cs	7	Build

Which suggests the compiler is picking up the required references?

The reference project (that contains the actual implementation) in the same solution does compile fine.

Happy to share my repo with you if have any time to look into it.

**Comment by davidfowl** [comment]
What does your `project.json` look like? Where is the package/project that has `Fx.ModulesCompileModule` defined?

**Comment by tuespetre** [comment]
All of my refs are beta7. Your comment makes me wonder if there's something about the version of the Roslyn compiler itself? Is that going off of the runtime version of DNX or is it separate? 

Also I am targeting 'dnx451'.

- Derek Gray

**Comment by tuespetre** [comment]
I checked out `Entropy` and built/ran that project. It seems to work (`Hello from generated code`.) After seeing that I tried some more things in my project -- overriding `BeforeCompile` to throw an exception in my class that derives from `RazorPreCompileModule` -- and the exception is thrown on build. Seems this must be an issue with `RazorPreCompileModule` in beta 7 then, as it seems to have no effect.

**Comment by Antaris** [comment]
@davidfowl My project structure is as follows:

    /samples/SampleConsole/project.json
    /samples/...other samples
    /src/Fx.Core.Contracts/project.json
    /src/...other modules
    /text/,,,other tests
    /global.json

My sample `project.json` is:

    {
        "authors": [ "" ],
        "commands": {
            "SampleConsole": "SampleConsole"
        },
        "dependencies": {
            "EntityFramework.InMemory": "7.0.0-beta7",
            "Microsoft.Dnx.Compilation.CSharp": "1.0.0-beta7",
            "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-beta7",
            "Microsoft.Framework.Configuration": "1.0.0-beta7",
            "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
            "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-beta7",
            "Fx.Common": "",
            "Fx.Core.Contracts": "",
            "Fx.Core": "",
            "Fx.Data.Contracts": "",
            "Fx.Data": "",
            "Fx.Hosting":  "",
            "Fx.Logging.Contracts": "",
            "Fx.Logging": "",
            "Fx.Security.Contracts": "",
            "Fx.Security": "",
            "Fx.Web.Contracts": ""
        },
        "description": "",
        "frameworks": {
            "dnx46": {
                "frameworkAssemblies": {
                    "System.Runtime": "",
                    "System.Threading.Tasks": "",
                    "System.Text.Encoding": ""
                }
            }
        },
        "licenseUrl": "",
        "projectUrl": "",
        "tags": [ "" ],
        "version": "1.0.0-*"
    }

And my `Fx.Core.Contracts` module `project.json` is:

    {
        "authors": [ "Fresh Egg" ],
        "dependencies": {
          "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-beta7",
          "Microsoft.Framework.DependencyInjection.Abstractions": "1.0.0-beta7",
          "Fx.Common": ""
        },
        "description": "Provides core interfaces, abstractions and types consumed by the Framework",
        "frameworks": {
            "dnx46": {
                "frameworkAssemblies": {
                    "System.Runtime": "",
                    "System.Threading.Tasks": "",
                    "System.Text.Encoding": ""
                }
            }
        },
        "licenseUrl": "",
        "projectUrl": "",
        "tags": [ "core" ],
        "version": "1.0.0-*"
    }

My `global.json` is:

    {
      "projects": [ "src", "samples", "test" ],
      "sdk": {
        "version":  "1.0.0-beta7"
      }
    }

My active DNX is `1.0.0-beta7-clr` and I have no defaults overridden in either the Project properties.

@tuespetre One thing to check, in pre 1.0.0-beta7, I was using references to `Microsoft.Framework.Runtime.Roslyn`, but this is now been moved/renamed as `Micorosft.Dnx.Compilation.CSharp.Abstractions` for the `ICompileModule`, I guess that would be important, as the newer DNX version won't be using the older package, but your code will still compile against that older package - hence no `ICompileModule` execution, as technically, you're now using a different interface contract.

**Comment by davidfowl** [comment]
So Fx.Common has the Fx.ModulesCompileModule?

**Comment by Antaris** [comment]
@davidfowl No, `Fx.Core.Contracts` has the `Fx.ModulesCompileModule` code in.

**Comment by davidfowl** [comment]
Is that project/package referenced from the project that is using the ICompileModule?

**Comment by Antaris** [comment]
@davidfowl Sure is, `Fx.ModulesCompileModule` belongs to `Fx.Core.Contracts`, and is `abstract`. The `SampleConsole.compiler.preprocess.DiscoverModulesCompileModule` which inherits from `Fx.ModulesCompileModule`.

I am happy to push my code to GitHub if that makes it easier to describe?

**Comment by davidfowl** [comment]
That would be better :smile:

**Comment by davidfowl** [comment]
Or you could make a small sample that doesn't have that many dependencies.

**Comment by Antaris** [comment]
@davidfowl  I'll try and make a reduced example :-)

**Comment by Antaris** [comment]
@davidfowl  Minimal repo is [here](https://github.com/Antaris/Framework-CompileModuleIssue), I've stripped out a lot of my core framework code. Cheers for looking into this by the way, much appreciated!

**Comment by davidfowl** [comment]
Seems to work. I ran `dnu build` and got a Debugger.Launch() screen:

![image](https://cloud.githubusercontent.com/assets/95136/9732078/d49d49b4-55d5-11e5-889a-ce97ca5b3b30.png)

**Comment by davidfowl** [comment]
After that I see:

C:\dev\git\demos\Framework-CompileModuleIssue\samples\SampleConsole\project.json(15,20): error: The dependency Fx.Core

**Comment by Antaris** [comment]
@davidfowl Yeah, I accidentally left that in the `project.json`, I've since removed it from the example. Interestingly, when I run `dnu build`, it appears to work for me also, but when I build from  VS, it doesn't.

**Comment by davidfowl** [comment]
Can confirm that it is broken in VS.

**Comment by Antaris** [comment]
@davidfowl Cheers for looking at it, glad it's not related to my machine config. Hopefully not anything major, will keep an eye on this thread. I owe you a beer.

**Comment by davidfowl** [comment]
Ok I know how to fix it. Add dnx451 to your projects as well as dnx46

**Comment by davidfowl** [comment]
The problem is that VS is running your project as dnx451 and can't find the dependencies because they are described in terms of dnx46 only. This is one of the trickier areas of making things like compile modules work. The dependencies of the compile module need to match the runtime's target framework instead of the project's target framework. They may overlap, but they are different things. 

You can compile for dnxcore50 or dnx46 with a compiler that runs on dnx451. When running code in the compiler itself, that code and its dependencies need to also work on the target framework of the compiler.

**Comment by Antaris** [comment]
@davidfowl Confirm fixed my issue, thanks for that :-). Is there anything that can be done to make it a little more obvious for devs?

**Comment by GuardRex** [comment]
@davidfowl ... so the bottom line is that `dnx451` is required to use the `RazorPreCompileModule` at this time?

**Comment by Asshiah** [comment]
I think so.

I had to add the dnx451 target to my project.json file in order for the ICompileModule to be processed.
Before that I was only targeting dnx46 and nothing occured.

I could not even compile my project anymore as the ICompileModule complained about missing assemblies (Error message like Dnx namespace is not defined in Microsoft namespace, etc.) even though the assemblies where registered just fined in the project dependencies (nuget packages).

So yes it seems that at the moment we have to keep targeting dnx451 (other targets can be specified at the same time) for ICompileModules to work in Visual Studio (not in dnu build via command line).

**Comment by GuardRex** [comment]
@Asshiah Thanks. I had the same result when I was playing with it, and I think that's what @davidfowl was saying. However, I don't want `dnx451` in my clean and beautiful `dnxcore50`-only project.

I was looking at this in order to possibly use it for Razor view minification, but I think I have something that will work now for that [aspnet/Razor #444](https://github.com/aspnet/Razor/issues/444#issuecomment-138828582).

**Comment by tuespetre** [comment]
After cloning/building/debugging dnx's 1.0.0-beta7 tag, I think I found where the issue lies, and it looks like @davidfowl had already corrected it, though it did not make it into beta7:

https://github.com/aspnet/dnx/blob/7c6e557fc821f9f10d7ef2f72f6437c840fc18a9/src/Microsoft.Dnx.Compilation.CSharp/RoslynProjectReference.cs#L98

I have confirmed it's working as expected now (local dev build of dnx and changing my project to target `1.0.0-*` and the nightly feed)
