### ISSUE TITLE
Some beta5/beta6 dnx releases don't include vcruntime140.dll

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#2637]
Some beta5/beta6 dnx releases don't include vcruntime140.dll, mainly the coreclr builds. This is a problem for running on PC's that don't have the MSVC redist installed. Is this intended? I can't see the harm for including vcruntime140.dll since the focus for .net core is quick iterative releases.

**Comment by glennc** [comment]
Are they included in beta7? I am ok with looking at adding files in a new beta, but don't want to re-ship an old beta.

**Comment by xanather** [comment]
Hmm, even after copying the vcruntime140.dll I am getting api-ms-win-crt-runtime-l1-1-0.dll. Googling shows it wants MSVC 2015 runtime installed, is there any way to avoid this?

Regarding beta7, I am unsure I don't have the builds at the moment, I will have a look tomorrow

**Comment by glennc** [comment]
It's unlikely that it's there then. I was asking because it sounded like you meant it was there in beta7 and wanted it in the older versions. @moozzyk should be able to talk more about it.

**Comment by xanather** [comment]
Yeah sorry, its strange, dnx-clr-win-x86.1.0.0-beta6 includes it, but none of the other builds I have downloaded include it (not even dnx-clr-win-x64.1.0.0-beta6).

**Comment by moozzyk** [comment]
@xanather - what are you running clr/coreclr and where windows10/nano etc.? Or are you trying to run Kestrel? 
dnx-clr-win-x86 should not need vcruntime140.dll at all. Forwarders (i.e. api-ms-win-crt-runtime-l1-1-0) are only needed on onecore (currently Nano and Win 10 IoT core on RaspberryPI only) and these are only x64 bit. 
Some beta6 builds from the unstable feed were broken (#2129) and did not include vcruntime140.dll. We had the same problem with some pre beta7 builds from the unstable feed but the official beta7 build was fixed.

**Comment by xanather** [comment]
@moozzyk No I was not trying to run Kestrel, just a normal console app. This was on a fresh install on Windows 7 64-bit SP1 (with all updates installed). First I try including vcruntime140.dll in the bin folder for the runtime, which seems to work, but then api-ms-win-crt-runtime-l1-1-0.dll error appears, note this happens on multiple Win7 computers. Unless I install MSVC 2015/2014 runtime this problem persists.

**Comment by moozzyk** [comment]
Was it coreclr or desktop clr? Do you see the same thing happening if you are running beta-7?

**Comment by xanather** [comment]
This was on coreclr x86 beta6, trying out beta7 builds just now.

**Comment by xanather** [comment]
I am unable to create builds of my app using any beta7 runtime to test. I was trying to update some packages needed to run on beta7 (namely Microsoft.Dnx.Runtime.Abstractions). Error message:

C:\Users\xanat\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe "C:\Users\xanat\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "C:\Users\xanat\Documents\Files\Programming\Viron.Engine\src\Viron.Engine" "C:\Users\xanat\Documents\Files\Programming\Viron.Engine\src\Viron.Engine.Tester" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.

No PackageManager dll exists in the builds?

I will try restoring packages with a previous build for now, just thought I should post that here.

**Comment by moozzyk** [comment]
Looks like https://github.com/aspnet/Announcements/issues/44

**Comment by xanather** [comment]
I am slightly confused which MSI's I should download & run on http://www.microsoft.com/en-us/download/details.aspx?id=48738, it says nowhere. Should I install the beta6 tools first or go straight for beta7?

Anyway from what i can see
1.	DotNetVersionManager-x64.msi
2.	DotNetVersionManager-x86.msi
3.	WebToolsExtensionsVS14.msi
4.	WebToolsExtensionsVWD14.msi
Should be all?

**Comment by moozzyk** [comment]
If you have VS Professional/Enterprise you want this: WebToolsExtensionsVS14.msi.

**Comment by xanather** [comment]
Okay so I tested against the two beta7 CoreCLR windows runtimes:

Results:
dnx-coreclr-win-x86.1.0.0-beta7 still asks for VCRUNTIME140.dll. After copying the C++ runtime it also continues to ask for api-ms-win-crt-runtime-l1-1-0.dll
dnx-coreclr-win-x64-1.0.0-beta7 doesnt seem to require VCRUNTIME140.dll, however it still asks for api-ms-win-crt-runtime-l1-1-0.dll at startup

I am publishing both projects with with "dnu publish --no-source --runtime active --configuration Release"

I will create another post testing with desktop clr builds soon (I need to install the whole .net 4.6 on this slow VM).

**Comment by moozzyk** [comment]
Thanks. I will have to check this. vcruntime140.dll should not be needed on non onecore system - runtime should not depend on this. The forwarder (api-ms-win-crt-runtime-l1-1-0.dll) seems to be a separate issue but needs to be looked at as well.

**Comment by xanather** [comment]
For the two beta7 desktop CLR windows runtimes:

dnx-clr-win-x86.1.0.0-beta7 wants api-ms-win-crt-runtime-l1-1-0.dll at startup (VCRUNTIME140.dll came included in the bin folder for this version of the runtime).
dnx-clr-win-x64-1.0.0-beta7 also wants api-ms-win-crt-runtime-l1-1-0.dll at startup (VCRUNTIME140.dll is also came included in the bin folder for this version of the runtime).

**Comment by moozzyk** [comment]
What is your active runtime? I just installed beta7 coreclr runtime on Win7 and am able to run dnx (the errors you're seeing come from native parts of the stack so running dnx should be enough):

```
C:\Users\Administrator>dnvm list

Active Version     Runtime Architecture OperatingSystem Alias
------ -------     ------- ------------ --------------- -----
       1.0.0-beta7 clr     x86          win             default
  *    1.0.0-beta7 coreclr x86          win

C:\Users\Administrator>ver

Microsoft Windows [Version 6.1.7601]

C:\Users\Administrator>dnx
Microsoft .NET Execution environment CoreCLR-x86-1.0.0-beta7-15532

Usage: dnx [options]
```

I also don't quite understand this:

_dnx-clr-win-x86.1.0.0-beta7 wants api-ms-win-crt-runtime-l1-1-0.dll at startup (VCRUNTIME140.dll came included in the bin folder for this version of the runtime)._

clr runtime never relies on forwarders - it's linked against kernel32. Can you share what you have published or provide steps to repro this issue?

**Comment by xanather** [comment]
Sorry for the confusion about all this, I think your right. Running dnx.exe directly on all four dnx beta7 runtimes work fine, running a hello world project works fine. I think one of the packages for this other project I am using is dynamically linking to a separate native library which I overlooked, i'll have to figure out which one.

**Comment by moozzyk** [comment]
No problem. Hint - it feels to me that the native library you are using is built for onecore (UAP?) and hence it is depending on vcruntime140.dll/api-ms-win-crt-runtime-l1-1-0.dll. If you run `dumpbin {dll} /dependents` from the developer command prompt you will see what a library depends on and you should be able to identify the offending one.

**Comment by xanather** [comment]
Thanks for that tip, with it I quickly found out, its a third-party package so yes I am the one at fault here :)
