### ISSUE TITLE
Allow dnu build, dnu pack to search subdirectories like dnu restore

### ISSUE THREAD

**Issue by yufeih** [aspnet/dnx#2647]
It is easy to restore packages at any directory by just typing `dnu restore`, but to build or pack a solution with multiple projects, you need to run `dnu pack` on each project directory separately. It will be handy if I can just type `dnu pack` at the root directory to build and pack everything. 

Are there any specific reasons why `build` and `pack` are implemented the way it is today, or am I missing some features that already does the task?

The only alternative I know of is `msbuild` the solution but this is not my preferred choice.

**Comment by davidfowl** [comment]
The behavior of dnu rewrote actually sucks and we don't like it. Dnu build and pack support passing in a globbing pattern.

**Comment by yufeih** [comment]
Thanks @davidfowl , the globbing pattern works really nice. It might be better to update `dnu build --help` to give people a hint that it actually accepts a globbing pattern. `dnu restore --help` has a slightly more detailed explaination.

**Comment by victorhurdugaci** [comment]
The help today says "One or more projects build". I guess we can be more explicit about the globbing support
