### ISSUE TITLE
We need better test output

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2650]
Especially for the dnx functional tests, it is very hard to figure out what output comes from the dnx being tests and what comes from the dnx used to run the tests.

Also, a list at the end to show the failed tests would be useful. It is not fun to scroll through 1 MB of logs just to see what failed.

cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
See if https://github.com/aspnet/dnx/pull/2823 helps in terms of logging.
