### ISSUE TITLE
Unable to execute basic console app

### ISSUE THREAD

**Issue by hkesharia** [aspnet/dnx#2651]
I am trying to setup CoreCLR and run console application as mentioned here http://dotnet.readthedocs.org/en/latest/dnx/console.html#creating-a-console-app

I have created test folder. In the folder, created Program.cs and project.json as mentioned in the above link. 'dnu restore' got executed successfully, 'dnx . run' throws error. Please see the attached image, I have tried it in Ubuntu as well, same error there as well.

Any help to resolve it?

![image](https://cloud.githubusercontent.com/assets/7568529/9727020/ca54cd28-5617-11e5-8b49-25f45ae71666.png)

**Comment by davidfowl** [comment]
Remove the `.`. It's just `dnx run` now. See https://github.com/aspnet/Announcements/issues/52

**Comment by hkesharia** [comment]
Thanks davidfowl, it is working Windows now. But still it's not working in Ubuntu 15.04. In Ubuntu 'dvn restore' throws error as shown in attached image.

![image](https://cloud.githubusercontent.com/assets/7568529/9727298/12b0ce52-561b-11e5-938a-533490f0ed00.png)

**Comment by BrennanConroy** [comment]
Looks like you don't have everything installed that you need for CoreCLR, see: http://docs.asp.net/en/latest/getting-started/installing-on-linux.html

**Comment by hkesharia** [comment]
I have followed as mentioned here 
http://dotnet.readthedocs.org/en/latest/getting-started/installing-core-linux.html

**Comment by BrennanConroy** [comment]
That one looks old, use the one I linked
