### ISSUE TITLE
Invalid json -> exception instead of diagnostic message

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2658]
If you have invalid json in project.json we should produce a diagnostic message that's user friendly and that shows up in the VS error list

cc @troydai

**Comment by davidfowl** [comment]
We need to throw at runtime, also I'm not sure we can do anything more sensible and throw in general since if the `project.json` file or `project.lock.json` don't parse, we cant do anything else

**Comment by victorhurdugaci** [comment]
It can throw but it should output the message in a format the VS can understand. Also, most users don't need to see the call stack. A simple "Invalid json. Blah details about what's wrong" would be enough.

**Comment by davidfowl** [comment]
We can add GetDiagnostic or something to this:

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/FileFormatException.cs#L9
