### ISSUE TITLE
Hard to load my application assembly in new AppDomain

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/dnx#2663]
Running under Full .NET something like this works:

``` c#
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var domain = AppDomain.CreateDomain(
                "My AppDomain",
                null,
                new AppDomainSetup { ApplicationBase = AppDomain.CurrentDomain.BaseDirectory });

            var proxy = (TestClass)domain.CreateInstanceAndUnwrap(typeof(TestClass).Assembly.FullName, typeof(TestClass).FullName);

            Console.WriteLine(proxy.TestMethod());
        }
    }

    public class TestClass : MarshalByRefObject
    {
        public string TestMethod()
        {
            return "Hello World";
        }
    }
}

```

But under DNX451 you get an exception because the current assembly is not on disk to be loaded by the second AppDomain.

> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundExcept
> ion: Could not load file or assembly 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find
> the file specified.
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMar
> k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark
> & stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawl
> Mark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, Cul
> tureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstance(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
>    at ConsoleApp1.Program.Main(String[] args) in c:\users\rowmil\documents\visual studio 2015\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 14
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
>    at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
>    at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
>    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
>    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
>    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.Dnx.Host.Clr.RuntimeBootstrapper.Execute(String[] argv, FrameworkName targetFramework)
>    at DomainManager.Main(Int32 argc, String[] argv)

Do we need an easy way to get in-memory assemblies into AppDomains?

**Comment by davidfowl** [comment]
Not hard likely impossible unless you are precompiled. There's literally no way to make that work that I'm aware of.

**Comment by muratg** [comment]
What's the workaround? Launch another process and do IPC?

**Comment by davidfowl** [comment]
Use core clr 😀 or yes launch another process

**Comment by muratg** [comment]
@rowanmiller OK to close this?

**Comment by rowanmiller** [comment]
Yeah I was just raising it as a scenario that is easy under full .NET and hard (or impossible) under DNX. If we don't care about the scenario then that's fine... just wanted to make sure we knew about it and made a conscious decision :smile:. Consider it more "feedback from using DNX" rather than a request to make it work.

BTW the scenario came up as we use AppDomains as a way to run cold start benchmarks for EF (and proxies to send timing and memory info back to the main AppDomain). We just disabled these tests for DNX and only run them on Full .NET.

**Comment by davidfowl** [comment]
Yep, it's one of those things that are a limitation if you don't publish before running. I'm looking running in a mode where things are put on disk so that scenarios like this are possible.

**Comment by muratg** [comment]
Putting this into Backlog instead of closing per @davidfowl's last comment.
