### ISSUE TITLE
Testing Infrastructure Improvements

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2664]
Following up on #2617 

Some of the changes that I plan to add into the testing framework:

1 Organize environment variables for the test environment in Microsoft.Dnx.Testing.TestEnvironmentNames
- This will be similar to Microsoft.Dnx.Runtime.EnvironmentNames
- Prefix test specific names with DNX_TEST_*

2 Trace
- Set DNX_TEST_TRACE=1
- When enabled, test headers ("running test DnuPublishTest.PublishConsoleApp") test commands ("running dnu publish ...") will be displayed otherwise, only test summaries will be displayed

3 File retention behavior
- Set DNX_TEST_SAVE_FILES="None|All|Failed"
- Files saved to TestOutput/ will be deleted if None is set or if the test passed and Failed is set
- File deletion will occur at the end of each test method

4 stdout/stderr log (deferred)
- save the output of each test to files stdout.log/stderr.log inside each test directory in TestOutput/
- parallelization in xUnit makes redirecting output from Console difficult 
- also needs to determine a way to detect test method pass/failure without re-implementing xunit runner
- pending discussion

5 Test method headers
- announce the name of the test method to the output so it's easier to identify which test is running when scanning logs

6 Remove redundant testing (deferred)
- Currently some tests are run for each runtime in every environment and make tests very slow
- this requires changes to makefile and naming convention
- pending further discussion

7 Directory skip comparison
- currently when comparing directories, either the contents of all files are compared or no content is compared
- tag files/dirs. so that some files (especially binaries or directories of no interest) can be checked for existence only

8 Non-blocking execution of commands (deferred)
- This will be useful for cases such as DthTestServer in DTH FunctionalTests
- this is isolated to DTH for now so will not be part of this change

9 Specify a specific runtime via Environment Variable
- instead of all runtimes, specify one via EV so re-running tests during debug will be much faster

10 reverse runtime/testname structure
- this is required for 11

11 ensure restore and cache restored project
- some tests requires only one restore across all runtimes

12 make the default logs less verbose
- do not output execution logs if dnx/dnu commands are successful

13 renaming Microsoft.Dnx.Testing.CommonUtils -> Microsoft. (deferred)
- this is a simple change but I might not have time for this

14 DnxTestContext (deferred)
- see anurse's comment below for details
- I might not have time for this

**Comment by JunTaoLuo** [comment]
I'll open a PR once the features listed here are completed (or marked as deferred). In the meantime, the related changes will be tracked by https://github.com/aspnet/dnx/tree/johluo/2664-testing-infra-improvements

**Comment by anurse** [comment]
I have an additional suggestion that I started prototyping a bit once (unfortunately the prototype is gone but it was pretty simple).

First: Rename `DnxSdk` to `DnxTestContext` and hang the `GetTestFolder`/`GetSolution`/etc. methods off of it. 

Then: Replace the use of `InlineDataAttribute` with a new custom `DnxSdkTestAttribute` (inheriting from XUnit's `DataAttribute`) which provides instances of `DnxTestContext` appropriate to the current test (you get the `MethodInfo` in the function which generates the test data so you can easily get the class name/method name/etc.) and the author's chosen SDKs.

The attribute would take a Flags enum `SdkType` which has the following structure:

```csharp
[Flags]
public enum SdkType {
    Mono = 1,
    ClrWinX86 = 2,
    ClrWinX64 = 4,
    CoreClrWinX86 = 8,
    CoreClrWinX64 = 16,
    CoreClrMacOSX64 = 32,
    CoreClrUbuntuX64 = 64,

    // Combinations!
    AllClr = ClrWinX86 | ClrWinX64,
    AllCoreClr = CoreClrWinX86 | CoreClrWinX64 | CoreClrMacOSX64 | CoreClrUbuntuX64,
    AllWindows = AllClr | CoreClrWinX86 | CoreClrWinX64,

    // These ones are primarily for future expansion, because why not
    AllMac = CoreClrMacOSX64,
    AllUbuntu = CoreClrUbuntuX64,
    AllUnix = AllMac | AllLinux,
    AllLinux = AllUbuntu,
    AllNonWindows = AllUnix
}
```

As a side-benefit, we could even merge in some of what `ConditionalTheory` currently does to add skip conditions by ensuring we never run use Windows SDKs on Non-Windows OSes, etc.

This also removes the need for the base-class

A sample test with this could look like this:

```csharp
[Theory]
[DnxSdkTest(SdkType.AllWindows)]
public void MyDnxTest(DnxTestContext test) {
    var solution = test.GetSolution("FooBar");
    test.Dnu.Restore(solution.GetProject("FooBar")).EnsureSuccess();
    // etc...
}
```

In theory, we could actually create our own version of `TheoryAttribute` to reduce it down to a single attribute, but that would mean re-implementing more xunit code which seems unnecessary.

Thoughts? /cc @davidfowl @troydai

**Comment by JunTaoLuo** [comment]
There are quite a few good ideas here that I cannot finish implementing for beta8, I have marked them as deferred and will open another issue later to track them.

**Comment by anurse** [comment]
Absolutely fine with me :)

**Comment by JunTaoLuo** [comment]
merged to dev
