### ISSUE TITLE
dnx.win32.dll could not be loaded. Last error: 87

### ISSUE THREAD

**Issue by EGrishin** [aspnet/dnx#2666]
Hello. I have this error after 'dnvm upgrade'. Windows 7 x64

**Comment by Eilon** [comment]
@moozzyk can you investigate?

**Comment by moozzyk** [comment]
@EGrishin - what version of runtime you are using when you get this (i.e. what dnvm list shows). Do you have dnx.win32.dll in the runtime folder you are using (the folder is in `%USERPROFILE%\.dnx\runtimes` - e.g. for beta7 coreclr it will be in: `%USERPROFILE%\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta7\bin\`)

**Comment by moozzyk** [comment]
(FWIW - I installed all the beta7 runtimes on my Win7 x64 machine (which does not have any dev bits) and was not able to repro this issue).

**Comment by muratg** [comment]
@EGrishin Does this still repro for you? If so, can you provide the runtime information @moozzyk has asked?

**Comment by EGrishin** [comment]
@moozzyk, i have dnx.win32.dll in runtime folder.
![default](https://cloud.githubusercontent.com/assets/9007132/9869635/488cf5d2-5b8e-11e5-91a9-e25788f72f42.png)

**Comment by muratg** [comment]
@EGrishin do you get this error when you run a dnx or dnu?

**Comment by EGrishin** [comment]
@muratg 'dnx' and 'dnu' get one error: dnx.win32.dll could not be loaded. Last error: 87

**Comment by moozzyk** [comment]
@EGrishin - can you share your runtime directory? I am wondering if this is related to the runtime itself or the environment/machine. Also a few more questions:
- does this happen only on runtime 15594 or also on other runtimes you have installed (like beta7, 15548 etc.)
- have you tried the same runtime on a different machine (ideally win7 english, non-win7 russian (I think it's russian an not ukrainian right?)) - I wonder if it might be related to OS version or language settings
- are you sure you are running the dnx installed with the runtime (e.g. `where dnx` from command prompt)

**Comment by moozzyk** [comment]
No further details provided. Closing.

**Comment by ghostkaa** [comment]
Hi. I have same problem. How you solved it?

**Comment by kaanoo2904** [comment]
Hi, I have this problem too. Windows 7 x64, dnx version 1.0.0-rc1-final.

![image](https://cloud.githubusercontent.com/assets/10462294/11455487/aa58d96a-9695-11e5-821c-83a5d460bac9.png)

**Comment by 010227leo** [comment]
same problem..

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/3213 tracks this with more details.

**Comment by moozzyk** [comment]
@EGrishin - in the other bug the issue was fixed by installing the latest updates. Make sure your system is up-to-date if you are still experiencing it (actually even if you are not experiencing it it is good to have the latest updates).

**Comment by ZOXEXIVO** [comment]
Which KB_xxx fix this problem ?

**Comment by moozzyk** [comment]
I was never able to reproduce the issue in my environment so I don't know exactly which KB fixes this. On the other hand dnx is going away so this would no longer be a problem in RC2 and beyond.

**Comment by otakusid** [comment]
To reproduce this issue you should install **dnvm** using powershell script [how to install](https://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-5-from-the-command-line) on the clean system from one user. And then try to use **dnu** from another user. When you recognize that **dnu** even not in PATH and try to run it by specifying full path, from dir with sources of your project - you reproduce the issue :)
