### ISSUE TITLE
Discussions for DNX Beta7 renames

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2678]
See https://github.com/aspnet/Announcements/issues/44

> You can now use the latest DNX builds from the dev feed alongside the Beta6 version of the ASP.NET Tools (available here: http://blogs.msdn.com/b/webdev/archive/2015/07/27/announcing-availability-of-asp-net-5-beta-6.aspx) without the environment variable described below. As long as you have the beta6 tools and a DNX build greater than or equal to 1.0.0-beta7-12290, the environment variable should not be necessary (in fact, you should remove it).

**Comment by ardalis** [comment]
So, if we are getting this error on the latest beta7 with the latest VS tools for beta7, what should we do?

**Comment by davidfowl** [comment]
What error exactly?

**Comment by ardalis** [comment]
On project load:
"error occurred attempting to run the DNX design time process (dnx-clr-win-x86.1.0.0-beta7). Unable to start the process. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.DesignTimeHost' or one of its dependencies. ..."

At build time:
1>------ Build started: Project: TodoApi, Configuration: Debug Any CPU ------
1>  C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe --appbase "C:\dev\github\aspnet-docs\aspnet\fundamentals\logging\sample\src\TodoApi" "C:\Users\Steve\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" pack "C:\dev\github\aspnet-docs\aspnet\fundamentals\logging\sample\src\TodoApi" --configuration Debug --out "..\..\artifacts\bin\TodoApi"
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.PackageManager' or one of its dependencies. The system cannot find the file specified.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : File name: 'Microsoft.Framework.PackageManager'
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error :    at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : WRN: Assembly binding logging is turned OFF.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : Note: There is some performance penalty associated with assembly bind failure logging.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(152,5): error : To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by anurse** [comment]
It's definitely using the wrong name. Did you ever use the `WEBPROJ_ENABLEBETA7RENAMES` environment variable to disable the use of the rename? If so, you need to remove that setting.

**Comment by ardalis** [comment]
I had had it set. I had removed it, multiple times, at the command prompt, but it wasn't being removed from my user profile. I finally figured that out and removed it via the GUI under This PC > Properties > Advanced System Settings and that deleted it permanently and sufficiently for VS to stop seeing it.

**Comment by anurse** [comment]
Ah yeah, removing it from the command line actually just sets it to empty in that command prompt.

**Comment by ericwj** [comment]
Which version is 1.0.0-beta7? >=12290? I switched to rc1-15838 to see if it fixed this, but I still get FileNotFoundException. It might be the tooling still, if I download beta6 from the link provided, it'll complain there is a newer version already. Should I remove that Microsoft ASP.NET and Web Tools 2015 - Visual Studio 2015 dd 28-09-2015 v14.0.60814.0 listed under Programs and Features and try installing (beta6) of that?

Or what else to get rid of this error? SET WEB produces a not defined error, so that shouldn't be it.
`%UP%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15838\bin\dnx.exe "%UP%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15838\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "C:\Project" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
System.IO.FileNotFoundException
File name: Microsoft.DNX.PackageManager`
