### ISSUE TITLE
React to externalized file watcher changes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2683]
- Delete IApplicationShutdown and merge it with IApplicationLifetime (see https://github.com/aspnet/Hosting/pull/264)
- Remove IFileWatcher interfaces from the runtime

**Comment by davidfowl** [comment]
@victorhurdugaci assigned to you

**Comment by davidfowl** [comment]
Need to do this post beta8

**Comment by muratg** [comment]
@davidfowl still working on this?

**Comment by davidfowl** [comment]
@pakrym You did this right?

**Comment by muratg** [comment]
I think this was done.

**Comment by victorhurdugaci** [comment]
@muratg @davidfowl you were supposed to be at the Christmas party... cc @Eilon fyi

**Comment by muratg** [comment]
@victorhurdugaci I really wanted to go, but decided to take a nap before going (I had like 3 hours sleep last night) and couldn't wake up. :hankey:

**Comment by pakrym** [comment]
@davidfowl yes, there is not IApplicationShutdown anymore

**Comment by davidfowl** [comment]
@pakrym Well close da bug :smile:
