### ISSUE TITLE
Add ability to ignore particular build warnings

### ISSUE THREAD

**Issue by Daniel15** [aspnet/dnx#2693]
Moved from https://github.com/aspnet/Home/issues/900

---

In csproj files, you can ignore particular build warnings with the `<NoWarn>` element (labelled as "Suppress warnings" in Visual Studio). For example, to ignore CS7035, you can either add `<NoWarn>7035</NoWarn>` to the csproj or pass it to MSBuild via `/p:NoWarn=7035`.  This does not appear to be possible with `project.json`

cc @Eilon @dougbu

**Comment by smbecker** [comment]
Duplicate of #2042?

**Comment by davidfowl** [comment]
Yes it is!
