### ISSUE TITLE
Removing a dependency should not be a breaking change

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnx#2694]
Currently dependencies are transitive which means that removing a dependency is a breaking change. If my app depends on A and A depends on B then my app depends on B, even if B is just an implementation detail of A. My app might use some type in B even though my app doesn't directly declare B as a dependency and this will currently work fine. If A later removes it's dependency on B then my app will break, so A would need to update it's version accordingly. This seems overly burdensome on package authors.

Some ideas: We could either require a project to declare all of it's direct dependencies (i.e. my app would fail to compile if it didn't declare its dependency on B). Or we could provide a way for A to hide its dependency on B as it is really just an implementation detail of A and not a formal contract.

**Comment by davidfowl** [comment]
> We could either require a project to declare all of it's direct dependencies (i.e. my app would fail to compile if it didn't declare its dependency on B)

This would be insane.

> Or we could provide a way for A to hide its dependency on B as it is really just an implementation detail of A and not a formal contract.

https://github.com/aspnet/dnx/issues/2391#issuecomment-127199095

It should also be a compile error if you marked a dependency as private and something was exposed in public API from that dependency.

**Comment by danroth27** [comment]
> This would be insane.

Why would this be insane? I think it's actually a good practice to be explicit in your project what you directly depend on. It makes inspecting your project dependencies easier and you get more control over the version that your project uses. If the runtime had this behavior it would help you make sure you did this correctly.

**Comment by davidfowl** [comment]
@danroth27 do it and tell me if you can figure out the 50 BCL package dependencies that you *actually* need in your application then let's talk :smile:

**Comment by muratg** [comment]
It doesn't look like we'll do this. Closing.  @danroth27 If you end up finding the right way to do it, please reopen. :)
