### ISSUE TITLE
Cache not caching?

### ISSUE THREAD

**Issue by benaadams** [aspnet/dnx#2696]
Looking at the allocations across a couple hundred repeated requests; same as in non-selected front part of trace:

![image](https://cloud.githubusercontent.com/assets/1142958/9839232/f86ab3d8-5a6a-11e5-97c2-ac25ddcd2f7b.png)

There are a enormous amounts of string allocs going on in dnx

![image](https://cloud.githubusercontent.com/assets/1142958/9839253/81f30c7c-5a6b-11e5-93ef-1f9f3b51f5d2.png)

However I'd assume since these are the same requests as at start everything should already be compiled? Mostly seems to be in LockfileReader:

![image](https://cloud.githubusercontent.com/assets/1142958/9839287/ebf5395a-5a6c-11e5-8efb-5a3a5c700c4c.png)

**Comment by muratg** [comment]
@troydai Any thoughts?

**Comment by benaadams** [comment]
Note this was running from source; running packaged --no-source didn't exhibit these issues

**Comment by troydai** [comment]
Well we do have work items to track the duplicate allocation of various things https://github.com/aspnet/dnx/issues/1446. And we're working on reducing the amount of string and duplicate data used in lock file reading.

Thanks @benaadams 

@muratg I link this issue to our other performance bugs.

**Comment by benaadams** [comment]
Closing this as stuff is moving to dotnet cli
