### ISSUE TITLE
A non-portable project cannot reference a portable one. Type exists in both + fx/System.Runtime could not be resolved

### ISSUE THREAD

**Issue by antiufo** [aspnet/dnx#2697]
See this example project: https://github.com/antiufo/exists-in-both
It contains a portable class library, and a dnxcore50/dnx46 project that references it.

Compilation fails with the following errors:
- Unable to resolve dependency fx/System.Runtime 4.0.0 (for the netcore50 version)
- The type 'AssemblyFileVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (for the dnx46 version)

**Comment by muratg** [comment]
@anurse Could you have a look please?

**Comment by davidfowl** [comment]
I'm looking into this assign to me
