### ISSUE TITLE
dnu restore fails when restoring a project reference

### ISSUE THREAD

**Issue by Mpdreamz** [aspnet/dnx#2698]
> System.ArgumentException: Can not add property System.Runtime to Newtonsoft.Json.Linq.JObject. 
> Property with the same name already exists on object.
>   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
>  at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
>   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
>   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
>   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteTargetLibrary(LockFileTargetLibrary library)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteTarget(LockFileTarget target)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteObject[TItem](IEnumerable`1 items, Func`2 writeItem)
>   at Microsoft.Dnx.Tooling.LockFileFormat.WriteLockFile(LockFile lockFile)
>   at Microsoft.Dnx.Tooling.LockFileFormat.Write(Stream stream, LockFile lockFile)
>   at Microsoft.Dnx.Tooling.LockFileFormat.Write(String filePath, LockFile lockFile)
>   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String > projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IProjectResolver > projectResolver, IEnumerable`1 contexts)
>   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
>----------
>Restore failed
>Can not add property System.Runtime to Newtonsoft.Json.Linq.JObject. Property with the same name >already exists on
>object.

This happens as soon as I add this project reference here: 

https://github.com/elastic/elasticsearch-net/blob/vnext/dnx-support/src/Nest/project.json#L21

Which is this project: https://github.com/elastic/elasticsearch-net/blob/vnext/dnx-support/src/Elasticsearch.Net/project.json

> dnu --- version

```
Microsoft .NET Development Utility
 Version:      1.0.0-beta8-15613
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
 Runtime Id:   win8-x86
```

> dnvm list

```
Active Version           Runtime Architecture Location                        Alias
------ -------           ------- ------------ --------                        -----
       1.0.0-beta4       clr     x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta4-11566 clr     x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta5       clr     x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta5       clr     x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta5       coreclr x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta5       coreclr x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta6       clr     x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta6       clr     x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta6       coreclr x64          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta6       coreclr x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta7       clr     x86          C:\Users\mpdreamz\.dnx\runtimes
       1.0.0-beta7       coreclr x86          C:\Users\mpdreamz\.dnx\runtimes
  *    1.0.0-beta8-15613 clr     x86          C:\Users\mpdreamz\.dnx\runtimes default
       1.0.0-beta8-15613 coreclr x86          C:\Users\mpdreamz\.dnx\runtimes
```

**Comment by muratg** [comment]
Thanks for the report. We'll investigate.

**Comment by muratg** [comment]
@JunTaoLuo Could you investigate please.

**Comment by davidfowl** [comment]
Looks like https://github.com/aspnet/dnx/issues/2554

**Comment by Mpdreamz** [comment]
I think so too deleting this line:

https://github.com/elastic/elasticsearch-net/blob/vnext/dnx-support/src/Elasticsearch.Net/project.json#L7

Fixes the dnu restore.
