### ISSUE TITLE
Remove dnu sources

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#2699]
At this point, we don't feel the feature is ready to be shipped at v1. We'll bring it back in the future once we feel it is ready.

**Comment by pranavkm** [comment]
Related: https://github.com/aspnet/dnx/issues/2455

**Comment by tillig** [comment]
Will the removal cause warnings during build if the `repo` information is left in `project.json` or will it just be ignored?

**Comment by davidfowl** [comment]
Ignored.

**Comment by david-driscoll** [comment]
This also doesn't prevent us from doing something similar using the global.json today, correct?  It's just we won't have a way using `dnu` to do it automatically.

**Comment by pranavkm** [comment]
> This also doesn't prevent us from doing something similar using the global.json today, correct? 

The parsing code does not have a strict schema that it validates these files against and simply ignores keys that it doesn't know about.

**Comment by pgrudzien12** [comment]
I've gome through announcement and this thread and still do not understand what was removed. Dnu script is still there and tooling source haven't been changed so what am I missing? Commit link would be useful.

**Comment by pranavkm** [comment]
Here's the actual work item that tracked the removal: https://github.com/aspnet/dnx/pull/2692

The command `dnu sources` and the associated code that executed when you ran `dnu pack` was removed.
