### ISSUE TITLE
Fix postbuild/postpack scripts in dnx repo

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2702]
After fixing #887 the {post|pre}pack scripts are run before/after pack and the {pre|post}build scripts are run after build. We have a few project.json files in the dnx repo that use scripts. Currently they have hardcoded paths copying files from Debug folder. Since build is always Release this is no-op on the CI. However on dev boxes where we typically build Debug we would copy too much some of the files will be copied to wrong folders (e.g. dnx451 bits to dnxcore50 runtime)

**Comment by muratg** [comment]
@moozzyk Need to do this in Beta 8?

**Comment by moozzyk** [comment]
@muratg - this is polish. can be done as part of sign off..

**Comment by muratg** [comment]
:+1: Let's do it while doing the sign-offs.

**Comment by muratg** [comment]
Moving to other Pavel
