### ISSUE TITLE
Don't return -1 exit code from managed code

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2707]
Follow up to https://github.com/aspnet/dnx/pull/2691 but in managed code - on non-windows valid exit codes are 0-255. However, in several places we return `-1` which is then converted to 255 which is wrong. We should return 1.
(Especially review all `return -1` and `Task.FromResult(-1)` occurrences)

**Comment by muratg** [comment]
@moozzyk If simple to do and not risky, we can pull back to beta 8.
