### ISSUE TITLE
[Announcement] dnx minimum version check

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2711]
Discussions for https://github.com/aspnet/Announcements/issues/68

**Comment by NeelBhatt** [comment]
I like this :+1:

**Comment by Antaris** [comment]
What is a use case for disabling this check as I can't really think of any myself?

**Comment by victorhurdugaci** [comment]
Outside of our team it might not be very common but for us it's extremely useful for us because we can have multiple builds per day and it makes it hard to keep everything in sync on the dev box.
