### ISSUE TITLE
AppVeyor build fails to resolve dnx451 dependencies

### ISSUE THREAD

**Issue by tmds** [aspnet/dnx#2712]
When I build.cmd my project on my local machine, it works fine.
On AppVeyor executing the tests throws an exception:
```
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   System.Reflection.Extensions 4.0.0.0 (incompatible) 

Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0
```
My NuGet.Config looks like this:
```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="NuGet" value="https://nuget.org/api/v2/" />
    <add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2" />
  </packageSources>
</configuration>
```
On AppVeyor and on my local machine I set the following environment variables:
```
BUILDCMD_RELEASE=beta7
DNX_FEED=https://www.nuget.org/api/v2
```

**Comment by muratg** [comment]
Are you trying to build the dev branch?

**Comment by tmds** [comment]
I am building a project of my own: https://github.com/tmds/Tmds.SockJS
The master branch should work in a beta7 enviroment. It works fine on my machine, but for some reason the tests don't run on AppVeyor.
The error message is talking about missing dependencies (4.0.0.0), but I don't know what to do about it. Any pointers on what I should change or how I can debug are welcome.

**Comment by muratg** [comment]
Beta 7 is already released, so you shouldn't need the aspnetmaster feed, everything a regular app needs is on nuget.org (beta7.) 

Are you depending on an exact version of `System.Reflection.Extensions` package?  

Sorry, I'm unable to look at your repo due to its license, but if you paste your project.json here, we can try to see what the problem may be.

**Comment by tmds** [comment]
I updated the license of my project to MIT, so you can have look now.
I am not depending on an exact version of the Extensions package. I think there is an issue resolving 'any' 4.0.0.0 package.
The project.json of the Tests looks like this:
```
{
    "description": "Tests for Tmds.SockJS",
    "authors": [ "Tom Deseyn" ],
    "dependencies": {
        "xunit.runner.aspnet": "2.0.0-aspnet-beta7",
        "Microsoft.AspNet.TestHost": "1.0.0-beta7",
        "TestWebSite": "1.0.0-*",
        "Microsoft.AspNet.WebSockets.Protocol": "1.0.0-beta7"
    },
    "commands": {
        "test": "xunit.runner.aspnet"
    },
    "frameworks": {
        "dnx451": { }
    }
}
```
Feel free to point out improvements to the project.json files in the solution.

**Comment by tmds** [comment]
LOL, AppVeyor seems to prefer an MIT License, now the project is building fine.
This build wasn't okay: https://ci.appveyor.com/project/tmds/tmds-sockjs/build/1.0.0-beta7-73
This build is: https://ci.appveyor.com/project/tmds/tmds-sockjs/build/1.0.0-beta7-74

**Comment by muratg** [comment]
LOL...  i guess AppVeyor was just being unreliable. 

Your project.json looks fine BTW.   Closing this issue, let us know if you hit other issues.

**Comment by tmds** [comment]
@muratg FYI, I've had the problem again and created an [AppVeyor issue](http://help.appveyor.com/discussions/problems/3124-xunit-tests-occasionally-throw-failed-to-resolve-dependencies-for-target-framework).

**Comment by muratg** [comment]
:+1:

**Comment by tmds** [comment]
@muratg looking a bit closer at the error message, I am wondering... System.Reflection.Extensions does that exist for DNX,Version=v4.5.1?
