### ISSUE TITLE
Assemble CoreCLR DNX from packages

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2728]
Use a project.json and runtime.json restore to assembly the CoreCLR DNX from packages.

Open Question: Where is `mscorlib.dll` and could we get `crossgen.exe` from a package? It's essential that these binaries and `coreclr.dll` be in sync AFAIK.

/cc @BrennanConroy @moozzyk @muratg @davidfowl

**Comment by BrennanConroy** [comment]
64c8d50eab71d884cd53e432b1b64e0cf432200
