### ISSUE TITLE
Create and test distro-specific DNXes

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2730]
We likely won't be able to ship a generic linux binary version of DNX for RTM due to CoreCLR incompatibilities. Until we work that out, we will create separate DNXes for our two officially supported distros: Ubuntu and CentOS.

We will REMOVE the `dnx-coreclr-linux-x64` package and ADD `dnx-coreclr-ubuntu-x64` and `dnx-coreclr-centos-x64` packages.

/cc @moozzyk @BrennanConroy @muratg @davidfowl

**Comment by muratg** [comment]
CentOS will be in Beta8.

**Comment by moozzyk** [comment]
Do we have CentOS CoreClr packages? I thought we did not...

**Comment by muratg** [comment]
Just checked, you're right it's not going to be in Beta 8. It'll be in early RC1.

**Comment by muratg** [comment]
Moving out of RC1 per discussion with @davidfowl

**Comment by joshfree** [comment]
@Eilon @coolcsh @danroth27 we need this for rc1

**Comment by ellismg** [comment]
FYI, The CLR team is now producing runtime packages for both Ubuntu 14.04 and Centos 7, so it should be possible to suck that into your process for building out DNX packages.
