### ISSUE TITLE
need an explicit “link” between dependency diagnostic warning/error and a dependency

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2743]
In order to implement this spec (see bottom for dependencies tree): https://github.com/aspnet/specs/blob/master/tooling/proj-json-missing-dep.md we also need an explicit “link” between dependency diagnostic warning/error and a dependency. 

Warnings/errors that we receive now, don’t have a code we could reference (even if they would , how do we parse it to determine which dependency it is related to?)

**Comment by troydai** [comment]
Proposed new error/warning entity (or may be reuse existing `DependencyDiagnosticss`)
``` JSON
{
  "dependency": {
    "name": "the dependency name",
    "version": "the requested version",
    "type": "package / project / unresolved",
    "resolved": "true / false"
  },
  "message": "NU100X: error message"
}
```

**Comment by davidfowl** [comment]
We need to do a few things:

- DiagnosticsMessage should have a Source property that's of type object
- When we make dependency diagnostics we should set the source to be the library description.
- DTH can cast the source and return the appropriate data. I think you only really need the name.

**Comment by troydai** [comment]
Fixed in 5db0890391be3ec34cee776c789431263055fce0

**Comment by muratg** [comment]
Cool, hopefully @abpiskunov will be able to finish the tooling side as well. It'll be a nice feature!

**Comment by abpiskunov** [comment]
Awesome, thanks for quick change!
