### ISSUE TITLE
Need to handle multiple cases of "NuGet.config".

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/dnx#2747]
I did a partial fix to updating DNX to understand the new NuGet.config (required by nuget.exe v3). You typically won't see issues until you go cross plat where file systems are case sensitive.

For context on this issue see the comment I left on the [commit](https://github.com/aspnet/dnx/commit/4cb916d2e0f88d6a62fa5224dbb5e65e77523068).

**Comment by akoeplinger** [comment]
Can we please just make it "nuget.config" and be done with all the casing shenigans :smile:

**Comment by Jetski5822** [comment]
yeah, I kind of agree, you have packages.config all lowercase for example.

**Comment by pranavkm** [comment]
This should be already fixed - https://github.com/aspnet/dnx/commit/9dca281a9594eec292c0bb502e31535900a23223. Similar changes need to happen on NuGet's side to ensure the casing behavior is unified.

**Comment by NTaylorMullen** [comment]
@pranavkm your changes don't account for this do they? https://github.com/aspnet/dnx/blob/9dca281a9594eec292c0bb502e31535900a23223/src/Microsoft.Dnx.Tooling/NuGet/Core/Configuration/Settings.cs#L177-L178

**Comment by davidfowl** [comment]
@pranavkm Did you fix this?
