### ISSUE TITLE
(Ubuntu) dnu and dnx not working when running as unprivileged user

### ISSUE THREAD

**Issue by Flavien** [aspnet/dnx#2748]
I'm installing the DNX (1.0.0-beta7) on Ubuntu using this, as seen in the asp.net dockerfile.

```
curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
    && dnvm install $DNX_VERSION -r coreclr -a default \
    && dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"
```

Then if I call `dnu` or `dnx` when running as root, it works as expected, however when running as an unprivileged user,  they just return (error code 5) with no output.

Any idea what's happening?

**Comment by KoKuToru** [comment]
We had the same problem, using the Dockerfile from github worked (Dockerfile from dockerhub didn't).

The github-version does not include `-r coreclr`. Removing the parameter worked for us.

**Comment by Flavien** [comment]
I believe that if you don't use `-r coreclr`, you get the mono version, don't you? I'm trying to use specifically the CoreCLR version.
