### ISSUE TITLE
PackInclude broken for recursive wildcards

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2750]
I tried to use packInclude on kestrel to package native binaries (specifically everything in here https://github.com/aspnet/KestrelHttpServer/tree/3470c6206a0a9c7a4ba5b22e00a03567409cbe27/src/Microsoft.AspNet.Server.Kestrel/native)

I modified `project.json` in `Microsoft.AspNet.Server.Kestrel` to have the following

```JSON
  "packInclude": {
    "native/": "native/**"
  }
```

Expected it to preserve the layout:

```
├───darwin
│   └───universal
└───windows
    ├───amd64
    └───x86
```

But actual

```
├───darwin
│   └───universal
└───windows
    └───amd64
        └───x86
```

Somehow it thinks that x86 is a child of amd64.

/cc @anurse 

/cc @bricelam and @natemcmaster  for visibility

**Comment by natemcmaster** [comment]
Urgency went up! This is breaking our CI now. See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/153

**Comment by BrennanConroy** [comment]
This was fixed by https://github.com/aspnet/FileSystem/pull/152

**Comment by davidfowl** [comment]
@BrennanConroy can you make sure the CLI is using this build?

**Comment by BrennanConroy** [comment]
I doubt it, they use a rc1 build of dnx

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/cli/blob/d461755c547f3517e083fab2fdd92a4385003851/scripts/obtain/install-dnx.ps1#L9

**Comment by davidfowl** [comment]
@BrennanConroy not what I meant :smile: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.ProjectModel/project.json#L17

**Comment by BrennanConroy** [comment]
Ah, 15882 has the change so they're good
