### ISSUE TITLE
Find entrypoints at compile time instead of runtime

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2753]
This will remove all of the searching we do at runtime. We can look for the entry point in the roslyn compiler and mark the assembly with an attribute [DnxEntryPoint] or something similar. We can still do the scan as a fallback.

**Comment by Eilon** [comment]
Fascinating. Do you envision allowing a user to manually mark a method with `[DnxEntryPoint]`?

**Comment by davidfowl** [comment]
Yes, although I'm trying to reduce the dependency on DNX itself. So maybe we look for that attribute by name instead of by type. An alternative would be to make an assembly with a real ECMA compliant entrypoint (public static void Main) and move some of our bootstrapping logic into the assembly itself:

```
public class Program
{
    public static void Main(string[] args)
    {
        new DnxEntryPoint().Main(args);
    }
}

public class DnxEntryPoint
{
    public void Main(string[] args)
    {
    }
}
```

There are some issues with this like how does DI work, do we need to inject in the generated code etc.

**Comment by borgdylan** [comment]
Automatic injection of an attribute would mean that specialized compiler forks would be needed just for use with DNX as specific logic would be needed just like with "static <type> main". Using an attribute from a package or using a naming convention would be best.

Also why would specific searching be carried out apart from looking for Program.Main in the project that dnx run gets invoked on?

**Comment by davidfowl** [comment]
@borgdylan What do you mean?

**Comment by borgdylan** [comment]
I meant that compilers would need to apply an attribute like is done while setting the entry point. Such changes are usually done inside the compilers themselves and not externally.
