### ISSUE TITLE
Add support for producing ecma compliant "exe"

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2754]
This will allow us to use dnx to produce the host as well. 

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Mono/EntryPoint.cs

**Comment by akoeplinger** [comment]
I presume this fixes https://github.com/aspnet/dnx/issues/1997 as well?

**Comment by borgdylan** [comment]
With this option, a compiler will still have to use the ".dll" extension when ordered to spit out files to disk?

**Comment by davidfowl** [comment]
@akoeplinger Hah, didn't even see that.

**Comment by davidfowl** [comment]
@bojanrajkovic You can do what you want to really. We're not changing the .dll extension.

**Comment by davidfowl** [comment]
Makes me wonder if we should call it emitEntryPoint so we don't confuse people when the output isn't an exe.

**Comment by davidfowl** [comment]
Done, the compiler option is emitEntryPoint

**Comment by akoeplinger** [comment]
Great :clap:

**Comment by bojanrajkovic** [comment]
@davidfowl Heh, I think you meant @borgdylan. Was wondering what I'd gotten myself into this time.

**Comment by davidfowl** [comment]
Oops! 😀

**Comment by borgdylan** [comment]
@davidfowl I thought the answer was not meant for me. Thanks for clearing this. Now I can implement the right behaviour in my provider.

**Comment by xanather** [comment]
Will it ever be possible for DNX to produce a native binary for a target platform (replaces dnx.exe) as a static app-specific bootstrapper? I think that would be pretty cool.

**Comment by borgdylan** [comment]
I found it easy to implement this for my own language support. Would this have any application apart from writing DNX hosts or command line tools to have no dependencies that are external to the BCL?
