### ISSUE TITLE
Visual Studio Restore packages uses wrong runtime

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#2766]
Not sure if its linked directly to VS or to dnx, but if you create a new web project, change project.json to only target the coreclr ("frameworks": { "dnxcore50": { }}), and right click on the Restore Packages in Visual Studio, the error output shows its always trying to restore from a clr runtime not a coreclr runtime.

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe "C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" restore "...
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.DNX.PackageManager'

I am targetting coreclr beta7

{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "exclude": [
        "wwwroot"
    ],
    "packExclude": [
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
        "Microsoft.AspNet.Mvc": "6.0.0-beta7",
        "Microsoft.AspNet.Hosting": "1.0.0-beta7",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta7",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta7",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta7",
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
    },
    "frameworks": {
        "dnxcore50": { }
    }
}

Calling dnu restore from command line works fine, and dnvm list is using the coreclr.

Active Version     Runtime Architecture Location                    Alias
------ -------     ------- ------------ --------                    -----
       1.0.0-beta5 clr     x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5 clr     x86          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5 coreclr x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5 coreclr x86          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta7 clr     x86          C:\Users\xxx\.dnx\runtimes
  *    1.0.0-beta7 coreclr x86          C:\Users\xxx\.dnx\runtimes default

It seems VS is ignoring completely the specified runtime in project.json and also in the properties page of the solution that explicity states to use ".Net Core". I've tried it checked and unchecked with the same result.

**Comment by davidfowl** [comment]
Visual studio always uses the non .NET Core dnx to restore packages and it doesn't really matter that it does.

**Comment by davidfowl** [comment]
The issue you're running into is that you need to update your tooling to beta7. See http://www.microsoft.com/en-us/download/details.aspx?id=48738&fa43d42b-25b5-4a42-fe9b-1634f450f5ee=True
