### ISSUE TITLE
Batch restore on a directory re-locks entire directory after first invalid lock file

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#2771]
When restoring for a single project the following line of code updates the lock state for the entire command.
https://github.com/aspnet/dnx/blob/a0af28b330f858c0ddc2063adfbd0ad18225c4ee/src/Microsoft.Dnx.Tooling/Restore/RestoreCommand.cs#L256

This causes the remaining lock files all to be rewritten, and their \* dependencies re-evaluated to latest.

/cc @weshaggard

**Comment by ericstj** [comment]
Just to be clear, I'd only expect regeneration of the 'invalid' lock files, not the entire repo.

**Comment by davidfowl** [comment]
@ericstj Yep. That sounds like a bug.

**Comment by weshaggard** [comment]
We keep hitting this issue in our corefx repo which is causing folks some grief. Any thoughts on how to work around this or ETA on a fix?

**Comment by dagood** [comment]
I have a temporary fix where I store `Lock` in a local variable (`relock`) in `RestoreForProject` and use that local variable going on. I then passed `relock` into another method that previously used `Lock`. It worked for my scenario but I don't know if there's a broader impact.

This is part of a larger set of changes right now, but I could cherry-pick and submit a pull request.

**Comment by davidfowl** [comment]
Just FYI, you shouldn't be checkin in lock files, in fact, we're going to be removing the locked property.

**Comment by ericstj** [comment]
Are you dropping * versions too and moving the file to intermediate directory?

**Comment by ericstj** [comment]
Also, I suspect this will make our perf problem worse.  If restore always writes the lock we are back to the perf issue that made us notice this bug in the first place.

**Comment by davidfowl** [comment]
We'll keep supporting *. Moving to an intermediate directory came up but nobody really agrees where it should go and it would require existing tools to update. 

@ericstj What performance issue is that?

**Comment by weshaggard** [comment]
For us it is critical to have the lock file for * versioning scenarios otherwise we cannot use it. We need our builds to be reliable and repeatable. 

As for the performance issue we try and restore all our packages up front and we cannot do that in parallel by launching multiple nuget/dnu restore commands because of all the races. That is why we started using this approach. So the only way for us to avoid that race problem would be to serialize all these restores and that is much slower.

**Comment by weshaggard** [comment]
To add to this we want to switch to nuget.exe v3 at some point which doesn't currently support this restore all under a directory so we need to figure out how to support this scenario there as well.

**Comment by ericstj** [comment]
Roughly, perf for our repo when we DNU re-writes lock files compared to when it does not is at least 20x.  We have 884 project.json files, 396 of them use * versioning and check in a lock file for predictable results.

We like the * because we can just run dnu restore --lock to update all dependencies to latest.  If we don't have that we'd probably list explicit versions in the project.json and write a tool that updates them all.

Perhaps we should just try this and see what the perf is to understand if the huge perf hit was from DNU hitting the feed over and over to evaluate *'s or if it is from lock-file generation itself.  I was assuming that * evaluation wouldn't be the dominant factor since most projects use the same set of packages and DNU caches the result across the operation.  Perhaps that was a poor assumption.
