### ISSUE TITLE
We need logic to translate non-Windows OS, OSName to RID

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2773]
Currently we create a valid RuntimeId only for Windows. For other OSes we just concatenate os and os version (https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime.Internals/RuntimeEnvironmentExtensions.cs#L106). This kind of worked before we started passing actual OS details but now in my branch that provides the details we get:

`darwin10.9-x64`
`linuxUbuntu 12.04-x64`

Also note that we say that we only recognize Ubuntu 14.04 as a supported version but Travis is running on 12.04.

**Comment by anurse** [comment]
Yeah, this is going to get a bit hairy. We can do fairly simple processing of the OS name to get it in to a RID.

The Travis issue is concerning. I'm not sure right now what the best option is... /cc @davidfowl

**Comment by moozzyk** [comment]
I am just hacking it - will show you soon...

**Comment by moozzyk** [comment]
Yes, creating a RID should be simple. For now I am just working around this issue since I don't want to make the PR any bigger.

**Comment by anurse** [comment]
Ouch, this should happen for beta8. /cc @muratg @DamianEdwards @Eilon 

OSX is working, but Ubuntu is reporting a RID of `linux.Ubuntu 14.04-x64` when it should be `ubuntu.14.04-x64`

**Comment by muratg** [comment]
Ugh, yeah I think we should take it.

**Comment by anurse** [comment]
We could consider taking a small fix here as well to allow Linux Mint 17.2 to behave as though it is Ubuntu 14.04 (since they share a package base). Thoughts @DamianEdwards? This would not be a formal declaration of support, just kinda like we do with Mono: "It should work, but no formal guarantees"

**Comment by dougbu** [comment]
FYI on my up-to-date Mint system:
```
> dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-15775
 Type:         CoreClr
 Architecture: x64
 OS Name:      Linux
 OS Version:   LinuxMint 17.2
 Runtime Id:   linux.LinuxMint 17.2-x64
> uname -a
Linux GarnetAv6 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
>  cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
> cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by anurse** [comment]
:+1: thanks

**Comment by anurse** [comment]
Maybe should consider using `os-release` for distro reporting. It's possible it's closer to what we're looking for. As far as I can tell it is fairly ubiquitous (like `lsb-release`)

**Comment by moozzyk** [comment]
`lsb-release` may not actually exist on redhat-based distros. We [kind-of](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Mono/EntryPoint.cs#L242 use it) to detect CentOs but we don't have this in the native code yet. If os-release always exists on Ubuntu 14.04 and (have the expected values) then we could use it instead of `lsb-release` but it's not beta-8

**Comment by anurse** [comment]
Agree entirely on the timing, changing to `os-release` would be for RC at least.

**Comment by anurse** [comment]
As far as I could tell, `os-release` definitely exists on Fedora.

**Comment by jstclair** [comment]
`/etc/lsb-release` also does not exist on recent `debian` releases (which are the base for most Docker images). Found this out when updating my Docker image - `dnx` no longer runs.

**Comment by moozzyk** [comment]
@jstclair https://github.com/aspnet/dnx/commit/097c7e55a6ddc6b13831949c86a9633f71714387#diff-f79c267a7f222c20dba5339e1498a6d3R231

**Comment by ctaggart** [comment]
I'm using a Debian based Docker container and have the same issue as @jstclair.

```
root@36924f4b977f:/opt/visualfsharp/src/fsharp/FSharp.Core# dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-beta7          coreclr x64          linux           
       1.0.0-beta7          mono                 linux/osx       
       1.0.0-rc1-15838      coreclr x64          linux           default
       1.0.0-rc1-15838      mono                 linux/osx       

root@36924f4b977f:/opt/visualfsharp/src/fsharp/FSharp.Core# dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-beta7-15532
 Type:         CoreCLR
 Architecture: x64
 OS Name:      Linux

root@36924f4b977f:/opt/visualfsharp/src/fsharp/FSharp.Core# dnvm use 1.0.0-rc1-15838 -r coreclr -arch x64
Adding /opt/dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-15838/bin to process PATH
root@36924f4b977f:/opt/visualfsharp/src/fsharp/FSharp.Core# dnx --version
Could not open /etc/lsb_release. OS version will default to the empty string.
```

**Comment by moozzyk** [comment]
@ctaggart  097c7e5 #diff-f79c267a7f222c20dba5339e1498a6d3R231 - we know should be using `/etc/os-release` - maybe the build is not out yet?

**Comment by jstclair** [comment]
Great! Do we need to use a custom DNX_UNSTABLE_FEED for that? Otherwise, when I try the default feed, I get "1.0.0-rc1-15838" for coreclr/linux, which I had tested previously.

**Comment by jeremymeng** [comment]
Is dnu/dnx supported on Debian (jessie)? One of our customers is getting the following errors when running beta8 `dnu help`.
```
Could not open /etc/lsb_release. OS version will default to the empty string.
```
His machine doesn't have either `/etc/lsb-release` or `/etc/os-release`.

There's also posts mentioning that the file `/etc/lsb-release` is not required by the Linux Standard Base, the command `lsb_release` is.

**Comment by jstclair** [comment]
@jeremymeng 
I believe the `/etc/os-release` is contained in the package `base-files`; can you check if that's installed?

As far as the fix for the missing `lsb_release` - I think that's in a post-beta8 release.

**Comment by anurse** [comment]
I have `/etc/os-release` on the Debian jessie docker image. Strange that it would have been removed. DNX does depend on this to install the correct packages. Even so, unfortunately base Debian is not supported at this time, only Ubuntu 14.04. One of the packages the CoreCLR depends on, libicu, varies it's binary interface by version and different distros run different versions so it's difficult to create a single binary that works on all distros.

**Comment by jstclair** [comment]
@anurse I understand, but I think that decision is a bit at-odds with the ASPNET Docker group, and the existing documentation about running CoreClr/DNX on Linux. Are there any issues or announcements on  Ubuntu-only platform support?

**Comment by anurse** [comment]
I don't know where the officially-supported distros are published, @DamianEdwards or @danroth27 might. Debian Jessie **should** work in general, which is why the Docker image uses it (to reduce the size of the image), but I know that CoreCLR only provides packages for Ubuntu 14.04 at the moment (I believe they are expanding to CentOS soon) and doesn't test on raw Debian so we're somewhat limited in what we can officially support there.

These decisions are still very much up-in-the-air though, so the documentation is still a little rough. We'll be clarifying and fine-tuning the documentation as we move towards RTM.

**Comment by jeremymeng** [comment]
Circling back.  The missing /etc/lsb-release just prints out an error message, what our customer missing is the `libicu` dependency.  Even he already has `libicu-devtools` installed, somehow the `libicu52` dependency was missing on his machine.  After he installed that, `dnu` works on his Debian Jessie machine.

Is there a list of dependencies and compatible versions?

**Comment by jstclair** [comment]
There is a list of required packages [here](http://docs.asp.net/en/latest/getting-started/installing-on-linux.html#install-the-net-execution-environment-dnx) but it's a bit unclear which particular versions are required.
