### ISSUE TITLE
dnu restore fails on latest 1.0.0-beta8-15618 

### ISSUE THREAD

**Issue by ellismg** [aspnet/dnx#2784]
Via (@ahmetabdi) [here](https://github.com/dotnet/coreclr/issues/1599).

```
dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-beta4          mono                 linux/osx
       1.0.0-beta6          mono                 linux/osx
       1.0.0-beta7          mono                 linux/osx
       1.0.0-beta8-15618    coreclr x64          darwin
  *    1.0.0-beta8-15618    mono                 linux/osx       default
```

```
dnu restore
bash: /Users/foo/.dnx/runtimes/dnx-mono.1.0.0-beta8-15618/bin/dnu: Permission denied
```

Same happends on coreclr x64

**Comment by BrennanConroy** [comment]
They are using an old version of dnvm most likely. Upgrade dnvm and reinstall the dnx

**Comment by ahmetabdi** [comment]
I fixed by chmod 777 the dnu bin

**Comment by davidfowl** [comment]
@BrennanConroy write the 3 lines of code that @ahmetabdi should do

**Comment by BrennanConroy** [comment]
Run ```dnvm update-self``` then ```dnvm install 1.0.0-beta8-15618 -f``` to reinstall the "bad" dnx. If the update-self doesn't work its possible you got a broken build of dnvm in which case you should delete it and reinstall following the instructions at https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md#get-dnvm
