### ISSUE TITLE
Remove Configuration from IApplicationEnvironment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2788]
It's a compilation specific concept so we should expose it via Microsoft.Dnx.Compilation.Abstractions

/cc @pranavkm @anurse

**Comment by anurse** [comment]
:+1:

**Comment by muratg** [comment]
@davidfowl I don't think this is for RC1.  Moving out.  Bring it back if necessary.

**Comment by muratg** [comment]
Assigned to @pakrym 

FYI @davidfowl

**Comment by muratg** [comment]
cc @pranavkm this is related to Razor compilation.

**Comment by pranavkm** [comment]
:+1:

**Comment by pakrym** [comment]
https://github.com/aspnet/Mvc/pull/3632
