### ISSUE TITLE
Integrate DTH integration test infrastructure into Microsoft.Dnx.Testing.CommonUtils

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2789]

**Comment by muratg** [comment]
Looks like you already have a PR out for this.  If it looks like you'll be able to check in we'll put this in beta 8 otherwise RC1 is fine.

**Comment by anurse** [comment]
Actually this is different, this is merging the DTH functional test tools into the common test framework. The existing PR is just for converting DTH tests to use the common framework as well as the DTH tools.

**Comment by muratg** [comment]
:+1:
