### ISSUE TITLE
Where is 'Microsoft.Dnx.Host.Clr.EntryPoint' type?!

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2790]
After update the runtime to 1.0.0-beta8-15653 I encourage with this error when run my application on IIS: 
`Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/70

**Comment by tstar** [comment]
And how to run the project in IIS Express now? Any ideas?

**Comment by davidfowl** [comment]
Wait until beta8 ships or downgrade your runtime

**Comment by mikeandersun** [comment]
@davidfowl  I use beta8 nightly builds,why can't run? What you means "wait until beta8 ships"?

**Comment by davidfowl** [comment]
beta8 nightly builds will not work on IIS express anymore. There are several changes that we are working on to make it work again. If you read the link I sent you'll see we're making changes to the IIS hosting model. As a result, IIS express will be broken.

When I said wait until beta8 ships, I mean is released and complete. Using ci builds will get you in a broken state sometimes, this is one of those times. You cannot use IIS express without some very manual steps at this point. By the time we're done with beta8 it will work smoothly again.

**Comment by mikeandersun** [comment]
I can use web OR Kestrel command to run my web application for now. Am I correct?

**Comment by davidfowl** [comment]
Yep

**Comment by mikeandersun** [comment]
I have this code in my startup.cs file :
`  services.Configure<OpenIdConnectOptions>(options =>
            {
                  options.SignInScheme = "Cookies";
             });`
with web or Kestrel  commands i get an `method ...` . But by commenting the code it run fine with web command and with Kestrel `Can't load libuv`

**Comment by davidfowl** [comment]
Try updating your packages.

**Comment by tstar** [comment]
I can not run the project with web command. If I run the project from the studio, I only see a black window, which immediately closes. If I run the project from the command line in root project folder, then I get an exception: System.InvalidOperationException: Unable to resolve project from C:\Test. If I publish project to the folder and run web.cmd, then I get an exception: System.InvalidOperationException: This application requires DNX version 1.0.0-beta8-15665 or newer to run. But now latest DNX version only is 1.0.0-beta8-15654. What's happening?

**Comment by davidfowl** [comment]
What does your project.json look like?

**Comment by davidfowl** [comment]
and what feeds are you using.

**Comment by tstar** [comment]
.NET Version Manager v1.0.0-beta8-15518
Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2

**Comment by tstar** [comment]
My project.json file is very large. Can I publish it here entirely?

**Comment by tstar** [comment]
I find this line in the file that refer to the version 15665:
      "Microsoft.AspNet.DataProtection.Abstractions/1.0.0-beta8-15617": {
        "type": "package",
        "dependencies": {
          "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta8-15665"
        },

**Comment by mikeandersun** [comment]
[Here](https://github.com/OrchardCMS/Brochard/issues/43) is the same issue

**Comment by mikeandersun** [comment]
I have the same issue and here is my project.json :
{
  "authors": [
        "me"
    ],
    "commands": {
        "web": "Microsoft.AspNet.Hosting --ASPNET_ENV development --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:49102",
        "WebListener": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:49102",
        "Kestrel": "Microsoft.AspNet.Server.Kestrel --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:49102",
        "run": "run server.urls=http://localhost:49102"

    },
    "dependencies": {
        "Controllers": "1.0.0-*",
        "EntityFramework": "1.0.0-*",
        "Services": "1.0.0-*",

        "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
        "Microsoft.Net.Http.Server": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "EntityFramework.Commands": "7.0.0-*",
        "Microsoft.AspNet.Mvc.Razor": "6.0.0-*",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-*",
        "Microsoft.Framework.Logging": "1.0.0-*",
        "Microsoft.Framework.Logging.Console": "1.0.0-*",
        "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*",
        "Microsoft.IdentityModel.Protocols.OpenIdConnect": "2.0.0-*",
        "Microsoft.IdentityModel.Protocols": "2.0.0-*",
        "System.IdentityModel.Tokens": "5.0.0-*",
        "System.IdentityModel.Tokens.Jwt": "5.0.0-*",
        "System.Net.Http": "4.0.1-beta-23302",
        "Microsoft.Framework.OptionsModel": "1.0.0-*"

    },
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components",
        "grunt"
    ],
    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Security.Cryptography.X509Certificates": "4.0.0-beta-*"
            }
        }

    },
    "publishExclude": [
        "bower.json",
        "package.json",
        "gruntfile.js",
        "grunt",
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "version": "1.0.0-*",
    "webroot": "wwwroot"
}
