### ISSUE TITLE
dnxw.exe: DNX loader sibling that starts without spawning a console.

### ISSUE THREAD

**Issue by prasannavl** [aspnet/dnx#2791]
DNX loader, while designed primarily for the server applications, can very well be used with WPF/WinForms or just plain background tasks. But DNX always spawns up a console (i.e, it never uses the Win32 class directly which will not create a console window). Provide a switch to suppress the console in supported platforms where a console may be hidden optionally or never created in the first place (in case of Win32).

This is particularly useful for background automation tasks.

**Comment by muratg** [comment]
This would require some architectural changes which are not straightforward. Not something we can realistically get in V1. Putting it in the backlog.

**Comment by davidfowl** [comment]
Actually sounds like it would be a good pill request. Let's make this up for grabs

**Comment by anurse** [comment]
One side note before unleashing the world on it :). As far as I know, the only way to achieve this right now is to build a separate `dnx.exe` that is marked as a Windows Application instead of a Console Application. That's certainly how Java handled it (`java` vs `javaw`). If that's the case, we'd want to discuss this further before accepting a PR.

Feel free to explore the options and get back to us though :)

**Comment by prasannavl** [comment]
@anurse - just thinking out loud here - would having dnx.exe as a Win32 application attaching itself to a console with AttachConsole manually for console applications be completely crazy - I'm a little unsure on the consequences of the internal dynamics to figure out it its a clean way to do it.

**Comment by davidfowl** [comment]
dnxw.exe

**Comment by anurse** [comment]
@prasannavl If that model works everywhere, it would probably be ok. My initial concern would be Nano Server where most of the Win32 APIs are gone.

@davidfowl If we have to... I guess :)

**Comment by prasannavl** [comment]
On second thought it does seem like `dnxw` would make life easier in all aspects. Intent would be much clearer, straight forward and well, less typing for quick invocations! :)

**Comment by anurse** [comment]
My only concern is that I've never been a big fan of `javaw` because it creates confusion (which do I use and why?). If it's the only way to get it to work, then maybe we'll have to go that way.
