### ISSUE TITLE
Change usage of "darwin" in package names/etc. to "osx"

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2792]
The CLR team has decided on using `osx` as the name for the OS in Mac OS X platform-specific packages. We previously used `darwin` for this purpose, for example `dnx-coreclr-darwin-x64`. We should probably get in sync with them and change our names to match. Here is an incomplete list of places I can think of, please feel free to add more!
- [ ] DNX package name should be `dnx-coreclr-osx.10.10-x64`
- [ ] DNX RIDs should be `osx.10.10-x64` (I believe this may be already done? @moozzyk)
- [ ] OS parameters on DNVM/DNU/etc. should accept BOTH `darwin` and `osx`
- [ ] Almost definitely more...

/cc @muratg (this can go in RC), @davidfowl @moozzyk @BrennanConroy

**Comment by BrennanConroy** [comment]
DNVM already accepts both, we'll just have to invert the behavior of changing osx to darwin

**Comment by davidfowl** [comment]
Ugh renames

**Comment by muratg** [comment]
@davidfowl You think we should get CoreCLR to use "Darwin" instead?

cc @Eilon

**Comment by Eilon** [comment]
`osx` seems like the more user-friendly one. Not sure which is more correct though.

**Comment by anurse** [comment]
We picked `darwin` because it tends to be more common:

* `https://static.rust-lang.org/dist/rust-1.3.0-i686-apple-darwin.tar.gz`
* `https://nodejs.org/dist/v4.1.1/node-v4.1.1-darwin-x64.tar.gz`
* `https://storage.googleapis.com/golang/go1.5.1.darwin-amd64.pkg`

And it matches the value returned by `uname`.

Having said that, I'd rather just align with the CLR team, so if they have a reason for picking `osx` (user-friendliness, etc.), I don't really mind :)

**Comment by muratg** [comment]
OK, let's go with Andrew's suggestions unless anyone has strong objections. Putting this in RC1.
