### ISSUE TITLE
dnu restore with encrypted packageSourceCredentials in NuGet.config throws System.NotImplementedException

### ISSUE THREAD

**Issue by dagood** [aspnet/dnx#2796]
When restoring from a simple project.json, if I have an encrypted `packageSourceCredentials` entry on a used feed a `System.NotImplementedException` is thrown:
```
Microsoft .NET Development Utility CoreCLR-x86-1.0.0-beta7-15532

----------
System.NotImplementedException: The method or operation is not implemented.
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at NuGet.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.PackageSourceProvider.ReadCredential(String sourceName)
   at NuGet.PackageSourceProvider.<>c__DisplayClass14_0.<LoadPackageSources>b__1(SettingValue p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageSourceProvider.LoadPackageSources()
   at Microsoft.Dnx.Tooling.PackageSourceUtils.GetEffectivePackageSources(IPackageSourceProvider sourceProvider, IEnumerable`1 sources, IEnumerable`1 fallbackSources)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
The method or operation is not implemented.
```

### Repro
This is where I got the package: https://www.nuget.org/packages/dnx-coreclr-win-x86/1.0.0-beta7

My NuGet.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <NuGet>
      <add key="Username" value="username" />
      <add key="Password" value="password" />
    </NuGet>
  </packageSourceCredentials>
</configuration>
```

My project.json:
```
{
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.Dnx.Runtime" : "1.0.0-*"
    }
}
```

The command: `bin\dnu.cmd restore project.json`

### Workarounds
The command succeeds if I use a plaintext password, like this:
`<add key="ClearTextPassword" value="password" />`

If I change `<NuGet>` to something that doesn't match a feed, the command succeeds. (But of course the credentials aren't used.)

### Root cause
[`ProtectedData.Unprotect` is shimmed](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Shims/ProtectedData.cs) with a `NotImplementedException`, and [decrypting the password calls it](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/NuGet/Core/PackageSource/PackageSourceProvider.cs#L155).

**Comment by davidfowl** [comment]
Unrelated:   You shouldn't be depending on `Microsoft.Dnx.Runtime`. Secondly, yes it's a know problem there's no DPAPI on CoreCLR

**Comment by dagood** [comment]
Didn't know that, thanks. I just trimmed a (possibly old) random project.json for the sake of an example.

**Comment by muratg** [comment]
Thanks @dagood.  Closing this one as this is not supported on CoreCLR as of yet.

**Comment by ericstj** [comment]
AFAIK we aren't going to be adding support for that API on CoreCLR /cc @bartonjs.  Even so, the source of this exception is a stub in your own code that throws the NotImplementedException, it isn't coming from any crypto package.

You shouldn't be crashing due to something valid in someone's nuget.config which is ambient state on the user's machine.  If you can't handle it you need to either ignore it or emit an intelligible error message.  As it is a regular user would have no clue that something put in their nuget.config file from nuget.exe SetApiKey was causing their DNX projects to fail to build.

**Comment by davidfowl** [comment]
@ericstj we opted to throw that exception during the initial port because we didn't want to fake it.

> emit an intelligible error message. As it is a regular user would have no clue that something put in their nuget.config file from nuget.exe SetApiKey was causing their DNX projects to fail to build.

Sure. This is just old crusty code that hasn't been touched in a long time. As we end up using more NuGet3 API this will all go away.
