### ISSUE TITLE
Stop publishing unnecessary packages

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnx#2797]
We don't need to publish packages like Microsoft.Dnx, we should get a list of all the unneeded ones and stop publishing them on the CI.

**Comment by ajaybhargavb** [comment]
We might need this to be done before enabling NuGetPackageVerifier in dnx. cc' @Eilon

**Comment by Eilon** [comment]
We could do it in either sequence - I'm fine either way.
