### ISSUE TITLE
Expose the project, the project reader and the lock file reader from runtime

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2800]
Because we don't ship Microsoft.Dnx.Runtime, no one outside of the Dnx can consume our readers.
We need this for things like the dnx watch

**Comment by muratg** [comment]
Good point, though not sure if we want to have a supported API like that or not.  cc @davidfowl 

Also, does this mean that we'll need to ship `Microsoft.Dnx.Runtime` for Beta 8?  cc @danroth27

**Comment by davidfowl** [comment]
We do just not right now. It needs design.

**Comment by anurse** [comment]
At most we would ship a separate package for project/lock file reading and that needs design. For now, `dnx-watch` could copy code (though of course that is a little brittle).
