### ISSUE TITLE
Cannot use System.Xml.XmlDocument

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#2803]
Using dnx451 and dnxcore50 I cannot use XDocument at all.

Whenever I reference "System.Xml.XDocument" I get 1000+ errors in the project, System.Object cannot be found, and multiple dual references such as:

Severity	Code	Description	Project	File	Line
Error	CS0433	The type 'IEnumerable<T>' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	xxx 4.5.1	

I'm on beta7. I've tried referencing it only in dnx451 and in the normal error, I've tried loads of different versions of the Xml reference and none work.

**Comment by NickCraver** [comment]
Can you post your `project.json` file?

**Comment by angelsix** [comment]
{
  "version": "1.0.0-beta7",
  "description": "Class Library",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.Framework.DependencyInjection": "1.0.0-beta7",
    "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta7",
    "System.Xml.XDocument": "4.0.11-beta-*"
  },

  "frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
    }
  }
}

**Comment by anurse** [comment]
`System.Xml.XDocument 4.0.11` requires `net46` or higher. You need to reference `System.Xml.XDocument 4.0.0` in your `dnx451` target.

**Comment by angelsix** [comment]
I reference 4.0.0 and I get the exclamation stating System.Xml is Not Availabel in 451, but only in core 5.0

**Comment by angelsix** [comment]
Found fix here: http://stackoverflow.com/questions/32004649/asp-net-vnext-and-xdocument

  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Xml": "4.0.0.0",
        "System.Xml.Linq": "4.0.0.0"

      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Xml.XDocument": "4.0.10"

      }
    }
  },
