### ISSUE TITLE
Detecting linux

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#2806]
Is there a compiler switch or any way to detect when compiling/running on a linux system?

**Comment by victorhurdugaci** [comment]
Yes, use [IRuntimeEnvironment](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime.Abstractions/IRuntimeEnvironment.cs).

Here's how to obtain an instance of it: https://github.com/aspnet/UserSecrets/blob/dev/src/Microsoft.Framework.SecretManager/Program.cs#L23

Here's how to use it: https://github.com/aspnet/UserSecrets/blob/dev/src/Microsoft.Framework.SecretManager/CommandOutputProvider.cs#L16

**Comment by muratg** [comment]
@angelsix Let us know if you have other questions on this. Otherwise, this should be good to close :)

**Comment by angelsix** [comment]
That did the trick thanks
