### ISSUE TITLE
Linux without Mono

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#2814]
I figured considering the whole point of the dnx is to be a cross platform framework that I could use dnx50 on linux.

However, I always have to build with Mono and it then uses the mono runtime in dnvm and not coreclr.

Am I doing something wrong or can Linux not run dnx yet only through mono?

**Comment by muratg** [comment]
Are you setting your default DNX to be a coreclr based one?  You should definitely be able to run with coreclr, not sure exactly what problem you're hitting.

**Comment by moozzyk** [comment]
If you want to build the dnx repo you have to use Mono. If you want just to run your app you can don't need Mono if you decide to go only with CoreClr.

**Comment by angelsix** [comment]
Ok so I have to run the dnu restore on another machine, move the compiled program over (which folders would that be? I have a web and a class library).

Then presumably run dnx kestrel on the linux side to start the server.

As when I run dnu restore on the linux side with coreclr runtime selected in dnvm I get:

  *    1.0.0-beta7          coreclr x64          linux           
/home/user/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta7/bin/dnu: line 12: /home/user/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta7/bin/dnx: cannot execute binary file: Exec format error

**Comment by moozzyk** [comment]
No. If you want to build **your** application  (and not the dnx repo) you should be able to do this with just CoreClr. If you want to publish your app so that it can be used on a different machine you need to use the `dnu publish` command which allows you to provide what runtime you want to use on this machine.

**Comment by angelsix** [comment]
Ok so on linux, with dnx50 as the framework, and coreclr selected as shown above. I get this error when running dnu restore. Tried it on 4 linux machines, ARM, x86, 32bit, 64bit, all the same.
 
/home/user/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta7/bin/dnu: line 12: /home/user/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta7/bin/dnx: cannot execute binary file: Exec format error

**Comment by angelsix** [comment]
Oops turns out all machines I was testing on (even 64bit ones) I installed 32bit linux. 

Looks like the issue is coreCLR isnt on 32bit. Is it planned to be? If so any ideas when? I would love to drop mono if possible

**Comment by muratg** [comment]
Currently CoreCLR is only 64 bits on Linux and OS X.  Not sure if they plan to have 32 bit support.

**Comment by muratg** [comment]
@angelsix closing this one. Let us know if you have problems with a 64 bit linux when you try it out.
