### ISSUE TITLE
This application requires DNX version 1.0.0-beta8-15665 or newer to run. But now latest DNX version only is 1.0.0-beta8-15654. What's happening?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnx#2824]
System.InvalidOperationException: This application requires DNX version 1.0.0-beta8-15665 or newer to run. But now latest DNX version only is 1.0.0-beta8-15654. What's happening?
This is my project.json :
{
"authors": [
"me"
],
"commands": {
"web": "Microsoft.AspNet.Hosting --ASPNET_ENV development --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:49102",
"WebListener": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:49102",
"Kestrel": "Microsoft.AspNet.Server.Kestrel --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:49102",
"run": "run server.urls=http://localhost:49102"

},
"dependencies": {
    "Controllers": "1.0.0-*",
    "EntityFramework": "1.0.0-*",
    "Services": "1.0.0-*",

    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
    "Microsoft.Net.Http.Server": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "EntityFramework.Commands": "7.0.0-*",
    "Microsoft.AspNet.Mvc.Razor": "6.0.0-*",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-*",
    "Microsoft.Framework.Logging": "1.0.0-*",
    "Microsoft.Framework.Logging.Console": "1.0.0-*",
    "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*",
    "Microsoft.IdentityModel.Protocols.OpenIdConnect": "2.0.0-*",
    "Microsoft.IdentityModel.Protocols": "2.0.0-*",
    "System.IdentityModel.Tokens": "5.0.0-*",
    "System.IdentityModel.Tokens.Jwt": "5.0.0-*",
    "System.Net.Http": "4.0.1-beta-23302",
    "Microsoft.Framework.OptionsModel": "1.0.0-*"

},
"exclude": [
    "wwwroot",
    "node_modules",
    "bower_components",
    "grunt"
],
"frameworks": {
    "dnx451": { },
    "dnxcore50": {
        "dependencies": {
            "System.Security.Cryptography.X509Certificates": "4.0.0-beta-*"
        }
    }

},
"publishExclude": [
    "bower.json",
    "package.json",
    "gruntfile.js",
    "grunt",
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
],
"version": "1.0.0-*",
"webroot": "wwwroot"
}

**Comment by BrennanConroy** [comment]
You are using the aspnetci feed packages with a vnext feed dnx. Either read this https://github.com/aspnet/Announcements/issues/68 and work around it or use the same feed for packages and dnx

**Comment by mikeandersun** [comment]
Where is  aspnetci feed?!
And how to i can use next feed only?

**Comment by BrennanConroy** [comment]
Look at your nuget.configs

**Comment by tstar** [comment]
I solved this problem. At first, I manually set all of the packages in project.json file as "-beta7" and restore packages. Then switched nuget feed to "https://www.myget.org/F/aspnetvnext/api/v2/" and update all packages to the latest version in this feed. Now I can run my project with the latest DNX version 1.0.0-beta8-15654 on WebListener or Kestrel servers.

**Comment by tstar** [comment]
Is it posible to get latest DNX version 1.0.0-beta 8-15665 or newer to be in trend?

**Comment by victorhurdugaci** [comment]
@tstar  yes, it is possible:

```
SET DNX_FEED=https://myget.org/F/aspnetcidev/api/v2
dnvm upgrade
```

**Comment by BrennanConroy** [comment]
Not recommended. You should be using vnext feed only for unstable bits

**Comment by mikeandersun** [comment]
@tstar  I did tried  https://myget.org/F/aspnetcidev/api/v2 feed. But there was many issues. 
I recommended to wait for next builds come from **anpnetvnext**  feed. See [this](https://github.com/aspnet/Home/issues/952)
