### ISSUE TITLE
Question: should project compile before (defined) command is invoked?

### ISSUE THREAD

**Issue by per-samuelsson** [aspnet/dnx#2828]
Hi,

Can I just line-check something? Consider a project `Foo` in `src\Foo`, referencing some project `Bar`. Foo contains just some random .cs file. Bar is a project with an entrypoint.

In `src\Foo\project.json` I have:
```
{
    "version": "0.1.0",
    "dependencies": {
      "Bar": "1.0.0"
    },
    "commands": {
      "run": "Foo",
      "runBar": "Bar"
    },
    "frameworks": {
        "dnxcore50": {
            "dependencies": {  }
        }
    }
}
```

Then do
```
cd src\Foo
dnx runBar
```

As a novice, I would expect Foo to compile, just as it does if I run `dnx run`. But apparently, it doesn't. That by design?

(Yes, doing `dnx run` actually *consume* Foo, invoking its entrypoint. But still).

**Comment by muratg** [comment]
Sorry can you clarify "I would expect Foo to compile"?

**Comment by per-samuelsson** [comment]
> Sorry can you clarify "I would expect Foo to compile"?

Sure. I can expand to a full sample:

**src\Foo\project.json**
```json
{
    "version": "0.1.0",
    "dependencies": {
      "Bar": "1.0.0"
    },
    "commands": {
      "run": "Foo",
      "runBar": "Bar"
    },
    "frameworks": {
        "dnxcore50": {
            "dependencies": {  }
        }
    }
}
```

**src\Foo\Program.cs**
```C#
static class Program {
  static void Main() {
    Console.WriteLine("Hello from Foo");
  }
}
```

Doing `src\Foo\dnx run` will compile `Program.cs` and invoke the entrypoint. The output is "Hello from Foo". Doing `src\Foo\dnx runBar` invokes the entrypoint of the referenced Bar project, which is what it should do. But it doesnt compile `Foo\Program.cs` first.

**Comment by muratg** [comment]
Do you mean it's not invoking `Foo\Program.cs`'s `Main` (i.e. not displaying the "Hello from Foo" message) when you do `dnx runBar`?  If so, that's by design.

**Comment by muratg** [comment]
BTW, one of the [principles](https://github.com/aspnet/dnx/blob/dev/README.md#principles) in DNX design is to "blur the lines between compilation and loading."  :)

**Comment by anurse** [comment]
Compilation only occurs before the first time an assembly is loaded. So if `runBar` never needs to load anything out of Foo, it never compiles it. Calling `Assembly.Load` on `Foo` would force a compilation.

**Comment by per-samuelsson** [comment]
> Do you mean it's not invoking Foo\Program.cs's Main (i.e. not displaying the "Hello from Foo" message) when you do dnx runBar? If so, that's by design.

No, I didn't mean that. That I totally understand.

> Compilation only occurs before the first time an assembly is loaded. So if runBar never needs to load anything out of Foo, it never compiles it. Calling Assembly.Load on Foo would force a compilation.

OK, thanks. I kind of suspected that, but I wish it wasn't like that, for our case, hence I asked. We have to figure something out then. I need to consider a bit more our options. Thanks for the feedback!

**Comment by per-samuelsson** [comment]
> Calling `Assembly.Load` on `Foo` would force a compilation.

@anurse 

Sorry if I'm bringing pain, but that statement got me thinking and I can't really let it go. Can you expand a bit on that at some time? 

Basically, what I'm wondering is how a case would look where doing a `Assembly.Load` could target a *project* (i.e. one that will be compiled)? What kind of `AssemblyName` would I pass for that?

I tried studying code in `corefx` to find out myself, but I just can't get it... :cry:

**Comment by davidfowl** [comment]
It's not the CoreFX code, the code is in DNX: 
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/Loader/ProjectAssemblyLoader.cs

The name you pass to Load is the name of the project. It's no different to compiling up front. Instead it's deferred to runtime.

**Comment by per-samuelsson** [comment]
> The name you pass to Load is the name of the project. It's no different to compiling up front. Instead it's deferred to runtime.

Ah, ok, that makes sense. I did look at that code some time ago, but the reference to `Assembly.Load` got me thinking it was the good old reflection thingy. I'll give the project assembly loader some more time to try figuring it all out. Thanks for all the help!

**Comment by per-samuelsson** [comment]
> The name you pass to Load is the name of the project. It's no different to compiling up front. Instead it's deferred to runtime.

Just got the chance to test this some more. It works like a charm, and *wow*, that feature is just totally super! Using this really fills me up with love (even more) of what you're doing here. Just thought I'd share that, being friday and all. :dancer: :+1: :wine_glass: Keep it up!
