### ISSUE TITLE
Do not stop DNX executing when application's lock file is invalid.

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2831]
/cc @davidfowl

**Comment by troydai** [comment]
/cc @muratg 
Probably won't make into beta8

**Comment by davidfowl** [comment]
@muratg @troydai I think we should do some of this for beta8.

**Comment by muratg** [comment]
@davidfowl after branching?  I think Troy will be busy today with the DTH bug and we should be branching pretty soon.

**Comment by muratg** [comment]
FYI @Eilon @danroth27

**Comment by davidfowl** [comment]
Assigning to myself.
