### ISSUE TITLE
Option -v (verbose) is ignored in Microsoft.Dnx.Tooling

### ISSUE THREAD

**Issue by pgrudzien12** [aspnet/dnx#2838]
As for now -v option is ignored thus Microsoft.Dnx.Tooling.ReportsFactory.CreateReports creates Reports object with Verbose always set to Reports.Constants.NullReport.

Example: dnx -v wrap does not output any additional information as it should (for example msbuild output).  

Cause: In Microsoft.Dnx.Tooling.Program current flow is:
1. Create new CommandLineApplication
2. Create CommandOption by callint app.Option - this creates option but not parses it
4. optionVerbose.HasValue() is called which is suppose to check if -v is present thus returning always false
5. ReportFactory is created with the value acquired from optionVerbose.HasValue()
[...]
6. app.Execute is called which parses command line arguments
7. Actual command invoked

Proposed solution (1):
Divide app.Execute into two parts
1. Parse arguments
2. Invoke command

Then add 1a. step to set verbosity on ReportFactory.
+ as extra refactoring - my proposition is to instead of returning execution error code, return just Func<int> to invoke by caller (empty one if help was displayed)
Upside: solve problem and separates responsibilities of invoking and parsing args from Execute method
Downsides I see: it would require changes in all dependent projects where Execute is used (four of them + tests) 

What do you think?

BTW: I'd be more than happy to help you with this issue as my first pull request.

**Comment by davidfowl** [comment]
It's been fixed by @anurse

**Comment by pgrudzien12** [comment]
Shame :D
