### ISSUE TITLE
Error while running `dnu restore`

### ISSUE THREAD

**Issue by sahilbabbar** [aspnet/dnx#2839]
After successfully executing the following commands:
> curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
> dnvm
> dnvm upgrade -r coreclr
> dnvm upgrade
> npm install -g yo
> yo aspnet
> dnu restore
> dnx kestrel
> dnvm upgrade -r mono
> dnu restore

```dnu restore``` gave an error:
> /Users/<user-name>/.dnx/runtimes/dnx-mono.1.0.0-beta7/bin/dnx: line 14: exec: mono: not found

**Comment by sahilbabbar** [comment]
I didn't install ```mono``` so it is the probable reason?

**Comment by davidfowl** [comment]
Yes. Check out the getting started docs. http://docs.asp.net/en/latest/getting-started/index.html
