### ISSUE TITLE
Error while running 'kestrel'

### ISSUE THREAD

**Issue by sahilbabbar** [aspnet/dnx#2841]
After successfully building the project, the `dnu kestrel` command in not working. The error output is:

> System.TypeInitializationException: An exception was thrown by the type initializer for HttpApi ---> System.DllNotFoundException: httpapi.dll
>   at (wrapper managed-to-native) Microsoft.Net.Http.Server.UnsafeNclNativeMethods/HttpApi:HttpInitialize (Microsoft.Net.Http.Server.UnsafeNclNativeMethods/HttpApi/HTTPAPI_VERSION,uint,void_)
>   at Microsoft.Net.Http.Server.UnsafeNclNativeMethods+HttpApi.InitHttpApi (UInt16 majorVersion, UInt16 minorVersion) [0x00000] in <filename unknown>:0 
>   at Microsoft.Net.Http.Server.UnsafeNclNativeMethods+HttpApi..cctor () [0x00000] in <filename unknown>:0 
>   --- End of inner exception stack trace ---
>   at Microsoft.Net.Http.Server.WebListener..ctor (ILoggerFactory factory) [0x00000] in <filename unknown>:0 
>   at Microsoft.AspNet.Server.WebListener.ServerFactory.Initialize (IConfiguration configuration) [0x00000] in <filename unknown>:0 
>   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication () [0x00000] in <filename unknown>:0 
>   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start () [0x00000] in <filename unknown>:0 
>   at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
>   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
>   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0 
>   at Microsoft.Dnx.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
>   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
>   at Microsoft.Dnx.Host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env, System.Runtime.Versioning.FrameworkName targetFramework) [0x00000] in <filename unknown>:0 
> System.DllNotFoundException: httpapi.dll
>   at (wrapper managed-to-native) Microsoft.Net.Http.Server.UnsafeNclNativeMethods/HttpApi:HttpInitialize (Microsoft.Net.Http.Server.UnsafeNclNativeMethods/HttpApi/HTTPAPI_VERSION,uint,void_)
>   at Microsoft.Net.Http.Server.UnsafeNclNativeMethods+HttpApi.InitHttpApi (UInt16 majorVersion, UInt16 minorVersion) [0x00000] in <filename unknown>:0 
>   at Microsoft.Net.Http.Server.UnsafeNclNativeMethods+HttpApi..cctor () [0x00000] in <filename unknown>:0

**Comment by davidfowl** [comment]
That doesn't look like kestrel at all.
