### ISSUE TITLE
Running dnx:dnu restore command on Visual Studio code gives me an error C:/Users/neha is not recognized as an internal or external command.My username has a space.

### ISSUE THREAD

**Issue by nehaabrol87** [aspnet/dnx#2844]
Running dnx:dnu restore command on Visual Studio code gives me an error C:/Users/neha is not recognized as an internal or external command.My username has a space.

I have tried installing/re-installing but I get the same error.

 C:/Users/neha is not recognized as an internal or external command.

My username has a space.I am not sure if that is the problem.Any help would be much appreciated.

**Comment by muratg** [comment]
@nehaabrol87 What's the DNX version you've installed?

**Comment by nehaabrol87** [comment]
1.0.0-beta7

**Comment by nehaabrol87** [comment]
@muratg  I created a new user C:/Users/neha_000 and installed and it is working fine with the same version so I think it is an issue with the space only.Not sure.Let me know if you need anything else.

**Comment by amirv92** [comment]
same problem. running rc1.
