### ISSUE TITLE
Consider downgrading lock file validation errors to warnings

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2849]
It's an error if the lock file doesn't exist but if it's out of sync with the dependencies, we can downgrade that to a warning.

Related to #2831

/cc @anurse @lodejard @glennc

**Comment by lodejard** [comment]
Did something change that made it safer to run in this case? Or is it that VS is getting better at running restore when needed, so problems happen less often when using the tooling?

**Comment by davidfowl** [comment]
VS can trigger a restore based on the diagnostic messages we return from DTH. The big change from before is the fact that the lock file is the source of truth so it means that instead of things failing you'll get the older versions. It's like that horrible error you get when you f5 in vs with a build error and it asks if you want to run the old output

**Comment by muratg** [comment]
It would be useful to go through different error cases and decide if we need to downgrade them all.

Do it as part of https://github.com/aspnet/dnx/issues/2831 and close this one.

**Comment by muratg** [comment]
@davidfowl Feel free to close this one if you're going to do it with the #2831's PR.
