### ISSUE TITLE
Publish over aggressively deletes package contents

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2850]
See #2741. Today the publish logic tries to keep only the things it requires by using the lock file input to post process the published files. Instead, we need to only delete the set of things we know of in the lock file that aren't relevant to the current publish. For example, if we're targeting dnx451 instead of dnxcore50, then we can delete all of the known dnxcore50 things.

**Comment by JunTaoLuo** [comment]
merged to dev
