### ISSUE TITLE
Restore should write lock files for transitive projects by default

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2851]
We want to make it so that running restore on a project makes it runnable. To do this we need to make sure that all transitive project references are also restored. This should be the default behavior if there's a project.json in the folder. There should be a flag `--no--project-references` (or some other name) that disables this behavior.

**Comment by davidfowl** [comment]
@anurse I want to give you this one. 

/cc @abpiskunov This will require a tooling change.

**Comment by anurse** [comment]
Yeah, I've noticed this and it's a pain. I can take it.

**Comment by muratg** [comment]
We'll need to get back to this one.

**Comment by abpiskunov** [comment]
Let me know when there are privates to try. At this point tooling does detect all project dependencies and sends them all to dnu. With this change - should we continue to do so or do nothing since dnu is expected to do the same?

**Comment by muratg** [comment]
@abpiskunov I think we will do this post RC1.  With this change, you wouldn't need to do it on the tooling side.
