### ISSUE TITLE
./build dev-install does not alias mono-dev properly

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2855]
Whenever ./build dev-install is run, the aliasing for mono-dev becomes jumbled. Probably some issue with the makefile.

screenshot:
![image](https://cloud.githubusercontent.com/assets/2030323/10148886/fbbdc1de-65ea-11e5-8b1f-3918280aef59.png)

**Comment by muratg** [comment]
Not sure if we care about Mono on Windows.  Putting this in Backlog, feel free to bring it back if you disagree.

This should work fine on XPlat though.
