### ISSUE TITLE
dnu does not recognize any installed commands

### ISSUE THREAD

**Issue by phenombox** [aspnet/dnx#2860]
I'm not sure where the issue originates from but dnu does not recognize any installed commands.
I am able to dnu restore and dnu build without issues, but I am not able to do dnu web or dnu ef.

dnvm v1.0.0-rc-15520 
dnx 1.0.0-beta7 x86 clr
vs2015 with web tools 2015 beta 7
dependencies are all the same throughout the solution / project (beta7)

Attempting to run dnu ef to set up ef migrations, but I get

    C:\Users\Yuri\Documents\Visual Studio 2015\Projects\RiWebApi\src\RiWebApi>dnu ef
    System.Exception: TODO: Error: unrecognized argument 'ef'

It used to work on another machine, but broke as well later on, not sure when it did but I'm trying this on a fresh Windows install, fresh VS2015 install in an empty ASP5 webapi project.

First I tried adding EntityFramework.Commands to dependencies and then adding "ef" as a command under commands in project.json. It used to work on my other machine but broke later on, again not sure when since I've been moving around a lot last few days. But it should still work on a fresh install in an empty project.

I've also tried
    C:\Users\Yuri\Documents\Visual Studio 2015\Projects\RiWebApi\src\RiWebApi>dnu commands install EntityFramework.Commands

which fetched a lot of packages (restore) and finished with 

    Installed:
    94 package(s) to C:\Users\Yuri\.dnx\bin\packages
    The following commands were installed: ef

But dnu does still not recognize "ef".

**Comment by BrennanConroy** [comment]
That's because you're supposed to use dnx

**Comment by phenombox** [comment]
Gosh right after I posted that I realised that, thats my bad been sitting with this for too long but thanks for the quick response.

**Comment by victorhurdugaci** [comment]
Closing as resolved
