### ISSUE TITLE
DNX451 on Mac - 'SqlConnection' does not contain a definition for 'RetrieveStatistics'

### ISSUE THREAD

**Issue by ln613** [aspnet/dnx#2863]
On Mac, got these 2 errors:

DNX,Version=v4.5.1 error CS1061: 'SqlConnection' does not contain a definition for 'RetrieveStatistics' and no extension method 'RetrieveStatistics' accepting a first argument of type 'SqlConnection' could be found (are you missing a using directive or an assembly reference?)

DNX,Version=v4.5.1 error CS1061: 'SqlConnection' does not contain a definition for 'ResetStatistics' and no extension method 'ResetStatistics' accepting a first argument of type 'SqlConnection' could be found (are you missing a using directive or an assembly reference?)

project.json:
```
{
    "dependencies": {
    },
    "frameworks" : {
        "dnx451" : {
          "frameworkAssemblies": {
            "Microsoft.CSharp": "4.0.0.0",
            "System.Core": "4.0.0.0",
            "System.Data": "4.0.0.0",
            "System.Linq": "4.0.0.0",
            "System.Xml": "4.0.0.0",
            "System.Xml.Linq": "4.0.0.0",
            "System.Collections": "4.0.0.0",
            "System.Runtime": "4.0.0.0",
            "System.Runtime.Serialization": "4.0.0.0",
            "System.Data.DataSetExtensions": "4.0.0.0",
            "System.ServiceModel": "4.0.0.0",
            "System.ServiceModel.Web": "4.0.0.0",
            "System.Configuration": "4.0.0.0"
          }
        }
    }
}
```

project.lock.json:
```
{
  "locked": false,
  "version": 2,
  "targets": {
    "DNX,Version=v4.5.1": {},
    "DNX,Version=v4.5.1/darwin-x86": {},
    "DNX,Version=v4.5.1/darwin-x64": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "": [],
    "DNX,Version=v4.5.1": [
      "fx/Microsoft.CSharp >= 4.0.0",
      "fx/System.Core >= 4.0.0",
      "fx/System.Data >= 4.0.0",
      "fx/System.Linq >= 4.0.0",
      "fx/System.Xml >= 4.0.0",
      "fx/System.Xml.Linq >= 4.0.0",
      "fx/System.Collections >= 4.0.0",
      "fx/System.Runtime >= 4.0.0",
      "fx/System.Runtime.Serialization >= 4.0.0",
      "fx/System.Data.DataSetExtensions >= 4.0.0",
      "fx/System.ServiceModel >= 4.0.0",
      "fx/System.ServiceModel.Web >= 4.0.0",
      "fx/System.Configuration >= 4.0.0"
    ]
  }
}
```

dnvm list:
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-beta7          coreclr x64          darwin          
       1.0.0-beta8-15654    coreclr x64          darwin          
  *    1.0.0-beta8-15654    mono                 linux/osx       default
```

please help, thanks

**Comment by muratg** [comment]
@divega

**Comment by divega** [comment]
Neither the version of SqlClient included in Mono nor the version we plan to provide for .NET Core offer the full functionality of SqlCient on the desktop version of .NET. 

For Mono there isn't much we can do but for .NET Core I believe @YoungGah's team is tracking feature requests and may be able to describe a workaround.

**Comment by muratg** [comment]
@ln613 it looks like you may want to use CoreCLR for this particular scenario when it's available (or use a workaround if that's available.)  Possibly tracking a bug on [Mono](https://github.com/mono/mono) repo may help, but not sure how they would prioritize it. Closing this for the DNX repo as a fix on DNX repo is not something we could do.
