### ISSUE TITLE
Update generation mapping table

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2866]
New table (via @ericstj):

| Generation | Platforms |
| ---------- | --------- |
| 5.1 | Windows Phone Silverlight (8 & 8.1)|
| 5.2 | .NET 4.5, Windows 8 |
| 5.3 | .NET 4.5.1/4.5.2, Windows 8.1, Windows Phone 8.1 |
| 5.4 | .NET 4.6, UWP |
| 5.5 | .NET 4.6.1, DNX Core 5.0  |

Should be done early in RC1 /cc @muratg @Eilon @davidfowl @lodejard @DamianEdwards

**Comment by anurse** [comment]
Figured I'd just bash this out. PR inbound.

**Comment by muratg** [comment]
Thanks @anurse, sounds good!
