### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#2871]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by davidfowl** [comment]
As part of this move the follow to Common:

- Microsoft.Dnx.Runtime.Json.Sources -> Microsoft.Extensons.JsonParser.Sources
- Microsoft.Framework.CommandLineUtils.Sources -> Microsoft.Extensions.CommandLineUtils.Sources

**Comment by Fosol** [comment]
Can you please let me know where the repository for Microsoft.Extensions.* are?

**Comment by pranavkm** [comment]
@Fosol, the repository names haven't been affected by this rename
