### ISSUE TITLE
Resolve Linux RIDs once and for all

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2881]
PR https://github.com/aspnet/dnx/pull/2880 had us switch to reporting all Linuxes as `ubuntu.14.04` because we just saw so much variance in Ubuntu versions in use that we couldn't reliably get them all accurately detected. For example: Travis-CI runs Ubuntu 12, Our CI runs Ubuntu 14.10, and anyone who installs 14.04 immediately gets prompted to upgrade to 15.04, so many of our other machines use 15.04. Some folks also use Linux Mint 17.2 which is entirely based on Ubuntu 14.04.

In all of these cases, the Ubuntu 14.04 CoreCLR build works fine, we just have RID matching issues. In the end, the simplest solution for beta8 was to just always report Linux as `ubuntu.14.04` since that's the only Linux Distro we are releasing packages for (AFAIK). That way, we unblock users on other distros which MAY work but are not 100% verified.

We need to resolve this issue in RC1.

/cc @davidfowl @muratg @Eilon @DamianEdwards

**Comment by anurse** [comment]
We're going to try and detect the specific distros we support: `ubuntu.14.04`, `centos.?` (I'm not 100% sure what version it is). For other distros, we'll do our best to detect them (Linux Mint, etc.) but provide an environment variable to override it manually and globally (if needed): `DNX_RUNTIME_ID`

**Comment by moozzyk** [comment]
@anurse - looks that if the `DNX_RUNTIME_ID` is specified `GetAllRuntimeIdentifiers` returns only `DNX_RUNTIME_ID` without any fallback/hierarchy. This does not seem to be correct - I thought the idea was that I can override my runtime id but if override to something that is in the hierarchy I get the fallback I would get if I was running a supported OS version.

**Comment by anurse** [comment]
The fallback hierarchy was only for Windows. It is generally expected that the runtime does **not** perform fallback, but we needed to do it for Windows.

Since the RID override is only intended for use with Ubuntu/OSX, this behavior is expected

**Comment by moozzyk** [comment]
The lack of fallback on non-Windows OSes is a bit problematic for native libs - especially on Mac OS. On Mac OS you may want to have just one `.dylib` that works for a number of versions (e.g. libuv on Kestrel). Currently you need to copy this .dylib x-times (e.g. 3 if you want to support 10.9, 10.10 and 10.11) instead of just using the osx-64 folder as fallback.

**Comment by anurse** [comment]
The expectation was always that a project will be restored explicitly for the runtime it is targeting, thus all fallbacks would be performed during restore. The Windows fallback is purely an optimization.

**Comment by moozzyk** [comment]
ACK
