### ISSUE TITLE
dnx test gets stuck in infinite build loop

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#2884]
Attempting to run `dnx test` on EntityFramework.SqlServer.FunctionalTests (dev branch) triggers an infinte loop wherein dnx builds, rebuilds, and forever builds one of the project's dependencies....EntityFramework.Core.FunctionalTests.

`dnu build` does not trigger this same loop.

DNX_TRACE log here: https://gist.github.com/natemcmaster/5257e322f7c05de66ae9

dnx, 1.0.0-rc1-15779 coreclr, darwin

**Comment by natemcmaster** [comment]
Happens on coreclr-linux too.

**Comment by moozzyk** [comment]
@Tratcher - can it be somehow related to the duplicate ApplicationHost parameter?

**Comment by Tratcher** [comment]
Our issue was only in the server tests, it shouldn't affect EF.

**Comment by natemcmaster** [comment]
I believe this could be caused by a build error. The reference project does not build, but the build errors do not halt the process.

**Comment by natemcmaster** [comment]
...and yes, follow up. The problem went away when fixing build errors. I'm leaving this bug open. To recap:

Project B depends on Project A. When building Project B, the Project A build fails and DNX repeatedly tries to build Project A without showing build errors.
