### ISSUE TITLE
GC.GetTotalMemory(forceFullCollection: true) ~50x slower under DNX than Full .NET

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/dnx#2886]
GC.GetTotalMemory(forceFullCollection: true) is around 50x slower running under DNX that Full .NET. This applies to both CLR and CoreCLR.

I found this because our benchmark tests use this API to capture memory usage numbers. The DNX test take ~3x longer to complete than the Full .NET ones. We obviously don't time the code that does garbage collection, so it doesn't affect that result of the tests, just the time it takes to run.

Here is a boiled down repro that shows the issue...

``` c#
using System;
using System.Diagnostics;

namespace GCTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var watch = new Stopwatch();
            watch.Start();

            for (var i = 0; i < 1000; i++)
            {
                GC.GetTotalMemory(forceFullCollection: true);
            }

            watch.Stop();

            Console.WriteLine(watch.ElapsedMilliseconds);
        }
    }
}
```

And here are a few runs of each on my machine. DNX takes 2-4 seconds and Full .NET takes ~60ms.

```
C:\GCTest\GCTest.DNX>dnvm use default -runtime clr
Adding C:\Users\rowmil\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15779\bin to process PATH

C:\GCTest\GCTest.DNX>dnx run
3979

C:\GCTest\GCTest.DNX>dnx run
4394

C:\GCTest\GCTest.DNX>dnx run
4153

C:\GCTest\GCTest.DNX>dnvm use default -runtime coreclr
Adding C:\Users\rowmil\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15779\bin to process PATH

C:\GCTest\GCTest.DNX>dnx run
4532

C:\GCTest\GCTest.DNX>dnx run
4316

C:\GCTest\GCTest.DNX>dnx run
2422

C:\GCTest\GCTest.DNX>cd ..\GCTest.NET\bin\Debug

C:\GCTest\GCTest.NET\bin\Debug>GCTest.NET.exe
61

C:\GCTest\GCTest.NET\bin\Debug>GCTest.NET.exe
55

C:\GCTest\GCTest.NET\bin\Debug>GCTest.NET.exe
56
```

**Comment by rynowak** [comment]
Dumb question but what's `GC.GetTotalMemory(forceFullCollection: true);` returning for desktop vs DNX. It wouldn't be surprising to see DNX using significantly more memory because of roslyn and thus taking much longer to run a GC.

However if the numbers are in the second range to GC that app, that feels broken.

**Comment by rowanmiller** [comment]
A run I just did returned 24,156 on desktop and 3,414,444 on DNX. I also got the memory number before forcing collection and the first iteration is doing more work on DNX. .NET is cleaning up just a ~900 bytes where as DNX is cleaning up ~3,300,000. It's not just the first iteration that is slower though.

BTW note the for loop, so it's not like one call to the method takes 2-4sec. The additional time for the EF benchmarks to run (1hr on .NET Framework and 5hr on DNX CLR) is because we call this multiple times per iteration to get memory before and after the measured section of each test.

**Comment by davidfowl** [comment]
It sound like dynamic compilation to me

**Comment by rowanmiller** [comment]
BTW to be clear I'm not super passionate about this scenario... I just wanted to file it so that you are aware of it (and I thought it might just be a symptom a deeper problem).

That said, it would be nice to trim the additional 4hrs of overhead spent in this API from our DNX benchmark runs (we currently run the .NET ones as a rolling build, but the DNX ones just nightly).

**Comment by muratg** [comment]
@davidfowl would a `dnu build` before a `dnx run` remedy the issue?

**Comment by anurse** [comment]
You could also try publishing the test with `--no-source` and running the output.
