### ISSUE TITLE
OS version should be the one reported by the OS

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2895]
We changed the way `IRuntimeEnvironment` handles OS version. It used to return the kernel version as returned by `GetVersionEx`/`uname`.

Now we do some transformations and return something else like "7.0" for win 7 instead of "6.1.x.x".

The transformation should be an util/extension method because only DNX cares about it and IRuntimeEnvironment should return the string as given by the OS.

cc @moozzyk @davidfowl

**Comment by moozzyk** [comment]
I assume that we would also return unprocessed values for other OSes

**Comment by anurse** [comment]
Agreed, but we should provide the distro id/release in a field as well so we can generate the correct RID.

**Comment by moozzyk** [comment]
:+1: - I never really liked cramming distro and version to one property

**Comment by muratg** [comment]
If not risky, we can give it a shot RC1.  Otherwise, I'll put it in 1.0.0 backlog.

**Comment by moozzyk** [comment]
If we put it in backlog then we will never be able to fix this as it will be a breaking change.

**Comment by muratg** [comment]
We'll be doing other changes in this area, so putting this in RC1 for now.

**Comment by pakrym** [comment]
So what we have right now in the IRuntimeEnvironment:

    OperatingSystem = Windows/Linux/Darvin
    OperatingSystemVersion = 
       On Win: Windows release number 
           7.0 for Windows 7, 8.1 for Windows 8.1 and Windows 2012 Server etc.
       On Linux: Release number (DISTRIB_NUMBER from /etc/lsb_release)  
           14.04 for Ubuntu 14.04, etc.
           Note: right now we always report Ubuntu.14.04 runtime identifier for dnu purposes
       On OSX: We are translating release number returned by uname to OSX version
           15.x.x -> 10.11.x El Capitan
           14.x.x -> 10.10.x Yosemite
           13.x.x -> 10.9.x  Mavericks
           etc.

I propose adding field to contain processed version number (OperatingSystemReleaseVersion?)  from above and keep actual kernel version (GetVersionEx on Windows, uname -r on Linux and OSX) in OperatingSystemVersion.

Also maybe we want to store Linux distributive name separately?

**Comment by victorhurdugaci** [comment]
I think we should have the same behavior as before (before Pawel's change). OsVersion is a string reporting `GetVersionEx` on Windows and `uname -a` on *nix.

Probably the conversion from the os reported version to what we do now (as in 6.1.0.0 -> 7.0) should be just a helper/extension method on `IRuntimeEnvironment`. Only DNX needs that conversion actually.

**Comment by moozzyk** [comment]
@victorhurdugaci on Linux you need the name of the distro. I think it would be good to keep it separate from the version. At the moment we concatenate both and pass as the version but it requires additional parsing. Also note that `uname -a` does not return the version. This is why we need to read the lsb_release. (On a separate note - maybe we should read just os-release which also exists on CentOS)

@pakrym - when doing this don't forget about [Mono](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Mono/EntryPoint.cs)
