### ISSUE TITLE
Error deploying site on azure (using github and kudu)

### ISSUE THREAD

**Issue by hahmed** [aspnet/dnx#2896]
I have been getting some issues with my app, managed to fix the kuduscript issues that stopped my site from deploying however my site is still failing. I can only see an error page atm with a 500 error.
Related issue:
https://github.com/projectkudu/kudu/issues/1722#issuecomment-145289162

I created a test repo that shows what I am trying to achieve, I can ping my site ok. Just the rest of the pipeline seems to be giving me issues.

Test repo: https://github.com/hahmed/TeamKudu
The site on azure: http://test-kudu-deploy.azurewebsites.net/
Ping: http://test-kudu-deploy.azurewebsites.net/ping

The issue I am getting at this moment on the backend:

```
<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li>    <li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li>    <li>IIS was not able to process configuration for the Web site or application.</li>     <li>The authenticated user does not have permission to use this DLL.</li>   <li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul>    <li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li>     <li>Check the event logs to see if any additional information was logged.</li>  <li>Verify the permissions for the DLL.</li>    <li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li>  <li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
```

Let me know if you need any more info from me, hope you can help.

By the way - why do I have a web.config file generated for me in azure? (I found that in the wwwroot folder)

Related to this is another issue as you can see from my issue in kuduscript, when I use 'project.json' in my deployment file - https://github.com/projectkudu/kudu/issues/1722#issuecomment-145185655 want me to open another issue for this or can we leave it open with this one?

Thanks

**Comment by muratg** [comment]
Perhaps you can enable error page to get more information? (app.UseErrorPage)

**Comment by hahmed** [comment]
It looks like this is a connection string error after all... strange as I am defo setting this in my app, as that is working, in production (azure) I am setting the overrides too. It is not reading the connection string.
````
Line 36:                .AddDbContext<ApplicationDbContext>(options =>
Line 37:                {
Line 38:                    options.UseSqlServer(config["ConnectionString"]);
Line 39:                });
````
````
at Microsoft.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName)
at Microsoft.Data.Entity.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString)
at Team.Startup.<>c__DisplayClass5_0.<ConfigureServices>b__0(DbContextOptionsBuilder options) in D:\home\site\approot\src\repository\Startup.cs:line 38
````

How can I ensure my connection string is being pulled out correctly from azure into my app/startup.cs

**Comment by muratg** [comment]
Since your connection string is under "AppSettings" of your configuration, you'll need to put it in "App Settings" on Azure Portal.  

If you had your configuration setup like VS Template (where your connection string is under ConnectionStrings) then setting it up under "Connection Strings" on Azure portal would have also worked. 

So either set the connection string on "App Settings" or change the sections in your config.json and redeploy.

**Comment by snobu** [comment]
You can have a look on this too https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext#dependency-injection-scenarios

**Comment by snobu** [comment]
This shoud work. It works on the test repo.

```c#
            services.AddEntityFramework()
              .AddSqlServer()
              .AddDbContext<ApplicationDbContext>(options =>
              {
                  options.UseSqlServer(Configuration["ConnectionString"]);
              });
```

**Comment by hahmed** [comment]
Thanks, looks like your code works, but only in production. That code will fail in the dev environment, i.e. locally.
````
Configuration["ConnectionString"])
````
The code above will pull out the environment variable as set in azure as you have commented above however in development environment where I am using the connection string too, it is not found. As I am setting it is AppSettings.ConnectionString
````
Configuration["AppSettings.ConnectionString"])
````
I was assuming portal simply overrides the settings/connection strings, looks like that is not happening yet (I appreciate this is being actively developed on) as we are trying to pull them out from the environment.

I hope that makes sense...

**Comment by snobu** [comment]
Maybe this helps?

#### Working with Multiple Environments ####
http://docs.asp.net/en/theming/fundamentals/environments.html

**Comment by hahmed** [comment]
Yes that did, thanks. Looks to me as though this is still a bug in azure, azure is not overriding the config settings - if that is the default behaviour. 

If I moved my connection string out from *app settings* to *connection strings*, how can I pull that out from the environment?

Configuration["Data:ConnectionString"] does not work...?

**Comment by snobu** [comment]
According to this bit of information here, yes, app settings should override your config.json.
https://github.com/aspnet/Home/wiki/Deploy-an-AspNet-vNext-application-to-Microsoft-Azure-websites#deploy-to-azure
at least that's how I read it.

> If your app has any general settings, create app settings from the portal with the same name. Value of this will override the one in your local config. 

DNX guys, is this still true with beta7?

**Comment by muratg** [comment]
@hahmed  Your problem is due to the fact that your local config and your azure settings (i.e. env vars) do not match. If you want to keep the connection string in AppSettings in your config, that's fine, but then you can't put it in Connection Strings on Azure portal.  You'll have to put it under App Settings on the portal. 

Go to http://test-kudu-deploy.scm.azurewebsites.net/ to see your environment variables (under App Settings) and connection strings.  Any of these variables are available to your Configuration, if you AddEnvironmentVariables.

For the most basic test, put it on top level `Configuration["ConnectionString"]` and then create a `ConnectionString` environment variable under "App Settings" section on Azure portal.

@snobu that's correct.

**Comment by hahmed** [comment]
@muratg 

If I use ````Configuration["ConnectionString"]```` as you mentioned, this will work in azure portal with the App Settings correctly giving me the connection string as you mentioned above. 

*However* the problem is, it does not work in development, it throws a connection string is null exception, the code that works is:

````
var config = Configuration.GetSection("AppSettings");
 services.AddEntityFramework()
              .AddSqlServer()
              .AddDbContext<ApplicationDbContext>(options =>
              {
                  // config["ConnectionString"] works for development env - we are getting this value from -> Configuration.GetSection("AppSettings")
                  // Configuration["ConnectionString"] works for production - we are pulling this value out directly from -> IConfigurationRoot
                  options.UseSqlServer(Configuration["ConnectionString"]); 
              });
````

To make this work for me, I basically did the below:
````
var config = Configuration.GetSection("AppSettings");
            services.Configure<AppSettings>(config, optionsName: null);
            
            // Setup options with DI
            services.AddOptions();
                   
            string connectionString = Configuration["ConnectionString"];           
  
            // pull from host...
            if(!IsDevelopment)
            {
                connectionString = config["ConnectionString"];
            }

            services.AddEntityFramework()
              .AddSqlServer()
              .AddDbContext<ApplicationDbContext>(options =>
              {
                  options.UseSqlServer(connectionString);
              });
````

In short for some reason azure portal is not correctly overriding the settings, unless I am pulling out the variables from the environment incorrectly. I have it working now with the code above.

I now want to move the connection string from app settings on azure portal into connection string, how can I pull out that value from the environment. ````Configuration["What_do_I_put_here?"] ````

**Comment by muratg** [comment]
Try this:

Config.json
```
{
  "Data": {
    "DefaultConnection": {
      "ConnectionString": ""
    }
  }
}
```

```csharp
           services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
```

And use "Connection String" section on the portal.

**Comment by hahmed** [comment]
````Configuration["Data:DefaultConnection:ConnectionString"]```` does not seem to work for me.

I have checked the portal and I am correctly setting the value, also the scm is telling me the same thing, see attached screenshots.
<img width="576" alt="screen shot 2015-10-06 at 23 02 34" src="https://cloud.githubusercontent.com/assets/658005/10324036/cddeb274-6c7e-11e5-8b23-4b96825458fe.png">
<img width="393" alt="screen shot 2015-10-06 at 23 03 27" src="https://cloud.githubusercontent.com/assets/658005/10324037/cde04c38-6c7e-11e5-8a1e-5dd69c9d90aa.png">

**Comment by moozzyk** [comment]
Do you have to configure your app to read configuration from env variables [configBuilder.AddEnvironmentVariables();](https://github.com/moozzyk/ToDoList/blob/master/src/ToDoList/Startup.cs#L25)

**Comment by hahmed** [comment]
@moozzyk Looking at this line, I am already adding the environment variables, just chaining the call...

https://github.com/hahmed/TeamKudu/blob/master/Startup.cs#L23

**Comment by Bartmax** [comment]
@hahmed in azure the Name should be `DefaultConnection` instead of `ConnectionString`
