### ISSUE TITLE
dnx stopped working.

### ISSUE THREAD

**Issue by GVX111** [aspnet/dnx#2897]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	dnx.exe
  Problem Signature 02:	1.0.0.11001
  Problem Signature 03:	560db74f
  Problem Signature 04:	Microsoft.Extensions.MemoryPool
  Problem Signature 05:	1.0.0.11003
  Problem Signature 06:	56106640
  Problem Signature 07:	12
  Problem Signature 08:	28
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	a9db
  Additional Information 2:	a9dbfcc7d4172d39e3996600cfe404a8
  Additional Information 3:	d3ce
  Additional Information 4:	d3ce54ef083d88a553ddf2920e13cead

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
<pre>Unhandled Exception: System.InvalidOperationException: A LeasedArraySegment was
collected without being returned to the pool. This is a memory leak.
   at Microsoft.Extensions.MemoryPool.DefaultArraySegmentPool`1.DefaultLeasedArraySegment.Finalize()</pre>

**Comment by muratg** [comment]
Can you provide more details?  What's the version of DNX?  CoreCLR or CLR?  What's the stack trace?
