### ISSUE TITLE
Update global.json schema (no intellisense when trying to add information like version, architecture in VS)

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2899]
http://json.schemastore.org/global

Current:
```
{
	"title": "JSON schema for the ASP.NET global configuration files",
	"$schema": "http://json-schema.org/draft-04/schema#",

	"type": "object",
	"additionalProperties": true,
	"required": [ "projects" ],

	"properties": {
		"projects": {
			"type": "array",
			"description": "A list of project folders relative to this file.",
			"items": {
				"type": "string"
			}
		},
		"sources": {
			"type": "array",
			"description": "This property is deprecated, please use the 'projects' property instead.",
			"items": {
				"type": "string"
			}
		}
	}
}
```

@Eilon

**Comment by Eilon** [comment]
BTW anyone is free to send a PR to https://github.com/SchemaStore/schemastore/. I've sent PRs and @madskristensen merged them quite quickly.

**Comment by davidfowl** [comment]
Don't add architecture and runtime they are not read by anything

**Comment by kichalla** [comment]
@davidfowl I see that these values are being used during kudu git based deployments and also @BrennanConroy  mentioned about these values being used during runtime of the application.

**Comment by kichalla** [comment]
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Infrastructure/AspNet5Helper.cs#L68

**Comment by kichalla** [comment]
This seems fixed, so closing
