### ISSUE TITLE
Problem with references in all ASP.NET vNext projects

### ISSUE THREAD

**Issue by EgyTechnology** [aspnet/dnx#2915]
Hi
I have current project created using ASP.NET vNext and I can't debug it because it's missing all Microsoft.* references.
I install DNX on my computer and I try to create new project but it show the same problem.

![capture1](https://cloud.githubusercontent.com/assets/6942742/10307489/bd8847e0-6c2f-11e5-85d9-a083212a9e46.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6942742/10307488/bd83ecc2-6c2f-11e5-895e-10f9ca729bfc.PNG)

**Comment by moozzyk** [comment]
Do you have latest tooling installed? How does your `project.json` look like?

**Comment by EgyTechnology** [comment]
Excuse me for stupid question. Because I'm new in vNext and this is my first step on working with.
This application it's going to be SPA application so I need to work with Entity Framework, Angular.js.
How I could setup this project to create application like this.
Any way. The 'project.json'

```json
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ]
}
```

**Comment by kpfaulkner** [comment]
Tried firing up the benchmarks project and I'm getting the same thing. Swear this was working fine a few days ago (before I pulled the latest)

**Comment by EgyTechnology** [comment]
When I change the DNX from beta 7 to beta 5 it's work after restoring all packages.
but when I using beta 7 it's did not work and gave me error.

**Comment by victorhurdugaci** [comment]
1. Can you please run "dnu restore" in the project folder form a command prompt and paste the output?
2. Can you share the `global.json` file?
3. Does the project run if you run it from console?

**Comment by davidfowl** [comment]
@EgyTechnology Do you have the latest tooling installed from here http://www.microsoft.com/en-us/download/details.aspx?id=48738&fa43d42b-25b5-4a42-fe9b-1634f450f5ee=True

**Comment by EgyTechnology** [comment]
Thanks @davidfowl and every one for help me the problem with the latest tooling that's did not exist on my PC.
