### ISSUE TITLE
dnu wrap does not create the correct relative path in project.json on Linux

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2917]
To repro:

1 create an empty app using yeoman, as an example my project is created at `/home/johluo/gh/EmptyApp`
2 `dnu restore` and `dnu pack` to create the dll at `/home/johluo/gh/EmptyApp/bin/Debug/dnx451/EmptyApp.dll`
3 go back to `/home/johluo/gh/EmptyApp` and run `dnu wrap bin/Debug/dnx451/EmptyApp.dll -f dnx451`

This will produce a `/home/johluo/gh/EmptyApp/wrap/EmtpyApp/project.json` with content 
![image](https://cloud.githubusercontent.com/assets/2030323/10317732/bf8f68c6-6c1a-11e5-914d-4637d2a294ea.png)

The path in the `project.json` does not have the correct relative path to the assembly.

**Comment by JunTaoLuo** [comment]
Note that maybe this is because there is no default `global.json` for project generated by yeoman?

**Comment by ashelley** [comment]
@JunTaoLuo 

Do you know what causes the changed value of these files to update the project? If I manually modify the assembly path visual studio still wants to use the old path and I'm not sure how to make it take into account my manually fixed values.
