### ISSUE TITLE
dnx --debug does not detect the attachment of gdb on linux.

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2921]
As titled. To repro,

1 run `dnx --debug`
2 in a another terminal attach gdb `gdb -pid=<process id of dnx>`
3 `continue` once gdb has finished loading the required symbols

The expected behaviour would be for dnx to continue running, in this case print the help text and exit. This is what happens on Windows once you attach a Visual Studio debugger for example. However on linux, the dnx process just never get further than `Waiting for the debugger to attach...` text. 

Likely we are not detecting the attachment of debuggers such as gdb properly but I'm not sure if this is a feature we support anyways.

Note that if you launch gdb and run dnx from inside gdb, everything runs as expected.

**Comment by moozzyk** [comment]
@JunTaoLuo - [known issue](https://github.com/aspnet/dnx/blob/dev/src/dnx.common/utils.cpp#L264) - it has not been implemented so far - one of the issues is that CoreClr is not debuggable at the moment.
