### ISSUE TITLE
Forwarded options for dnx stops parsing of subsequent commands

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2924]
There are some forward options for dnx like `--packages` and once `RuntimeBootstrapper` encounters them, everything after the options are forwarded to `ApplicationHost`. Since the user does not know that these options are forwarded, they may place the command after the option and `ApplicationHost` will be unable to parse the option as a command.

To illustrate:

![image](https://cloud.githubusercontent.com/assets/2030323/10326579/ce3d0ca2-6c51-11e5-8b03-50de31562a46.png)

Note how `dnx kestrel --packages packages` works because the command `kestrel` comes before the forwarded option `--packages` whereas  `dnx --packages packages kestrel` won't work since `--packages` was parsed as a command instead of `kestrel`.

At least we should indicate to the user the forwarded options should come after the command.

**Comment by JunTaoLuo** [comment]
In fact it seems as if those options are not even forwarded properly:

![image](https://cloud.githubusercontent.com/assets/2030323/10326818/67baf6a8-6c54-11e5-9779-3ad093dcbff0.png)

I moved one of required packages to a local directory `packages` and it was not picked up even if I specified the `--packages` option.

**Comment by moozzyk** [comment]
No. The `kestrel` command does not have the `--packages` parameter so it does not have any effect. 

`dnx --packages {packages} kestrel` should work though - `--packages` is a bootstrapper parameter.

**Comment by BrennanConroy** [comment]
This is still an issue in RC1

```
Information: [LoaderContainer]: Load name=--packages, Culture=neutral, PublicKeyToken=null
Error: Unable to load application or execute command '--packages'. Available commands: web, kestrel.
```
