### ISSUE TITLE
dnx ef shouldn't trigger a build

### ISSUE THREAD

**Issue by frapontillo** [aspnet/dnx#2926]
I am trying to run `dnx ef dbcontext scaffold-templates EntityFramework.SqlServer`, but as I'm heavily refactoring my code, it won't work: it looks like, no matter what dnx command I run, it first tries to compile the current project.
Is this something that can be somehow overridden?

**Comment by rhires** [comment]
I had a similar issue with dnx ef just being broken when my code wasn't perfectly compilable, but that's how EF6 works now - you can't do a migration if your code has errors. I think the rationale is correct, even if it's a pain. I can imagine the work required to make sure that your models/entities/dbcontext(s) are correct, but ignore other stuff that isn't...
