### ISSUE TITLE
Remove CallContextServiceLocatorProvider

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#2927]
We're going to be removing it (and potentially moving it up the stack to something like Hosting for web applications). As a temporary replacement, we can use the AppDomain/AppContext dictionary bag with well known keys to store/retrieve this.

**Comment by smbecker** [comment]
How would you access runtime services from tests? That is main place I use it today.I remember seeing an issue before (although couldn't find it) where someone was requesting changes in the DNX runner for xunit to provide access to the runtime IServiceProvider and it was closed as won't fix.

**Comment by davidfowl** [comment]
@smbecker We're going to get rid of the runtime services and just have a static that will be usable there. It won't be an IServiceProvider either. Just a type with some properties.

**Comment by muratg** [comment]
@davidfowl out of scope now?

**Comment by davidfowl** [comment]
@pakrym did this
