### ISSUE TITLE
With Ctrl-F5, sometimes, you get a HTTP Error 502.3 - Bad Gateway

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#2934]
1. New ASP.NET 5 Web Application using Beta8 bits
2. Comment out app.UseBrowserLink in Startup.cs
3. Ctrl-F5 (with Internet Explorer), page loads fine
4. Alt-tab to Startup.cs and hit Save
5. Alt-tab to the browser and hit Refresh

ACTUAL
![image](https://cloud.githubusercontent.com/assets/8246794/10353967/082f0d98-6d10-11e5-9638-20a243e373e5.png)

**Comment by muratg** [comment]
@troydai Could you investigate this for Beta 8 please? Feel free to get help as needed.  We'll need to figure out what this is and if we should take a fix for Beta 8.

@danroth27 @Eilon

**Comment by muratg** [comment]
@moozzyk and @halter73 per @davidfowl's request.

**Comment by davidfowl** [comment]
Confirmed it is a Kestrel shutdown problem:

Server Disposed in 2510ms

I modified hosting to show the server shutdown time. It's taking ~2-4 seconds to shutdown the server. Can we move this issue to Kestrel?

/cc @Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/247
