### ISSUE TITLE
dnu build fails to recognize resolved package reference

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#2935]
Repro:
- create a dnx console application in VS and only have `dnx451` dependencies. Make sure to have the sdk version in global.json to be `beta8`
- Add the dependencies `"Nuget.Core": "2.8.6", "Nuget.Indexing": "3.0.75-r-master"` in project.json
- save project.json, let it restore and try building the project. you should see an error like below
  ![image](https://cloud.githubusercontent.com/assets/6559784/10355929/4a11b34e-6d26-11e5-8fd8-19dc87065d07.png)

Now change the sdk version in global.json to be `beta7` and you should see the dependencies resolved properly and build is also successful.

Just FYI:
Nuget.Indexing depends on NugetGallery.Core, which in turn depends on `NuGet.Core (≥ 2.8.3-alpha0001)`

**Comment by davidfowl** [comment]
Seems we still have this casing issue:

![image](https://cloud.githubusercontent.com/assets/95136/10356720/e6bc5976-6d2e-11e5-9ae7-e47eb1504e45.png)

I wonder if this regressed somehow... On a side note @abpiskunov why doesn't this bubble up the chain of dependencies?

**Comment by abpiskunov** [comment]
diagnostics bubble up issue is fixed in beta8, thanks for pointing it out.

**Comment by kichalla** [comment]
@abpiskunov BTW I am using Beta8 WTE 

![image](https://cloud.githubusercontent.com/assets/6559784/10375155/c091be1c-6dab-11e5-9522-50486f00ba71.png)

**Comment by abpiskunov** [comment]
it was just fixed , build is not ready yet, should be available later today
