### ISSUE TITLE
Wrong version of dependency is copied to output directory

### ISSUE THREAD

**Issue by pakrym** [aspnet/dnx#2937]
1. .\build & .\build dev-install
2. Look into %USERPROFILE%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin\lib\Microsoft.Dnx.Tooling\

Microsoft.Dnx.Project.dll is CoreClr version of this assembly

..\Microsoft.Dnx.Project\Microsoft.Dnx.Project.dll is correct

**Comment by moozzyk** [comment]
Can this be this related to #2702?

**Comment by pakrym** [comment]
Yes, looks similar.

**Comment by pakrym** [comment]
This issue is caused by hardcoding "dnxcore50" in https://github.com/aspnet/dnx/blob/dev/makefile.shade#L1252
