### ISSUE TITLE
Assembly binding redirection

### ISSUE THREAD

**Issue by adriaanp** [aspnet/dnx#2939]
How is assembly binding redirection suppose to work.

I've included a package MyCouch that depends on another package Ensure.That(2.0.0). When running dnx reports it can't resolve Ensure.That 2.0.0 (incompatible).

Then when adding dependency Ensure.That 3.2.0, my app runs but as soon as I use MyCouch I'm getting:
System.IO.FileNotFoundException: Could not load file or assembly 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=null' or one of its dependencies. File name: 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=null'

I've created a repo here, when just doing dnx run it gets that Exception.
https://github.com/adriaanp/bindingdirection

I'm trying this on mono with beta7.

My question is then why is it not using 3.2.0 and still looking for 2.0.0?

**Comment by davidfowl** [comment]
You should never need it. We hook assembly resolve and fix up th versions at load time. Will take a look at the sample to see where the problem is

**Comment by davidfowl** [comment]
Did ensure that change assembly names at some point? If you crack open reflector on EnsureThat 2.0.0 and 3.2.0 what do the assembly names say?

**Comment by adriaanp** [comment]
Yes the assembly names changed. :-(

**Comment by davidfowl** [comment]
Nothing you can do there
