### ISSUE TITLE
Running DNX as a Windows service locks breadcrumbs indefinitely

### ISSUE THREAD

**Issue by latvalam** [aspnet/dnx#2942]
### Functional impact
When a dnx app is running as a background service, other dnx apps fail to launch.

### Minimal repro steps
See https://taskmatics.com/blog/run-dnx-applications-windows-service/

1. Create a dnx console application and implement a dummy service class. Note that the svc needs to be properly implemented for it to start
2. Register the service with: `sc create <service-name> binPath= "\"<dnx-exe-path>\" \"<project-path>\" run"`. You can use run.cmd as a reference for the binPath, but change the paths to absolute ones
3. Start the service with: `net start <service-name>`
4. Create a dnx web app and host it in IIS
5. Navigate to your app in a browser

### Expected result
The web page should open without errors

### Actual result
The page fails to open due to an Access Denied exception. If you stop the svc, you will be able to open the web page normally.

### Further technical details
An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll
Additional information: Access to the port is denied.

Stack trace:
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
> Microsoft.Framework.Runtime.Internal.ConcurrencyUtilities.ExecuteWithFileLocked(string filePath, System.Action<bool> action)
> Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.Servicing.Breadcrumbs.WriteAllBreadcrumbsInternal()
> System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
> System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, > > System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)
> System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
> System.Threading.ThreadPoolWorkQueue.Dispatch()

Tested on: dnx46, dnx-clr-win-x64.1.0.0-beta6, IIS 10

### Workaround

If you set the environment variable DNX_NO_BREADCRUMBS to 1, everything works fine.

**Comment by victorhurdugaci** [comment]
Can you please try with beta7 or newer? The bug might have been fixed.

**Comment by latvalam** [comment]
Unfortunately looks like making the whole setup work with beta7 is a bit more of an undertaking I currently have time for. We are planning to upgrade to beta8 soon-ish, but not right now.

**Comment by latvalam** [comment]
Works fine in rc1
