### ISSUE TITLE
ConcurrencyUtilities.FilePathToLockName causes ArgumentException for long paths

### ISSUE THREAD

**Issue by poizan42** [aspnet/dnx#2943]
There is a 260 characters limit on semaphore file names. This currently causes coreclr to fail at restoring packages when built from a long path (dotnet/coreclr#1731).

I would suggest using a hash like SHA2 instead, but that would introduce a dependency on System.Security.Cryptography.Hashing.Algorithms - is that acceptable? Or we could add our own private implementation of a hashing algorithm.

It's also possible that this issue goes away depending on what happens in dotnet/corefx#3740

**Comment by IDisposable** [comment]
I would vastly prefer #3740 getting implemented. Hash collisions are so hard to detect and mixing them with transient things like locks an semaphores makes it even harder.

**Comment by poizan42** [comment]
Well the current implementation has trivial collisions such as `c:\a\b\c` and `c:\a_b\c` giving the same name.

Compare that to Sha256 where (assuming it's not broken) you would have to generate a different hash every nanosecond for about 3.4*10^20 years just to have 0.1% chance of getting a collision.
