### ISSUE TITLE
dnu publish should clean up packages left behind from previous publish

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnx#2945]
If you publish with `--framework dnxcore50` and then rerun publish with `--framework dnx451`, the packages required by `dnxcore50` are not removed and are still kept in the output directory in `approot/packages/`. Although the user can just manually delete these packages, it's inconvenient.

**Comment by victorhurdugaci** [comment]
Isn't publish deleting the contents of the folder before it runs?

**Comment by JunTaoLuo** [comment]
It seems like only the folders of the packages required by `dnx451` are being cleared by publish. Publish does not nuke the entire `packages` folder.
