### ISSUE TITLE
Review and clean-up Microsoft.Dnx dependencies

### ISSUE THREAD

**Issue by anurse** [aspnet/dnx#2947]
The packaging project, Microsoft.Dnx, gained a few extra dependencies during beta 8 sign-off. We need to reevaluate that during the next milestone.

/cc @Eilon @muratg

**Comment by muratg** [comment]
:+1:   @anurse could you drive this one Beta 8 is out?  Please get help from @BrennanConroy et.al.

**Comment by BrennanConroy** [comment]
Remove my latest commit as part of this once the publish issue is fixed :D

Sent from my HTC

----- Reply message -----
