### ISSUE TITLE
Enable users to analyze overridden dependencies using dnu list command.

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#2948]
Added two features to `dnu list`
1. List all the dependencies of a project of which the request version is different from the final version.
2. List source of a give dependency. The source is represented by a path from project root to the given dependency.  

Related: #2744

**Comment by troydai** [comment]
@davidfowl @DamianEdwards @muratg 

This is derived from #2744, I regard it as a 1.0.0-rc1 feature.

**Comment by muratg** [comment]
:+1:
