### ISSUE TITLE
Should "prepare" scripts run immediately after "postrestore" scripts?

### ISSUE THREAD

**Issue by halter73** [aspnet/dnx#2951]
https://github.com/aspnet/dnx/blob/05fdf7feae9667877cf19e68c88277905d2281c7/src/Microsoft.Dnx.Tooling/Restore/RestoreCommand.cs#L522

What's the point of having both of these events if they trigger at the same time? I would also expect prepare to run before postrestore if anything.

**Comment by davidfowl** [comment]
prepare also runs before publish https://github.com/aspnet/dnx/blob/972b3be035c34f4599a0687623d352b4341bd03d/src/Microsoft.Dnx.Tooling/Publish/PublishManager.cs#L102

**Comment by halter73** [comment]
So if I run dnu restore and then dnu publish, the prepare script runs twice but postrestore script runs once? Since you need to restore packages before publishing, what's the point of running prepare as part of dnu publish?
