### ISSUE TITLE
dnu publish on xproj referencing a csproj fails

### ISSUE THREAD

**Issue by glennc** [aspnet/dnx#2954]
xproj referencing a csproj. xproj is dnx451 only
csproj has some NuGet package dependencies that only have lib/net451 assemblies

Project can run fine, but running publish gives an error about being unable to resolve the package dependencies in the wrapped project.json. It was reported that modifying the wrapper project.jsons tfm from net451 to dnx451 made it work. No idea why that is.

Need some root cause analysis to find out what's really happening here.

**Comment by JasonRowe** [comment]
Even when the project doesn't have a reference the publish is failing for me silently. The only reason I can tell it fails is the exit code and the wwwroot folder and the contents are not published.

**Comment by muratg** [comment]
@pakrym Could you investigate this on Monday?

**Comment by pakrym** [comment]
@muratg Sure, will do.

**Comment by feldskov** [comment]
Just a note. I am experiencing the same problem (with csprojects not using ngut-packages).

Manually changing the framework in project.json in the wrap-folder from net451 to dnx451 will allow me to publish (after running "dnu restore"), but my error list in VS2015 will show a lot of errors ("The type or namespace name ‘abc’ does not exist in the namespace"). The solution builds fine, but shows a lot errors.

Looking forward to a fix :)

**Comment by promontis** [comment]
I have this problem as well: https://github.com/aspnet/dnx/issues/2842
I also managed it to publish by updating it from net451 to dnx451, and it also shows a lot of errors.

**Comment by promontis** [comment]
Is this already pushed to the dev branch myget feed? Would love to try it out!

**Comment by muratg** [comment]
@pakrym checked in a fix, though we do not yet have the packages on vnext feed.

**Comment by miragejb** [comment]
I have this exact same problem with Beta8.  Is this problem corrected?  If so, where can I find the fixes?

Thanks.

**Comment by muratg** [comment]
Could you guys try this out with the current set of vnext packages (RC1-*)

**Comment by miragejb** [comment]
I would love to test it out for you.  Do you have any instructions on how to get and use the latest rc1 version of vnext?

**Comment by muratg** [comment]
Try `dnvm upgrade -u` to install unstable bits.

**Comment by Lakerfield** [comment]
@muratg ```dnu publish``` is working with beta8 with the following workaround

Use a beta8 project with publish problem from above
```dnvm upgrade -u``` installs: dnx-clr-win-x86.1.0.0-rc2-16128 (tried to get rc1-* but not succeeded)
```dnu publish --out ... --runtime dnx-clr-win-x86.1.0.0-rc2-16128```
After publish copy dnx-clr-win-x64.1.0.0-beta8 runtime to approot/runtimes
Edit run files to use dnx-clr-win-x64.1.0.0-beta8
Result a working published version running on beta8

**Comment by Lakerfield** [comment]
@muratg I found a bug in the workaround publish process with the rc2 bits. If the project wrap a console app instead of a class library. The publish doesn't copy the .exe file to the packages location. The .nuspec and project.json are there, but the lib/net45 directory doesn't exists

**Comment by muratg** [comment]
cc @anurse.  We'll be revisiting publish in RC2 and we should look into this.
