### ISSUE TITLE
Will shared projects be supported in `xproj` projects?

### ISSUE THREAD

**Issue by TomasHubelbauer** [aspnet/dnx#2973]
Hey, is this a right repository to ask in?

In ASP .NET 4.5 one could hack the `csproj` file to include:
```xml
<Import Project="..\SharedProject\SharedProject.projitems" Label="Shared" />
```
This would work just fine and as expected. Under references, the shared project would be visible, the code would be shared and so on. It is still a hack, but it feels only like a lack of tooling.

In ASP .NET 5, the `xproj` file can still be patched, but the shared project doesn't appear under *References* and the code is not shared.

Will this change in the future? Are there plans to add support for shared projects to `xproj` projects? Preferably with the *References* dialog offering the *Shared projects* tab.

**Comment by davidfowl** [comment]
@TomasHubelbauer Can you file this under https://github.com/aspnet/Tooling
