### ISSUE TITLE
Matching algorithm for processing RESX files should use a culture pattern instead of a known list

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#2976]
Instead of using a hard-coded known culture list, detect `Foo.%CULTURE%.resx` based on what matches a possible culture name. E.g. `en`, `en-US`, and `foo-Damo` all match the culture pattern, so process those as satellite RESX files. But `kitten-meow` and `poodle` do not match the pattern of culture names so they are treated as regular resource files. We should accept only `xx`, `xx-yyyy`, and `xx-yyyy-zzzz` patterns. The `xx` can be 2 or 3 chars, and the `yyyy` and `zzzz` have some of their own restrictions as well. Need to consult the spec to see the exact rules that Resource Manager on Core CLR uses.

**Comment by Eilon** [comment]
@davidfowl we currently have undesirable behavior in DNX compilation for resources. Is it worth investing in this, or does this not matter when we switch the DNX compilation stuff around?

**Comment by davidfowl** [comment]
@Eilon yes that's fine if we can get the logic right. We removed it because it detected too much stuff and broke on a bunch of our repositories.

**Comment by Eilon** [comment]
@davidfowl we're currently thinking of making the logic a bit more precise than it used to be. It might still capture more than you want, e.g. a file named `MyComponent.cs.resx` will be interpreted as a satellite resource for the language `cs` for the resource type `MyComponent`. It's worth noting that *no matter what you do*, there will always be cases like this. There might today already be a real culture called `cs`, or even if there isn't today, Win10+++ might add that culture, and then it would be real. So even if we filter on existing cultures, that doesn't help much. And it could very well be a custom culture, which is also supported.

@kirthik FYI

**Comment by Eilon** [comment]
@davidfowl and it's worth noting that in our meeting when we discussed this, the only (and in our opinion *correct*) workaround is to rename the "offending" file.

**Comment by davidfowl** [comment]
@Eilon Sounds fine if that aligns with what msbuild + resgen does today.

**Comment by Eilon** [comment]
Yeah in reality everything is broken, but in their own special ways, but I believe this gets us a lot closer.

@DamianEdwards @lodejard FYI as well.
