### ISSUE TITLE
Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr in DNX dnx-clr-win-x64.1.0.0-rc1-15838

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/dnx#2983]
Please help issue when run in dnx-clr-win-x64.1.0.0-rc1-15838

Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Descripción: Excepción no controlada al ejecutar la solicitud Web actual. Revise el seguimiento de la pila para obtener más información acerca del error y dónde se originó en el código. 

Detalles de la excepción: System.TypeLoadException: Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Error de código fuente: 

Se ha generado una excepción no controlada durante la ejecución de la solicitud Web actual. La información sobre el origen y la ubicación de la excepción pueden identificarse utilizando la excepción del seguimiento de la pila siguiente.

Seguimiento de la pila: 

[TypeLoadException: Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9920760
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by moozzyk** [comment]
Helios is no longer supported as the host. See: https://github.com/aspnet/Announcements/issues/70.

**Comment by CarlosFreire** [comment]
Please How I can publish IIS

**Comment by moozzyk** [comment]
Beta8 shipped today. See the details in the announcement [blog post](http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx), install the latest tooling and report back if you have any questions.

**Comment by CarlosFreire** [comment]
dnx 1.0.0-Beta8 publish in IIS 
show resource not found

Failed to load resource: the server responded with a status of 404 (Not Found)

on when publish in IIS

**Comment by davidfowl** [comment]
Please read the blog post it has the exact detsils you need to publish
