### ISSUE TITLE
Refactoring DNX not to inject into Program constructors

### ISSUE THREAD

**Issue by pakrym** [aspnet/dnx#2990]
Kill anything that takes IServiceProvider in Program.Main or Program()
All entry points to public static void Main
Add compilation option emit entry point to everything with Program.Main

@muratg

**Comment by per-samuelsson** [comment]
Doesn't sound very compatible with whats out now. This something you plan on? Care to share a couple of lines of insight?

**Comment by tugberkugurlu** [comment]
huh?

**Comment by tugberkugurlu** [comment]
So, no DI in console applications to my `Program` class? maybe I am misunderstanding this. Would be good to clarify.

**Comment by ejsmith** [comment]
What is the reasoning behind this change?

**Comment by davidfowl** [comment]
We want to be compatible with regular Program.Main entry points. We're working to get this in for the next version of C# https://github.com/dotnet/roslyn/issues/1695. We also want to be able to avoid scanning for the application entry point at runtime so it's better if we can just do all of the hard work at compile time instead of runtime.

**Comment by davidfowl** [comment]
BTW anything is possible with indirection so there could be another Program.Main that does support injection and calls into this program main, but that would be in a library.

**Comment by roji** [comment]
Can you guys describe how a DNX command is supposed to be written after this change? What's the right way to access, say, the IApplicationEnvironment from a program?

**Comment by davidfowl** [comment]
the PlatformServices static. You also want to set `emitEntryPoint: true` in your compilation options and have a public static int/void Main.

accessing runtime services
https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher/Program.cs#L26

project.json
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/ConsoleApp/project.json#L10

**Comment by davidfowl** [comment]
There are also other examples in Entropy:

https://github.com/aspnet/Entropy/tree/dev/samples/Runtime.ApplicationEnvironment

**Comment by roji** [comment]
Thanks @davidfowl

**Comment by csunali** [comment]
Do we also have to do this for ASP.NET applications?

I currently get the `Unable to resolve service for type 'Microsoft.Dnx.Runtime.IAssemblyLoadContextAccessor' while attempting to activate ....Startup` exceptions all around.

Trying to use your suggestion `PlatformServices.Default` also returns `null`.

DNX x86 version 1.0.0-rc1-16048   |   Microsoft.AspNet.Hosting version 1.0.0-rc1-15872

**Comment by csunali** [comment]
Sorry, changing from `Microsoft.Dnx.Runtime.Abstractions` to `Microsoft.Extensions.PlatformAbstractions` fixed the issue.

But still, is this the new suggested way of accessing `IApplicationEnvironment`, etc. for ASP.NET applications?

**Comment by jruckert** [comment]
breaking change?

**Comment by davidfowl** [comment]
@csunali in ASP.NET apps use dependency injection.

**Comment by csunali** [comment]
@davidfowl - I am developing a custom bootstrapper that does some work on itself and the developers have to provide me with the `IApplicationEnvironment` instance (within ConfigureServices, where I still don't have dependency injection service provider built) and I would be glad if I can use `PlatformServices` in an ASP.NET application as well. That would remove the requirement for my developers to pass in that parameter of `IApplicationEnvironment`.

After the ConfigureServices complete its job, I will of course be using dependency injection to inject `IApplicationEnvironment` and other type instances wherever applies.

I just tried it and `PlatformServices.Default.Application` seems to work fine during ConfigureServices execution time. Is there any harm if I keep using it?

**Comment by davidfowl** [comment]
@csunali Just that you can't test set stuff because statics. All we did was remove injection for Program.Main entrypoints. We expect ASP.NET applications to still use the injected services and not reach out to statics.

**Comment by csunali** [comment]
I see your concern. Thank you for the feedback!

**Comment by jruckert** [comment]
IApplicationEnvironment is not available anymore in the

```
public Startup(IHostingEnvironment env, IApplicationEnvironment env)
```
It cannot resolve it.

**Comment by csunali** [comment]
@jruckert - Changing from `Microsoft.Dnx.Runtime.Abstractions.IApplicationEnvironment` to `Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment` fixes the issue.

**Comment by jruckert** [comment]
Thanks!

**Comment by tugberkugurlu** [comment]
> We want to be compatible with regular Program.Main entry points.

@davidfowl does this also mean that `Main` method cannot return `Task` anymore?

**Comment by davidfowl** [comment]
That's correct.
