### ISSUE TITLE
Debugging Generic Console App in VS 2015 breaks

### ISSUE THREAD

**Issue by dcinzona** [aspnet/dnx#2993]
When including the following dependencies in project.json, F5 breaks in Visual Studio 2015 (all updates and running WebTools Beta8.

Dependencies that break F5:
```
"Microsoft.Dnx.Compilation": "1.0.0-*",
"Microsoft.Dnx.Runtime": "1.0.0-*",
```

Steps to repro:
1. Create a new console app project in VS
2. Have the console wait for user input so it stays open (Console.ReadLine())
3. Run (this works fine)
4. Add the above dependencies to project.json and save the file (dependencies should auto restore)
5. Run (this breaks with the following error)

```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Dnx.ApplicationHost.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Dnx.ApplicationHost.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Dnx.Host.dll
```

My current setup:
```
Active Version         Runtime Architecture OperatingSystem Alias
------ -------         ------- ------------ --------------- -----
       1.0.0-beta5     clr     x64          win
       1.0.0-beta5     clr     x86          win
       1.0.0-beta5     coreclr x64          win
       1.0.0-beta5     coreclr x86          win
       1.0.0-beta8     clr     x64          win
       1.0.0-beta8     clr     x86          win
       1.0.0-beta8     coreclr x64          win
       1.0.0-beta8     coreclr x86          win
  *    1.0.0-rc1-15838 clr     x86          win             default
```

**Comment by NeelBhatt** [comment]
Are you running from VS or from command line?

**Comment by dcinzona** [comment]
From VS - that's the issue.

**Comment by dcinzona** [comment]
Here's a repository with the code: https://github.com/dcinzona/DNXBug

**Comment by NeelBhatt** [comment]
Try running from command line. For VS it is currently not supported.

See : https://github.com/aspnet/dnx/issues/2727

**Comment by dcinzona** [comment]
I can run from VS without debugging (ctrl+F5).  So these two packages prevent any debugging in VS (other than attaching? )

**Comment by dcinzona** [comment]
Actually, running without debugging also creates an error: 
```
Error: This application requires DNX version 1.0.0-rc1-15904 or newer to run.
```
Not sure why thought

**Comment by dcinzona** [comment]
Heh, myget has the wrong feed url listed for dnvm.  Needs to be: `https://www.myget.org/F/aspnetcidev/api/v2/`
