### ISSUE TITLE
Beta 8 and Azure

### ISSUE THREAD

**Issue by ealsur** [aspnet/dnx#2996]
Deployed a new Web App using Beta8 to Azure (the site works locally with no problem).

Kudu pulls the Git repo and builds without problems.

But upon the first request, the site becomes unresponsive for some time and eventually shows an http 500.

Checking the EventLog file on Kudu, it's full of:

```xml
<Event>
        <System>
            <Provider Name="HttpPlatformHandler"/>
            <EventID>1000</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2015-10-16T18:54:22Z"/>
            <EventRecordID>1891235750</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD000D3A7033D2</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Process '3400' failed to start. Port = 21515, Error Code = '-2147023436'.</Data>
        </EventData>
    </Event>
```

And the stdout files show:

```
Microsoft.Net.Http.Server.WebListenerException (0x80004005): Access is denied
   at Microsoft.Net.Http.Server.WebListener.SetupV2Config()
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNet.Server.WebListener.MessagePump.Start(Func`2 app)
   at Microsoft.AspNet.Server.WebListener.ServerFactory.Start(IFeatureCollection serverFeatures, Func`2 app)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

**Comment by muratg** [comment]
Looks like you're using WebListener for your app. That is not supported. You should use Kestrel instead. Please give it a try and let me know.

**Comment by ealsur** [comment]
Thanks for clarifying @muratg this was a beta5 app migrated to beta8.

**Comment by ealsur** [comment]
@muratg Tried adding Kestrel to the project.json file (like https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/project.json) but the error remains.

It works locally but once Git-published on Azure, it fails to start.

**Comment by ealsur** [comment]
@muratg I'm sharing a repro repo: https://github.com/ealsur/testbeta8

**Comment by kichalla** [comment]
@ealsur can you try again after making the following changes:

- Change 
`"Microsoft.AspNet.Server.Kestrel": "1.0.0-*"`   
to 
`"Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8"`
- Change 
`"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001"`   
to   
`"web": "Microsoft.AspNet.Server.Kestrel"

Also I see that your `wwwroot` folder does not have a web.config file. How are you creating the project...from VS? if yes, have you installed Beta8 tooling update? the content of web.config would look something like below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>

```

**Comment by ealsur** [comment]
@kichalla I created the project from scratch using VS Code. On previous (<= Beta7) DNX versions, you didn't need a web.config.

When you deploy to Azure, Kudu creates the file automatically and all my apps were running ok that way.
When I migrated to Beta8, the problem started.
I added the suggested web.config and changed the command and it worked :)

Might want to add this to the BetaX-Beta8 migration guide :)

**Comment by muratg** [comment]
@ealsur Good to know you got your project working!  Web.config requirements are called out [here](http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx).

**Comment by JohnGalt1717** [comment]
How does one specify which command get's run by Azure? I'd rather have web bet the hosting and kestral/azure be named "azure" or something if possible.

**Comment by davidfowl** [comment]
Why? What's special about the azure command?

**Comment by JohnGalt1717** [comment]
The site gets run locally on iis, etc. for unit testing and I want web to default to those configurations and azure be the deploy scenario.

On Dec 16, 2015 10:17 PM, David Fowler <notifications@github.com> wrote:

Why? What's special about the azure command?

-

**Comment by davidfowl** [comment]
That didn't answer my question. Can you show me your command definitions

**Comment by JohnGalt1717** [comment]
If I have it this way:

  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:45576",
    "run": "run server.urls=http://localhost:45577",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:45578"
  },


It blows up in Azure and just hangs because it's assuming it should run "web" which isn't setup for kestrel.

This of course works:

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:45576",
    "run": "run server.urls=http://localhost:45577",
    "Host": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:45578"
  }, 


But there should be a way during publish to specify which command is used to launch on Azure. (or anywhere else)

**Comment by davidfowl** [comment]
There's a switch on the command line and an option in the publish profile to specify the command. You could also just change web to be kestrel and avoid the extra complexity

**Comment by JohnGalt1717** [comment]
What's the option in the publish profile? (It's not in the UI and I can't find any documentation.)
