### ISSUE TITLE
dnx 1.0.0-Beta8 publish in IIS show resource not found

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/dnx#2999]
please help

dnx 1.0.0-Beta8 publish in IIS 
show resource not found

Failed to load resource: the server responded with a status of 404 (Not Found)

on when publish in IIS

**Comment by muratg** [comment]
Did you deploy to a local IIS?  Or the IIS Express that comes with VS?  Did you use Beta 8 tooling? 

If it's full IIS, did you deploy HttpPlatformHandler?

**Comment by CarlosFreire** [comment]
It's full IIS and is installed HttpPlatformHandler in the pc

How to deploy HttpPlatformHandler?

**Comment by muratg** [comment]
Where are you deploying to?  If to Azure Websites, the handler is already installed there too.  If you're deploying to a different host, you'll need to get HttpPlatformHandler installed there as well.

Also, I'm assuming your app works locally without issues.

**Comment by CarlosFreire** [comment]
The app works locally without issues, but when deploy in different host the app doesnt run and is installed HttpPlatformHandler in the host, some additional configuration is required?

**Comment by GuardRex** [comment]
@CarlosFreire Check my notes and see if anything there helps: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by andreigorlov** [comment]
Check these comments:
https://github.com/aspnet/Hosting/issues/364#issuecomment-148752376
https://github.com/aspnet/Hosting/issues/364#issuecomment-148755010
