### ISSUE TITLE
Internalize JSON.NET dependency

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#30]
Today we're using JSON.NET as a package and that's no good for apps and frameworks that use this framework. This is part of the work #29

**Comment by ChengTian** [comment]
We should close the following issues after this is done:
https://github.com/aspnet/dnx/issues/1788
https://github.com/aspnet/dnx/issues/1816

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/1816#issuecomment-100063615

**Comment by muratg** [comment]
https://github.com/aspnet/Announcements/issues/24

**Comment by troydai** [comment]
Fixed in f0a852af06282494168100a83b3b79e0cc155c15
