### ISSUE TITLE
Improve DNX minimum version message

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#3000]
DNX now does a minimum version check: https://github.com/aspnet/dnx/issues/2711

Unfortunately the message doesn't tell you what packages aren't compatible with the installed version of DNX. If you don't want to increase the DNX version - for example you are on a stable version of DNX but you have a dependency on a package that requires an unstable version - it is hard to figure out what package is the cause of the minimum version message.

**Comment by JamesNK** [comment]
Hey, issue 3000. Do I win a prize? :smile_cat:

**Comment by muratg** [comment]
I think this is a good suggestion.  @victorhurdugaci 

BTW, @JamesNK You get 3 internet points! :gift: :gift: :gift:

**Comment by JamesNK** [comment]
RIP
