### ISSUE TITLE
beta8 azure "no space left on device"

### ISSUE THREAD

**Issue by dimsedane** [aspnet/dnx#3001]
Creating a new beta8 website using the generator-aspnet, doing nothing other than

* dnu restore
* dnu build
* git init
* git add --all
* git commit -m "initial commit"
* git remote add azure <azurepath>
* git push azure master

This works fine until I get this error:

    remote: ----------
    remote: System.IO.IOException: There is not enough space on the disk.
    remote: 
    remote:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    remote:    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
    remote:    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
    remote:    at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
    remote:    at System.IO.Stream.CopyTo(Stream destination)
    remote:    at Microsoft.Framework.PackageManager.Publish.PublishOperations.ExtractFiles(ZipArchive archive, String targetPath, Func`2 shouldInclude)
    remote:    at Microsoft.Framework.PackageManager.Publish.PublishOperations.ExtractNupkg(ZipArchive archive, String targetPath)
    remote:    at Microsoft.Framework.PackageManager.NuGetPackageUtils.ExtractPackage(String targetPath, FileStream stream)
    remote:    at Microsoft.Framework.PackageManager.NuGetPackageUtils.<>c__DisplayClass0_0.<<InstallFromStream>b__0>d.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.Runtime.Internal.ConcurrencyUtilities.<ExecuteWithFileLocked>d__2`1.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.PackageManager.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.PackageManager.RestoreCommand.<InstallPackageCore>d__76.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.PackageManager.RestoreCommand.<InstallPackages>d__75.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    remote:    at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__70.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass69_0.<<Execute>b__1>d.MoveNext()
    remote: --- End of stack trace from previous location where exception was thrown ---
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    remote:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    remote:    at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__69.MoveNext()
    remote: ----------
    remote: Restore failed
    remote: There is not enough space on the disk.

**Comment by davidfowl** [comment]
@dimsedane we're aware of this issue. Can you try removing one of the frameworks from your project.json and starting from a fresh site?

**Comment by dimsedane** [comment]
I removed the dnx451 framework since I am on a mac and it is my understanding i need the core framework to build locally.

I also create a new free azure website, updated the git remote and now I get a new error:

    remote: .....
    remote: bower jquery-validation#1.11.1       not-cached git://github.com/jzaefferer/jquery-validation.git#1.11.1
    remote: bower jquery-validation#1.11.1          resolve git://github.com/jzaefferer/jquery-validation.git#1.11.1
    remote: bower hammer.js#2.0.4                not-cached git://github.com/hammerjs/hammer.js.git#2.0.4
    remote: bower hammer.js#2.0.4                   resolve git://github.com/hammerjs/hammer.js.git#2.0.4
    remote: bower jquery-validation-unobtrusive#3.2.2       not-cached git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
    remote: bower jquery-validation-unobtrusive#3.2.2          resolve git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
    remote: bower bootstrap#3.0.0                           not-cached git://github.com/twbs/bootstrap.git#3.0.0
    remote: bower bootstrap#3.0.0                              resolve git://github.com/twbs/bootstrap.git#3.0.0
    remote: bower bootstrap-touch-carousel#0.8.0            not-cached git://github.com/ixisio/bootstrap-touch-carousel.git#0.8.0
    remote: bower bootstrap-touch-carousel#0.8.0               resolve git://github.com/ixisio/bootstrap-touch-carousel.git#0.8.0
    remote: bower jquery-validation-unobtrusive#3.2.2         download https://github.com/aspnet/jquery-validation-unobtrusive/archive/v3.2.2.tar.gz
    remote: bower hammer.js#2.0.4                             download https://github.com/hammerjs/hammer.js/archive/2.0.4.tar.gz
    remote: bower jquery-validation#1.11.1                    download https://github.com/jzaefferer/jquery-validation/archive/1.11.1.tar.gz
    remote: bower bootstrap-touch-carousel#0.8.0              download https://github.com/ixisio/bootstrap-touch-carousel/archive/v0.8.0.tar.gz
    remote: bower bootstrap#3.0.0                             download https://github.com/twbs/bootstrap/archive/v3.0.0.tar.gz
    remote: bower jquery-validation-unobtrusive#3.2.2          extract archive.tar.gz
    remote: bower jquery-validation-unobtrusive#3.2.2     invalid-meta jquery-validation-unobtrusive is missing "ignore" entry in bower.json
    remote: bower jquery-validation-unobtrusive#3.2.2         resolved git://github.com/aspnet/jquery-validation-unobtrusive.git#3.2.2
    remote: bower hammer.js#2.0.4                              extract archive.tar.gz
    remote: bower bootstrap-touch-carousel#0.8.0               extract archive.tar.gz
    remote: bower hammer.js#2.0.4                                retry Decompression of archive.tar.gz failed with ENOSPC, trying with git..
    remote: bower jquery-validation#1.11.1                     extract archive.tar.gz
    remote: bower hammer.js#2.0.4                             checkout 2.0.4
    remote: bower bootstrap-touch-carousel#0.8.0              resolved git://github.com/ixisio/bootstrap-touch-carousel.git#0.8.0
    remote: bower jquery-validation#1.11.1                       retry Decompression of archive.tar.gz failed with ENOSPC, trying with git..
    remote: bower bootstrap#3.0.0                                retry Download of https://github.com/twbs/bootstrap/archive/v3.0.0.tar.gz failed with ENOSPC, trying with git..
    remote: bower bootstrap#3.0.0                             checkout v3.0.0
    remote: bower jquery#2.1.4                              not-cached git://github.com/jquery/jquery.git#2.1.4
    remote: bower jquery#2.1.4                                 resolve git://github.com/jquery/jquery.git#2.1.4
    remote: bower jquery#2.1.4                                download https://github.com/jquery/jquery/archive/2.1.4.tar.gz
    remote: bower jquery#2.1.4                                 extract archive.tar.gz
    remote: bower jquery#2.1.4                                   retry Decompression of archive.tar.gz failed with ENOSPC, trying with git..
    remote: bower jquery-validation#1.11.1                       EPERM EPERM, unlink 'D:\local\Temp\WORKGROUP-RD00155D562DDD$\bower\jquery-validation-12848-iilsgU\archive.tar.gz'
    remote: The 'prepublish' script failed with status code 1.
    remote: An error has occurred during web site deployment.
    remote: 
    remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by davidfowl** [comment]
Looks like an NPM problem

**Comment by dimsedane** [comment]
Okay, turned out that was a bower issue, which has since been fixed. 

However, I still had problems where requests would time out. I have just fixed that by removing the dnxcore50 framework from project.json and creating a global.json file with the following contents:

    {
        "sdk": {
            "version": "1.0.0-beta8",
            "runtime": "clr"
        },
        "packages": "packages"
    }

Deploying the application to azure using git now results in a working site. That you for your help!

**Comment by tdekoekkoek** [comment]
I'm getting this.  Pushing to Azure has been a nightmare.  Constant errors.  I can't even republish from within Visual Studio.

**Comment by artemgrygor** [comment]
Any updates here? Still have the same issue.

**Comment by GuardRex** [comment]
@artemgrygor You're not on the Free tier, correct?

**Comment by artemgrygor** [comment]
@GuardRex I was on Shared tier. On Basic it's fine, so I'm going with Basic one. Thanks

**Comment by GuardRex** [comment]
That's cool ... then it's not simply a footprint size (i.e., https://github.com/aspnet/dnx/issues/3192).

I have the mostly known Azure issues with Azure Apps in my comment. It's mostly updated, but I'll update all of the issue links within a week or two. https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by JohnGalt1717** [comment]
this is the closest to working that I've found: https://msdn.microsoft.com/en-us/library/vs/alm/build/azure/deploy-aspnet5

But it errors on the deploy to azure step and I have yet to figure out how to get release management do the deploy instead of the build step which for obvious reasons isn't the way you want it to work.
