### ISSUE TITLE
script to install dnvm beta8

### ISSUE THREAD

**Issue by ctaggart** [aspnet/dnx#3002]
Is there a script that I can run to install version 1.0.0-beta8-15521?

If I run this, it installs the  older 1.0.0-rc1-15527.

http://dotnet.readthedocs.org/en/latest/getting-started/installing-core-windows.html
```
&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}
```

**Comment by davidfowl** [comment]
that just gets dnvm after installing it you can install any dnx you want.

**Comment by davidfowl** [comment]
The dnvm version is irrelevant

**Comment by ctaggart** [comment]
K
