### ISSUE TITLE
dnx build is creating an incorrect mono runtime

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#3011]
I started seeing this as the mono runtime:

```
1.0.0-dnx-mono.1.0.0-dev-dnx-mono.1.0.0-dev.1.0.0-dev mono    x86/x64      linux/osx       mono-dev (missing)
```

Initially I thought I just did something wrong but then I saw it on @pakrym's box and then it reappeared on my box again after I deleted it.

**Comment by davidfowl** [comment]
nice
