### ISSUE TITLE
Support Startup.Main entrypoint

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#3020]
Just in case we don't get this for RC https://github.com/dotnet/corefx/issues/3336

/cc @muratg

**Comment by muratg** [comment]
:+1:

**Comment by anurse** [comment]
To make sure I fully understand the plan, we just need to update https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime.Sources/Impl/EntryPointExecutor.cs#L70 to check `Assembly.EntryPoint` and use that, correct? Do we want to fall-back to the old logic or just make a clean break?
