### ISSUE TITLE
[Announcement] Changes to assembly signing

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#3029]
Discussion for https://github.com/aspnet/Announcements/issues/86

**Comment by fmarcoux96** [comment]
Little typo: [...] that ships with the {?} to sign the assembly.

**Comment by moozzyk** [comment]
@fmarcoux96 - fixed, thanks

**Comment by alexmg** [comment]
It would be good if you defined what OSS signing is. The announcement doesn't describe how that is different to regular signing or why you would use one over the other.

**Comment by alexmg** [comment]
Here is a link to the Open Source Signing documentation page for those who are interested.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/oss-signing.md

It might be worthwhile adding the link to the announcement for context.

**Comment by moozzyk** [comment]
@alexmg - I updated the announcement to include the link to the OSS signing post from the corefx repo.

**Comment by alexmg** [comment]
:thumbsup:

**Comment by GuardRex** [comment]
@moozzyk May I ask about a signing scenario ... I just dropped `Microsoft.Aspnet.Razor` into my app as a project add-in so that I could make some mods to it. Locally when I went to compile and execute, it complained about not having the `Key.snk` file at `C:\tools`. I created that folder and dropped the `Key.snk` file in ... worked great locally. When I published the app, it threw on the server, requesting the `Key.snk` file at `\approot\tools\`. I manually created that folder on the server and gave it the file, and it was cool with that. Two questions:

1. If I'm only supposed to provide the file such as I am in these cases, how do I get dnx/VS to publish the `Key.snk` file to `approot\tools` (or look for it where it ends up), when what VS really wants to do is take any folder in the project root (e.g., if I put the tools folder in project root) and publish it to `C:\PROJ_FOLDER\src\PROJECT\bin\output\approot\packages\MY_PROJECT\1.0.0\root\tools` so it ends up on the server in `F:\WEBSITE_FOLDER\approot\src\MY_PROJECT\tools` ... but on the server, the file is sought at `F:\WEBSITE_FOLDER\approot\tools` (which is where I had to manually put it)?

2. If that's all wrong and I'm not supposed to be using/placing the `Key.snk` file like this, what should I be doing or can you point me to a good online resource to explain the basics of assembly signing keys for an IIS environment app?

**Comment by davidfowl** [comment]
`c:\tools\`? Sounds like `Path.Combine` bug. The key file should be picked up as a relative path from the project file. When you copied Razor did you copy the keyfile from the relative location? One problem might be the fact that we have the key file in the solution root and publish doesn't take that into account. You should publish --no-source and just work around the whole problem.

**Comment by GuardRex** [comment]
@davidfowl ... Regarding it being on the relative path (as it's found in the Razor repo download), no, and that's probably what I screwed up not knowing any better. I just took the `Microsoft.AspNet.Razor` folder out of the `Razor-release\src` folder and just dropped it right into my app (into my `src` folder). It was quick to just drop in in that way and add it to `project.json` and `global.json` and it :sparkles: just works, but that might be a totally wrong way to do it.

**Comment by davidfowl** [comment]
@GuardRex you need to tweak this value:

https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor/project.json#L6

**Comment by GuardRex** [comment]
@davidfowl BRILLIANT! Perfect. Thanks! ... again!!!!

**Comment by GuardRex** [comment]
@davidfowl Still not working for me. If I setup the project key location like this in `project.json` ...
```
"keyFile": "tools/Key.snk"
```
... and I have a `tools` folder in the solution (at the same level as the `project.json` file), then it finds the file locally and VS doesn't choke.

When I VS publish and move the bits, the `tools` folder ends up here on the server ...
```
F:\PROJECT_FOLDER\approot\src\PROJECT_NAME\tools
```
... but it chokes to a 500. When I click `web.cmd` to see what's what in the console window, it states ...
```
Could not find part of the path 'F:\PROJECT_FOLDER\approot\tools\Key.snk'
```
I can invoke a PS script to move the file to that spot in the output folder, but is that really the way that you want this to work?

Here's more of the spew in case it helps ...

![capture](https://cloud.githubusercontent.com/assets/1622880/11402947/12c56652-934f-11e5-9927-09d1ffc59ace.PNG)

**Comment by GuardRex** [comment]
Workaround ...

Publishing to ...
```
C:\PROJECT_FOLDER\src\PROJECT\bin\output2
```
... create a PS script (`copy-key-file.ps1`) ...
```
New-Item C:\PROJECT_FOLDER\src\PROJECT\bin\output2\approot\tools -type directory -Force | Out-Null
Copy-Item -Path tools\Key.snk -Destination C:\PROJECT_FOLDER\src\PROJECT\bin\output2\approot\tools -Force
```
... and hook it in `project.json` on ...
```json
"scripts":  {
    "prepare": "powershell.exe -ExecutionPolicy ByPass -file %project:Directory%/copy-key-file.ps1"
},
```
... have this in `project.json` ...
```json
"compilationOptions":  {
    "keyFile": "tools/Key.snk"
},
```
... and put the `Key.snk` key file in a `tools` folder in the solution (at the same level as the `project.json` file).

... but I'm guessing you will say this is not so good jumping through all of these hoops.

**Comment by davidfowl** [comment]
Publish --no-source. What you're seeing is us not preserving or copying enough of the original project structure on publish when replaying source code

**Comment by GuardRex** [comment]
Is there a --no-source option for using VS's publish command?

**Comment by GuardRex** [comment]
Found out that the VS setting for `Compile source files into NuGet packages` adds the `--no-source` flag to the `dnu publish` command. `Key.snk` present in `tools` folder and found in the right spot. I'm good.

**Comment by moozzyk** [comment]
@GuardRex - if you publish with `--no-source` you actually should not need the `.snk` at all. If it is copied it is a bug. (`.snk` files are needed only to build assemblies and `--no-source`

**Comment by GuardRex** [comment]
Ah ... I see. I'll be back in the office this afternoon to confirm as u say
that there is no copy, thus no bug with --no-source. All I know this far is
that --no-source did prevent the exception.

**Comment by GuardRex** [comment]
@moozzyk I returned to the office too late today to take a second look. I do want to re-trace my steps to confirm the expected behavior. I should have time tomorrow evening. I'll get back you --

**Comment by moozzyk** [comment]
@GuardRex - no worries...

**Comment by GuardRex** [comment]
@moozzyk Ok ... back ... finally. Crazy week.

Good ... behavior confirmed. When VS publish has the File Publish Option "Compile source files into NuGet packages" checked, `--no-sources` is added to the underlying `dnu publish` command and the `Key.snk` file is *not* requested/required. I'm good. Thanks.

btw- Tooling is going to add something like "`(--no-sources)`" to that VS publish option text so everyone will know that's what the option is going to do. https://github.com/aspnet/Tooling/issues/318

**Comment by moozzyk** [comment]
Great! Thanks for confirming!
