### ISSUE TITLE
dnu restore and dnu publish don't play nice.

### ISSUE THREAD

**Issue by btrepp** [aspnet/dnx#3030]
Using the 'standard' directory structure.

```
src/
     App.Stuff/
            project.json
test/
    App.Stuff.Test/
           project.json
global.json
```

Where global.json is
```
{
    "sources": ["src","test"]
}
```

and the test project.json has
```
.....
     "dependencies":{
             "App.Stuff" : ""
     }
....
```

If you run `dnu publish` in the app.stuff directory. You get a path with `App.Stuff/bin/output/approot/src/App.Stuff/project.json`

This completely breaks `dnu restore` at the root directory. It can't resolve the references in the `App.Stuff.Test/project.json` because its recursively walking down the tree all the way to the second one. You get ambigous references to `App.Stuff` because the src is copied to the ouput in dnu publish.

Is there way to tell dnu restore to not walk down through the `bin` folders?. Eg limiting it to top layers only. Its easier in build servers to just run `dnu restore` at the top directory, rather than per project.

I can make the build server clean everything, but that is less than ideal as I would like it to not have to recompile things again and again if its not necessary.

**Comment by davidfowl** [comment]
This is already fixed in the latest builds /cc @troydai

**Comment by troydai** [comment]
@btrepp this commit should have addressed this issue: https://github.com/aspnet/dnx/commit/0dda8bf86863364cc20421f1af7494f1b2a3256f. `dnu restore` won't walk in the subdirectory if there is a `project.json` already present at current folder. Would you please try your scenario on the latest build?

**Comment by btrepp** [comment]
Upgrading to the latest unstabl (15838) seems to have fixed the issue.

Thanks.
