### ISSUE TITLE
Visual Studio 2015 "Exclude from project"

### ISSUE THREAD

**Issue by joshmouch** [aspnet/dnx#3033]
How do you exclude a file from a DNX project in Visual Studio 2015?  I tried "Hide from Solution Explorer", but "hidden" files are still included when you build the project.

It used to be that you could right click any file in the project and click "exclude from project".  This is essential for many, many reasons, and I use this all the time.  For example, 3rd party applications may add random files to the project structure that you do not want to build with your project (e.g. Dropbox, Apple's file share crap, Visual Studio plugins, SVN, GIT, TFS, whatever, etc.).  As another example, there may be files you want in your project folder for whatever reason but that are irrelevant to Visual Studio development experience (e.g. you use a 3rd party app to generate documentation from your code comments and it has a whole set of configuration files). For example, if you are adding code but aren't finished with it yet and need to move to something else.  For another example, if you're migrating code and need to fix it piece by piece.  For another example, if there is a class you no longer need but that you believe you'll need in the future.  For another example, if you are having trouble getting EF Migrations to work correctly, and you want to remove a few entities temporarily to simplify the configuration.  The list goes on and on.  The ability to add and remove code quickly via exclusion is essential.

Here's another great example: you include the bootstrap library using NuGet.  This library contains hundreds of "demo" files that you care nothing about.  You *especially* don't want these files to be included in your search result when you're doing a project-wide search.  You *especially* don't want to hit ctrl-shift-t, have Resharper pop up, start typing a filename, and then have hundreds of irrelavent "demo" files show up in the search results.  With the old project type, you would just exclude these folders you never want to think about again.  You can't just delete them, because the next time you update the library using NuGet, the folders will come back again.

Removing this ability alone would be enough to make me never want to use another .xproj again.  If for no other reason, now when you do a project-side search or else a file search (through Resharper), Visual Studio now searches potentially hundreds of 3rd-party library files you care nothing about.

Are you no longer able to exclude items from the project?

**Comment by muratg** [comment]
@joshmouch you may want to file this in https://github.com/aspnet/tooling repo. I believe @sayedihashimi has been thinking about this too.

**Comment by sayedihashimi** [comment]
Yes we have a feature to support excluding files in Visual Studio. We are currently working on other higher priority work but it is a feature I very much would like to deliver.

**Comment by MelbourneDeveloper** [comment]
Why is this not the highest priority?

With the new xproj format, you cannot link a file in from another project. And, at the same time, you can't exclude files from the folder structure. This means you literally cannot share code files (.cs files) between two platforms because you need to make physical copies of the files and then delete the files that you don't want, or use conditional compilation symbols which is currently broken in .NET Core. 

 I have documented issues with .NET Core (xproj) projects, including this one, here:
https://github.com/dotnet/cli/issues/4022#issuecomment-238777946

**Comment by muratg** [comment]
@MelbourneDeveloper DNX repo is defunct. Please continue discussion on this at dotnet/cli or aspnet/tooling. Thanks.

**Comment by MelbourneDeveloper** [comment]
I have logged the problem here:
https://github.com/aspnet/Tooling/issues/723

**Comment by MelbourneDeveloper** [comment]
The aspnet/tooling team snuck this functionality in to the project.json at some point. It seems you can't do it through the VS front end, but you can do it by manually editing the project.json. Here is a sample app that shows you how to exclude files:

https://dl.dropboxusercontent.com/u/79781769/Sample%20Apps/ExcludeFileSample2.zip
