### ISSUE TITLE
Incorrect "unsupported package for framework" nuget errors (NU1002)

### ISSUE THREAD

**Issue by tmds** [aspnet/dnx#3034]
A while ago I logged [an issue](https://github.com/aspnet/dnx/issues/2712) which only occurred when I used AppVeyor to build my project. Now that I have upgraded to beta8 it also happens in my development machine.

The reference section of my project looks like this:

![screenshot2](https://cloud.githubusercontent.com/assets/1025424/10641308/fade6d32-7818-11e5-8989-5b3105e101d0.png)

I have a similar error dnx451: The dependency System.Threading 4.0.0 does not support framework DNX,Version=v4.5.1.

![screenshot3](https://cloud.githubusercontent.com/assets/1025424/10641693/979a739a-781a-11e5-9464-082e10672f2a.png)

The information on nuget suggests these assemblies are supported on those platforms [System.Reflection.Extensions](https://www.nuget.org/packages/System.Reflection.Extensions/4.0.0) and [System.Threading](https://www.nuget.org/packages/System.Threading/4.0.0)

**Comment by tmds** [comment]
I cleared my .dnx/packages folder to see whether that would fix the problem. Now the NU1002 error has moved to another package.
![screenshot4](https://cloud.githubusercontent.com/assets/1025424/10644347/876f1954-7828-11e5-9fe1-6aaba070f8b6.png)

**Comment by NiyazShoukath** [comment]
i have also same issue?

**Comment by tsvetomir** [comment]
+1

**Comment by ericstj** [comment]
Indeed all of these are supported on the platforms being called out.  Looks to me like some sort of DNX or NuGet issue.  The lock file and/or the restore spew may point to the problem.

**Comment by davidfowl** [comment]
Something seems to be pulling in lower versions. I don't see this locally though.

**Comment by ericstj** [comment]
All the versions listed in this thread contain both ref and implementation, so even if a lower version was brought in it doesn't explain why it would trip up the compat check.

**Comment by tmds** [comment]
@ericstj @davidfowl Can you reproduce this on your machines using this project:  https://github.com/tmds/Tmds.SockJS ?

**Comment by davidfowl** [comment]
It's failing for dnx451

**Comment by tmds** [comment]
@davidfowl 
Do you get NU1002 in dnx451?
Does the Core 5.0 part build?
Can you investigate the problem further on your machine?

Btw, I was in the middle of changing to beta8 when I encountered this issue, so there might be some loose ends.

**Comment by davidfowl** [comment]
@tmds I'll try out your solutionnow.

**Comment by tmds** [comment]
@davidfowl are you able to reproduce the issue?

**Comment by tsvetomir** [comment]
Please note that, at least for me, the application runs fine with `dnx web`. It's only in Visual Studio where it throws an error on build.

**Comment by tmds** [comment]
For me, even my AppVeyor build fails with these errors: https://ci.appveyor.com/project/tmds/tmds-sockjs/branch/master

**Comment by tmds** [comment]
I had a closer look at project.json.lock.and it seemed empty for the problematic package
```
      "System.IO.FileSystem.Primitives/4.0.0": {
        "type": "package"
      },
```
So I opened up the nuget package file under.dnx\packages\System.IO.FileSystem.Primitives\4.0.0\System.IO.FileSystem.Primitives.4.0.0:
![nuget](https://cloud.githubusercontent.com/assets/1025424/10777712/840f04e0-7d1e-11e5-9494-f468311e0da7.png)
This doesn't seem right ...
@davidfowl @ericstj any thoughts?

**Comment by davidfowl** [comment]
Yes, you are pointing to a super old feed:

https://github.com/tmds/Tmds.SockJS/blob/master/NuGet.Config#L6

Remove it.

**Comment by tmds** [comment]
@davidfowl ok thanks, the reason I chose this feed is because it is used on the beta8 tags: e.g. [Mvc](https://github.com/aspnet/Mvc/blob/6.0.0-beta8/NuGet.config#L6), [WebSockets](https://github.com/aspnet/WebSockets/blob/1.0.0-beta8/NuGet.config)

Which feed should I use?

**Comment by davidfowl** [comment]
Why do you need it?

**Comment by tmds** [comment]
AppVeyor doesn't seem to find KoreBuild without it: https://ci.appveyor.com/project/tmds/tmds-sockjs/build/1.0.0-beta8-86

**Comment by davidfowl** [comment]
Ah, Try using the aspnetvnext feed for that. Master needs to be cleaned up.

**Comment by tmds** [comment]
That doesn't seem to work: https://ci.appveyor.com/project/tmds/tmds-sockjs/build/1.0.0-beta8-88
https://github.com/tmds/Tmds.SockJS/commit/8cec5dd5345bde2a9fbba3b1ab90a3df77b0aee7

**Comment by tmds** [comment]
@davidfowl what feed should I use to get KoreBuild 0.2.1-beta8?

**Comment by pranavkm** [comment]
@tmds that package should be located on `https://www.myget.org/f/aspnetmaster`

**Comment by tmds** [comment]
@pranavkm this is the feed I shouldn't use to avoid the issue at the top of this thread (see @davidfowl's  https://github.com/aspnet/dnx/issues/3034#issuecomment-151696986)
Looks like I am stuck in an issue-loop :)

What feed should I use if I want to shop form the latest release (beta8)?

**Comment by Eilon** [comment]
Sorry, what needs to be cleaned up? Some RTM-looking packages in the aspnetmaster feed?

**Comment by pranavkm** [comment]
Looks like it - `System.IO.FileSystem.Primitives` in his case. I removed a bunch of these the last time we were branching master.

**Comment by tmds** [comment]
@pranavkm @Eilon restoring System.IO.FileSystem.Primitives from nuget got rid of the error for me. Please remove it from the aspnetmaster.

Next issue: I have about 100 errors like this:
```
Error	CS1705	Assembly 'x' with identity 'xxx' uses 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
I searched 4.0.10.0 in the project.lock.json file but it was no where to be found. It did contain references to "4.0.21-beta-23409", "4.0.20" and "4.0.0".
My project.json has an explicit System.Runtime dependency: "System.Runtime": "4.0.21-beta-*".

Why do I get this error? And what can I do about it?

**Comment by Eilon** [comment]
@pranavkm do you know which bad packages to look for and destroy? Presumably the "RTM-looking" packages are never needed, right?

**Comment by pranavkm** [comment]
Any package with a RTM version (4.0.0.0 \ 4.0.10.0 \ 4.0.20.0) etc can be safely deleted.

**Comment by Eilon** [comment]
How easy is it to get a list of the bad packages?

**Comment by pranavkm** [comment]
```
Microsoft.CodeAnalysis.Analyzers, 1.0.0
Microsoft.CSharp, 4.0.0.0
Microsoft.Win32.Primitives, 4.0.0.0
Microsoft.Win32.Registry, 4.0.0.0
System.ApplicationContext, 4.0.0.0
System.Collections.Specialized, 4.0.0.0
System.ComponentModel.Annotations, 4.0.10.0
System.Diagnostics.Contracts, 4.0.0.0
System.Diagnostics.FileVersionInfo, 4.0.0.0
System.Diagnostics.TextWriterTraceListener, 4.0.0.0
System.Dynamic.Runtime, 4.0.0.0
System.Globalization, 4.0.10.0
System.Globalization.Extensions, 4.0.0.0
System.IO.Compression, 4.0.0.0
System.IO.Compression.ZipFile, 4.0.0.0
System.IO.FileSystem, 4.0.0.0
System.IO.FileSystem, 4.0.10.0
System.IO.FileSystem.DriveInfo, 4.0.0.0
System.IO.FileSystem.Primitives, 4.0.0.0
System.IO.FileSystem.Primitives, 4.0.10.0
System.IO.FileSystem.Watcher, 4.0.0.0
System.IO.MemoryMappedFiles, 4.0.0.0
System.IO.Pipes, 4.0.0.0
System.IO.UnmanagedMemoryStream, 4.0.0.0
System.Linq, 4.0.0.0
System.Linq.Expressions, 4.0.0.0
System.Linq.Parallel, 4.0.0.0
System.Linq.Queryable, 4.0.0.0
System.Net.Http, 4.0.0.0
System.Net.Http.WinHttpHandler, 4.0.0.0
System.Net.NetworkInformation, 4.0.10.0
System.Net.Primitives, 4.0.10.0
System.Net.Sockets, 4.0.0.0
System.Runtime, 4.0.20.0
System.Runtime.CompilerServices.VisualC, 4.0.0.0
System.Runtime.Extensions, 4.0.10.0
System.Runtime.InteropServices, 4.0.20.0
System.Runtime.Loader, 4.0.0.0
System.Runtime.Serialization.Json, 4.0.0.0
System.Runtime.Serialization.Primitives, 4.0.0.0
System.Runtime.Serialization.Xml, 4.0.0.0
System.Security.Cryptography.DeriveBytes, 4.0.0.0
System.Security.Cryptography.Encoding, 4.0.0.0
System.Security.Cryptography.Encryption, 4.0.0.0
System.Security.Cryptography.Encryption.Aes, 4.0.0.0
System.Security.Cryptography.Encryption.RSA, 4.0.0.0
System.Security.Cryptography.Hashing, 4.0.0.0
System.Security.Cryptography.Hashing.Algorithms, 4.0.0.0
System.Security.Cryptography.RandomNumberGenerator, 4.0.0.0
System.Security.Cryptography.X509Certificates, 4.0.0.0
System.Security.SecureString, 4.0.0.0
System.ServiceModel.Http, 4.0.0.0
System.ServiceModel.Primitives, 4.0.0.0
System.Text.Encoding.CodePages, 4.0.0.0
System.Text.Encoding.Extensions, 4.0.10.0
System.Text.RegularExpressions, 4.0.0.0
System.Threading.ExecutionContext, 4.0.0.0
System.Threading.Tasks.Parallel, 4.0.0.0
System.Xml.ReaderWriter, 4.0.10.0
System.Xml.XDocument, 4.0.0.0
System.Xml.XmlDocument, 4.0.0.0
System.Xml.XmlSerializer, 4.0.0.0
System.Xml.XPath, 4.0.0.0
System.Xml.XPath.XDocument, 4.0.0.0
System.Xml.XPath.XmlDocument, 4.0.0.0
```

From: http://myget.org/f/aspnetmaster/api/v2/Packages?$filter=IsPrerelease%20eq%20false

**Comment by tmds** [comment]
@Eilon Please let me know when you've removed the packages.

**Comment by Eilon** [comment]
Ok, all the "RTM-looking" packages have been deleted from the MyGet / aspnetmaster feed. Please note that due to caching some packages might still appear to be there for several minutes.

**Comment by Eilon** [comment]
BTW you also need to clear out your local NuGet caches.

**Comment by tmds** [comment]
Thanks @Eilon @pranavkm @davidfowl, my project is building fine now!

**Comment by cmadrid86** [comment]
Hi, I have a similar issue with my project. Currently I am getting the following error:
NU1002 The dependency AA.Core 2.0.41 in project AA.Web.Core does not support framework DNX,Version=v4.5.1.

My project AA.Core 2.0.41 is not a vnext project, but since I created my own nuget server, I started to get this issue. Also, previously I had a local folder as a nuget feed and the AA.Core package was created based on a nuspec file, but to have the dependencies automatically, I changed the nuget pack command to generate the package from the project file.

I hope you have an idea about the error.

Thank you!

**Comment by Eilon** [comment]
@cmadrid86 can you log a new issue for that? Thanks!

**Comment by ericwj** [comment]
To summarize

    RMDIR /S /Q "%USERPROFILE%\.dnx\packages"

Deletes some 1.6GB !! of packages on my machine. Took a while. Did fix the problem.

Is switching to dev branch and the aspnetmaster feed polluting .dnx\packages machine wide? Would it become a problem again for projects that I'd like to stay on rc1-final and the aspnetrelease feed for a while?

**Comment by pranavkm** [comment]
@ericwj we had back packages on aspnetmaster which were causing the original issue. You shouldn't see it any more. Pointing to nuget.org should suffice if you only want to point to rc1 bits (unless you depend on our source packages or KoreBuild which are found on `aspnetmaster`).

**Comment by Namrata-AdvancedTicketing** [comment]
Microsoft.Extensions.Configuration.Xml does not support DNXcore version 5.0

**Comment by davidfowl** [comment]
Why are you still using dnx?
