### ISSUE TITLE
"DNU pack" should support packing more files types into nupkg

### ISSUE THREAD

**Issue by yan-li** [aspnet/dnx#3039]
In our scenario, a dependent external library A.dll requires access to A.dll.config in the runtime.
However when I wrap A.dll with the DNX concept, A.dll.config is ignored when creating the nupkg.

Hope to have a way to enclose this kind of configuration files to the package so they could be leveraged in the runtime.

By traversing the code, it appears that only dll and xml are included for the moment.
 
https://github.com/aspnet/dnx/blob/cc99b276cbb9734e4d65dea0c99165f095681421/src/Microsoft.Dnx.Tooling/Building/BuildManager.cs
```
context.AddLibs(packageBuilder, "*.dll");
context.AddLibs(packageBuilder, "*.xml");
context.AddLibs(packageBuilder, "*.resources.dll", recursiveSearch: true);
```

**Comment by per-samuelsson** [comment]
Title "dnx pack" -> "**dnu** pack", right?

**Comment by yan-li** [comment]
Thanks Per, you're right. Fixed.

**Comment by moozzyk** [comment]
Have you tried using `packInclude` in your project.json? See http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx for more details.

**Comment by yan-li** [comment]
Thanks @moozzyk, it works as a charm.
It appears that the wiki page is out of date. https://github.com/aspnet/Home/wiki/Project.json-file
