### ISSUE TITLE
i found  in web  refference package loading: error in VS 2015 beta8 , how can solve ?

### ISSUE THREAD

**Issue by NiyazShoukath** [aspnet/dnx#3041]

**Comment by davidfowl** [comment]
No idea, you need to provide more details if you want to get help :smile:

**Comment by NiyazShoukath** [comment]
![error](https://cloud.githubusercontent.com/assets/14939784/10664459/3a4dcebe-78cc-11e5-9fbc-a4414ba7f3a1.png)

**Comment by Kagamine** [comment]
You can have a try to open the project.json, and type Ctrl+S many times quickly & frequently. It will be solved.

**Comment by davidfowl** [comment]
What's in `global.json`

**Comment by Kagamine** [comment]
src only

**Comment by NiyazShoukath** [comment]
@kagamine i have check your solution. but,stil same error 

i am using VS 2015 : beta8 version
DNX : 1.0.0-beta8-15858

OS windows 10

**Comment by tmds** [comment]
Is this also NU1002 like https://github.com/aspnet/dnx/issues/3034 and https://github.com/aspnet/dnx/issues/3055? Or is it a different error code?

**Comment by davidfowl** [comment]
@NiyazShoukath push your repository to github let me take a look

**Comment by tmds** [comment]
@davidfowl I have similar issues (see https://github.com/aspnet/dnx/issues/3034). My repo is at https://github.com/tmds/Tmds.SockJS. Can you have a look?

**Comment by davidfowl** [comment]
@tmds Try removing all of these:

https://github.com/tmds/Tmds.SockJS/blob/master/src/Tmds.SockJS/project.json#L23-L31

I'm not sure you need them and depending on your nuget feed you might be pulling in busted packages.

**Comment by tmds** [comment]
@davidfowl Removing the dependencies doesn't fix the issue. It gives me extra errors 'are you missing an assembly reference'.
[My AppVeyor build](https://ci.appveyor.com/project/tmds/tmds-sockjs/build/1.0.0-beta8-84#L396) is also suffering from these issues. For example it says:
```
C:\projects\tmds-sockjs\src\Tmds.SockJS\project.json(0,0): error NU1002: The dependency System.IO.FileSystem.Primitives 4.0.0 in project Tmds.SockJS does not support framework DNXCore,Version=v5.0. 
```
[Nuget](https://www.nuget.org/packages/System.IO.FileSystem.Primitives/4.0.0) tells me this package IS supported on DotNet 5.0.

**Comment by NiyazShoukath** [comment]
@ davidfowl  @tmds  it cant solve

**Comment by NiyazShoukath** [comment]
![error33](https://cloud.githubusercontent.com/assets/14939784/10715951/0f9e88ec-7b39-11e5-93f7-46a2ae4c7a33.png)

**Comment by NiyazShoukath** [comment]
@ericstj  how can solve this
