### ISSUE TITLE
RuntimeOptions is set as null.

### ISSUE THREAD

**Issue by xanather** [aspnet/dnx#3044]
For example:
```
        private RuntimeOptions runtimeOptions;
        private IRuntimeEnvironment runtimeEnvironment;
        private ILibraryManager libraryManager;

        public Program(RuntimeOptions runtimeOptions, IRuntimeEnvironment runtimeEnvironment, ILibraryManager libraryManager)
        {
            this.runtimeOptions = runtimeOptions;
            this.runtimeEnvironment = runtimeEnvironment;
            this.libraryManager = libraryManager;
        }

```
After Program initializes runtimeOptions is null? This only just started occurring with beta8 release.

Both IRuntimeEnvironment and ILibraryManager fields get set fine.

**Comment by davidfowl** [comment]
Why are you accessing runtime options?

**Comment by xanather** [comment]
I am currently using the RuntimeOptions class to obtain the ApplicationBaseDirectory property (which is then used to load assets/content of the program). Another reason I am using it can be shown:
```
Library programLibrary = libraryManager.GetLibrary(runtimeOptions.ApplicationName);
```

Where libraryManager is an ILibraryManager.

Since this code is within a DNX library this is used to discover the host dnx "console" app making use of the library.

**Comment by davidfowl** [comment]
That's wrong, don't use it. Use IApplicationEnvironment instead

**Comment by xanather** [comment]
Ahh, okay, thanks for that, didn't know it existed (must be new?).

**Comment by davidfowl** [comment]
@xanather very old :smile:
