### ISSUE TITLE
DNU always HTTP request timed out. Retrying.

### ISSUE THREAD

**Issue by Kagamine** [aspnet/dnx#3045]
![image](https://cloud.githubusercontent.com/assets/2216750/10667600/b22d4db8-790a-11e5-835b-02bfc687789f.png)

![image](https://cloud.githubusercontent.com/assets/2216750/10667939/7f31f9de-790c-11e5-9d14-753acfed9372.png)

![image](https://cloud.githubusercontent.com/assets/2216750/10668010/cab00f36-790c-11e5-8c74-b8c190e535d2.png)

I cannot restore the packages! HELP!

I tried to restore many times, it takes me 4 hours, and it has not been solved!!!

@davidfowl

**Comment by Kagamine** [comment]
It can be restored successfully in Windows, but failed with OSX.

**Comment by hantleman** [comment]
execute mozroots --import --sync should solve problem for linux
