### ISSUE TITLE
Support server side rendering with JavaScript in DNX + Debugging

### ISSUE THREAD

**Issue by Lenne231** [aspnet/dnx#3053]
We would like to do the server side HTML rendering with ReactJS, but if we stick with ASP.NET as the backend there is currently no simple way to do this. Possible is:

1. An additional NodeJS service for rendering and use this from the ASP.NET application
2. Use EdgeJS to run JS inside the ASP.NET application
3. ?

We would prefer the solution with EdgeJS, but we can't debug the JS code in VS with this.

**Comment by davidfowl** [comment]
This isn't a dnx issue. File this on aspnet/Home and possibly aspnet/Tooling for the debugging piece.

**Comment by alexsandro-xpt** [comment]
:point_up_2:
