### ISSUE TITLE
ProjectName\project.json(0,0): error NU1002: The dependency Microsoft.Win32.Primitives 4.0.0 in project ProjectName does not support framework DNXCore,Version=v5.0.

### ISSUE THREAD

**Issue by kosmakoff** [aspnet/dnx#3055]
It might be a somewhat general issue, but I hope if I figure out how to solve this one - I will be able to solve others.

Basically, I am receiving the error from the title when trying to run **dnu build** in my project directory.
Note that I have added 2 of aspnet project sources to my global.json in order to debug them. It is after I added those sources I started to experience these problems, when I had my project standalone it built fine. Aspnet libs I referenced are **MVC** and **Security**. After I fetched them from github, I updated them to beta8 revision. My project is also beta8.

I tried literally everything trying to fix the issue: cleaned packages cache folder, deleted lock files and regenerated them by running the restore command - nothing helps.

DNVM I use is **CoreClr-x64-1.0.0-beta8-15858**

**Comment by tmds** [comment]
Looks similar to [my issue](https://github.com/aspnet/dnx/issues/3034).

**Comment by kosmakoff** [comment]
Indeed it looks like it.

Still, can't find a solution to this problem.

**Comment by NiyazShoukath** [comment]
how can solve this ?

**Comment by kosmakoff** [comment]
I figured out that it was outdated nuget packages config that caused problems. Issue was solved when I simply copied aspnet repo nuget.config to my project directory.
