### ISSUE TITLE
Solution Structure Causes DNX Restore to Fail

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/dnx#3056]
With VS 2015 - I have 4 projects within a solution. After creating the first project ( called component ), I add the 3 other projects to the src folder of component. After this I have:

..\component ( with the .sln )
..\component\src ( with the 4 xproj )
..\component\src\component.services ( asp.net class library )
..\component\src\component.dal ( asp.net 5 class library )
..\component\src\component.web ( asp.net 5 class library )
..\component\src\component.test ( asp.net 5 web application )

After adding the web application to the solution, DNX fails on the project restore. If I remove component.test from src and then add it to the solution so that I have

..\component\component.test

then DNX restore resolves all the dependencies fine.

For what it's worth: The above component structure is: component.services and component.dal for the backend; component.web for client side; component.test for testing.

**Comment by gach87** [comment]
I had a similar problem in beta7, needed to add the proper paths to the folders where projects are stored in global. json
