### ISSUE TITLE
AspNet 5 project can not be loaded because of node_modules directory

### ISSUE THREAD

**Issue by everydev** [aspnet/dnx#3067]
When the directory node_modules in the folder wwwroot is very deep because of too much dependencies in sub pacjages, the project can not reopen. The project should ignore the folder node_modules like it's the case for the folder Packages.

Here are the dependencies I use for my project:

"dependencies": {
    "es6-shim": "^0.33.6",
    "flux": "^2.1.1",
    "object-assign": "^1.0.0",
    "bootstrap": "^3.3.5",
    "counterpart": "^0.17.0",
    "jquery": "^2.1.4",
    "jsonwebtoken": "^5.4.0",
    "react": "^0.14.0",
    "react-interpolate-component": "^0.8.0",
    "react-router": "~1.0.0-rc3",
    "history": "^1.12.5",
    "react-translate-component": "^0.10.0",
    "underscore": "^1.8.3",
    "sifter": "^0.4.4",
    "react-select": "^0.8.1",
    "openpgp": "^1.3.0",
    "pdfkit": "^0.7.1"
  },
  "devDependencies": {
    "babel": "^5.8.23",
    "gulp-babel": "^5.3.0",
    "browser-sync": "^2.9.11",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-cache": "^0.3.0",
    "gulp-changed": "^1.3.0",
    "gulp-csscomb": "^3.0.6",
    "gulp-gh-pages": "^0.5.4",
    "gulp-htmlmin": "^1.2.0",
    "gulp-if": "^2.0.0",
    "gulp-jshint": "^1.11.2",
    "gulp-less": "^3.0.3",
    "gulp-load-plugins": "^1.0.0",
    "gulp-minify-css": "^1.2.1",
    "gulp-plumber": "^1.0.1",
    "gulp-size": "^2.0.0",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.7",
    "jest-cli": "^0.5.10",
    "jshint": "^2.8.0",
    "jshint-loader": "^0.8.3",
    "jshint-stylish": "^2.0.1",
    "jsx-loader": "^0.13.2",
    "karma": "^0.13.11",
    "karma-chrome-launcher": "^0.2.1",
    "karma-firefox-launcher": "^0.1.6",
    "karma-jasmine": "^0.3.6",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-webpack": "^1.7.0",
    "merge-stream": "^1.0.0",
    "minimist": "^1.2.0",
    "protractor": "^2.5.1",
    "psi": "^1.0.6",
    "run-sequence": "^1.1.4",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1",
    "file-encrypt": "^0.0.1",
    "jwt-decode": "^1.4.0"
  }

Either Visual Studio brings intelligence to flatten the directory, either Visual Studio could not care of the node_module directory.

**Comment by davidfowl** [comment]
File this on aspnet/Tooling
