### ISSUE TITLE
Git bash on windows

### ISSUE THREAD

**Issue by TerribleDev** [aspnet/dnx#3068]
The DNU, DNVM commands are not available in git bash on windows, but DNX is.

**Comment by moozzyk** [comment]
`source ~/.dnx/bin/dnvm.sh`

**Comment by tparnell8** [comment]
I don't have that file....

**Comment by moozzyk** [comment]
Sorry, I updated the command - the folder should be `dnvm` instead of `bin`.

**Comment by muratg** [comment]
@anurse did we enable dnvm.sh on git bash (windows) or is that punted for now?

**Comment by khellang** [comment]
I get the following when I do `source ~/.dnx/dnvm/dnvm.sh` in git bash on Windows :confused: 

> sh.exe": /c/Users/Kristian/.dnx/dnvm/dnvm.sh: line 177: conditional binary operator expected
> sh.exe": /c/Users/Kristian/.dnx/dnvm/dnvm.sh: line 177: syntax error near `=~'
> sh.exe": /c/Users/Kristian/.dnx/dnvm/dnvm.sh: line 177: `    if [[ "$runtimeFullName" =~ $_DNVM_RUNTIME_PACKAGE_NAME-[^-.]*-[^-.]*-[^-.]*\..* ]];'

**Comment by anurse** [comment]
We are not supporting `dnvm` on bash. There have been some PRs to help make it work, but we don't plan to run tests on that platform at this time. `dnx` will continue to work as it is a plain executable. You may be able to use `dnu` by running `cmd /c dnu [args]` from git bash to launch the `dnu.cmd` batch file inside `cmd`

**Comment by slofurno** [comment]
@khellang i think upgrading to a newer version of git for windows will fix that
