### ISSUE TITLE
Include Server Name as part of IRuntimeEnvironment

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/dnx#3069]
Just wondering if others think it makes sense that `IRuntimeEnvironment` should include the server name? It includes everything else about the runtime and the server environment except for its name. Is this possible to get added?

**Comment by davidfowl** [comment]
Server Name? `IRuntimeEnviroonment` is a low level concept that has nothing to do with web whatsoever. In fact, anything that comes from this repository should not be considered for web.

The server name should be a specific server feature, see:

https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.AspNet.Hosting.Server.Abstractions

**Comment by avanderhoorn** [comment]
Makes sense. As a side note though, maybe Server Name was a bad choice of
words... That actual property would probably be Machine Name or something
similarly abstract. In that case it would work in a device context just as
well as a web context.
