### ISSUE TITLE
VS 2015 Beta8 - KRE_HOME Warning, 

### ISSUE THREAD

**Issue by NiyazShoukath** [aspnet/dnx#3070]
![error33](https://cloud.githubusercontent.com/assets/14939784/10715977/9f092046-7b39-11e5-96d0-897d4a8cde3c.png)

dnvm provide  this warning, so, i cant load dependencies (not load refferences DNX core, kestrol,...) in new Web project

**Comment by kosmakoff** [comment]
It clearly says that you need to remove the environment variable called KRE_HOME.
Start -> Control Panel -> Search Box : Environment Variables
