### ISSUE TITLE
Not clear to which dnx process the VS debug to Attach  

### ISSUE THREAD

**Issue by Anderman** [aspnet/dnx#3071]
With the new hosting model I must attach to a DNX process to debug an application from VS2015. Before it was to iisexpress which show which website it was running. 

But now it is not clear which dnx process is running the website.

![image](https://cloud.githubusercontent.com/assets/1858745/10716558/57bf1976-7b3d-11e5-8dda-86d0f0fccc0a.png)

**Comment by NickCraver** [comment]
+1 on this - you have to go to task manager and grab the PID via command line differentiation at the moment - can DNX set a title? This would be a marked improvement over w3wp.exe as a bonus. 

Related: the description for `dnx.exe` itself is also missing, so you'll see only "dnx" as the fallback description anywhere else, e.g. Task Manager.

**Comment by per-samuelsson** [comment]
FWIW, running `dnx --debug [command]` will show you the PID and wait for you to attach.

```
dnx --debug run
Process Id: 5376
Waiting for the debugger to attach...

```

**Comment by anurse** [comment]
We're looking at options to solve this by RTM. Believe me, we are well aware of how much it sucks, having to debug DNXes all day ;P

Thanks for the report though, good to keep it on our radar :D

**Comment by Anderman** [comment]
Thanks you can also use dnx-watch 

```
[DnxWatcher] info: dnx process id: 3580
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

**Comment by jln1989** [comment]
If my project does not have a static main method is there a way to attach and debug when running via dnx?

**Comment by Anderman** [comment]
I don't see how static main is related to debugging. Just attach the debugger to the right dnx process. If you don't know then attach to all dnx. You can also add code to start the debugger
`System.Diagnostics.Debugger.Launch();`

**Comment by jln1989** [comment]
@Anderman  : In my project I tried attaching to the right dnx process and it gave me an error saying cannot attach to a program which does not have entry point which was the reasoning behind my query.

Let me know if am missing something here.

**Comment by Anderman** [comment]
@jln1989  Aha, Okee, I have never seen this message. Is the debugger working if launched from code by System.Diagnostics.Debugger.Launch(); or can you debug the starterweb template?
