### ISSUE TITLE
DNX Restore does not try all package sources when one is UNC based and offline

### ISSUE THREAD

**Issue by Mertsch** [aspnet/dnx#3075]
Situation:
In my NuGet.config, I have configured an alternative package source which gets added to the list of sources.
In total I have 3 active sources (nuget.org v3, nuget.org v2 and \server\share) configured, additionally DNX provides more package sources by itself.

When my DNX project is about to restore packages, it tries to access the UNC path first, no matter the order of package sources. When this UNC source is unavailable, the package restore fails, even though there is more then one other source which could provide the package.

I experience this issue since version beta 7 till beta 8, but don't know if other versions are affected.

Error Message

```
C:\Users\<user>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe "C:\Users\<user>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "D:\Workspaces\<ProjectName>\Source\<ProjectName>.Interfaces.Web" "D:\Workspaces\<ProjectName>\Source\<ProjectName>.Service.Web" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858
  CACHE https://api.nuget.org/v3/index.json
  CACHE https://nuget.org/api/v2/
Restoring packages for D:\Workspaces\<ProjectName>\Source\<ProjectName>.Interfaces.Web\project.json
Error: FindPackagesById: Newtonsoft.Json
  The local package source \\<FileServerName>.local\<Path>\NuGetRepository doesn't exist
----------
System.IO.FileNotFoundException: The local package source \\<FileServerName>.local\<Path>\NuGetRepository doesn't exist
File name: '\\<FileServerName>.local\<Path>\NuGetRepository'
   at Microsoft.Dnx.Tooling.Restore.NuGet.PackageFolder.FindPackagesByIdAsync(String id)
```

**Comment by AStoker** [comment]
Any movement on this? I'm currently in the same situation.
