### ISSUE TITLE
Using System.Data.SqlClient under Linux-coreclr-rc1

### ISSUE THREAD

**Issue by Agitto** [aspnet/dnx#3076]
I have a small sample project (https://github.com/Agitto/SqlClientProblem).
It's works well on Windows (dnx-coreclr-win-x64.1.0.0-rc1-15838 runtime). But if i run it on Ubuntu (dnx-coreclr-linux-x64.1.0.0-rc1-15838) it falls with following exception:
```C#
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
```C#
File name: 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Data.SqlClient'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at ConsoleApp3.Program.Main(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Data.SqlClient'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by ChaosEngine** [comment]
The bug still holds true even after 1.0.0-rc1-update1. I'm testing it on latest `microsoft/aspnet:1.0.0-rc1-update1-coreclr` image.

Stacktrace:
>info: Microsoft.AspNet.StaticFiles.StaticFileMiddleware[2]
>      Sending file. Request path: '/js/site.min.js'. Physical path: '/root/EntityFramework.Docs/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5.ExistingDb/wwwroot/js/site.min.js'
>info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
>      Request finished in 0.0011ms 200 application/javascript
>info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
>      Request finished in 0.001ms 200 application/javascript
>warn: Microsoft.AspNet.Server.Kestrel[0]
>      Connection processing ended abnormally
>      System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
>         --- End of inner exception stack trace ---
>         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
>         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
>warn: Microsoft.AspNet.Server.Kestrel[0]
>      Connection shutdown abnormally
>      System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
>         --- End of inner exception stack trace ---
>         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult()
>         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
>info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
>      Request starting HTTP/1.1 GET http://172.17.0.1:5004/Blogs
>info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
>      Executing action method EFGetStarted.AspNet5.ExistingDb.Controllers.BlogsController.Index with arguments () - ModelState is Valid'
>fail: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
>      An exception occurred in the database while iterating the results of a query.
>      System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>
>      File name: 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
>      File name: 'System.Data.SqlClient'
>         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
>         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
>         at Microsoft.Data.Entity.Storage.Internal.SqlServerConnection.CreateDbConnection()
>         at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
>         at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
>         at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
>         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
>fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
>      An unhandled exception has occurred: Could not load the specified file.
>      System.IO.FileNotFoundException: Could not load the specified file.
>      File name: 'EntityFramework.Core.resources'
>         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
>         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
>         at Microsoft.Data.Entity.Storage.Internal.SqlServerConnection.CreateDbConnection()
>         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>         at EFGetStarted.AspNet5.ExistingDb.Controllers.BlogsController.Index()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.ExecuteAsync(MethodInfo actionMethodInfo, Object instance, Object[] orderedActionArguments)
>         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
>info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
>      Executing action method EFGetStarted.AspNet5.ExistingDb.Controllers.HomeController.Error with arguments () - ModelState is Valid'
>

**Comment by Eilon** [comment]
@natemcmaster @divega @anurse ?

**Comment by ChaosEngine** [comment]
I've created Dockerfile for exposing this bug. Hope it will help: https://github.com/ChaosEngine/dockerfiles/blob/master/entityframework/Dockerfile

One can buld it:
`$ docker build -t EF-Bug .`
and test it with:
`$ docker run -it --rm EF-Bug`
`$ docker exec $(docker ps -q -f {ancestor=EF-Bug}) curl http://localhost:5000/Blogs/`
Errors appear in curl-ed response and backround log console of container

**Comment by anurse** [comment]
I love the idea of using docker to share the repro! I'm working on investigating it now. Thanks!

**Comment by anurse** [comment]
Looks like `dnu restore` is not properly honouring the `DNX_RUNTIME_ID` environment variable that we use to override the OS detection (since DNX technically only supports Ubuntu, but we use Debian). This would be a bug in DNX (but would be fixed in NuGet for RC2 rather than here). As a workaround though, you can get your scenario working by changing your `dnu restore` call to `dnu restore --runtime ubuntu.14.04`

i.e. change Line 7 in your Docker file (https://github.com/ChaosEngine/dockerfiles/blob/master/entityframework/Dockerfile#L7) to:

```
RUN [ "dnu", "restore", "--runtime", "ubuntu.14.04-x64" ]
```

**Comment by anurse** [comment]
Note I do still get an exception after this change, but it appears to be something more specific to your configuration:

```
An exception occurred in the database while iterating the results of a query.
      System.PlatformNotSupportedException: Integrated Security is not supported on non-Windows platform.
         at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
         at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
         at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

**Comment by natemcmaster** [comment]
@anurse the "Integrated Security is not supported on non-Windows" error just means you need to use a UserID/Password in the connection string instead of relying on Windows authentication. On the bright side, the appearance of this error indicates `System.Data.SqlClient.dll` is actually loaded.

**Comment by anurse** [comment]
Yeah, I figured it was just something in the connection string for the repro project.

**Comment by ChaosEngine** [comment]
@anurse Great, it behaves exactly as you predicted, thanks!
However now, after changing connection to something more sane:
`var connection = @"Server=192.168.0.55;Database=testDB;User Id=user;Password=P@ssw0rd;"`
I still get FileNot found for `System.Net.Security`. Stack trace:
>root@655cbbd3df7d:~/EntityFramework.Docs/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5.ExistingDb# dnu restore --runtime ubuntu.14.04-x64
>Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231
>
>  CACHE https://api.nuget.org/v3/index.json
>Restoring packages for /root/EntityFramework.Docs/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5.ExistingDb/project.json
>Writing lock file /root/EntityFramework.Docs/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5.ExistingDb/project.lock.json
>Restore complete, 4746ms elapsed
>
>Feeds used:
>    https://api.nuget.org/v3-flatcontainer/
>root@655cbbd3df7d:~/EntityFramework.Docs/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5.ExistingDb# dnx web
>Hosting environment: Production
>Now listening on: http://*:5004
>Application started. Press Ctrl+C to shut down.
>info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
>      Request starting HTTP/1.1 GET http://172.17.0.2:5004/Blogs
>info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
>      Executing action method EFGetStarted.AspNet5.ExistingDb.Controllers.BlogsController.Index with arguments () - ModelState is Valid'
>fail: Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
>      An exception occurred in the database while iterating the results of a query.
>      System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>
>      File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
>      File name: 'System.Net.Security'
>         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
>         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
>         at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
>         at System.Data.SqlClient.SNI.SNIProxy.ConstructTcpHandle(String fullServerName, Int64 timerExpire, Object callbackObject, Boolean parallel)
>         at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
>         at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
>         at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
>         at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
>         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
>         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
>         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
>         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
>         at System.Data.SqlClient.SqlConnection.Open()
>         at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
>         at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
>         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
>fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
>      An unhandled exception has occurred: Could not load the specified file.
>      System.IO.FileNotFoundException: Could not load the specified file.
>      File name: 'EntityFramework.Core.resources'
>         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
>         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
>         at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
>         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>         at EFGetStarted.AspNet5.ExistingDb.Controllers.BlogsController.Index()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.ExecuteAsync(MethodInfo actionMethodInfo, Object instance, Object[] orderedActionArguments)
>         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
>      --- End of stack trace from previous location where exception was thrown ---
>         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
>info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
>      Executing action method EFGetStarted.AspNet5.ExistingDb.Controllers.HomeController.Error with arguments () - ModelState is Valid'
>info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
>      Executing ViewResult, running view at path /Views/Shared/Error.cshtml.
>info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
>      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
>info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
>      Executed action EFGetStarted.AspNet5.ExistingDb.Controllers.HomeController.Error in 0.1998ms

**Comment by natemcmaster** [comment]
@ChaosEngine it's a known bug in `dnu restore` in rc1.  See https://github.com/aspnet/EntityFramework/pull/3689#issuecomment-158201904

**Comment by ChaosEngine** [comment]
@natemcmaster Thanks, it worked; have to harden my github search skills.

**Comment by anurse** [comment]
Cool! If anyone is still encountering issues, please feel free to reopen!
