### ISSUE TITLE
`dnu restore` fails with DNX Core on Windows

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#3077]
Unable to use DNX Core on Windows to restore packages for the DNX repo. Failure always has the form:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Object[]' to type 'System.Net.Http.WinHttpRequestState'.
   at System.Net.Http.WinHttpRequestState.FromIntPtr(IntPtr gcHandle)
   at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
```

This occurs regardless of the options used on the `dnu command` e.g.
- `dnu restore`
- `dnu restore src test samples`
- `dnu restore --quiet --lock --parallel src test samples`

All end with the same failure.

```
> dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-15996
 Type:         CoreClr
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.3
 Runtime Id:   win81-x86
```

**Comment by dougbu** [comment]
The issue here is at least somewhat specific to the DNX repo. Am able to use the same DNX Core version to restore packages for the MVC repo for example.

**Comment by muratg** [comment]
Looks like this was the problem: https://github.com/dotnet/corefx/pull/4001 

As soon as we get a CoreCLR successfully, this should go away.

**Comment by dougbu** [comment]
DNX Core version `1.0.0-rc1-16028` picked up System.Net.Http.dll `4.6.23426.0`. That fixed the problem.
