### ISSUE TITLE
DNX restoring older packages for System.IO.Compression

### ISSUE THREAD

**Issue by ianhays** [aspnet/dnx#3078]
I'm running into the same issue as in https://github.com/NuGet/Home/issues/1418 with the same repro. Package restoration is choosing the 4.0.0 version instead of the 4.0.1 version of System.IO.Compression and subsequently System.IO.Compression.ClrCompression when the runtime is win7-x64 or win7-x86.

Adding a reference in the Common project.json for the most recent System.IO.Compression fixes the issue and causes the correct package versions to be restored.

CC: @ericstj

**Comment by ericstj** [comment]
To be clear, restore wasn't choosing 4.0.0 of System.IO.Compression, it was using the latest (4.1.0-beta-), however it was consuming the runtime.json from both 4.0.0 and 4.1.0-beta-.

I looked at this with Ian and found that the compile graph had 4.1.0-beta-23419 but it was still pulling in System.IO.Compression.clrcompression-x86 which is only referenced from the runtime.json in 4.0.0 which should have been completely trimmed.

We saw this using a recent RC of DNX so it looks like this NuGet but made it into the DNX codebase as well.

/cc @davidfowl
