### ISSUE TITLE
IApplicationEnvironment no longer injected in DNX command

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3079]
I have a custom DNX command with the following ctor:

```c#
public Program(IServiceProvider dnxServices) {
    var appEnv = (IApplicationEnvironment)dnxServices.GetService(typeof (IApplicationEnvironment));
}
```

When using DNX 1.0.0-rc1-15996 (from aspnetcidev), appEnv is null. When using 1.0.0-rc1-15838, it's properly filled.

Has there been some sort of change or is this a bug?

**Comment by per-samuelsson** [comment]
> Has there been some sort of change or is this a bug?

#2990

**Comment by henkmollema** [comment]
You can access the application environment and other runtime services via the `PlatformServices` class in the `Microsoft.Extensions.PlatformAbstractions` namespace:
```csharp
public Program()
{
    var env = PlatformServices.Default.Application;
}
```

**Comment by Jetski5822** [comment]
Hmmm not sure I like that change

**Comment by roji** [comment]
@per-samuelsson thanks for indicating the right issue, am closing this and will continue the discussion there.
