### ISSUE TITLE
DNX doesn't write actual dependencies to nupkgs it produces

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#3094]
DNX isn't writing the actual dependencies that a library referenced to the output nupkg, it appears to just copy whatever was in the project.json.

This creates an implicit compatibility contract with a packages dependencies.  If a package were two drop a dependency in its implementation this would be perceived as breaking change by up-stack packages since they'd now see a FileNotFound at runtime due to the missing dependency.

Package authors (including BCL) do not view implementation dependencies as part of the public contract for a library.

DNX should be examining the output of the compiler, mapping that back to the packages, and ensuring a direct package ref for every direct dependency.

**Comment by davidfowl** [comment]
> DNX isn't writing the actual dependencies that a library referenced to the output nupkg, it appears to just copy whatever was in the project.json.

That's by design.

> DNX should be examining the output of the compiler, mapping that back to the packages, and ensuring a direct package ref for every direct dependency.

Assemblies are not packages. Can't make that assumption.

Where did this break somebody? It's like bad nuspec authoring. We could return some diagnostics warnings for best practices but I don't see a clean way to solve this generally. There's an impedance mismatch.

**Comment by ericstj** [comment]
I'm not making any assumptions about assemblies being packages, you need to map from assembly back to package using the information in the lock file.  The package is supposed to represent all the dependencies of the library it contains but it does not.  It's leeching off packages referenced indirectly.  Are you saying you think that a package's implementation dependencies should be part of that package's public contract?

I see this pattern all over the ASP.NET packages produced with DNX and it worries me. They are assuming that they'll get most of their dependencies indirectly.  The second anyone in that chain refactors an implementation assembly to remove a dependency those packages will break on upgrade.  FWIW Nuget v2 didn't have this problem since it burned in the indirect refs and you'd never lose them.

>Where did this break somebody? It's like bad nuspec authoring. 
Exactly, bad nuspec authoring by DNX.  I've already seen it happen a many times during pre-release and folks just absorb the break and move on since it's a pre-release.  Once we are stable folks will complain that it is a breaking change.

**Comment by davidfowl** [comment]
To do this right we'd need private dependencies + a compile time check to make sure you're not exposing things marked private

**Comment by muratg** [comment]
Let's sit down and talk about possible options here.
