### ISSUE TITLE
Latest ARM runtime is broken

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#3095]
ARM runtime 16048 is missing some crucial files like coreclr.dll. Trying to run dnx on Raspberry Pi 2 results in:
```
The default servicing root does not exist.
Loaded module: dnx.onecore.coreclr.dll
Found export: CallApplicationMain
Failed to locate or load coreclr.dll
```

**Comment by BrennanConroy** [comment]
What was the last build you saw actually work?

**Comment by moozzyk** [comment]
pre-beta8 because I have not had a chance to play with that recently.

**Comment by BrennanConroy** [comment]
bf1ae43c6bac2b1cdc691ec8aec58a6c154125ae

**Comment by npateman** [comment]
I understand this is an issue in rc1-final?  Is there a quick fix I can implement locally to get it working?

**Comment by moozzyk** [comment]
@npateman Add the folder where libuv.dll for ARM lives to the PATH.

**Comment by npateman** [comment]
Okay this didn't work for me, so I assume it's not the same issue?

I have all my files on a USB key, I put the ARM version of libuv.dll into a folder,

    e:\extralibs\libuv.dll

then added that to the PATH,

    $env:PATH+='e:\extralibs\'

Then ran Kestrel again, same error,

    Failed to locate or load coreclr.dll

I'm not getting any more errors, just that single line.

**Comment by npateman** [comment]
The location of the libuv.dll that I used was,

    C:\myapp\arm\approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes\win10-arm\native

Oddly enough, which is the published folder.

**Comment by moozzyk** [comment]
@npateman - did you publish your application with the runtime? Does your published folder contain coreclr.dll?

**Comment by npateman** [comment]
I published it using a powershell command, but you're right, there's no coreclr.dll file in the published folder.  Do I have to add this to the project.json to get it to include it? Or has it just omitted it due to a bug?

    dnu publish --out C:\myapp\ --no-source --runtime dnx-coreclr-win-arm.1.0.0-rc1-final

The coreclr.dll doesn't actually appear to be in the runtime folder in my user\.dnx folder either.  i.e.

    C:\Users\nickp\.dnx\runtimes\dnx-coreclr-win-arm.1.0.0-rc1-final\bin

**Comment by npateman** [comment]
Just been reading this issue,

    https://github.com/aspnet/dnx/issues/3358

It suggests installing an rc2 build and using coreclr.dll from that... but I can't find it, apparently rc1-final is the latest,

    $env:DNX_UNSTABLE_FEED="https://www.myget.org/F/aspnetmaster/api/v2" 
    dnvm install latest -unstable -r CoreClr -arch arm

**Comment by npateman** [comment]
Installing now using this feed,

    $env:DNX_UNSTABLE_FEED="https://www.myget.org/F/aspnetvnext/api/v2/"

**Comment by npateman** [comment]
That didn't work, just got

    Failed to start CLR host

Haven't had any luck building for rc2 yet but I'll try again just incase.

**Comment by npateman** [comment]
No luck building for RC2, can't find rc2-16595 versions for all of my dependencies.

**Comment by moozzyk** [comment]
@npateman - I finally had a few minutes to check this. Sorry for the delay. 
I was able to make things work without any hacks. This was just a basic Hello World console app. Here is what I did:
 - installed the arm runtime: `dnvm install latest -arch arm -r coreclr -u`
 - in my application folder (using an x64 runtime) restored packages: `dnu restore -f https://www.myget.org/F/aspnetvnext/api/v3/index.json`
 - made sure my application runs on x64 (`dnx run`)
 - published the application for arm - `dnu publish -o C:\temp\Console --no-source --runtime dnx-coreclr-win-arm.1.0.0-rc2-16595`
 - x-copied the published application to my RPi2
 - remote PS'd to my RPi2 and ran the application (for whatever reason the run.cmd was not created so I just ran the application directly):
```
[my-pi2]: PS C:\temp\Console\approot> .\runtimes\dnx-coreclr-win-arm.1.0.0-rc2-16595\bin\dnx.exe .\packages\Console\1.0.0\lib\dnxcore50\Console.dll
Hello, World!
```

You must be missing one of the steps or you may have a broken shared runtime installed which you use to run your application.

**Comment by npateman** [comment]
Hi @moozzyk, yeah I'm sure it works for something simple, but certainly doesn't work for my app which has the following dependencies (not all of which can be resolved to the latest version),

  "dependencies": {
    "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-rc1-final",
    "System.Security.Cryptography.DeriveBytes": "4.0.0-beta-23311",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "System.Runtime.Serialization.Json": "4.0.0-beta-23109",
    "System.Runtime.Extensions": "4.0.11-beta-23516",
    "System.Collections": "4.0.11-beta-23516",
    "System.Runtime": "4.0.21-beta-23516",
    "Microsoft.CSharp": "4.0.1-beta-23516",
    "System.Private.Networking": "4.0.1-beta-23516",
    "System.Net.Security": "4.0.0-rc2-23623",
    "System.Reflection.TypeExtensions": "4.1.0-beta-23516"

**Comment by moozzyk** [comment]
@npateman - the error you `Failed to start CLR host` indicates that the runtime could not be loaded. It does not matter how simple or complicated your application is if the runtime cannot be loaded nothing works. Once you get past this error I can take another look if you post more details.
Another thing is that you are trying to use an rc2 runtime with rc1-final packages. I don't think this can work in general. Either stick to rc1 or move to rc2 (although dnx is being retired in rc2 in favor of dotnet)
