### ISSUE TITLE
Assembly.GetEntryAssembly returns NULL

### ISSUE THREAD

**Issue by sklose** [aspnet/dnx#3096]
```Assembly.GetEntryAssembly()``` always returns ```NULL```. At least for dnx console apps I would expect to get the assembly that contains the Main method. For web applications it would probably make sense to return the assembly that contains the Startup class.

This was tested on dnx-rc1-15838 clr x86 on Windows 7.

**Comment by davidfowl** [comment]
That's by design. You need to use the new "emitEntryPoint" to get a real entrypoint. That also means you need a Program.Main
