### ISSUE TITLE
DNU publish on a project that has System.Runtime.InteropServices.RuntimeInformation as a dependancy will not give a 'runnable' output

### ISSUE THREAD

**Issue by joepeer** [aspnet/dnx#3097]
dnx run will actually work by resolving the appropriate runtime.win7.System.Runtime.InteropServices.RuntimeInformation

But running the result of a dnu publish will give a FileNotFoundException.

> Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Under windows that dependancy should become runtime.win7.System.Runtime.InteropServices.RuntimeInformation as listed in the runtime.json file.

There is nothing in the packages folder of the output directory that gives any information on the runtime dll for this dependancy.

I can't seem to understand how a dependancy to System.Console works but not InteropServices.RuntimeInformation.

I'm currently using dnx-coreclr-win-x64.1.0.0-rc1-15838

**Comment by davidfowl** [comment]
@anurse did we fix this?

**Comment by anurse** [comment]
@davidfowl  It should be fixed, it'll be in the next Coherence build I believe.
