### ISSUE TITLE
When pointed only dnxcore50 have another dependencies in project.lock.json

### ISSUE THREAD

**Issue by Codenator81** [aspnet/dnx#3102]
When pointed only dnxcore50 have another dependencies in project.lock.json/ This couse errors on sqlite for example. Related issue aspnet/EntityFramework#3573

**Comment by Codenator81** [comment]
And there wrong runtimes:
```json
"compile": {
          "lib/dotnet5.4/EntityFramework.Sqlite.dll": {}
        },
        "runtime": {
          "lib/dotnet5.4/EntityFramework.Sqlite.dll": {}
        }
```
Support to be netcore50 or dnxcore50

**Comment by BrennanConroy** [comment]
dotnet5.4 runs on dnxcore50 so that's fine

**Comment by Codenator81** [comment]
@BrennanConroy Thanks good news)

**Comment by Codenator81** [comment]
@BrennanConroy is that new name for dnxcore50 or just alias? When I need point coreclr50 on linux wich name better for now?
