### ISSUE TITLE
DNX commands pulling in Roslyn from DNX runtime

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3109]
I have a DNX command which I use as a pre-build step doing some Roslyn code generation. The command is compiled against Microsoft.CodeAnalysis.CSharp 1.0.0.

When I execute it, I get a MissingMethodException. Some investigation revealed that Microsoft.CodeAnalysis.CSharp is being loaded from the DNX runtime's bin directory, which happens to have some version of Roslyn 1.1.0. With DNX 1.0.0-rc1-15844 things happened to work, while with 1.0.0-rc1-16048 I get the aforementioned MissingMethodException (presumably because of some change to Microsoft.CodeAnalysis.CSharp).

It seems like I should be able to have the Microsoft.CodeAnalysis.CSharp I compiled against somehow... Any suggestions?

**Comment by davidfowl** [comment]
Can't do it as it stands today. Use the one that matches the dnx version you have.

**Comment by roji** [comment]
OK, will try that for now. Am leaving open for future resolution...

**Comment by davidfowl** [comment]
Sure
