### ISSUE TITLE
Way of ensuring support for specific profiles with dotnet

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3111]
The `dotnet` TFM is a great way to support different profiles/runtimes. However, DNX is lacking a way of ensuring support for a set of supported profiles. In other words, if I'm a library developer and want to be sure that my library is usable in various profiles, it's not clear how to do so - a dependency might slip in which limits the profiles in which my library can be used.

Is there any way to do this currently? Ideally there would be some dnu command which accepts a list of TFMs, walks the dependency graph and returns zero for success or non-zero for compliance failure - this would allow easy usage in a build server.

**Comment by davidfowl** [comment]
This is now irrelevant given the new standard platform https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by roji** [comment]
You're right. So if I understand correctly, in the new standard platform package maintainers decide at publishing time whether they target/support netstandard1.2 or netstandard1.3? In other words it's no longer the package *consumer* which checks compatibility for dependency packages?
