### ISSUE TITLE
DNX Restore does not work properly when project.json is edited outside the solution (project.json.lock is out of date)

### ISSUE THREAD

**Issue by Mertsch** [aspnet/dnx#3112]
I am working on two machines with the same code stored in VS Online. I use the TF Version Control to share my changes between those two machines.
What happened the second time now for me and is quite annoying is that
1. I use a package like `JetBrains.Annotations` in multiple projects
2. Both machines are up to date with the source code and dependencies
3. I upgrade the package on one machine (e.g. 10.0.0-eap3 to 10.0.0), and DNX Restore properly updates the references and stuff
4. I check in the code and download the updates on the other machine without having the solution open
5. The second machine see the new package, but the project.json.lock file is still in the old dependency state
6. I get a compiler warning/error

What does not work: Manually restore packages via the context menu

The only way to fix this is
- Change a random package in `project.json`, wait for restore, change it back
- Delete (all) `project.json.lock` files, and let DNX restore create an updated version

**Comment by davidfowl** [comment]
You're not checking in project.lock.json files are you?

**Comment by Mertsch** [comment]
@davidfowl Absolutely not, just made sure.
