### ISSUE TITLE
Will 'dnu publish --native' be supported on Linux?

### ISSUE THREAD

**Issue by joepeer** [aspnet/dnx#3114]
On dnx-coreclr-linux-x64.1.0.0-rc1-1604, running dnu publish --native ends up with a

> Exit code for mscorlib: 2
> Native image generation failed.

There does not seems to have a crossgen tool included witht the runtime on Linux.

Will the first version of dnx offer native images generation on Linux ?

**Comment by yanickv** [comment]
The .NET Core and ASP.NET 5 RC announcement mentions that CrossGen is currently broken under Linux and will be fixed: http://blogs.msdn.com/b/dotnet/archive/2015/11/18/announcing-net-core-and-asp-net-5-rc.aspx 

Does this mean that dnu publish --native will be fixed for RC2?
