### ISSUE TITLE
Command line exception

### ISSUE THREAD

**Issue by aaron-hammond** [aspnet/dnx#3120]
Hi,

I attempted to run the following command in powershell:

dnx test -method "UnitTests.Domain.Factories.Cooki
eFactorySpecs.WhenIBuildTheCookies.TheSessionCookieIsCorrect"  -debug

I'm not sure if this a valid command, (i was attempting to debug the "TheSessionCookieIsCorrect"  method) but running this command threw a .net exception nonetheless.

Thanks
Aaron

**Comment by davidfowl** [comment]
I'm not sure what to do with this bug. It's a little vague.

**Comment by aaron-hammond** [comment]
@davidfowl ok, sorry, let me try and be a little more concise.

I've created a test application: https://github.com/aaron-hammond/dnx.foo

its a basic project with one unit test.

When i run the following command in powershell:

dnx test -method "dnx.foo.tests.AddNumbersSpecs.AddSomeNumbersTests.TheResultIs20" -debug

I get the following exception:

![exceptio](https://cloud.githubusercontent.com/assets/7657318/11624811/3db9078c-9cce-11e5-9161-f8520963ec1f.PNG)

If you run it without the -debug flag then the test runs fine, if i append a non-existent flag i get a more graceful "unknown option".

**Comment by dougbu** [comment]
@aaron-hammond looks like the `-debug` switch is doing exactly what's required to start the debugger. Choose the debugger you want in that dialogue and hit `Yes`.

**Comment by aaron-hammond** [comment]
@dougbu if that's the case then so be it, but, i would suggest that: "An unhandled Microsoft .Net Framework exception occurred in dnx.exe" isn't a very good explanation of whats going on IMO.
It looks like, to me, that the command has failed in what i'm expecting it to do and it wants me to debug dnx.exe and not my code. 

I don't know how easy it is to change something like this but; "Please choose an environment for debugging:" would cause less confusion.

I'm not sure if there is anything in the pipeline, but, it would be much better if it just opened visual studio or a pre-defined application? 

I can set my git command "git mergetool" to open the visual studio vsdiffmerge tool, not sure if i can do anything similar here?

Thanks for the info.

**Comment by davidfowl** [comment]
Can't really change that. We don't control it.

**Comment by aaron-hammond** [comment]
@davidfowl OK, no worries, thanks for the feedback.
