### ISSUE TITLE
Check why signing is required for build time dependency

### ISSUE THREAD

**Issue by pakrym** [aspnet/dnx#3123]
Looks like it shouldn't be.

See https://github.com/aspnet/KestrelHttpServer/pull/324/files#r43715021

**Comment by Eilon** [comment]
@pakrym why is this closed/done? Isn't this still possibly an issue in how DNX compiles things?

**Comment by pakrym** [comment]
@Eilon, I looked trough the code and it looks like by design. Maybe there is and issue with my understanding of how it should work.

**Comment by Eilon** [comment]
Yeah at least for me this doesn't sound right. The compile modules should have no relationship to the project they are running on. It could be that the current design does this on purpose, but then I think the current design is lacking :smile: 

Now, perhaps none of this will matter with some of the upcoming changes, but I'd like to know that for sure.

@davidfowl @lodejard FYI

**Comment by davidfowl** [comment]
We need to remove the key file etc when compiling the pre process aspect

**Comment by davidfowl** [comment]
It needs to happen here https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L123

**Comment by pakrym** [comment]
@davidfowl https://github.com/aspnet/dnx/pull/3134
