### ISSUE TITLE
Unable to install Npgsql on Linux/mono due to missing packages in nuget feed

### ISSUE THREAD

**Issue by ysilvestrov** [aspnet/dnx#3127]
### Functional impact

Unable to run ASP.NET 5 apps on Linux
### Minimal repro steps
1. Add Npgsql dependency to project
2. Try to run 'dnu restore' in docker container
### Expected result

'dnu restore' finish successfuly, just like on Windows
### Actual result

'dnu restore' fails with the following result:

```
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for /DockerWebApp/project.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.linux.system.net.nameresolution/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/runtime.linux.system.net.nameresolution/index.json 1248ms
Unable to locate Dependency runtime.linux.System.Net.NameResolution >= 4.0.0-beta-23409
Writing lock file /DockerWebApp/project.lock.json
Restore complete, 13689ms elapsed

Errors in /DockerWebApp/project.json
    Unable to locate Dependency runtime.linux.System.Net.NameResolution >= 4.0.0-beta-23409
```
### Further technical details

URL https://api.nuget.org/v3-flatcontainer/runtime.linux.system.net.nameresolution/index.json results  BlobNotFound error. However, the package exists at https://www.nuget.org/packages/runtime.linux.System.Net.NameResolution/4.0.0-beta-23409 so it looks like nuget feed problems

**Comment by woutertenbosch** [comment]
Having the same issue here :(

**Comment by hjgraca** [comment]
I had the same issue and to fix it I by adding more nuget feeds to NuGet.config. 

<packageSources>
    
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="api.nuget.b8" value=" https://www.myget.org/F/aspnetbeta8/api/v2" />
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="NuGet" value="https://nuget.org/api/v2/" />
    <add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly/" />
    <add key="DotNet" value="https://www.myget.org/F/dotnet-corefx/" />
  </packageSources>

**Comment by sirentek** [comment]
I had the same issue... I use linux mint mate x64. 
I use mono runtime.

After I add the dependency EntityFramework7.Npgsql 3.1.0-beta8-2, I cannot restore it.

If I add the feed: <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" /> to my Nugget.config file, it restores.
But this time it cannot build: System.Console is not compatible with dnx core 50

Now I will try with using CoreClr-beta7 runtime.

Has anybody found a way to solve it ?

**Comment by hjgraca** [comment]
@benriordan glad it worked. I also made it work in travis ci, just needed to select Ubuntu OS.

**Comment by sirentek** [comment]
@hjgraca I would like to know which runtime you used to make it run.

I used coreclr-beta7 runtime and built it.
This time there is an exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.NameResolution,..."

Here is my project.json:
{
    "dependencies": {
        "EntityFramework7.Npgsql": "3.1.0-beta8-2",     
        "EntityFramework.Commands": "7.0.0-beta8",
        "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta8"
    },
    "commands": {
        "run": "SirenTek",
        "ef": "EntityFramework.Commands"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-*",
            }
        }
    }
}

Mint is based on Ubuntu so it should work on Linux mint. Please advise me where am I wrong ?

**Comment by hjgraca** [comment]
@sirentek I'm using coreclr beta 8. I also got exactly that error System.Net.NameResolution not found.
To fix it I added more feeds to nuget, check my reply above. That worked. Also check my repo https://github.com/hjgraca/AspNet5-Awesome, that is building in travis ci

**Comment by sirentek** [comment]
@hjgraca I used coreclr beta 8, added feeds to Nuget.Config file. I restored with success.
But I cannot build it: 
The dependency System.Net.NameResolution 4.0.0-rc2-23513 in project SirenTek does not support framework DNXCore,Version=v5.0.

I checked your repo and in project.json file, I couldn't see Ngpsql related dependency. Sqlite was used instead. Do you have a repo which includes both ef7 and npgsql which targets clr-core runtime ?

**Comment by hjgraca** [comment]
@sirentek sorry no I haven't. but from the error you are getting it seems like npgsql does not support coreclr yet. so you can't build it. try remove "dnx451": { }, from your frameworks. it will probably complain in visual studio dependencies. if that is the case you need to ask to npgsql devs in their repo when is a coreclr version available.

**Comment by sirentek** [comment]
If I remove dnx451, it will create an other error. (Tried before) It will try building it while targeting dnx451 although it doesn't have any dependency. Thanks anyway!
