### ISSUE TITLE
Remove Microsoft.DiaSymReader.Native.*.dll from DNX packages

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#3128]
These files are needed only for "deterministic compilation" (i.e. produce identical PE files on rebuilds):
* Microsoft.DiaSymReader.Native.amd64.dll
* Microsoft.DiaSymReader.Native.arm.dll
* Microsoft.DiaSymReader.Native.x86.dll

It's not clear that they're truly needed in DNX, so we should consider removing them from DNX.

@davidfowl we're looking at this for RC1 so please take a look and chime in when you have a chance.

**Comment by davidfowl** [comment]
We don't use this feature yet but we'd want to enable it

**Comment by Eilon** [comment]
@davidfowl so move to RC2? We currently have an issue with these DLLs but it looks like the Roslyn folks are fixing it (file signature issue), so this is less urgent for RC1.

**Comment by davidfowl** [comment]
Yep

**Comment by davidfowl** [comment]
Doesn't matter anymore
