### ISSUE TITLE
Unify how paths to native libs are resolved for package and project references

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#3132]
For package references we now just read the "native" section from the architecture specific target in the project.lock.json file. For project references we try to load native libraries from a project subfolder but we don't use the same mechanism for creating the path to native libs that is used to create architecture specific targets in project.lock.json file. As a result in the case of project references we don't have all the fallbacks that are in place when using a package reference (e.g. if the native library is located in the `runtimes/win-x64/native/mylib.dll` it will work with a package reference but not with a project reference, - `runtimes/win7-x64/native/mylib.dll` will work in both cases though).

**Comment by davidfowl** [comment]
Not sure this is still relevant for CLI work
