### ISSUE TITLE
Published source projects missing signing key

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#3135]
https://github.com/aspnet/IISIntegration/pull/28

Is there a way to include the signing key when publishing a project via source?

**Comment by moozzyk** [comment]
I was thinking about this after I saw your bug and was wondering how common it is to publish sources for projects that need to be signed - typically people keep their snk private in which case this won't work.I am also wondering if it is possible just to use scripts that run on publish to take care of copying the file in cases you want to publish sources and the snk.
