### ISSUE TITLE
Getting wrap error: Unable to find output assembly name for project reference...

### ISSUE THREAD

**Issue by manastalukdar** [aspnet/dnx#3137]
When I run the dnu wrap xyz.csproj command, I get the following error:

Error: Unable to find output assembly name for project reference 'abc' in dumped metadata

abc is another csproj referenced in xyz. I was able to successfully wrap abc. Any pointers?

**Comment by davidfowl** [comment]
What's special about abc? Hard to know what's wrong without more information? Can you make a sample that reproduces the problem to put on github?

**Comment by manastalukdar** [comment]
abc: https://github.com/manastalukdar/QiTwitterDemo/tree/master/src/QiTwitterDemo.Contract
xyz: https://github.com/manastalukdar/QiTwitterDemo/tree/master/src/QiTwitterDemo.Helper

For some reason, this problem now does not appear to occur from my work machine (has same software as other machine where it was not working earlier).

Going to close this issue for now.
