### ISSUE TITLE
dnu command uninstall: command is not installed

### ISSUE THREAD

**Issue by CallMeLaNN** [aspnet/dnx#3138]
I have dnvm `1.0.0-beta5` and `1.0.0-beta8`. `1.0.0-beta8` is default and activated.

I install the 'proabably outdated command' from this doc:

    dnu commands install SecretManager

However I realize it is not the one I should run, because I saw the download URL of some nuget package contain 'beta5'. I supposed to run the below command based on this doc:

    dnu commands install Microsoft.Framework.SecretManager

I should uninstall the old one first like this:

    dnu commands uninstall SecretManager

but then I got:

    SecretManager command is not installed.

**Expected**
It supposed to uninstall successfully.

**Workaround**
I force install `Microsoft.Framework.SecretManager` using `--overwrite` option to replace the existing `user-secret` command.

**Comment by BrennanConroy** [comment]
SecretManager is not the name of the command to uninstall
```dnu commands uninstall user-secret```
