### ISSUE TITLE
dnx.win32.dll could not be loaded. Last error: 126 (system profile)

### ISSUE THREAD

**Issue by brent-russell** [aspnet/dnx#3140]
Similar to #2666 and #2648 but neither of those has any resolutions documented.

In my case this is happening on a build server, so the commands are being executed under a system profile. Under beta7 everything worked. The issue appeared after moving to beta8. When dnx or dnu commands are run, the error "dnx.win32.dll could not be loaded. Last error: 126" is returned. A powershell build script does the following:

1. Set a bunch of path variables
2. run dnvm install for a specified .net version (success)
3. dnvm use the just installed version (success)
4. dnvm alias default the just installed version (success)
5. dnu / dnx stuff (fail)

Following some of the suggestions from #2666, I verified the path was set correctly, the runtime install exists at the path, and dnx.win32.dll exists. The path for the system profile dnx is C:\Windows\System32\config\systemprofile\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta8\bin

When I run through the script or commands on my own user profile on the same machine, there are no issues.

**Comment by moozzyk** [comment]
What is the OS? Also dnx living in the Windows\System32 does not seem right - are you sure you don't get permission issues? Have you tried setting DNX_HOME to move the runtime out of windows folder? I think if you set this machine-wise all profiles will use it so it may be easier to troubleshoot.

**Comment by brent-russell** [comment]
OS is Windows Server 2012 R2 x64

It's under system32 because the build process runs as the system user, so .net versions get installed under the "systemprofile" user profile, which lives in system32.

I can't rule out permissions issues, but again the process is running as the system user and using its profile, and dnx was working under beta7.

I currently have DNX_HOME set to C:\Windows\system32\config\systemprofile\.dnx because this is where dnx was installed by default when the process first ran. I'll try setting it to a different location and forcing the script to install dnx elsewhere.

Thanks, and I'll let you know if it that changes anything.

**Comment by brent-russell** [comment]
I set the build/script's DNX_HOME environment variable to a path inside the build working directory, and that solved it. I like this location much better.

Thanks.
