### ISSUE TITLE
Running DNX on Lego Mindstorms EV3

### ISSUE THREAD

**Issue by pgrudzien12** [aspnet/dnx#3145]
It would be great to see Lego Mindstorms EV3 running ASP.NET 5. I would very much like to see it running directly on the brick. Solutions that remote controls lego and needs permanent or temporary connection is out of discussion.

Few things I see here:
- it is cool
- it could serve for educational purposes in schools (which I think is in line with overall MS strategy for ASP.NET 5)
- it would expand dnx ecosystem
- it would allow people to program Lego the way they want (as I fell it for myself)

Things to discuss:
What do you think about support for this scenario? 
Do you see any value in it/is anyone interested in it?
Do you see any other approaches i haven't described below?
How do you like each of the approaches?
What have to be done to enable this scenario?
Do you know of any successful attempts?
And anything that you feel is important to discuss.

I think that there are at least two main approaches:
## 1. Construct own firmware.

I know we have Mono-Brick and Lejos projects that takes this approach. Both projects are based on the same image of linux but they run different runtime.

Pros:
- probably faster boot startup as dnx would stay in the internal memory
- does not need SD card to boot

Cons:
- restrictions on system/packages size
- probably every program would need to deliver own set of packages
- problems with system packages upgrade
## 2. Run Linux on top of Lego like ev3dev does

As EV3 has ARM processor I tried running ASP.NET on Raspberry PI 2 using ev3dev Debian linux with success. I was able to run kestrel and reach it from my own machine. 

The same thing does not work on EV3 probably due to package problems. I tried to install Xamarin compilation of mono but they apparently do not support armel architecture as noted here:
https://github.com/ev3dev/ev3dev/issues/423. I think that this approach is doable with some support from community.

My attempt to run this is described on my blog (I published this only for reference for this conversation) here:
http://bleedingnedge.com/2015/11/08/asp-net-5-on-lego-mindstorms-ev3-using-ev3dev/

Pros:
- open architecture
- easy setup eg. with sd card image with dnx and mono
- infinite possibilities of integration
- support from community
- no need to flash internal memory of Lego
- low chance of breaking the brick

Cons:
- needs sd card 
- slower startup

I imagine that we could do something _like_ `dnu publish` that could upload program directly onto the brick. Also remote debugging could be possible.

**Comment by Eilon** [comment]
I totally need an excuse to buy the Mindstorms EV3 :smile:

**Comment by pgrudzien12** [comment]
It seems that mono-brick and lejos does not need flashing so they work more like (or exactly the same as) ev3dev.

**Comment by dlech** [comment]
MonoBrick and leJOS are based on the official firmware for the EV3 from the LEGO Group and are a generic Linux with no type of packaging system and a rather old kernel (2.6.32). ev3dev is Debian Linux (jessie) and has totally different hardware drivers and a contemporary kernel.

It looks to me like getting dnx setup takes massive amounts of RAM. I read on Hanselman's blog that one component takes 400MB while installing. The EV3 only has 64MB. I suggest looking at the ev3dev [brickstrap](https://github.com/ev3dev/brickstrap) tool. It provides an environment similar to Linux Containers that allows you to build and install software on a host computer and then create a bootable SD card image that can be used on the EV3.

**Comment by caioproiete** [comment]
I totally need an excuse to buy the Mindstorms EV3 :smile: [2]

**Comment by victorhurdugaci** [comment]
@Eilon can we get a few Mindstorms for the team? I mean, you know, for *development* and *testing* purposes...

**Comment by Eilon** [comment]
Yeah I'll expense a few... for me :smile:

**Comment by pgrudzien12** [comment]
I need a second set :) - you know someone has to test communication between bricks.

**Comment by pgrudzien12** [comment]
With a lot of struggles I finally managed to fire up Hello World example on the brick. Compilation still does not work but with publish --no-source program runs.

Does anyone knows if "Could not determine OS" has any repercussions and I should be worry?

```
root@ev3dev:~/code/home/samples/1.0.0-beta8/ConsoleApp/bin/output/approot# ./ConsoleApp
Could not determine OS version information. Defaulting to the empty string.
Hello World
```

**Comment by victorhurdugaci** [comment]
That's awesome! 

Probably `IApplicationEnvironment` will give wrong results and anything relying on it (a lot!) will fail.

**Comment by victorhurdugaci** [comment]
Did you use mono or coreclr?

**Comment by dlech** [comment]
I played around with this a bit as well. I noticed [this](https://github.com/aspnet/dnx/blob/1e32361b54373fa6251e756b7865a04da932afcf/src/Microsoft.Dnx.Host.Mono/EntryPoint.cs#L265). The EV3 is `armv5tejl`, so it will be detected as `x86`.

**Comment by pgrudzien12** [comment]
I used mono

**Comment by pgrudzien12** [comment]
@dlech indeed it is. In every command I run there is this :

```
root@ev3dev:~/code/home/samples/1.0.0-beta8/ConsoleApp/bin/output/approot# dnu restore
Could not determine OS version information. Defaulting to the empty string.
Microsoft .NET Development Utility Mono-x86-1.0.0-beta8-15858
```

**Comment by pgrudzien12** [comment]
@victorhurdugaci I thought CoreCLR is not supported at all at ARM architecture. When I try to install DNX with ` dnvm upgrade -arch ARM -r coreclr` dnvm prints this `Architecture must be x86 or x64`.

I do not know what is behind that restrictions. Do you think that running CoreCLR is possible?

**Comment by moozzyk** [comment]
@pgrudzien12 - Have you seen my [comment](http://stackoverflow.com/questions/33541630/dnx-on-lego-mindstorms#comment54974430_33541630)? There is no CoreClr for Linux ARM available as a drop currently. You could try building it from sources. Once you get the CoreClr creating a runtime shouldn't be that bad (it took me a few hours to hack the first version of the ARM dnx for Win10 IoT Core once I found the right CoreClr).

`dnvm.sh` was not updated for arm since the dnx arm runtime works only on Windows so only `dnvm.ps1` is aware of this architecture. 

@dlech - not being able to detect OS version or architecture will show up mostly in places where there native code needs to be used (e.g. Kestrel). In case this causes problems you could try setting the `DNX_RUNTIME_ID` environment variable accordingly (and obviously provide the correct versions of dependencies - e.g. in case of Kestrel you would have to build libuv). For CoreClr when creating a Linux ARM version you would have to change this [line](https://github.com/aspnet/dnx/blob/72d8a95c584b25a4b150b735407c1e5d7605a148/src/dnx.coreclr.unix/dnx.coreclr.cpp#L341) to something similar that we do for windows [here](https://github.com/aspnet/dnx/blob/097c7e55a6ddc6b13831949c86a9633f71714387/src/dnx.coreclr/dnx.coreclr.cpp#L253-L259) to get the correct architecture.

**Comment by pgrudzien12** [comment]
@moozzyk Thanks for information. I'll keep that in mind for next time. This seems very advanced as I have no experience with compiling CoreCLR yet. Moreover it would need cross compiling because taking into account size of this machine (in terms of speed and ram) it would take ages to compile on the device. Needless to say that this is not my field of expertise.

For now I think that I'll focus on stabilizing dnx+mono architecture.

1. Compilation does not work (but this is not main concern as compilation on brick would be slow and I wouldn't use it either way)
2. I haven't tried anything more complex than hello World (yet)
3. I'd like to port ev3dev Lego API (at least some part of it) in order to be able to do something more useful.

**Comment by Eilon** [comment]
@pgrudzien12 we certainly look forward to anything you come up with!

**Comment by moozzyk** [comment]
@pgrudzien12 - out of curiosity what were the problems with compilation?

**Comment by pgrudzien12** [comment]
@moozzyk You asked for it :D. I tried to be as concise as possible. I am trying to compile almost vanilla version of ConsoleApp from Home repo (with `CoreCLR` removed):

Out of the box after installation of mono 4.0.4 rolsyn compiler from `dnu build` throws `error CS0009: Metadata file '/usr/lib/mono/4.5/mscorlib.dll' could not be opened -- Invalid public key`. This was my initial problem I end up at my blog. There are of course other errors later with loading assemblies. Most probably resulting from this one.

I've managed to replace compiler with my own version that gives more information and it seems that as far as compiler is aware the public key of mscorlib.dll is too long. It's string representation (`publicKeyOrToken` variable at the point where it throws exception)  is `/ws/2005/05/identity/claims/streetaddresszhttp://sch`. It expects 8 bytes but gets far more from this string. I assume that string (hexadecimal) representation of this key should be "b77a5c561934e089" - the 8 bytes compiler expects. Even if it should be some kind of other token (this looks like claim) it still does not look good considering:

1. `http://` at the end of this string, 
2. missing `http` at the beginning (if it suppose to be a claim)
3. the fact that code explicitly says that this `publicKeyOrToken` should be length of 8.

My conclusions: either way mscorlib I have is corrupted or roslyn has a bug. 

So I loaded this mscorlib with ILSpy. Public key is "PublicKeyToken=b77a5c561934e089", architecture is AnyCPU and all other decompiled code looks ok. The assembly come from xamarin repo "http://origin-download.mono-project.com/repo/debian/dists/wheezy/main/binary-armel/" so I suppose it should be ok.

On the other hand I thought that if arch is AnyCPU then it should be the same assembly as in windows mono. So I installed Mono, replaced mscorlib file on the brick with windows version. I think that this step is safe enough but on the other hand I can't rule out that following errors come from this step.So I got stuck with this message:

```
(1,29): DNX,Version=v4.5.1 error CS0648: '' is a type not supported by the language
(2,29): DNX,Version=v4.5.1 error CS0234: The type or namespace name 'AssemblyVersionAttribute' does not exist in the namespace 'System.Reflection' (are you missing an assembly reference?)
(3,29): DNX,Version=v4.5.1 error CS0648: '' is a type not supported by the language
/root/code/home/samples/1.0.0-beta8/ConsoleApp/Program.cs(7,9): DNX,Version=v4.5.1 error CS0518: Predefined type 'System.UInt64' is not defined or imported
```

If I copy compiled ConsoleApp without source directly to the device it runs ok with both versions of mscorlib.

I am not sure if I should file a bug to mono or roslyn. I saw that there is mono version of roslyn but I assume also that if "normal" roslyn if incompatible with mono then it should not work on Raspberry PI 2 as well. But obviously it works ok. 

Btw thanks for your support your aid and kind words. Every advice I get from you and ev3dev (@dlech) is very informative and helpful. I think I would not get this far without your support.

And one other thing remains - restoring packages on mono is very painful. Around 60% of times I get `HTTP request timed out. Exiting.`. I tried setting `export MONO_THREADS_PER_CPU=2000` but it doesn't help at all. Am I doing something wrong here (a typo maybe or I should set this variable differently)?

**Comment by pgrudzien12** [comment]
I'm proud to announce that ASP.NET 5 is now able to shoot red balls guys !!! https://youtu.be/lCFWwI6eL2g (sorry for bad quality and my accent - I'm working on it) :dancers: 

Updated also my blog post so if anyone is interested how to run it here you go: http://bleedingnedge.com/2015/11/08/asp-net-5-on-lego-mindstorms-ev3-using-ev3dev/

Thanks again for your help :+1:

**Comment by dlech** [comment]
:heart_eyes: 

Now, if we can just get `dnu publish` on the host computer to AOT compile for armv5 we will really have something here!

**Comment by Eilon** [comment]
This. Is. Cool. !!!!!!!

@coolcsh @shanselman @richlander check this out - DNX running on Lego Mindstorms EV3 :smile: !!!

**Comment by jskulavik** [comment]
So very impressive & exciting @pgrudzien12, bravo!

**Comment by Eilon** [comment]
@DamianEdwards FYI too.

**Comment by shanselman** [comment]
HOLY CRAP.

https://twitter.com/shanselman/status/667144339353526272

On Mon, Nov 16, 2015 at 11:11 AM, Eilon Lipton <notifications@github.com>
wrote:

> @DamianEdwards <https://github.com/DamianEdwards> FYI too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/dnx/issues/3145#issuecomment-157102539>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by Eilon** [comment]
@shanselman you can tweet the YouTube link as well: https://youtu.be/lCFWwI6eL2g (probably can't DoS YouTube as easily).
