### ISSUE TITLE
Version Restore Issue

### ISSUE THREAD

**Issue by endeffects** [aspnet/dnx#3152]
Hi Guys,

i have an issue with the version management of the dnu restore command. I have 2 Solutions, one for a class library (package) and a web applicaton.

The Package has a dependency for:
"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-*"

When i'm adding the package to my web application and running a package restore the dependency is changing it's version to:
"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc2-15788*"

Still if the web application is limited to rc1 at all.

My dnx runtime version is:
1.0.0-rc2-16138

From my point of view the restore should respect the versions of library dependencies, or?

**Comment by davidfowl** [comment]
That's by design. Take a look at your package sources. Versions are always a minimum unless you specify an upper bound. 

1.0.0-rc1-* means, prefer the highest matching the 1.0.0-rc prefix, OR the lowest >= 1.0.0-rc. If your configured feeds doesn't have any RC1 packages then thats the ONLY case where you'll get RC2. BTW the theres tons of warnings (not on restore) on compile when this situation happens.

**Comment by endeffects** [comment]
Well, i thought the prefix is "1.0.0-rc1-" and not "1.0.0-rc"?
Also, your daily feed has both versions, but i was not able to limit the version to rc1.

project.json of Class Library:

  "dependencies": {
    "Microsoft.CSharp": "4.0.0-beta-23109",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-*" 
  },

project.json of Web Application

    "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-*",
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-*",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-*",
        "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1-*",
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc1-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-*",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc1-*",
        "Microsoft.AspNet.Server.IIS": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*"
    },

But the project.lock.json of Web Application contains both version for most of the dependencies. Which ends up in a version conflict.

**Comment by davidfowl** [comment]
Your `project.json` has a mix of `1.0.0-rc1-*` and `1.0.0-*` that will almost never work. Be consistent and choose a single prefix. If you specify that you want rc1-* and it exists, you will get it. You have other dependencies that are likely pulling other transitive dependencies forward.

Here's my advice:

Until we ship stable builds you cannot mix and match versions, it will never work. Be consistent and the success rate will go up. This is true for the dnx version, and any package version for things that we ship (aspnet).

**Comment by davidfowl** [comment]
I'd also urge you to read this so that you can learn how to diagnose problems like these when they arise http://davidfowl.com/diagnosing-dependency-issues-with-asp-net-5/

**Comment by endeffects** [comment]
Well, i got your point and thanks for your help. But this is hard to handle with beta8, rc1 and rc2 versions out there. And the new strong naming makes it currently impossible to handle this on complex prototyps.

**Comment by davidfowl** [comment]
@endeffects It's hard if you mix versions. Stick to a single prefix and things will almost always work. What you *cannot* do is say `oh that feature looks nice` and update one of the ~60 packages we ship. We will get there but pre v1 that will not be possible as everything is currently interdependent. Upgrading one thing requires upgrading all things. Keep that mindset as we approach 1.0 then it'll be looser as we move on.

**Comment by endeffects** [comment]
I totally agree with you and i'm going to downgrade my dependencies as adviced. Thanks :)

**Comment by endeffects** [comment]
I tried to downgrade all dependencies to a dynamic and fix version lower than rc2, but the restore still upgrades to rc2.
