### ISSUE TITLE
DNU chooses latest local package, regardless of feeds, when using '*'

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#3153]
The scenario is to do some builds on a local machine using myget feeds that have the latest versions of packages (say http://myget.org/f/dotnet-core).  Then build a repo that is only using nuget.org.  Even though nuget.org only contains beta-23409, DNX is picking the local copy, beta-23509, from the cache.  This is incorrect.  In this particular case it was preventing me from building the NuGet repo because it was using an older version of DNX that didn't understand the latest packages.  DNX should only use the highest version from the feeds that are in view.

**Comment by davidfowl** [comment]
That's debatable

**Comment by ericstj** [comment]
Sure, but one could argue that the Nuget repo behavior is definitely a bug.  So is the recommendation to always use a local packages folder?  That seems to defeat the purpose of the cache.
