### ISSUE TITLE
RandomNumberGenerator on DNX 5.0

### ISSUE THREAD

**Issue by angelsix** [aspnet/dnx#3160]
Is there a plan in the RC to have the RandomNumberGenerator available in DNX50. Right now its only in 451.

**Comment by smbecker** [comment]
It already is available for DNX 5...

https://www.nuget.org/packages/System.Security.Cryptography.RandomNumberGenerator

**Comment by angelsix** [comment]
Great thanks. I had to add an explicit reference and its fine now.
