### ISSUE TITLE
Restore errors from the DTH no longer include the line and column number so are not squiggled in project.json

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/dnx#3161]
I verified that the same VS tooling running with Beta8 works fine. Looks like some recent change in DNX broke this feature.

_Updated by Troy_
We narrow down the scenario:
0. Set up a healthy project;
1. Change one reference's name so that the reference can't be resolved.
2. Save, VS restore the project, error message shows correct information.
3. Correct the reference's name. Without saving, change the version to an incorrect value.
4. Save, VS restore the project.
<Error> The dependency diagnostics message returned is not correct. Error locations are not set and message is wrong.

**Comment by davidfowl** [comment]
Nothing changed here AFAIK. Do you have a repro? 

/cc @troydai

**Comment by troydai** [comment]
I scanned through the places we created `DiagnosticMessage` and didn't find any obvious change. The format is still [there](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/DiagnosticMessage.cs#L19).

**Comment by davidfowl** [comment]
Yea sounds like a tooling issue. @BillHiebert can you paste the DTH response.

**Comment by BillHiebert** [comment]
"Errors": [
    {
      "ErrorCode": "NU1001",
      "SourceFilePath": "C:\\Users\\billhie\\documents\\visual studio 2015\\Projects\\WebApplication1\\src\\WebApplication1\\project.json",
      "Message": "The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc1-final could not be resolved.",
      "Severity": 2,
      "StartLine": 0,
      "StartColumn": 0,
      "EndLine": 0,
      "EndColumn": 0,
      "FormattedMessage": "C:\\Users\\billhie\\documents\\visual studio 2015\\Projects\\WebApplication1\\src\\WebApplication1\\project.json(0,0): error NU1001: The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc1-final could not be resolved.",
      "Source": {
        "Name": "Microsoft.Extensions.Configuration.Json",
        "Version": "1.0.0-rc2-final"
      }
    }
  ],
  "Warnings": []
})

**Comment by troydai** [comment]
The error position is indeed in the formatted message.

**Comment by troydai** [comment]
Ah, I see what you mean. The value are not set correctly.

**Comment by BillHiebert** [comment]
Very unfortunate that the squiggle feature is broken in RC1. Obviously we need better test coverage to catch this sooner.

**Comment by troydai** [comment]
I can't repo this on the RC1 test build. Talked with @BillHiebert , he's now narrowing down his repo scenario.

**Comment by troydai** [comment]
@BillHiebert @muratg 
Do we still need to fix this in RC2?

**Comment by muratg** [comment]
Yes, let's decide if this is something we'll need to do in the new DTH.

**Comment by davidfowl** [comment]
in the new DTH it should be fixed

**Comment by muratg** [comment]
:+1:

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#595
