### ISSUE TITLE
dnu publish solution.sln

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/dnx#3166]
I am using `dnu publish` on my continuous integration server to build .xproj projects into NuGet pacakges. It is a little tedious to have to execute the command for every project in the solution.

It would be nice if `dnu publish` or perhaps a new command entirely could be pointed at a solution of .xproj projects and could publish them all together.

**Comment by JorritSalverda** [comment]
+1  I would expect dnu build and dnu publish to behave similarly as dnu restore which can use a global.json file to scan multiple subdirs for project.json files.

**Comment by davidfowl** [comment]
> I am using dnu publish on my continuous integration server to build .xproj projects into NuGet pacakges. It is a little tedious to have to execute the command for every project in the solution.

Publish isn't about making packages, you're not using the right command. What you want is `dnu pack`.

You can use globbing patterns with `dnu build/pack` like so:

```
dnu pack src/*
```

**Comment by RehanSaeed** [comment]
Cool, that solves that problem.
