### ISSUE TITLE
`dnx-watch web` results in System.NullReferenceException under rc1-final

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/dnx#3170]
Hi,

When working with https://github.com/aspnet/Templates content in https://github.com/OmniSharp/generator-aspnet I've found that `dnx-watch web` no longer seems to work and I'm not able to debug the problem.
I've tried both Mono and CoreCLR:
Mono:
```
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-16147
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64
```
Running `dnx-watch web`:
```
dnx-watch web
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Dnx.Watcher.CommandOutputProvider..ctor (IRuntimeEnvironment runtimeEnv) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.Watcher.Program..ctor (IRuntimeEnvironment runtimeEnvironment) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
```

Under CoreCLR:
```
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-16147
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64
````
Invoking `dnx-watch web`:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.Watcher.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
   at Microsoft.Dnx.Watcher.Program..ctor(IRuntimeEnvironment runtimeEnvironment)
```

The errors have different stack trace slightly. I'm using web templates for rc1.

Thanks!

**Comment by BrennanConroy** [comment]
And what version of dnx-watch are you using

**Comment by peterblazejewicz** [comment]
Hm, I've tried to re-install, and it looks it still beta8?
```
dnu commands install Microsoft.Dnx.Watcher --no-cache
Microsoft .NET Development Utility Mono-x64-1.0.0-rc1-16147

  GET https://api.nuget.org/v3/index.json
  OK https://api.nuget.org/v3/index.json 397ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.dnx.watcher/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.dnx.watcher/index.json 1152ms
  GET https://api.nuget.org/v3/index.json
  OK https://api.nuget.org/v3/index.json 260ms
Restoring packages for /Users/piotrblazejewicz/.dnx/bin/packages/fe16379c14a44cf09e1a4c87e208a970/project.json
Writing lock file /Users/piotrblazejewicz/.dnx/bin/packages/fe16379c14a44cf09e1a4c87e208a970/project.lock.json
Restore complete, 216ms elapsed

NuGet Config files used:
    /Users/piotrblazejewicz/.config/NuGet/nuget.config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
  GET https://api.nuget.org/v3/index.json
  OK https://api.nuget.org/v3/index.json 232ms
Restoring packages for /Users/piotrblazejewicz/.dnx/bin/packages/Microsoft.Dnx.Watcher/1.0.0-beta8/app/project.json
Writing lock file /Users/piotrblazejewicz/.dnx/bin/packages/Microsoft.Dnx.Watcher/1.0.0-beta8/app/project.lock.json
```
```
dnu feeds list
Feeds in use:
    https://myget.org/f/aspnetrc1/api/v2
      Origin: /Users/piotrblazejewicz/development/WebAPIApplication/./nuget.config
    https://api.nuget.org/v3/index.json [Disabled]
      Offical NuGet Source, enabled by default
```
Does it mean I should simply force install to `rc1` somehow?

**Comment by BrennanConroy** [comment]
You need to run ```dnu commands install <package> -s <feed>``` and use the same DNX as the package version installed

**Comment by peterblazejewicz** [comment]
@BrennanConroy 
Yes, this is it. Sorry for a false flag post.
The command I used:
```
dnu install Microsoft.Dnx.Watcher --no-cache --source https://myget.org/f/aspnetrc1/api/v2 
```
Thanks!

**Comment by neilyoung** [comment]
Still the same exception.

dnu list

* Microsoft.Dnx.Watcher 1.0.0-rc1-final
  Microsoft.Dnx.Watcher.Core 1.0.0-rc1-final

Nevertheless

dnx-watch web
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.Watcher.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
   at Microsoft.Dnx.Watcher.Program..ctor(IRuntimeEnvironment runtimeEnvironment)

**Comment by OG84** [comment]
try running the command line as administrator

**Comment by neilyoung** [comment]
After some back and forth my dnx now has a --watch option, which works...

Microsoft .NET Execution environment Mono-x64-1.0.0-rc1-16202

Usage: dnx [options]

Options:
  --project|-p <PATH>              Path to the project.json file or the application folder. Defaults to the current folder if not provided.
  --appbase <PATH>                 Application base directory path
  --lib <LIB_PATHS>                Paths used for library look-up
  --debug                          Waits for the debugger to attach before beginning execution.
  --framework <FRAMEWORK_ID>       Set the framework version to use when running (i.e. dnx451, dnx452, dnx46, ...)
  -?|-h|--help                     Show help information
  --version                        Show version information
  --watch                          Watch file changes
  --packages <PACKAGE_DIR>         Directory containing packages
  --configuration <CONFIGURATION>  The configuration to run under
  --port <PORT>                    The port to the compilation server

**Comment by trentbullard** [comment]
when i use dnx --watch test, it simply runs my test suite and exits instead of showing this: [dnx-watch](http://docs.asp.net/en/latest/_images/dnx-watch.png). When i use dnx-watch (with or without any options) i get 
![dnx-watch error](https://cloud.githubusercontent.com/assets/6423662/15193143/07ef37be-1782-11e6-9f7d-2584f5b17c02.PNG)
i'm using 
![dnx version](https://cloud.githubusercontent.com/assets/6423662/15193175/2461b7d2-1782-11e6-8afd-c1d2e0b2477d.PNG)

any help would be great although i suppose i _can_ just click run tests in VS each time since its not _that_ annoying
