### ISSUE TITLE
dnu pack should pass developmentDependency from project.json into the .nuspec file

### ISSUE THREAD

**Issue by bradwilson** [aspnet/dnx#3172]
The DNX runner (among other things) should be considered a development dependency in NuGet terms. This is a valid value in the .nuspec file as of NuGet 2.8, but project.json doesn't seem to respect it or pass it through into the generated .nuspec file.

Related: xunit/xunit#667

**Comment by bradwilson** [comment]
Example: https://github.com/xunit/dnx.xunit/commit/bbafa29c1ef39d1c8d7174613c4cf2163b7b30dd

**Comment by davidfowl** [comment]
While I agree this should be supported (in some form), why would you need it? Who is using the dnx xunit package in this way?

**Comment by bradwilson** [comment]
I was doing it for completeness (marking all the runners with this flag) at the request of a user.

**Comment by davidfowl** [comment]
That's what I thought 😀

**Comment by muratg** [comment]
@davidfowl I hear pack is moving to nuget, not CLI.  Will talk to @yishaigalatzer later.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#552

**Comment by muratg** [comment]
This was copied to CLI. Reopening to triage it for NuGet as well.
