### ISSUE TITLE
DNX_BUILD_VERSION Environment Variable Not Working

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/dnx#3174]
Following on from [this](https://github.com/aspnet/dnx/issues/2190#issuecomment-156365219) issue, I tried using the DNX_BUILD_VERSION Environment Variable to set the build number of my class library (Package) projects. I wrote the following PowerShell script to test it:

```
# Pass version into the PowerShell script.
$version = $args[0]

[Environment]::SetEnvironmentVariable("DNX_BUILD_VERSION", $version, "User")

dnu restore Source\MyProject\project.json
dnu publish Source\MyProject\project.json --configuration Release --include-symbols --no-source --out artifacts
```

All my projects have the '*' character at the end of the version where it can be replaced by the build number:

```
{
  "version": "1.0.0-*",
  ...
}
```

Unfortunately, running the script above results in NuGet packages being generated with a version of '1.0.0' and a file name of 'MyProject.1.0.0.nupkg'.

**Comment by davidfowl** [comment]
It totally works (that's how we build our own stuff). The only different I see (and it shouldn't make a difference) is this:

```
[Environment]::SetEnvironmentVariable("DNX_BUILD_VERSION", $version, "User")
```

Not sure why you're setting the variable user wide.

**Comment by RehanSaeed** [comment]
I'm using Beta 8. I'll try machine wide instead, just in case that makes a difference.

**Comment by dougbu** [comment]
@RehanSaeed 
```
[Environment]::SetEnvironmentVariable("DNX_BUILD_VERSION", $version, "User")
```
doesn't set `$env:DNX_BUILD_VERSION` in the _current_ process. Change that line to
```
$env:DNX_BUILD_VERSION=$version
```

**Comment by RehanSaeed** [comment]
@dougbu That was it. Thanks!

**Comment by RehanSaeed** [comment]
I'm using the latest version of `nuget.exe` from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe and am getting the following error complaining about the version number when using the `nuget publish` command:

> '1.0.0-1' is not a valid version string.

How do you get around this internally?

**Comment by dougbu** [comment]
@RehanSaeed am I correct your issue has nothing to do with the `DNX_BUILD_VERSION` environment variable? If so, please close this issue again and comment on or perhaps reopen NuGet/Home#1486.

/fyi @emgarten

**Comment by RehanSaeed** [comment]
Would it be possible to allow `"version": "1.0.0.*` versions with a `.` instead of a `-`? I had a look at the source code and it's specifically looking for a dash.

**Comment by ankitbko** [comment]
@RehanSaeed Microsoft uses [semver](http://semver.org/) versioning scheme. Quoting from semver
>A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

 Also have a look at number 2 at [NuGet - Top 10 NuGet (Anti-) Patterns](https://msdn.microsoft.com/en-us/magazine/jj851071.aspx) document.

**Comment by RehanSaeed** [comment]
Thanks @ankitbko.
