### ISSUE TITLE
Switch DNX SDK Version breaks build in 3 ways

### ISSUE THREAD

**Issue by AArnott** [aspnet/dnx#3175]
Repro machine: Dev14 Update 1 (14.0.24705.00 vsuvscore.d)

1. Create new "Class Library (Package)" project
1. Build
1. Switch from Solution DNX SDK version 1.0.0-beta5 to 1.0.0-beta8
1. Build

```
1>------ Build started: Project: ClassLibrary4, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(159,5): error : Cannot connect to the design time host to perform the build. The following socket exception occurred: No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:57025
1>
1>  Build failed.
1>           0 Warning(s).
1>           1 Error(s).
1>
1>  Time elapsed 00:00:05.2549143
1>
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

1. Build again

```
1>------ Build started: Project: ClassLibrary4, Configuration: Debug Any CPU ------
1>c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary4\src\ClassLibrary4\project.lock.json(1-1): .NET Platform error NU1006: . Please run "dnu restore" to generate a new lock file.
1>
1>  Build failed.
1>           0 Warning(s).
1>           1 Error(s).
1>
1>  Time elapsed 00:00:01.2306026
1>
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

Building repeatedly after this point fails with the "dnu restore" error above.

Running "dnu restore" resolves the build break. But IMO I shouldn't need to drop to the command line to run a tool when I've only done things in VS. If "dnu restore" has to be run, then the UI in VS that lets me switch SDKs should run it for me.
The build then succeeds.

But when I then using the project designer in VS indicate that I want to "Produce outputs on build" and build again, the build fails with this output in the build window:

```
1>------ Build started: Project: ClassLibrary4, Configuration: Debug Any CPU ------
1>  C:\Users\andarno\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe --appbase "c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary4\src\ClassLibrary4" "C:\Users\andarno\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary4\src\ClassLibrary4" --configuration Debug --out "..\..\artifacts\bin\ClassLibrary4"
1>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
1>  File name: 'Microsoft.DNX.PackageManager'
1>     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1>     at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
1>     at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
1>     at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
1>     at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
1>     at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
1>  WRN: Assembly binding logging is turned OFF.
1>  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
1>  Note: There is some performance penalty associated with assembly bind failure logging.
1>  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

**Comment by AArnott** [comment]
Needless to say (I hope), running "dnu restore" resolves the build break. But IMO I shouldn't need to drop to the command line to run a tool when I've only done things in VS. If "dnu restore" has to be run, then the UI in VS that lets me switch SDKs should run it for me.

**Comment by davidfowl** [comment]
@AArnott You need to update the tooling in VS to beta8

**Comment by AArnott** [comment]
The build is broken at the command line too. And I have beta8 installed on this box. So what exactly is it I'm missing?

**Comment by nguymin4** [comment]
@AArnott I think what David meant is besides updating dnx-runtime to beta8, you should update your VS Web Tools to beta8 as well. [https://www.microsoft.com/en-us/download/details.aspx?id=49442](https://www.microsoft.com/en-us/download/details.aspx?id=49442)

I met a similar problem when upgrading from beta5 to beta7

**Comment by AArnott** [comment]
I see. Thanks. I'll give that a try. I would have expected that Update 1 would have included this though. Is that a bad assumption?

**Comment by davidfowl** [comment]
I'm not sure what's in update 1 /cc @sayedihashimi @barrytang

**Comment by sayedihashimi** [comment]
Update 1 should have beta8 installed minus the project templates.

cc @balachir @barrytang

**Comment by sayedihashimi** [comment]
@aarnot what's in global.json?

**Comment by AArnott** [comment]
@sayedihashimi I never modify global.json myself. But it seems to follow the settings changes made from VS. For instance, after the step to use beta8, the contents of global.json are:

```json
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta8",
    "runtime": "clr",
    "architecture": "x86"
  }
}
```

**Comment by sayedihashimi** [comment]
That looks right to me

**Comment by davidfowl** [comment]
@AArnott The version of Update 1 that you have doesn't have the new DNX tooling.

**Comment by AArnott** [comment]
I see. Is there a story for improved errors in VS or at the command line when the user is in this mismatched world?

My *very* limited understanding on this is I can use `dnvm use 1.0.0-beta8` followed by `dnu build` to build with beta8. If I can do this, why doesn't it also work in VS?

**Comment by BillHiebert** [comment]
Update1 should have beta8 tooling so unless you have RC of Update1 one you shouldn't see the failure about  not finding Microsoft.Dnx.PackageManager.  A number or renames occurred after beta5 so tooling which shipped in beta5 doesn't work with Beta8. However, with beta8 tooling installed, it should work correctly with beta5, beta6, beta7 and beta8 as we handle the differences internally.

To do a manual restore, you don't have to drop to the command line. You can r-click on the project node and select Restore Packages. 

I don't like the stack dump\exception that comes from the command line tools either. Hopefully going forward this will be improved so the errors are more clear as to the problem..

We should be handling changes to the framework version global.json (or via the application property page) and from the messages I see, we are. VS looks at this version when determining which version of DNX will be used for restore, build,  and project data from DesignTimeHost.

**Comment by AArnott** [comment]
Thanks, @BillHiebert. 
The repro machine is an Update 1 RC (newer than customers have, but older than RTM). The exact version is in my repro steps (first line).

**Comment by BillHiebert** [comment]
We pushed beta8 tooling in fairly late so most likely the version you have doesn't include it.

**Comment by davidfowl** [comment]
Closing this out. If the issue persists, file this on aspnet/Tooling
