### ISSUE TITLE
Running msbuild.exe /m on solution breaks with mixed DNX and classic libraries

### ISSUE THREAD

**Issue by BrianVallelunga** [aspnet/dnx#3177]
I have a solution that fails to build with msbuild when using the /m switch, but builds fine in VS and without the /m switch. The solution consists of an ASP.NET 5 (beta 8 and RC1) site referencing a classic .NET 4.5.1 project. There's also a unit test project for the site (DNX-based) and a unit test project for the classic .NET 4.5.1 project.
<img width="351" alt="dependencies" src="https://cloud.githubusercontent.com/assets/351190/11221225/ea22d608-8d31-11e5-9246-77a8889bdc65.PNG">

When running the build with msbuild, I receive the error: 

> DNX : error : Could not find file '.\EthicalSkeleton\src\EthicalSkeleton.ClassicLibrary\obj\Release\EthicalSkeleton.ClassicLibrary.dll'. [.\EthicalSkeleton\tests\EthicalSkeleton.UnitTests\EthicalSkeleton.UnitTests.xproj]

Yet checking the obj\Release folder shows that the EthicalSkeleton.ClassicLibrary.dll does in fact exist. I suspect that this is a timing issue and that the DNX builder is trying to build the EthicalSkeleton.UnitTests.xproj project in parallel before the EthicalSkeleton.ClassicLibrary has finished. This occurs even though the build order is:

EthicalSkeleton.ClassicLibary
EthicalSkeleton (site)
EthicalSkeleton.UnitTests
EthicalSkeleton.ClassicLibrary.UnitTests

For reference, this is running on a Surface Pro 3 (i5) with 8GB RAM running Windows 10 with the November update.

I'm happy to provide the source for this test project.

**Comment by wburgers** [comment]
Was this issue solved yet?
I would like to speed up our build, but this is the reason it fails to work in parallel.
