### ISSUE TITLE
project.json's version property should be extensible

### ISSUE THREAD

**Issue by AArnott** [aspnet/dnx#3178]
We want the libraries and packages we build with DNX to be stamped with a version as unique as the source code. And we want semver to roughly understand (assuming linear versioning) how to pick newer packages from older ones *independent of a particular build server*. We want reproducible builds, such that if I build a commit locally or in the cloud, the result is exactly the same, including the version that is calculated that is stamped onto the package and the assembly.

We also want to be able to backtrack from an assembly or package version to the source code that produced it.

This is encoded in [Nerdbank.GitVersioning](https://github.com/aarnott/nerdbank.gitversioning#where-and-how-versions-are-calculated-and-applied) but this extends MSBuild to work its magic. DNX doesn't use MSBuild so we need another way to influence where DNX gets its package versions, and the several assembly versioning attributes it produces while compiling. I'd love for this Nerdbank.GitVersioning package to be applicable to DNX projects via adding as a dependency and have it automatically work with DNX to get the version right.

**Comment by davidfowl** [comment]
You could just use assembly attributes for this. Specifically `[AssemblyMetadata]`

**Comment by AArnott** [comment]
I don't think that resolves the issue. The values for these assembly metadata need to be computed at build time, and DNX (AFAIK) doesn't offer me a way to hook into that pipeline. 
Also, that doesn't address the NuGet package version.

**Comment by GuardRex** [comment]
@AArnott You can script your way to a new version for each publish operation. You can run a PS script on "prepare" and provide whatever versioning logic you want. I needed a new patch version for each publish, so I whipped this up: https://github.com/GuardRex/net5-autoupdate-version

**Comment by AArnott** [comment]
Thanks, @GuardRex. But that requires a source code change to impact the build. Then to ensure the number keeps incrementing you have to check in the change. What I'm looking for is automation that can control the version *without* changing source code every time I build or publish.
And I want build and publish to be effectively the same thing. Every time I build a commit, the result should be the same, regardless whether it's a CI build, a local build, or a release build.

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#551
