### ISSUE TITLE
NullReferenceException when running dnu build with compile modules and not targeting matching DNX TFM

### ISSUE THREAD

**Issue by Antaris** [aspnet/dnx#3180]
Hi Team

I've encountered an issue since updating to the `rc1-final` bits released yesterday. My particular issue is around compile modules (yay!) and the new target framework moniker changes.

Given I have the following solution:

```
/global.json
  {
    "projects": [ "src", "test" ],
    "sdk": {
      "version": "1.0.0-rc1-final"
    }
  }


/src/ClassLibrary1/project.json
  {
    "version": "1.0.0-*",
    "description": "ClassLibrary1 Class Library",
    "authors": [ "abbottm" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",
    "dependencies": {
      "Microsoft.Dnx.Compilation.CSharp.Abstractions": "1.0.0-rc1-final"
    },
    "frameworks": {
      "net451": {
      },
      "dotnet5.4": {
        "dependencies": {
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "System.Collections": "4.0.11-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Runtime": "4.0.21-beta-23516",
          "System.Threading": "4.0.11-beta-23516"
        }
      }
    }
  }
/src/ClassLibrary1/ExampleCompileModule.cs
  public class ExampleCompileModule : ICompileModule { }

/src/ClassLibary2/project.json
  {
    "version": "1.0.0-*",
    "description": "ClassLibrary2 Class Library",
    "authors": [ "abbottm" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",
    "dependencies": {
      "ClassLibrary1": ""
    },
    "frameworks": {
      "net451": { },
      "dotnet5.4": {
        "dependencies": {
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "System.Collections": "4.0.11-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Runtime": "4.0.21-beta-23516",
          "System.Threading": "4.0.11-beta-23516"
        }
      }
    }
  }
/src/ClassLibary2/compiler/preprocess/RunExampleCompileModule.cs
  public class RunExampleCompileModule : ClassLibrary1.ExampleCompileModule { }

/src/ConsoleApp1/project.json
  {
    "version": "1.0.0-*",
    "description": "ConsoleApp1 Console Application",
    "authors": [ "abbottm" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "compilationOptions": {
      "emitEntryPoint": true
    },

    "dependencies": {
      "ClassLibrary1": { "type": "build", "version": "" }
    },

    "commands": {
      "ConsoleApp1": "ConsoleApp1"
    },

    "frameworks": {
      "dnx451": { },
      "dnxcore50": {
        "dependencies": {
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "System.Collections": "4.0.11-beta-23516",
          "System.Console": "4.0.0-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Threading": "4.0.11-beta-23516"
        }
      }
    }
  }
/src/ConsoleApp1/compiler/preprocess/RunExampleCompileModule.cs
  public class RunExampleCompileModule : ClassLibrary1.ExampleCompileModule { }
```

When I trigger a build (both in Visual Studio, and manually using `dnu build` on the `ClassLibrary2` project, I get the following output:

> dnu build
> Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202
> 
> Building ClassLibrary2 for .NETFramework,Version=v4.5.1
> Error: Object reference not set to an instance of an object.

Unfortunately no stack trace is dumped at this point, and the `-v|--verbose` option does not give anything more either.

Running the same `dnu build` command against `ConsoleApp1` yields a succesful build. I did discover a fix, which was to add the `dnx451` TFM back into `ClassLibrary2` and then the build works as usual.

It seems to be an issue when trying to run compile modules in a project that doesn't target specifically the same runtime as your current DNX. So if my active dnx flavour is `dnx-clr-win-x86.1.0.0-rc1-final`, I must have the `dnx451` TFM in my `project.json`. If I change my dnx flavour to `dnx-coreclr-win-x86.1.0.0-rc1-final`, I must have `dnxcore50` TFM in my `project.json`.

I think I understand why, because you _use_ DNX to build projects, so DNX itself must be able to load preprocess compilations, therefore those libraries that have preprocess aspects must provide a TFM target that matches the DNX flavour you're currently running?

I don't see this as being a big issue really, as it's solved by adding the missing TFM, but I don't know if it will have any knock-on effects with package deployments that target the .NET Platform Standard TFMs? I gather they'd just use the specific TFM libs that happen to exist because of DNX-specific target?

I've added a [repo on GitHub](https://github.com/Antaris/RC1-TFM-CompileModileIssue/tree/master/src) which replicates this issue. In it's current state, `ClassLibrary2` won't build, but add the `dnx451` target to the `project.json` and it builds fine (assuming your running a `clr`, not `coreclr` DNX runtime).

**Comment by Antaris** [comment]
As an update to this, I've run a build after `set DNX_TRACE=1` (cheers @davidfowl), and the following is the build output for a failing build:

>The default servicing root does not exist.
>Loaded module: dnx.clr.dll
>Found export: CallApplicationMain
>Information: [DomainManager] Using Desktop CLR v4.5.1
>Information: [LoaderContainer]: Load name=Microsoft.Dnx.Tooling
>Information: [PathBasedAssemblyLoader]: Loaded name=Microsoft.Dnx.Tooling in 15ms
>Information: [Bootstrapper] Runtime Framework: DNX,Version=v4.5.1
>Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202
>
>
>Building ClassLibrary2 for DNXCore,Version=v5.0
>Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
>Information: [ApplicationHostContext] Using Lock File Target: DNXCore,Version=v5.0/
>Information: [LibraryExporter]: Resolving references for 'ClassLibrary2'
>Information: [LibraryExporter]: ExportProject(ClassLibrary2, , DNXCore,Version=v5.0, Debug)
>Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
>Information: [ApplicationHostContext] Using Lock File Target: DNXCore,Version=v5.0/
>Information: [LibraryExporter]: GetProjectReference(Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler, ClassLibrary2, DNXCore,Version=v5.0, )
>Information: [LibraryExporter]: Resolving references for 'ClassLibrary2'
>Information: [LibraryExporter]: ExportProject(ClassLibrary1, , .NETPlatform,Version=v5.4, Debug)
>Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
>Information: [ApplicationHostContext] Using Lock File Target: .NETPlatform,Version=v5.4/
>Information: [LibraryExporter]: GetProjectReference(Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler, ClassLibrary1, .NETPlatform,Version=v5.4, )
>Information: [LibraryExporter]: Resolving references for 'ClassLibrary1'
>Information: [LibraryExporter]: Resolved 32 references for 'ClassLibrary1' in 3ms
>Information: [RoslynCompiler]: Compiling 'ClassLibrary1'
>Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [LoaderContainer]: Load name=System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [LoaderContainer]: Load name=System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>Information: [RoslynCompiler]: Compiled 'ClassLibrary1' in 214ms
>Information: [LibraryExporter]: Resolved 33 references for 'ClassLibrary2' in 267ms
>Information: [RoslynCompiler]: Compiling 'ClassLibrary2'
>Information: [LoaderContainer]: Load name=ClassLibrary2!preprocess
>Error: Object reference not set to an instance of an object.
>Error: Full Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.<>c__DisplayClass11_0.<GetCompileModules>b__0(CacheContext _)
>   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
>   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
>   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
>   at System.Lazy`1.CreateValue()
>   at System.Lazy`1.LazyInitValue()
>   at System.Lazy`1.get_Value()
>   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
>   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
>   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.GetCompileModules(CompilationTarget target)
>   at Microsoft.Dnx.Compilation.CSharp.RoslynCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
>   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver)
>   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
>   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
>   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
>   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
>   at System.Lazy`1.CreateValue()
>   at System.Lazy`1.LazyInitValue()
>   at System.Lazy`1.get_Value()
>   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
>   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
>   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
>   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
>   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(LibraryDescription root, String aspect, Func`2 include)
>   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(String name, String aspect, Func`2 libraryFilter)
>   at Microsoft.Dnx.Compilation.LibraryExporter.GetAllExports(String name, String aspect)
>   at Microsoft.Dnx.Tooling.BuildContext.ShowDependencyInformation(IReport report)
>   at Microsoft.Dnx.Tooling.BuildManager.BuildConfiguration(String baseOutputPath, IEnumerable`1 frameworks, List`1 allDiagnostics, String configuration)
>   at Microsoft.Dnx.Tooling.BuildManager.BuildInternal(String projectPath)
>   at Microsoft.Dnx.Tooling.BuildManager.Build()
>   at Microsoft.Dnx.Tooling.BuildConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
>   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
>   at Microsoft.Dnx.Tooling.Program.Main(String[] args)

**Comment by davidfowl** [comment]
The error is pretty bad but it is by design. You need to have the right TFMs in order to *run* the compile module.

**Comment by Antaris** [comment]
This can probably be closed as when RC2 drops compile modules *may* not exist until Roslyn supports then directly.
