### ISSUE TITLE
How to specify http port when using `dnx web`

### ISSUE THREAD

**Issue by txchen** [aspnet/dnx#3181]
I think --port is for compilation server. But how do we use a different port to launch web?
Always 5000 is not cool since I cannot launch multiple sites on local machine.

**Comment by Eilon** [comment]
@Tratcher ?

**Comment by Tratcher** [comment]
`--server.url=http://localhost:5000/` or just `--server.url=5000`

**Comment by txchen** [comment]
@Tratcher seems not working. I am using rc1 now.

**Comment by moozzyk** [comment]
Take a look at your `project.json` file - the port might already be specified there in the `web` command. If this is the case I think you could remove it and specify as the last parameter as @Tratcher showed.

**Comment by txchen** [comment]
@moozzyk nope
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "WebAPIApplication"
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug" : "1.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by Tratcher** [comment]
Try ` "web": "Microsoft.AspNet.Server.Kestrel --server.urls=http://*:5000/"`

**Comment by txchen** [comment]
@Tratcher Thanks! That works, but will this work with azure web apps? I think it would be better to support specify port via env_var or commandline.

I am closing this, thanks!

**Comment by Tratcher** [comment]
FYI: The difference between --server.urls=http://*:5000/ and --server.urls=http://localhost:5000/ is that localhost only listens on loopback addresses (::1), so you can only access it on the local machine.

When you publish to azure web apps don't set this, it will be picked up from the HTTP_PLATFORM_PORT env variable, but again that is only for loopback.

**Comment by txchen** [comment]
@Tratcher thanks for the tip. Maybe you should call it out in your doc, so that others don't have to ask the same question. I think this is a common task.

When we set the `server.urls` and use HTTP_PLATFORM_PORT, looks like it will listen to BOTH.
For me I will use the HTTP_PLATFORM_PORT during my development, because I don't need to change the project.json, and when I deploy to azure websites, it would not listen on two addresses.

**Comment by Mparaiso** [comment]
I was doing a search about this very subject, and I landed on that page, which didn't really help. This answer on stackoverflow explains precisely how to set the correct PORT and IP for a web application launched with `dnx web` : 

http://stackoverflow.com/questions/34212765/how-do-i-get-the-kestrel-web-server-to-listen-to-non-localhost-requests

As for 2016-05-08 , that solution works.

it involves creating a hosting.json file . A hosting.development.json can also be created and the correct manifest will be picked by Kestrel thanks to an environment variable, it is all detailed in the link above. No need to modify project.json or use HTTP_PLATFORM_PORT environment variable.
