### ISSUE TITLE
dnu publish size increased...use --framework to prune?

### ISSUE THREAD

**Issue by adamhathcock** [aspnet/dnx#3184]
We've been using dnu publish for the past several betas.  Now RC1 has doubled the size of our deployment on DNX 451.

It looks like all of the new packaging targets just adds more unnecessary DLLs in the publish structure.

I was hoping that "--framework dnx451" would prune things out as I thought there were issues that looked like this would make happen.  However, it doesn't seem anything is pruned.

What's worse is that I can't use --framework together with --runtime and I'd like the runtime included for xcopy deploys.

Is there any way to reduce the packaged dlls to just the ones I need?
If --framework is supposed to do that, why can't I use --runtime with it?
Am I way off base?

**Comment by adamhathcock** [comment]
Sorry, forgot to mention we're now on RC1

**Comment by davidfowl** [comment]
> It looks like all of the new packaging targets just adds more unnecessary DLLs in the publish structure.

Can you describe the unneeded ones?

**Comment by adamhathcock** [comment]
For example: a lot of the Extensions are targeting a dotnet version and net451 while I'm specifying dnx451 on the base application I'm publishing.  I would expect only to have dotnet (I think) in the published package dependency tree.  Not both targets for those Extension packages.
