### ISSUE TITLE
DocumentationMode compileOptions

### ISSUE THREAD

**Issue by couven92** [aspnet/dnx#3189]
There should be the possibility to assign the documentationMode in the compieOptions element in project.json to set the documentation mode to one of the DocumentationMode enumeration values.

This setting would be similar to setting the documentation warning checkbox in .csproj files.

Currently, setting DocumentationMode to Diagnostic and getting warning about missing documentation for publicly visible members, is only possible by creating a preprocessing ICompileModule. And when you do that all warnings are displayed, but e.g. Visual Studio does only show these warning after a compilation and not while coding as it does in usual C# projects.

**Comment by davidfowl** [comment]
This issue was moved to https://github.com/dotnet/cli/issues/312
