### ISSUE TITLE
Under certain circumstances, the pkg from get.asp.net creates user .dnx folder with wrong owner

### ISSUE THREAD

**Issue by flq** [aspnet/dnx#3191]
When I installed the package 1.0.0-rc1-15540 for OSX, the folder ~/.dnx seems to have been created with root as owner

This shows then when you do e.g.

    yo aspnet (with empty application)
    cd whatever
    dnu restore

It would fail with something like 

    Access to the path [snip]'/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final' is denied.

Running the command

    sudo chown me .dnx

would fix this.

**Comment by ardacetinkaya** [comment]
Even if I changed the owner for .dnx, I got the same error

**Comment by anurse** [comment]
Thanks for the report, we're aware of the issue and are investigating! @BrennanConroy @muratg

**Comment by muratg** [comment]
@ardacetinkaya what's the output of `ls -al ~/.dnx`?  (Especially the owner column, and the permissions column)

@BrennanConroy Please close this one too when the internally tracked one is closed as fixed.

**Comment by ardacetinkaya** [comment]
@muratg you may find the output. packages do not have permissions I guess.

![screen shot 2015-11-23 at 11 31 12 pm](https://cloud.githubusercontent.com/assets/4550197/11350495/6f2011ba-923a-11e5-9335-64b532c274f9.png)

And this is the upper folder
![screen shot 2015-11-23 at 11 34 07 pm](https://cloud.githubusercontent.com/assets/4550197/11350561/c67ba316-923a-11e5-8bd0-2cfc50f84150.png)

When I installed from installer, this was also owned by root.

**Comment by BrennanConroy** [comment]
```sudo chown -R Arda:group .dnx```

**Comment by BrennanConroy** [comment]
That will recurse the folders in .dnx

**Comment by ardacetinkaya** [comment]
Thanks a lot, this workaround fixes it.

**Comment by BrennanConroy** [comment]
PKG Fixed with Update1

**Comment by rdarioduarte** [comment]
Hi @BrennanConroy I'm experiencing the same issue but didn't get resolved with the workaround. Still Permission denied after changing the owner to myself. You said that it's fixed under Update1, how should I proceed? thanks

**Comment by rdarioduarte** [comment]
Hi again, seems like running chmod solved my issue, this was the command I run:
chmod 777 /Users/dario/.dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin/dnu
Thanks
