### ISSUE TITLE
dnx -p and --appbase

### ISSUE THREAD

**Issue by schotime** [aspnet/dnx#3196]
Is it possible to run both the -p and --appbase options.

The scenario is I want to execute a unit test command from the root directory, but specify the appbase as if I was running from the same location as the project.json file.

I get the error. Could not load file or assembly 'test' when trying to run.

dnx -p .\tests --appbase .\tests test

Thanks.

**Comment by davidfowl** [comment]
`-p` alone already does what you want.

**Comment by moozzyk** [comment]
No, because `-p` is expanded to `--appbase`. `dnx -p .\tests test` expands to `dnx --appbase .\tests Microsoft.Dnx.ApplicationHost test` so is what you are looking for.

**Comment by davidfowl** [comment]
?

**Comment by schotime** [comment]
This line in my tests 

```csharp
var configuration = new Microsoft.Framework.Configuration.ConfigurationBuilder()
    .Add(new JsonConfigurationProvider( "config.json"))
    .Build();
```

does not find the config.json file when running not in the directory itself. 
eg. I need to set the running path.

**Comment by davidfowl** [comment]
@schotime Did you try: `dnx -p {myfolder} test`

**Comment by davidfowl** [comment]
Wait I think I get what you're asking now. That code is in the application you are testing?

**Comment by schotime** [comment]
That code is in the test project and yes I did try it.

**Comment by schotime** [comment]
https://github.com/schotime/NPoco/blob/dnx/test/NPoco.Tests/Common/BaseDBDecoratedTest.cs#L27

**Comment by schotime** [comment]
Thanks to @davidfowl.
You must use the Extension Method `AddJsonFile` like so as it will set the path correctly.

```csharp
var configuration = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
    .AddJsonFile("config.json")
    .Build();
```

https://github.com/aspnet/Configuration/blob/dev/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationExtensions.cs#L60
