### ISSUE TITLE
Impossible to specify the Runtime Id of the target OS the app is published for

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#3197]
When publishing an app I can specify the target `--runtime`. This will include the runtime with the package along with the project.lock.json file. For windows the project.lock.json will contain however only entries for win7. This breaks when a package contains native dependencies that are OS version specific (in this case I think dlls for OneCore are the best example) because they won't be included in the package description in the project.lock.json. 
Currently it breaks in Kestrel because the project.lock.json contains only the `"DNXCore,Version=v5.0/win7-arm": {` target and libuv is in `win10-arm` folder. As a result libuv.dll is not included in the Kestrel package description and therefore is not loaded at runtime which in turn causes a crash. 
In case of Kestrel we can change the package to put libuv into win7-arm (even though win10-arm is technically more correct) folder but shipping a package that contains a dll for both win10/onecore and a downlevel/kernel32 is currently not possible.

**Comment by davidfowl** [comment]
@anurse  @moozzyk Relevant with the CLI?

**Comment by anurse** [comment]
Probably still relevant, but @moozzyk can confirm
