### ISSUE TITLE
Project is unsupported by current project and can not be referenced (RC1)

### ISSUE THREAD

**Issue by bluemmc** [aspnet/dnx#3198]
I have created a ASP.NET 5 RC1 web project and specified "dnx451" as the only framework in project.json. This allows me to add a old-style (non-DNX) 4.5.1 C# class library projects as dependencies but when I try to add a similar 4.5.1 F# class library project as a reference to the web project,  I get an error that the "Project is unsupported by current project and can not be referenced". Why does DNX care what language a referenced non-DNX class library is written in? 

P.S. As a workaround I can add the output DLL for the F# project manually but this is not exactly ideal. I does indicate however that there is no real reason for the error to occur when adding project references. It should work!

**Comment by davidfowl** [comment]
Please file this under aspnet/Tooling
