### ISSUE TITLE
DNX4.5.1 selected as framework even if I select 4.6 inside VS when creating project (RC1)

### ISSUE THREAD

**Issue by bluemmc** [aspnet/dnx#3199]
With RC1 in VS2015, I selected 4.6 as .NET framework and created a new ASP.NET 5 project. In the project.json however, "dnx451" is configured as .NET framework instead of "dnx46". Why?

**Comment by davidfowl** [comment]
That dialog is never read.

**Comment by davidfowl** [comment]
Also this is another aspnet/Tooling issue
