### ISSUE TITLE
Set custom value for AssemblyInformationalVersion

### ISSUE THREAD

**Issue by mjeanrichard** [aspnet/dnx#3200]
We currently use the AssemblyInformationalVersion-Attribute to add metadata about the build of this assembly (e.g. what build plan, which commit hash).
As far as I can tell there is currently no way to do this with vNext? Is such a feature planned or is there another way to address this issue?

See also https://github.com/aspnet/dnx/issues/1504#issuecomment-87222972

**Comment by Eilon** [comment]
You can add the attribute to your assembly in the normal way and DNX will leave it alone. At least, that's what *should* happen...

**Comment by mjeanrichard** [comment]
Thanks, after some testing I can see that the Problem is a different one. If the attribute is defined in a 'normal' code file then it works indeed as you say.
BUT if the attributes are defined in a liked code file (Visual Studio: "Add as Link") they are not picked up. In order to use the same attributes in every project we create one code file with the attribute in the solution root folder and link them into every project. But that does not seem to work (yet?).

**Comment by davidfowl** [comment]
Sure it does:

e.g.

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Sqlite/project.json#L16

https://docs.asp.net/en/latest/dnx/projects.html?highlight=working%20dnx#advanced-properties

```JSON
{
    "compileFiles": [ "../path/to/some/shared/file.cs" ]
}
```

**Comment by mjeanrichard** [comment]
Ok, thank you. That works fine!

I think it has to do with the way I add linked files. I usually add the linked file for the first project in my solution (which happened to be a conventional class library) and the just copy the links to the other project (which is faster the using the add dialog for every project). This works fine with conventional (old style) projects, but it does not update the project.json file with vNext projects. Everything looks fine in the solution explorer but the files are not compiled. I noticed that the "Add as Link" option is disabled when i try to add the file directly to the vNext project.

So, this is only an issue if you copy linked files from one project to another...
