### ISSUE TITLE
How to depend on a specific target framework of a NuGet package?

### ISSUE THREAD

**Issue by tuespetre** [aspnet/dnx#3205]
I am trying to use this nifty library from @JoshClose called [CsvHelper](https://www.nuget.org/packages/CsvHelper/) from a dnx console application. However, that package only defines the following folders in lib:
- `net20`
- `net35-client`
- `net40-client`
- `portable-net40+sl5+win8+wpa+wp8`

The project I am working on targets `dnx46`, and the version of the library that gets referenced is the `net20` version, which means I don't get to use a lot of my favorite features of that library. I want to be able to reference the `net40` target framework specifically so that I can use the extension methods and dynamic features.

I know I could submit an issue or contact @JoshClose about this for this particular package, but I think this points out an issue with dnx if there is no way to override which version of a package should be used. I haven't been able to figure out how to use a 'wrap' (like the kind produced by `dnu wrap`) to solve this, either.

**Comment by davidfowl** [comment]
> but I think this points out an issue with dnx if there is no way to override which version of a package should be used. 

You mean framework not version. If you want to override the nuget selection logic you need to edit the package. I don't see us adding a first class feature for picking a specific framework folder.

**Comment by tuespetre** [comment]
Correct, I did mean "target framework version."

I do have to wonder though -- is there an issue with the mentioned 'nuget selection logic' if it selects `net20` instead of `net40` for a `dnx46` project?

**Comment by JoshClose** [comment]
@davidfowl Is there a reason it's choosing net20 over one of the client profiles?

If I wanted to add DNX support to CsvHelper, should I follow Marc Gravell's posts? http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html

**Comment by davidfowl** [comment]
That could just be a bug in the logic we have.

@JoshClose yes. That's a great guide

**Comment by JoshClose** [comment]
@davidfowl Would you be able to confirm if this is a bug in your logic? I've had a few people reporting this. If it's an issue with with package structure or something, that should be a quick fix for me. I won't have to do the dnx work for a while still.

This same thing happened in VS/NuGet previously too. Here is the ticket for the NuGet issue from before. http://nuget.codeplex.com/workitem/2502
