### ISSUE TITLE
VS2015 with ASP.NET 5 RC1 Class Library DNX Build Error

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/dnx#3207]
When creating a new Class Library (Package) with VS2015 and ASP.NET 5 RC1 Tooling installed, the project.json contains:

```
"frameworks": {
        "net451": { }
    }
```

This causes grief when adding razor view precompilation. Changing to "dnx451" is required.

I do not have VS2015 Update 1 installed so that is most likely the cause.

**Comment by danludwig** [comment]
I do have vs update1 rc installed, and still creating a new class library project uses net451 instead of dnx451.

**Comment by redowl3** [comment]
I also have this issue and have vs update1 rc installed - very annoying.
