### ISSUE TITLE
Dnu restore fails with error "Sequence contains more than one element"

### ISSUE THREAD

**Issue by Flavien** [aspnet/dnx#3208]
Running `dnu restore` on my project on Linux causes an error: `System.InvalidOperationException: Sequence contains more than one element`.

See this gist for more details about the exception: https://gist.github.com/Flavien/daca89e3d0e0c084b033

**Comment by davidfowl** [comment]
Happens when you have a dependency duplicated

**Comment by Flavien** [comment]
Except I don't, at least not directly. I might be referencing a package that is already referenced by a dependency, but that should be ok, shouldn't it?

Here is the project.json:

```
{
  "version": "0.4.4-rc1-*",

  "dependencies": {
    "System.Net.WebSockets.Client": "4.0.0-beta-23516",
    "System.Text.Encoding": "4.0.11-beta-23516",
    "Microsoft.AspNet.Cors": "6.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.ViewFeatures": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.WebSockets.Server": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Newtonsoft.Json": "7.0.1",
    "Openchain.Abstractions": "0.4.4-rc1-*",
    "Openchain.Ledger": "0.4.4-rc1-*",
    "Openchain.Ledger.Blockchain": "0.4.4-rc1-*",
    "Openchain.Sqlite": "0.4.4-rc1-*"

  },

  "commands": {
    "start": "Microsoft.AspNet.Hosting --webroot \"Webroot\" --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:8080"
  },

  "frameworks": {

    "dnxcore50": {
      "dependencies": {
        "System.Runtime.Serialization.Primitives": "4.0.11-beta-23516",
      }
    },

    "dnx46": { }
  },

  "exclude": [
  ],

  "publishExclude": [
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by davidfowl** [comment]
ot could be in one of your other projects. Scan all of your project.json files not just the main one

**Comment by Flavien** [comment]
It seems to be coming from this, but it has no duplicates, and no dependency other than .NET Core itself:

```
{
  "version": "0.4.4-rc1-*",

  "dependencies": {
    "Microsoft.Data.SQLite": "1.0.0-rc1-final",
  },

  "frameworks": {
    "dotnet5.4": { },

    "net451": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0",
        "System.Xml": "4.0.0.0"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
Odd. Will take a look when I get a chance

**Comment by Flavien** [comment]
Something I noticed: if I remove the global.json file two levels up, dnu restore works fine. That's strange since there is no reference other than ``Microsoft.Data.SQLite`` in the file.

**Comment by davidfowl** [comment]
Odd. Can you a simple sample that shows the problem and put it in a repository somewhere?

**Comment by muratg** [comment]
@flavien Could you create a simple repro app and share with us?  We can make the error output such that it shows you where the problem is.

cc @yishaigalatzer

**Comment by Flavien** [comment]
I just tried to reproduce the issue from an empty project, but the issue doesn't repro in that situation.
