### ISSUE TITLE
Error occured to run DNX design time process dnx-clr-win-x86.1.0.0-rc1-final

### ISSUE THREAD

**Issue by brijmailid** [aspnet/dnx#3211]
I'm getting following error
Error occured to run DNX design time process(dnx-clr-win-x86.1.0.0-rc1-final) No Connection could be made because the target machine actively refused it [ ::ffff:127.0.0.1 ]:49660

**Comment by davidfowl** [comment]
Any more details? Can you reproduce this on any project? Are you using VS update 1? Did you install the RC1 tooling?

**Comment by glennsills** [comment]
I am seeing the same error. Below is my system info.

Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA669
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA669
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA669
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA669
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight HQL Service   2.0.2200.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2200.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30728.1602

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.159
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Visual Studio Tools for Universal Windows Apps   14.0.23309.00 d14oob
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by glennsills** [comment]
Rebooting solved the problem.
