### ISSUE TITLE
Linux - DNX Mono rc1 - dnx46 - error on start

### ISSUE THREAD

**Issue by kpocza** [aspnet/dnx#3212]
The websites here 
https://github.com/kpocza/thriot/tree/asp.net_5_rc1_dnx46/Service
run fine on Windows IISExpress+IIS with dnx rc1-final having dnx46 in the project.json files. 
https://github.com/kpocza/thriot/tree/asp.net_5_rc1_dnx46/Service/Management/Thriot.Management.WebApi/project.json

Every class lib targets .NET 4.6.

Previously I've used beta7 with dnx451 which was fine on Linux.

Now, after upgrading to rc1, I try the following on Ubuntu 14.04 LTS:
dnx --project /opt/thriot/api/approot/packages/Thriot.Management.WebApi/1.0.0/root kestrel

However the following error occurs:
System.InvalidOperationException: The current runtime target framework is not compatible with 'root'
Current runtime target framework: 'DNX, Version=v4.5.1 (dnx451)'
[capture](https://cloud.githubusercontent.com/assets/6399280/11454211/1d2ac1ea-9625-11e5-8a23-a600ead6160c.PNG)

It doesn't help if I specify --framework dnx46 or any other version.
I've installed the rc1-final version of dnx-mono, of course.
Mono is 4.2.1.

Not all of my Nuget packages support .NET Core, I cannot move to dnxcore.

**Comment by davidfowl** [comment]
Mono doesn't support .NET 4.6

**Comment by kpocza** [comment]
Meanwhile I've switched back to 4.5.1 and it's working.

**Comment by davidfowl** [comment]
Closing
