### ISSUE TITLE
dnx.win32.dll could not be loaded. Last error: 87

### ISSUE THREAD

**Issue by kaanoo2904** [aspnet/dnx#3213]
Similar to #2666 and #2648 but they're both closed with no resolution.

In my case here:

- Win 7 SP1 
- .NET Framework 4.5 , Powershell 3 installed
- No Visual Studio installed ( got DNVM and DNX through cmd)

- I've switched between coreclr and clr , x86 vs x64, still had this issue.

![image](https://cloud.githubusercontent.com/assets/10462294/11455491/e9a957c0-9695-11e5-8729-04d4cbd916cb.png)

![image](https://cloud.githubusercontent.com/assets/10462294/11455562/82aee2b2-9698-11e5-979a-92c8f4fb58a2.png)

![image](https://cloud.githubusercontent.com/assets/10462294/11455512/a4b7b674-9696-11e5-80fd-bf0c6064dcad.png)

I have multi-boot with 2 other system and both of theme work fine.
- Win10 with VS installed.
- Linux Mint 

![screenshot_2015-11-29_23-47-06](https://cloud.githubusercontent.com/assets/10462294/11458500/e967bdf2-96f3-11e5-89f2-96dfd03e8df6.png)

**Comment by muratg** [comment]
Adding @ghostkaa and @010227leo.

@moozzyk Could you have a look?

**Comment by moozzyk** [comment]
@ghostkaa @010227leo @kaanoo2904 - I think the common thing is that these are non-English Win7/2008R2 OSes. Can you confirm? Also, I assume you have the latest updates/service packs installed.

**Comment by kaanoo2904** [comment]
@moozzyk I use the Windows 7 Professional SP1 64Bit version, ( X17-59186.iso, I downloaded years ago , not remember where)  . I turn off windows update, but have .net 4.5 installed.

**Comment by 010227leo** [comment]
@moozzyk I install the latest updates, solve the problem. Thank you!

**Comment by moozzyk** [comment]
@kaanoo2904 - try installing latest updates - this apparently helped in  @010227leo to fix the issue. If it does not let me know what language you are using an I will try to repro this on the same version setup (but with latest updates).

**Comment by kaanoo2904** [comment]
@moozzyk Ok, it's work now . But I think you should include everything needed in dnx installer ? I ( and I believe many other dev also) prefer to turn off this windows update feature.

**Comment by moozzyk** [comment]
@kaanoo2904 I don't know what was missing that dnx couldn't run but it is not a DNX responsibility to provide updates - Windows Update is the mechanism of keeping your machine up to date. I also don't know why devs would prefer to turn off updates and a) be vulnerable b) miss important additions that make it impossible to run some apps (like dnx).

**Comment by aplex** [comment]
I have this problem reliably reproduced on clean 32-bit English version of Windows 7 with SP1 and empty console application built on dnx-clr-win-x86.1.0.0-rc1-update1.

It would be great if this can be fixed somehow, or at least minimum system requirements should be updated to demand latest updates.

**Comment by moozzyk** [comment]
@aplex In a few cases installing all the latest updates (not only SP1) fixed the issue.

**Comment by andy65007** [comment]
@moozzyk I think someone should fix this problem.first, it is a bug obviously, second, developer should dig in to the real problem to improve software quality。 
PS: I'm not sure is this correct: my pc's arch is win 7 x86_64, but the library "dnx.win32.dll" in error message include 32?

**Comment by moozzyk** [comment]
@andy65007 - 
1) if updating the machine fixes the issue then I don't think it's a bug per se. Why wouldn't you want to update your machine?
2) win32 in the name refers to the version of dnx linked against win32 libs as opposed to the one linked against onecore 
3) dnx is going away and we are not making any changes to it. You may want to look at dotnet cli which will replace dnx. If you want to continue to use dnx until dotnet cli is released please update your machine with latest service packs and patches.

**Comment by Nero0909** [comment]
KB2533623(https://support.microsoft.com/en-us/kb/2533623) fix this problem. As I understand, the problem occurs when call LoadLibraryEx WinAPI function, where flag LOAD_LIBRARY_SEARCH_DEFAULT_DIRS requires this KB(see https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179(v=vs.85).aspx). At least it helped me.
