### ISSUE TITLE
What is ASPNET_ENV default value?

### ISSUE THREAD

**Issue by jincod** [aspnet/dnx#3214]
```
"commands": {
  "web": "Microsoft.AspNet.Server.Kestrel"
},
...
dnx web
```

`Environment: Production`

Production value is default?

**Comment by jincod** [comment]
Answer: https://github.com/aspnet/Mvc/issues/3254

**Comment by GuardRex** [comment]
Post back if it fails to set the environment per https://github.com/aspnet/Mvc/issues/3254 ... It fails for me, but there was no answer at https://github.com/aspnet/Configuration/issues/342, so I assumed I was doing something wrong myself.

**Comment by jincod** [comment]
Solution for me:
```
"commands": {
  "web": "Microsoft.AspNet.Server.Kestrel",
  "dev": "Microsoft.AspNet.Server.Kestrel ASPNET_ENV=development"
}
```

For dev `dnx dev`, for production `dnx web`

**Comment by GuardRex** [comment]
@jincod I was hoping to keep my `Startup.cs` logic along the lines of ...
```c#
if(machineName.StartsWith("STABLE_SERVER_PREFIX_1", StringComparison.OrdinalIgnoreCase))
{
    Configuration["ASPNET_ENV"] = "Production";
    // Other settings here for running on Server environment #1
}
else if (machineName.StartsWith("STABLE_SERVER_PREFIX_2", StringComparison.OrdinalIgnoreCase))
{
    Configuration["ASPNET_ENV"] = "Production";
    // Other settings here for running on Server environment #2
}
else
{
    // Will be the result of using a local dev box or server
    Configuration["ASPNET_ENV"] = "Development";
    // Other settings here for running on local box or server
}
```
... the reason being that I like auto-detection of the physical environment to determine if the app should run in dev or prod. I don't like config files all over the place.

This logic started to fail in RC1, so I had to move over to checking the environment directly later in the app (i.e., not using the "ASPNET_ENV" var but instead looking at the server name everywhere. I don't use `.IsDevelopment()` or `.IsProduction()` any longer ... unfortunately).

**Comment by davidfowl** [comment]
Startup is too late to set the Environment name. There's a bunch of things that have already read it by that time (like the startup loader itself). That's how it knows to call configure{environment} on your startup class (if specified). You can always change the proper on IHostingEnvironment after the fact but the code that ran before that logic will see older values and might lead to inconsistent behavior.

In the latest RC release there's a program.main, that could be used to do the same thing since it runs early enough that you can get in between the startup logic and app for running

**Comment by GuardRex** [comment]
@davidfowl Thanks for telling me about that. I wondered what changed.

Like this in `Startup.cs`? ... in a web app?
```c#
internal class Program
{
    private static void Main(string[] args)
    {
        // Test COMPUTERNAME and set ASPNET_ENV here
    }
}
```

**Comment by GuardRex** [comment]
@davidfowl This isn't getting executed (or the env var isn't getting set) (dnxcore50, x64, IIS Express, standard web app pattern, RC1). I tried it inside and outside of the `Startup` class.
```c#
internal class Program
{
    private static void Main(string[] args)
    {
        string machineName = Environment.GetEnvironmentVariable("COMPUTERNAME");
        if (machineName.StartsWith("~~~~~~~", StringComparison.OrdinalIgnoreCase))
        {
            Environment.SetEnvironmentVariable("ASPNET_ENV", "Production");
        }
        else
        {
            Environment.SetEnvironmentVariable("ASPNET_ENV", "Development");
        }
    }
}
```

**Comment by davidfowl** [comment]
Yes to use main you need to call dnx run. You also need a hosting.json with the default web server

**Comment by GuardRex** [comment]
I think I'll stick with a direct machine name check in the `Startup` ctor and save my "environment" in configuration/options. It's not for BCL stuff ... just my own app settings. With the official environment default to Production, I'm fine with that.

I still think there is a slight loss here that the environment is set so early and out of reach of the dev, but I hear you on the startup loader ... makes perfect sense.

Given this situation, it would have still have been nice to at least be able to dictate the setting of the env var that would be used for the :sparkles: convenience magic of `.IsDevelopment()` and `.IsProduction()`. It's cool ... I might create my own extension `.IsAppDevelopmentMode`.

**Comment by GuardRex** [comment]
So just for completeness ...

Create an `ExtensionMethods.cs` file with something like ...
```c#
using System;
using Microsoft.AspNet.Hosting;

namespace MyApp.Misc
{
    public static class CustomExtensions
    {
        public static bool IsAppDevelopmentMode(this IHostingEnvironment myInterface)
        {
            if (Environment.GetEnvironmentVariable("ASPNET_APP_ENV") != null && 
                Environment.GetEnvironmentVariable("ASPNET_APP_ENV") == "Development")
            {
                return true;
            }
            return false;
        }
    }
}
```
In `Startup.cs` ctor, I have my own env var setup based on the environment (my server environment in this case) ...
```c#
string machineName = Environment.GetEnvironmentVariable("COMPUTERNAME");
if (machineName.StartsWith("VM_PREFIX_1", StringComparison.OrdinalIgnoreCase) ||
    machineName.StartsWith("VM_PREFIX_2", StringComparison.OrdinalIgnoreCase))
{
    Environment.SetEnvironmentVariable("ASPNET_APP_ENV", "Production");
}
else
{
    Environment.SetEnvironmentVariable("ASPNET_APP_ENV", "Development");
}
```
Then, I can do this elsewhere in the app ... I can bring in the namespace of my extension (`using MyApp.Misc;`) and `using Microsoft.AspNet.Hosting;`, inject `IHostingEnvironment env`, and ...
```c#
if (env.IsAppDevelopmentMode())
{
    // Do something for the local box or local server
}
else
{
    // Do something for the production servers
}
```
... and before a posse forms with pitchforks and torches for extending that interface (namely, not creating a new type from `IHostingEnvironment`) :facepunch: ... I locked the door to the office ... nobody can get in here! :no_entry_sign: ... a collision of method names is unlikely and nothing is changed by the method.

**Comment by GuardRex** [comment]
cc: @ardalis @danroth27 Vaguely relevant to https://docs.asp.net/en/latest/fundamentals/configuration.html?highlight=extension%20method#writing-custom-providers ... falls under your "extreme flexibility" in the closing paragraph of your excellent doc on the subject.

You may prefer to do what I did with `IOptions`, and that's entirely understandable, but I just wanted to mention that the concept of setting configuration based on the physical environment (not config files named like the environment or config files physcially in the environment), especially as it pertains to development vs. production, isn't part of the article ... and some may wonder about how it might be done.
