### ISSUE TITLE
Breakpoint in Main() is never reached

### ISSUE THREAD

**Issue by leak** [aspnet/dnx#3215]
Env: `1.0.0-rc1-final clr     x86          win             default`
`"emitEntryPoint": true`

Created an empty web application, converted the default Main() line to a method with body. Placed a breakpoint inside the body.

Breakpoint is never hit, yet removing the Main() method results in a compiler error.

**Comment by Eilon** [comment]
@davidfowl I think we looked at this the other day and weren't sure why it wasn't hitting. Does VS not attach early enough?

**Comment by davidfowl** [comment]
To run through the Main code path you need to use DNX run instead of DNX web. You'll also need a hosting.json to specify the sever
