### ISSUE TITLE
Using Microsoft.Dnx.Tooling programmatically?

### ISSUE THREAD

**Issue by uncleyo** [aspnet/dnx#3216]
For example to restore packages (in another project). Do you see this as valid use case?

Right now it is kept private in runtime "lib" folder. Are there any reasons to not make it available in the feed? Or is there an elegant way to reference it now?

**Comment by davidfowl** [comment]
Nope, the dnu is just a tool that will go away in favor of nuget. NuGet 3 will have these APIs available (and some already are). Restore is here https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Commands
