### ISSUE TITLE
What is the story for desktop applications? WPF? Qt? Gtk?

### ISSUE THREAD

**Issue by theonlylawislove** [aspnet/dnx#3217]
I know there are plans to support web and cli, but would about the others (non cli)? 

If we can get at least an empty project with no console, the community could get started writing Gtk or Qt bindings.

Also, provided their using dnx451, what is stopping someone from referencing PresentationCore/PresentationFramework (WPF) and running a UI thread? I understand that the xaml would have to be compiled in a separate traditional project for now, but I could see xaml compilation happening using the [MarkupCompile](https://msdn.microsoft.com/en-us/library/bb397829.aspx) MSBuild tasks currently used, although outside of MSBuild somehow. This would be very similar to how razor is compiled.

Oh man, this all gives me goosebumps...

**Comment by davidfowl** [comment]
No plans for anything but web right now. This might be a better question for corefx (https://github.com/dotnet/corefx). https://github.com/Perspex/Perspex is the only xplat UI stack that seems to have people working on it that I'm aware of.
