### ISSUE TITLE
resx resources get embedded with the wrong resource identifier if the project's default namespace differs from the project name

### ISSUE THREAD

**Issue by oliverw** [aspnet/dnx#3219]
The compiler currently embeds resx resources with the wrong resource identifier if the project's default namespace differs from the project name.

**Scenario:**

- Project Name: `ConsoleApp1`
- Default Namespace: `ConsoleApp`
- Resource Name: `Resource.resx`

**Expected behavior:**

The resource would be embedded as `ConsoleApp.Resource.resources`

**Actual behavior:**

The resource is embedded as `ConsoleApp1.Resource.resources`

This is especially bad as Designer.cs files generated from .resx resources use the correct identifier when instantiating the resource manager resulting in `MissingManifestResourceException`s thrown at runtime when accessing any of the generated properties.

[Link to demo project](https://onedrive.live.com/redir?resid=754261B3C2015CB0!95771&authkey=!AOguho3aeJSbV3g&ithint=file%2czip)

**Remark:** Since I'm not sure who is to blame here I've also created an identical issue in aspnet/tooling: https://github.com/aspnet/Tooling/issues/311

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#548
