### ISSUE TITLE
dnu publish doesn't resolve relative paths in global.json

### ISSUE THREAD

**Issue by runxc1** [aspnet/dnx#3223]
So I have a solution with 4 .net 4.5 (classic) projects in one folder and another .net 4.5 project in another folder and a dnx console app in another folder referencing all 5 of theses projects in the solution.

I can run/debug the solution but publishing from VisualStudio as well as the command line always gives me an error - Error NU1001: The dependency XXX.Library >= 1.0.0 could not be resolved

After battling with this on rc1-final and rc1-update1  I finally manually added the full path to the global.json of where the project.json files are at as opposed to the relative path that dnu wrap puts in and it would finally publish correctly.

**Comment by davidfowl** [comment]
Can you make a sample repro?
