### ISSUE TITLE
System.IO.File Alternative for DNX Core?

### ISSUE THREAD

**Issue by a11smiles** [aspnet/dnx#3226]
I've written middleware that uses the System.IO.File object (specifically, *.Exists() and *.ReadAllText()).

If, in my _project.json_, I have:

    "frameworks": {
      "net451": {
        "dependencies": {
          "Microsoft.CSharp": "4.0.1-beta-23516",
          "System.Collections": "4.0.11-beta-23516",
          "System.Linq": "4.0.1-beta-23516",
          "System.Runtime": "4.0.21-beta-23516",
          "System.Threading": "4.0.11-beta-23516",
          "System.IO": "4.0.11-beta-23516"
        }
      },
      "dnxcore50": { }

It will not compile, obviously, because System.IO.File doesn't exist in DNX Core 5.0.

Anyone recommend an alternative so that I can also target DNX Core 5.0?

**Comment by pranavkm** [comment]
You should be able to reference `System.IO: 4.0.11-beta-23516` from `dnxcore50`.

**Comment by a11smiles** [comment]
Intellisense keeps telling me that System.IO.File is not available in System.IO.

**Comment by anurse** [comment]
You want the `System.IO.FileSystem` package. You can use the unofficial "reverse package lookup" site: http://packagesearch.azurewebsites.net/ to look up which packages contain specific types.

That should resolve your issue, but if not please don't hesitate to reopen and let us know!

**Comment by a11smiles** [comment]
@anurse Thanks so much for the tip.  Additionally, thanks for the website.  Man, it always takes me a bit of time to "hunt and peck" for those types in the new packages and that site will save me a ton of hours.
