### ISSUE TITLE
Remove IAssemblyLoadContextAccessor and IAssemblyLoadContext from runtime services

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#3227]

**Comment by csunali** [comment]
Are we not going to be able to access those anymore?

I was using the IAssemblyLoadContextAccessor to load libraries from custom paths.

Sorry if I got the title wrong.

**Comment by smbecker** [comment]
Will there be a replacement or some other way to access? I also use it quite a bit.

**Comment by davidfowl** [comment]
Nope, see https://github.com/dotnet/corefx/issues/4027. Please add your comments there it'll help us push the feature back into the CLR. We can potentially keep exposing these interfaces as a separate library but they will need to be manually added to the container.

**Comment by csunali** [comment]
@davidfowl What I understand is that, you are getting rid of these interfaces in favor of providing consistent methods that we can do this on Core CLR? E.g.: `Assembly.LoadFile`?

If this is what you meant, I don't think I have any reason to ask for those interfaces being pushed back into the CLR.

**Comment by muratg** [comment]
@csunali Let's continue the discussion (and questions) here: https://github.com/dotnet/corefx/issues/4027.  This is basically dotnet CLI prep.

**Comment by pakrym** [comment]
Usages of `IAssemblyLoadContextAccessor`
```
Mvc\test\Microsoft.AspNet.Mvc.Test\MvcOptionsSetupTest.cs 
Scaffolding\src\Microsoft.Extensions.CodeGeneration\Program.cs 
Scaffolding\src\Microsoft.Extensions.CodeGeneration.EntityFramework\EntityFrameworkServices.cs 
Scaffolding\src\Microsoft.Extensions.CodeGeneration.Templating\Compilation\RoslynCompilationService.cs 
BrowserLink\src\Microsoft.VisualStudio.Web.BrowserLink.Loader\RegisteredBrowserLinkModule.cs 
BrowserLink\src\Microsoft.VisualStudio.Web.BrowserLink.Loader\RegisteredBrowserLinkModule.cs 
```

**Comment by csunali** [comment]
I am not sure if it is related to these bits you are discussing here but I am curious as to how may I access referenced assemblies of an Assembly object in Core CLR.

Full CLR provides the `assembly.GetReferencedAssemblies` method but I have no luck finding one for Core CLR.

Any help would be highly appreciated.

Cheers

**Comment by csunali** [comment]
And unfortunately using `ILibraryManager` is not an option since the assembly is loaded manually using `IAssemblyLoadContextAccessor.Default.LoadFile`.

**Comment by davidfowl** [comment]
@csunali you mean loaded assemblies right? https://github.com/dotnet/corefx/issues/1784

**Comment by csunali** [comment]
@davidfowl, yes. The issue you shared seems to be the right place to subscribe for notifications :)

Thank you!
