### ISSUE TITLE
New TFMs (dotnet5.4 and net451) for class libraries not 1:1 with old ones

### ISSUE THREAD

**Issue by pemari-msft** [aspnet/dnx#3230]
``WindowsAzure.Storage`` client library has been supporting all the way back since the days of the `ASPNet5.0` and `ASPNETCore5.0` TFMs. 

We currently have an existing `net40` dll that is GA. We also have `dnx451` and `dnxcore50` dlls that are in preview. Now I see the guidance [from here](https://github.com/aspnet/Announcements/issues/98) says that we should be changing our project.json targets to `net451` and `dotnet5.4` as we move to support `1.0.0-rc1-final`.

Currently, if we don't change our TFMs we get a resolution error when trying to resolve `System.IO.FileSystem 4.0.1-beta-23516` -- this is actually a breaking change for us as we took a dependency on `4.0.1-beta-*` which now won't resolve for `dnxcore50`. I suppose we could take a dependency on an older version of this going forward and keep the old TFM (whether it be in both our project.json and our nuspec or just in the nuspec), but that's neither here nor there. 

Setting those issues aside, my question is actually about the new TFMs, particularly `net451`. My understanding of nuget is that our preview package, which would have a `net40` and a `net451` dll, will cause any customers using regular Windows Desktop .NET 4.5.1 (which should be most of them, I think) to now get our new 'preview dnx451' dll that has different signatures for APIs and will cause a massive break. Am I misunderstanding anything regarding this? 

Further, how does dotnet5.4 relate to our `PCL Profile 111` dll that works with Xamarin? Are we finally at the point where we can use our CoreCLR dll as a replacement for PCL? 

Do you have guidance for this scenario? Please let me know if we should be discussing this via email/in person instead.

**Comment by khellang** [comment]
You should read through https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md. It should answer some questions :smile:

**Comment by pemari-msft** [comment]
I've read through it. It provides some details but I'm not sure how it particularly answers my questions, particularly about the `net451` and `net40` issue. Thanks!

**Comment by khellang** [comment]
> My understanding of nuget is that our preview package, which would have a `net40` and a  `net451` dll, will cause any customers using regular Windows Desktop .NET 4.5.1 (which should be most of them, I think) to now get our new 'preview dnx451' dll that has different signatures for APIs and will cause a massive break.

I'm not sure I understand... If you have a package with `net451` and `net40`, why would "our new 'preview dnx451' dll" be picked? Does the package also contain a `dnx451` target? Besides, I don't think there should be any difference in surface area for `net451` and `dnx451`?

> Further, how does `dotnet5.4` relate to our `PCL Profile 111` dll that works with Xamarin?

It doesn't, but `dotnet5.2` does. If you look at the document I linked, you'll see that profile 111 corresponds to `netstandard1.1`, which is the new name of `dotnet5.2` (there's an off-by-one error in there :wink:)

**Comment by pemari-msft** [comment]
>I'm not sure I understand... If you have a package with net451 and net40, why would "our new 'preview dnx451' dll" be picked? Does the package also contain a dnx451 target? Besides, I don't think there should be any difference in surface area for net451 and dnx451?

Let me try to clarify. We have a `net40` and `dnx451` dll today. When customers make a new Console Application targeting .NET 4.5.1 in VS 2015 (a regular one, not a (Package) one), and take a dependency on our library, they currently pull in the dll that exists in the `net40` folder as a reference.

Now, we're retargeting the `dnx451` dll to be -> `net451`. Now the package will have `net451` and `net40` dlls. In the exact same scenario as above, (A regular Console App targeting .NET 4.5.1) which dll will be pulled in? My understanding is it is the `net451` dll. Is this the case?

**Comment by Eilon** [comment]
@davidfowl any thoughts?

**Comment by davidfowl** [comment]
net451

**Comment by davidfowl** [comment]
Closing this
