### ISSUE TITLE
DNU Restore - Not Working - rc1-final

### ISSUE THREAD

**Issue by Fosol** [aspnet/dnx#3232]
I've upgraded to rc1-final.

dnu restore no longer obeys the packageSources I've listed when you add a network share.  
> \\someserver\sompath

This was working previously.

**Comment by Fosol** [comment]
Looks like there is an inconsistency in how configuration is setup and used.  If you disable something in your user profile it will disable the same named value in your local configuration copy.

**Comment by davidfowl** [comment]
yea bad nuget behavior
