### ISSUE TITLE
Using DNX for libraries

### ISSUE THREAD

**Issue by andschwa** [aspnet/dnx#3233]
I've run into some problems. We're building our application using DNX, and most of the time, when we want to launch the app (i.e. execute a managed `Main` function), we're fine, the DNX host works great.

However, we *also* need to be able to load the managed libraries and create delegates to managed library functions from native code, without ever launching any sort of `Main` function.

This is entirely unsupported with DNX, yet it's a very major usage scenario.

What makes matters worse is that, while we can re-implement the native host to not execute an assembly, we unfortunately also depend on the initialization that the DNX managed host performs, as we use the `PlatformServices.Default.LibraryManager`.

Short of forking and rewriting all of DNX so we can simply use managed libraries from native code, what can we do here?

**Comment by andschwa** [comment]
For what it's worth, `dotnet-cli` has the same issues, and more (they don't even support the `ILibraryManager` yet).

**Comment by davidfowl** [comment]
> However, we also need to be able to load the managed libraries and create delegates to managed library functions from native code, without ever launching any sort of Main function.

I'm not sure what you're asking for here. You want a way to invoke managed code from native code in the running app domain?

> This is entirely unsupported with DNX, yet it's a very major usage scenario.

I'm not sure it's major enough to support in a first class way. How did you do this in .NET Framework?

> What makes matters worse is that, while we can re-implement the native host to not execute an assembly, we unfortunately also depend on the initialization that the DNX managed host performs, as we use the PlatformServices.Default.LibraryManager.

What are you using it for?

> Short of forking and rewriting all of DNX so we can simply use managed libraries from native code, what can we do here?

Fork DNX.But it's going away anyways so you may not want to do that.

What exactly are you trying to do.

**Comment by andschwa** [comment]
> I'm not sure what you're asking for here. You want a way to invoke managed code from native code in the running app domain?

I need a way to create an app domain and invoke managed code, from a native shared library.

> I'm not sure it's major enough to support in a first class way. How did you do this in .NET Framework?

The upstream authors (and my way with our custom CoreCLR build system) do this by owning the entire native host: initialize the CLR, create delegates, use them, then shut down the CLR. Things I'd prefer to be able to do via a library, rather than reimplementation.

> What are you using it for?

We are (unfortunately) using it to get a list of the loaded .NET libraries so that we can build a type catalog cache, because the upstream project requires this.

> Fork DNX.But it's going away anyways so you may not want to do that.

Exactly. Unfortunately `dotnet-cli` has its own host of issues (it doesn't work out-of-the-box yet).

> What exactly are you trying to do.

My mouth is forced shut on this by our company's choice of secrets. I'll ping you on Monday and explain.

**Comment by davidfowl** [comment]
> I need a way to create an app domain and invoke managed code, from a native shared library.

Not sure how you can do this other than writing your own host.

> The upstream authors (and my way with our custom CoreCLR build system) do this by owning the entire native host: initialize the CLR, create delegates, use them, then shut down the CLR. Things I'd prefer to be able to do via a library, rather than reimplementation.

This bug is better suited for dotnet/coreclr and dotnet/corefx. If you're looking for a built in way to do something outside of owning a host then thats the place to go.

**Comment by andschwa** [comment]
What I'd like is a hosting library from DNX or dotnet-cli or CoreFX, so I don't have to redo all the setup work, and just call some functions. The CLR, DNX, dotnet-cli, and my internal project all have individual forks of what amounts to the same native host code.

More than that, however, is that to use `PlatformServices.Default.LibraryManager`, DNX does preliminary work in managed code that, again, I'd have to redo to use.

**Comment by andschwa** [comment]
Just FYI @davidfowl we got what we needed with respect to this issue using dotnet-cli. We still have to own the host, but the result of a `dotnet publish` was much easier to work with, especially without DNX's managed shim host.

**Comment by davidfowl** [comment]
Great! Will close this.

PS: I'd be interested to see what you're doing (if that is ever possible)

**Comment by andschwa** [comment]
I've talked a bit to @anurse of `dotnet-cli`, and if/when I get the time, I'd like to port the work I've done internally over to their native host, and just consume it from there. Will keep you updated.
