### ISSUE TITLE
An argument for dnx to set the process name

### ISSUE THREAD

**Issue by tuespetre** [aspnet/dnx#3235]
Since ASP.NET 5 is aiming to provide a highly scalable, deployable, or otherwise 'cloud-friendly' approach to writing applications, I think it is important to discuss [the 'processes' components of the twelve-factor methodology:](http://12factor.net/processes)

> ... a production deploy of a sophisticated app may use many process types, instantiated into zero or more running processes.

In order to properly identify the running instances of a process, it can be useful for each process to have a distinct name. This allows processes to be easily identified through various user interfaces and command line utilities that provide information on a node's running process, and if set via command-line arguments, allows other utilities like Powershell DSC to distinguish the instances of the running processes that they are supposed to manage.

I realize this can be implemented within each application with very little effort but I hadn't seen a discussion on this yet so I wanted to hear some other opinions.

**Comment by davidfowl** [comment]
We're not adding any features to DNX since it won't be used past RC1. The good news is this will be the default when using the new CLI. Each app with get a unique process name (matching the application name).

**Comment by benaadams** [comment]
w00p! :+1:

**Comment by tuespetre** [comment]
DNX won't be used anymore? As in, DNX is going away? Also, will the process name account for multiple instances of a running process, or will there be more of a bias to writing an application to use a configurable number of worker threads?

**Comment by benaadams** [comment]
@tuespetre is moving to [.NET Command Line Interface](https://github.com/dotnet/cli) was announced at Connect(); // 2015 and should be the way for RTM (as I understand)

**Comment by davidfowl** [comment]
> DNX won't be used anymore? As in, DNX is going away? 
Yes.

> Also, will the process name account for multiple instances of a running process, or will there be more of a bias to writing an application to use a configurable number of worker threads?

What does that mean? You get an executable file in your output folder (like the old days).

**Comment by tuespetre** [comment]
Ah, the CLI is something I missed entirely. It looks wonderful!

@davidfowl: I am talking about deployment and scalability, like managing multiple instances of the same process on a server. Think queue processors, etc.

**Comment by davidfowl** [comment]
@tuespetre What are you asking about that specifically? You want to set each title of your running app? 

```
mywebapp.exe (1)
mywebapp.exe (2)
...
mywebapp.exe (n)
```

Something like that? I'm not sure what feature you are asking for...

**Comment by tuespetre** [comment]
That is correct.

**Comment by davidfowl** [comment]
How would you do that if you could do it programmatically?

**Comment by tuespetre** [comment]
I would pass the desired process name as a command line argument when instantiating each process.

As I said, this doesn't take much at all to implement within each application that would even need this, so it may just fall under the category of 'other' and not really belong with the 'dnx' or 'dotnet run' commands.

**Comment by muratg** [comment]
This issue was moved to dotnet/corefx#4970
