### ISSUE TITLE
Unable to cast object of type 'FSharp.Dnx.FSharpProjectCompiler' to type 'Microsoft.Dnx.Compilation.IProjectCompiler'

### ISSUE THREAD

**Issue by nojaf** [aspnet/dnx#3236]
Hi,

I'm trying to fix the FSharp support for DNX from the fsharp-dnx repo. 
https://github.com/fsprojects/fsharp-dnx/issues/18

I was able to get the DNX compile project building again but when referenced in another F# project it doesn't compile

The error I get:
```
Error: Unable to cast object of type 'FSharp.Dnx.FSharpProjectCompiler' to type 'Microsoft.Dnx.Compilation.IProjectCompiler'.
```

My compiler class
```csharp
using System;
using System.Collections.Generic;
using Microsoft.Extensions.CompilationAbstractions;
using Microsoft.Extensions.CompilationAbstractions.Caching;
using Microsoft.Extensions.PlatformAbstractions;

namespace FSharp.Dnx
{
  public class FSharpProjectCompiler : IProjectCompiler
  {
    readonly FSharpCompiler _compiler;

    public FSharpProjectCompiler(
      ICache cache,
      ICacheContextAccessor cacheContextAccessor,
      INamedCacheDependencyProvider namedCacheProvider,
      IApplicationEnvironment environment,
      IServiceProvider services)
    {
      _compiler = new FSharpCompiler(
        cache,
        cacheContextAccessor,
        namedCacheProvider,
        environment,
        services);
    }

      public IMetadataProjectReference CompileProject(CompilationProjectContext projectContext, Func<LibraryExport> referenceResolver,
          Func<IList<ResourceDescriptor>> resourcesResolver, string configuration)
      {
            var export = referenceResolver();
            if (export == null)
            {
                return null;
            }

            var incomingReferences = export.MetadataReferences;
            var incomingSourceReferences = export.SourceReferences;

            var compilationContext = _compiler.CompileProject(
              projectContext,
              incomingReferences,
              incomingSourceReferences,
              resourcesResolver);

            if (compilationContext == null)
            {
                return null;
            }

            // Project reference
            return new FSharpProjectReference(compilationContext);
        }
  }
}
```

The ```IProjectCompiler``` is in the new ```Microsoft.Extensions ``` namespace. So I'm a bit puzzled why it is expecting to be a ```Microsoft.Dnx.Compilation.IProjectCompiler``` type.

The project json of the F# project:
```json
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "FSharp.Dnx": { "type": "build", "version": "" },
    "Microsoft.AspNet.Testing": "1.0.0-*",
"Microsoft.Framework.Runtime": "1.0.0-beta6",
    "xunit.runner.aspnet": "2.0.0-aspnet-*"
  },

  "commands": {
    "test": "xunit.runner.aspnet"
  },

  "frameworks": {
    "dnx451": { }
  },

  "compiler": {
    "name": "F#",
    "compilerAssembly": "FSharp.Dnx",
    "compilerType": "FSharp.Dnx.FSharpProjectCompiler"
  },
  
  "fsharp": {
    "files": [
      "test.fs"
    ]
  }
}

```

dnvm is 1.0.0-rc1-update1

Could somebody point me in the right direction?

Cheers,

nojaf

**Comment by davidfowl** [comment]
> "Microsoft.Framework.Runtime": "1.0.0-beta6",

The version of that has to match the runtime you're executing.

**Comment by Alxandr** [comment]
Yeah. This is definitely a version mismatch

**Comment by nojaf** [comment]
Ok, not sure how to proceed to be honest. How would I know which runtime I'm executing?
Is it the thing in my dnvm or not?
If so why is there no 1.0.0 rc 1  packages of ```Microsoft.Framework.Runtime``` on https://www.nuget.org/packages/Microsoft.Framework.Runtime/

**Comment by Alxandr** [comment]
@nojaf First of all. The F# master branch is intended to run against the dev branches of DNX (and libraries), which is not hosted on nuget but on myget. You install this using `dnvm upgrade -u` (`-u` for unstable). Second, dnvm version does not really matter (as long as it's new enough to get the newest DNX), however DNX version does matter. To see which DNX versions you have installed do `dnvm list`, and to see the current selected DNX version in use do `dnx --version`. It should read something like `1.0.0-rc2-16258` (or greater). Also, if you'd like, I can be available on IM to answer questions regarding both DNX and the dnx-fsharp library.

If your goal is just to use F# in DNX though, you can. It's not broken. Just download it from nuget, and make sure you're using RC1 packages. This should all work without any problems. It's only the latest "nightly" DNX stuff that doesn't work with F# at the moment.

**Comment by nojaf** [comment]
Hi @Alxandr, thanks for the info.
I'll look at my dnx version when I can, if I have follow-up questions I'll reach out on IM.
My goal is indeed to use F# in DNX.

**Comment by xperiandri** [comment]
Cloned https://github.com/fsprojects/fsharp-dnx
Updated to "FSharp.Compiler.Service": "2.0.0.2"
Have the same error
Don't understand how to fix

**Comment by Alxandr** [comment]
@xperiandri This discussion should probably be on that repo, and not here. But nontheless, CI still builds `fsharp-dnx` just fine (https://ci.appveyor.com/project/Alxandr/fsharp-dnx). This issue might be caused by the new `FSharp.Compiler.Service` if that's the change you did.

**Comment by xperiandri** [comment]
It actually works with RC2. I had to reload solution after `dnvm upgrade -u`
