### ISSUE TITLE
dnu restore picks up packages not in NuGet.config

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3238]
Packages under .dnx\packages aren't marked with the NuGet feed they came from this leads to some problematic scenarios:
- Work on project A, which has aspnetvnext in its NuGet.config. Restoring some package X downloads the latest unstable rc2 into my .dnx\packages
- Switch to project B, which is stable and only has nuget.org in its NuGet.config. Doing `dnu restore` will now pick up the unstable rc2 of package X from .dnx\packages.

What seems to be needed is some sort of trace inside .dnx\packages which allows `dnu restore` to skip a version if it came from a feed which isn't listed for the currently-building project...

**Comment by davidfowl** [comment]
Are you using -*? If yes then all bets are off. The best way to shield yourself from other repositories when using floating versions is to use a per repository packages folder. You can edit global.json and set a relative path to packages. 

> What seems to be needed is some sort of trace inside .dnx\packages which allows dnu restore to skip a version if it came from a feed which isn't listed for the currently-building project...

We could choose to ignore the local disk when restoring -* versions and instead only used configured feeds (instead of trying to keep track of where things came from).

**Comment by roji** [comment]
I'm indeed using -* (I guess otherwise this problem can't occur in the first place).

Specifying a package path in global.json is definitely a workaround, although it's less than ideal in a single project where sometimes you need to switch between stable and unstable branches - you need to switch back and forth both your NuGet.config and your global.json.

Wouldn't ignoring the local disk for -* make things very slow for no good reason? I mean, dropping a simple metadata file inside the package's directory under .dnx\packages seems pretty simple, you could even include other information such as download date just for fun.
