### ISSUE TITLE
P/Invoking a method that throws a .net exception from within a natively invoked callback crashes the running application with SIGABRT on Linux

### ISSUE THREAD

**Issue by jumpinjackie** [aspnet/dnx#3239]
Preface: I'm not sure if this is a DNX or a CoreCLR issue, so re-assign as required.

I'm currently looking at porting the .net API for [MapGuide](http://mapguide.osgeo.org/) over to run on ASP.net 5/CoreCLR in a cross-platform scenario

The code itself is in C++, but we use [SWIG](http://swig.org/) to generate a .net interop layer around our C++ code. I've been able to get this interop layer to work for the CoreCLR in both Windows and Linux, but I've hit a show-stopping snag with regards to exceptions.

Our MapGuide API can throw exceptions in various places, and SWIG will generates code such that when such exceptions are thrown on the native side they are caught, the essential information in the exception extracted and passed back into a callback on the .net side where an equivalent .net exception proxy class is created with the captured information and thrown from there.

While this works fine on Windows (any exception in the native code of the MapGuide API is caught, processed and rethrown as a .net exception), on Linux (Ubuntu 14.04 64-bit with the CoreCLR 1.0.0 rc1-update1 binaries) it crashes the running application with SIGABRT on the (rethrow on .net side) step.

While posting the SWIG-generated code and .net proxies is a bit too complex to deconstruct (we are wrapping several hundred C++ classes!), I have been able to somewhat distill the problem down to an easy simple and reproducible test application that's available in the link below.

https://github.com/jumpinjackie/coreclr-pinvoke-crash-repro

Is what is illustrated in the above link a supported scenario?

**Comment by davidfowl** [comment]
This belongs on dotnet/coreclr

**Comment by jumpinjackie** [comment]
Moved to: https://github.com/dotnet/coreclr/issues/2263
