### ISSUE TITLE
DNX doesn't seem to handle the SIGTERM signal on Linux

### ISSUE THREAD

**Issue by Flavien** [aspnet/dnx#3241]
DNX should wind down and gracefully exit upon receiving a SIGTERM signal on Linux. It seems it is not currently the case.

A simple use case for this: The ``docker stop`` command sends a SIGTERM to the process in the container. Dockerized DNX apps can't gracefully shut down.

**Comment by Tragetaschen** [comment]
That policy is too specific DNX (think "cleanup"). The Hosting infrastructure would be the right place and there, SIGINT is used graceful shutdown. In addition, you can always register a signal handler that ‘IApplicationLifetime‘.

**Comment by Flavien** [comment]
How do you register a signal handler?

**Comment by Tragetaschen** [comment]
I do it with Mono.Posix against the full framework profile. On Core, I don't know, Posix signal handlers have a couple of restrictions.

**Comment by davidfowl** [comment]
@Flavien File this bug on aspnet/Hosting.
