### ISSUE TITLE
Reloading an application in process

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/dnx#3243]
For tools that modify project files like appsettings.json / project.json etc, is there a way to reload the application in process? 

For instance, Scaffolding needs to install dependencies before it can generate code. In this case since the dnx gen command is already loads the project, the new dependencies do not get reflected in the process.

**Comment by victorhurdugaci** [comment]
There's no way to do that. Can you spin off a new process? That's what `dnx-watch` does
