### ISSUE TITLE
Is there a repository for Microsoft.Framework.CommandLineUtils.Sources?

### ISSUE THREAD

**Issue by reliak** [aspnet/dnx#3246]
Is there a git repository for Microsoft.Framework.CommandLineUtils.Sources?
Because I'm using the latest version (https://www.nuget.org/packages/Microsoft.Framework.CommandLineUtils.Sources/) and I think I found a bug in the handling of commandline arguments.

**Comment by muratg** [comment]
@davidfowl To Common repo, or create a new repo for this (cc @Eilon)?

**Comment by Eilon** [comment]
Common seems fine to me for now.

**Comment by victorhurdugaci** [comment]
Do we plan to replace this with `System.CommandLine`?

**Comment by Eilon** [comment]
@victorhurdugaci can you compare & contrast those and we can discuss?

**Comment by Eilon** [comment]
(Not necessarily in this bug, but we can discuss offline.)

**Comment by BrennanConroy** [comment]
The command line utils package has moved to https://github.com/aspnet/Common/src/Microsoft.Extensions.CommandLineUtils
Also it is now an actual package and no longer a source package.

**Comment by shanselman** [comment]
Where is this code **now**?

**Comment by pranavkm** [comment]
@shanselman like @BrennanConroy pointed out, it's at https://github.com/aspnet/Common/tree/dev/src/Microsoft.Extensions.CommandLineUtils. We also have a package available on nuget.org: 
https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils/

**Comment by babelshift** [comment]
@pranavkm, as of today, there's nothing interesting at the github link you've provided. Has the source moved?

**Comment by davidfowl** [comment]
https://github.com/aspnet/Common/tree/dev/src/Microsoft.Extensions.CommandLineUtils

**Comment by babelshift** [comment]
@davidfowl There's nothing there. Everything was removed in a commit last December.

**Comment by babelshift** [comment]
Looks like it's actually here now?

https://github.com/aspnet/Common/tree/dev/shared/Microsoft.Extensions.CommandLineUtils.Sources/CommandLine

**Comment by Eilon** [comment]
@babelshift there are two versions of the command line utils package: one is an actual library that you reference, and the other (the `.Sources` one), has the same code, but it's a "sources package", which means that the code gets included and compiled into *your* library as internal APIs. Both contain the exact same functionality.

**Comment by fredrikhr** [comment]
@Eilon iirc it was a source package back in the old DNX days, but then it was changed to a usual library package... Any idea why it is a Source Package again? And why it is moving around so much? It is really hard to find, and therefore also hard to create issues and submit PRs!

**Comment by Eilon** [comment]
@couven92 - we didn't want to own a "public" command line parser - that's not the focus of ASP.NET/EF Core. So instead we have a .Sources package that is internal.
