### ISSUE TITLE
Question: Why CompilationServices.Default.LibraryExporter is null?

### ISSUE THREAD

**Issue by GeroL** [aspnet/dnx#3248]
Hi,

there is no LibraryExporter defined in WebApplication. DefaultHost does register them.
I try to use the code form DefaultHost but I always run into EntryPointNotFoundException when I use LibraryExporter.GetExports() or even MethodNotFoundException

Maybe it has something to do with: #2984

Background:
I need to pass MetadataReferences from Packages to OrleansClient from Asp.Net WebApplication.
This is because Orleans does not include Assemblies without Location because the Roslyn Compiler needs physical Assembly Files for loading Metadata.
This works now with a DNX Console App but not in a WebApp.

Thats the Code I use to setup the Compiler:

```csharp
    public class CompilerSetup
    {
        private static readonly string RuntimeAbstractionsPackageName =
            typeof(IRuntimeEnvironment).GetTypeInfo().Assembly.GetName().Name;

        private readonly LibraryManager _libMgr;

        public CompilerSetup(IApplicationEnvironment env)
        {
            var mgr = PlatformServices.Default.LibraryManager;

            //Steal the LibMgr for GetLibraryDescriptions()
            var field = mgr.GetType().GetField("_libraryManager", BindingFlags.Instance | BindingFlags.NonPublic);
            var val = field.GetValue(mgr) as Lazy<LibraryManager>;

            _libMgr = val.Value;
        }

        public void Init(IServiceCollection collection)
        {
            Initialize(collection);
        }

        private void Initialize(IServiceCollection collection)
        {
            var libraries = _libMgr.GetLibraryDescriptions().ToList();
            
            var projectDesc = libraries.OfType<ProjectDescription>().FirstOrDefault();

            var hostEnvironment = PlatformServices.Default.Application;

            var compilationContext = new CompilationEngineContext(
                hostEnvironment,
                PlatformServices.Default.Runtime,
                PlatformServices.Default.AssemblyLoadContextAccessor.Default,
                new CompilationCache());

            var compilationEngine = new CompilationEngine(compilationContext);
            
            var runtimeLibraryExporter = new LibraryExporter(_libMgr, compilationEngine, "Debug");
            collection.AddSingleton(runtimeLibraryExporter);

            // TODO: Dedupe this logic in the RuntimeLoadContext
            var projects = libraries.Where(p => p.Type == LibraryTypes.Project)
                                    .ToDictionary(p => p.Identity.Name, p => (ProjectDescription)p);

            var compilerOptionsProvider = new CompilerOptionsProvider(projects);

            collection.Add(new ServiceDescriptor(typeof(ICompilerOptionsProvider), compilerOptionsProvider));

            CompilationServices.SetDefault(
                    CompilationServices.Create(
                            libraryExporter: runtimeLibraryExporter,
                            compilerOptionsProvider: compilerOptionsProvider
                        )
                );
        }
```
OffTopic:
Thats the Code I use to pass MetadataReferences to Orleans (Modified Version):

```csharp
       public void InitOrleansTypes()
        {
            libExporter = CompilationServices.Default.LibraryExporter;

            var listCollection = new List<Assembly>(AppDomain.CurrentDomain.GetAssemblies().Where(x=> x.IsDynamic == false));

            var ownLibs = PlatformServices.Default.LibraryManager.GetLibraries()
                .Where(x => x.Name.StartsWith("OwnProject") && x.Name.Contains("Interface") && x.Assemblies.Any(z => listCollection.Any(y => y.FullName.Split(',')[0] == z.Name)))
                .SelectMany(x => x.Assemblies)
                .Distinct()
                .ToList();
            
            ownLibs .ForEach(x => listCollection.Add(Assembly.Load(x)));

            var exports = ownLibs .SelectMany(x => libExporter.GetAllExports(x.Name).MetadataReferences).GroupBy(x => x.Name).Select(x => x.First());

            var references = new List<IMetadataReference>();
            references.AddRange(exports);


            //in memory dlls coming from compiled projects

            var oldReferences = new List<MetadataReference>();

            foreach (var reference in references)
            {
                var rosRef = reference as IMetadataProjectReference;
                if (rosRef != null)
                {
                    var ms = new MemoryStream();
                    rosRef.EmitReferenceAssembly(ms);
                    if (ms.Length > 0)
                    {
                        ms.Seek(0, SeekOrigin.Begin);
                        oldReferences.Add(MetadataReference.CreateFromStream(ms));
                    }
                }
            }

            var generator = Orleans.CodeGeneration.CodeGeneratorManager.CodeGeneratorInstance.Value as Orleans.CodeGenerator.RoslynCodeGenerator;
            generator.AdditionalReferences = oldReferences;
        }
```

**Comment by davidfowl** [comment]
I need more context. What are you doing exactly? CodeGen? Runtime compilation?

**Comment by GeroL** [comment]
Orleans generates and compiles code at runtime. For detecting references to this code it uses AppDomain.Current.GetAssemblies() and filters out every Assembly without Location because Roslyn loads the Metadata from physical or in-memory files only.

Unfortunatlely I need these dnx assemblies without location as references. 
So I get the metadata using the ILibraryExporter. Call EmitReferenceAssembly() and write the assembly into a MemoryStream and load the MetadataReference for Roslyn. I pass them as explicit to use references to orleans.

That works on the host side with DNX ConsoleApp where I have CompilerServices.Default.LibraryExporter 
but in the WebApplication this CompilationServices are not set. So I try to setup one with the code listed above but it just does not work.

MVC builder also just uses CompilationServices.Default.LibraryExporter (which is not set):
https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNet.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L123 

What I need is one of the following 3 possibilities:

* The physical file path of the dnx assembly (Location)
* The metada from that assembly
* Functional LibraryExporter like in the console app. (The DefaultHost class creates one)

There is a sample in the orleans repo showing a asp.net client.

**Comment by davidfowl** [comment]
Are you using RC1? OR Post RC1 bits? For RC1 you should be able to use the ILibraryExporter as Razor is doing today. See https://github.com/aspnet/Mvc/blob/6.0.0-rc1/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs.

Post RC1 we're going to be moving away from this interface, see:

- https://github.com/aspnet/Mvc/issues/3633
- https://github.com/dotnet/cli/issues/392
- https://github.com/dotnet/cli/issues/376

PS: Using `AppDomain.CurrentDomain.GetAssemblies()` is wrong anyways as it'll miss assemblies that aren't loaded yet. It's also not right to use the runtime assemblies for compilation. You'll get different results (but maybe you don't care?)

**Comment by GeroL** [comment]
I use nightly builds for the web part. The console app uses RC1
After reading the links you provided it seems to me that there is a huge construction site. Did not expect that from a RC2. 
I can't just switch back to RC1 because there are other issues then. I will have to create some sort of proxy.

Thanks for your help and the infos!

**Comment by XVincentX** [comment]
@davidfowl Is this solution actually working with `rc1-update1`?

**Comment by davidfowl** [comment]
@XVincentX What solution?

**Comment by XVincentX** [comment]
@davidfowl 
Let me reformulate the question: does `rc1-update1` belong to `postRc1` bits? In other words, can I inject `ILibraryExporter` into my Console application?

**Comment by davidfowl** [comment]
> Let me reformulate the question: does rc1-update1 belong to postRc1 bits? 

Nope.

> In other words, can I inject ILibraryExporter into my Console application?

No you can't. Use the static. Post RC1 means RC2 where more things are changing.

**Comment by XVincentX** [comment]
@dagood 

I can't, it's null
`Microsoft.Dnx.Compilation.CompilationServices.Default.LibraryExporter` is null.

Am I missing something?

**Comment by XVincentX** [comment]
@davidfowl Sorry to ping you again, but I still do not understand how to move.

**Comment by davidfowl** [comment]
You're using the wrong type. The type is `Microsoft.Extensions.CompilationAbstractions.Default. LibraryExporter` *not* `Microsoft.Dnx.Compilation.CompilationServices.Default.LibraryExporter`

**Comment by XVincentX** [comment]
In which assembly is it included?

**Comment by davidfowl** [comment]
You're using RC2 right? None of the RC2 packages are on nuget.org

**Comment by XVincentX** [comment]
@davidfowl 
Where do I find them then?

**Comment by davidfowl** [comment]
@Xiaohongt have you been using RC2 all this time or something else? I'm trying to figure out what you are currently doing...

**Comment by XVincentX** [comment]
I still do not get what should I do here :-1:

**Comment by davidfowl** [comment]
I dunno if you're using RC2

**Comment by XVincentX** [comment]
Amazing.

**Comment by davidfowl** [comment]
Did you figure it out?

**Comment by XVincentX** [comment]
Unfortunately not, and I have no idea how to proceed unless waiting for a newer release.

**Comment by davidfowl** [comment]
I wrote this before but I'll write it again:

You're using the wrong type. The type is Microsoft.Extensions.CompilationAbstractions.Default. LibraryExporter not Microsoft.Dnx.Compilation.CompilationServices.Default.LibraryExporter

If you're still having a hard time making it work. Put a repro project on github and I'll send a PR to fix it.

**Comment by XVincentX** [comment]
@davidfowl 

Thanks! Current state of the things is here: https://github.com/XVincentX/dredd-hooks-dotnet

**Comment by davidfowl** [comment]
@Xiaohongt your project has no global.json, what DNX version are you using?

**Comment by XVincentX** [comment]
@davidfowl I guess you're referring to me (**XVincentX**)...so

```bash

$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc2-16357      coreclr x64          darwin          
  *    1.0.0-rc2-16357      mono                 linux/osx       default
```

**Comment by davidfowl** [comment]
@Xiaohongt Why aren't you using rc1-update1?

**Comment by XVincentX** [comment]
Because if I understand that correctly, that code is not going to work anymore in following versions, right?

**Comment by davidfowl** [comment]
I don't see why it wouldn't. The reason you're getting a null reference is because you have a mismatch between this: https://github.com/XVincentX/dredd-hooks-dotnet/blob/master/project.json#L35 and the DNX you're running. They need to match. Downgrade your dnx to update1-rc1 and it'll start working again.

**Comment by XVincentX** [comment]
@davidfowl Didn't you stated it here?  https://github.com/aspnet/dnx/issues/3248#issuecomment-164276955

**Comment by davidfowl** [comment]
I asked which bits you were using. The correct answer would have been RC1. I'd recommend staying away for this kinda of stuff because things are still changing. Downgrade your application to the RC1 dnx and it will work.

You're not doing anything RC2 specific so that's your easy solution.

**Comment by XVincentX** [comment]
Thanks! Using rc1 and `Microsoft.Dnx.Compilation.CompilationServices.Default.LibraryExporter` made it work. Looks like I can finally going forward wit this.
