### ISSUE TITLE
DNU wrap uses version 1.0.0-* for all assemblies when csproj is already using a project.json

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/dnx#3251]
I have  a project that I'm upgrading from WebApi 2.2 to ASP.NET 5. There are a few csproj projects that should migrate with no problem - nothing ASP.NET specific in them. I have been using project.json in those projects already instead of packages.config. When I tried to reference the project from the ASP.NET 5 project in VS, it created some "wrapped" project files and amended the already existing project.json. A couple of issues with this:
1. It caused duplication of "dependencies" that appears to be tracked by #2554
2. All of the versions are shown as "1.0.0-*" instead of the specific version.

Example:

Original:

``` json
{
  "dependencies": {
    "Microsoft.Fx.Portability": "1.2.2-alpha-00034"
  },
  "frameworks": {
    "net45": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

Auto-generated wrap:

```
{
  "dependencies": {
        "Microsoft.Fx.Portability": "1.2.2-alpha-00034"
  },
  "frameworks": {
    "net45": {
      "wrappedProject": "Microsoft.Fx.Portability.Service.Common.csproj",
      "bin": {
        "assembly": "obj/{configuration}/Microsoft.Fx.Portability.Service.Common.dll",
        "pdb": "obj/{configuration}/Microsoft.Fx.Portability.Service.Common.pdb"
      },
      "dependencies": {
        "Microsoft.Fx.Portability": "1.0.0-*",
        "Newtonsoft.Json": "1.0.0-*"
      }
    }
  },
  "runtimes": {
    "win": { }
  },
  "version": "1.0.0-*"
}
```

Fixed:

```
{
  "dependencies": {
  },
  "frameworks": {
    "net45": {
      "wrappedProject": "Microsoft.Fx.Portability.Service.Common.csproj",
      "bin": {
        "assembly": "obj/{configuration}/Microsoft.Fx.Portability.Service.Common.dll",
        "pdb": "obj/{configuration}/Microsoft.Fx.Portability.Service.Common.pdb"
      },
      "dependencies": {
        "Microsoft.Fx.Portability": "1.2.2-alpha-00034",
        "Newtonsoft.Json": "6.0.8"
      }
    }
  },
  "runtimes": {
    "win": { }
  },
  "version": "1.0.0-*"
}
```

Once I fixed the versions, things started working. I also had to go into the the "wrap" directory and fix those versions.

**Comment by twsouthwick** [comment]
This is blocking us from using ASP.NET 5 - is this not a supported scenario?

**Comment by davidfowl** [comment]
This is super broken and will be fixed in rc2. For now you can manually edit the project.json file in the wrap folder.
