### ISSUE TITLE
Color codes are emitted even if stdout isn't a terminal

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3261]
When doing `dnu build | less`, color codes such as `ESC[33m` seem to be outputted. The Unix/Linux standard is to check whether your output is a terminal and to suppress color codes if not (at the C level this is done with [isatty](http://linux.die.net/man/3/isatty)).

```
Microsoft .NET Development Utility Mono-x64-1.0.0-rc1-16231


Building EF7Test for ESC[1mESC[33mDNX,Version=v4.5.1ESC[39mESC[22m
  Using Project dependency EF7Test 1.0.0
    Source: ESC[1m/home/roji/projects/EF7Test/project.jsonESC[22m
```

**Comment by khellang** [comment]
This should've been fixed with https://github.com/dotnet/corefx/pull/1886 and/or https://github.com/dotnet/corefx/pull/3885, no?

`dnu` might be writing some escape codes separately, though.

**Comment by muratg** [comment]
Yup, this would be throwaway work as we're moving away from dnx/dnu to dotnet CLI in RC2.  

Closing this one.
