### ISSUE TITLE
RC1 update1 works very slow on Linux/Mono

### ISSUE THREAD

**Issue by yaapelsinko** [aspnet/dnx#3263]
I've ran into the issue with my application, so to test if it is the app or something else I've created a template ASP.NET 5 app (web app template, not empty). It targeted solely to dnx451 framework and is built under Linux/Mono without any warnings.

To host it I have a Linux setup with nginx passing requests from external IP to internal application. When I'm accessing it, the app is responding very slow, like tens of seconds. Actually, it almost always close to 60 seconds. However, in application output log I see it processes requests pretty quick, like building a page in 0.6 sec (well not a lightspeed) and then passing linked resources (css, jpg) in under 0.001 second.

(strange - page is rendering in about 0.6, and loading in about 60, then file served in 0.003, but loaded in 0.3, i.e. always about 100x longer that it recorded in app log)  

However, it often ends in nginx returning 504. Sometimes page is loading only partially. Sometimes load is complete, but too much time it takes.

When 504, it is just 504 in nginx log. Like it wasn't nginx fault, but the application not responded. At the same time, in app log there can be a record about the action method Index() was fired and then the log just ends.

Could it be a Kestrel issue? App log shows considerable response time, but nginx sometimes show that app not responded at all. Also, time between log records (like the one about view rendering in 0.6 sec and the following records about resource passing in 0.0003 sec) can be about several seconds. So maybe the problem is in the middle layer?

What else, apart of reading logs, can I do to diagnose it?

Once I did the same setup, but with ASP.NET 5 beta8 (and, well, maybe actual versions of mono/libuv/etc were a bit different), and it worked well. But not this time. :/

**Comment by davidfowl** [comment]
File this issue on aspnet/Home. This has nothing to do with DNX.

**Comment by khellang** [comment]
@davidfowl https://github-issue-mover.appspot.com/? :stuck_out_tongue_closed_eyes:

**Comment by yaapelsinko** [comment]
I'll move it to aspnet/Home, this is closed then.
