### ISSUE TITLE
dnu pack --configuration Release isn't used by wrapped projects

### ISSUE THREAD

**Issue by BrianVallelunga** [aspnet/dnx#3265]
I have an ASP.NET 5 site that references a wrapped .NET 4.5 project. When calling `dnu pack --configuration Release` on the site's directory I get an error that the following file can't be found:

`"../../source/Widgets.Core/obj/Debug/Widgets.Core.dll"`

Note the **Debug** in the path instead of **Release**. The wrapped Widgets.Core project.json shows the `{configuration}` placeholder:

```
{
    "version": "1.0.0-*",
    "frameworks": {
        "net45": {
        "wrappedProject": "../../source/Widgets.Core/Widgets.Core.csproj",
        "bin": {
            "assembly": "../../source/Widgets.Core/obj/{configuration}/Widgets.Core.dll",
            "pdb": "../../source/Widgets.Core/obj/{configuration}/Widgets.Core.pdb"
        },
        "dependencies": {
        }
    }
}
```

What's even more strange is if I call `dnu pack --configuration TEST`, it checks the following path: `"../../source/Widgets.Core/obj/TEST/Widgets.Core.dll"`

Is there any way to work around this right now? It seems like this might be related to https://github.com/aspnet/dnx/issues/1501

**Comment by muratg** [comment]
`dnu pack` functionality is being moved to `dotnet cli` in RC2.  No more change is planned for DNU.
