### ISSUE TITLE
RoslynCompiler missing AfterCompile calls

### ISSUE THREAD

**Issue by jonathanburrows** [aspnet/dnx#3266]
To whom it may concern,

While attempting to use ICompileModule to do some post build checks, I found that it was never called. I set up a class which implemented ICompileModule:
![image](https://cloud.githubusercontent.com/assets/8765635/11860154/77c122c0-a426-11e5-8a9e-222189667c6d.png)
then, set up a class which implemented it in a compiler/preprocess folder of a seperate project:
![image](https://cloud.githubusercontent.com/assets/8765635/11860168/bf36dac8-a426-11e5-96e7-e4fd80189995.png)
While the breakpoints on BeforeCompile worked great, the AfterCompile ones didnt. Curiously, all your tests for ICompileModule had no AfterCompile tests. So, after looking at your source code for RosylnCompiler, it appears it was never added. 
https://github.com/aspnet/dnx/blob/7ac7929aa575e17b3c271e4a7a0c164418de0395/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs

If you refer to line 170 in the method CompileProject, it has a call to BeforeCompile. Awesome! Then, it has nothing for AfterCompile. Many sads. 

May I propose that either:
1) RoslynCompiler's CompileProject have AfterCompile added in a similar manner as BeforeCompile
2) ICompileModule have the AfterCompile method removed

Sincerely,
Jonathan R. Burrows

**Comment by davidfowl** [comment]
After compile gets called here https://github.com/aspnet/dnx/blob/7ac7929aa575e17b3c271e4a7a0c164418de0395/src/Microsoft.Dnx.Compilation.CSharp/RoslynProjectReference.cs#L112

**Comment by muratg** [comment]
In RC2, dnx is being retired. All compilation will be done through Roslyn and our abstractions will be retired.
