### ISSUE TITLE
dnu publish includes extra files that it used not to

### ISSUE THREAD

**Issue by opletayev** [aspnet/dnx#3269]
We upgraded a project from beta 5 (it was stable enough for us to keep development going) to RC1 a couple days back. We immediately noticed that our published folders ballooned up in size due to different versions of libraries and .pdb files being now included in the build.

I just reproduced in a new project this morning:

1) Created new console project using RC1 template in Visual Studio
2) Added a couple dependencies 3rd party dependencies

  "dependencies": {
    "AWSSDK": "2.3.46",
    "Dapper": "1.42.0"
  }

3) Ran publish:

dnu publish --out c:\temp\publish\rc1 --no-source

4) The folder size is over 100M due to all extra files being included:

Directory of C:\Temp\publish\rc1\approot\packages\AWSSDK\2.3.46\lib

2/18/2015  09:03 AM    <DIR>          .
2/18/2015  09:03 AM    <DIR>          ..
2/18/2015  09:03 AM    <DIR>          net35
2/18/2015  09:03 AM    <DIR>          net45
2/18/2015  09:03 AM    <DIR>          portable-wpa+netcore45
2/18/2015  09:03 AM    <DIR>          windows8
2/18/2015  09:03 AM    <DIR>          windowsphone8

Beta 5 build only included net45, and only AWSSDK.dll, but RC1 build includes both AWSSDK.dll and AWSSDK.pdb for each version. For instance,

 Directory of C:\Temp\publish\rc1\approot\packages\AWSSDK\2.3.46\lib\net45

12/18/2015  09:03 AM    <DIR>          .
12/18/2015  09:03 AM    <DIR>          ..
12/16/2015  05:05 PM         7,609,856 AWSSDK.dll
12/16/2015  05:05 PM        39,863,808 AWSSDK.pdb

To illustrate that it's not AWSSDK issue, I also included Dapper:

 Directory of C:\Temp\publish\rc1\approot\packages\Dapper\1.42.0\lib

12/18/2015  09:03 AM    <DIR>          .
12/18/2015  09:03 AM    <DIR>          ..
12/18/2015  09:09 AM    <DIR>          net35
12/18/2015  09:09 AM    <DIR>          net40
12/18/2015  09:09 AM    <DIR>          net45

As you can see, same issue here. PDB files are also in there.

We tried pretty much everything we could think of and any guidance on this would be greatly appreciated.

**Comment by muratg** [comment]
`dnu publish` is being moved to dotnet CLI in RC2.

**Comment by opletayev** [comment]
Thanks for the note. For now, we patched our build scripts to manually delete some of the extra files, but I hope that future versions will resolve this issue.

**Comment by muratg** [comment]
@opletayev You're welcome. Please feel free to watch dotnet/cli repo, and try out the `dotnet publish` command to see if it has the same problem or not.
