### ISSUE TITLE
"dnu restore" screws up "private" dependencies in published projects.

### ISSUE THREAD

**Issue by fsoikin** [aspnet/dnx#3273]
By "private" dependencies I mean packages that I have manually copied into local `/packages` folder in my project, because there is no NuGet feed for them.

When I have such "private" dependencies, and I `dnu publish` the project that uses them, and then try to `dnu restore` on that published project, `dnu restore` will not only complain about those dependencies not being available, but actually spoil the project, so that the "private" dependencies won't load anymore.

Where I may have made a mistake:
* Perhaps I am not supposed to have such "private" packages in the first place. In that case, how do I do this? In the old `*proj` files, I could just put them somewhere like `/lib` and then do `<Reference Include="MyLib"><HintPath>../lib/MyLib.dll</HintPath></Reference>`. But how do I do this with `project.json`?
* Perhaps I'm not supposed to run `dnu restore` on published packages? But in this case, why the hell does it not refuse to run? Also, unfortunately, I have to do it sometimes, because it is the only workaround for issue #3272.

## Detailed repro:
First, we need a setup identical to that from [issue #2429 in coreclr](https://github.com/dotnet/coreclr/issues/2429) - follow the steps up until, and including, "Publish project B".

After this, I have project B published in `C:\work\CentOS\b`, and project A under `C:\work\CentOS\b\approot\packages\a`. I can now verify that project B runs:

```
C:\work\CentOS\b\approot> .\b.cmd
A.C    <-- correct output
```

### Do "dnu restore"
```
C:\work\CentOS\b\approot> dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\work\CentOS\b\approot\packages\a\1.2.3\root\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='a'
Unable to locate Dependency a >= 1.2.3
Writing lock file C:\work\CentOS\b\approot\packages\a\1.2.3\root\project.lock.json
Restore complete, 174ms elapsed
Restoring packages for C:\work\CentOS\b\approot\packages\b\1.0.0\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime/4.0.20
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Private.Uri'
  CACHE https://www.nuget.org/api/v2/package/System.Private.Uri/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
  CACHE https://www.nuget.org/api/v2/package/System.Console/4.0.0-beta-23409
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
  CACHE https://www.nuget.org/api/v2/package/System.IO/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  CACHE https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  CACHE https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Console'
  CACHE https://www.nuget.org/api/v2/package/runtime.win7.System.Console/4.0.0-beta-23409
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.20
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
  CACHE https://www.nuget.org/api/v2/package/System.Reflection/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives'
  CACHE https://www.nuget.org/api/v2/package/System.Reflection.Primitives/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime.Handles/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager'
  CACHE https://www.nuget.org/api/v2/package/System.Resources.ResourceManager/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization'
  CACHE https://www.nuget.org/api/v2/package/System.Globalization/4.0.0
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives'
  CACHE https://www.nuget.org/api/v2/package/System.IO.FileSystem.Primitives/4.0.0
  CACHE https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10
  CACHE https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  CACHE https://www.nuget.org/api/v2/package/System.Threading/4.0.10
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  CACHE https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.10
Unable to locate Dependency a >= 1.2.3
Installing System.Runtime.4.0.20
Installing System.Private.Uri.4.0.0
Installing System.Console.4.0.0-beta-23409
Installing System.IO.4.0.0
Installing System.Text.Encoding.4.0.0
Installing System.Threading.Tasks.4.0.0
Installing runtime.win7.System.Console.4.0.0-beta-23409
Installing System.Runtime.InteropServices.4.0.20
Installing System.Reflection.4.0.0
Installing System.Reflection.Primitives.4.0.0
Installing System.Runtime.Handles.4.0.0
Installing System.Resources.ResourceManager.4.0.0
Installing System.Globalization.4.0.0
Installing System.IO.FileSystem.Primitives.4.0.0
Installing System.Threading.Tasks.4.0.10
Installing System.Text.Encoding.4.0.10
Installing System.Threading.4.0.10
Installing System.Text.Encoding.Extensions.4.0.10
Writing lock file C:\work\CentOS\b\approot\packages\b\1.0.0\app\project.lock.json
Restore complete, 1241ms elapsed
Restoring packages for C:\work\CentOS\b\approot\packages\b\1.0.0\root\project.json
Unable to locate Dependency a >= 1.2.3
Writing lock file C:\work\CentOS\b\approot\packages\b\1.0.0\root\project.lock.json
Restore complete, 60ms elapsed
Total time 1650ms

Errors in C:\work\CentOS\b\approot\packages\a\1.2.3\root\project.json
    Unable to locate Dependency a >= 1.2.3

Errors in C:\work\CentOS\b\approot\packages\b\1.0.0\app\project.json
    Unable to locate Dependency a >= 1.2.3

Errors in C:\work\CentOS\b\approot\packages\b\1.0.0\root\project.json
    Unable to locate Dependency a >= 1.2.3

NuGet Config files used:
    C:\Users\Fyodor\AppData\Roaming\NuGet\nuget.config

Feeds used:
    https://www.nuget.org/api/v2/

Installed:
    18 package(s) to C:\work\CentOS\b\approot\packages
```

### Despite the errors, try to run it anyway
```
C:\work\CentOS\b\approot> .\b.cmd
System.IO.FileNotFoundException: Could not load file or assembly 'a, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'a, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'a'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'a'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by davidfowl** [comment]
> By "private" dependencies I mean packages that I have manually copied into local /packages folder in my project, because there is no NuGet feed for them.

That's not supported. If you have a dependency that's not in a nuget package, put it in a nuget package and reference it from project.json. You should make a local nuget feed with the "private" packages and you should change your nuget.config to add it as a feed.

> Perhaps I'm not supposed to run dnu restore on published packages? But in this case, why the hell does it not refuse to run? Also, unfortunately, I have to do it sometimes, because it is the only workaround for issue #3272.

You're not supposed to run restore on the published output. You're supposed to run it on the `project.json`

**Comment by fsoikin** [comment]
> You should make a local nuget feed with the "private" packages and you should change your nuget.config to add it as a feed.

I assume you mean a repo-local `nuget.config` pointing to a repo-local folder with packages? Got it, works. Somehow didn't occur to me before.

> You're not supposed to run restore on the published output

This raises two questions:

1. If it's not supposed to be run like that, then why does it run like that? It even creates new `project.json` files in subfolders `a\1.2.3\root`, `b\1.0.0\app`, and `b\1.0.0\root` - this doesn't look like accidental functionality at all.
2. Unfortunately, due to #3272, I do have to `dnu restore`. At least for now. Just for the time being I have resorted to "publishing" by copying the whole source, but this is not acceptable long-term.

**Comment by davidfowl** [comment]
> If it's not supposed to be run like that, then why does it run like that? It even creates new project.json files in subfolders a\1.2.3\root, b\1.0.0\app, and b\1.0.0\root - this doesn't look like accidental functionality at all.

That's because the current model preserves the package hierarchy in the output folder. It merely copies the relevant data and files from the original projects and transforms the output.

> Unfortunately, due to #3272, I do have to dnu restore. At least for now. Just for the time being I have resorted to "publishing" by copying the whole source, but this is not acceptable long-term.

Still, that happens at development time. You can only publish what you have restored for...

**Comment by fsoikin** [comment]
Sooo.. I still don't see why `dnu restore` would write a `project.json` inside `packages/a/1.2.3/root` and others. When I do `dnu restore` on a non-published (i.e. source) project, it doesn't go into the `packages` folder.
