### ISSUE TITLE
DNX command line help does not show sub-commands

### ISSUE THREAD

**Issue by lmartinking** [aspnet/dnx#3274]
Running `dnx --help` does not show any information about sub commands (eg: `run`, `publish`).

```
lucas@lucas-mac ~/code/3rdparty/dnx (dev) $ dnx --help
Microsoft .NET Execution environment Mono-x64-1.0.0-rc1-16231

Usage: dnx [options]

Options:
  --project|-p <PATH>              Path to the project.json file or the application folder. Defaults to the current folder if not provided.
  --appbase <PATH>                 Application base directory path
  --lib <LIB_PATHS>                Paths used for library look-up
  --debug                          Waits for the debugger to attach before beginning execution.
  --framework <FRAMEWORK_ID>       Set the framework version to use when running (i.e. dnx451, dnx452, dnx46, ...)
  -?|-h|--help                     Show help information
  --version                        Show version information
  --watch                          Watch file changes
  --packages <PACKAGE_DIR>         Directory containing packages
  --configuration <CONFIGURATION>  The configuration to run under
  --port <PORT>                    The port to the compilation server
```

I think it would aid discoverability if the subcommands were displayed in this usage message.

Version output:
```
lucas@lucas-mac ~/code/3rdparty/dnx (dev) $ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

**Comment by davidfowl** [comment]
DNX has no subcommands. Run is a built in command that runs the program's main. Dnu has subcommands though.

**Comment by lmartinking** [comment]
Sorry, my terminology is taken from Python's `argparse` which I am more used to :-)

Would you mind mentioning the existance of `run`, `publish`, etc via `--help` ?

**Comment by davidfowl** [comment]
@lmartinking There's 2 different tools at play and you have them confused. DNX is the runtime like `python` and `DNU` is the tool chain (no first class equivalent in python that I'm aware of). DNU has publish, DNX does not. DNX can run things, DNU cannot. Type dnu and you'll see a list of subcommands. 

We could mention the existence of run for dnx but we're not making anymore changes as we're moving to a new toolchain post RC1

**Comment by lmartinking** [comment]
Ahhh that makes more sense now.

I was poking at OmniSharp in Atom on Mac today, so that led me down the path to here.

I'm very excited about `dotnet` on Mac & Linux -- keep up the good work!

**Comment by davidfowl** [comment]
Thanks!
