### ISSUE TITLE
Not recognizing RID on Ubuntu 14 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/dnx#3275]
Recent change https://github.com/aspnet/dnx/commit/2be312f5ff7e675140d68f74d42b753d593c7fef broke RID recognition on Ubuntu 14 (aka, our targeted linux distro for CI and docs). Restore does not include the proper "runtimes.*" packages => runtime failures.

cc @victorhurdugaci @anurse

**Comment by natemcmaster** [comment]
CI is failing: https://travis-ci.org/aspnet/EntityFramework/builds/97756973#L511

**Comment by natemcmaster** [comment]
cc @muratg

**Comment by muratg** [comment]
@BrennanConroy

**Comment by natemcmaster** [comment]
``GetRuntimeIdentifier()`` returns `"linux.ubuntu 14.04-x64"`

**Comment by BrennanConroy** [comment]
Closed via #3276
