### ISSUE TITLE
File system-based feed path from nuget.config is resolved relative to "current directory"

### ISSUE THREAD

**Issue by fsoikin** [aspnet/dnx#3279]
My goal is to reference "locally built" libraries from my project, but without including their source. In order to accomplish this, I make NuGet packages out of those libraries and put them in a local `./lib` folder in my project source tree. I then add a `nuget.config` that references this `./lib` folder. 

This works well, but only if I run `dnu restore` from the directory where `nuget.config` is located. Apparently `dnu restore` just uses the path verbatim, which means that the `./lib` won't be visible from any other directory.

From my experience with other similar tools, I would expect it to resolve the path as relative to `nuget.config`.
### Repro:

```
C:\i\a> ls

    Directory: C:\i\a

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/21/2015  11:48 PM                lib
d-----       12/21/2015  11:48 PM                src
-a----       12/21/2015  11:49 PM             26 global.json
-a----       12/21/2015  11:48 PM            156 nuget.config

C:\i\a> cat .\nuget.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local" value="./lib" />
  </packageSources>
</configuration>

C:\i\a> dnu restore

<snip>

NuGet Config files used:
    C:\Users\Fyodor\AppData\Roaming\NuGet\nuget.config
    C:\i\a\nuget.config

Feeds used:
    https://www.nuget.org/api/v2/
    ./lib

C:\i\a> cd src

C:\i\a\src> dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\i\a\src\project.json
Error: FindPackagesById: System.Runtime
  The local package source ./lib doesn't exist
----------

```

**Comment by conniey** [comment]
I was wondering if there was an ETA on when this issue would be fixed? 

We were working with a customer who had shared libraries in multiple solutions and it was painful to coordinate the right location to find all the locally built packages in the program. (There was code churn in multiple solutions, so we wanted to update the references easily to see the changes.)

At some point, we had a NuGet.config in every project referencing that local repository.. but that only worked if you restored packages by right-clicking on each project and not the solution. And eventually, had copies of the shared library (.xproj) in each solution referencing the same code so we didn't have to deal with it.

I feel like this is a scenario many other developers are going to face if they have their shared components in different solutions and want to work on features that touch different components.

**Comment by davidfowl** [comment]
DNX bugs are not being fixed at this point because it is being retired in favor of the .NET CLI for RC2 (which already supports this).
