### ISSUE TITLE
Installing updates to packages defined in project.json

### ISSUE THREAD

**Issue by jchannon** [aspnet/dnx#3280]
If there is a newer version of a package defined in project.json how do you get it? No-one seems to know....

**Comment by GuardRex** [comment]
@jchannon If you look at https://www.nuget.org/ you can find out manually. In VS, you can check out `Tools > NuGet Package Manager > Manage NuGet Packages for Solution ...`.

**Comment by jchannon** [comment]
So you're saying I use `dnu install Blah` but have to do `nuget update`? Good UX!

**Comment by GuardRex** [comment]
Yeah, I missed the point of your question. My bad.
