### ISSUE TITLE
dnu wrap: failed to resolve references

### ISSUE THREAD

**Issue by elmortega** [aspnet/dnx#3282]
I'm trying to reference a class library project (csproj target framework 4.5.1) from my aspnet50 app 

Adding the reference from visual studio won't do the wrapping, I don´t know why, so in the cmd prompt I ran the dnu wrap command from the solution folder where the global.asax is and i get: Failed to resolve references for C:\...\ClassLibrary.csproj

if I do this process for the assembly (.dll) and not the cproj file it works fine, but as i´m referencing a non aspnet50 I think the cproj way is the way to do it because the nuget dependencies of both project would conflict

I also tried to remove the window's environment variable Platform=BPC with no luck

my dnx 
clr 1.0.0-rc1-final (also upgraded to 1.0.0-rc1-update1, same result)

dnu version
1.0.0-rc1-16231

**Comment by muratg** [comment]
Dnx/dnvm/dnu are being retired in favor of dotnet CLI.
