### ISSUE TITLE
HttpStatusCodeResult return description along with code?

### ISSUE THREAD

**Issue by a11smiles** [aspnet/dnx#3283]
In .Net < 5, there was an overloaded constructor that allowed us to create an HttpStatusCodeResult with status code and a description.

Apparently, in .Net 5, I can no longer add a description?

Should we be using an alternative result type (i.e. ObjectResult or ContentResult)?

Please advise.

**Comment by davidfowl** [comment]
This is an MVC question ask on that repository.

**Comment by muratg** [comment]
This issue was moved to aspnet/Mvc#3820
