### ISSUE TITLE
'dnx web' command within vscode UI fails on whitespace in profile path

### ISSUE THREAD

**Issue by george-polevoy** [aspnet/dnx#3286]
### Title

'dnx web' command within vscode UI fails on whitespace in profile path.
### Functional impact

Uable to start aspnet website using ndx from vscode ui.
### Minimal repro steps

Having a space in the user profile path, such as:
C:\Users\George Polevoy\

Follow this tutorial to set up an aspnet webapi website:
The problem appears
https://code.visualstudio.com/Docs/runtimes/ASPnet5

At the stage explaning running the F1 command:
![image](https://cloud.githubusercontent.com/assets/2792885/12015246/b93041c8-ad4a-11e5-837c-37e81967b08d.png)

![image](https://cloud.githubusercontent.com/assets/2792885/12015259/e69d185c-ad4a-11e5-9a10-6b911095d7a4.png)
### Expected result

I'd expect the web site to be started, as i can do it with 'dnx web' command from powershell.
![image](https://cloud.githubusercontent.com/assets/2792885/12015271/132d90cc-ad4b-11e5-8717-059e5d5db23b.png)
### Actual result

I see a cmd window with following contents:
'C:\Users\George' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
### Further technical details

For debugging, i have run the following command (list of of the command lines used to start the currently running cmd processes):

``` powershell
Get-WmiObject Win32_Process | select CommandLine | sls cmd
```

Which yields the two related processes:

``` powershell
@{CommandLine=cmd.exe /c start /wait cmd.exe /c "C:\Users\George 
Polevoy\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe web & pause"}
@{CommandLine=cmd.exe  /c "C:\Users\George Polevoy\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe web & 
pause"}
```

Which reselmbles to the following command being executed:

``` cmd
cmd.exe /c start /wait cmd.exe /c "C:\Users\George Polevoy\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe" "web & pause"
```

I attempted a slightly modified version from powershell console (double-quoted path inside the inner command to dnx) and it seems to run fine:

``` cmd
cmd.exe /c start /wait cmd.exe /c """C:\Users\George Polevoy\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe"" web & pause"
```

The web service is spinning up and running then.

**Comment by muratg** [comment]
@george-polevoy Since we're retiring DNX/DNU/DNVM in RC2, I recommend testing this with dotnet CLI.  (See http://github.com/dotnet/cli)

**Comment by runxc1** [comment]
@muratg Does dotnetcli work with RC1 bits?

**Comment by muratg** [comment]
@runxc1 It might, although that's not a scenario we're currently testing.  For the current RC2 bits, @davidfowl has some samples with the CLI here: https://github.com/davidfowl/dotnetcli-aspnet5
