### ISSUE TITLE
paths to static files not found

### ISSUE THREAD

**Issue by DasJott** [aspnet/dnx#3287]
Neither the "content" path value in project.json nor any other local path is gettable from the browser.
No content files, such as css or js can be found and produce 404 errors in the console.

Shouldn't be the webroot value the root for the webpage?

**Comment by davidfowl** [comment]
Not sure I understand the question.

**Comment by muratg** [comment]
@DasJott What's the scenario that's failing? Are you trying to access some static files on disk?

**Comment by DasJott** [comment]
Exactly, @muratg .
I experiment with the HelloMVC project in Ubuntu 14.04 using VSCode.
There is a css file I created but the browser can't find. The developer console says 404 while trying to get the file. If I browse the path to the file directly I also get nothing.
It doesn't matter where I put the file within the projects folder, the DNX seems to not provide any folder structure.
In the project.json I have an entry "webroot" which points to "wwwroot" in the root of the project. I can put files directly into this wwwroot folder and still can't access them by browsing to http://localhost/example.css

I am wondering this for days now (but paused while christmas ;) ) and I don't know anymore.
Where do I have to put static files to be accessible by a browser?

**Comment by muratg** [comment]
Can you set your webroot to a subfolder instead?  HelloMVC sample already has wwwroot, so keep that and put your css file there, and let us know if that doesn't work.

**Comment by davidfowl** [comment]
@DasJott And you're using the static files middleware right?

**Comment by muratg** [comment]
Ugh good point. I forgot that HelloMVC sample doesn't have static files...  @DasJott, you'll need to add `Microsoft.AspNet.StaticFiles` to your project.json, and do `app.UseStaticFiles()` in your `Configure` method.

**Comment by DasJott** [comment]
@muratg @davidfowl That was it, thanks a lot! And I am sorry, but I didn't know that and obviously didn't find the correct information in the last days of intense googling...

So you need a package to be able to access static files? How odd is that... ;)
Guess, this can be closed then...

**Comment by muratg** [comment]
@DasJott no worries.  I recommend searching https://docs.asp.net. The documentation is not complete, but some of the stuff is actually documented.  See [static files docs](https://docs.asp.net/en/latest/fundamentals/static-files.html) for example.

**Comment by DasJott** [comment]
@muratg thank you very much! 
I guess I will study that documentation a bit deeper.
