### ISSUE TITLE
Hosting:Environment cant changed

### ISSUE THREAD

**Issue by endink** [aspnet/dnx#3288]
i upgrade my ASP.NET MVC 6 project to RC2, and the I change settings in launchSettings.json,{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:45646/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      }
    },
    "web": {
      "commandName": "web",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5001",
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      },
      "sdkVersion": "dnx-clr-win-x64.1.0.0-rc2-16302"
    }
  }
}

and everythings seems ok, but when i restart VS2015, the property window of the project still like this:
![default](https://cloud.githubusercontent.com/assets/240164/12028541/cbbd1d42-ae13-11e5-88c3-ddab680e57f4.PNG)

and i check the launchSettings.json file , "ASPNET_ENV" be used in launchSettings.json, VS project property window display "Hosting:Environment", i had to change "Hosting:Environment" to "ASPNET_ENV" each time, is there some cache for this settings? please help, thanks!

BTW, only "web" like this, "IIS Express" is OK

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#541
