### ISSUE TITLE
dnx "command" can fail when used with Powershell

### ISSUE THREAD

**Issue by knarfalingus** [aspnet/dnx#3289]
When using commands in a console app on Windows, along with Powershell, can introduce case sensitivity issues not seen with the console. For example if this is in project.json

 "commands": {
    “xyz”: "ConsoleApp1"
  }

In Powershell

from parent folder

cd ConsoleApp1 
dnx xyz

works

cd consoleAPP1
dnx xyz

fails.

![powershell](https://cloud.githubusercontent.com/assets/7730209/12046102/ac9c6c86-ae7e-11e5-88a6-f9f8d9d87659.png)

**Comment by muratg** [comment]
Thank you for your report.  We're retiring DNX, DNU and DNVM in RC2 and will be moving on to use dotnet CLI (https://github.com/dotnet/cli) going forward.
