### ISSUE TITLE
Restore should warn me about packages trying to use old content-inclusion mechanisms

### ISSUE THREAD

**Issue by dls314** [aspnet/dnx#3290]
There are a tangle of issues in the Nuget repository about how to safely replace the old install.ps1 / init.ps1 script functionality for DNU restore scenarios, but it would be nice if DNU restore would fail when restoring a package that uses the unsupported functionality.

Is there a way to configure this behavior today? If so, I haven't found it.

**Comment by davidfowl** [comment]
DNU restore is going away and will merge with NuGet restore. To that effect there won't be any warning for those things because packages can support old and new ways of doing thing (people do this all the time for down level support).

**Comment by dls314159** [comment]
Do you have any thoughts about how to figure out if a package will be broken today? Other than my mental list (liblog, mono.options, ...), I've started searching my packages folder for *.ps1 after the fact.

**Comment by davidfowl** [comment]
There's no tool if that's what you're asking for.
