### ISSUE TITLE
Failing to copy content files defined in project.json into the output directory

### ISSUE THREAD

**Issue by thiagomajesk** [aspnet/dnx#3291]
Hi everyone! 
Just started a project using the new DNX RC and NancyFX and I need to copy some content files to the output directory (view files). And I just can't get it to work, no files are copied to my *\artifacts\bin\{project}\Debug\app*, only project.json.

Here's my project.json file:

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true,
    "languageVersion": "csharp6"
  },
  "tooling": {
    "defaultNamespace": "Project"
  },
  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.Owin": "1.0.0-rc1-final",
    "Nancy": "1.4.3"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "frameworks": {
    "dnx451": { }
  },
  "content": [ "Views/**/*.html", "*.html" ],
  "contentFiles": ["Views/Index.html", "page.html"]
}
```

**Comment by davidfowl** [comment]
the `/app` folder is irrelevant. Files for your project get copied into the right place by default.

**Comment by thiagomajesk** [comment]
@davidfowl Howcome? Where can I see the copied files then? This doesn't make sense to me

**Comment by davidfowl** [comment]
The question I have is what doesn't already work

**Comment by thiagomajesk** [comment]
Ok, maybe I should make myself more clear...
NancyFx expects that the view files (*.html) to be copied to the output directory to make them avaible when returning views (you can see the explanation [here]( https://github.com/NancyFx/Nancy/issues/1528). So I'm defining which files I want as content in my project.json and they are not beeing copied to the output folder.

**Comment by muratg** [comment]
@thiagomajesk were you able to workaround this?  

In RC2, we're retiring dnx/dnu and we'll be moving to use dotnet CLI.  Putting this in backlog for now.

**Comment by thiagomajesk** [comment]
@muratg I think we could remove this issue because the problem is not relevant anymore. 
The guys from nancyfx team cracked the case for me... 
Even though the framework behaves differently with dnx, it seems that is not a dnx issue, I had to use just a different approach.

**Comment by muratg** [comment]
@thiagomajesk Cool, good to hear!
