### ISSUE TITLE
Publish tests failing on CI due to long path

### ISSUE THREAD

**Issue by rynowak** [aspnet/dnx#3293]
Just leaving a breadcrumb here because I had to disable tests: https://github.com/aspnet/dnx/pull/3292

Due to some package changes by CoreCLR these tests fail on the CI due to long path issues.

**Comment by muratg** [comment]
@ryanbrandenburg Are they failing because we're still using DNX with full CLR to start the tests?  I was under the impression that CoreCLR would be able to deal with long paths.

**Comment by ryanbrandenburg** [comment]
@muratg I think you might have meant @rynowak, I don't know much on this subject.
