### ISSUE TITLE
dnu pack will fail if consuming nuget package `ServiceBus.V1_1`

### ISSUE THREAD

**Issue by Tasteful** [aspnet/dnx#3294]
Error message from compiller is
`The package ID 'ServiceBus.v1_1' contains invalid characters. Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'.`

**Comment by davidfowl** [comment]
Can you make a sample that repros the issue? Push it to github and send the url.

**Comment by Tasteful** [comment]
@davidfowl Sample application is found here https://github.com/Tasteful/bugs/tree/DnuPack-3294

**Comment by davidfowl** [comment]
That's pretty weird. I wonder if NuGet pack fails the same way.

**Comment by davidfowl** [comment]
Yep, bug in `dnu pack`, this will be fixed in the dotnet CLI (hub.com/dotnet/cli) as `dnu` and `dnx` are being retired.

**Comment by Tasteful** [comment]
I have added an nuspec that will work with `nuget pack` and that seams to work.

**Comment by davidfowl** [comment]
Fix is here https://github.com/dotnet/cli/pull/689
