### ISSUE TITLE
WebSockets not working when hosted on IIS

### ISSUE THREAD

**Issue by jakakonda** [aspnet/dnx#3295]
Version: ASP.NET 5 rc1-Update1
Socket library: SignalR 3 rc1-final (not rc1-update1 as stated originaly)

**Problem**: SignalR fallbacks to long polling when hosted on IIS, works when run directly (started from cmd dnx web command).

**Tested on**: Azure website (with websockets on), my PC on IIS and directly through Kestrel (works).
I have web sockets installed.

SignalR log when hosted on IIS, fallbacks to long polling:

    SignalR: Client subscribed to hub 'chathub'.
    SignalR: Negotiating with '/signalr/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
    SignalR: serverSentEvents transport starting.
    SignalR: Attempting to connect to SSE endpoint 'http://localhost:31650/signalr/signalr/connect?transport=serverSentEvents&c…wVlnXCY8bI7R8E&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=2'.
    SignalR: serverSentEvents transport timed out when trying to connect.
    SignalR: EventSource calling close().
    SignalR: serverSentEvents transport failed to connect. Attempting to fall back.
    SignalR: foreverFrame transport starting.
    SignalR: Forever Frame is not supported by SignalR on browsers with SSE support.
    SignalR: foreverFrame transport failed to connect. Attempting to fall back.
    SignalR: longPolling transport starting.
    SignalR: Opening long polling request to 'http://localhost:31650/signalr/signalr/connect?transport=longPolling&client…8WRrhWwVlnXCY8bI7R8E&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
    SignalR: Long poll complete

After long hours of debugging, I started my website directly through dnx (no IIS or anything else) via command line using:

    dnx web

And web sockets **worked** out of the box without any problems.

When working with sockets for node, websockets should be turned ff on IIS in order to work (link to resource [here on iis.net][1]), so I tried the same thing and got the error (occurs as soon as `webSocket` element is present in web.config):

> An error occurred attempting to determine the process id of the DNX process hosting your application.

My web.config:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <system.webServer>
            <handlers>
                <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
            </handlers>
            <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="true" startupTimeLimit="3600" />
            <webSocket enabled="false" /> 
        </system.webServer>
    </configuration>

At this point I ran out of ideas. 

I'd say that the problem is web sockets not being forwarded to DNX and would therefore classify it as a bug. I also added a link to a quickly (and ugly) created solution, where the problem is recreated.

[Solution: WebSocketsDemo.zip](https://github.com/aspnet/Home/files/76767/WebSocketsDemo.zip)
[Github repository with the demo solution source code](https://github.com/jakakonda/WebSocketsDemo)

  [1]: http://www.iis.net/learn/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support

**Comment by davidfowl** [comment]
> Socket library: SignalR 3 rc1-update1

Doesn't exist. Did do you build it from source? Also, websockets and SignalR are not going to be RTM with ASP.NET 5 RTM. See the roadmap for more details https://github.com/aspnet/Home/wiki/Roadmap

**Comment by davidfowl** [comment]
Side node: It would be better if you made a repository so people don't have to download a zip to look at the code.

**Comment by jakakonda** [comment]
SignalR is **rc1-final** (my mistake, copy and paste is sometime hell, I update the original post). Taken from [aspnetmaster myget](https://www.myget.org/F/aspnetmaster/api/v3/index.json) repo.

Github repo to the demo solution [here](https://github.com/jakakonda/WebSocketsDemo).

**Comment by davidfowl** [comment]
Same applies, we're not actively developing SignalR for release right now as it won't be shipping. I don't expect us to be fixing bugs like this in the short term. File this issue on the SignalR repository for later consideration.

**Comment by jakakonda** [comment]
I am aware that the official release is planed for Q3 this year. 

As it works when ran without IIS I assumed this is an issue related to the bridge between IIS and dnx not to SignalR or websockets in general.

If there won't be any fixes in near future, is there any quick and dirty way to run on Azure as an App Service (previously know as Web Site)?

**Comment by davidfowl** [comment]
You're missing the websocket middleware. Add it and call UseWebSockets before calling UseSignalR

**Comment by jakakonda** [comment]
Just tested it and works. My mistake after all.
Thanks you for your help and time, have a very nice day!
