### ISSUE TITLE
Support dnu restore --no-proxy

### ISSUE THREAD

**Issue by matthewvalimaki** [aspnet/dnx#3296]
Using `dnu` version 1.0.0-rc1-16231 on Windows 7 I noticed that `dnu restore` by default uses default Windows proxy settings and there is no way, other than modifying the OS proxy settings, to disable proxy. Just like there is `-p` for defining proxy I recommend a flag `--no-proxy` or similar to enforce disabling proxy. Use case for this is being able to bypass OS level proxy configuration when necessary.

**Comment by muratg** [comment]
DNU functionality is being moved to NuGet in RC2.  They have the initial support for ASP.NET 5 in their dev branch now.  No more changes in DNU is planned.
