### ISSUE TITLE
Async Issues using net40 dll with DNX451

### ISSUE THREAD

**Issue by pemari-msft** [aspnet/dnx#3297]
Since the DNX451 TFM was dropped and have reverted to using our `net40` dll for `WindowsAzure.Storage` on DNX451, we've been getting a few issues related to Async calls with this interaction. 

https://github.com/Azure/azure-storage-net/issues/220 : Should it be expected that a DNX451 dll that takes a dependency on our package works on Mac OSX at this point? 

https://github.com/Azure/azure-storage-net/issues/202 : This was reported on the ASP.NET github issues as well. This works fine in our code but the interaction with ASP.NET MVC causes these odd failures. Completely orthogonal to our code and not reproducible unless you're using ASP.NET, so maybe I should be reengaging over there?

I thought this was supposed to be compatible -- am I misunderstanding? Any pointers as to what's going on here?

**Comment by muratg** [comment]
@anurse What's the TFM that they should be using?  Feel free to close the issue after providing them guidance.

**Comment by davidfowl** [comment]
closing this out as its not a dnx issue
