### ISSUE TITLE
Dnu packs wrong dlls in TFS build.

### ISSUE THREAD

**Issue by noeljiangcc** [aspnet/dnx#3299]
My solution contains 2 aspnet5 projects. When make build in tfs, the artifacts of these 2 projects are generated in $(BinariesRoot)\$(Configuration). It is common way to generate all artifacts into a same place. And the detail steps are like:
1. Build the first project, it outputs Project1.dll in the $(BinariesRoot)\$(Configuration).
2. Dnu(Microsoft.Dnx.Tooling.dll) packs all the dlls  into nuget pack in the folder. Then Project1.nupkg which contains Project1.dll are created.
3. Build the second project, it outputs Project2.dll in the same folder.
4. Dnu still packs all the dlls in the folder. Then Project2.nupkg which contains both Project1 and Project2.dll are created. But the expected is Project2.nupkg should only contain Project2.dll.

In my local machine, the binaries are output in different folder. So this issue doesn't occur.

Is there any way to make some configurations to force dnu only pack the specified files?

Or I have to make some configurations of TFS to specify different output dir for different project?

**Comment by muratg** [comment]
`dnu pack` functionality will move to dotnet CLI for RC2.  No more changes are planned for DNU.

**Comment by noeljiangcc** [comment]
I have solved this issue by setting "GenerateProjectSpecificOutputFolder" to "true", according to:
https://blog.stangroome.com/2012/05/10/override-the-tfs-team-build-outdir-property-net-4-5/

The property makes to generate the artifacts in a separated sub-folder of $(BinariesRoot)\$(Configuration).
