### ISSUE TITLE
Unable to publish ASP.net 5 project  when using PCL Framworks.

### ISSUE THREAD

**Issue by jaganjan** [aspnet/dnx#3300]
look at this issue  [link to stackoverflow!](http://stackoverflow.com/questions/34628319/asp-net-5-publish-not-working-but-project-build-and-run-debug-is-expectedwor) , i seen a similar thread in this repostory #2967 but its not closed right now , please provide any workaround to this issue.

**Comment by muratg** [comment]
@jaganjan @davidfowl will look into #2967.  Though, FYI, we're moving publish command to dotnet CLI.
