### ISSUE TITLE
Kestrel 1.0.0-rc2-16268 package in local directory.dnx/packages

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/dnx#3301]
Just spent ages working this out,
It seems I have this package Kestrel 1.0.0-rc2-16268 in my local packages directory.
Cant understand where it came from but the net effect was my application stopped working due to this package.
When I checked myget latest prerelease was 1.0.0-rc2-16236.

Deleting the packages out of .dnx/packages and doing a dnu restore got things working again.

My question - how did that package get in there?  Was I unlucky to download a package that was not meant to be released?

My nuget config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="aspvnext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="aspvnext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
  </activePackageSource>
</configuration>
```

**Comment by mikes-gh** [comment]
Would it be possible for dnu restore to delete packages in .dnx/packages that disappear from myget or is it just a case of deleting the contents of .dnx/packages before dnu restore while things are in flux.
related to

https://github.com/aspnet/dnx/issues/3238

**Comment by BrennanConroy** [comment]
You probably grabbed that package from the aspnetcidev feed somehow. Either you cloned one of our repos which has its own local nuget.config or you did restore and passed in that feed

**Comment by mikes-gh** [comment]
Ah yes I downloaded the Identity repo to check out a google sign in issue I was having.
That had the aspnetcidev  and I must have restored off that.
Thanks for working that out.
