### ISSUE TITLE
DNX Core USB

### ISSUE THREAD

**Issue by wim11be** [aspnet/dnx#3306]
I need to read from a serial port or usb device in DNX Core. I found several ways to do this in C#: using WinUSBNet, LibUsbDotNet or SerialPort class. But none of these are available in DNX Core. 

Are there any others or is this simply not possible yet(or never)?

**Comment by davidfowl** [comment]
@wim11be See https://github.com/dotnet/corefx/issues/984

**Comment by wim11be** [comment]
All of those are not built for DNX Core 5.0 so this really didn't help. Is USB support something that is going to be added or is this not possible?
