### ISSUE TITLE
Loading DNX project symbols while debugging multiple startup projects

### ISSUE THREAD

**Issue by davenewza** [aspnet/dnx#3307]
We are having issues with debugging DNX projects using Kestrel. When running multiple DNX startup projects simultaneously, it seems that symbols from class libraries within the solution cannot be loaded into both DNX debug sessions.

We have two API startup projects using four, 'shared' class libraries. It appears that, with debugging both API projects simultaneously, only one of the API projects can "grab" the debug symbols at a time.

**Modules for the one API project:**

![image](https://cloud.githubusercontent.com/assets/6212830/12293612/6c5f3c18-b9fd-11e5-8226-f2777761a704.png)

Here the symbols aren't being loaded for the projects in the solution!

**Modules for the other API project:**

![image](https://cloud.githubusercontent.com/assets/6212830/12293719/19a348e2-b9fe-11e5-99f6-7848d5c1f4c4.png)

Here the symbols are indeed being loaded!

Debugging these API projects alone works perfectly fine. Symbols are loaded for all projects.

Note that symbols for the startup projects are also loaded fine.

**Solution structure:**

![image](https://cloud.githubusercontent.com/assets/6212830/12294094/606d6dc8-ba00-11e5-9092-1954d0f65700.png)

**Debugging multiple projects:**

![image](https://cloud.githubusercontent.com/assets/6212830/12293905/43ed08b2-b9ff-11e5-8731-cce507e5a00a.png)

**Typical API debug properties:**

![image](https://cloud.githubusercontent.com/assets/6212830/12293921/62fbae3e-b9ff-11e5-927a-36e21a238fa2.png)

**Typical API project.json:**

```
  {
    "title": "MyProject.Api",
    "webroot": "wwwroot",
    "version": "1.0.0-*",
    "dependencies": {
      "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
      "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
      "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
      "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
      "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
      "Microsoft.AspNet.Mvc.Abstractions": "6.0.0-rc1-final",
      "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc1-final",
      "MyProject.Domain.Model": "1.0.0",
      "MyProject.Infrastructure": "1.0.0",
      "MyProject.Domain.Interfaces": "1.0.0",
      "MyProject.Domain.Services": "1.0.0",
    },
    "commands": {
      "web": "Microsoft.AspNet.Server.Kestrel"
    },
    "frameworks": {
      "dnx451": { }
    },
    "publishExclude": [
      "node_modules",
      "bower_components",
      "**.xproj",
      "**.user",
      "**.vspscc"
    ],
    "exclude": [
      "wwwroot",
      "node_modules",
      "bower_components"
    ]
  }
```

**Solution's global.json:**

```
  {
    "projects": [ "src", "test", "." ],
    "sdk": {
        "version": "1.0.0-rc1-update1",
        "runtime": "clr",
        "architecture": "x86"
    }
  }
```

**Comment by davidfowl** [comment]
File this on aspnet/Tooling

**Comment by davenewza** [comment]
Sorry for that.  Issue filed [here](https://github.com/aspnet/Tooling/issues/367).
