### ISSUE TITLE
Would it be possible to support finding extension methods at runtime?

### ISSUE THREAD

**Issue by NullVoxPopuli** [aspnet/dnx#3310]
here is my scenario:

```csharp
dynamic myTable = db.Send(RelationshipName);
var myInclude = myTable.Include(i => ((object)i).Send(relationship));
```

`myTable.Include` throws a compile-time error, due to dynamics currently not being able to find extension methods.

Since dynamic stuff is all run-time anyway, couldn't the extension method just be looked up at runtime?
or, why can't it?

Could there be an implementation that would allow finding extensions methods at runtime?

**Comment by davidfowl** [comment]
This has nothing to do with DNX. Looks like you want a roslyn feature? Or maybe an EntityFramework feature...

**Comment by NullVoxPopuli** [comment]
I was thinking it would end up being a C# feature, since it would be extension mapping.  
what's Roslyn?

**Comment by davidfowl** [comment]
https://github.com/dotnet/roslyn
