### ISSUE TITLE
DNX under a system user account

### ISSUE THREAD

**Issue by joshbartley** [aspnet/dnx#3311]
Our TeamCity server runs under a system user account, which may not be ideal. The issue it causes is that during a build, all new framework downloads go to C:\Windows\System32\config\.dnx Then an error is thrown that DNU can't be found.

To work around the issue, in our buildcmd file, we set DNX_HOME to the more global path
SET DNX_HOME=C:\ProgramData\Microsoft DNX\

This feels wrong, and I'm concerned what we may have to do to get DNX secrets working once we move to the web servers and start running under another system account, like network service. Is this the preferred way to work around the issue?

**Comment by victorhurdugaci** [comment]
You are doing the right thing. Setting DNX_HOME is the way to go.
