### ISSUE TITLE
dnu publish overwrites web.config's httpPlatform.arguments

### ISSUE THREAD

**Issue by mswietlicki** [aspnet/dnx#3312]
In PublishProject.cs in GenerateWebConfigFileForWwwRootOut() there is a variable attributesToOverwrite with values "processPath", "arguments". Because of this in output web.config httpPlatform.arguments will be always empty.

I think that is a bug. 
I would like to be able to set httpPlatform.arguments during publish.

**Comment by muratg** [comment]
DNVM/DNX/DNU are being retired in RC2, so no more work is planned. 

@moozzyk I assume the new IIS publish command doesn't have this?

**Comment by moozzyk** [comment]
new iis publish copies existing attributes. processPath is the only one that is created if it does not exists and modified if it does exist.

**Comment by muratg** [comment]
:+1:

**Comment by spankr** [comment]
@muratg Could clarify what you mean about those tools being retired in RC2?

**Comment by muratg** [comment]
@spankr We won't be releasing another version of DNX or DNU going forward.  This functionality will be moved to dotnet CLI and nuget.

**Comment by davidfowl** [comment]
This specific issue has been fixed in the new iis publish tool

**Comment by muratg** [comment]
Right, this is about modifying web.config.. removed the tag and closing

**Comment by spankr** [comment]
Thank for the quick response!
