### ISSUE TITLE
"dnu restore" doesn't work with VSO (VSTS) package feeds

### ISSUE THREAD

**Issue by neilhuiz** [aspnet/dnx#3314]
For folks that use the (prerelease) Package management extension in VSO (a.k.a. VSTS), "dnu restore" doesn't work. Attempts to restore a package fail with an HTTP 400 (Authentication information is not given in the correct format. Check the value of Authorization header). I was able to do some debugging with Fiddler and found out that the process goes like this:
1. Request to: `https://{account}.pkgs.visualstudio.com/DefaultCollection/_packaging/{project}/nuget/v3/flat2/{package id}/{package version{/{package id}.{package version}.nupkg`
2. Response: 303, go see (something like) `https://vsblobprodcussu4shard46.blob.core.windows.net/b-{hex hash value}.blob?sv=2014-02-14&sr=b&sig={base64 encoded magic value}&st=2016-01-15T19%3A38%3A35Z&se=2016-01-15T23%3A43%3A35Z&sp=r`
3. Request URI in 303
4. Response: `400 Authentication information is not given in the correct format. Check the value of Authorization header`

This is where it gets interesting. The request to the blob storage location includes the same Authorization header (a basic auth header in this case) from the request to the VSO package feed. If I remove the authorization header (thus making an anonymous request to blob storage), then I get 200 and the content of the package back.

If I restore packages using nuget.exe all is fine. The second request does not contain an auth header and the package is downloaded.

I have a fiddler capture that shows all of this, but it contains some sensitive data (the auth header and the blob location) that I'd rather not simply attach. Let me know if you'd like it.

**Comment by muratg** [comment]
`dnu restore` doesn't support authentication, as @yishaigalatzer just reminded me. This is not supported yet.

**Comment by neilhuiz** [comment]
It works fine as long as you use the "ClearTextPassword" option. Am I just getting lucky?

If this really isn't supported, can someone suggest a workaround?

**Comment by ankitbko** [comment]
I am also currently using ClearTextPassword option as workaround. It would be great if authentication is supported by dnu restore

**Comment by muratg** [comment]
As you guys may have known, dnu (+ dnx and dnvm) will be retired in RC2.  Restore functionality will be through dotnet cli (which will internally use nuget)

**Comment by SrivatsaMarichi** [comment]
How can i get rid of the DNX runtime error in VSTS? Can anyone help me out here?
![2016-02-02_1218](https://cloud.githubusercontent.com/assets/13433045/12741949/2800b4ac-c9a7-11e5-8868-2036ea720936.png)

**Comment by ankitbko** [comment]
@SrivatsaMarichi You will need to run a powershell script to install dnx and run dnu restore before you can build the solution.

**Comment by pherbel** [comment]
Is there any workaround to use VSTS Package feeds with dnu or with dnx projects?

**Comment by ankitbko** [comment]
@pherbel You will need to use `ClearTextPassword` option in Nuget.config for dnu restore to work properly.
