### ISSUE TITLE
How to correctly link resources (resx)

### ISSUE THREAD

**Issue by Maxwe11** [aspnet/dnx#3315]
Hi,
I'm trying to migrate to a new DNX stuff and .NET Core from classic class library (https://github.com/NModbus4/NModbus4/pull/86) but got stuck with resources. In runtime I'm getting `System.Resources.MissingManifestResourceException` from my library with following message:

    Could not find any resources appropriate for the specified culture or the neutral culture.
    Make sure  "Modbus.Resources.resources" was correctly embedded or linked into assembly 
    "NModbus4" at  compile time, or that all the satellite assemblies required are loadable and fully signed.

How to correctly specify *.resx file in project.json? Or what another way to link resources?

**Comment by narmontas** [comment]
Duplicate #2804
