### ISSUE TITLE
DNX Web publishing doesn't register package runtime

### ISSUE THREAD

**Issue by kkurni** [aspnet/dnx#3316]
When you publish your web project, you will get AppRoot/web.cmd
This AppRoot/web.cmd will get executed on IIS and fire DNX.exe.When publishing web project, it will create AppRoot/web.cmd
IIS will execute this Web.cmd and it will execute DNX.exe.

Unfortunately this web.cmd doesn't register your runtime (which should be on your current publish package). So it will use any runtime that you installed in your user profile.

In IIS, by default it will run your web application with "ApplicationPoolIndentiy" user, But your DNX runtime was installed under your local user. This is the root cause why you get sni.dll loader exception. Because it is depend on api-ms-win-core-stringansi-l1-1-0.dll which should be located inside your runtime.

In other cases, this will lead to the different runtime version.
E.g you published x64 version, but you set your current dnvm environment with x86.
When you run this using approot/web.cmd, this will use x86 runtime which will cause exception to load native dll

For workaround, you can modify web.cmd to add your runtime into your path.
SET "PATH=%PATH%;%~dp0runtimes\%DNX_FOLDER%\bin\;"
# 

I heard that dnx will be replaced by CLI.
but i thought this will be a good fix to take while waiting for that CLI.

Here is the issue in corefx : https://github.com/dotnet/corefx/issues/5252

https://github.com/aspnet/dnx/blob/943c028633635a3fc50f0c71a69b1af525893065/src/Microsoft.Dnx.Tooling/Publish/PublishRoot.cs#L142-L167

**Comment by muratg** [comment]
DNX/DNU/DNVM is being retired in RC2 in favor of dotnet CLI like you said.  We don't have time to do more DNX changes unfortunately, but looks like you have found a workaround already.
