### ISSUE TITLE
Support checked arithmetic compile-time option

### ISSUE THREAD

**Issue by jskeet** [aspnet/dnx#3319]
Looking at https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/Compilation/CompilerOptions.cs, there's no equivalent for the `/checked+` compiler option.

I'd argue that's a reasonably serious omission - checked arithmetic has been an option since C# 1, and presumably it's still supported in IL given that it can be made explicit within source code.

(On a personal note, this is a blocker for me porting [Noda Time](http://nodatime.org) to use DNX as a build system. There's no way I'm going to make every operation that should use checked arithmetic do so explicitly...)

If it _does_ become supported in `project.json`, I'd argue that `checkedArithmetic` would be a clearer option than just `checked`.

**Comment by tugberkugurlu** [comment]
@jskeet to unblock yourself for now, you can write a compile module to add this option if I am not mistaken. I am not entirely familiar with the feature you are referring to but it should be similar to below even if it's not the correct one:

```csharp
using Microsoft.Dnx.Compilation.CSharp;

namespace CompileModuleSample
{
    public class OverflowCheckCompilationModule : ICompileModule
    {
        public void BeforeCompile(BeforeCompileContext context)
        {
            var optionsOverflowCheck = context.Compilation.Options.WithOverflowChecks(true);
            context.Compilation = context.Compilation.WithOptions(optionsOverflowCheck);
        }
        
        public void AfterCompile(AfterCompileContext context) { }
    }
}
```

There are several way to activate compile module. One of them is to stick it under `compiler/preprocess` folder for your DNX project, like I do [here](https://github.com/tugberkugurlu/aspnet-5-samples/tree/b85d21f5f67f44a685d7bb2afad1e6db4f174108/7-compile-module) and the other one is to [explicitly tell the project structure to locate it](https://github.com/aspnet/dnx/blob/60800ceec6cb92b9b19ea0575ab6380ab1bef0a5/src/Microsoft.Dnx.Tooling/project.json#L11-L13).

**Comment by jskeet** [comment]
Thanks - I'll give that a try. (The last 4 tests that are failing in Noda Time when targeting net451 are all due to this.) Does that dependency (and the compilation module) end up in the final nuget package, or is it just a build-time thing? (Obviously I'd prefer the latter :)

**Comment by davidfowl** [comment]
We just need to add a compiler option in the new CLI https://github.com/dotnet/cli (I added the tag to move it). It'll be a trivial change to add it to the compilation options.

**Comment by jskeet** [comment]
Woot - thanks David.
