### ISSUE TITLE
How to correctly diagnose a startup issue after deploying a DNX project to an Azure WebSite.

### ISSUE THREAD

**Issue by joshmouch** [aspnet/dnx#3320]
I'm deploying a DNX project to an Azure WebSite and am getting a very generic error when trying to browse it after deployment:

Oops.
500 internal server error.
An error occurred while starting the application.

What is the best way to diagnose the problem?  Browsing StackOverflow gives some suggestions, but none that work.  And I can't find a way to actually find what the problem is.  It seems that the error occurs before the Configuration method in Startup.cs runs (I say this because I tried putting the entire method in a try/catch block).
Trying anything in Startup.cs Configure() doesn't do anything (e.g. a Try/Catch block, app.UseDeveloperExceptionPage, etc.).  I don't think it even makes it this far.
The SCM portal contains nothing (e.g. Event Viewer log)
The FREB Log contains the same useless error.
The Log Stream contains the same useless error message (after enabling Diagnostic logs).

My suspicion is that there's a corrupt deployment because there were no code changes between two deployments, and one worked and one didn't.  I had to stop a deployment because it was stuck. But I need to know how to verify that.

**Comment by davidfowl** [comment]
That error page sounds like the one coming from hosting. You can enable it by setting ASPNET_DETAILEDERRORS=1 in the azure portal configuration settings. That should show the error.

**Comment by joshmouch** [comment]
Hmm... no luck with that.  I tried both "1" and "true".

![image](https://cloud.githubusercontent.com/assets/3098820/12425834/ab1da006-bea4-11e5-8d98-02c4733efff5.png)

![image](https://cloud.githubusercontent.com/assets/3098820/12425856/bbc11bfe-bea4-11e5-8258-2f798962c877.png)


![image](https://cloud.githubusercontent.com/assets/3098820/12425818/9fdfba30-bea4-11e5-9919-bca22873e118.png)

**Comment by joshmouch** [comment]
If it helps, here's the relevant line from the FREB log:

90. MODULE_SET_RESPONSE_ERROR_STATUS
Warning
 ModuleName="httpPlatformHandler", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="Internal Server Error", HttpSubStatus="0", ErrorCode="The operation completed successfully.
 (0x0)", ConfigExceptionInfo="" 17:06:43.925

**Comment by davidfowl** [comment]
Can you show a screenshot of the error page, and can you say what versions you are using?

**Comment by joshmouch** [comment]
I tried a million other things with no success.  Finally, I created a new deployment slot and deployed there instead.
That worked perfectly.
Then I swapped the two deployment slots.  Now my main slot works and the new slot doesn't (which makes sense because they were swapped).

**Comment by joshmouch** [comment]
@davidfowl I'm using the latest DNX (v 1.0.0-rc1-final)

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/3098820/12428299/da2933c6-beb1-11e5-8424-1173218a743e.png)

**Comment by davidfowl** [comment]
Yea, that's the one. Setting that setting should do the job... Are you sure it's set?

**Comment by joshmouch** [comment]
Yeah, it was set.  I have it in the screenshot, above.  Save was pressed.  I even redeployed and restarted a couple times, so the setting definitely kicked in.

**Comment by joakimfischer** [comment]
I got the same problem. Recreating the deployment slot worked for me as well.

**Comment by jhentsch2** [comment]
I was able to get a more detailed error message by adding the following to my `WebHostBuilder`:

```
var host = new WebHostBuilder()
    .CaptureStartupErrors(true)
    .UseSetting("detailedErrors", "true")
```

I found this information on this [stackoverflow answer](http://stackoverflow.com/a/29524042/263773).
Documentation link: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting

**Comment by joshmouch** [comment]
@jhentsch 
That's the first time on the entire interweb I've seen those two settings.
