### ISSUE TITLE
Relative paths in DNX projects

### ISSUE THREAD

**Issue by BenjaminAbt** [aspnet/dnx#3321]
What is the correct way to work with relative paths in DNX projects?
I cannot use Assembly.CodeBase, ```xproj``` seems to work here different to ```csproj``` 
Environment.CurrentDirectory is no option.

Usually I would use
```
typeof (MyType).Assembly.Location;
```
or
```
typeof (MyType).Assembly.CodeBase;
```
to determine the path of the assembly and to get the base path.
This works so far if I work locally with Visual Studio with both environments.

On my test server (agents are not started in the project directory!) the csproj code still returns the correct path but xproj returns
```
C:/Users/benjaminabt/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc1-update1/bin/Microsoft.Dnx.Loader.dll
```

Is this a known issue or does the developer have to work here in another way?

**Comment by davidfowl** [comment]
If you're in an ASP.NET application you should be using `IApplicationEnvironment.ApplicationBasePath`.

**Comment by BenjaminAbt** [comment]
Hi David,

I'm in a Preview Class Library Package Template (DNX). 
It will be consumed by an ASP.NET Core 1 application but should also be consumable to other applications.
So ```IApplicationEnvironment.ApplicationBasePath``` wont work if this is only available in hosting environments.

**Comment by davidfowl** [comment]
You have 2 options:

- Use `Microsoft.Extensions.PlatformAbstractions`. There you can use `PlatformServices.Default.Application.ApplicationBase` (Application is an `IApplicationEnvironment`)
- Use `System.AppContext` and use `AppContext.BaseDirectory`

**Comment by BenjaminAbt** [comment]
Thanks!
```PlatformServices.Default.Application.ApplicationBasePath``` works great.
