### ISSUE TITLE
Warning for correct dependency resolution during dnu restore

### ISSUE THREAD

**Issue by StrangeWill** [aspnet/dnx#3323]
warning NU1007: Dependency specified was [AppName] >= 1.0.0 < 2.0.0 but ended up with [AppName] 1.0.0.18.

Uh... that's what I'm expecting though. 1.0.0.18 is above or equal to 1.0.0 and below 2.0.0.

Is this expected behavior for non-exact matches? I know there were a few other bugs concerning resolving incorrect beta versions and whatnot, but didn't find anything that was a warning during a correct resolution.

**Comment by davidfowl** [comment]
If your lower bound doesn't exist then you're kinda guessing with your dependencies aren't you?

**Comment by StrangeWill** [comment]
1.0.0 would be the lower bound, is it not? This is a supporting library in a solution (specifically the tests for a web application), 4th build number is auto-incremented on every build for nuget package compatibility for Octopus deployment.

**Comment by davidfowl** [comment]
Using the 4th number is pretty non standard. It's only supported in nuget for legacy reasons. Still I don;t quite understand what you're doing so I can't comment. The warning was intended to let you know that you're aiming your dependency too low.

**Comment by StrangeWill** [comment]
OK, I was worried that the 4th number was only sort-of kept around... I'll explain my use case but I can probably change what we do and only use the 4th number for Octopus.

Octoplus deploy uses nuget packages to deploy software, these are generated from our continuous integration server, if I build the same project with the same nuget package agents will have trouble determining that they need to pull a new package (in general modifying a nuget package in-place is a big no-no).

So typically we increment minor for scheduled releases, revision for hot fixes and use the 4th number as our build number from TeamCity so all builds have unique versions.

However, I can make Octopack use a different version than what the library reports, so I'll go ahead and see about telling Octopack to build the 4 number version (being as that is ONLY for Octopack) and the issue should go away and I can easily be more strict about versions with no wiggle room.

Thanks! Feel free to close this if you think this is a non-issue.
