### ISSUE TITLE
Favoring local projects during dependency resolution

### ISSUE THREAD

**Issue by herecydev** [aspnet/dnx#3326]
I'm struggling with the following error, during restore:

*Dependency specified was MyApp.Persistence >= 2.0.0 but ended up with MyApp.Persistence 1.0.0*

The 2.0.0 package is available from a nuget feed and can be resolved if forcing the target to `package`. However no matter what the local project is always favored despite being a different version. Any idea about this? It seems their is a blanket rule of locality over versioning.

**Comment by davidfowl** [comment]
Projects *always* win over packages, you can work around that by specifying a target on that particular dependency edge:

```
{
    "dependencies": {
          "MyApp.Persistence": { "target": "package", "version": "2.0.0" }
     }
     ...
}
```
I've been seeing error reported like this for wrapped projects, is that the current situation?

**Comment by herecydev** [comment]
It's not wrapped. Thanks for the explanation, it feels like a strange decision to break SemVer over choosing a local project.

Do we have a way of restricting versioning? I've seen a few ideas like `2.*` to indicate *only* version 2, e.g. 2.1, 2.2, etc.

In this current situation it broke SemVer and therefore my referencing project over choosing the readily available nuget package.

**Comment by davidfowl** [comment]
> It's not wrapped. Thanks for the explanation, it feels like a strange decision to break SemVer over choosing a local project.

Nope! projects always win over packages. When you build a project into a package there's usually a step that sets the version to be in sync with the ci build. We don't want to deal with looking at what a project version would have been on disk to pick a package or project, it's just too brittle (we used to do this).

> In this current situation it broke SemVer and therefore my referencing project over choosing the readily available nuget package.

We're not going to change this behavior, your best bet it to specify the project or package if that's what you want to target.

**Comment by muratg** [comment]
Also, DNX is being retired in RC2, so closing this.
