### ISSUE TITLE
Can't get MVC project running on Raspberry Pi with Windows IoT Core

### ISSUE THREAD

**Issue by rorymurphyza** [aspnet/dnx#3329]
Hi guys. .NET MVC amateur/DNX novice here. I need some help with getting my MVC project running on my Raspberry Pi, running Windows IoT core. I have been following the project instructions at http://timdows.com/projects/asp-net-vnext-on-a-raspberry-pi/ but I am still not coming right. I have dnvm set up on my dev machine:

```
Active Version           Runtime Architecture OperatingSystem Alias
```

---

```
   1.0.0-beta7       clr     x86          win
   1.0.0-beta8       clr     x64          win
   1.0.0-beta8       clr     x86          win
   1.0.0-beta8       coreclr x64          win
   1.0.0-beta8       coreclr x86          win
   1.0.0-rc1-update1 clr     x64          win
   1.0.0-rc1-update1 clr     x86          win             default
   1.0.0-rc1-update1 coreclr x64          win
   1.0.0-rc1-update1 coreclr x86          win
   1.0.0-rc2-16357   clr     x64          win
   1.0.0-rc2-16357   clr     x86          win
   1.0.0-rc2-16357   coreclr arm          win
   1.0.0-rc2-16357   coreclr x64          win
   1.0.0-rc2-16357   coreclr x86          win
```

After creating the project in Visual Studio as shown in the tutorial above, I made the changes to the `project.json` by adding in the `--server.urls=http://*:5000/` as required, linked here for you to see.
[project.json.txt](https://github.com/aspnet/dnx/files/100538/project.json.txt)

I can then run this project from the Visual Studio environment, using the "web" runtime option.
I then compile the project for ARM using the command:
`dnu publish --out C:\publish\DnxPi --no-source --runtime dnx-coreclr-win-arm.1.0.0-rc2-16357`, which takes a while but gives me what I need. I then transfer this to my Pi and enter a PowerShell session with the Pi to start the application using the `.\web.cmd` command. As I would expect, I get output showing that everything is cool so far:
`info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\xxxxxxxxxx
pository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Now listening on: http://*:5000/
Application started. Press Ctrl+C to shut down.`
Now comes the part that gets me. When I navigate to this app using my browser, this happens:
`info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://10.8.1.116:5000/
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method mvctest.Controllers.HomeController.Index with arguments () - ModelState is Valid'
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to resolve service for type 'Microsoft.Dnx.Compilation.ILibraryExporte
r' while attempting to activate 'Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService'.
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Dnx.Compilation.ILibraryExporter'
while attempting to activate 'Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, I
Set`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet
`1 callSiteChain)`
This is only part of the message. Full message is linked: 
[stacktrace.txt](https://github.com/aspnet/dnx/files/100549/stacktrace.txt).

Looking through other issues, I see that some other people had the same problem as discussed in https://github.com/aspnet/dnx/issues/3032, but these solutions have not worked for me. I tried everything from changing all the `project.json` dependencies from `"EntityFramework.Commands": "7.0.0-rc1-final"` to `"EntityFramework.Commands": "7.0.0-*"`, etc. which did not help.

I then tried changing these to `"EntityFramework.Commands": "7.0.0-rc2-16357"`, as also suggested in order to bring these in line with the dnvm installed, but this caused problems in Visual Studio because I could not then build the project anymore. I am unexperienced with using NuGet at the moment, so I could not see how to resolve these issues.

After tearing my hair out for a couple of days and only getting myself more confused, I thought I would ask for any help here that I can get. Please keep in mind that I haven't really done something like this before, so any advise would be awesome. Thanks for reading this and I really appreciate the time you guys have spent on this.

**Comment by davidfowl** [comment]
Did you update all of your dependencies to rc2 as well? It looks like you didn't....

**Comment by rorymurphyza** [comment]
Hi. Thanks for the quick response. I tried updating the dependencies from `"EntityFramework.Commands": "7.0.0-rc1-final",` to `"EntityFramework.Commands": "7.0.0-rc2-16357",`, etc., This then generates the error:
`dnu : Unable to locate Dependency EntityFramework.Commands >= 7.0.0-rc2-16357
At line:1 char:1
+ dnu restore
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to locat...7.0.0-rc2-16357:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`
when running `dnu restore` from Visual Studio. I then tried to NuGet Package Manager to get these updated versions, but it will not show me anything other the the current "v1.0.0-rc1-final" that I already have and there is no newer version shown here. I am assuming that the problem I am seeing is because Visual Studio thinks I need "1.0.0-rc1-final" and I have "1.0.0-rc2-16357" installed on my machine?
Additionally, trying to download the 1.0.0-rc1-final from the stream gives me this:
![image](https://cloud.githubusercontent.com/assets/16285026/12508997/1c6e22de-c108-11e5-9af6-37f8d8ae294a.png)

Am I doing this incorrectly?

**Comment by davidfowl** [comment]
Almost.. We don't official ship arm builds so they are only available on our myget feeds hence there's no 1.0.0-rc1-final version. That means you have to move all of your dependencies to rc2 which means you have to either use * in your versions ({version}-rc2-*) or go to myget to pick specific versions.

**Comment by rorymurphyza** [comment]
Great. I'm going to try the "*" that you suggested and see if that helps. Unfortunately it takes a while to build the project, but I'll let you know what happens. Thanks for the advise.

**Comment by rorymurphyza** [comment]
Hi again. I am sorry to have to come back to this, but I am really struggling here still. I think that something is just not fitting in place in my head. I tried changing my dependencies as you suggested in my `project.json`:
`"dependencies": {
    "EntityFramework.Commands": "7.0.0-rc2-*",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc2-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc2-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc2-*",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc2-*",
    "Microsoft.AspNet.Mvc": "6.0.0-rc2-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc2-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-*",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc2-*",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-*"
  },`

but I suspect that this is not what you meant by your previous comment. 
When I do a `dnu restore`, I get the expected "Unable to locate Dependency" errors that show that I am slightly out of my depth here.
I also have no idea how to use myget to download other packages, I thought that is what I was previously doing?

**Comment by davidfowl** [comment]
Go to https://jabbr.net/#/rooms/AspNetCore or https://gitter.im/aspnet/Home

**Comment by samualjacksonau** [comment]
I could install exact same version using following commands.

`set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetvnext`
`dnvm install 1.0.0-rc2-16319 -r coreclr -arch arm -u`
`dnvm install 1.0.0-rc2-16319 -r coreclr -arch x86 -u`
`dnvm install 1.0.0-rc2-16319 -r coreclr -arch x64 -u`
`dnvm install 1.0.0-rc2-16319 -r clr -arch x86 -u`
`dnvm install 1.0.0-rc2-16319 -r clr -arch x64 -u`

I will update if rest of the process worked...

**Comment by Kinani** [comment]
Anything on this? because right now, I'm not able to install any ARM build to my machine.

**Comment by BrennanConroy** [comment]
@Kinani DNX has been retired since RC2 and has been superseded by dotnet CLI (https://github.com/dotnet/cli) Please give it a shot to see if your scenario is fixed there, and if not, feel free to file a bug there as well.

**Comment by Kinani** [comment]
@BrennanConroy Okay, Thank you for your quick response.
