### ISSUE TITLE
Static constructors not being called during DNX on-the-fly recompile

### ISSUE THREAD

**Issue by joshmouch** [aspnet/dnx#3331]
I have a set of static properties on a static class that I initialize using a static constructor.

For example:

````
public static class KnownValues {
    static KnownValues() {
        ConfigureKnownValues.Configure()
    }

    public static class SetOne {
        public static class SubSetOne {
            public static object ValueOne {get;set;}
        }
    }
}

public static class ConfigureKnownValues {
    static ConfigureKnownValues() {
        Configure()
    }

    public static void Configure() {
        KnownValues.SetOne.SubSetOne.ValueOne = new Object();
    }
}

.....

// Some random line of code in the application.
// Sometimes this will work... sometimes it won't.
if (KnownValues.SetOne.SubSetOne.ValueOne == null) throw new Exception("What is going on?!");

````

This works fine.... for a while.  I'm able to access KnownValues.SetOne,SubSetOne.ValueOne from anywhere

However, after a few or more saves of different files, which causes DNX to recompile my MVC project on-the-fly, KnownValues.SetOne,SubSetOne.ValueOne becomes null.

It feels like when DNX recompiles in the background, it's not re-running the static constructor.

However, if I then hit F5 in Visual studio to run the application, it'll start working again.  Then I can stop and hit Ctrl-F5 to enter DNX-compile-on-the-fly-mode (sorry I don't know the real name), and it'll continue working until a make a changes to a few more files.

Also, if I stop IISExpress and then hit Ctrl-F5, it starts working again.

I know the obvious question is: "Is something setting that property to null?"  But I can assure you that according to Resharper, it is only being set in the single location.

**Comment by davidfowl** [comment]
AFAIK, they work the same. Also it compiles it on the fly but after killing the process. So it likely unrelated to dynamic compilation.

**Comment by joshmouch** [comment]
@davidfowl It sure does seem like it's related to dynamic compilation.
I can 

1) Save a file (should force dynamic complication. 2) Run some code 3) Recreate my problem.
Then:
1) Hit Ctrl-f5 2) Run the *exact same code* 3) Problem is gone.

**Comment by davidfowl** [comment]
When you save a file, the entire process dies.

**Comment by joshmouch** [comment]
I'm going to recreate this issue now that I've been able to create a test case.  It's not related to recompiling at all.  It's a general static class issue.  I'll call it: Static constructors not called when accessing nested static type.
