### ISSUE TITLE
Unable to run/debug the web application

### ISSUE THREAD

**Issue by javafun** [aspnet/dnx#3332]
Create a new project using VS2015 Update 1 and receive the following error

---
## Microsoft Visual Studio

The following error occurred attempting to run the DNX design time process (dnx-clr-win-x86.1.0.0-rc1-update1). 

Unable to start the process. System.ComponentModel.Win32Exception (0x80004005): Access is denied   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)   at Microsoft.Dnx.DesignTimeHost.Program.Main(String[] args)--- End of stack trace from previous location ...

**Comment by javafun** [comment]
In addition, I have already tried the followings solutions, none of them could fix the issue

1. Repair the ASP.NET 5 RC1 
2. Run the dnvm update-self

**Comment by muratg** [comment]
@javafun Thanks for the report. In RC2, we're retiring DNX, DNU and DNVM. New command line experience will be through dotnet CLI. I recommend raising the question over that repo (https://github.com/dotnet/cli)
