### ISSUE TITLE
Project Dependency References at different directory levels

### ISSUE THREAD

**Issue by russcam** [aspnet/dnx#3333]
Given the following project directory structure

```
Root
|_ global.json
|_ Solution.sln
|_ src
    |_ Project1
    |_ Project2
    |_ Performance
        |_ Benchmark
```

where the `project.json` in Benchmark specifies dependencies on Project1 and Project2

``` javascript
{
  "version": "1.0.0-*",
    "compilationOptions": {
        "warningsAsErrors": false,
        "emitEntryPoint": true
    },
  "dependencies": {
    "Project1": { "target": "project" },
    "Project2": { "target": "project" }
  },
  // ...
}
```

dependencies `Project1` and `Project2` cannot be resolved for `Benchmark` with `Solution.sln` in VS 2015. In contrast, `Project2` has a project dependency on `Project1` which can be resolved without problem.

Do project directories need to be at the same directory level in order to resolve project dependencies? Is there a way to specify where to look for a project dependency?

**Comment by muratg** [comment]
@russcam thanks for the report. In RC2, we're retiring DNX, DNU and DNVM. New command line experience will be through dotnet CLI.  I recommend raising the question over that repo (https://github.com/dotnet/cli)
