### ISSUE TITLE
Unable to find/load System.Net.NetworkInformation on ARM machine.

### ISSUE THREAD

**Issue by jornbeyers** [aspnet/dnx#3334]
I'm trying to run a dnx project that uses System.Net.NetworkInformation on an ARM machine. The machine is a RaspBerry PI 2 running on windows iot core. The project is unable to find System.Net.NetworkInformation. There already have been issues with System.Net.NetworkInformation (#3262) on Linux CoreCLR. They advised to add Microsoft.NETCore.Platforms, but this doesn't resolve the error. 

I'm using version 1.0.0-rc2-16357 with the arm architecture.

Does anyone have an idea on how to solve this issue?

**Comment by muratg** [comment]
Thanks for the report. In RC2, we're retiring DNX, DNU and DNVM. New command line experience will be through dotnet CLI.  I recommend experimenting with that instead.
