### ISSUE TITLE
Can resolve resource from .NET dll when referenced via a wrapper "project.json"

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/dnx#3335]
[Here](https://github.com/theonlylawislove/temp-dnx-resource-issue) is the repo to reproduce the issue. ([relevant file](https://github.com/theonlylawislove/temp-dnx-resource-issue/blob/master/src/TestDacResourceResolver/Program.cs))

When running the code, I get an exception....

> Could not find file 'Microsoft.Data.Tools.Schema.Sql.resources'.

However, when I move a few dlls to the path that `dnx.exe` is located, everything works correctly. I checked the loaded appdomain. Normally, the assembly location is loaded from where it is referenced from the `project.json` wrapper. However, if the dll exists where `dnx.exe` is located, it is loaded instead.

Moving my referenced dlls is, of course, not acceptable. I was only doing it to debug things.

Any ideas why .NET resources can't be resolved for a dll when referenced via `project.json` wrappers?

**Comment by muratg** [comment]
Thanks for the report. In RC2, we're retiring DNX, DNU and DNVM. New command line experience will be through dotnet CLI.

**Comment by theonlylawislove** [comment]
Are you sure this won't happen in the new dotnet cli?

**Comment by muratg** [comment]
@theonlylawislove I suppose it's possible, though things changed quite a bit too.  I recommend installing dotnet cli tooling and give it a shot! http://dotnet.github.io/getting-started/ is the place.
