### ISSUE TITLE
Project Dependencies do not have their build scripts ran when a referencing project is built

### ISSUE THREAD

**Issue by Kieranties** [aspnet/dnx#3336]
[Repro here](https://github.com/Kieranties/DnuScriptsIssueRepro)

Scenario:
- Project A has a prebuild/postbuild entry 
- Project B has a dependency on Project A

When running `dnu build` on Project A, the pre and post build scripts are executed.
When running `dnu build` on Project B, the pre and post build scripts are **not** executed.

In my real world scenario, the scripts add resources when built.  Due to the above, those resources are not included when building.

**Comment by davidfowl** [comment]
That's a known issue. Unfortunately it won't be fixed an DNX since DNX is dead. The good news is it's fixed in the .NET CLI.

**Comment by Kieranties** [comment]
Happy days!  Will be moving over to that soon.
