### ISSUE TITLE
Use of *nix directory separators in dnu pack --out under Windows in RC1

### ISSUE THREAD

**Issue by paulhanssen** [aspnet/dnx#3339]
Hi,

I'm using dnx/dnu RC1 in a cross-platform continuous build environment, and noticed a small issue when using the dnu pack command.

If you run the following pack command like so:

`dnu pack --out \artifacts`

then your packages are created correctly.

However, if you run the command with *nix directory separators so under Windows (10 & Server 2012):

`dnu pack --out /artifacts`

the package is created in the right directory, but I've noticed that the framework directory "doubles-up" e.g.

```
proj.nupkg/
           lib/
               net451/
                      net451/
                             ...file.dll
```

When you use a package like this in another project, none of your classes will appear.

Cheers

**Comment by muratg** [comment]
Thanks for the report. We're retiring dnx/dnu/dnvm toools in RC2, and we'll move on to using dotnet CLI instead.
