### ISSUE TITLE
dnu pack should support semver with build no

### ISSUE THREAD

**Issue by shederman** [aspnet/dnx#3340]
Version: "2.0.0-alpha-*"

results in a package with a version of "2.0.0-alpha", ignoring the build number at the end. This means that I cannot easily upload multiple builds for the package to our internal NuGet repository. Instead I have to do funky stuff with the -Version command line option.

**Comment by shederman** [comment]
My bad, not even -Version works. I have to manually edit the project.json and hand -enter the build number. I guess I could use gulp for this, but why should I need to?

**Comment by muratg** [comment]
DNX/DNU are being retired in RC2.

**Comment by shederman** [comment]
And nothing is going to take their place?

**Comment by davidfowl** [comment]
https://github.com/aspnet/dnx#dnx-retired
