### ISSUE TITLE
On OSX native libraries are not loaded when referencing a project.

### ISSUE THREAD

**Issue by sherif-elmetainy** [aspnet/dnx#3341]
**Reproduce Issue: ** ProjectA has the following structure below, and we do `dun restore`, 
  
```
ProjectA
|--project.json
|--Class1.cs
|--runtimes
   |--osx
   |   |--native
   |       |--mylib.dylib
   |--ubuntu-x64
   |   |--native
   |       |--mylib.so 
   |--win7-x64
   |   |--native
   |       |--mylib.dll
   |--win7-x86
       |--native
           |--mylib.dll
```

**Expected Behaviour:** The native library `mylib.dll`, `mylib.dylib` or `mylib.so` is referenced correctly in `project.lock.json` depending on the platform and loaded correctly by interop. 

**Actual Behaviour:** The library is loaded correctly in both Windows and Linux but not in OSX. In OSX ```project.lock.json``` would not contain a reference to the native library, and ```System.DllNotFoundException``` would be thrown at run time when accessing the library via interop.

When running ```dnu pack``` to create a nuget package and referencing the nuget package instead of referencing the project, the library is loaded and referenced correctly on all platforms.

**Workaround:** On Windows and Linux no workaround is needed. On OSX copying the library file ```my lib.dylib``` to ```/usr/local/lib``` would prevent the runtime exceptions. 

**Platform:**
Windows testing is done on Windows 10 64-bit (using .NET Framework 4.6 and .NET Core 32 and 64 bit 1.0.0-rc1-update1)
Linux Testing is done on Ubuntu 15.10 64-bit (Using .NET Core x64 1.0.0-rc1-update1)
OSX Testing is done on OSX El Capitan 10.11.3 (Using .NET Core x64 1.0.0-rc1-update1)

**Comment by davidfowl** [comment]
> Expected Behaviour: The native library mylib.dll, mylib.dylib or mylib.so is referenced correctly in project.lock.json depending on the platform and loaded correctly by interop.

NuGet restore does not look at the project structure it only handles packages. DNX has logic to look at those folders at runtime and do the appropriate thing per OS. As the DNX and DNU are being retired, I'll refer you to this bug on the .NET CLI https://github.com/dotnet/cli/issues/710.

See https://github.com/aspnet/dnx#dnx-retired
