### ISSUE TITLE
Dnx version and ASPNET_ENV

### ISSUE THREAD

**Issue by kscott5** [aspnet/dnx#3344]
I'm running Linux Centos 7[runtime = mono linux/osx] and Windows 10 [runtime = clr x86]
Both have dnvm version 1.0.0-rc2-15546
Both have dnvm alias set to 1.0.0-rc1-update1

On Windows the dnx commands I use all reference the correct ASPNET_ENV. 
On Centos 7 the dnx command I use always reference the production.

Does the dnvm version impact project.json reference all rc1-final assemblies?
Is there a way to downgrade the dnvm version to 1.0.0-rc1-final?

Secondly, what is the correct place to set the ASPNET_ENV environment command (profile, project.json, or hosting.json)?

**Comment by muratg** [comment]
@kscott5 you can dnvm install 1.0.0-rc1-final and use it.  dnvm version doesn't impact either runtime (dnx) versions or the versions of the packages you reference in your project.json.

**Comment by kscott5** [comment]
@muratg It would be nice if the dnu command could uninstall/cleanup older dependencies such as beta-*.

Thanks again for the info.

**Comment by BrennanConroy** [comment]
@kscott5 Just an FYI, dnu/dnx is no longer in development. We have moved onto the dotnet cli see https://github.com/dotnet/cli

**Comment by kscott5** [comment]
@BrennanConroy Right! That's my frustration! 

I guess I'll eventually need to wipe my dev box clean. Disk space issue!

Thanks again!

**Comment by kscott5** [comment]
This is no longer an issue. Currently using .NET Core 1.0.1
