### ISSUE TITLE
Namespace confusion on imported "wrap" library

### ISSUE THREAD

**Issue by dythim** [aspnet/dnx#3345]
I'm attempting to create a new ASP.NET front end for our existing Silverlight application and ran into what seems like a bug for imported projects.  It seems like if there is a namespace "collision" -- the same namespace in two referenced assemblies, ASP.NET does not aggregate all the classes across all referenced assemblies.

We have a `MyApp.DataAccess.Security.User` object which previously lived in a `MyApp.DataAccess.Security.dll` project.  It was extracted so that we could move it to a portable class library, but the namespace remained the same.  It now lives in `MyApp.DataModel.dll`.
I generated "wrap" project.json files for each of those libraries (`MyApp.DataAccess.Security.dll`, `MyApp.DataModel.dll`) and see both of them as referenced by the ASP.NET project.  
When I type `new MyApp.DataAccess.Security.` I only get classes from the `MyApp.DataAccess.Security.dll` and I do not get `MyApp.DataAccess.Security.User`.  Entering the full name only gives me a compile error.

Any help would be greatly appreciated.

I'm on VS 2015 Update 1 Community, with ASP.NET 5 RC1-Update 1.  I did not see a known issue filed against this -- sorry if I missed it.

**Comment by muratg** [comment]
Can you share your project.json for the web app? 

I also recommend trying out the new dotnet cli (https://github.com/dotnet/cli & https://dotnet.github.io) because we'll be retiring dnx, dnu and dnvm in favor of it in RC2.

**Comment by dythim** [comment]
Thank you!  Below are (in order) the project.json, the global.json, the "wrap" project.json of the project where the class I want lives, and the "wrap" of that project's only dependency.

**/src/MyApp.Hub.Net/project.json**
>{
>  "version": "1.0.0-*",
>  "compilationOptions": {
>    "emitEntryPoint": true
>  },
>
>  "dependencies": {
>    "Microsoft.AspNet.Identity": "3.0.0-rc1-final",
>    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
>    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
>    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
>    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
>    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
>    "NHibernate": "4.0.4.4000",
>  },
>
>  "commands": {
>    "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://*:5404"
>  },
>
>  "frameworks": {
>    "dnx451": {
>      "dependencies": {
>        "MyApp.DataAccess": "1.0.0-*",
>        "MyApp.DataAccess.Security": "1.0.0-*",
>        "MyApp.DataModel": "1.0.0-*",
>        "MyApp.DataModel.Licensing": "1.0.0-*",
>        "MyApp.GeoResource": "1.0.0-*",
>        "MyApp.PickLists": "1.0.0-*"
>      }
>    }
>  },
>
>  "exclude": [
>    "wwwroot",
>    "node_modules"
>  ],
>  "publishExclude": [
>    "**.user",
>    "**.vspscc"
>  ]
>}

**/global.json**
> {
>   "projects": [ "src", "test", "wrap" ],
>   "sdk": {
>     "version": "1.0.0-rc1-update1"
>   }
> }

**\wrap\MyApp.DataModel\project.json**
> {
>   "version": "1.0.0-*",
>   "frameworks": {
>     "net45": {
>       "wrappedProject": "../../../MyApp.DataModel/MyApp.DataModel.csproj",
>       "bin": {
>         "assembly": "../../../MyApp.DataModel/obj/{configuration}/MyApp.DataModel.dll",
>         "pdb": "../../../MyApp.DataModel/obj/{configuration}/MyApp.DataModel.pdb"
>       },
>       "dependencies": {
>         "MyApp.PickLists": "1.0.0-*"
>       }
>     }
>   }
> }

**\wrap\MyApp.PickLists\project.json**
> {
>   "version": "1.0.0-*",
>   "frameworks": {
>     "net45": {
>       "wrappedProject": "../../../MyApp.PickLists/MyApp.PickLists.csproj",
>       "bin": {
>         "assembly": "../../../MyApp.PickLists/obj/{configuration}/MyApp.PickLists.dll",
>         "pdb": "../../../MyApp.PickLists/obj/{configuration}/MyApp.PickLists.pdb"
>       }
>     }
>   }
> }

**Comment by muratg** [comment]
If you change the order of `MyApp.DataAccess.Security` and `MyApp.DataModel` (or remove the former) Do you get this type?

**Comment by dythim** [comment]
Re-ordering and removing both did not resolve the issue.  Even after closing and restarting Visual Studio.  So I guess the DataModel is not being imported correctly somehow.

It is a portable class library with the following targets:
.NET Framework 4.5
Silverlight 5
Windows 8
Xamarin.Android
Xamarin.iOS
Xamarin.iOS (Classic)

Inside the csproj file I have:
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile47</TargetFrameworkProfile>

**Comment by muratg** [comment]
I don't have much experience with the PCLs -- @bricelam do you think that may be the reason?

**Comment by bricelam** [comment]
Hmm, the wrap `project.json` may be getting picked up by the [NuGet MSBuild integration](https://github.com/NuGet/NuGet.BuildTasks) for PCL projects.

**Comment by dythim** [comment]
Is there anything I can do to check?
