### ISSUE TITLE
How to distinguish which I need: (Windows) Class Library or (Web) Class Library (Package)

### ISSUE THREAD

**Issue by nkhut10** [aspnet/dnx#3346]
Before I moved to Asp.Net 5 I used to create standard (Windows) Class Libraries (dlls) and then used them in my Asp.Net 4 Project as references. Now I am confused, should I do the same as before or start creating Class Library (Package) - s which are in "Web" section when creating a new project. Any ideas appreciated.

**Comment by muratg** [comment]
This issue was moved to aspnet/Tooling#387
