### ISSUE TITLE
"Failed to initialize runtime 0x"

### ISSUE THREAD

**Issue by booschie** [aspnet/dnx#3347]
On a Windows 7 32-bit, I perform the following installation steps, in order:

```
dnvm upgrade -r coreclr -a x86 -u
dnvm upgrade -r clr -a x86 -u
```

I try to run the following command:

```
dnu restore
dnu build
dnx run
```

an error **Failed to initialize runtime 0x** is displayed in console and the program quits

I tried to switch to coreclr by setting:
`dnvm use -r coreclr -arch x86 1.0.0-rc2-16357`

The dnx and dnu commands started to work. Unfortunately, the dnu/dnx binaries from the clr package still don't work. This prevents me from using Visual Studio Code to compile and run my application without changing the code to match the coreclr libraries.

**Comment by muratg** [comment]
Thanks @booschie.  In RC2, we're retiring dnx and dnu. New command line experience will be via dotnet cli (https://github.com/dotnet/cli, download: https://dotnet.github.io)  I recommend trying that out if you need to use current RC2 builds.  If you prefer to stay on RC1 and DNX, that's fine too. Desktop CLR should be working there.
