### ISSUE TITLE
System.Net.Security could not be loaded on arm machine 

### ISSUE THREAD

**Issue by jornbeyers** [aspnet/dnx#3355]
I'm experiencing the famous "System.Net.Security" issue on an arm machine.
The arm machine is a Raspberry PI which is running Windows IoT Core. 

When running the project on version 1.0.0-rc2-16357 on a x64 architecture, everything runs smooth. But when I publish the project and try to run it on the Raspberry PI, I’m facing the following error:

`Exception throwed in IoTHubAmqpConnection: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Security'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)` 

. I already combined the System.Net.Security with the Microsoft.NETCore.Platforms library but this doesn't work for me. Or should I use specific versions? My project.json looks like this:

```
{
  "version": "1.2.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Text.RegularExpressions": "4.0.11-beta-23516",
        "System.Xml.XmlSerializer": "4.0.11-beta-23516",
        "System.ComponentModel": "4.0.1-beta-23516",
        "System.Text.Encoding": "4.0.11-beta-23516",
        "System.Threading.Tasks": "4.0.11-beta-23516"
      }
    }
  },
  "dependencies": {
  },
  "configurations": {
  }
}

```

There already have been issues regarding System.Net.Security: #4533
It should have been resolved in RC2 builds as stated here #3183

**Comment by SamVanhoutte** [comment]
I was able to reproduce this one on my PI as well.

**Comment by muratg** [comment]
Could you guys try to do this with the new dotnet CLI?  DNX is being retired in RC2 and the new dev workflow will be through the new CLI.
