### ISSUE TITLE
Integration of xunit tests (xprojs) with visual studio online (TFS)

### ISSUE THREAD

**Issue by ip28** [aspnet/dnx#3360]
Hi Team,
 I don't see option to configure xunit unit tests for MVC 6 projects (xproj extension) in visual studio online.
I also couldn't find any relevant article explaining the same.
Can you please help me configure unit tests in vso?

![image](https://cloud.githubusercontent.com/assets/8371740/13105377/e5c5fece-d588-11e5-8d08-a0afaca27a65.png)

**Comment by muratg** [comment]
I recommend moving the question to dotnet/cli repo with more explanation.

DNX will be retired in RC2, and main compile/run/test workflow will be through the new dotnet CLI.
