### ISSUE TITLE
dnu build error with System.Web.Extensions

### ISSUE THREAD

**Issue by emfluenceindia** [aspnet/dnx#3362]
I get an error while compiling after added Framework Assembly System.Web.Extensions in my project.
The error says:

> D:\Projects\ColemanApi\src\ColemanApi\Controllers\ValuesController.cs(7,14): DNXCore,Version=v5.0 error CS0234: The type or namespace name 'Web' does not exist in the namespace 'System' (are you missing an assembly reference?)
D:\Projects\ColemanApi\src\ColemanApi\Controllers\ValuesController.cs(59,27): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'JavaScriptSerializer' could not be found (are you missing a using directive or an assembly reference?)

Build failed.

Project.json looks like this:

```json
"frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.AspNet.WebApi.Cors": "5.2.3"
      },
      "frameworkAssemblies": {
        "System.Web.Extensions": "4.0.0.0"
      }
    },
    "dnxcore50": { }
  },
```

dnu list command says the assembly has been resolved. Please see screenshot
![untitled3](https://cloud.githubusercontent.com/assets/11072678/13218553/685e99b2-d990-11e5-89f9-e76a2110df48.png)

**Comment by adamsitnik** [comment]
It seems like you added the dependencies for dnx451 which compiles, but the bulild failed for dnxcore50 (no dependencies defined)

**Comment by emfluenceindia** [comment]
Exactly! I have removed "dnxcore50" reference and project builds without any error now. But what should be the work around if I want to keep the reference in the project?

**Comment by adamsitnik** [comment]
It depends on which platforms the library that you would like use  supports. 
* If it supports both dnx451 and dnxcore50 then you just need to move the dependencies to common dependencies (same level as frameworks).
```
  "frameworks": {
    "dnx451": { },
	"dnxcore50": { }
  },
  "dependencies": {
	"someCommonDependency": "it's version"
  }
```
* If there are two different packages/version then you need to specify both dependencies in explicit way:
```
    "frameworks": {
    "dnx451": { 
		"dependencies": {
			"someCommonDependency": "exact version that supports dnx451"
	  }
    },
	"dnxcore50": { 
		"dependencies": {
			"someCommonDependency": "exact version that supports dnxcore50"
	  }
    }
  }
```

One of ways of checking which platforms are supported is visiting nuget package website. [Sample](https://www.nuget.org/packages/StackExchange.Redis/1.1.572-alpha)

Sorry for not giving you exact answer, but I am not familiar with these MVC packages to tell.

**Comment by emfluenceindia** [comment]
Thank you so much for your nice and elaborate reply Adam. I should be able to move on from here. :)

**Comment by muratg** [comment]
@adamsitnik :+1:
