### ISSUE TITLE
ASP.NET 5 - NETSH commands cause DNX error (determine the process id of the DNX)

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/dnx#3363]
I have problem with debugging of my ASP.NET 5 application after two powershell commands for subdomain debugging (Windows 10):

Here are my steps
•Application debugging working

•Powershell commands to enable subdomain debugging are:
Netsh http add urlacl url=http://tenant1.localhost:60903/ user=everyone
netsh firewall add portopening TCP 60903 IISExpressWeb enable ALL 

•Check to run application

•And here is comming this error message:
"An error occurred attempting to determine the 
process id of the DNX process hosting your application"

•powershell:
netsh http delete urlacl url=http://tenant3.localhost:60903/ 
netsh firewall delete portopening protocol=all port=60903

•Application run properly...

I have this problem only on my new Desktop. On my laptop with the same system (Windows 10) is this working properly... What can I do please?

http://stackoverflow.com/questions/35588574/asp-net-5-netsh-commands-cause-dnx-error-determine-the-process-id-of-the-dnx

**Comment by muratg** [comment]
@sayedihashimi @BillHiebert

**Comment by muratg** [comment]
@barrytang 

Is this more a WTE issue?

**Comment by muratg** [comment]
@barrytang 

Is this more a WTE issue?

**Comment by muratg** [comment]
This issue was moved to aspnet/Tooling#414
