### ISSUE TITLE
project.json version to support build metadata as described in SemVer 2.0.0

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#3365]
I am not sure which repo this is more suitable (dotnet-cli, NuGet, here). So, opening here to see.

Currently, `dnu` doesn't support versions with build metadata [as described in Semantic Versioning 2.0.0 spec](http://semver.org/#spec-item-10):

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

It gives me this:

```
➜  subscriber git:(master) ✗ dnu restore
Microsoft .NET Development Utility Mono-x64-1.0.0-rc1-16231

  CACHE https://nuget.org/api/v2/
Restoring packages for /home/tugberk/apps/web-client/src/subscriber/project.json
----------
/home/tugberk/apps/web-client/src/subscriber/project.json(0,0): Error: Microsoft.Dnx.Runtime.FileFormatException: '1.0.0+10' is not a valid vers
ion string.
Parameter name: version ---> /home/tugberk/apps/web-client/src/subscriber/project.json(2,16): Error: Microsoft.Dnx.Runtime.FileFormatException: 
'1.0.0+10' is not a valid version string.
Parameter name: version ---> System.ArgumentException: '1.0.0+10' is not a valid version string.
Parameter name: version
  at NuGet.SemanticVersion.Parse (System.String version) <0x419a9300 + 0x00133> in <filename unknown>:0 
  at NuGet.SemanticVersion..ctor (System.String version) <0x419a92c0 + 0x00017> in <filename unknown>:0 
  at Microsoft.Dnx.Runtime.ProjectReader.SpecifySnapshot (System.String version, System.String snapshotValue) <0x419a91b0 + 0x000e3> in <filenam
e unknown>:0 

```

**Comment by muratg** [comment]
@tugberkugurlu I think this should be tracked in dotnet/cli repo. We don't plan any more changes in DNX. 

Could you move this bug over and close?

**Comment by muratg** [comment]
@yishaigalatzer Should this be moved to nuget/home?

**Comment by tugberkugurlu** [comment]
I was going to ask the same :) let me know where and I can move this there.

Tugberk

**Comment by yishaigalatzer** [comment]
It's a mixed question.

Yes there is a nuget component, but we explicitly announced we are not supporting semver2 in the upcoming release. I'm also not sure about other things that read and understand this version in the build side of the world. So I would add this info to the semver2 issue in nuget and open a bug in the CLI as well.

At the end of the day servers don't support it yet either, so the value of quickly moving on this is lowish.

**Comment by muratg** [comment]
@tugberkugurlu What Yishai said I guess :)  Closing this one.
