### ISSUE TITLE
Enable control over thread pool minThreads

### ISSUE THREAD

**Issue by KKhurin** [aspnet/dnx#3368]
The current coreclr thread pool min threads & thread injection policy defaults aren't optimized for server loads. As the result we'll see very poor startup times and thread starvation. Add a way to control those defaults (when / if it gets exposed).

**Comment by benaadams** [comment]
dotnet cli issue now, add comments there, you can override with environment var https://github.com/dotnet/cli/issues/889#issuecomment-172975280

**Comment by KKhurin** [comment]
Yes, but I don't want every possible asp.net customer on planet to have to override the defaults themselves. I'd like the asp.net host to set the new defaults suitable for server loads.

**Comment by benaadams** [comment]
Yeah, just mean dnx is being discontinued and dotnet cli is replacing it; so you would want to give feedback on issue I linked rather than here

**Comment by davidfowl** [comment]
We don't have an asp.net host

**Comment by muratg** [comment]
Yeah, no more dnx changes are planned. We can continue the discussion on the [CLI issue](https://github.com/dotnet/cli/issues/889)
