### ISSUE TITLE
Question: Memory consumption of dnx.exe

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/dnx#3371]
Please, see the attached image of a few websites (rc1) I am running on my web server **Windows Server 2012 R2** server.

The websites are very similar and you can see the consumption is around **100MB** Memory (private working set).

Let's say, if my memory on the server is only 3GB, let's say 1GB for system, 1GB for SQL Server, and 1GB for the rest. 

1) Can I only have approx. **10** ASP.NET Core 1.0 websites?

2) How is working memory management for dnx.exe. If some of the websites are busy, and the others not would the one which are less busy release some memory?

3) What should be the minimum consumption of dnx.exe?

4) I wonder if I had these websites **20-30** hosted by any hosting company, would they be happy that each of my websites will take 100MB of the memory that is **2-3GB** of memory in this case scenario?

5) Saying that, if I had **Azure VM** we cannot even increase only the memory of VM we had to always increase including processors and so on so the overall cost will increase.

6) Isn't **dnx.exe** _memory hungry_, so the hosting might be more expensive or it is just not correct observation I am doing.

Thank you for any light on this :)

![image](https://cloud.githubusercontent.com/assets/4528464/13433617/91c88b74-dfca-11e5-8ad7-0c594f528d5a.png)

**Comment by GuardRex** [comment]
Four small informational website apps under `netstandardapp1.5` & `dotnet cli` running latest bits:

IIS Worker Processes: ~4 MB each
Application Executables: ~40-60 MB each
Console Window Hosts: ~200-400 KB each

**Comment by VaclavElias** [comment]
Thanks for sharing @GuardRex. I have added additional information to the screen shot. I use only one IIS Worker Process. Should I use a separate worker for each website? That will be even more memory used? :)

**Comment by GuardRex** [comment]
@VaclavElias It's the current guidance https://docs.asp.net/en/latest/hosting/apppool.html, but there are some significant changes coming in the `dotnet cli` world in terms of how the runtime/packages are hosted. There will be a standalone/fully-isolated approach and a shared/un-isolated approach, so there might be changes in regard to the usual advice about having one AppPool per app under the un-isolated approach.

Those are great questions that you asked :+1: You might want to move this issue over to Hosting repo issues. @Elion will know where this goes.

Although the footprint seems a little lighter with these apps I have running compared to what you show there, they really are small apps that I have here, so I have the same concern you do.

**Comment by VaclavElias** [comment]
Thanks again @GuardRex for the additional information. 

Not a problem at all. I will test and implement new coming bits accordingly. 

I don't know how to move things around so I shall leave it for the guys here in asp.net to do it or I should do it manually, as a new issue?

**Comment by GuardRex** [comment]
You can do it ... just open a new issue elsewhere ... close this one ... put the link to this one in the new one. The only question is ... which repo is the best spot? Maybe a team member will jump in and say where the best place for this is.

**Comment by muratg** [comment]
@VaclavElias I think Hosting repo may be a better place to have this discussion.

**Comment by VaclavElias** [comment]
Moved as suggested to https://github.com/aspnet/Hosting/issues/623.

Thanks.

**Comment by Elion** [comment]
Why do I have to talk about your PowerShell 3 ? 
Dnia 1 marca 2016 18:36 Vaclav Elias &lt;notifications@github.com&gt; napisał(a):
Thanks again @GuardRex for the additional information.Not a problem at all. I will test and implement new coming bitsaccordingly.I don&#39;t know how to move things around so I shall leave it forthe guys here in asp.net to do it or I should do it manually, as anew issue?—

**Comment by Eilon** [comment]
@Elion pretty sure they meant me :smile: A common typo. If you ever see random stuff come your way, it was probably meant for me :smile:
