### ISSUE TITLE
Cannot compile System.Net.Sockets

### ISSUE THREAD

**Issue by ddobric** [aspnet/dnx#3372]
Hi all,

trying to compile System.Net.Sockets. It fails with errors:

"System.Net.NameResolution 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
System.Security.Principal.Windows 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0."

..build output...

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Detected package downgrade: System.Collections from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.IO.FileSystem (≥ 4.0.0) -> System.Collections (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Collections (≥ 4.0.0)
Detected package downgrade: System.Collections from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.Net.Primitives (≥ 4.0.10) -> System.Private.Networking (≥ 4.0.0) -> System.Collections (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Collections (≥ 4.0.0)
Detected package downgrade: System.Globalization from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.Net.Primitives (≥ 4.0.10) -> System.Private.Networking (≥ 4.0.0) -> System.Globalization (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Globalization (≥ 4.0.0)
System.Net.NameResolution 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
System.Security.Principal.Windows 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
Some packages are not compatible with DNXCore,Version=v5.0.
The project 'System.Net.Sockets' does not specify any target frameworks in 'C:\tfs\git\corefx\src\System.Net.Sockets\ref\project.json'.
NuGet package restore failed.
1>------ Rebuild All started: Project: System.Net.Sockets (src\System.Net.Sockets), Configuration: Windows_Debug Any CPU ------
1>  System.Net.Sockets -> C:\tfs\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.Sockets\System.Net.Sockets.dll

Thanks
Damir

**Comment by muratg** [comment]
@davidfowl Why did you reopen?

**Comment by muratg** [comment]
@ddobric Please open in CoreFX (with more details in how you repro)
