### ISSUE TITLE
Support for outputPath in prepublish/postpublish scripts

### ISSUE THREAD

**Issue by mariuszjamro** [aspnet/dnx#3374]
Currently there is no way to get the output directory path when executing prepublish/postpublish scripts. 

I propose to add it to the `PublishManager`, so that users can add `%outputPath%` variable to their scripts, just the same way as `%project:Directory%`, `%project:Name%`.

This will look for example like this:

    "scripts": {
         "prepublish": [ "dir %outputPath%" ]
    }

The variable holding the path is already defined in [`PublishManager`:](https://github.com/aspnet/dnx/blob/819a6e603b0f43ef1a9da539ecc8ecc29a16bdbc/src/Microsoft.Dnx.Tooling/Publish/PublishManager.cs#L93-L93)

    string outputPath = _options.OutputDir;

I believe it's only a matter of adding it to the [`getVariable`](https://github.com/aspnet/dnx/blob/819a6e603b0f43ef1a9da539ecc8ecc29a16bdbc/src/Microsoft.Dnx.Tooling/Publish/PublishManager.cs#L107-L110):

    Func<string, string> getVariable = key =>
    {
       # return outputPath for key = 'outputPath'
    };

    #(...)

    if (!ScriptExecutor.Execute(project, "prepublish", getVariable))
    {
         _options.Reports.Error.WriteLine(ScriptExecutor.ErrorMessage);
         return false;
     }

**Comment by moozzyk** [comment]
`dnx/dnu` are being replaced with `dotnet`. `dotnet publish` has a variable containing the [ouptut path](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L99-L104)

**Comment by mariuszjamro** [comment]
Awesome, thanks!
