### ISSUE TITLE
DNX doesn't properly restore transitive dependencies when using netstandard/netstandardapp

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/dnx#3375]
https://github.com/aspnet/dnx/pull/3367#issuecomment-191286135

**Comment by muratg** [comment]
@PinpointTownes dnu removing nuspec on the depencies is the issue? (if so, @pakrym's last check-in should fix it) If not, can you clarify?

**Comment by PinpointTownes** [comment]
@muratg yep, looks like @pakrym's last commit fixed the issue :clap:
