### ISSUE TITLE
Parallel publishing with DNX RC1

### ISSUE THREAD

**Issue by avinhan** [aspnet/dnx#3377]
Hello,

We have a project in which there are multiple web applications and shared libraries in the src folder. Our publish workflow has been,
1) Do a dnu restore at the root
2) run dnu publish for each web app and pass an output directory.

This takes some time to publish each project individually so we tried to run all publishes in parallel (we are using sake for the builds on a windows machine). This however fails with a file in use error. Seems like it has a lock on a shared project's dll in the bin folder. We are able to run 'dnu build' and 'dnu pack' in parallel without any issues. 

This issue only happens with our dll's and not with other dnx packages which are also being copied from the %DNX_HOME%packages.

Is it possible to run publish in parallel? Can we run dnu build beforehand and just get the publish to copy out files?

**Comment by muratg** [comment]
DNX/DNU is retired in RC2. Please do any necessary follow-up on dotnet CLI repo (https://github.com/dotnet/cli)
