### ISSUE TITLE
Support NETCoreApp1.0...

### ISSUE THREAD

**Issue by muratg** [aspnet/dnx#3378]
Just like we supported netstandard and netstandardapp. 

See https://github.com/dotnet/cli/pull/1810

cc @anurse @Eilon @NTaylorMullen @pranavkm

**Comment by muratg** [comment]
See the corresponding NuGet change here: https://github.com/NuGet/Home/issues/2299

**Comment by pranavkm** [comment]
Is this essentially an alias for `netstandardapp1.5`?

**Comment by muratg** [comment]
I think so, but @anurse can confirm.

**Comment by anurse** [comment]
I believe it's not an alias, it's a different thing. We want to hold `netstandardapp1.5` as something we could use in different ways later. /cc @DamianEdwards

**Comment by pranavkm** [comment]
Would we need to rename `netstandardapp1.5` -> `netcoreapp1.0` in our project.jsons as a follow up to this?

**Comment by muratg** [comment]
Also cc @emgarten

**Comment by anurse** [comment]
@pranavkm Yep

**Comment by DamianEdwards** [comment]
`netcoreapp1.0` is the successor to `dnxcore50`. `netstandard1.x` and `netstandardapp1.x` are completely new concepts that are functionally equivalent to each other for now.

**Comment by muratg** [comment]
@DamianEdwards https://github.com/NuGet/Home/issues/2299#issue-140029596 

*... a new TFM called "netcoreapp" currently with only one version "netcoreapp1.0" which maps to netstandard1.5*

**Comment by GuardRex** [comment]
Will `netcore1.0` be for packages?

Side note ... plz let us know when these latest updates are on the CI feed & `dotnet cli`-ready. I froze packages to ride out the changes, but I'd like to unfreeze and get in on this action asap.

**Comment by DamianEdwards** [comment]
@GuardRex `netcoreapp1.0` (note the `app` in there) represents applications running on/via the .NET Core CLI infrastructure (which is CoreCLR and some number of libraries, just like `dnxcore50` was). Libraries are free to target this TFM if they need API that only works in these app types, otherwise we'll be encouraging libraries to target `netstandard1.x` for the widest compatibility.

**Comment by GuardRex** [comment]
Gotcha ...

`netcoreapp1.0` for Core CLR apps
`netstandard1.5` for Core CLR packages (as it is now)

**Comment by GuardRex** [comment]
I'll go back and re-read the latest wiki docs on the plan. Note ... it's a bit confusing! ... but I'll get it.

**Comment by DamianEdwards** [comment]
@GuardRex basically, yeah. There are more docs coming very soon for this stuff, some of the ones that are public might be out of date with the absolute latest bits in GH repos as we're still working through this ourselves.

**Comment by DamianEdwards** [comment]
Also note that `netstandard1.5` will be supported by .NET Framework 4.6.2, it's not just about Core CLR.

**Comment by anurse** [comment]
The **app** in `netcoreapp` is definitely important. Unfortunately `netcore` is already taken and is an alias for `win` ;). `netcore45` maps to `win8`, `netcore451` maps to `win81`, and `netcore50` maps to `uap10.0`

**Comment by pakrym** [comment]
This was done but support if far from full, dnx run, restore, test are not working correctly for portable apps.

**Comment by GuardRex** [comment]
@pakrym @anurse @ericstj I'm still working with standalone apps (`win8-x64` RID). It looks like `netcoreapp1.0` with `-rc2-*` packages and with `NETStandard.Library 1.0.0-*` runs ok. With either `NETStandard.Library 1.5.0-*` or adding in one of my NuGet packages, it breaks (that's open at https://github.com/aspnet/Razor/issues/718).

May I ask for a few clarifications at this point? No rush ... "wait" is fine ... "idk" is fine ... just asking ...

1. Should I stay on `NETStandard.Library 1.0.0-*` or move to `1.5.0-*` at some point? Seems like I should use the latest; but thus far, it breaks with `netcoreapp1.0`. If I will move to `1.5.0-*`, how will I know when to do that?
2. What's the current status of `imports` on the TFM? When `"imports": [ "dnxcore50", "portable-net45+win8" ]` is removed from `netcoreapp1.0`, I get a lot of packages not ready for it ... e.g., `error: System.Diagnostics.TraceSource 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.`. We'll have `imports` around for a while, correct? Is the best way to get a "poor man's progress report" to just remove it and see how many packages choke? ... eventually that should dwindle down to a fully restoring app without the `imports` on the TFM, correct?
3. I'm still having difficulty getting a straight answer on which RID's to use with which Windows Server platforms. I thought that `win8-x64` would be a WS 2012/R2-ish sort of RID, while `win10-x64` would be a WS 2016/Nano-ish sort of RID; but apparently from what I've gathered on JabbR that isn't true. They produce different outputs, but there is no guidance on what to use for the standalone app situation with WS. Can you shed any light on that?

**Comment by ericstj** [comment]
>  it breaks (that's open at aspnet/Razor#718).

I put a workaround in today's build to address that problem until the whole stack can get on the latest packages: https://github.com/dotnet/corefx/commit/0f268ed1079c182d71cdf49cde3f339a01d67863

> Should I stay on NETStandard.Library 1.0.0-* or move to 1.5.0-*

/cc @weshaggard You should be able to move now.  All that was done was change the major.minor version of this package.  We're only building one version, so using 1.0.0 means you are on old builds.

> What's the current status of imports on the TFM?

It should work without import.  

>error: System.Diagnostics.TraceSource 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0

That's an old package

> which RID's to use with which Windows Server platforms

We haven't created separate RIDs for Server.  The main differences between the Windows version RIDs as used by the CoreFx packages are as follows;
win7 - contains the most API set dlls since none were inbox
win8/win81 - contains fewer API set dlls since some were inbox, also enables a couple WindowsRuntime packages that are only supported on Win8 and later
win10 - contains API set dlls since almost all are inbox.  Right now this RID should only be used by UWP apps since there is a case with CLRCompression where we package the appx DLL under this RID.

The intent is that apps will be compatible with future versions, so if you did a standalone app for Win7 it will still work when upgraded to Win8, and so-forth.  However, do to the size of the app (number of DLLs for all those API sets) you might want to use the RID for your minimally supported platform.
Server 2012 > Win8
Server 2012 R2 > Win81
I'd avoid using the Win10 RID for now.

**Comment by GuardRex** [comment]
Thank you so much for this info. Very helpful.

**Comment by GuardRex** [comment]
@ericstj Regarding dropping the `imports` from `netcoreapp1.0`. For my package ...
```json
{
"dependencies": {
    "NETStandard.Library": "1.5.0-*",
    "System.Net.Http": "4.0.1-*"
},
"frameworks": {
    "netcoreapp1.0": {}
},
"runtimes": {
    "win81-x64": {}
}
```
... I do not need the `imports`. The package restores and `dotnet pack`'s-up fine. For app that consumes the package ...
```json
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "NETStandard.Library": "1.5.0-*",
    "razor_issue_pkg": "1.0.0"
},
"frameworks": {
    "netcoreapp1.0": {}
},
"runtimes": {
    "win81-x64": {}
},
```
I'm still getting many errors when I attempt to drop `"imports": [ "dnxcore50", "portable-net45+win8" ]`. With the `imports` all is well ... full restore and it compiles fine.

Errors without `imports` ...
```
Errors in c:\_APPLICATIONS\razor_issue_app\project.json
    System.Diagnostics.TraceSource 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Threading.ThreadPool 4.0.10-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Numerics.Vectors 4.1.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Reflection.TypeExtensions 4.1.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Text.Encodings.Web 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.ComponentModel 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Linq.Expressions 4.0.11-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Diagnostics.StackTrace 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.ComponentModel.Annotations 4.1.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Threading.Tasks.Parallel 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Runtime.Loader 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0.
    Newtonsoft.Json 8.0.3 is not compatible with .NETCoreApp,Version=v1.0.
    System.Net.WebSockets 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Diagnostics.Contracts 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Dynamic.Runtime 4.0.11-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Resources.Reader 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    Microsoft.CSharp 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.ComponentModel.TypeConverter 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Runtime.Serialization.Primitives 4.1.0 is not compatible with .NETCoreApp,Version=v1.0.
    Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0.
    System.Security.Claims 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Security.Principal 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Collections.Immutable 1.1.37 is not compatible with .NETCoreApp,Version=v1.0.
    System.Reflection.Metadata 1.1.0 is not compatible with .NETCoreApp,Version=v1.0.
    Microsoft.Win32.Registry 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    System.Security.Principal.Windows 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0.
    Some packages are not compatible with .NETCoreApp,Version=v1.0.
    System.Diagnostics.TraceSource 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Threading.ThreadPool 4.0.10-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Numerics.Vectors 4.1.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Text.Encodings.Web 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.ComponentModel 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Linq.Expressions 4.0.11-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Reflection.TypeExtensions 4.1.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.ComponentModel.Annotations 4.1.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Threading.Tasks.Parallel 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Runtime.Loader 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Newtonsoft.Json 8.0.3 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    runtime.win7.System.Diagnostics.TraceSource 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Diagnostics.StackTrace 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Net.WebSockets 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Diagnostics.Contracts 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    runtime.any.System.Linq.Expressions 4.0.11-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    runtime.any.System.Reflection.TypeExtensions 4.1.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Resources.Reader 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Microsoft.CSharp 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.ComponentModel.TypeConverter 4.0.1-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Runtime.Serialization.Primitives 4.1.0 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Dynamic.Runtime 4.0.11-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Collections.Immutable 1.1.37 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    System.Reflection.Metadata 1.1.0 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Microsoft.Win32.Registry 4.0.0-rc2-23826 is not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
    Some packages are not compatible with .NETCoreApp,Version=v1.0 (win81-x64).
```
.NET Command Line Tools (1.0.0-beta-001937)

Product Information:
 Version:     1.0.0-beta-001937
 Commit Sha:  3616378130

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

`NuGet.config` ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
    <add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
    <add key="LocalPkg" value="C:\_APPLICATIONS\razor_issue_pkg\bin\Release" />
  </packageSources>
</configuration>
```

**Comment by ericstj** [comment]
@GuardRex looks like you're picking up old packages `rc2-23826`.  The latest on dotnet-core feed is `rc3-23923`.

**Comment by GuardRex** [comment]
@ericstj nuke the cache and try restore again?

**Comment by ericstj** [comment]
Looks like the ASP.NET packages are still bringing in old packages that don't support 'netstandard' moniker.  When you use * it only chooses latest direct references, indirect are still whatever was referenced by direct referenced packages.  You need a newer build of ASP.NET that references the latest packages.

Previously we (CoreFx) would try to unify all the packages to a single version/build with entries in the runtime.json, however ASP.NET and NuGet both didn't like this and it caused issues like https://github.com/dotnet/corefx/issues/6603 as well as upset folks who wanted more control of getting exactly the version referenced by their packages.  As a result we stopped doing this.   What that means during pre-release is that you have to be more careful about mixing/matching builds.

One thing you could try is directly referencing the latest build of all packages with something like https://gist.github.com/ericstj/2cda9163e22016893733.  When doing this I see that only the following errors:
```
    Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0.
    Newtonsoft.Json 8.0.3 is not compatible with .NETCoreApp,Version=v1.0.
    Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with .NETCoreApp,Version=v1.0.
```
That leaves us with Roslyn and JSon.NET as the only packages still requiring an import.  I believe Roslyn is working on this now: https://github.com/dotnet/roslyn/issues/9891.

**Comment by GuardRex** [comment]
@ericstj I see. This has turned out after all (and along with the package downgrade issue) to be just a work-in-progress situation.

I'll do as you suggest and work more directly with matching latest packages. Regarding the `importsperforming a "poor man's import test" by just keeping the `imports` while I'm still getting "not compatible" mentions. It looks like those will just melt away eventually, leaving me with packages/apps that restore just fine.

**Comment by GuardRex** [comment]
![esj](https://cloud.githubusercontent.com/assets/1622880/13991133/2ddc7f42-f0d4-11e5-9ddc-fb9205089508.png)
