### ISSUE TITLE
dnu publish fails if path length exceeds 260 characters

### ISSUE THREAD

**Issue by JustHereForTheBugReport** [aspnet/dnx#3380]
When I invoke `dnu publish MyProject` I get an error message about path lengths having to be less than 260 characters:

> Error: The specified path, file name, or both are too long. The fully qualified
> file name must be less than 260 characters, and the directory name must be less
> than 248 characters.

Can we please put the 260 character issue behind us in the final release of aspnet core?

**Comment by Eilon** [comment]
@JustHereForTheBugReport the `dnu` command is being replaced with the new .NET CLI, so I recommend trying that out, and if there's still an issue, log it here: https://github.com/dotnet/cli/
