### ISSUE TITLE
How can I install this dnx on windows server 2003

### ISSUE THREAD

**Issue by lmxin123** [aspnet/dnx#3382]
How can I install this dnx on windows server 2003,I have install dnvm on win2003,but I can run dnx.exe on win2003.It have an error “approot\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe Is not a valid Win32 Application”.
The following is my version of the operating system information
![_20160315115554](https://cloud.githubusercontent.com/assets/12029452/13767399/d384b698-eaa4-11e5-9a19-0a9e624c9d41.png)

**Comment by BrennanConroy** [comment]
I think Windows Server 2003 is too old for DNX, oldest version I've seen it on is Windows 2008 R2

**Comment by victorhurdugaci** [comment]
Sorry but Windows 2003 is not supported. Win 2008 R2 and Win7  are the oldest versions of Windows that we support.
