### ISSUE TITLE
dnx web command failing to run on rc2 

### ISSUE THREAD

**Issue by Challagolla** [aspnet/dnx#3383]
I am trying to use the dnx web command on my project and i am getting the following error. 
The dnx version on my machine is **1.0.0-rc2-16591   clr     x86          win**. Can someone please suggest me on how to fix this problem?

_C:\Users\Suneel\Documents\Visual Studio 2015\Projects\TestPublish\src\TestPublish>dnx web
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.ILibrary
Manager Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_LibraryManager()'.
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCoreServices
(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServic
eCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServic
eCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollect
ion services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollect
ion services)
   at TestPublish.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Suneel\Document
s\Visual Studio 2015\Projects\TestPublish\src\TestPublish\Startup.cs:line 52_

**Comment by davidfowl** [comment]
Why are you using rc2? Did you update all of your dependencies to some version of RC2?

**Comment by Challagolla** [comment]
@davidfowl  We started building a project on rc2. all my dependencies are of rc2 version.

**Comment by davidfowl** [comment]
Can you provide a sample project with repro instructions on github? I'd like to run it for myself. It's clearly a dependency mismatch somewhere.

**Comment by Challagolla** [comment]
@davidfowl  please find the sample project which is giving the same error as mentioned about at the repository https://github.com/Challagolla/TestDnxWeb

please let me know if you think that i am missing anything.

**Comment by Challagolla** [comment]
@davidfowl We are using OpenIddict.Core  package to generate JWT tokens. This package has dependencies of rc2. So, we are using rc2.

**Comment by davidfowl** [comment]
How did you pick those individual versions? Why not use * for all dependencies or use the same build numbers for the things that ASP.NET produces? We have aligned build numbers now.

**Comment by Challagolla** [comment]
@davidfowl  I changed the versions to * and now i am getting the following error when running the dnx web command. This is coming from the main method. we are currently using WebApplicationBuilder class in the main method. Is this correct?  could you please suggest the best way for the entry point of the application when we use the rc2.

_C:\Users\Suneel\Documents\Visual Studio 2015\Projects\TestPublish\src\TestPublish>dnx web
System.TypeLoadException: Method 'Log' in type 'Microsoft.Extensions.Logging.Logger' from assembly '
Microsoft.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' doe
s not have an implementation.
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at Microsoft.AspNet.Hosting.WebApplicationBuilder..ctor()
   at TestPublish.Startup.Main(String[] args) in C:\Users\Suneel\Documents\Visual Studio 2015\Projec
ts\TestPublish\src\TestPublish\Startup.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, ISer
viceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()_

**Comment by davidfowl** [comment]
You're mixing RC1 and RC2 packages. I suggested you spend some time reading the annoucements for breaking changes https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by Challagolla** [comment]
@davidfowl Now, i understand this and moved all the packages to latest RC2 version and successfully build this. Thanks for the information
