### ISSUE TITLE
xproj, DNX and msbuild recompilation without any changes

### ISSUE THREAD

**Issue by xoofx** [aspnet/dnx#3384]
Hi,
Not sure if there was an issue already for this, sorry if it has already been reported.
After migrating some of my projects to use xproj and DNX, I noticed that when re-compiling a project, it seems to recompile everything even if nothing has changed. When targeting multiple platforms, it takes several seconds to re-compile a project, quite annoying...

From the `Microsoft.DNX.targets` file, It looks like DNX is not cooperating with MSBUILD in order to provide the list of input files that it used to compile the project (and output files so that msbuild knows what to check) so that msbuild doesn't retrigger DNX if nothing changed.

Is this a known issue? Is there a plan to improve this?

**Comment by davidfowl** [comment]
It's fixed in RC2 with the .NET CLI, the builds are incremental.

**Comment by xoofx** [comment]
Oh! good to hear that it will be part of the .NET CLI! I'm not using the command line, only building from VS. Will follow more closely .NET CLI. Thanks!
