### ISSUE TITLE
Where are project DLL's located?

### ISSUE THREAD

**Issue by WillRay** [aspnet/dnx#3388]
When debugging the application by running from Visual Studio, where are the DLL files located for the compiled application?

There doesn't appear to be a bin folder in the project itself, and the artifacts folder at the root has no DLL files in it until I publish the application.

My apologies if I have asked this in the wrong repo.

**Comment by davidfowl** [comment]
> When debugging the application by running from Visual Studio, where are the DLL files located for the compiled application?

DNX does dynamic compilation, nothing is on disk.

> There doesn't appear to be a bin folder in the project itself, and the artifacts folder at the root has no DLL files in it until I publish the application.

Yep.

**Comment by WillRay** [comment]
Ahh, thanks so much @davidfowl!
