### ISSUE TITLE
Visual studio publish project is not working after upgrading to 1.0.0-rc2-20222 clr x86.

### ISSUE THREAD

**Issue by codinesh** [aspnet/dnx#3390]
Hi Team,

We are working on a web application using rc2 and have migrated all dlls in our project to target latest dnx version and upgraded to 1.0.0-rc2-20222 clr x86. After upgrading I am able to build the project and start the project using 'dnx web' command. 

But when I try to publish the project from Visual Studio, publish fails with below error message.

Error:*_The project being published does not support the runtime 'dnx-clr-win-x86.1.0.0-rc2-20222'  *_

Please help me fix this issue.

**Comment by muratg** [comment]
@codinesh DNX is being retired, and the replacement is dotnet CLI (https://github.com/dotnet/cli). Unfortunately there's no public VS tooling with support for dotnet CLI, so this is a point in time issue.

Once RC2 is released, you should be able to do publish from VS.  For now, I recommend other avenues for deployment.
