### ISSUE TITLE
Missing DbProviderFactories.GetFactory

### ISSUE THREAD

**Issue by fitzchak** [aspnet/dnx#3391]
We are missing the DbProviderFactories.GetFactory() from DNX, which means that we cannot support any other database other than SQL Server.

Can you tell us what are plans regards supporting this?

Also we miss the DbCommandBuilder class which we use the method GetParameterName through reflection and the QuoteIdentifier. method.

**Comment by smbecker** [comment]
Your question would be better served on [dotnet/corefx](https://github.com/dotnet/corefx) repository, specifically in [dotnet/corefx#5782](https://github.com/dotnet/corefx/issues/5782)

**Comment by Eilon** [comment]
Yep, please refer to the linked issues. Thanks!
