### ISSUE TITLE
Update Microsoft.Dnx.TestHost to react to logging changes.

### ISSUE THREAD

**Issue by soeron** [aspnet/dnx#3393]
Greetings,
After the changes to the logging interfaces are made they are not reflected to the Microsoft.Dnx.TestHost packages, which results in failing test discovery when using xunit.runner.aspnet.

```
System.TypeLoadException: Method 'BeginScope' in type 'TestHostLogger' from assembly 'Microsoft.Dnx.TestHost, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

This is the error I get in Visual Studio 2015U2.
If it is possible this package to target net451 like the rest of the packages would be wonderful too. The version used is rc-20221 because aspnet.runner.aspnet depends on it, but rc2-20222 doesn't have the implementation either.

Edit:
And since I can't file a bug at xunit.runner.aspnet, updating that package is necessary too.

**Comment by pranavkm** [comment]
cc @BrennanConroy
