### ISSUE TITLE
DNX app/Angular2 does not keep the routes in memory

### ISSUE THREAD

**Issue by Abdelkrim** [aspnet/dnx#3395]
source of the question: http://stackoverflow.com/questions/36464020/microsoft-dnx-application-angular2-does-not-run-when-deployed-on-azure

in short: 
1. I have followed this tutorial describing how to build an ASP.NET MVC app using Angular2 and typescript https://ievangelistblog.wordpress.com/2016/01/13/building-an-angular2-spa-with-asp-net-5-mvc-6-web-api-2-and-typescript-1-7-5/
2. the menu is correctly displayed using local iisexpress or kestrel servers
3. the same menu isn't displayed when the app is deployed on azure

you will find package.json, typings.json, project.json and package.json files on stackoverflow

**Comment by muratg** [comment]
I see the menu on the app deployed on Azure: http://marketresearchio.azurewebsites.net/index.

Do you still have the problem?

**Comment by muratg** [comment]
Not sure if this is a problem still.  Placing in backlog for now

**Comment by Abdelkrim** [comment]
the answer is finally the following: some niminifed js files break the code. 

**I had to deploy the un-minified versions of the code and the app worked!**
