### ISSUE TITLE
Build project doesn't update the embedded resource files

### ISSUE THREAD

**Issue by mzaatar** [aspnet/dnx#3396]
Hello,

It wasted more than one hour from my time to discover.
If you add a script/text files in your DNX ASP project and update that file. Build the project doesn't update this script file in the generated dll. So you have to rebuild or clean/build the solution.

In old versions, you can specify how do you want to handle this file to be updated. Now, it is not updated and you can't discover that!

**Comment by muratg** [comment]
@mzaatar Thanks for the report. DNX is being retired in RC2 to be superseded by dotnet CLI (https://github.com/dotnet/cli)  Please give it a shot to see if your scenario is fixed there, and if not, feel free to file a bug there as well.
