### ISSUE TITLE
Update to Roslyn 1.3.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#3397]
We need to compile DNX against Roslyn 1.3.0 binaries to allow the latest builds of Mvc to work with DNX.

**Comment by pranavkm** [comment]
I ran into some issues compiling DNX that I'm not super sure how to resolve. @davidfowl 's volunteered to sort it out.

**Comment by sepplK** [comment]
is there a workarround yet? unable to return a view in rc2-20466 or later.

**Comment by davidfowl** [comment]
Not yet, it's a little tricky

**Comment by rsbavaresco** [comment]
@skoenigpi It works if you compile with .Net Core Cli

**Comment by muratg** [comment]
@davidfowl are you doing anything with this? If not, could you close?

**Comment by davidfowl** [comment]
Naw this isn't happening

**Comment by pranavkm** [comment]
@Eilon would like me to take a stab at this. Try using dotnet restore to build dnx.
