### ISSUE TITLE
AVG Detect dnx runtime is unknown

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [aspnet/dnx#3403]
![image](https://cloud.githubusercontent.com/assets/17920962/14663606/6f2ad1c0-06e0-11e6-8795-4729a1893fe6.png)

Windows 10

AVG 2016 Internet security

**Comment by blowdart** [comment]
Well that's fun. Unknown is rather helpful. This is obviously a false positive.

**Comment by Eilon** [comment]
We've seen a number of false-positives from various security products. All of DNX/ASP.NET/EF is virus scanned and Authenticode-signed.

**Comment by blowdart** [comment]
AVG have updated their detection, and this should be fixed in an update available today,

**Comment by ghingyi** [comment]
It's not fixed yet.
