### ISSUE TITLE
dnu publish cannot access the file "..../Autofac.4.0.0-rc1-177.nupkg"

### ISSUE THREAD

**Issue by mrahhal** [aspnet/dnx#3406]
Autofac is not special here, the first package alphabatically in the temp publish directory cannot be accessed a lot of the times when doing a `dnu publish`. The problem appears to be random.

This is really frustrating, sometimes it just keeps on happening for a whole 15 minutes. I found other people with the same problem but I didn't find a solution or a workaround.

**Comment by muratg** [comment]
We're not planning to make any changes to dnvm/dnx/dnu as we are retiring dnx in RC2.
