### ISSUE TITLE
Guidance for using ASP.NET Core 1 with net45 dependencies in RC2 - how to target Mono?

### ISSUE THREAD

**Issue by kcd83** [aspnet/dnx#3415]
So `dnx45` was a great middle ground where we could build projects that were both ASP.NET MVC 6 and cross platform, but used the dependencies we need (nuget packages for database, message bus, serialisation etc etc).

The dotnet CLI and `netstandard` are only CLR based (see the docker images), which may be the future, but is not an option for however many months it will take for the likes of `MongoDB` to update their drivers.

Is the best alternative to go back to mono and `net451` but use Kestrel? Can we target `netstandard` import `dnx451` and slap in missing libraries? Any advice or do we just come back to this when RTM sorts it all out.

**Comment by davidfowl** [comment]
dnx45x was on xplat _was_ mono. Now you have to use net45x, it's really no different from dnx, just that it's vanilla mono.

**Comment by kcd83** [comment]
Yes correct, so I guess it is a question of tooling not the underlying framework. Feel free to label this "discussion"

**Comment by vassilvk** [comment]
@davidfowl - I am porting an ASP.NET 5 RC1 application which used to run on Docker image **1.0.0-rc1-update1:latest** [from here](https://github.com/aspnet/aspnet-docker) to the new [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) Docker image.

I'm trying to understand what you mean by "Now you have to use net45x, it's really no different from dnx, just that it's vanilla mono."

Do you mean that a project which referred to framework `dnx451` and used to run in an [aspnet-docker](https://github.com/aspnet/aspnet-docker) container, will run with no issues in a [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) container by simply changing the target framework to `net451`?

I know my question skews things towards Docker, but I think this is relevant to the discussion as `dnx451` was a popular option for running stuff in the official RC1 Docker image.
