### ISSUE TITLE
Error	CS0433	The type 'SecureString' exists in both 'System.Security.SecureString, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' DNX 4.5.1.0	

### ISSUE THREAD

**Issue by Bibo1978** [aspnet/dnx#3416]
after last upgrade to rc1-update2 I am getting this error

> Error CS0433  The type 'SecureString' exists in both 'System.Security.SecureString, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'  .DNX 4.5.1.0    

I am using 

> dnvm use 1.0.0-rc1-update1 -r clr -arch x64 -p

Project .json looks like this

> {
> 
>   "buildOptions": {
>     "emitEntryPoint": true
>   },
> 
>   "dependencies": {
>     "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
>     "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
>     "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
>     "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
>     "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
>     "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
>     "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
>     "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
>     "Microsoft.AspNet.Mvc.ViewFeatures": "6.0.0-rc1-final",
>     "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
>     "Microsoft.AspNet.Localization": "1.0.0-rc1-final",
>     "System.Security.SecureString": "4.0.0-beta-23409",
>     "System.Runtime": "4.0.21-beta-23516",
>     "System.Runtime.InteropServices": "4.0.21-beta-23516",
>     "Newtonsoft.Json": "8.0.3",
>     "Microsoft.AspNet.Http": "1.0.0-rc1-final",
>     "Microsoft.AspNet.Session": "1.0.0-rc1-final",
>     "Microsoft.Extensions.Caching.Memory": "1.0.0-rc1-final",
>     "System.Net.Primitives": "4.0.11-beta-23516"
>   },
> 
>   "commands": {
>     "web": "Microsoft.AspNet.Server.Kestrel",
>     "ef": "EntityFramework.Commands"
>   },
> 
>   "frameworks": {
>     "dnx451": {
>       "dependencies": {
>       .....
> 
> ```
>   }
> }
> ```
> 
>   },
> 
>   "exclude": [
>     "wwwroot",
>     "node_modules"
>   ],
>   "publishExclude": [
>     "**.user",
>     "**.vspscc"
>   ]
> }

no global.json it messed up everything when I try

**Comment by muratg** [comment]
DNX is no longer supported. I recommend moving to ASP.NET Core RC2 bits with dotnet CLI.
