### ISSUE TITLE
'HelloWorld' does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by edcastanohunter** [aspnet/dnx#3421]
I got this error: 'HelloWorld' does not contain a static 'Main' method suitable for an entry point

this are my files:

```
project.json
{
    "frameworks": {
        "dnx451": {}
    }
}
```

program.cs

```
public class program
{
    public static void Main(string[] args)
    {
        System.Console.WriteLine("Hello World");
    }

}

```

when I run dnvm list 

Active Version           Runtime Architecture OperatingSystem Alias

---

```
   1.0.0-rc1-update2 clr     x64          win
```
-    1.0.0-rc1-update2 clr     x86          win             default
     1.0.0-rc1-update2 coreclr x86          win

Could anyone help me?

**Comment by colhountech** [comment]
Go to http://dot.net and download the new dotnet core bits. 

DNX

This repository is obsolete and no longer used or maintained.

DNX and DNVM have been replaced by the new .NET CLI. See:

http://dotnet.github.io/getting-started/
http://github.com/dotnet/cli

As a result, we're not accepting anymore changes to this project. Please file any new issues on http://github.com/dotnet/cli.
