### ISSUE TITLE
To many files are watched running project from source

### ISSUE THREAD

**Issue by Alxandr** [aspnet/dnx#365]
Currently, the FileSystemWatcher is setup to watch everything that ends with `.cs` regardless of whether it's included in the compilation or not. So if I create a project `MyProject` with the files `A.cs` and `B.cs` and set in my `project.json` that only `A.cs` should be included in the compilation, the application will still exit if I change `B.cs` when it's running.

The code that sets up the watching can be found here: https://github.com/aspnet/KRuntime/blob/590d1a788592fef61b1394fd28e5fc7e98da5aaf/src/Microsoft.Framework.Runtime.Roslyn/RoslynCompiler.cs#L74

The way this should be change would probably be to expose the globs to the watcher, and watch the directory instead, and if anything changes match it against the glob and if it's a match, then notify the `IApplicationShutdown` event.

**Comment by davidfowl** [comment]
watcher dead
