### ISSUE TITLE
Clean up rules around what is a valid dependency version in the project.json file

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#438]
The current rules are too fuzzy and need to be more clearly defined. Today we have 3 kinds of references:

- **SDK references** - These are reference assemblies or things in the GAC. Things like System.Data on the full CLR or System.Runtime when targeting a PCL target framework.
- **Project references** - These are references to other projects (self explanatory really)
- **Package references** - References to nuget packages

Today we allow `""` for project dependencies since versions don't matter for projects. We also allow it for SDK references so you don't have to know what version System.Data actually is. This leads to ambiguity so we're going to stop allowing empty versions:

```JSON
{
  "dependencies": {
    "ClassLibrary1": "1.0.0-*",
    "Newtonsoft.Json": "5.0.8"
  },  
  "frameworks": {
    "net45": { 
      "dependencies": {
        "System.Data": "4.0.0.0"       
      }
    }
  }
}
```

**ClassLibrary1** - This is an example of a project reference. The version is ignored completely for source references. Whatever version of the source you have as  project reference will be used.
**System.Data** - This is an SDK reference for .NET 4.5, if there's no version 4.0.0.0 on this platform this will be an error
**Newtonsoft.Json** - This is a package reference

**Comment by davidfowl** [comment]
New set of rules:

Dependencies can have a specific type or by "any". Within the specific type certain fallback orders are allowed:

Project -> []
Package -> [Project]
Framework/Gac assembly -> []

Any means the dependency can come from anywhere

We need a generic way of specifying the type of dependency (type is already taken to mean things like dev, build and shouldn't be confused with this).

```JSON
{
    "dependencies": {
        "A": "1.0.0"
    }
}
```

A is of type any. If it's not a project then it will be considered a package and search for in the configured feeds when restoring.

**Comment by muratg** [comment]
Current decision from the design meeting:

```JSON
{
   "dependencies": {
        "A": "1.0.0-*",
        "B" : { "version": "1.0.0-*", "target": "package" },
        "ClassLibrary12" : { "target": "project" },
        "ClassLibrary34" : { "target": "project" }
    }
}
```
