### ISSUE TITLE
Custom nuspec files

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#45]
Projects should be allowed to supply their own nuspec file. This would light up many NuGet features that are currently not possible.

**Scenario 1**
The xunit.core project needs to include additional files for the TestDriven.Net runner. This includes two assemblies that need to be in the lib folder, but should not be referenced by consuming projects.

**Scenario 2**
The Microsoft.Data.SQLite project also needs to include the native sqlite3.dll library.

**Comment by Fosol** [comment]
It's my experience that don't include a half feature unless you provide a simple way to override it.  What's the simple way to configure what is packaged from our project?

How do I have the project build and place files to the output folder but lets me do the actual nuget package stuff?

**Comment by anurse** [comment]
You can always use `dnu build` to compile assemblies and then use the traditional `nuget pack` command.

**Comment by NullVoxPopuli** [comment]
nuget pack doesn't seem to work for me. 

I get the following:

```

WARNING: 2 issue(s) found with package 'csharp-extensions'.

Issue: Assembly outside lib folder.
Description: The assembly 'bin\Debug\dnx46\csharp-extensions.dll' is not inside the 'lib' folder and hence it won't be a
dded as reference when the package is installed into a project.
Solution: Move it into the 'lib' folder if it should be referenced.

Issue: Assembly outside lib folder.
Description: The assembly 'bin\Debug\dnxcore50\csharp-extensions.dll' is not inside the 'lib' folder and hence it won't
be added as reference when the package is installed into a project.
Solution: Move it into the 'lib' folder if it should be referenced.
```

Why doesn't it copy to the lib folder? and why, when I move those folders (dnxcore50 and dnx46) to lib, does it still not work? (still shows those warnings)
