### ISSUE TITLE
Check for full semantic version when wildcard is specified in project.json

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnx#455]
Currently we allow wildcard to specified in the project.json for packages only for the formats                         

          [max].[min].[patch]-[build]

We do not throw an error if the full semantic version is not specified in the project.json file. For example "1.0-&#42;" does not thrown an error and is resolved to anything 1.0.0-&#42;. I believe this confusing to the users as it suggests that "1.0-&#42;" might resolve to "1.0.&#42;" as well. 

Ideally we should throw an error if the full version is not specified

**Comment by davidfowl** [comment]
Parsing has been improved in NuGet itself. The new runtime should take care of this
