### ISSUE TITLE
Merge NuGet.Config into global.json

### ISSUE THREAD

**Issue by thaiphan** [aspnet/dnx#460]
Hi there,

I was thinking that it might be a good idea to merge NuGet.Config into the global.json file. This will allow you can do stuff like the following:

```json
{
    "sources": ["src"],
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/microsoft/windows.git"
        },
        {
            "type": "nuget",
            "url": "https://www.myget.org/F/aspnetvnext/api/v2"
        },
        {
            "type": "nuget",
            "url": "https://nuget.org/api/v2/"
        }
    ]
}
```

**Comment by glennc** [comment]
@davidfowl ping so you consider this in the stuff you are working on at the moment.

**Comment by yishaigalatzer** [comment]
We need to see how this fits e-e, lets discuss as part of nuget 3.2, we also need to talk side by side and inheritance scenarios with nuget.config.

I also want to understand the upside, all I see is moving the file format around
