### ISSUE TITLE
kpm restore - Dependency graph at the end should be more readable

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#466]
With latest bits, the dependency graph gets printed at the end of kpm restore - after 'Restore complete'. 

We should add some description here to explain that this is the dependency graph that's getting printed. This is not easily readable right now, it'll be nice if we can also format the output better so that it's more readable.

![image](https://cloud.githubusercontent.com/assets/8246794/3675475/0ee1d766-127f-11e4-887c-1272bda5af16.png)

**Comment by davidfowl** [comment]
We have `kpm list` now
