### ISSUE TITLE
Allow kpm pack not to pack packages

### ISSUE THREAD

**Issue by troydai** [aspnet/DNX#468]

**Comment by glennc** [comment]
@troydai what?

**Comment by troydai** [comment]
Ah, this was filed while building the performance infrastructure. When `kpm bundle`  (then `kpm pack`) it will copy the packages from `.k/packages` folder to the application's app root. It will be helpful to enable skip the copy and just pack the other contents because in performance testing environment all packages are concentrated under `KRE_PACKAGES`.

**Comment by troydai** [comment]
It is not needed by Perf automation any more. I'll close it.
