### ISSUE TITLE
Make it possible to build design time plugins

### ISSUE THREAD

**Issue by glennc** [aspnet/dnx#499]
We have two plugins today, one for Razor and one for testing.

We should be able to add a tooling dependency package and have the design time host pick them up and use them at dev time.

@davidfowl will add more specifics

**Comment by NTaylorMullen** [comment]
I've gone ahead and completed the `IPlugin` extensibility points to provide `DesignTimeHost` plugins. Next thing that is needed is to provide a way to reference the plugins in `project.json` without causing circular dependencies.

**Comment by NTaylorMullen** [comment]
Items that added `IPlugin` support:

378a9042bcf1e17c21fae4548346f00794e0bb3b
4b07a60f981a6bcdf0aa8e2e9e429cf5f84ca9a1

**Comment by davidfowl** [comment]
We did this for razor.
