### ISSUE TITLE
Clean up paths for relative embedded resources

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#502]
If I embed a resource using a relative path:
`"resources": "../../global.json",`
Then it keeps that path as the resource name:
`../../global.json`

Such paths should be scrubbed.

**Comment by victorhurdugaci** [comment]
@Tratcher @davidfowl can you please give a little more context on this issue?

**Comment by Tratcher** [comment]
Open an assembly in ILSpy and look at the names of embedded resources.
