### ISSUE TITLE
kpm restore does not fail when a dependency does not support the target framework

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/dnx#506]
For example, the following project.json says it targets .NET 4.5 and K10 but the EntityFramework.Relational package only supports .NET 4.5.1 (not 4.5). There are no errors during package restore, you just get build errors when you try to build because there is no reference to EntityFramework.Relational.

```JSON
{
  "version": "1.0.0-*",
  "dependencies": {
    "EntityFramework.Relational": "7.0.0-*"
  },
  "frameworks": {
    "net45": {},
    "k10": {}
  }
}
```

BTW, by comparison here is the message generated from NuGet for non-K projects:

```
Install-Package : Could not install package 'EntityFramework.Relational 7.0.0-alpha3-10425'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by ChengTian** [comment]
Agree with @davidfowl .

When you find a dependency that doesn't provide the assembly compatible with your app's target framework, it doesn't mean we should always report an error. Think about metadata/tool packages (e.g. `Microsoft.AspNet.Loader.IIS.Interop`) that don't provide any assembly but you still need them as your dependencies.

So the error should only be reported when you actually need to load an assembly but you cannot find it in the package. There is no way for `dnu restore` to tell this.

I'll talk to Tooling team to check whether we can make something show up in VS.
