### ISSUE TITLE
command and subcommand options should implicitly contain parent options

### ISSUE THREAD

**Issue by lodejard** [aspnet/dnx#547]
`kpm restore --verbose` is not recognized, only `kpm --verbose restore` is

also `kpm restore --help` does not display `-v|--verbose` as an option

in both cases processing the options for a subcommand should continue to loop over options from parent command(s)

**Comment by muratg** [comment]
@lodejard Needed for RC1? And will you have time to do it?

**Comment by davidfowl** [comment]
Irrelevant now ish sorta
