### ISSUE TITLE
Throw when putting an invalid author name

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#560]
This is a negative case, but just trying to cover scenarios.

Create an app and put the authors value as null like below

```
{
    "authors": [ null ]
}
```

Try doing a kpm build. Package is successfully generated. But when opening the package in nuget package explorer i see this error: 

![image](https://cloud.githubusercontent.com/assets/2294732/4003106/416b1f84-2973-11e4-8005-569b6a715f9e.png)

**Comment by StefH** [comment]
Same error occurs when using empty string or empty strings.

```c#
{
    "authors": [ "" ]
}
```

or

```c#
{
    "authors": [ "", "" ]
}
```

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#605

**Comment by muratg** [comment]
This issue was moved to dotnet/cli#607
