### ISSUE TITLE
Using KPM offline should succeed if all dependencies are already available

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#591]
KPM restore fails if run offline (no internet connection), even if all the necessary packages are already installed. KPM restore is a standard build step. This prevents build (& test) from being run offline. This reproduces in any of our repositories.

Expected:
- KPM restore tries to download packages (probably due to wildcard dependencies) and fails, but the failure is suppressed as a warning because all of the required packages are already installed.

Observed:
- KPM restore tries to download packages (probably due to wildcard dependencies) and fails, even though the dependencies are all already installed.

**Comment by jkyadav** [comment]
How to install all the necessary packages by kpm if necessary packages are not install on the machine and nor  present in \User\userName\.kpm\packages folder.

**Comment by ChengTian** [comment]
@jkyadav , simply do `kpm restore` for your project. You can check the usage of `kpm restore` with `kpm help restore`. BTW, `kpm` was renamed to `dnu` recently, so if you find `kpm` is unavailable, use `dnu` instead.

**Comment by jkyadav** [comment]
Hi @ChengTian  I have kpm I tried to restore packages with kpm restore but it throws exception.

**Comment by jkyadav** [comment]
See this even this failing for System.IO as well..

 CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections.Immutable'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections.Immutable'.
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Collections.Immutable'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection.Metadata'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Reflection.Metadata'.
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Reflection.Metadata'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Mvc.TagHelpers'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='Microsoft.AspNet.Mvc.TagHelpers'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Mvc.TagHelpers'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.IO'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Text.Encoding'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Text.Encoding'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Threading.Tasks'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Threading.Tasks'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Globalization'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Globalization'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Reflection'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Reflection'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Collections'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ObjectModel'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.ObjectModel'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.ObjectModel'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Xml.ReaderWriter'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.Extensions'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime.Extensions'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime.Extensions'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime.InteropServices'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime.InteropServices'.
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections.Concurrent'
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections.Concurrent'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='System.Collections.Concurrent'.
Warning: FindPackagesById: System.IO
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
Warning: FindPackagesById: System.Collections.Immutable
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.IO'.
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections.Immutable'.
Warning: FindPackagesById: System.Text.Encoding
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Text.Encoding'.
Warning: FindPackagesById: System.Runtime
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime'.
Warning: FindPackagesById: System.Reflection.Metadata
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Reflection.Metadata'.
Warning: FindPackagesById: System.ObjectModel
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.ObjectModel'.
Warning: FindPackagesById: System.Runtime.InteropServices
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime.InteropServices'.
Warning: FindPackagesById: System.Collections
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections'.
Warning: FindPackagesById: System.Threading.Tasks
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Threading.Tasks'.
Warning: FindPackagesById: System.Text.Encoding
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Text.Encoding'.
Warning: FindPackagesById: System.IO
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.IO'.
Warning: FindPackagesById: System.Reflection.Metadata
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Reflection.Metadata'.
Warning: FindPackagesById: System.Collections.Concurrent
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections.Concurrent'.
Warning: FindPackagesById: System.Collections.Immutable
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections.Immutable'.
Warning: FindPackagesById: System.Runtime.Extensions
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime.Extensions'.
Warning: FindPackagesById: System.Xml.ReaderWriter
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Xml.ReaderWriter'.
Warning: FindPackagesById: System.Globalization
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Globalization'.
Warning: FindPackagesById: System.Runtime.InteropServices
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime.InteropServices'.
Warning: FindPackagesById: System.Threading.Tasks
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Threading.Tasks'.
Warning: FindPackagesById: System.Runtime
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Runtime'.
Warning: FindPackagesById: Microsoft.AspNet.Mvc.TagHelpers
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='Microsoft.AspNet.Mvc.TagHelpers'.
Warning: FindPackagesById: System.Collections
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
  GET https://api.nuget.org/v3/index.json/FindPackagesById()?Id='System.Collections'.
Error: FindPackagesById: System.Collections.Immutable
  Response status code does not indicate success: 400 (One of the request inputs is out of range.).
----------
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (One of the request inputs is out of range.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__61.MoveNext()
----------
Restore failed
Response status code does not indicate success: 400 (One of the request inputs is out of range.).

**Comment by davidfowl** [comment]
Disable the api.nuget.org feed.

**Comment by jkyadav** [comment]
Thanks @davidfowl , its worked but failing now for this ..

kpm : 'npm' is not recognized as an internal or external command,
At line:1 char:1
+ kpm restore
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('npm' is not re...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

What is wrong with this..

**Comment by davidfowl** [comment]
You need to install node and npm

**Comment by jkyadav** [comment]
Thanks @davidfowl  kpm restore worked, but still I am getting npm related error, trying to fix it.
