### ISSUE TITLE
Provide ability to modify compiled .dll files before they're packaged into a .nupkg

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/dnx#621]
We have some scenarios (Authenticode signing, IL rewriting, resource modification, XML Intellisense modification, obfuscation) which require modifying the raw .dll files after they have been compiled but before they're packaged into a .nupkg.

Ideally there would be a compilation hook which gives us all the raw files which we could then modify as needed, then we could return the modified files back to the runtime for them to be put into a .nupkg and a .symbols.nupkg.

At minimum, such a stage would need to provide access to the generated .dll, .xml, and .pdb files so that any or all of them can be inspected or modified.

**Comment by muratg** [comment]
@GrabYourPitchforks does preprocessing feature solve this?

**Comment by GrabYourPitchforks** [comment]
No - none of the scenarios I listed above are covered by the preprocessing feature.

**Comment by davidfowl** [comment]
It will be, we just haven't properly implemented the AfterCompileContext. We also need to add an extra event that happens during packaging.

**Comment by muratg** [comment]
@davidfowl do you want this in RC1?

**Comment by Tasteful** [comment]
Any progress on this?

**Comment by moozzyk** [comment]
Could a prepack script work in this scenario?

**Comment by davidfowl** [comment]
@moozzyk yep! Closing as the CLI now has to handle this
