### ISSUE TITLE
KPM needs a cache cleanup option

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#634]
KPM caches every version in the global package cache. When working with nightly builds this can get huge. KPM needs the one or both of the following options:
1. Clear the entire cache
2. Clear the entire cache except for the latest version of each package.

If you wanted to get really fancy you could do something like:
Clear the entire cache except for the latest version of each package and the direct dependencies of those packages.

**Comment by chmontgomery** [comment]
:+1:

**Comment by ByteBlast** [comment]
:+1:

**Comment by troyschneringer** [comment]
+1

**Comment by tparnell8** [comment]
:+1:

**Comment by bricelam** [comment]
I found similar commands in other package managers:
* [npm prune](https://docs.npmjs.com/cli/prune)
* [bundle clean](http://bundler.io/v1.10/bundle_clean.html)

**Comment by davidfowl** [comment]
Except this is shared packages folder so it's a bit different.

**Comment by bricelam** [comment]
(That's why I was careful to use the word *similar* :wink:)

**Comment by bricelam** [comment]
:trollface: Can't we just keep maintain a `repositories.config` file in there that points back to the individual projects?
