### ISSUE TITLE
kpm bundle switches wwwroot and wwwroot-out should be renamed to webroot and webroot-out

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#635]
The --wwwroot switch of kpm pack is being used to override the 'webroot' folder defined in project.json. 

We think it's a lot easier to understand that if the switches are named --webroot and --webroot-out

Examples:
kpm pack --webroot foo --webroot-out wwwroot

kpm pack --webroot-out wwwroot (Publish from VS needs to use only this option. This is clear that wwwroot is now the output folder name for whatever webroot is specified in web app project.json)

**Comment by Tragetaschen** [comment]
Wouldn't it be more consistent to rename project.json's webroot to wwwroot instead? The situation now is that probably everybody leaves the default of `"webroot": "wwwroot"`, so webroot is really the odd one out.
