### ISSUE TITLE
PackageManager should use System.Net.Http

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#643]
The System.Net.Http package has a `HttpClient` which would be the replacement for `Microsoft.Net.HttpClient`.

**Comment by muratg** [comment]
@ChengTian @pranavkm what's the status of this issue?

**Comment by ChengTian** [comment]
Buggy HttpClient from CoreCLR was preventing this from being done. I will try integrating the latest CoreCLR HttpClient to see whether it usable now.

**Comment by muratg** [comment]
@glennc do we need this in RC1?

**Comment by ChengTian** [comment]
@danroth27 talked to me and we should keep trying to integrate HttpClient from CoreCLR and filing bugs if we can catch any with `dnu restore`. Putting this to `beta6`.

**Comment by ChengTian** [comment]
Still waiting for bug fix from CoreCLR team: https://github.com/dotnet/corefx/issues/2168

The purpose of this task is testing HttpClient on CoreCLR and it is not an urgent issue. Moving to next milestone. @muratg
