### ISSUE TITLE
Improve the error when assembly load failures occur

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#661]
Heres an example of what you see when there's a load error:

```
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: WebListener, Kestrel, run.
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationN
ame, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
```

We don't do enough work to attempt to figure out if the thing typed in was a command or package so we show this generic error when anything fails. 

There are a few cases to cover:

- There's a compilation error (we handle this) already
- When the command name is mistyped
- When the command name is fine but there was a problem executing the command
- When the entry point package is mistyped (same as command name mistyped)
- When the entry point package fails to load

**Comment by vbouret** [comment]
I got this exception while using this option of self-hosting in Visual Studio 2015 Preview (14.0.22310.1)

    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
    }

The error fixed itself by restarting Visual Studio but displaying the InnerException on the Console Output may help the developer diagnose more efficiently the underlying cause.
