### ISSUE TITLE
global.json source entries to accept individual project folders

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#662]
Today an entry in to `"sources"` of `global.json` indicates a folder of projects rather than a project folder. So pointing to a project folder fails to resolve the code in the folder. 

Expectation: this to also accept a folder location as well. 

This will also help the case where I would like to selectively build in the default VS project as well as exclude projects.

**Comment by muratg** [comment]
@Praburaj Can you clarify the scenario a bit?
