### ISSUE TITLE
Add performance testing around kpm restore with Empty template

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#718]
STEPS
1.       New EmptyApp4 using VS
2.       Close VS, delete C:\Users\balach\.kpm folder
3.       Test kpm restore from command-line vs VS
 
ACTUAL

With the work we did in WTE for CTP4, the WTE repo folder (C:\Program Files (x86)\Microsoft Web Tools\Kpm) already has the fully expanded packages. When I talked to Wei about this, he was suggesting that we might still be extracting from the .nupkg, that seems like a bug.

Restore currently takes about 15 seconds. If we remove Scaffolding from Empty template, then restore takes about 8 seconds. 
 
Restore in VS:
```
Restoring packages for C:\Users\balach\documents\visual studio 14\Projects\EmptyApp4\src\EmptyApp4\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.IIS'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.CodeGenerators.Mvc'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.IIS' 414ms
  OPEN C:\Program Files (x86)\Microsoft Web Tools\Kpm\Microsoft.AspNet.Server.IIS\1.0.0-beta1-10416\Microsoft.AspNet.Server.IIS.nuspec
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.CodeGenerators.Mvc' 410ms
…

Installing System.Security.Claims 1.0.0-beta1-10357
  OPEN C:\Program Files (x86)\Microsoft Web Tools\Kpm\System.Security.Claims\1.0.0-beta1-10357\System.Security.Claims.1.0.0-beta1-10357.nupkg
Restore complete, 14560ms elapsed
 ```
Restore in Cmd line: 

![image](https://cloud.githubusercontent.com/assets/8246794/4553438/815da5c6-4e99-11e4-8934-c437419e1842.png)
…
![image](https://cloud.githubusercontent.com/assets/8246794/4553439/8b36a7c8-4e99-11e4-8dab-974258296168.png)

**Comment by glennc** [comment]
@balachir is this still an issue that we need to look at? It's been a while since you created it.

**Comment by troydai** [comment]
@muratg maybe we need to create some performance baseline for common scenario like this?

**Comment by muratg** [comment]
:+1: Changing title to make this a perf. test item.
