### ISSUE TITLE
kpm bundle updates timestamp of unchanged files

### ISSUE THREAD

**Issue by naianacampos** [aspnet/dnx#721]
WTE 10/7

1. Create empty vNext WAP
2. publish
3. make ZERO changes, select file preview in publish dialog

 

[Observed]
the following files has newer timestamp and are going to be re-published
  global.json
  k.ini
  project.json

 

[Expected]
there has been no changes; therefore no files should need to be published.

**Comment by BrennanConroy** [comment]
Currently we are modifying the project.json file to have the correct path for wwwroot.
We generate the web.config with application specific values.
And we make the global.json file with relative path information.

It seems like there would be a lot of performance hits if we added the logic to parse these files and see if everything is correct inside them.
@muratg

**Comment by muratg** [comment]
@davidfowl is it worth the potential perf penalty to read the files, and check if they're correct and not update them if not needed?

**Comment by davidfowl** [comment]
Moving
