### ISSUE TITLE
Projects referencing contract version greater than existing have very poor error experience

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#726]
# Issue:
I hit this error a fair bit moving my older K projects to newer ASP.NET VNext since some of the contract versions have actually dropped over time (as the versions they had had not shipped).
Basically, when the version specified of a contract is too LOW (i.e. lower than exists), it unifies forward to the next version which is useful.  When it's too high, the only feedback the developer gets in VS is:"The program '[PID] klr.exe' has exited with code 1 (0x1)."  
Some kind of specific "Unable to resolve this or unify to higher version" message would be great.

# Repro:
1) Create new ASP.NET VNext Console app
2) update project.json to contain the following:
```json
{
    "dependencies": {
    },
    "frameworks" : {
        "aspnetcore50" : { 
            "dependencies": {
            "System.Console": "4.0.0.0",
            "System.IO.FileSystem": "4.0.10.0"
        }
    }
}
```

Initially filed in http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/1041931

**Comment by davidfowl** [comment]
Dependent on how we solve #2638

**Comment by muratg** [comment]
Good to close @davidfowl ?
