### ISSUE TITLE
Unable to load resources when they are under a namespace other than the assembly name

### ISSUE THREAD

**Issue by kanchanm** [aspnet/dnx#738]
1. Create a vNext Class library e.g. EmbedResourceTest
2. Add a resx file 
3. Change the namespace in the corresponding designer.cs file to EmbedResourceTest.Core
note, you need to change here too -

```
global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbedResourceTest.Core.EmbedMoreResources", typeof(EmbedMoreResources).GetTypeInfo().Assembly);
```

Try loading the resource, this will fail. If you ignore the namespace and change the above to not include the namespace it works fine. 

```
global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbedResourceTest.EmbedMoreResources", typeof(EmbedMoreResources).GetTypeInfo().Assembly);
```

This is a very common pattern and it worked in the old world so although there is a workaround it is super painful to keep changing this when you are porting your application to vNext and have large number of resource files (which some projects do).

**Comment by davidfowl** [comment]
@muratg @Eilon I wanna change our resource format for beta3

**Comment by bojanrajkovic** [comment]
This also breaks trying to use EF6 migrations, as the embedded filenames for generated .resx files don't match what EF is looking for.

**Comment by muratg** [comment]
@davidfowl rc1?
