### ISSUE TITLE
being able to pass appbase location through k

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/dnx#747]
I wasn't able to find a way to pass the appbase location to `k`. I found out that klr.cmd looks for an environment variable called `K_APPBASE` and if it's there, it uses it.

However, It would be nice to have a way to pass this through `k`.

**Comment by davidfowl** [comment]
This is fixed now. We're basically obsoleting k.cmd and replacing it with a `dotnet` executable. 

You can run `dotnet "c:\dev\foo\bar" test`
