### ISSUE TITLE
Show a warning if KRE CoreCLR version don't match with project.json specified version

### ISSUE THREAD

**Issue by xqiu** [aspnet/dnx#768]
From: David Fowler

Nope, the contracts are pretty much part of the SDK and aren't split out right now. We would probably show an error if they don't match but we don't today. 
________________________________________
From: Xinyang Qiu
 
It seems confusing though.  VS project.json referencing a version of CoreCLR, but when running it through console, it uses CoreCLR for the current KRE environment.  Is it possible to enforcing loading of CoreCLR references based on project.json define?

**Comment by muratg** [comment]
@davidfowl/@lodejard ping.  Want to get this in RC1 or is it OK to backlog? Please assign the milestone accordingly.
