### ISSUE TITLE
Default environment should be "production"

### ISSUE THREAD

**Issue by blowdart** [aspnet/dnx#777]
This makes any pivot for development fail by default, which would make some decisions safer (such as detailed errors).

**Comment by glennc** [comment]
Not sure of all the implications of this, assigning it to RC1 to find out.

**Comment by rustd** [comment]
We met and we want to do this for Beta4. VS would set it to Development

**Comment by blowdart** [comment]
Security win!

**Comment by muratg** [comment]
I believe tooling and runtime changes required are still pending for this change. Based on this, moving to Beta5.

**Comment by muratg** [comment]
Tracked here: https://github.com/aspnet/Hosting/issues/272

Closing this one.
