### ISSUE TITLE
Using kpm appears to sometimes disable the main nuget feed

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/dnx#782]
This morning, package restore started failing for me saying that it couldn't resolve a handful of packages. Turns out, the main nuget feed had been disabled on my machine. This was strange as my machine had only just been completely rebuilt (new OS Install) and latest KVM/VS/WTE installed.

Turns out, there have been reports of this happening before from other users (ASP.NET Insiders) so it appears it's not an isolated case. No idea on specific repro unfortunately.

**Comment by bricelam** [comment]
(See https://nuget.codeplex.com/workitem/4397)
