### ISSUE TITLE
K Run and KPM Pack for KConsole Silently fail when application path is too long

### ISSUE THREAD

**Issue by lukewaters** [aspnet/dnx#823]
This is a difficult problem to troubleshoot and solve because no error message is given.  With KRE_TRACE=1 the only output we get is 
```
C:\source\GitHub\Perf\artifacts\server\apps\EntityFramework.CUD.Tests.coreclr> .\Start.cmd
Loaded Module: klr.core45.dll
Found DLL Export: CallApplicationMain
```

the contents of the start.cmd mentioned above are:
```
@"%~dp0approot\packages\KRE-CoreCLR-x86.1.0.0-beta2-10619\bin\klr.exe" --appbase "%~dp0approot\src\EntityFramework.CUD.Tests" Microsoft.Framework.ApplicationHost Start %*
```

**Comment by muratg** [comment]
@lukewaters Does this still repro?

**Comment by BrennanConroy** [comment]
I made a PR, and then we were going to use STL instead, neither of which has gone through yet.
https://github.com/aspnet/dnx/pull/1363

**Comment by davidfowl** [comment]
@moozzyk did your changes resolve this?

**Comment by moozzyk** [comment]
Looks like a dupe of #1363 which is resolved - we now use stl to do concatenate paths and build TPA list.
