### ISSUE TITLE
kpm pack does not include System.ComponentModel.Annotations on Mono

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnx#840]
Consider a sample Mvc app on Mono. Doing 'kpm pack' on it and then running the package on Windows machines throws an error saying cannot resolve 'System.ComponentModel.Annotations 4.0.10-beta-22230'. If you check the approot/packages, this package is not included.

If you do 'kpm pack' on the same application in Windows and then run the package on Mac, this runs fine because System.ComponentModel.Annotations is included in the package. 

We need to investigate why this package is missed on Mono. Verified with KRE 1.0.0-beta1-10659

**Comment by muratg** [comment]
Removing duplicate label since we have decided to keep this one open.
