### ISSUE TITLE
kpm 'add' removes comments from project.json file and reformats it

### ISSUE THREAD

**Issue by kichalla** [aspnet/dnx#841]
1. Create a new project in VS using the regular ASP.NET 5 web application template...check it in Git source control(would be easy to compare the differences between versions later)
2. At command line do, `kpm add "Microsoft.AspNet.Mvc.TagHelpers" 6.0.0-beta1`
3. project.json file should be changed now
4. compare the difference between the versions in VS

Example:
![image](https://cloud.githubusercontent.com/assets/6559784/4867749/5d5cc970-6138-11e4-97b6-81658f2239d5.png)

**Comment by muratg** [comment]
Not valid anymore.  https://github.com/aspnet/Announcements/issues/24
