### ISSUE TITLE
Allow additional files in the nupkg

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#848]
Similar to a nuspec file, project.json should allow you to specify additional files to include in the nupkg. I imagine a format like the following.
```JSON
{
    "files": {
        "tools/EntityFramework.psd1": "tools/",
        "tools/EntityFramework.psm1": "tools/",
        "tools/init.ps1": "tools/"
    }
}
```
We currently do this post-build on the following packages.
* EntityFramework.Commands
* Microsoft.Data.SQLite

**Comment by bricelam** [comment]
Ping... [our workaround](https://github.com/aspnet/DataCommon.SQLite/blob/dev/makefile.shade#L37-L75) depends on an external-to-DNX solution that leverages `WindowsBase.dll`. This means you can't build a valid `Microsoft.Data.Sqlite` package without Desktop .NET/Mono.

**Comment by muratg** [comment]
@davidfowl I don't think you're looking into this.  Could you move to another milestone (or in 1.0.0 backlog?)

**Comment by anurse** [comment]
I prefer putting the destination on the left, and I'd like to see if we can get globbing in there. We'll be talking about this in the design meeting today.

**Comment by bricelam** [comment]
W00t! We have workarounds [in EntityFramework](https://github.com/aspnet/EntityFramework/blob/dev/makefile.shade#L58-L104) and [in Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/makefile.shade#L30-L60) for this...

**Comment by anurse** [comment]
Initial design notes. We're going to iterate on it tomorrow. /cc @davidfowl 

```json
{
    "packageFiles": {
        "dest": "src"
    }
}
````

I think that the "source" file specifier needs to be able to be an array. Basically, if the thing on the right ends up evaluating to multiple file names, the thing on the left is a folder. Otherwise, the thing on the left is a file and must have the full name of the file. Because the body of this property is a JSON dictionary, we are restricted to only having one entry per destination.

```json
{
    "packageFiles": {
        "test": ["a.txt", "b.txt"],
        "README.md": "docs/README.md"
    }
}
```

**Comment by MiguelAlho** [comment]
This is just about how to add files to the generated nupkg, but not about how they will be consumed, right?

**Comment by davidfowl** [comment]
@MiguelAlho That's correct.

**Comment by anurse** [comment]
Additional design notes: 

* We want the project to be able to fully behave like a package, so any files specified in this section should be available when referencing the project. For example, if a native binary is specified using this property, that binary should be placed in the correct lock-file section.
