### ISSUE TITLE
StackOverflow exception thrown if language is set to the project you're building

### ISSUE THREAD

**Issue by Alxandr** [aspnet/dnx#855]
Title was a bit hard to write, but let me explain the issue:

I have a project, named `FSharpSupport` ([project.json](https://github.com/YoloDev/FSharpSupport/blob/master/src/FSharpSupport/project.json)) which has `FSharpSupport` listed as it's language assembly like this:

```js
  "language": {
    "name": "F#",
    "assembly": "FSharpSupport",
    "projectReferenceProviderType": "FSharpSupport.FSharpProjectReferenceProvider"
  }
```

The reason for this is that I use FSharpSupport to build FSharpSupport. This generally just works, because I supply `kre` with the previous compiled version of FSharpSupport using `--lib`. However, I had a short period with a bug in my build-script, which resulted in `kre` not finding the previous version of FSharpSupport, a `StackOverflowException` is thrown. However, due to how this exception is thrown, windows pops up with a dialog asking me if I want to debug the issue, instead of the application just exiting with an error code. This causes builds on my build-server to hang indefinitely.

**Comment by muratg** [comment]
Related: language support WIs

**Comment by davidfowl** [comment]
CLI mitigates this it's all out of proc
