### ISSUE TITLE
Avoid NRE for `kpm.cmd help unsupported`

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#862]
`kpm.cmd unsupported` displays an Exception containing
```
TODO: Error: unrecognized argument 'unsupported'
```
Expect similar output from `kpm.cmd help unsupported` but that command instead displays
```
System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by BrennanConroy** [comment]
71cb0ee4c1a01efe4fdae5ef9d58e839604fe1d3
