### ISSUE TITLE
Cannot reference portable assembly in aspnet50 projects

### ISSUE THREAD

**Issue by maumar** [aspnet/dnx#867]
Repro:

Create portable class library with the following project.json (portable + core):

```
{
    "version": "1.0.0-*",
    "dependencies": {
    },

    "frameworks": {
        "aspnetcore50": {
            "dependencies": {
                "System.Runtime": "4.0.20-beta-22231"
            }
        },
        ".NETPortable,Version=v4.6,Profile=Profile151": {
            "frameworkAssemblies": { "System.Runtime": "4.0.10.0" }
        }
    }
 }
```

now try referencing it in a console application for aspnet50 and core. Json would look like this:

```
{
    "version": "1.0.0-*",
    "dependencies": {
        "MyLibrary": ""
    },
    "commands": {
        "run": "run"
    },
    "frameworks": {

        "aspnet50": { },
        "aspnetcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-22231"
            }
        }
    }
}
```

This doesn't work, throwing the following exception:

System.InvalidOperationException: Failed to resolve the following dependencies f
or target framework 'Asp.Net,Version=v5.0':
   gac/System.Runtime 4.0.10.0

Searched Locations:
  C:\Projects\ConsoleApp2\src{name}\project.json
  C:\Projects\ConsoleApp2\test{name}\project.json
  C:\Users\maumar.kpm\packages{name}{version}{name}.nuspec
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\
v4.5.3{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\
v4.5.3\Facades{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_32{name}{version}{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL{name}{version}{name}.dll

Try running 'kpm restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

I would expect this to work, we should be loading aspnet50 library for system.runtime in this case

**Comment by StefH** [comment]
Hi @Maumar and @davidfowl,

Can you please share the documentation on how to define a PCL in the project.json? (e.g. ".NETPortable,Version=v4.6,Profile=Profile151")

And what's the compiler directive to use in code when dealing with PCL specific statements? Is that **PORTABLE**?

And why is #827 related to this?

**Comment by davidfowl** [comment]
I wouldn't recommend creating portable class libraries this way. We also don't make compiler directives when you use the PCL targets.

**Comment by StefH** [comment]
Is this also not planned for the future release?
