### ISSUE TITLE
Support for text-templating-like functionality

### ISSUE THREAD

**Issue by lajones** [aspnet/dnx#879]
I was trying to add a .tt file and generate the results I would have gotten before by using the TextTemplatingFilePreprocsesor Custom Tool - see https://github.com/aspnet/Tooling/issues/150

Had a chat with @lodejard about this and apparently there are a number of issues this brings up including producing a file generator using ICompileModule, a "preprocess" step in the build, communication between VS and DesignTimeHosting and intellisense.

This issue is to keep track of that.

**Comment by davidfowl** [comment]
Closing this as it could be another command line tool
