### ISSUE TITLE
Expose project build configuration in scripts section of project.json

### ISSUE THREAD

**Issue by troydai** [aspnet/dnx#887]
There are a few variables surfaced in the [scripts section of project.json](https://github.com/aspnet/Home/wiki/Project.json-file#scripts). However, the current build configuration is not among them. 

The variable is useful in such a scenario: copying the output to a folder other than default output
``` json
{
  "scripts":{
    "postbuild": [
      "xcopy /F /Y /I bin\\%project:BuildConfiguration%\\* C:\\Playground"
    ]
  }
}
```

It worth to mention that `kpm build` support multiple configurations in one build run. If this variable is exposed, the scripts need to be executed multiple times to match each configuration.

**Comment by Eilon** [comment]
In the design meeting we need to discuss whether doing https://github.com/aspnet/dnx/issues/2450 would eliminate or at least alleviate the need for the feature in this issue.

**Comment by glennc** [comment]
Will run the *build *pack method per configuration and pass the configuration in.

**Comment by victorhurdugaci** [comment]
Assigning to Pawel because he needs this to unblock his other change

**Comment by apawsey** [comment]
Hi guys,

Can we actually run a different script depending on build configuration or architecture now then?  If so how?

Thanks.
