### ISSUE TITLE
Inconsistent coloring of "kpm pack" output text on OSX

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#888]
Run `kpm pack` on OSX

![screen shot 2014-11-12 at 2 45 27 pm](https://cloud.githubusercontent.com/assets/1383883/5020491/bad3b574-6a7e-11e4-8ceb-4fe49fbbbeaf.png)

**Comment by glennc** [comment]
Assigning to 1.0 milestone. We will take it sooner if @borgdylan sends a PR for it though :)

**Comment by borgdylan** [comment]
With Mono 4.0+ the color improves automatically i.e. it is consistent enough. This issue might  be an expired one then with no PR needed.

![screenshot from 2015-03-13 19 11 53](https://cloud.githubusercontent.com/assets/7761010/6644515/de59b1ac-c9b4-11e4-84ae-c791c88cd382.png)

**Comment by borgdylan** [comment]
To make stuff work in general with the latest bits Mono 4.1 or later is needed anyway.

**Comment by glennc** [comment]
Ok, I am going to close this then. We can always re-open or create a new one if it makes sense to.
