### ISSUE TITLE
Add first class Emit to IMetadataProjectReference

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#922]
So that we don't have to do this:

https://github.com/aspnet/KRuntime/blob/dev/src/klr.hosting.shared/LoaderEngine.cs

**Comment by davidfowl** [comment]
We need this for CTP5 since we removed the reference assembly emit. This should replace that. You should be able to emit without putting anything on disk. This Emit should support producing an assembly stream and a symbol stream.

**Comment by muratg** [comment]
If this should go in beta 5, we need to do it today or tomorrow.

**Comment by troydai** [comment]
I believe this won't make into beta5.

**Comment by davidfowl** [comment]
Moved to the backlog, this isn't important right now.

**Comment by davidfowl** [comment]
Deprecated
