### ISSUE TITLE
Need a Resources.tt replacement (or reanimation)

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#93]
With updates to new tooling, we've lost the ability to generate Resources.designer.cs from Resources.resx.  It's not just that Resources.tt no longer shows up in the Properties directory: Add the file manually (as a link to the packages\Korebuild\build file) and it just shows up as regular Content.

This is an urgent requirement since we update Resources.resx files frequently.  A manual workaround would help for now.

**Comment by davidfowl** [comment]
I believe the replacement for this will be global commands (tools). Basically turning each of the things that were single file generators and turning them into command line tools.

**Comment by davidfowl** [comment]
<script>alert('testing')</script>

**Comment by davidfowl** [comment]
<script>alert('testing')</script>
