### ISSUE TITLE
DTH should return .csproj file instead of wrapper project.json for references

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#945]
If k projects reference csproj, right now DTH sends the wrapped project.json in the references message. It should instead send the .csproj that's being wrapped.

**Comment by muratg** [comment]
@davidfowl can this be closed?

**Comment by muratg** [comment]
@PradeepKadubandi is this OK to close?

**Comment by muratg** [comment]
Looks like Dependencies issue is also fixed after Fowler's check-ins.  Closing this one.
