### ISSUE TITLE
Package Manager Console hook for ASP.NET 5 projects

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#952]
If a user is developing on Windows in Visual Studio, it's clear from aspnet/EntityFramework#1196 that they still expect to be able to use the Package Manager Console with ASP.NET 5 projects.

The piece that's missing for us to light up the Entity Framework PowerShell commands on ASP.NET 5 projects is a hook to import our PowerShell module.

For *.csproj projects this is as simple as calling `Import-Module` inside of [tools/init.ps1](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/tools/init.ps1#L7).

**Comment by davidfowl** [comment]
Needs to be moved to the tooling issues.

**Comment by bricelam** [comment]
Re-openeing; @barrytang says it's a runtime issue.

**Comment by rowanmiller** [comment]
Moved to the NuGet repo https://github.com/NuGet/Home/issues/634

**Comment by ToddThomson** [comment]
:+1: This would be a convenience and a time saver for me. I very much would like to make the move to EF7, but all the pieces I need are not all there and from all indications ( the backlog ) it will be sometime before EF7 is ready to take over from EF6.

**Comment by vossad01** [comment]
I think this may need to be reopened.  It was closed for the move to NuGet, but the NuGet item is closed with guidance to talk to DNX.

NB. I have not encountered the need for this issue yet, just reporting the issue with the Issues.
