### ISSUE TITLE
Ability to strong-name assemblies

### ISSUE THREAD

**Issue by bricelam** [aspnet/dnx#963]
`kpm buid` should allow the assemblies to be strong-named **at least** for non-ASP.NET frameworks if nothing else.

**Comment by Eilon** [comment]
@glennc @davidfowl @bricelam @muratg @lodejard re-opening this based on our recent discussions.

**Comment by muratg** [comment]
:+1:

**Comment by davidfowl** [comment]
We can do this now everywhere thanks to https://github.com/dotnet/roslyn/commit/f591db040a09b0d958b628a4183a332bea6834c1

**Comment by muratg** [comment]
YAY!

**Comment by muratg** [comment]
@davidfowl still Beta5?

**Comment by bricelam** [comment]
As far as the original report is concerned, this is resolved by #2004

**Comment by muratg** [comment]
Yup, @moozzyk essentially took over this while he's working on servicing.
