### ISSUE TITLE
How does "kpm pack" handle web.Debug.config and web.Release.config

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnx#980]
In addition to `web.config`, we have `web.Debug.config` and `web.Release.config` in MusicStore. Current `kpm pack` always copies `web.config` to destination and ignores the other two files.

@lodejard  @davidfowl @GrabYourPitchforks , do we want to discard `web.Debug.config` and `web.Release.config`? Or we want to change `kpm pack` to support the two web.config files (maybe with `kpm pack --configuration`).

**Comment by muratg** [comment]
This behavior changed quite a bit.  Closing
