### ISSUE TITLE
Runtime identification is inconsistent between KVM and KPM pack

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#983]
To select the current runtime with KVM you do:
`KVM use 1.0.0-rc1-10770 -x86 -runtime CLR`

However, with KPM pack it looks like this:
`KPM pack --runtime KRE-CLR-x86.1.0.0-rc1-10770`

The format difference leads to confusion when working with both tools.

If I use one format with other command I get less than helpful errors:
```
C:\temp\HelloWeb>kpm pack --runtime 1.0.0-rc1-10770
Unable to locate runtime '1.0.0-rc1-10770'
```
```
C:\temp\HelloWeb>kvm use KRE-CLR-x86.1.0.0-rc1-10770
Cannot find KRE-CLR-x86.KRE-CLR-x86.1.0.0-rc1-10770, do you need to run 'kvm install KRE-CLR-x86.1.0.0-rc1-10770'?
```

The KVM docs are better at explaining what format to use than the KPM pack docs are. At the very least the KPM pack docs and errors need improvement. Anything that could be done to unify the format would be better.

**Comment by muratg** [comment]
dup https://github.com/aspnet/dnx/issues/1890
