### ISSUE TITLE
KPM pack should warn about "webroot": "."

### ISSUE THREAD

**Issue by rynowak** [aspnet/dnx#986]
If you set `"webroot": "."` in a project.json, kpm pack will fail. If you keep trying, it will try to keep recursively packing the same directory.

This is a relatively easy mistake to make for someone that's new, we might want to blow up if you do this.

**Comment by muratg** [comment]
I'll see if this repro's still.

**Comment by muratg** [comment]
@davidfowl where will this change happen?  FYI, you haven't modified the milestone (Backlog).

cc @anurse

**Comment by davidfowl** [comment]
I don't know if we have a place to do this anymore.

**Comment by muratg** [comment]
Wherever publish code will live in?
